Some bug fixed for shader validation and perf improvement
KhronosGroup/Vulkan-ValidationLayers pull request #2226
Opened 2020-10-13 17:11 UTC by locke-lunarg

The index of Images or Samplers in shader might not be a constant. Skip it if the index is not a constant.

This bug fix is related to 
VUID-vkCmdTraceRaysIndirectKHR-None-02702
If the VkPipeline object bound to the pipeline bind point used by this command accesses a VkSampler object that uses unnormalized coordinates, that sampler must not be used to sample from any VkImage with a VkImageView of the type VK_IMAGE_VIEW_TYPE_3D, VK_IMAGE_VIEW_TYPE_CUBE, VK_IMAGE_VIEW_TYPE_1D_ARRAY, VK_IMAGE_VIEW_TYPE_2D_ARRAY or VK_IMAGE_VIEW_TYPE_CUBE_ARRAY, in any shader stage.

2020-10-13 22:40 UTC, locke-lunarg commented
The second commit is to improve performance. It moved that looking for samplers when only it needs.

2020-10-20 22:53 UTC, jzulauf-lunarg requested changes
There's a map lookup at a constant key in the inmost loop that needs to be pulled out.  Then re-review.

2020-10-20 22:53 UTC, jzulauf-lunarg commented on layers/core_validation.cpp
> +                    result |= ValidateDrawState(bind_point, descriptor_set, delta_reqs, state.per_set[setIndex].dynamicOffsets,
I'm willing to bet this is a big part of the performance hit.  We're passing in bind_point instead of a `const LAST_BOUND_STATE & ` ... and then in the in most loop, looking up the LAST_BOUND_STATE in the same map, at the same key over and over... if you need the CB's last bound state pass it in ... or look it up *once* at the top of the per descriptor set loop.

2020-10-20 22:53 UTC, jzulauf-lunarg commented on layers/buffer_validation.cpp
> +    if (set >= last_bound_it->second.per_set.size()) {
from a style standpoint I find iterator->std::pair notation terrible.  

const LAST_BOUND_STATE & last_bound_state = last_bound_it->second;

the use that from then on.

BUT... I don't think this function should exist at all anyway... (or at least not in it's current form) see comment below.

2020-10-20 23:01 UTC, jzulauf-lunarg commented on layers/core_validation.cpp
> +                    result |= ValidateDrawState(bind_point, descriptor_set, delta_reqs, state.per_set[setIndex].dynamicOffsets,
And/or, if we want to make look ups of the `lastBound[bind_point]` fast create  an LvlBindPoint enum that maps VK_PIPELINE_BIND_POINT_RAY_TRACING_KHR to 3 (with  GRAPHICS and COMPUTE left as is) and convert `lastBound` to a std::array<LAST_BOUND_STATE,3>.

2020-10-21 00:25 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +            auto it = sampler.second.find(key);
Is there some way to avoid this find?

2020-10-21 00:31 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +                descriptorset->GetDescriptorFromBinding(sampler.first.sampler_slot.second, sampler.first.sampler_index);
This is also a find (under several layers).

2020-10-21 10:45 UTC, jzulauf-lunarg approved these changes
Consider my comments advisory for the followup performance work.  Okay as is.

2020-10-21 15:37 UTC, locke-lunarg commented
@jzulauf-lunarg  Thanks. Great advices.

2020-10-22 00:35 UTC, merged