syncval: Rework sync model to correct order independence of barrier batches and subpass dependencies
KhronosGroup/Vulkan-ValidationLayers pull request #2259
Opened 2020-10-24 16:36 UTC by jzulauf-lunarg

Fixes errors in barrier application model s.t. unintended dependency chains are no longer created for barriers within the same "batch" whether a barrier command or subpass definition.

Includes clean of subpass transition/load store validation/record as they were affected by the model changes, and the plumbing needed to support them.

2020-10-26 15:43 UTC, jeremyg-lunarg commented on layers/synchronization_validation.cpp
> +bool ResourceAccessState::IsWARHazard(VkPipelineStageFlagBits usage_stage, SyncStageAccessFlagBits usage) const { return false; }
Is this ever going to be used, or be anything other than return false?

2020-10-26 15:45 UTC, jeremyg-lunarg commented on layers/synchronization_validation.cpp
> +// resolve the pendinging state. Suitable for processing Image and Buffer barriers from PipelineBarriers or Events
pending

2020-10-26 15:47 UTC, jeremyg-lunarg commented on layers/synchronization_validation.h
> +    //                       bool layout_transition);
remove commented out declaration?

2020-10-26 16:25 UTC, jeremyg-lunarg commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +    // m_errorMonitor->VerifyNotFound();
should this be uncommented or removed?

2020-10-26 21:09 UTC, jeremyg-lunarg requested changes
found some typos / commented out code...

2020-10-26 21:09 UTC, jeremyg-lunarg commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +    // m_errorMonitor->VerifyNotFound();
Should this be uncommented or removed?

2020-10-26 21:09 UTC, jeremyg-lunarg commented on layers/synchronization_validation.cpp
> +// resolve the pendinging state. Suitable for processing Image and Buffer barriers from PipelineBarriers or Events
pendinging

2020-10-26 21:09 UTC, jeremyg-lunarg commented on layers/synchronization_validation.h
> +    // void ApplyImageBarrier(const IMAGE_STATE &image, const SyncBarrier &barrier, const VkImageSubresourceRange
remove this commented out code?

2020-10-26 21:09 UTC, jeremyg-lunarg commented on layers/synchronization_validation.cpp
> +bool ResourceAccessState::IsWARHazard(VkPipelineStageFlagBits usage_stage, SyncStageAccessFlagBits usage) const { return false; }
IsWARHazard() unused, but you fixed this locally already.

2020-10-27 14:41 UTC, jeremyg-lunarg reviewed
LGTM

2020-10-27 14:41 UTC, jeremyg-lunarg approved these changes

2020-10-28 20:34 UTC, jeremyg-lunarg requested changes

2020-10-28 20:34 UTC, jeremyg-lunarg commented on layers/synchronization_validation.cpp
> +                (input_attachment_ordering && usage_is_input_attachment) || (0 != (usage_bit & ordering.exec_scope));
(0 != (usage_bit & ordering.exec_scope))
While converting SyncStageAccessFlags to be bitset<>, the compiler informed me that usage_bit is of type SyncStageAccessFlagBits but ordering.exec_scope is type VkPipelineStageFlags. Should this check use usage_stage instead of usage_bit?

2020-10-30 15:55 UTC, jeremyg-lunarg reviewed
LGTM (again)

2020-10-30 15:55 UTC, jeremyg-lunarg approved these changes

2020-11-03 11:58 UTC, Tobski approved these changes
As best as I can tell, at the macro level, the modelling looks correct. I don't have enough experience with this code to say categorically that it works, particularly given the complexity of the underlying problem this is trying to solve, so there may be some details I'm failing to appreciate. However I'm confident enough that I'll add my approval.

2020-11-03 14:02 UTC, merged