[WIP] Validate protected command buffer and filter cubic and some perf improvement
KhronosGroup/Vulkan-ValidationLayers pull request #2269
Opened 2020-10-28 06:20 UTC by locke-lunarg

2020-10-28 07:09 UTC, locke-lunarg commented
Some refactors.

1) Moved looking for sampler descriptor from ValidateDescriptorSetBindingData into PreCallRecordCmdBindPipeline & PreCallRecordCmdBindDescriptorSets to impre

2) https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2226#pullrequestreview-513191074
   1) Change map BindingReqMap into unordered_map
   2) Change map lastBoundnge into array

3) Moved some validation for both image and sampler descriptor from` if (descriptor_class == DescriptorClass::ImageSampler || descriptor_class == DescriptorClass::PlainSampler)` into `if (descriptor_class == DescriptorClass::ImageSampler || descriptor_class == DescriptorClass::Image)`.

   ` if (descriptor_class == DescriptorClass::ImageSampler || descriptor_class == DescriptorClass::PlainSampler)` only validates sampler descriptor.

2020-11-04 01:11 UTC, sfricke-samsung commented
So first off you are attempting to finish the last 2 sets of Protected memory validation which will close #1996

So  "resource" can be anything that can be written to which is not limited to descriptors. For draws calls you will also want to check for Framebuffer attachments as well

2020-11-04 17:49 UTC, locke-lunarg commented
@sfricke-samsung  Thanks. Do you think it should also include binding vertices and indices?

2020-11-04 17:59 UTC, sfricke-samsung commented
@locke-lunarg  Ok, so re-read the VU

`02712` is "any resource written"

and

`02707` is "any resource accessed"

The "accessed" is defined as "store, load, atomic" else where in the spec

So yes, vertex input would be "Accessed" and possibly the use of Physical Storage Buffer as well

basically, I put these off as they are not a trivial addition of a VU

2020-11-04 22:27 UTC, locke-lunarg commented
@sfricke-samsung  Added validating framebuffer's attachments and binding vertex & index buffer.

2020-11-17 00:09 UTC, Tony-LunarG requested changes

2020-11-17 18:33 UTC, jzulauf-lunarg reviewed
didn't do a full review... just a couple quick notes

2020-11-17 18:33 UTC, jzulauf-lunarg commented on layers/core_validation_types.h
> +enum LvlBindPoint {
Naming issue no _

Computer -> Compute

2020-11-17 18:33 UTC, jzulauf-lunarg commented on layers/core_validation_types.h
> +    switch (bind_point) {
Given that graphics and compute are the same and only ray tracing differs... is there a simpler form... (look up, force cast, something.. for the first two...)

2020-11-17 18:33 UTC, jzulauf-lunarg commented on layers/core_validation_types.h
> +    std::array<LAST_BOUND_STATE, 3> lastBound;  // index is LvlBindPoint.
Define a LvlBindPoint BindPointSize (or Count) and use that as the array size.

2020-11-17 20:37 UTC, locke-lunarg commented on layers/core_validation.cpp
> +                    uint32_t index = subpass.pColorAttachments[i].attachment;
In FRAMEBUFFER_STATE::GetUsedAttachments, it has checked VK_ATTACHMENT_UNUSED, if it's VK_ATTACHMENT_UNUSED, the view is VK_NULL_HANDLE

2020-11-17 20:37 UTC, locke-lunarg commented on layers/core_validation.cpp
> +            skip |= ValidateProtectedBuffer(pCB, buf_state, caller, vuid.unprotected_command_buffer, "Buffer is a binding index");
Fixed

2020-11-17 20:37 UTC, locke-lunarg commented on layers/core_validation.cpp
> +                    ValidateProtectedBuffer(pCB, buf_state, caller, vuid.unprotected_command_buffer, "Buffer is a binding vertex");
fixed

2020-11-17 20:37 UTC, locke-lunarg commented on layers/core_validation.cpp
> +                uint32_t index = subpass.pDepthStencilAttachment->attachment;
In FRAMEBUFFER_STATE::GetUsedAttachments, it has checked VK_ATTACHMENT_UNUSED, if it's VK_ATTACHMENT_UNUSED, the view is VK_NULL_HANDLE

2020-11-17 20:47 UTC, locke-lunarg commented on layers/core_validation.cpp
> +                    uint32_t index = subpass.pInputAttachments[i].attachment;
In FRAMEBUFFER_STATE::GetUsedAttachments, it has checked VK_ATTACHMENT_UNUSED, if it's VK_ATTACHMENT_UNUSED, the view is VK_NULL_HANDLE

2020-11-17 20:51 UTC, locke-lunarg commented on layers/core_validation_types.h
> +    std::array<LAST_BOUND_STATE, 3> lastBound;  // index is LvlBindPoint.
I cannot find out lastBoundnge

2020-11-17 20:57 UTC, locke-lunarg commented on layers/core_validation_types.h
> +        samplers_used_by_image;  // Copy from StageStCmdDrawDispatchInfoate.interface_var. It combines from plural shader stages.
fixed

2020-11-17 21:16 UTC, Tony-LunarG commented on layers/core_validation_types.h
> +    std::array<LAST_BOUND_STATE, 3> lastBound;  // index is LvlBindPoint.
In the commit message "layers: Change map lastBoundnge into array"

2020-11-17 21:18 UTC, locke-lunarg commented on layers/core_validation_types.h
> +enum LvlBindPoint {
fixed

2020-11-17 21:18 UTC, locke-lunarg commented on layers/core_validation_types.h
> +    std::array<LAST_BOUND_STATE, 3> lastBound;  // index is LvlBindPoint.
added

2020-11-17 21:29 UTC, locke-lunarg commented on layers/core_validation_types.h
> +    std::array<LAST_BOUND_STATE, 3> lastBound;  // index is LvlBindPoint.
Thanks. Fixed

2020-11-17 21:55 UTC, locke-lunarg commented on layers/core_validation_types.h
> +    switch (bind_point) {
fixed

2020-11-17 22:27 UTC, mark-lunarg commented on layers/core_validation.h
> +    const char* maxMultiviewInstanceIndex;  // TODO: Some instance values are in VkBuffer.The validation in those Cmds is skipped.
All three of these should be lower_snake_case, please (like the others).

2020-11-17 22:39 UTC, locke-lunarg commented on layers/core_validation.h
> +    const char* maxMultiviewInstanceIndex;  // TODO: Some instance values are in VkBuffer.The validation in those Cmds is skipped.
fixed

2020-11-18 01:46 UTC, mark-lunarg commented on layers/core_validation.h
> +    const char* maxMultiviewInstanceIndex;  // TODO: Some instance values are in VkBuffer.The validation in those Cmds is skipped.
Thanks!  I have a PR up that refactors these `DrawDispatchVuid `structures, but I'll wait for your PR so you won't need to deal with the rebase.

2020-11-18 18:08 UTC, locke-lunarg commented on layers/core_validation.h
> +    const char* maxMultiviewInstanceIndex;  // TODO: Some instance values are in VkBuffer.The validation in those Cmds is skipped.
Thanks!

2020-11-23 16:25 UTC, locke-lunarg commented
@Tony-LunarG @mark-lunarg @jzulauf-lunarg  Refactored the attachments part to ensure their lifetime during commandbuffer. It's ready to review.

2020-11-24 18:15 UTC, Tony-LunarG approved these changes
LGTM - thanks!

2020-11-24 18:36 UTC, merged