Buffer dedup
KhronosGroup/Vulkan-ValidationLayers pull request #2320
Opened 2020-11-11 12:39 UTC by karl-lunarg

Remove buffer handle from the BufferDescriptor so we have only one buffer handle (in BUFFER_STATE) in our data structures.

Also, add a test that exercises the small logic change that was needed.

The new test doesn't depend on the code changes, so the test commit can be in any order or squashed with the layer commit.

2020-11-11 13:40 UTC, jzulauf-lunarg requested changes
I'd leave the interface the same and hide the lookup logic in it.

Note also, that other DescriptorSet subclass's aren't have been dehandled but not deduplicated.  For example `ImageDescriptor` has both a `std::shared_ptr<IMAGE_VIEW_STATE>` and a `VkImageView`.
 Probably sensible/maintainable to make these all as common in implementation as possible.

2020-11-11 13:40 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +                    VkBuffer buffer = buffer_node ? buffer_node->buffer : VK_NULL_HANDLE;
Why not leave this implementation detail in the BufferDescriptor::GetBuffer?  The caller doesn't care how BufferDescriptor knows.

2020-11-11 13:40 UTC, jzulauf-lunarg commented on layers/descriptor_sets.h
> -    VkBuffer GetBuffer() const { return buffer_; }
I'd leave the interface an implement the indirect lookup in it.

2020-11-11 13:59 UTC, karl-lunarg commented on layers/descriptor_sets.cpp
> +                    VkBuffer buffer = buffer_node ? buffer_node->buffer : VK_NULL_HANDLE;
Yes, changed as described.

2020-11-11 14:00 UTC, karl-lunarg commented on layers/descriptor_sets.h
> -    VkBuffer GetBuffer() const { return buffer_; }
Yes, changed as described.

2020-11-11 14:02 UTC, karl-lunarg commented
> Note also, that other cvdescriptorset::Descriptor subclass's aren't consistent with this change. They have been dehandled but not deduplicated. For example `ImageDescriptor` has both a `std::shared_ptr<IMAGE_VIEW_STATE>` and a `VkImageView`.
> Probably sensible/maintainable to make these all as common in implementation as possible. Deduplicating is the safest way to ensure full dehandling.

I was thinking of punting that task off to a card in the Enhancements Project so I could get back to what I'm supposed to be doing.  But I'll see about the others while I am here.

2020-11-11 15:59 UTC, karl-lunarg commented
I applied the same sort of changes to the other subclasses.  I think the result is better.  The VLTs pass for me.

2020-11-11 16:54 UTC, jzulauf-lunarg requested changes
Two patterns to fix
1) Borked copy -- shouldn't be doing (meta coded) 

`state_ = Get<STATE_TYPE>(src->GetState()->handle);`

but instead

`state_ = src_->state_`

if state_->destroyed, then the current pattern is looking up either a non-extant entry or worse a new alias for state_->handle.

2) No reason to got through two double accessors for (state_) ? state_->handle : NULL_HANDLE

2020-11-11 16:54 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +    buffer_state_ = dev_data->GetConstCastShared<BUFFER_STATE>(buff_desc->GetBufferState()->buffer);
Borked pattern, Copy the member directly, or the result of GetBufferState()

2020-11-11 16:54 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +    buffer_view_state_ = dev_data->GetConstCastShared<BUFFER_VIEW_STATE>(buffer_view);
Same borked pattern.

2020-11-11 16:54 UTC, jzulauf-lunarg commented on layers/descriptor_sets.h
> +    VkSampler GetSampler() const { return GetSamplerState() ? GetSamplerState()->sampler : VK_NULL_HANDLE; }
given that sample_state_ is a member (which has a cast to bool) I think it would be better to just use it than to do two Get/get's

2020-11-11 16:54 UTC, jzulauf-lunarg commented on layers/descriptor_sets.h
> +    VkSampler GetSampler() const { return GetSamplerState() ? GetSamplerState()->sampler : VK_NULL_HANDLE; }
same comment as above... and below as applicable

2020-11-11 16:54 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +        auto update_sampler = static_cast<const SamplerDescriptor *>(src)->GetSampler();
Should have (and use) a GetSamplerState  (and hopefully nobody else is using `Get<SAMPLER_STATE>(GetSampler())` (or similar as a pattern.  It's wasteful and broken.)

2020-11-11 16:54 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +        sampler_state_ = dev_data->GetConstCastShared<SAMPLER_STATE>(update_sampler);
can't we just either copy the src->sampler_state_ or src->GetSamplerState()

2020-11-11 16:54 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +    image_view_state_ = dev_data->GetConstCastShared<IMAGE_VIEW_STATE>(image_view);
Same borked pattern.  Either copy src->image_view_state_ directly or through GetImageViewState

2020-11-11 16:54 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +                auto buffer = static_cast<const BufferDescriptor *>(src_desc)->GetBufferState()->buffer;
Should use GetBuffer(), hide the details and avoid the null deref.

2020-11-12 01:34 UTC, karl-lunarg commented on layers/descriptor_sets.cpp
> +    buffer_state_ = dev_data->GetConstCastShared<BUFFER_STATE>(buff_desc->GetBufferState()->buffer);
Unborked.  I added GetSharedxxxState to the subclasses.

2020-11-12 01:35 UTC, karl-lunarg commented on layers/descriptor_sets.cpp
> +    buffer_view_state_ = dev_data->GetConstCastShared<BUFFER_VIEW_STATE>(buffer_view);
Unborked

2020-11-12 01:35 UTC, karl-lunarg commented on layers/descriptor_sets.h
> +    VkSampler GetSampler() const { return GetSamplerState() ? GetSamplerState()->sampler : VK_NULL_HANDLE; }
yep

2020-11-12 01:35 UTC, karl-lunarg commented on layers/descriptor_sets.cpp
> +        auto update_sampler = static_cast<const SamplerDescriptor *>(src)->GetSampler();
Unborked

2020-11-12 01:36 UTC, karl-lunarg commented on layers/descriptor_sets.cpp
> +                auto buffer = static_cast<const BufferDescriptor *>(src_desc)->GetBufferState()->buffer;
fixed

2020-11-12 02:17 UTC, jzulauf-lunarg requested changes
Looks like you got all but one of the ::Copy updates... and a couple unused (or soon to be unused) variables

2020-11-12 02:17 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +    image_view_state_ = dev_data->GetConstCastShared<IMAGE_VIEW_STATE>(image_view);
should be a copy from src, not a dev_data lookup.

2020-11-12 02:17 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +    auto image_view = static_cast<const ImageSamplerDescriptor *>(src)->GetImageView();
this should turn into an unused variable error

2020-11-12 02:17 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +    auto image_view = static_cast<const ImageDescriptor *>(src)->GetImageView();
this is an unused variable

2020-11-12 16:11 UTC, karl-lunarg commented on layers/descriptor_sets.cpp
> +    image_view_state_ = dev_data->GetConstCastShared<IMAGE_VIEW_STATE>(image_view);
done

2020-11-12 16:12 UTC, karl-lunarg commented on layers/descriptor_sets.cpp
> +    auto image_view = static_cast<const ImageDescriptor *>(src)->GetImageView();
yes

2020-11-12 16:12 UTC, karl-lunarg commented on layers/descriptor_sets.cpp
> +    auto image_view = static_cast<const ImageSamplerDescriptor *>(src)->GetImageView();
yes

2020-11-12 16:26 UTC, mark-lunarg commented
I love 'unborked'.  More unborking, please. It's not commonly known that the name 'Mark' comes from the German 'Marcus', meaning 'to bork'.

2020-11-16 16:51 UTC, jzulauf-lunarg approved these changes
Looks clean. Not sure why the shared pointer copies are going through accessors.  Copy is entirely a implementation aware process.  I'm sure RVO is going to avoid additional shared_pointer copies (which would imply atomic inc/dec operations), but it seems odd to hide internal manipulations behind an interface

2020-11-16 18:30 UTC, karl-lunarg commented
> Not sure why the shared pointer copies are going through accessors.

Yes, the code is cleaner and more consistent without the accessors.  I've cleaned that up along with a couple of other items.  I had probably thought that using the accessors were useful for self-documenting the shared ptr copy and making it easier to change the code behind the accessors if that ever became necessary.   Neither reason is worth it now.

Will merge once local and cloud CI passes.

2020-11-16 20:11 UTC, merged