build: Update known-good files for 1.2.160 header
KhronosGroup/Vulkan-ValidationLayers pull request #2325
Opened 2020-11-14 03:14 UTC by shannon-lunarg

Changes:
- Updated known-good files
- Generated new source files using `generate_source.py`
- Reconciled some VUID inconsistencies

2020-11-16 20:07 UTC, mikes-lunarg requested changes
Looks good, just one little change around `VUID-vkCmdSetViewportWScalingNV-firstViewport-01324`

2020-11-16 20:07 UTC, mikes-lunarg commented on layers/parameter_validation_utils.cpp
> +    if (firstViewport < device_limits.maxViewports) {
I think this if statement should go away. The idea behind removing `-01323` was that it is redundant with `-01324`, so we don't want to skip the sum check for the case that previously had its own VUID.

2020-11-17 18:15 UTC, shannon-lunarg commented
@mikes-lunarg I made the change you suggested to `parameter_validation_utils.cpp`.

#2328 fixed 10 VUID inconsistencies introduced by this header.

#2266 addresses 5 more VUID inconsistencies.

2020-11-17 18:28 UTC, mikes-lunarg approved these changes

2020-11-18 01:44 UTC, merged