build: Update known-good files for 1.2.165 SDK
KhronosGroup/Vulkan-ValidationLayers pull request #2426
Opened 2020-12-22 21:32 UTC by shannon-lunarg

Changes:
- Updated known-good files
- Generated new source files using `generate_source.py`

2020-12-28 21:20 UTC, mark-lunarg commented on layers/generated/object_tracker.cpp
> +            skip |= ValidateObject(pInfos[index0].srcAccelerationStructure, kVulkanObjectTypeAccelerationStructureKHR, true, kVUIDUndefined, "VUID-VkAccelerationStructureBuildGeometryInfoKHR-commonpa
@mikes-lunarg, @shannon-lunarg, is this is the right thing to do here?  Should we be checking  `noautovalidity` and maybe passing a flag down to/through `ValidateObject/CheckObjectValidity` to skip the `invalid_handle_code` error?

Also, @souravpNV, @dgkoch, this leaves some new VUIDs unimplemented according to [the Gitlab MR](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4278).

2020-12-29 16:12 UTC, mark-lunarg commented on layers/core_validation.cpp
> -                                LogError(device, "VUID-VkFragmentShadingRateAttachmentInfoKHR-pFragmentShadingRateAttachment-04523",
Gitlab Vulkan repo says this changed to `VUID-VkRenderPassCreateInfo2-pAttachments-04586`, should it be deleted, updated, or moved?

2020-12-29 17:21 UTC, shannon-lunarg commented on layers/core_validation.cpp
> -                                LogError(device, "VUID-VkFragmentShadingRateAttachmentInfoKHR-pFragmentShadingRateAttachment-04523",
I couldn't find an equivalent statement when I made the change. Upon second inspection `VUID-VkRenderPassCreateInfo2-pAttachments-04586` is the closest new VUID I found (from Vulkan-Headers commit at the `v1.2.161` tag).

2021-01-04 19:04 UTC, mikes-lunarg requested changes

2021-01-04 19:18 UTC, mikes-lunarg commented on layers/generated/object_tracker.cpp
> +            skip |= ValidateObject(pInfos[index0].srcAccelerationStructure, kVulkanObjectTypeAccelerationStructureKHR, true, kVUIDUndefined, "VUID-VkAccelerationStructureBuildGeometryInfoKHR-commonpa
@mark-lunarg We should probably suppress the generation of `ValidateObject` calls in the case of `noautovalidity="true"` because it indicates that valid usage is more nuanced than the xml can express (or we can autogen).

2021-01-04 21:17 UTC, shannon-lunarg commented on tests/vklayertests_others.cpp
> -    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "VUID-vkCmdBuildAccelerationStructuresKHR-commandBuffer-recording");
I'm not sure why that was removed. I probably ran the validation stats script before fixing the spelling mistake. Anyway, it's fixed now!

2021-01-04 21:28 UTC, shannon-lunarg commented
I need to spend some time updating copyright information, but the actual code change requests were addressed.

2021-01-04 22:00 UTC, mark-lunarg commented
Looks like the object tracker stuff will still throw false positives as @mikes-lunarg pointed out in `ObjectLifetimes::PreCallValidateCmdBuildAccelerationStructuresKHR`.

2021-01-04 23:43 UTC, dgkoch commented on layers/generated/object_tracker.cpp
> +            skip |= ValidateObject(pInfos[index0].srcAccelerationStructure, kVulkanObjectTypeAccelerationStructureKHR, true, kVUIDUndefined, "VUID-VkAccelerationStructureBuildGeometryInfoKHR-commonpa
> Also, @souravpNV, @dgkoch, this leaves some new VUIDs unimplemented according to the Gitlab MR.

@mark-lunarg I'm unclear if you need something from us on this MR, or are you just alerting us that there are additional VUIDs that still need to be implemented (that's expected from my side at least).

2021-01-05 00:16 UTC, mark-lunarg commented on layers/generated/object_tracker.cpp
> +            skip |= ValidateObject(pInfos[index0].srcAccelerationStructure, kVulkanObjectTypeAccelerationStructureKHR, true, kVUIDUndefined, "VUID-VkAccelerationStructureBuildGeometryInfoKHR-commonpa
@dgkoch, just an FYI -- should have known y'all would have it covered.

2021-01-05 00:17 UTC, mark-lunarg commented on layers/generated/object_tracker.cpp
> +            skip |= ValidateObject(pInfos[index0].srcAccelerationStructure, kVulkanObjectTypeAccelerationStructureKHR, true, kVUIDUndefined, "VUID-VkAccelerationStructureBuildGeometryInfoKHR-commonpa
To be even more clear, we don't need anything from you for this PR!

2021-01-05 18:30 UTC, mikes-lunarg commented
> Looks like the object tracker stuff will still throw false positives as @mikes-lunarg pointed out in `ObjectLifetimes::PreCallValidateCmdBuildAccelerationStructuresKHR`.

The noautovalidity parameters are also marked optional so I think the only true false positives would only be for non-null acceleration structure handles provided to vkGetAccelerationStructureBuildSizesKHR. I would be ok with fixing this in a follow-on PR but we should open an issue if not doing it right away.

2021-01-05 18:32 UTC, mikes-lunarg approved these changes

2021-01-05 20:45 UTC, merged