corechecks: Fix Android QueueSubmitBinarySemaphoreNotSignaled
KhronosGroup/Vulkan-ValidationLayers pull request #2569
Opened 2021-02-19 23:59 UTC by jeremyg-lunarg

In commit e60d417b5 I didn't properly handle the different VUIDs
for devices that support timeline semaphores vs those that do not.

Change-Id: I0cf08f113667aec43767916225d41fef36a49e2e

I ignored a @jzulauf-lunarg 'hmmm' at my own peril...

2021-02-20 01:45 UTC, ncesario-lunarg approved these changes
LGTM!

2021-02-20 15:40 UTC, jzulauf-lunarg requested changes
Enum name confusing/misleading.

2021-02-20 15:40 UTC, jzulauf-lunarg commented on layers/core_validation.cpp
> +                auto error = core->device_extensions.vk_khr_timeline_semaphore ? SubmitError::kTimelineCannotBeSignalled : SubmitError::kBinaryCannotBeSignalled;
the name kTimelineCannotBeSignalled  is confusing.  It's not that a TimelineSemphore cannot be signaled... it's the "VK_KHR_timeline_semaphore is enabled *variant* of the "binary cannot be signaled" message. 

We should probably have a consistent naming scheme to clarify.  kBinaryCannotBeSignalledAltTimeline or hide the complexity in Get*VUID functions as needed somehow (pass in the extension structure?)

2021-02-22 21:28 UTC, jzulauf-lunarg approved these changes
Can leave naming as it is for now...

2021-02-22 21:29 UTC, merged