layers: Remove unnecessary descriptor_sets functions
KhronosGroup/Vulkan-ValidationLayers pull request #2613
Opened 2021-03-07 05:08 UTC by sfricke-samsung

So after diving more into the code

- If the a new descriptor type is ever added, finding all the spots being used to add it is just as error prone as someone using `IsDyanmicDescriptor` incorrectly as descriptor types are used for various checks of different scopes anyways
- The `Descriptor` class had a virtual function for this already, but no one is using it anyway as it is easier to check the enum you want instead of hoping some abstracted function is doing it correctly. Plus there isn't any fancy logic picking which to use
- The functions ruins the places where switch statements make more scene

2021-03-08 17:18 UTC, ncesario-lunarg reviewed
If each usage of `IsDynamicDescriptor` must be checked whenever a new descriptor type is added, then I agree, the function isn't useful. I'm not entirely certain that's the case, though. If others agree this is the way to go, LGTM!

2021-03-08 19:00 UTC, jzulauf-lunarg requested changes
I don't have a strong preference for virtual function of `||` list -- though profiling might make sense.  But I do have a strong aversion to repeated stanzas... which might need to be updated everywhere.

2021-03-08 19:15 UTC, sfricke-samsung commented on layers/core_validation.cpp
> +                        if ((binding->descriptorType != VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC) &&
Some places like above `VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-pBindingFlags-03015` I feel the function doesn't make sense, that is a case were the VU being check explicitly labels the other 2

The other case was when it is easier to do a switch statement 

I guess I can see using the `IsDyanmicDescriptorType` for some of the places I took it out, but some places I feel it was less of "IsDyanmicDescriptorType" and more of "I want to check these 2 exact enum values, which just happen to be in that function" and that is where I feel the difference needs to be

2021-03-08 19:24 UTC, jzulauf-lunarg commented on layers/core_validation.cpp
> +                        if ((binding->descriptorType != VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC) &&
A more descriptive name for the function is fine.  Checking the same multipart condition in a number of places is asking for the next maintainer to miss one, so not fine.

2021-03-09 07:37 UTC, sfricke-samsung commented on layers/core_validation.cpp
> +                        if ((binding->descriptorType != VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC) &&
So brought back the `IsDyanmicDescriptorType` (and did as a second commit to more easily see the difference)

I think the best way to describe the descriptor classes is it is one part state tracking and one part consuming that state tracking

I only added the `IsDynamicDescriptorType` where it makes sense to both add the information w.r.t where it is consumed

For example, there is the `BindingTypeStats` which is checking if "both buffer type and/or dynamic" as that is how it is consumed. For this, the goal of `IsDynamicDescriptorType` doesn't make sense

2021-03-09 18:21 UTC, jzulauf-lunarg reviewed
Style nits ( == false) aside, we don't seem to be DRYing up the code with this change, when that's really what it needs.

2021-03-09 18:21 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +                    if ((binding_info.descriptorType == VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC) ||
Again isn't this `IsDynamicDescriptorType` ? it's in three places...

2021-03-09 18:21 UTC, jzulauf-lunarg commented on layers/descriptor_sets.h
> +inline bool IsDynamicDescriptorType(VkDescriptorType type) {
Why did we rename this if the name isn't any clearer?

2021-03-09 18:21 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +        // Get stats depending on descriptor type for caching later
Isn't this? IsDynamicDescriptorType  (or would a better name be IsDynamicBufferDescriptor)?

2021-03-09 18:21 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +                assert(IsDynamicDescriptorType(type));
if we want to DRY this, we could check on IsDynamicDescriptorType in the default: case...

2021-03-09 18:32 UTC, sfricke-samsung commented on layers/descriptor_sets.cpp
> +        // Get stats depending on descriptor type for caching later
Do we want a `IsDynamicBufferDescriptor` and some `IsNotDynamicButStillBufferDescriptor` for the `else if` case as well?

2021-03-09 18:32 UTC, sfricke-samsung commented on layers/descriptor_sets.cpp
> +                    if ((binding_info.descriptorType == VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC) ||
This one I left because `VUID-VkDescriptorSetLayoutBindingFlagsCreateInfo-pBindingFlags-03015` is explicity listing these two descriptor types so I think it makes sense to leave as being explicit here

2021-03-09 18:32 UTC, sfricke-samsung commented on layers/descriptor_sets.cpp
> +                assert(IsDynamicDescriptorType(type));
If a new dynamic type was added, it would not be obvious you need to drop all dynamic descriptors types down to the default case and not include a case here

2021-03-09 18:32 UTC, sfricke-samsung commented on layers/descriptor_sets.h
> +inline bool IsDynamicDescriptorType(VkDescriptorType type) {
I took this from your suggestion in a previous comment, I feel both are fine for me

2021-03-09 18:36 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +        // Get stats depending on descriptor type for caching later
It does occur twice, so would make sense

2021-03-09 18:40 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +                assert(IsDynamicDescriptorType(type));
With the mix of if check's and cases there's no perfect solution to be sure.  DRY as we can with appropriate commentary... I guess...

Most of the usage is generated, so at least that's probably safer...

2021-03-11 20:06 UTC, ncesario-lunarg commented
Running updated changes through internal CI.

2021-03-15 21:28 UTC, ncesario-lunarg commented
@jzulauf-lunarg do you still have suggestions regarding the latest changes here?

2021-03-16 15:33 UTC, jzulauf-lunarg approved these changes
Much DRY'r, thanks

2021-03-16 16:35 UTC, merged