[WIP] build: Update build docs
KhronosGroup/Vulkan-ValidationLayers pull request #2630
Opened 2021-03-17 20:47 UTC by ncesario-lunarg

This moves calling `update_deps.py` inside CMakeLists.txt in an attempt to streamline the build a bit and make it look more like a "standard cmake project." i.e., "git clone ... -> cmake ... -> cmake --build ..."

The build type and generator will get passed to `update_deps.py` by default. I also updated the docs to put a sort of "TL;DR" up front; I may be missing something important there, though.

@lunarpapillo @johnzupin This change would break 32b internal CI. If this change looks like something we want, adding the cmake var `NO_UPDATE_DEPS=ON` would need to be added so that things function the same as before (I can make that change...maybe even without breaking all of CI). Or we can change the default behavior to prefer what is necessary for CI, but this seems backwards to me. OR, upgrading to cmake >= 3.15 might work as `CMAKE_GENERATOR_PLATFORM` (i.e., what's controlled by the `-A` argument) looks like it wasn't supported officially until 3.15.

2021-03-18 23:52 UTC, johnzupin requested changes
I ran into something that might be a separate issue, so if it is one please let me know. 

Currently on ubuntu 18 and 20, `apt install python` installs python2. If I only do an `apt install python3`, so I only have python3 and not python2, and try run this cmake command `update_deps.py` fails

```
...
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 
Starting builds in /root/Vulkan-ValidationLayers/external
Checking out glslang in /root/Vulkan-ValidationLayers/external/glslang
Cloning glslang into /root/Vulkan-ValidationLayers/external/glslang
b'HEAD detached at e56beaee\nnothing to commit, working tree clean\n'
Building glslang in /root/Vulkan-ValidationLayers/external/glslang
Build dir = /root/Vulkan-ValidationLayers/external/glslang/build
Install dir = /root/Vulkan-ValidationLayers/external/glslang/build/install

Traceback (most recent call last):
  File "/root/Vulkan-ValidationLayers/scripts/update_deps.py", line 727, in <module>
    main()
  File "/root/Vulkan-ValidationLayers/scripts/update_deps.py", line 717, in main
    repo.Build(repos, repo_dict)
  File "/root/Vulkan-ValidationLayers/scripts/update_deps.py", line 519, in Build
    self.PreBuild()
  File "/root/Vulkan-ValidationLayers/scripts/update_deps.py", line 407, in PreBuild
    command_output(shlex.split(p), self.repo_dir)
  File "/root/Vulkan-ValidationLayers/scripts/update_deps.py", line 288, in command_output
    cmd, cwd=directory, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python': 'python'
CMake Error at CMakeLists.txt:94 (message):
  Could not run update_deps.py which is necessary to download dependencies.
```

The `update_deps.py` script's shebang is `/usr/bin/env python`, I'm wondering if the shebang can be changed to something like `/usr/bin/env python3` but I was unable to get this to work currently.

2021-03-18 23:52 UTC, johnzupin commented on BUILD.md
> +python ./scripts/update_deps.py --dir external-release-32 --arch Win32 --config Release
Change python to python3?

2021-03-19 18:51 UTC, ncesario-lunarg commented
Thanks for taking a look @johnzupin! I believe the issue you are seeing is a "python wart" WRT python 2 vs 3. In the scenario where you're experiencing the failure, is `python` in your PATH? My guess is that only `python3` is in the PATH, but I might be mistaken.

The part that's failing in the python trace above looks like it is during the `"prebuild"` step (most likely when doing the prebuild step for glslang) as that explicitly calls `python`; that will be a problem regardless of this change. We might be able to do something like search/replace a keyword (e.g., `$python`) in prebuild commands with `sys.executable` [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/a8918dfc53cf9abaaec848d0c1aa53e7fa6b7b0c/scripts/update_deps.py#L407), but I would probably do that in a follow up change if that is indeed the problem you encountered.

2021-03-19 18:56 UTC, ncesario-lunarg commented on BUILD.md
> +python ./scripts/update_deps.py --dir external-release-32 --arch Win32 --config Release
That might be clearer, but is python3 always installed? Or, on distributions where python3 is the default (or when only python3 is installed on, say, Windows), is there always a python3 -> python alias/symlink?

2021-03-19 19:49 UTC, johnzupin commented
> In the scenario where you're experiencing the failure, is `python` in your PATH? My guess is that only `python3` is in the PATH, but I might be mistaken.

Yeah that's the case, so I guess this isn't really an issue. I was testing in an ubuntu container and noticed this. Thanks for double checking.

2021-03-19 19:51 UTC, johnzupin commented on BUILD.md
> +python ./scripts/update_deps.py --dir external-release-32 --arch Win32 --config Release
I don't think this change is needed. It looks like python3 isn't a hard requirement to run this script.

2021-03-19 23:46 UTC, ncesario-lunarg commented
https://github.com/LunarG/VulkanTests/pull/100 would be likely be necessary if this change were to get merged.

2021-03-19 23:47 UTC, johnzupin approved these changes

2021-03-19 23:51 UTC, ncesario-lunarg commented on CMakeLists.txt
> +    endif()
The recent addition of a new project (i.e., the robin-hood repo) highlights that this isn't a great solution for this. I think just including `helper.cmake` after running `update_deps.py` instead of maintaining this list manually should work; going to give that a try.

2021-05-20 16:25 UTC, lunarpapillo approved these changes
> This change would break 32b internal CI.

I'm probably being thick, but I don't understand how... and it looks like the change passed CI... ?

At this point I'm going to tentatively approve, as I only see minor nits.  I'd like to understand more how you think this might impact 32-bit CI - we may want CI to build "both ways" to ensure that we don't inadvertently break one side of the build or the other (maybe the GitHub Actions CI is enough for that).

2021-05-20 16:25 UTC, lunarpapillo commented on CMakeLists.txt
> +        set(WARNING "CMAKE_GENERATOR_PLATFORM not set. Using x64 as target architecture.")
Why is this `set(WARNING...)` instead of `message(WARNING...)`?

2021-05-20 16:25 UTC, lunarpapillo commented on BUILD.md
> +1. C++ >= c++11 compiler. See platform-sepcific sections below for supported compiler versions.
sepcific => specific
c++11 => C++11

2021-05-20 16:25 UTC, lunarpapillo commented on BUILD.md
> +cmake --build . --config Debug
I'm not sure, but I think this is misleading... I think you need `-DCMAKE_BUILD_TYPE=Debug` only on Linux (single-configuration generator), but `--config Debug` only on Windows (multi-configuration generator)... I'm not sure what the Mac does.

Is the intent to provide a set of commands that works on both platforms, even if it's unnecessary?

2021-05-20 16:25 UTC, lunarpapillo commented on BUILD.md
> +1. Python >= 3.6
Where did Python 3.6 as a version come from?  An arbitrary choice, or derived from the functionality used in the script?

If arbitrary, CI uses 3.7; I think it would be good to keep a consistent Python version where possible.
If based on analysis of actual used functionality, then keep 3.6.

2021-05-20 16:48 UTC, ncesario-lunarg commented on CMakeLists.txt
> +        set(WARNING "CMAKE_GENERATOR_PLATFORM not set. Using x64 as target architecture.")
I like making hard-to-find cmake bugs? Nice catch!

Fixed.

2021-05-20 16:52 UTC, ncesario-lunarg commented on BUILD.md
> +cmake --build . --config Debug
This has the effect of passing along `CMAKE_BUILD_TYPE` along to `update_deps.py`. I will try to make this clear as Windows-only users (I believe Xcode has the same behavior as VS in this regard) are probably not used to setting this.

`--config Debug` is not necessary on *nix systems, but won't hurt.

2021-05-20 16:58 UTC, ncesario-lunarg commented on BUILD.md
> +1. Python >= 3.6
The reasoning for 3.6 is that 3.5 is deprecated. I have no reason not to bump this to 3.7.

2021-05-20 17:01 UTC, ncesario-lunarg commented
I added an obnoxious cmake message in an attempt to make users aware that `update_deps.py` will be running automatically and what to do to disable that behavior. Still a couple more scenarios to test out locally.

2021-05-20 17:53 UTC, mark-lunarg commented
+1 to what Mike said.  The decision to run it manually was a deliberate one, though I can no longer recall the particulars.

2021-05-20 17:57 UTC, mikes-lunarg commented on CMakeLists.txt
> +if (NOT NO_UPDATE_DEPS)
In general, I have a personal preference against bools with negative names because you get double negatives like this. `-DUPDATE_DEPS=ON` or `-DUPDATE_DEPS=OFF` would be a little more clear

2021-05-20 18:44 UTC, ncesario-lunarg commented
I have way less context than you guys, so if anyone is "way off," it's most likely me. The easiest thing for me to do is make the "auto update" opt-in rather than the default. I'll do that and change the flag to a positive name.

2021-05-20 19:31 UTC, ncesario-lunarg commented
Default behavior is now unchanged, and users can opt-in to automatically running `update_deps.py` via `-DUPDATE_DEPS=ON`.

2021-05-21 16:57 UTC, ncesario-lunarg commented
Any objections if this goes in now that the default behavior is unchanged?

2021-05-22 19:49 UTC, mikes-lunarg commented
> Any objections if this goes in now that the default behavior is unchanged?

None here, I like it!

2021-05-24 14:38 UTC, merged