corechecks: Simplify Image Layout Transition maps
KhronosGroup/Vulkan-ValidationLayers pull request #2679
Opened 2021-04-02 19:04 UTC by jeremyg-lunarg

Use a single range_map in ImageSubresourceLayoutMap instead of having 3 separate maps for each type of data tracked. This speeds up construction, lookups and iteration.

Make InitialLayoutStates be a small_vector
    
Many images appear to need only 1 or 2 InitialLayoutStates, so using a small vector prevents new calls in these cases. Performance appears to fall off if the small vector is size 4. In some cases we're getting over entries 255, so the small vector cannot use uint8_t for its size.

2021-04-02 22:48 UTC, ncesario-lunarg approved these changes
One clarifying question, but this LGTM (from what I can grasp :)).

2021-04-02 22:48 UTC, ncesario-lunarg commented on layers/image_layout_map.cpp
> +        if (pos->valid) {
I'm probably missing something obvious here, but in the `!pos->valid` case above, won't `return true` get hit on line 51, and this would never get hit? If that's true, seems like this should be an `else`.

2021-04-02 22:59 UTC, jeremyg-lunarg commented on layers/image_layout_map.cpp
> +        if (pos->valid) {
hmm. yeah. This is based on update_range_value() in range_vector.h with some options removed.  this could be an else, or not a block at all because the !valid block returns. Also the comment is not correct anymore either.

2021-04-02 23:01 UTC, jeremyg-lunarg commented on layers/image_layout_map.cpp
> +        if (pos->valid) {
in fact, this may not need to be a while loop at all.

2021-04-06 14:58 UTC, jzulauf-lunarg commented on layers/image_layout_map.cpp
> +        if (pos->valid) {
Hold on there... pos is being updated pos.seek(...) in the !pos->valid case, and will be either valid or end afterwards.

While is needed because the map we are updating may have multiple entries over range.

2021-04-06 15:02 UTC, jeremyg-lunarg commented on layers/image_layout_map.cpp
> +        if (pos->valid) {
Yes I came to that conclusion over the weekend and have an updated version in the works. But haven't pushed it yet because my gerrit jobs got caught up in CI weirdness yesterday afternoon.

2021-04-06 15:15 UTC, jzulauf-lunarg commented on layers/image_layout_map.cpp
> +        if (pos->valid) {
I won't have time for a thorough review until later in the week, servicing a "non-maskable interrupt."

2021-04-08 17:14 UTC, jeremyg-lunarg commented on layers/image_layout_map.cpp
> +        if (pos->valid) {
This part of the code changed substantially in the most recent push. Previously I was trying to do only the 'prefer source' part of update_range_value() but really I need to walk the range in 'prefer dest' mode but always update the current layout (if it is valid).

2021-04-08 17:14 UTC, jeremyg-lunarg commented
This change passed internal CI in job 4280

2021-04-08 22:35 UTC, ncesario-lunarg approved these changes
Updated changes LGTM; again, from what I understand.

2021-04-10 18:23 UTC, jzulauf-lunarg requested changes
I've reviewed down as far as just above ImageSubresourceLayoutMap::ConstIterator::UpdateRangeAndValue...  

Several small things, but one big one at ImageSubresourceLayoutMap::UpdateFrom

2021-04-10 18:23 UTC, jzulauf-lunarg commented on layers/image_layout_map.cpp
> +void ImageSubresourceLayoutMap::SetSubresourceRangeInitialLayout(const CMD_BUFFER_STATE& cb_state,
This version is never called with a view_state, and even though there is a default nullptr arg, it would be less confusing to kill the argument entirely.  I wrote this, and I got confused :).

2021-04-10 18:23 UTC, jzulauf-lunarg commented on layers/image_layout_map.cpp
> +ImageSubresourceLayoutMap::Layouts ImageSubresourceLayoutMap::GetSubresourceLayouts(const VkImageSubresource& subresource) const {
Why not just return a LayoutEntry?

2021-04-10 18:23 UTC, jzulauf-lunarg commented on layers/image_layout_map.cpp
> +ImageSubresourceLayoutMap::Layouts ImageSubresourceLayoutMap::GetSubresourceLayouts(const VkImageSubresource& subresource) const {
even by const reference...

2021-04-10 18:23 UTC, jzulauf-lunarg commented on layers/image_layout_map.cpp
> +ImageSubresourceLayoutMap::Layouts ImageSubresourceLayoutMap::GetSubresourceLayouts(const VkImageSubresource& subresource) const {
for a subsequent PR ... it would be nice to stay in range index space to avoid encode/decode round trips (assuring compatible encoders)

2021-04-10 18:23 UTC, jzulauf-lunarg commented on layers/image_layout_map.cpp
> +    return sparse_container::splice(&layouts_, other.layouts_, Arbiter::prefer_source);
This is going to incorrectly overwrite initial_layout... a smarter/predicated/Traits::update version of splice is going to be needed for the merge... or a smart assignment operator in LayoutEntry...  (though that seems... likely to be confusion to have an operator = that implement *write once* semantics...  so an update function would make sense.

2021-04-15 16:25 UTC, jeremyg-lunarg commented on layers/image_layout_map.cpp
> +            if (entry.state == nullptr) {
resolved by removing this logic from the pos->valid == true case.

2021-04-15 16:26 UTC, jeremyg-lunarg commented on layers/image_layout_map.cpp
> +            if (update_entry.initial_layout == kInvalidLayout) {
I went with orig and new to avoid current_state->current_layout Little Caesar's syndrome

2021-04-15 16:27 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
> +            if (item.second.current_layout != image_layout_map::kInvalidLayout) {
new splice implemented

2021-04-15 16:27 UTC, jeremyg-lunarg commented on layers/image_layout_map.cpp
> +    LayoutEntry entry = {expected_layout, layout, nullptr};
Fixed with Update method.

2021-04-15 16:28 UTC, jeremyg-lunarg commented on layers/image_layout_map.cpp
> +ImageSubresourceLayoutMap::Layouts ImageSubresourceLayoutMap::GetSubresourceLayouts(const VkImageSubresource& subresource) const {
returning const* and making caller deal with not found case.

2021-04-15 16:28 UTC, jeremyg-lunarg commented on layers/image_layout_map.cpp
> +    return sparse_container::splice(&layouts_, other.layouts_, Arbiter::prefer_source);
fixed with new splice + Update method.

2021-04-15 16:36 UTC, mark-lunarg commented on layers/image_layout_map.cpp
> +            if (update_entry.initial_layout == kInvalidLayout) {
🍕 🍕

2021-04-15 18:32 UTC, jeremyg-lunarg commented
This change passed internal CI in job 4315

2021-04-22 16:49 UTC, jzulauf-lunarg requested changes
one missing |= in the spice... and an open question re: updater semantics.

(this review covers only sparse_container)

2021-04-22 16:49 UTC, jzulauf-lunarg commented on layers/range_vector.h
> +using UpdaterFunction = bool (*)(typename Dst::mapped_type &dst, bool dst_valid, const typename Src::mapped_type &src);
I've been using stl style naming in this file, given the stl container usage support.

2021-04-22 16:49 UTC, jzulauf-lunarg commented on layers/range_vector.h
> +        updater = [](ValueType &dst, bool dst_valid, const ValueType &src) {
Instead of defining a type and two lambda to assign to it... why not just define the two default updater function templates and pass one of them?

2021-04-22 16:49 UTC, jzulauf-lunarg commented on layers/range_vector.h
> +                updated |= updater(write_it->second, true, read_it->second);
I'm torn between having single updater function and at traits object with update and make or create methods...

I don't see any stl examples with either of those semantics, and I'm uncomforatable creating a novel semantic...

Anything we can crib off of.  Also as written, there are likely unavoidable (i.e. not optimized away copies)

2021-04-22 16:49 UTC, jzulauf-lunarg commented on layers/range_vector.h
> +        updater = [](ValueType &dst, bool dst_valid, const ValueType &src) {
Some comment to a future maintainer  that may not know that *capture-less* lambda can be converted to function pointers. (I didn't.)

2021-04-22 17:22 UTC, jeremyg-lunarg commented on layers/range_vector.h
> +        updater = [](ValueType &dst, bool dst_valid, const ValueType &src) {
should I just make this a std::function? I think I tried at one point and had weird compiler errors.

2021-04-22 17:23 UTC, jeremyg-lunarg commented on layers/range_vector.h
> +        updater = [](ValueType &dst, bool dst_valid, const ValueType &src) {
NVM, I should just make 2 functions instead of using lamdas

2021-04-22 18:47 UTC, jzulauf-lunarg requested changes
There's one missing capture of "updated_current" and some other behavior that is (I think) unintentionally different between this PR and previous revisions

2021-04-22 18:47 UTC, jzulauf-lunarg commented on layers/image_layout_map.cpp
> +            LayoutEntry::Update(orig_entry, true, new_entry);
we're dropping the return value on the floor here.

2021-04-22 18:47 UTC, jzulauf-lunarg commented on layers/image_layout_map.h
> +        static bool Update(LayoutEntry& dst, bool dst_valid, const LayoutEntry& src) {
good.

2021-04-22 18:47 UTC, jzulauf-lunarg commented on layers/image_layout_map.cpp
> +            LayoutEntry::Update(orig_entry, true, new_entry);
updated_current |= ....

2021-04-23 17:25 UTC, jzulauf-lunarg reviewed
Comments on Optional that should align it better with std::optional and also fix the CI issue.

2021-04-23 17:25 UTC, jzulauf-lunarg commented on layers/vk_layer_data.h
> +    const T&& operator*() const&& {
I think move of the *value*  doesn't call for running the destructor... the optional would then contain a has_value of the post move object... maybe?

https://en.cppreference.com/w/cpp/utility/optional/operator%3D  explicitly says that a "Note that a moved-from optional still *contains* a value.

2021-04-23 17:25 UTC, jzulauf-lunarg commented on layers/vk_layer_data.h
> +    const T&& operator*() const&& {
In other weirdness check out the rules for move construction... https://en.cppreference.com/w/cpp/utility/optional/optional

2021-04-28 00:30 UTC, jzulauf-lunarg approved these changes
A nice cleanup.

2021-04-28 00:30 UTC, jzulauf-lunarg commented on layers/vk_layer_data.h
> +static constexpr in_place_t in_place{};
Nice

2021-04-28 00:30 UTC, jzulauf-lunarg commented on layers/range_vector.h
> +                auto opt = updater.insert(read_it->second);
Nice.  Optional is so cool.

2021-04-28 00:30 UTC, jzulauf-lunarg commented on layers/buffer_validation.cpp
> -
Unintentional w/s change?

2021-04-28 00:30 UTC, jzulauf-lunarg commented on layers/buffer_validation.cpp
> +struct GlobalLayoutUpdater {
I like this a ton more than the multi-path with bool implementation.

2021-04-28 00:35 UTC, jeremyg-lunarg commented
I'm running this through CTS tonight. If that looks good I'll have a very minor rebase and a whitespace change and then merge.

2021-04-28 16:31 UTC, jeremyg-lunarg commented
CTS results with this PR are identical to current results on master

2021-04-28 18:01 UTC, merged