SyncVal ImageRange traversal optimizations
KhronosGroup/Vulkan-ValidationLayers pull request #2694
Opened 2021-04-07 20:18 UTC by jzulauf-lunarg

Implement several range traversal optimizations:

1. Reduce recursion and unneeded map copies when traversing ranges in to AccessContext hierarchies
2. Store range generators for attachments, generated at begin renderpass time to minimize construction time
3. Refactor ImageRangeGenerator and ImageRangeEncoder to reduce generator construction time
4. Replace "upper_bound" based range termination checks with direct range value inspection

Useful diagnostic code exists for range generation and traversal temporarily in commit list, but is removed... but obviously can be found again if needed.

2021-04-07 21:51 UTC, jeremyg-lunarg reviewed
I'm probably going to need to go through this at least once more to understand the guts of it

2021-04-07 21:51 UTC, jeremyg-lunarg commented on layers/vk_layer_data.h
>  template <typename T>
This change looks good and could be a separate PR if you wanted to lighten the load

2021-04-07 21:51 UTC, jeremyg-lunarg commented on layers/synchronization_validation.cpp
> +                // is not valid, to minimize that reccurance
google says it is 'recurrence'

2021-04-07 21:51 UTC, jeremyg-lunarg commented on layers/synchronization_validation.h
> +    std::vector<AttachmentViewGen> attachment_views_;
AttachmentViewGenVector?

2021-04-08 17:10 UTC, jeremyg-lunarg reviewed
Aside from some cosmetic stuff, I think I get and agree with everything except the "syncval: Rewrite of image range gen for perf" change. That one is still breaking my head. Do we have enough test coverage to be sure we're hitting all of the different flavors of of SetInitialPos?

2021-04-08 17:10 UTC, jeremyg-lunarg commented on layers/subresource_adapter.cpp
> +    all_aspects_ = true;  // Let ++ know *not* to walk the mip/aspect
This comment, combined with the field name, throws me for a loop. Does the comment mean that if all_aspects_ is true, there's no need to walk each aspect in the mask because we can process them all in one contiguous blob?

2021-04-08 20:36 UTC, jzulauf-lunarg commented on layers/synchronization_validation.cpp
> +            (*previous_barrier)(access);
Trying to ensure std::function doesn't new. Pass by pointer avoids this completely. I've seen that become a cycle graveyard. same reason std::ref is used elsewhere. Playing with godbolt, passing a function pointer as a std::ref to the std::function stays within the "small string" optimization. passing a reference to std::function has copy-by-value semantics.

2021-04-08 20:47 UTC, jzulauf-lunarg commented on layers/synchronization_validation.cpp
> +            (*previous_barrier)(access);
Trying to ensure std::function doesn't new. Pass by pointer avoids this completely. I've seen that become a cycle graveyard. same reason std::ref is used elsewhere. Playing with godbolt, passing a function pointer as a std::ref to the std::function stays within the "small string" optimization. passing a reference to std::function has copy-by-value semantics.

2021-04-10 02:57 UTC, jzulauf-lunarg commented on layers/subresource_adapter.cpp
> +    all_aspects_ = true;  // Let ++ know *not* to walk the mip/aspect
Good instinct.  It was broken as written.  Update pushed (with a better name).

2021-04-12 17:07 UTC, jeremyg-lunarg commented on layers/subresource_adapter.cpp
> +    all_aspects_ = true;  // Let ++ know *not* to walk the mip/aspect
new name single_full_size_range makes much more sense, thanks.

2021-04-12 17:10 UTC, jeremyg-lunarg approved these changes
LGTM, all my comments are addressed.  I think we do need to do a before & after CTS run to check for changes in reported errors. Do you want to do that before or after committing this PR?

2021-04-12 17:25 UTC, jzulauf-lunarg commented
@jeremyg-lunarg  -- we'll wait on that result (and address any issues found)... it's a fundamental enough change.

2021-04-14 15:22 UTC, jeremyg-lunarg requested changes
I'm hitting this assert in many CTS tests:
```
Test case 'dEQP-VK.api.image_clearing.core.clear_color_image.1d.optimal.single_layer.r4g4_unorm_pack8'..
deqp-vk: /home/jeremyg/src/Vulkan-Meta/ValidationLayers/layers/subresource_adapter.cpp:534: subresource_adapter::ImageRangeGenerator::ImageRangeGenerator(const subresource_adapter::ImageRangeEncoder&, const VkImageSubresourceRange&, const VkOffset3D&, const VkExtent3D&, VkDeviceSize): Assertion `subres_range_.levelCount == 1' failed.

```

2021-04-14 22:26 UTC, jeremyg-lunarg commented
Another CTS assert:
```
Test case 'dEQP-VK.pipeline.multisample.raster_samples.samples_2.primitive_triangle_sparse'..
deqp-vk: /home/jeremyg/src/Vulkan-Meta/ValidationLayers/layers/synchronization_validation.cpp:5882: const ImageRangeGen* AttachmentViewGen::GetRangeGen(AttachmentViewGen::Gen) const: Assertion `got' failed.
```

2021-04-15 15:52 UTC, jeremyg-lunarg commented
CTS 1 at a time pass is *still* running after 30+ hours.  Another assertion failure:
```
Test case 'dEQP-VK.pipeline.render_to_image.core.3d.small.r8g8b8a8_unorm'..
deqp-vk: /home/jeremyg/src/Vulkan-Meta/ValidationLayers/layers/subresource_adapter.cpp:453: void subresource_adapter::ImageRangeGenerator::SetInitialPosSomeLayers(uint32_t, uint32_t): Assertion `!encoder_->Is3D() && (offset_.x == 0) && (offset_.y == 0) && (offset_.z == 0)' failed.
```

2021-04-19 22:15 UTC, lunarpapillo commented
> CTS 1 at a time pass is _still_ running after 30+ hours. 

I found a stray **Debug Assertion Failed** dialog box on `tcwinnvi2`.  That can explain CTS appearing to be running for 30+ hours, as the test effectively hangs until the dialog box is dismissed.

We really should bring updates to the CTS tests (like we had to do for **GFXReconstruct**, **Vulkan-ValidationLayers**, **Vulkan-ExtensionLayer**, and **Vulkan-Loader**) to avoid triggering a Windows C++ Runtime dialog box.

2021-04-19 23:15 UTC, lunarpapillo commented
I'm doing some webhook trigger testing using this PR... apologies for the spam.

2021-04-20 15:37 UTC, jeremyg-lunarg commented
> > CTS 1 at a time pass is _still_ running after 30+ hours.
> 
> I found a stray **Debug Assertion Failed** dialog box on `tcwinnvi2`. That can explain CTS appearing to be running for 30+ hours, as the test effectively hangs until the dialog box is dismissed.
> 
> We really should bring updates to the CTS tests (like we had to do for **GFXReconstruct**, **Vulkan-ValidationLayers**, **Vulkan-ExtensionLayer**, and **Vulkan-Loader**) to avoid triggering a Windows C++ Runtime dialog box.

This isn't what I was hitting. I was running code on linux that we knew had assertion failures. So I wrote a really dumb shell script that launched every line in the mustpass.txt file as its own command. This lets you find ALL the assertion failures but it takes a very long time to run.

2021-05-04 14:16 UTC, jeremyg-lunarg approved these changes
LGTM. latest push ran CTS to completion. SYNC error counts are in line with what was generated before.

2021-05-05 13:39 UTC, merged