layers: validate storage image reads/writes formats
KhronosGroup/Vulkan-ValidationLayers pull request #2777
Opened 2021-05-05 09:59 UTC by djdeath

Reads & writes on storage images require formats based of

 VkPhysicalDeviceFeatures:
    - shaderStorageImageReadWithoutFormat
    - shaderStorageImageWriteWithoutFormat

2021-05-05 09:59 UTC, djdeath commented
Apologies if I got my SPIRV foo wrong :/

2021-05-05 10:00 UTC, djdeath commented
Partially addresses https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1276

2021-05-05 12:18 UTC, jekstrand commented on layers/shader_validation.cpp
> +                                           "features-shaderStorageImageWriteWithoutFormat");
The Vulkan spec is actually stronger than this and requires that the variables themselves be decorated **NonReadable** or **NonWritable**.  We should also ensure that they aren't read/written but that seems more like the SPIR-V validator's job.

2021-05-05 17:31 UTC, ncesario-lunarg requested changes
Thanks @djdeath! I'm adding @jeremy-lunarg (though not sure when he'll be able to take a look) as I think he had done previous work on this.

2021-05-05 17:31 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +               assert(false); // This should never happen
It looks like `get_def` immediately follows where this is called. Maybe just make this function return a `spirv_inst_iter` (i.e., `def`)? I think you would then be able to return `end()` here and check that in the calling code; even if it _should_ never happen, we've gotten bit by asserts in the shader_validation code in the past.

2021-05-05 17:31 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +                                           "features-shaderStorageImageReadWithoutFormat");
This should probably be a constant in `core_validation_error_enums.h` (and ditto for below).

2021-07-21 09:27 UTC, llandwerlin-intel commented on layers/shader_validation.cpp
> +                                           "features-shaderStorageImageReadWithoutFormat");
Done/

2021-07-21 09:27 UTC, llandwerlin-intel commented on layers/shader_validation.cpp
> +               assert(false); // This should never happen
Good point, done.

2021-07-21 09:27 UTC, llandwerlin-intel commented on layers/shader_validation.cpp
> +        if (loads.find(id) != loads.end()) {
Done.

2021-07-21 09:28 UTC, llandwerlin-intel commented on layers/shader_validation.cpp
> +uint32_t GetImageFormat(SHADER_MODULE_STATE const *src, std::map<uint32_t, uint32_t>& loads, uint32_t id)
Seems like it would interact with your other comment about keeping the list of loads around, leaving as is for now.

2021-07-21 11:23 UTC, llandwerlin-intel commented on layers/shader_validation.cpp
> +                                           "features-shaderStorageImageWriteWithoutFormat");
It wasn't too much code to add, so I did.

2021-07-21 18:51 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +spirv_inst_iter GetImageFormatInst(SHADER_MODULE_STATE const *src, std::map<uint32_t, uint32_t>& loads, uint32_t id)
> "Seems like it would interact with your other comment about keeping the list of loads around, leaving as is for now."

Sorry, I don't think I understand this comment. This should probably at least live in `shader_module.cpp` rather than `shader_validation.cpp` as it's just dealing with parsing SPV, not validation. If passing in the state is preferable to making this a member function, then this should be a const reference.

2021-07-21 19:51 UTC, llandwerlin-intel commented on layers/shader_validation.cpp
> +spirv_inst_iter GetImageFormatInst(SHADER_MODULE_STATE const *src, std::map<uint32_t, uint32_t>& loads, uint32_t id)
Okay, done.

2021-07-22 00:10 UTC, ncesario-lunarg requested changes
Sorry if these were here before and I missed it. I think this looks good except for a couple minor nits.

2021-07-22 00:10 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +                             "shaderStorageImageReadWithoutFormat not supported but variable %u "
`%u` -> `PRIu32` (same below).

2021-07-22 00:10 UTC, ncesario-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "features-shaderStorageImageReadWithoutFormat");
Should this string contain `UNASSIGNED` now (same for other tests below)? I personally prefer using the variable here, but I know we have both ways in the code currently.

2021-07-22 07:32 UTC, llandwerlin-intel commented on layers/shader_module.cpp
> +        const auto& def = get_def(id);
done.

2021-07-22 07:32 UTC, llandwerlin-intel commented on layers/shader_validation.cpp
> +                             "shaderStorageImageReadWithoutFormat not supported but variable %u "
Done.

2021-07-22 07:33 UTC, llandwerlin-intel commented on tests/vklayertests_pipeline_shader.cpp
> +    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "features-shaderStorageImageReadWithoutFormat");
Ah thanks, that test wasn't running on my machine so I missed it.

Leaving the string, I can't see any other kVUID constant in that file.

2021-07-22 15:54 UTC, ncesario-lunarg approved these changes

2021-07-22 15:55 UTC, ncesario-lunarg commented
Thanks @llandwerlin-intel @djdeath!

2021-07-22 15:55 UTC, merged