layers: Add descriptor level change tracking for image layouts
KhronosGroup/Vulkan-ValidationLayers pull request #2792
Opened 2021-05-11 16:25 UTC by jeremyg-lunarg

Extend the set level change tracking to also track changes per image.
The set level tracking does catch (and skip) completely unchanged
DescriptorSets, but we can also get very large sets with only a few
changed descriptors. The new change count also catches cases of
the same image reused in multiple descriptors, so the checked_layouts
set optimization is removed.

2021-05-11 18:53 UTC, jzulauf-lunarg requested changes
the descriptor scope is global, so the version can't be tracked there safely.

2021-05-11 19:43 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> -                    if (set_node->GetTotalDescriptorCount() > cvdescriptorset::PrefilterBindRequestMap::kManyDescriptors_) {
this isn't taking out the prefilter stuff, just what was in  commit 2171f936be655d3044d68308f26ebf2c2fe8bd0a

2021-05-11 21:32 UTC, jzulauf-lunarg commented on layers/descriptor_sets.h
> +    layer_data::unordered_map<const CMD_BUFFER_STATE*, uint64_t> layout_change_counts_;
Also, please don't use std::pair... First, I hate first.  Second, I hate second twice as much.  Define a little struct with real names.

2021-05-11 23:05 UTC, jeremyg-lunarg commented on layers/descriptor_sets.h
> +    layer_data::unordered_map<const CMD_BUFFER_STATE*, uint64_t> layout_change_counts_;
the robin hood version is faster than my try at my try at a vector version...

2021-05-18 14:34 UTC, jeremyg-lunarg commented
This PR is regressing performance in benchmarking of multi-threaded game engines. It is on hold until I figure out how to solve that.

2022-09-07 13:40 UTC, closed without merging