layers: Use range based iteraton for subresource layout checking
KhronosGroup/Vulkan-ValidationLayers pull request #2838
Opened 2021-05-27 17:07 UTC by jeremyg-lunarg

Remove ImageSubresourceLayoutMap::ConstIterator, which went through
a bunch of trouble to iterate over every single subresource in a
range with the same layout. It is sufficient to check each range
once.

2021-05-28 17:31 UTC, jzulauf-lunarg requested changes
Concerns about your CLB traversal algorithm

2022-04-20 15:08 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
> +                         (pos->lower_bound != pos.map().end()) && (range_gen->includes(pos->index));
no longer using cached_lower_bound at all

2022-04-20 15:08 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
> +                         pos.seek(pos->lower_bound->first.end)) {
yep.

2022-04-20 15:09 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                    cb_layouts != cb_subres_map->GetLayoutMap().end() ? cb_layouts->second.current_layout : kInvalidLayout;
hmm this might still need to be addressed

2022-04-20 15:10 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
> +                 pos.seek(pos->lower_bound->first.end)) {
all of the iteration logic is now in ImageSubresourceLayoutMap::AnyInRange()

2022-04-20 15:52 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                    cb_layouts != cb_subres_map->GetLayoutMap().end() ? cb_layouts->second.current_layout : kInvalidLayout;
It looks like range_map::find handles the intersection check. Or am I not looking at the right find()?

```
    iterator find(const index_type &index) {
        auto lower = lower_bound(range<index_type>(index, index + 1));
        if (!at_end(lower) && lower->first.includes(index)) {
            return lower;
        }
        return end();
    }

```

2022-04-20 16:08 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
>  // Utility type for ForRange callbacks
not actually resolved yet.

2022-06-01 15:19 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
>  // Utility type for ForRange callbacks
now resolved.

2022-06-02 13:41 UTC, jzulauf-lunarg reviewed
The review so far... a couple bit of DRYness recommend... continuing to working starting with the parallel_iterator in CoreChecks::PreCallValidateCmdExecuteCommands.

2022-06-02 13:46 UTC, jeremyg-lunarg commented on layers/image_layout_map.cpp
> +    for (auto range_gen = RangeGenerator(encoder_, normalized_range); range_gen->non_empty(); ++range_gen) {
just pushed an update to do this.

2022-06-02 13:53 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
> +bool CoreChecks::VerifyImageLayout(const CMD_BUFFER_STATE *cb_node, const IMAGE_STATE *image_state,
the real reason for this version is to use image_view_state->range_generator for AnyInRange() instead of creating a new one.

2022-06-02 14:47 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
> +                                                              caller, error](const VkImageSubresource &subres, const LayoutEntry &state) {
git clang-format is finicky I guess. Fixed.

2022-06-02 14:47 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
> +bool CoreChecks::VerifyImageLayout(const CMD_BUFFER_STATE *cb_node, const IMAGE_STATE *image_state,
Got rid of the image_state parameter and added comments about the precooked range_generator

2022-06-02 17:10 UTC, aitor-lunarg approved these changes
LGTM! There's a comment I added, but it's just a personal preference.

2022-06-02 17:10 UTC, aitor-lunarg commented on layers/buffer_validation.cpp
> +    assert(cb_node);
May as well just request a reference instead of a pointer (this is just a personal style preference though, can be done in a different PR). Same applies to other asserts below.

2022-06-02 19:31 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
> +    assert(cb_node);
Ok. I think I'll do that in a separate PR and change all of the different versions of this method at once.

2022-06-03 18:28 UTC, jzulauf-lunarg approved these changes
LGTM -- nice to get rid of the overhead of the abstraction.

2022-06-06 15:40 UTC, merged