Add warning for zero-sized render area
KhronosGroup/Vulkan-ValidationLayers pull request #2885
Opened 2021-06-16 03:01 UTC by HildarTheDorf

A mistake that's caught me far too many times. Render passes with a zero-sized render area seem to be allowed by the spec but seem to be rarely intended. They can cause useful side-effects like layout transitions (amongst a whole host of other things), but there's generally a simpler/better replacement if you aren't actually writing to any framebuffer attachments.

I assume I need to write a test for this? If so ping me and I'll add one.

2021-06-16 14:27 UTC, ncesario-lunarg reviewed
Thanks @HildarTheDorf, I think this makes sense, but I'd like to get @Tony-LunarG's opinion on this. If you could please add a test, then I think this would be GTG!

2021-06-16 16:37 UTC, sfricke-samsung commented
So for some added context, I asked before about the warnings currently for a zero volume `vkCmdBlitImage`, `vkCmdCopyBufferToImage`, and `vkCmdCopyImageToBuffer` and we said in the WG

> We allowed these so that developers didn't have to put if checks on them, IIRC - same reason draw counts of 0 are allowed. A warning seems appropriate

So I assume there was a similar reason this was allowed to be zero as well, but agree a warning is a great addition here

2021-06-16 16:39 UTC, Tony-LunarG commented
Agreed on a warning.

2021-07-15 18:06 UTC, ncesario-lunarg approved these changes

2021-07-16 05:11 UTC, ncesario-lunarg requested changes

2021-07-16 05:11 UTC, ncesario-lunarg commented on tests/vklayertests_best_practices.cpp
> +    m_commandBuffer->EndRenderPass();
Getting a crash here on every platform except Windows + AMD. I think just removing this and the following line should be sufficient. Because there is a validation error with CmdBeginRenderPass, the actual dispatch to the driver never happens; looks like calling CmdEndRenderPass without first calling CmdBeginRenderPass causes a crash on most drivers.

2021-07-16 05:13 UTC, ncesario-lunarg commented on layers/best_practices_utils.cpp
> +                           "and can only be used for side effects such as layout transitions.");
Would it be possible to add this change to the previous commit? In general we try to keep changes to the tests separate from the layer changes for clarity/neatness.

2021-07-16 09:20 UTC, hannes-harnisch commented on tests/vklayertests_best_practices.cpp
> +    m_commandBuffer->EndRenderPass();
Oops. I didn't realize that within the test context, calls to functions that expect validation errors don't get executed.

2021-07-16 13:05 UTC, hannes-harnisch commented on layers/best_practices_utils.cpp
> +                           "and can only be used for side effects such as layout transitions.");
Done.

2021-07-16 13:05 UTC, hannes-harnisch commented on tests/vklayertests_best_practices.cpp
> +    m_commandBuffer->EndRenderPass();
Done.

2021-07-16 15:22 UTC, ncesario-lunarg approved these changes
LGTM, thanks!

One minor nit I missed is that the "label" in the subject of the commit (i.e., `practices:` in this case) should be `tests:` for the commits that modify the test code.

2021-07-16 15:25 UTC, HildarTheDorf commented
Comment lines fixed

2021-07-16 15:47 UTC, ncesario-lunarg commented
> Comment lines fixed

Thanks!

2021-08-16 11:13 UTC, hannes-harnisch commented
Is this ready to be merged?

2021-08-16 11:20 UTC, HildarTheDorf commented
Should be as far as I know!On 16 Aug 2021 12:14, Hannes Harnisch ***@***.***> wrote:
Is this ready to be merged?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-08-16 17:10 UTC, ncesario-lunarg commented
Yep, my apologies, this slipped through the cracks.

2021-08-16 17:10 UTC, merged