Jeremyg qfot
KhronosGroup/Vulkan-ValidationLayers pull request #2898
Opened 2021-06-18 15:33 UTC by jeremyg-lunarg

layers: Do pipeline stage checking for queue family transfers
    
There is nothing in the spec indicating we should skip this checking, unlike access masks which are specifically called out to be ignored.
    
Fixes #2888

2021-06-18 16:06 UTC, krOoze commented on layers/buffer_validation.cpp
>          skip |= ValidateMemoryBarrier(objects, loc, op_type, queue_flags, mem_barrier, src_stage_mask, dst_stage_mask);
This also looks sus. Why do we care about `op_type` at all here?

2021-06-18 16:11 UTC, krOoze commented on layers/buffer_validation.cpp
>      if (op_type == kAllRelease || op_type == kGeneral) {
The  "all" name does no longer make sense I think. The `ComputeBarrierOperationsType()` could just be invoked in here.

2021-06-18 16:13 UTC, krOoze commented on layers/buffer_validation.cpp
> +    skip |= ValidatePipelineStage(objects, loc.dot(Field::srcStageMask), queue_flags, barrier.srcStageMask);
This looks too down the callchain. I think this would just validate the same thing multiple times for each barrier struct.

2021-06-18 16:18 UTC, krOoze commented on layers/cmd_buffer_state.h
> +        return (assume_transfer || IsTransferOp(barrier)) && (command_pool->queueFamilyIndex == barrier.srcQueueFamilyIndex);
I don't really trust these functions. `assume_transfer` feels abuseable, and I am not really sure if it is used correctly everywhere.

2021-06-18 16:30 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
>          skip |= ValidateMemoryBarrier(objects, loc, op_type, queue_flags, mem_barrier, src_stage_mask, dst_stage_mask);
because this call will validate the access flags on a VkImageMemory barrier and we use op_type to control if src or dst flags are skipped.

2021-06-18 16:30 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
> +    skip |= ValidatePipelineStage(objects, loc.dot(Field::srcStageMask), queue_flags, barrier.srcStageMask);
This is for the synchronization2 barrier structures, which each have their own set of pipeline stage flags.

2021-06-18 16:30 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
>      if (op_type == kAllRelease || op_type == kGeneral) {
good point.

2021-06-18 16:30 UTC, jeremyg-lunarg commented on layers/cmd_buffer_state.h
> +        return (assume_transfer || IsTransferOp(barrier)) && (command_pool->queueFamilyIndex == barrier.srcQueueFamilyIndex);
@jzulauf-lunarg , what do you think? This looks like it was originally added as an optimization. Was there a specific case where these checks were a hot spot?

2021-06-18 16:34 UTC, krOoze commented on layers/buffer_validation.cpp
>          skip |= ValidateMemoryBarrier(objects, loc, op_type, queue_flags, mem_barrier, src_stage_mask, dst_stage_mask);
Sure, but why here. Feels like it should be inside `ValidateMemoryBarrier`. The `op_type` variable does not seem otherwisely used for anything else.

2021-06-18 16:54 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
>          skip |= ValidateMemoryBarrier(objects, loc, op_type, queue_flags, mem_barrier, src_stage_mask, dst_stage_mask);
ValidateMemoryBarrier() is templated. twice. One version can check VkMemoryBarrier, VkBufferMemoryBarrier and VkImageMemory barrier. The other version can check the synchronization2 equivalents.  Since VkMemoryBarrier and VkMemoryBarrier2KHR do not have src or dst QueueFamilyIndex fields we either need to pass in something like op_type from the caller, or have  a 3rd version of the template, or some other way to handle plain memory barriers. Now that op_type isn't passed in all the way from the top it might be possible to replace it with template specializations of CMD_BUFFER_STATE::ComputeBarrierOperationsType(). But that would then require passing a CMD_BUFFER_STATE object down to the next level, so it doesn't seem like a big improvement to me.

2021-06-18 16:56 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
> +        skip |= ValidateMemoryBarrier(objects, loc, kGeneral, queue_flags, mem_barrier, src_stage_mask, dst_stage_mask);
Here's where ValidateMemoryBarrier() gets called for a VkMemoryBarrier, which is never part of a QFOT

2021-06-18 17:09 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
>          skip |= ValidateMemoryBarrier(objects, loc, op_type, queue_flags, mem_barrier, src_stage_mask, dst_stage_mask);
actually, I take it back. I may be able to collapse a whole bunch of stuff by moving op_type down..

2021-06-18 22:05 UTC, krOoze commented on layers/buffer_validation.cpp
> +    skip |= ValidatePipelineStage(objects, loc.dot(Field::srcStageMask), queue_flags, barrier.srcStageMask);
Looks to me though it is called for both. `PreCallValidateCmdPipelineBarrier()` calls `ValidateBarriers()`. And `ValidateBarriers()` calls the stage version of `ValidateMemoryBarrier()`.

Perhaps a separate issue from what you set out do to here though...

2021-06-18 23:06 UTC, krOoze commented on layers/core_validation.cpp
> +        skip |= ValidateSubpassBarrier(objects, loc, nullptr, dependency);
I think the function does not need the parameter at all then.

2021-06-23 14:57 UTC, jzulauf-lunarg commented on layers/cmd_buffer_state.h
> +        return (assume_transfer || IsTransferOp(barrier)) && (command_pool->queueFamilyIndex == barrier.srcQueueFamilyIndex);
I know that before the command_pool was dehandled, the Get<COMMAND_POOL_STATE> would sometimes show, but frankly, I don't remember about the assume_transfer...

2021-06-23 15:48 UTC, jzulauf-lunarg requested changes
one real issue ... the queue flags for subpass barriers, and a couple of nits.

Good cleanup of some leftover "well it used to be a good idea" in there as well.

2021-06-23 15:48 UTC, jzulauf-lunarg commented on layers/buffer_validation.cpp
> -    auto queue_flags = cb_state->GetQueueFlags();
Another remnant of when these Get* functions hid a Get<COMMAND_POOL_STATE>.  No need to cache and pass this anymore.

2021-06-23 15:48 UTC, jzulauf-lunarg commented on layers/core_validation.cpp
> +        skip |= ValidateSubpassBarrier(objects, loc, nullptr, dependency);
Looks like it's only called once with only nullptr, s.t. ValidateSubpassBarrier can assume the incoming CB_STATE would be nullptr, and potentially simplify?

2021-06-23 15:48 UTC, jzulauf-lunarg commented on layers/qfo_transfer.h
> +// specializations for barriers that cannot do queue family ownership transfers
can these be constexpr and/or do we care?

2021-06-23 15:59 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
> +    auto queue_flags = cb_state ? cb_state->GetQueueFlags() : sync_utils::kAllQueueTypes;
This is a really good point and will help me get rid of the cb_state nullptr.

2021-06-23 16:45 UTC, jeremyg-lunarg commented on layers/qfo_transfer.h
> +// specializations for barriers that cannot do queue family ownership transfers
Yes, they can. It looks like constexpr is slightly more efficient on some compilers at low optimization levels. https://godbolt.org/z/75rYPojx3  But in any case it is more expressive than just inline.

2021-06-23 20:00 UTC, jzulauf-lunarg approved these changes
LGTM

2021-06-23 20:00 UTC, jzulauf-lunarg commented on layers/buffer_validation.cpp
> +static inline VkQueueFlags SubpassToQueueFlags(uint32_t subpass) {
Good catch on EXTERNAL

2021-06-23 20:00 UTC, jzulauf-lunarg commented on layers/buffer_validation.cpp
> +    auto src_queue_flags = SubpassToQueueFlags(dependency.srcSubpass);
I was considering whether it would be DRY'r to somehow use ValidateMemoryBarrier (with cb_state derived state unpacked into arguments), but it's better as is, without the complexity given that it would save only 4 lines, and all the argument unpacking would be different as well.

2021-06-23 20:00 UTC, jzulauf-lunarg commented on layers/cmd_buffer_state.h
> +// specializations for barriers that cannot do queue family ownership transfers
Meant to ask the same question about constexpr here... but not worth another CI spin at this point.

2021-06-23 20:00 UTC, jzulauf-lunarg commented on layers/qfo_transfer.h
> +// specializations for barriers that cannot do queue family ownership transfers
@ -O1 you can see the difference in the setup for the  << call... but we'll never see the difference in perf I'd be willing to bet.

2021-06-23 20:10 UTC, jeremyg-lunarg commented on layers/cmd_buffer_state.h
> +// specializations for barriers that cannot do queue family ownership transfers
I already did that spin, and it didn't go all the way around. :(

2021-06-23 20:11 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
> +static inline VkQueueFlags SubpassToQueueFlags(uint32_t subpass) {
Unit tests caught it!

2021-06-23 20:11 UTC, merged