layers: Clean up and document check disable options
KhronosGroup/Vulkan-ValidationLayers pull request #2902
Opened 2021-06-22 17:45 UTC by jeremyg-lunarg

VALIDATION_CHECK_DISABLE_IDLE_DESCRIPTOR_SET is now part of ...DISABLE_OBJECT_IN_USE,
because it does the same thing for all non-descriptor objects.

VALIDATION_CHECK_DISABLE_PUSH_CONSTANT_RANGE is removed because it was
not used by the code.

Add manifest descriptions for the rest, and add some other fields needed
by vkconfig.

Fixes #2897

2021-06-23 19:50 UTC, ncesario-lunarg approved these changes
One wording nit, but LGTM!

2021-06-23 19:50 UTC, ncesario-lunarg commented on layers/json/VkLayer_khronos_validation.json.in
> +                            "description": "Check that layout of each image subresource is correct whenever it is used a command buffer. These checks are very CPU intensive for some applications.",
"..._the_ layout..."

"..._in_ a command buffer"? "..._by_ a command buffer"?

2021-06-25 18:39 UTC, christophe-lunarg commented on layers/json/VkLayer_khronos_validation.json.in
> +        "platforms": [ "WINDOWS", "LINUX", "ANDROID" ],
MacOS is missing

Not everything is supported but each individual feature also has a platform element that removes macOS when it's not supported.

2021-06-25 18:41 UTC, christophe-lunarg requested changes
Looks good to me except for the layer platforms element that needs to be fixed.

2021-06-25 18:46 UTC, christophe-lunarg reviewed
I think the branch needs to be rebase to master as @Tony-LunarG added shader cache.

Check that shader cache has a platform element and that macOS is not set as @KarenGhavam-lunarG said it's not supported.

2021-06-29 12:49 UTC, christophe-lunarg reviewed
So there is no environment variable for "report_flags", "debug_action", "log_filename"?

2021-06-29 13:57 UTC, mark-lunarg commented
@christophe-lunarg, correct, env vars do not exist for those three options.

2021-06-29 16:35 UTC, christophe-lunarg commented
> @christophe-lunarg, correct, env vars do not exist for those three options.

Ok, thanks @mark-lunarg

2021-07-01 16:48 UTC, christophe-lunarg commented
`printf_to_stdout`, `printf_verbose`, `printf_buffer_size`, `gpuav_buffer_oob`, `validate_draw_indirect` should not be listed with macOS

`"key": "debug"`
Add `"view": "ADVANCED"` value.

Otherwise it's perfect.

2021-07-01 17:48 UTC, christophe-lunarg commented
Ok were a a big bug which caused the doc generation to not output some many settings. I have a PR to fix this for SDK 1.2.182.

Here is what the doc looks like now:
<html>
<body>
<!--StartFragment--><h1 id="top" style="color: rgb(164, 30, 34); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/khronos_validation_layer.html" style="color: rgb(164, 30, 34);">VK_LAYER_KHRONOS_validation</a></h1><h3 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Khronos Validation Layer</h3><p style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The main, comprehensive Khronos validation layer. Vulkan is an Explicit API, enabling direct control over how GPUs actually work. By design, minimal error checking is done inside a Vulkan driver. Applications have full control and responsibility for correct operation. Any errors in how Vulkan is used can result in a crash. The Khronos Valiation Layer can be enabled to assist development by enabling developers to verify their applications correctly use the Vulkan API.</p><h2 style="color: rgb(164, 30, 34); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="#top" style="color: rgb(164, 30, 34);">Layer Properties</a></h2><ul style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li>API Version: 1.2.176</li><li>Implementation Version: 1</li><li>Layer Manifest: VkLayer_khronos_validation.json<ul><li>File Format: 1.2.0</li><li>Layer Binary Path: .\VkLayer_khronos_validation.dll</li></ul></li><li>Platforms:<span> </span><span class="code" style="color: rgb(0, 128, 0); font-family: consolas;">WINDOWS,<span> </span><span class="code" style="color: rgb(0, 128, 0); font-family: consolas;">LINUX,<span> </span><span class="code" style="color: rgb(0, 128, 0); font-family: consolas;">MACOS,<span> </span><span class="code" style="color: rgb(0, 128, 0); font-family: consolas;">ANDROID</span></span></span></span></li><li><a href="#settings" style="color: rgb(164, 30, 34);">Number of Layer Settings: 6</a></li><li><a href="#presets" style="color: rgb(164, 30, 34);">Number of Layer Presets: 6</a></li></ul><p style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Visit<span> </span><a href="https://vulkan.lunarg.com/doc/sdk/latest/windows/khronos_validation_layer.html" style="color: rgb(164, 30, 34);">VK_LAYER_KHRONOS_validation home page</a><span> </span>for more information.</p><h2 style="color: rgb(164, 30, 34); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="#top" id="settings" style="color: rgb(164, 30, 34);">Layer Settings Overview</a></h2>

Setting | Type | Default Value | vk_layer_settings.txt Variable | Environment Variable | Platforms
-- | -- | -- | -- | -- | --
Debug Action | FLAGS | VK_DBG_LAYER_ACTION_LOG_MSG | khronos_validation.debug_action | N/A | WINDOWS, LINUX, MACOS
Message Severity | FLAGS | error,warn,perf | khronos_validation.report_flags | N/A | WINDOWS, LINUX, MACOS
Duplicated Messages Limit | INT | 10 | khronos_validation.duplicate_message_limit | VK_LAYER_DUPLICATE_MESSAGE_LIMIT | WINDOWS, LINUX, MACOS
Mute Message VUIDs | LIST |   | khronos_validation.message_id_filter | VK_LAYER_MESSAGE_ID_FILTER | WINDOWS, LINUX, MACOS
Disables | FLAGS | VK_VALIDATION_FEATURE_DISABLE_THREAD_SAFETY_EXT | khronos_validation.disables | VK_LAYER_DISABLES | WINDOWS, LINUX, MACOS
Enables | FLAGS |   | khronos_validation.enables | VK_LAYER_ENABLES | WINDOWS, LINUX, MACOS

<h2 style="color: rgb(164, 30, 34); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="#top" id="presets" style="color: rgb(164, 30, 34);">Layer Presets</a></h2><h3 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Standard</h3><p style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Good default validation setup that balance validation coverage and performance.</p><h4 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: [...]

2021-07-01 17:50 UTC, jeremyg-lunarg commented
> `"key": "debug"`
> Add `"view": "ADVANCED"` value.

I had to use HIDDEN to get this one to go away.

2021-07-01 17:58 UTC, jeremyg-lunarg commented on layers/json/VkLayer_khronos_validation.json.in
> +                            "platforms": [ "WINDOWS"]
@christophe-lunarg  I added this...

2021-07-01 17:58 UTC, jeremyg-lunarg commented on layers/json/VkLayer_khronos_validation.json.in
> +                            "view": "HIDDEN"
and this.

2021-07-01 18:22 UTC, christophe-lunarg approved these changes
Perfect

2021-07-01 18:22 UTC, christophe-lunarg commented on layers/json/VkLayer_khronos_validation.json.in
> +                            "platforms": [ "WINDOWS", "LINUX", "MACOS", "ANDROID" ]
"key": "printf_to_stdout", doesn't have 
"platforms": [ "WINDOWS", "LINUX" ]

2021-07-01 18:32 UTC, merged