Fix handling of separate depth-stencil layouts
KhronosGroup/Vulkan-ValidationLayers pull request #2940
Opened 2021-07-05 15:21 UTC by HansKristian-Work

In vkd3d-proton, I ran into many issues with image layout tracking. The main issue is that while the current validation layers track layout per aspect, the validation code would naively check the layout for all aspects at a time, leading to non-sensical errors where a depth-stencil layout would be compared against the stencil layout. The code also didn't handle the `VK_IMAGE_LAYOUT_{DEPTH,STENCIL}_{ATTACHMENT,READ_ONLY}_OPTIMAL` layouts in normalization path. The spec says that the combined image layout enums are equivalent to the separate ones, so the added test case should be in-spec as far as I can tell.

I added a reasonable exhaustive test here that trips all the cases I found.

I'm not sure if I did it the right way since I've never poked into this part of the validation layers before.

The fix was essentially to loop over all aspects one by one, and then calling MatchLayout with a specific aspect.

2021-07-06 13:59 UTC, jeremyg-lunarg commented
Thanks for the fixes! This looks good to me but I'm going to run it through some more extensive parts of our internal test suite before merging.

2021-07-07 03:04 UTC, jeremyg-lunarg requested changes
Found two minor problems, but other than that looks good and testing isn't finding anything that looks problematic.

2021-07-08 10:06 UTC, HansKristian-Work commented on layers/buffer_validation.cpp
>                                                                     ? const_p_cb->GetImageSubresourceLayoutMap(image)
Should be fixed.

2021-07-08 10:06 UTC, HansKristian-Work commented on tests/vkpositivelayertests.cpp
> +    fence.wait(UINT64_MAX);
Fixed.

2021-07-08 14:37 UTC, jeremyg-lunarg approved these changes
LGTM

2021-07-08 14:37 UTC, merged