layers: Handle pNext usage of VkBufferOpaqueCaptureAddressCreateInfo
KhronosGroup/Vulkan-ValidationLayers pull request #2959
Opened 2021-07-13 14:28 UTC by rumblehhh

If an opaque buffer address is available by means other than vkGetBufferDeviceAddress/vkGetBufferDeviceAddressKHR/vkGetBufferDeviceAddressEXT a buffer may be requested to be created using this handle (as may be the case with capture/playback tools). In this case calling vkGetBufferDeviceAddress/vkGetBufferDeviceAddressKHR/vkGetBufferDeviceAddressEXT is redundant and may be skipped.

2021-07-13 17:55 UTC, ncesario-lunarg reviewed
Thanks for the change! LGTM, but may need this for the state tracker as well.

2021-07-13 17:55 UTC, ncesario-lunarg commented on layers/gpu_validation.cpp
> +            buffer_map[opaque_capture_address->opaqueCaptureAddress] = pCreateInfo->size;
Looks like this should also be done in `ValidationStateTracker` for updating `BUFFER_STATE::deviceAddress` appropriately?

2021-07-13 17:56 UTC, ncesario-lunarg commented
Looks like the subject line is just a [bit too long](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2959/checks?check_run_id=3057894195#step:4:20).

2021-07-13 19:54 UTC, ncesario-lunarg commented on layers/gpu_validation.cpp
> +    if (pCreateInfo) {
You'll need to add `ValidationStateTracker::PostCallRecordCreateBuffer(device, pCreateInfo, pAllocator, pBuffer, result);`; otherwise crashes will ensue.

2021-07-13 19:55 UTC, ncesario-lunarg requested changes
Please see comment where to add `ValidationStateTracker::PostCallRecordCreateBuffer(device, pCreateInfo, pAllocator, pBuffer, result);`.

2021-07-14 13:21 UTC, rumblehhh commented
I think I've addressed all your feedback now as well as passing the CI builds

2021-07-14 15:17 UTC, ncesario-lunarg commented on layers/state_tracker.cpp
> +    if (pCreateInfo) {
👍

2021-07-14 15:17 UTC, ncesario-lunarg commented on layers/gpu_validation.cpp
> +    if (pCreateInfo) {
Looks like this one is still missing. Still seeing failures on internal CI.

2021-07-14 16:33 UTC, Tony-LunarG approved these changes
LGTM once ValidationStateTracker call is added and CI passes

2021-07-15 08:16 UTC, rumblehhh commented on layers/gpu_validation.cpp
> +    if (pCreateInfo) {
Ah sorry I misunderstood this comment. I'm not massively familiar with the internals of the layers (although an avid user!)
This should be addressed now

2021-07-15 15:42 UTC, ncesario-lunarg commented on layers/gpu_validation.cpp
> +    if (pCreateInfo) {
That's ok! I'm learning too, and probably would have done what you did :)

The base class `ValidationStateTracker` creates the `VkBuffer -> BUFFER_STATE` map which will be necessary other places.

Thanks for the fix!

2021-07-15 15:43 UTC, ncesario-lunarg approved these changes

2021-07-26 19:59 UTC, Tony-LunarG commented
CI run after rebase passed

2021-07-26 19:59 UTC, merged