tests: Work around failing tests on Intel Mesa
KhronosGroup/Vulkan-ValidationLayers pull request #3013
Opened 2021-07-20 09:58 UTC by nisse-work

Problematic tests are disabled with an IsDriver check. This makes the testsuite pass when I run it on 

  Driver Name = Intel open-source Mesa driver
  Driver Info = Mesa 20.3.4

Still not quite reliable; running individual tests seems to fail, e.g., running

VK_LAYER_PATH=layers ./tests/vk_layer_validation_tests  --gtest_filter='VkSyncValTest.SyncEventsCommandHazards'

crashes with a segmentation fault.

2021-07-20 13:27 UTC, sfricke-samsung commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +        // Test produces validation error VUID-VkBindImageMemoryInfo-pNext-01619
looking at the test, I am curious why this is throwing `01619` as it called `vkGetImageMemoryRequirements2` with `VK_IMAGE_ASPECT_PLANE_0_BIT` and used the memoryType

Also does it not throw both errors? because the `01620`  tests should be only ran if the alignment is greater then 1 and therefore could be triggered

2021-07-20 17:21 UTC, ncesario-lunarg commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +        // Test produces validation error VUID-VkBindImageMemoryInfo-pNext-01619
@nisse-work do you have any ideas as to why this VUID is incorrectly getting logged?

Usually when we disable a test on a particular driver, it is because the test causes a crash in the driver and there is no way to work around the driver crash. An incorrectly logged VUID sounds like maybe the test is wrong and/or there is a bug in the VL.

2021-07-22 09:20 UTC, nisse-work commented
> Still not quite reliable; running individual tests seems to fail, e.g., running
> 
> VK_LAYER_PATH=layers ./tests/vk_layer_validation_tests --gtest_filter='VkSyncValTest.SyncEventsCommandHazards'
> 
> crashes with a segmentation fault.

I think this worries me a bit, since there seems to be some hidden dependency between tests. E.g., running
```
VK_LAYER_PATH=layers ./tests/vk_layer_validation_tests  --gtest_filter='VkPositiveLayerTest.*'
```
succeeds with these changes, but explicitly running only the second test (the one after the one I'm disabling) fails:

```
VK_LAYER_PATH=layers ./tests/vk_layer_validation_tests  --gtest_filter='VkPositiveLayerTest.ToolingExtension
...
[ RUN      ] VkPositiveLayerTest.ToolingExtension
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Segmentation fault
```

I think the gtest design is that the test fixture should be destroyed and recreated between tests, but maybe there's some state outside of the test fixture that survives and affects following tests?

2021-07-22 18:56 UTC, ncesario-lunarg commented
> I think this worries me a bit

Worrying indeed! We've had some similar problems in the past.
- Do you know if this is crashing in the driver or VVL?
- Any chance you can reduce the number of tests run before that one crashes (via `--gtest_filter`)?

2021-07-23 07:28 UTC, nisse-work commented
> * Do you know if this is crashing in the driver or VVL?

Good question.  I've tried out a few different variations of the environment variable settings, and it seems this particular crash is triggered by VK_LAYER_TESTS_PRINT_DRIVER=1 (!).

This crashes:

```
 VK_LAYER_TESTS_PRINT_DRIVER=1 VK_LAYER_PATH=layers ./tests/vk_layer_validation_tests --gtest_filter='VkPositiveLayerTest.ToolingExtension'
```
If I drop VK_LAYER_PATH (so that loading validation layers fail), it *still* crashes. If I drop the VK_LAYER_TESTS_PRINT_DRIVER, the test passes.

I quick check in gdb indicates that it's the call to

            vk::GetPhysicalDeviceProperties2(gpu_, &physical_device_properties2);

that jumps via a null pointer. even though the call is guarded with an

```
        if (InstanceExtensionSupported(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME)) {
```

Maybe it's supported by the driver but for some reason not enabled on the instance (I don't grasp all the fine details of extensions)?
 
> * Any chance you can reduce the number of tests run before that one crashes (via `--gtest_filter`)?

Invocation uses --gtest_filter='VkPositiveLayerTest.ToolingExtension', so there's only that single test being run.

2021-07-23 16:00 UTC, ncesario-lunarg commented
The `VK_LAYER_TESTS_PRINT_DRIVER` crash is present on Mesa RADV as well; I'll submit a PR for that.

Do you think this is related to the "incorrectly logged VUIDs"?

2021-07-26 08:18 UTC, nisse-work commented
> The `VK_LAYER_TESTS_PRINT_DRIVER` crash is present on Mesa RADV as well; I'll submit a PR for that.

I guess that's good news: easy to repro, and likely not a driver bug.
 
> Do you think this is related to the "incorrectly logged VUIDs"?

I can only guess, and my guess is that it's unrelated.

2021-08-11 13:58 UTC, nisse-work commented
Rebased on top of the latest changes. I could take out a few of the workarounds.

2021-08-11 17:27 UTC, jeremyg-lunarg commented
This PR fixes all tests for me on Ubuntu 20.04 with mesa-vulkan-drivers:amd64 21.0.3-0ubuntu0.2~20.04.1

Also, I can run the individual test you mentioned without crashing.

2021-08-11 20:11 UTC, jeremyg-lunarg reviewed
I haven't looked at VkPositiveLayerTest, CreatePipelineWithCoreChecksDisabled yet, but many of these were caused by a bug in state_tracker.cpp

2021-08-11 20:11 UTC, jeremyg-lunarg commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +        // Test produces validation error VUID-VkBindImageMemoryInfo-pNext-01619
this is caused by a bug in the state tracker. See: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3156

2021-08-11 20:11 UTC, jeremyg-lunarg commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +        // Test produces validation error VUID-VkBindImageMemoryInfo-pNext-01619
This test is also fixed by #3156

2021-08-11 20:11 UTC, jeremyg-lunarg commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +        printf("%s This test should not be run on the Intel Mesa driver\n", kSkipPrefix);
This test works for me with mesa-vulkan-drivers:amd64  21.0.3-0ubuntu0.2~20.04.1 but it is most likely related to #3156 as well

2021-08-11 20:35 UTC, jeremyg-lunarg requested changes
Unless I'm missing one, I think we have fixes for all of the failing tests, in #3154, #3156 and #3157.  @nisse-work if you agree we've got them all, can you close this PR? Thanks!

2021-08-11 20:35 UTC, jeremyg-lunarg commented on tests/vkpositivelayertests.cpp
> +    if (IsDriver(VK_DRIVER_ID_INTEL_OPEN_SOURCE_MESA)) {
This is a test bug, https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3157

2021-08-12 07:29 UTC, nisse-work commented
Closing, I'll reopen (or make a new one) if it turns out there are remaining problems after pending fixes are merged. Thanks!

2021-08-12 07:29 UTC, closed without merging