layers: Fix state tracking of Surfaces, Swapchains and Images
KhronosGroup/Vulkan-ValidationLayers pull request #3025
Opened 2021-07-21 21:58 UTC by jeremyg-lunarg

PRs #2964 and #2980 made bad assumptions about how these objects interact, especially how SWAPCHAIN_IMAGE::bound_images was handled. 

Remove SWAPCHAIN_NODE::bound_images, which was used to allow all images bound to the same swapchain and index to share the same fake virtual address for sync validation. Instead, store a fake address in SWAPCHAIN_IMAGE and allow Swapchains to have Images as their parent. This allows Swapchain and VK_IMAGE_CREATE_ALIAS_BIT aliasing to work in almost the same way. This also lets bound Images be invalidate if their Swapchain or Surface gets destroyed.
    
Give SWAPCHAIN_NODE a back pointer to the state tracker so that  its Destroy() can remove Images from the device level handle map.

Fake address lookup is now hidden behind a BINDABLE / IMAGE_STATE method. This should make it easier to add addresses for sparse buffers and images at some point.

Swapchains should be the parent their Surface in the object tracking tree because destroying the Surface will invalidate the Swapchain. Make their state objects follow the convention of 'parent holds shared_ptr on child object'.
    
Because Surfaces are tracked at the Instance level, Swapchains need to be explicitly destroyed in DestroyDevice() to avoid potential accesses to the Device level state after it is destroyed. VkBestPracticesLayerTest.ValidateReturnCodes + ASan hits this condition.

2021-07-23 19:11 UTC, ncesario-lunarg reviewed
This LGTM, though I'm not familiar with the details of the fake addresses. And I greatly appreciate the comments :)

2021-07-23 19:11 UTC, ncesario-lunarg commented on layers/image_state.h
> +// Parent -> child relationships in the object usage tree:
Nice to have this :)

2021-07-23 23:52 UTC, jzulauf-lunarg reviewed
I'm a bit concerned with the unlinking of aliases not being consistent (and not DRY) and the FakeAllocator 0 address being valid (given the compare to zero test used on it).

The AddParent reversal is concerning/confusing but probably right

2021-07-23 23:52 UTC, jzulauf-lunarg commented on layers/state_tracker.cpp
> +            if (!swapchain_image.fake_base_address) {
see note re: FakeAllocator above.

2021-07-23 23:52 UTC, jzulauf-lunarg commented on layers/state_tracker.cpp
> +        surface_state->AddParent(swapchain.get());
Why have we reverse parent and child?  The surface state must outlive the swapchain. Deleting the surface makes the swap chain invalid.

2021-07-23 23:52 UTC, jzulauf-lunarg commented on layers/state_tracker.cpp
> +    RecordCreateSwapchainState(result, pCreateInfo, pSwapchain, std::move(surface_state), old_swapchain_state);
This is good. Avoid atomic ops with refs and moves...

2021-07-23 23:52 UTC, jzulauf-lunarg commented on layers/state_tracker.cpp
> +        surface_state->AddParent(swapchain.get());
Wait.. this could be correct.  The "parent" name is confusing as we're adding dependent nodes, i.e. nodes that become invalid if the current node becomes invalid.

2021-07-26 16:28 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +                if (!swapchain_image.fake_base_address) {
making fake_base_address be optional<> avoids complicating the fake allocator.

2021-07-26 16:28 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +        surface_state->AddParent(swapchain.get());
I agree that parent is confusing, but... what is  better name?

2021-07-26 16:29 UTC, jeremyg-lunarg commented on layers/image_state.cpp
> +    if (bind_swapchain) {
done. and passes unit tests with ASan on.

2021-07-26 16:29 UTC, jeremyg-lunarg commented on layers/image_state.cpp
>        create_from_swapchain(swapchain),
done.

2021-07-26 21:12 UTC, jzulauf-lunarg requested changes
1 logic issue (last comment).  1 styleguide. 1 DRYness. 1 disagreement over FBA

2021-07-26 21:12 UTC, jzulauf-lunarg commented on layers/state_tracker.cpp
> +        surface_state->AddParent(swapchain.get());
stet.

2021-07-26 21:12 UTC, jzulauf-lunarg commented on layers/synchronization_validation.cpp
> +        SimpleBinding(static_cast<const BINDABLE &>(image_state)) || image_state.IsSwapchainImage() || !image_state.bind_swapchain;
That ! reverses the sense of the test re: bind_swapchain, doesn't it?  In the original, the last clause is *true* for valid bind_swapchain, but now it's true for invalid bind_swapchain.

2021-07-27 15:56 UTC, jeremyg-lunarg commented on layers/image_state.cpp
> +    UnlinkAliases();
Yep, and it's possible that this is an improvement that would benefit many of the other state objects.

2021-07-27 15:59 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +        } else if (image_state->create_from_swapchain != image_state->bind_swapchain->swapchain()) {
this is another of the 'convert handle storage in every class into common storage in BASE_NODE' methods... I'd like to come up with a clever way to clean these up and then do them all in one go.

2021-07-27 17:48 UTC, jzulauf-lunarg commented on layers/core_validation.cpp
> +        } else if (image_state->create_from_swapchain != image_state->bind_swapchain->swapchain()) {
I've thought about that, but all the returns are of different types so it's not something you could virtualize without returning  VulkanTypedHandle ... and that's a pain to get the real handle from, though if we're just looking for operator== and compare type and handle fields... that could be useful

2021-07-27 17:57 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +        } else if (image_state->create_from_swapchain != image_state->bind_swapchain->swapchain()) {
Looks like `BASE_NODE`'s only constructor is templated. Could we make `BASE_NODE` itself templated, then have `BASE_NODE::Handle` return the templated handle type?

2021-07-27 19:18 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +        } else if (image_state->create_from_swapchain != image_state->bind_swapchain->swapchain()) {
maybe... some other methods that take BASE_NODE* will have to be templated as well then.

2021-07-28 22:23 UTC, jzulauf-lunarg approved these changes
LGTM.

2021-07-29 14:09 UTC, merged