tests: Check properties function for valid pointer
KhronosGroup/Vulkan-ValidationLayers pull request #3045
Opened 2021-07-23 16:07 UTC by ncesario-lunarg

Mesa Intel and RADV (and possibly other drivers) are returning null for
vkGetPhysicalDeviceProperties2KHR when trying to print driver info. Add
a check before using this function.

See https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3013#issuecomment-885453863 for context.

FYI @nisse-work.

2021-07-23 16:19 UTC, jeremyg-lunarg approved these changes
LGTM assuming CI agrees

2021-07-26 08:31 UTC, nisse-work commented
> Mesa Intel and RADV (and possibly other drivers) are returning null for
> vkGetPhysicalDeviceProperties2KHR when trying to print driver info. Add
> a check before using this function.

Do you have any explanation why function pointer is null, despite the explicit  InstanceExtensionSupported query returning true?

2021-07-26 16:28 UTC, Tony-LunarG commented
I think that perhaps a better fix would be to add:
```
static bool driver_printed = false;
if (GetEnvironment("VK_LAYER_TESTS_PRINT_DRIVER") != "" && !driver_printed &&
        InstanceExtensionSupported(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME))
        instance_extensions_.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
```
before 
```
RemoveIf(instance_layers_, LayerNotSupportedWithReporting);
RemoveIf(instance_extensions_, ExtensionNotSupportedWithReporting);
``` 
and remove the static driver_printed  declaration below.

That seems to fix the problem on my RADV system

2021-07-26 16:28 UTC, Tony-LunarG requested changes
I think enabling the instance extension will fix this problem

2021-07-26 18:25 UTC, ncesario-lunarg commented
> Do you have any explanation why function pointer is null, despite the explicit InstanceExtensionSupported query returning true?

I think the problem is what @Tony-LunarG pointed out; namely, the instance extension was not getting enabled.

2021-07-26 18:59 UTC, Tony-LunarG approved these changes
LGTM - Thanks

2021-07-26 20:58 UTC, merged