Fix some instances of -Wunused-but-set-variable.
KhronosGroup/Vulkan-ValidationLayers pull request #3058
Opened 2021-07-26 14:37 UTC by pkasting

Bug: chromium:1203071

2021-07-26 14:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3058) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3058) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3058) it.</sub>

2021-07-26 16:48 UTC, sfricke-samsung commented on layers/generated/chassis.cpp
> -    bool skip = false;
this will need to be changed in the source file as this is a generated file
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/scripts/layer_chassis_generator.py#L1022-L1026

2021-07-26 16:49 UTC, sfricke-samsung commented on layers/generated/chassis.cpp
> -    bool skip = false;
to regenerate you can run

`python3 scripts/generate_source.py path/to/Vulkan-Headers/registry`

2021-07-26 21:50 UTC, ncesario-lunarg requested changes

2021-07-26 21:50 UTC, ncesario-lunarg commented on layers/generated/chassis.cpp
> -    bool skip = false;
+1 (https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/6b447aaa3a670998c564c9ac901d5cfd99abfbcf/scripts/layer_chassis_generator.py#L1026).

If you're using cmake, you can "build" the `VulkanVL_generated_source` target to run the generate scripts with the Vulkan-Headers downloaded from `scripts/known_good.json`.

2021-07-28 00:24 UTC, pkasting commented on layers/generated/chassis.cpp
> -    bool skip = false;
Thanks!  Fixed the .py file and removed the commented-out reference to (skip) while at it.

I'm not actually using cmake -- I'm developing inside Chromium, which has its own build system.  But AFAICT I've tweaked the right bits here now.

2021-07-28 18:23 UTC, ncesario-lunarg commented
@pkasting if you could please change the commit message to something along the lines of `layers: Fix some instances of -Wunused-but-set-variable` (i.e., adding a "component label" at the beginning of the subject line, and removing the period from the subject line), I think this should be GTG (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3058/checks?check_run_id=3183388694#step:4:20)!

2021-07-29 13:25 UTC, pkasting commented
Done, I hope!

2021-07-29 17:33 UTC, ncesario-lunarg approved these changes

2021-07-29 21:49 UTC, merged