[WIP] build: Refactor Android build
KhronosGroup/Vulkan-ValidationLayers pull request #3088
Opened 2021-07-30 17:58 UTC by ncesario-lunarg

Android build refactor:
- Removes dependency on ndk-build/Android.mk build tools
- Remove shaderc dependency in the Android build for tests
- Use single `known_good.json` for desktop and Android

Still WIP:
- Adding an "easy" way to build and package multiple architectures (may or may not be needed depending on CI)
- Still investigating some test failures

Creating this now to get early feedback on the build process. In short, setting up an Android build would look something like:
```bash
cmake -GNinja -Bbuild-android-cmake \
  -DCMAKE_BUILD_TYPE=Debug \
  -DUPDATE_DEPS=ON \
  -DCMAKE_TOOLCHAIN_FILE=<ndk-path>/build/cmake/android.toolchain.cmake \
  -DANDROID_NDK_HOME=<ndk-path> \
  -DANDROID_SDK_HOME=<sdk-path> \
  -DANDROID_PLATFORM=26 \
  -DANDROID_BUILD_TOOLS=31.0.0-rc1 \
  -DANDROID_ABI=arm64-v8a \
  -DANDROID_STL=c++_static
```
I removed the need for using environment variables to set `ANDROID_{S,N}DK_HOME` as I'm not personally a fan of this (though you can still do it that way if you prefer with this change). Also, using `UPDATE_DEPS=ON` this should be a similar "one-time-setup" as with desktop.

FYI @Tony-LunarG @jeremyg-lunarg @ziga-lunarg @mikes-lunarg.

FYI @lunarpapillo @johnzupin as this would eventually require some changes to CI. The big one (I'm guessing) is that each arch would need its own cmake build (instead of specifying all archs in `Application.mk`).

2021-07-30 18:04 UTC, jeremyg-lunarg commented
This is one of my favorite things ever.  Will the final version get rid of the various .mk files or other stuff under build-android?

2021-07-30 18:04 UTC, ncesario-lunarg commented on layers/libVkLayer_khronos_validation.map
> +    vkEnumerateDeviceLayerProperties;
This is apparently required for the Android loader (at least older versions of the Android loader).

2021-07-30 18:54 UTC, mikes-lunarg commented
> Use single known_good.json for desktop and Android

Great!

2021-07-30 19:00 UTC, mark-lunarg commented
@cnorthrop, @ben-clayton, @ggfan, @timvpGoogle, y'all may have some interest in this PR -- if not, that's useful info too!

2021-09-21 22:30 UTC, lunarpapillo requested changes
Woot!  Excited to see this come to fruition...

2021-09-21 22:30 UTC, lunarpapillo commented on scripts/github_ci_android.py
> +        unzip_cmd = 'unzip -u -q android-ndk-r21d-linux-x86_64.zip'
This works.... but there is a native Python `zip` module that can do this in a more Pythonesque way

2021-09-21 22:30 UTC, lunarpapillo commented on scripts/github_ci_android.py
> +        wget_cmd = 'wget http://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip'
Generally, it's better to use list commands than string commands, e.g.:
```
wget_cmd = ['wget', 'http://dl.google.com/android/repository/android-ndk-r21d-linu-x86_64.zip']
```
because there's no dependency on a particular shell's splitting and quoting behaviors.

Also, we've been requested by Google to test with an NDK that's no older than 6 months or so.  I don't know whether this should matter for GitHub CI, but I wanted you to be aware.

2021-09-21 22:30 UTC, lunarpapillo commented on scripts/common_ci.py
> +        cmd_list = command.split(" ")
This is a bit dubious, as it doesn't take into consideration shell quotes or splitting behaviors.  I think it'll work for all the purposes I've seen here, but it's a bit clumsy.

Preferred answer is to always pass commands as lists, which avoids quoting and splitting problems.

Secondary answer would be to pass the string command and `shell=True` to `subprocess.check_call()`, and let the host shell manage quotes and splitting.

2021-09-21 22:30 UTC, lunarpapillo commented on scripts/github_ci_android.py
> +    ndk_build_cmd = f'make -j{os.cpu_count()}'
Alternatively:
```
ndk_build_cmd = ['make', '-j', str(os.cpu_count())]
```

2021-09-21 22:30 UTC, lunarpapillo commented on scripts/known_good.json
> +    {
Why is **Vulkan-Tools** required now?

2021-09-21 22:30 UTC, lunarpapillo commented on scripts/update_deps.py
> +        dir_top = os.path.abspath(args.dir)
Changes to `update_deps.py` should be propagated through all our repositories... have fun!

2021-09-21 22:30 UTC, lunarpapillo commented on scripts/update_deps.py
> +            helper_file.write(f'set({repo.name.replace("-","_").upper()}_SOURCE_DIR "{escape(repo.src_dir)}" CACHE STRING "" FORCE)\n')
Shouldn't this be below the `if install_names and repo.name in install_names and repo.on_build_platform` check below?

It would be nice if both `helper_file.write()` commands used the same method of string formatting (so they don't look completely different).

2021-09-21 22:30 UTC, lunarpapillo commented on tests/CMakeLists.txt
> +    add_executable(${layer_test_target_}
Does the trailing `_` reflect a convention I'm not familiar with?

2021-09-21 22:30 UTC, lunarpapillo commented on tests/layers/CMakeLists.txt
> +elseif(UNIX AND (NOT (APPLE OR ANDROID))) # i.e.: Linux
We already know `NOT APPLE` here, right?  Because of the `elsif(APPLE)` above?

Moving the below `elsif(ANDROID)` above this could simplify the expression to just `elseif(UNIX)`.

2021-09-21 22:30 UTC, lunarpapillo commented on tests/platforms/android/res/values/strings.xml
> +<!-- Copyright 2016 The Android Open Source Project
This is taken from somewhere else?  Or should the copyright be updated?

2021-09-23 17:29 UTC, ncesario-lunarg commented on BUILD.md
> +cmake -GNinja -Bbuild-android-cmake \
That is correct; this is likely a copy/paste leftover.

2021-09-23 17:34 UTC, ncesario-lunarg commented on BUILD.md
> +adb shell am start -a android.intent.MAIN -c android-intent.categeory.LAUNCH -n com.example.VulkanLayerValidationTests/android.app.NativeActivity --es args --gtest_catch_exceptions=0
Not sure what I'm doing wrong, but if I don't have this and I don't add any other `--gtest_*` args, none of the tests run :man_shrugging:

2021-09-23 20:54 UTC, ncesario-lunarg commented on scripts/known_good.json
> +    {
The android build requires something from Vulkan-Tools (it is one of the differences between the "desktop" known_good.json and Android's known_good.json)...but now I can't recall what. I'll double check this; maybe it can be removed.

2021-09-23 20:58 UTC, ncesario-lunarg commented on scripts/known_good.json
> +    {
Looks like this is just required for `vulkan_wrapper.{h,cpp}`, which is in the NDK. I'll see if I can remove this and just refer to the one in the NDK.

2021-09-23 21:04 UTC, ncesario-lunarg commented on scripts/update_deps.py
> +        dir_top = os.path.abspath(args.dir)
Afraid I'll be the proverbial "stick in the mud" on that one ;)

Changes in one repo should not effect others. As I've expressed previously, this is fundamentally broken IMHO. I'll wait until this gets resolved before moving ahead with this change if need be (even if I'm the one eventually making the changes :grimacing:)

2021-09-23 21:55 UTC, ncesario-lunarg commented on tests/CMakeLists.txt
> +    add_executable(${layer_test_target_}
Nope! Just something I tend to do in order to help differentiate "local/non-cmake" variables from "official variables."

2021-09-23 22:01 UTC, ncesario-lunarg commented on tests/platforms/android/res/values/strings.xml
> +<!-- Copyright 2016 The Android Open Source Project
Correct, this was copied from `build-android/res/values/strings.xml` and was unchanged.

2021-09-23 22:05 UTC, ncesario-lunarg commented on scripts/github_ci_android.py
> +        unzip_cmd = 'unzip -u -q android-ndk-r21d-linux-x86_64.zip'
I agree with all of the python comments. Though can't say I will spend too much time on these scripts as I would much rather use _your_ CI scripts when they become available ;)

2022-11-22 17:56 UTC, juan-lunarg commented
Closing this PR. CMake has changed drastically. I'll definitely refer to this PR in the future though when I try and tackle this.

2022-11-22 17:56 UTC, closed without merging

2023-04-24 18:27 UTC, juan-lunarg commented on layers/libVkLayer_khronos_validation.map
> +    vkEnumerateDeviceLayerProperties;
These are being exported via VVL_EXPORT right now.