Adding vuid 04809
KhronosGroup/Vulkan-ValidationLayers pull request #3128
Opened 2021-08-04 23:19 UTC by ziga-lunarg

Check if pipeline has discard rectangle dynamic state when inherited viewports and discard rectangles are used

2021-08-09 14:41 UTC, jeremyg-lunarg requested changes
VVL looks good, it'd be nice to have an additional test check to cover both ways to get the error.

2021-08-09 14:41 UTC, jeremyg-lunarg commented on tests/vklayertests_viewport_inheritance.cpp
> +}
what about the opposite case of the discard rectangle being state but the pipeline is not dynamic?

2021-08-09 21:46 UTC, ziga-lunarg commented on tests/vklayertests_viewport_inheritance.cpp
> +}
Does that case fall under this VUID? Not sure I'm understanding this correctly.

2021-08-10 14:50 UTC, jeremyg-lunarg commented on tests/vklayertests_viewport_inheritance.cpp
> +}
Nevermind, I was just looking at the logic of the new check. But it looks like I got confused.

2021-08-10 14:50 UTC, jeremyg-lunarg approved these changes

2021-08-12 14:35 UTC, merged