Adding vuid 02651
KhronosGroup/Vulkan-ValidationLayers pull request #3139
Opened 2021-08-07 19:52 UTC by ziga-lunarg

When creating a renderPass, if pNext chain of VkSubpassDescripton2 contains pDepthStencilResolveAttachment and attachment is not unused, its format features must support VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT

2021-08-09 02:01 UTC, sfricke-samsung commented on layers/core_validation.cpp
> +            const VkFormatFeatureFlags tiling_features = format_properties.optimalTilingFeatures;
So I realize the issue is `VUID-VkSubpassDescriptionDepthStencilResolve-pDepthStencilResolveAttachment-02651` is not properly written in the spec like `VUID-VkSubpassDescription2-pDepthStencilAttachment-02900`

but this should be using `GetPotentialFormatFeatures` or else someone will have some fun edge case using AHB that hits a false positive here

2021-08-09 14:34 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +            const VkFormatFeatureFlags tiling_features = format_properties.optimalTilingFeatures;
Good point, hopefully running the unit tests on Android devices will cover this case

2021-08-09 14:36 UTC, jeremyg-lunarg requested changes
@sfricke-samsung 's comment needs to be addressed, otherwise LGTM.

2021-08-09 14:36 UTC, sfricke-samsung commented on layers/core_validation.cpp
> +            const VkFormatFeatureFlags tiling_features = format_properties.optimalTilingFeatures;
https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/4758 for the record

2021-08-10 12:40 UTC, oddhack commented on layers/core_validation.cpp
> +            const VkFormatFeatureFlags tiling_features = format_properties.optimalTilingFeatures;
This should be fixed in the 1.2.188 spec update.

2021-08-23 15:19 UTC, jeremyg-lunarg approved these changes
LGTM

2021-08-23 15:22 UTC, merged