Fix issue 1596
KhronosGroup/Vulkan-ValidationLayers pull request #3141
Opened 2021-08-08 13:56 UTC by ziga-lunarg

Closes #1596

Check if shared memory used by compute shader exceeds VkPhysicalDeviceLimits::maxComputeSharedMemorySize

2021-08-09 16:28 UTC, ncesario-lunarg requested changes
Some clarifying questions/requests, but I think this looks good!

2021-08-09 16:28 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +        return iter.word(3);
Wouldn't this return the _value_ of the constant, not the _type size_ (https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpConstant)? Based on the function name `get_type_size` I would have expected this to return the size of this type? I think there is already a `GetConstantValue` helper function; I would vote for using that directly where it should be used here. (i.e., OpTypeArray, etc.).

2021-08-09 16:28 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +uint32_t CoreChecks::get_type_size(SHADER_MODULE_STATE const *src, spirv_inst_iter iter) const {
Seems like this should be a `SHADER_MODULE_STATE` member function.

2021-08-09 16:28 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +uint32_t CoreChecks::get_type_size(SHADER_MODULE_STATE const *src, spirv_inst_iter iter) const {
`spirv_inst_iter` -> `const spirv_inst_iter&`?

2021-08-09 16:28 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +                                             spirv_inst_iter &insn) const {
Also seems like this should be a `SHADER_M0DULE_STATE` member function.

2021-08-09 16:28 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +                                             spirv_inst_iter &insn) const {
`spirv_inst_iter&` -> `const spirv_inst_iter&`?

2021-08-09 16:28 UTC, ncesario-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +    csSource << R"(
Might as well toss a `glsl` in there to pick up syntax highlighting in some environments?

2021-08-09 16:28 UTC, ncesario-lunarg commented on layers/core_validation.h
> +    uint32_t CalcComputeSharedMemory(SHADER_MODULE_STATE const* src, VkShaderStageFlagBits stage, spirv_inst_iter& insn) const;
Looks like these belong in `shader_module.*` and `SHADER_MODULE_STATE`.

2021-08-09 16:28 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +uint32_t CoreChecks::get_type_size(SHADER_MODULE_STATE const *src, spirv_inst_iter iter) const {
Since SPIR-V specifies type width in bits, might be good to make it explicit whether this is returning size in bits or bytes (e.g., `GetTypeByteSize`).

2021-08-11 10:58 UTC, ziga-lunarg commented on layers/shader_validation.cpp
> +        return iter.word(3);
Correct, that is actually what I wanted but it shouldn't be in this function.

2021-08-11 16:09 UTC, ncesario-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +    csSource << R"(
Strange, should be no difference (just a raw string). The following seems to work fine on gcc 11.1 and clang 12.0.1? What error are you seeing?
```cpp
    std::stringstream csSource;
    // Make sure compute pipeline has a compute shader stage set
    csSource << R"glsl(
        #version 450
        shared int a[)glsl";
    csSource << (max_shared_ints + 16);
    csSource << R"glsl(];
        void main(){
        }
    )glsl";
```

2021-08-11 16:20 UTC, ncesario-lunarg requested changes
Just a couple more nits/questions!

2021-08-11 16:20 UTC, ncesario-lunarg commented on layers/shader_module.cpp
> +        auto component_type = get_def(iter.word(2));
Could be `const` (here and elsewhere)?

2021-08-11 16:20 UTC, ncesario-lunarg commented on layers/shader_module.cpp
> +uint32_t SHADER_MODULE_STATE::GetConstantValue(const spirv_inst_iter &iter) const { return iter.word(3); }
Isn't this already define on line 1797?

2021-08-11 16:20 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +    if (total_shared_size > phys_dev_props.limits.maxComputeSharedMemorySize) {
This limit is in bytes, but isn't `total_shared_size` in bits?

2021-08-11 16:31 UTC, ziga-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +    csSource << R"(
Ah I forgot the `glsl`s in the middle, you're right this works fine.

2021-08-11 16:43 UTC, ziga-lunarg commented on layers/shader_validation.cpp
> +    if (total_shared_size > phys_dev_props.limits.maxComputeSharedMemorySize) {
Good catch.

2021-08-12 05:56 UTC, ncesario-lunarg approved these changes
Nice work!

2021-08-12 12:18 UTC, merged