Adding vuid 01525
KhronosGroup/Vulkan-ValidationLayers pull request #3142
Opened 2021-08-09 09:59 UTC by ziga-lunarg

If VkRenderPassSampleLocationBeginInfoEXT is needed, check if it matches VkPipelineSampleLocationStateCreateInfoEXT

2021-08-09 14:34 UTC, jeremyg-lunarg requested changes

2021-08-09 14:34 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                            LogError(pipeline, "VUID-vkCmdBindPipeline-variableSampleLocations-01525",
It might be nice to include the current subpass index in the output, even though this error message is already very long.

2021-08-09 14:34 UTC, jeremyg-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +}
Would it be feasible to add a few more cases to this test to cover the other ways to get this error:
-no VkRenderPassSampleLocationsBeginInfoEXT structure
-wrong (but valid) subpass index in the sample locations info

2021-08-09 14:36 UTC, ziga-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +}
Will do.

2021-08-23 15:20 UTC, jeremyg-lunarg approved these changes
LGTM

2021-08-23 15:23 UTC, merged