Fix issue 2304
KhronosGroup/Vulkan-ValidationLayers pull request #3143
Opened 2021-08-09 14:03 UTC by ziga-lunarg

Closes #2304 

Check if specialization for WorkGroupSize is within VkPhysicalDeviceLimits::maxComputeWorkGroupSize

2021-08-09 22:44 UTC, ncesario-lunarg requested changes
A few nits/questions/requests, but I think the core idea here looks good!

2021-08-09 22:44 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +                    memcpy(&value, (uint8_t *)spec->pData + spec->pMapEntries[i].offset, spec->pMapEntries[i].size);
`memcpy` necessary here? This code will only happen if size == 4, so there is no variable size to account for.

I'd personally prefer something like `std::copy` over `memcpy`, or something that gives the "option" for being more type safe.

2021-08-09 22:44 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +uint32_t GetSpecializationValue(SHADER_MODULE_STATE const *src, VkSpecializationInfo const *spec, spirv_inst_iter iter,
Looks like this function will always return 0 unless the OpSpecConstant is a 32 bit integer?

2021-08-09 22:44 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +bool CoreChecks::ValidateWorkgroupSize(SHADER_MODULE_STATE const *src, VkPipelineShaderStageCreateInfo const *pStage) const {
Looks like there is some overlap with https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/f1ea8fba12fadae976a96455e8fc897194669658/layers/shader_validation.cpp#L1865?

Maybe there is some way to use some of the specialization tracking there rather than looping through the spir-v again?

2021-08-09 22:44 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +            } else if (decoration == spv::DecorationSpecId) {
We effectively do this at https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/f1ea8fba12fadae976a96455e8fc897194669658/layers/shader_validation.cpp#L1297 as well. Maybe it's time to add this to `SHADER_MODULE_STATE` and avoid the duplicate map buildup?

2021-08-09 22:44 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +                        uint32_t workGroupSize = GetSpecializationValue(src, spec, constituent, spec_id);
`snake_case` for variables.

2021-08-09 22:44 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +                            const char *member = i == 0 ? "x" : i == 1 ? "y" : "z";
`const char member = 'x' + static_cast<int8_t>(i)`?

2021-08-09 22:44 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +                    memcpy(&value, (uint8_t *)spec->pData + spec->pMapEntries[i].offset, spec->pMapEntries[i].size);
For the memcpy, while we do have C-style casts in the code base, they are technically not allowed according to the [style guide](https://google.github.io/styleguide/cppguide.html#Casting), so we should probably avoid adding new ones.

2021-08-12 19:06 UTC, ncesario-lunarg commented on layers/shader_module.cpp
> +        if (opcode == spv::OpSpecConstantComposite) {
@sfricke-samsung any chance you know if this is required to be an `OpSpecConstantComposite`, or can it also be an `OpSpecConstant`? e.g., the following seems to pass `spirv-val`:
```
; SPIR-V
; Version: 1.5
; Generator: Khronos Glslang Reference Front End; 10
; Bound: 11
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %main "main"
               OpExecutionMode %main LocalSize 1 1 1
               OpSource GLSL 450
               OpName %main "main"
               OpDecorate %7 SpecId 3
               OpDecorate %7 BuiltIn WorkgroupSize
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
       %uint = OpTypeInt 32 0
          %7 = OpSpecConstant %uint 1
       %main = OpFunction %void None %3
          %5 = OpLabel
               OpReturn
               OpFunctionEnd
```

2021-08-18 16:00 UTC, sfricke-samsung commented on layers/shader_module.cpp
> +        if (opcode == spv::OpSpecConstantComposite) {
when running `spirv-val` make sure to use `--target-env vulkan1.2` 

```
spirv-val test.spv --target-env vulkan1.2
error: line 13: [VUID-WorkgroupSize-WorkgroupSize-04427] According to the Vulkan spec BuiltIn WorkgroupSize variable needs to be a 3-component 32-bit int vector. ID <3> (OpSpecConstant) is not an int vector.
  %gl_WorkGroupSize = OpSpecConstant %uint 1
```

but regardless, let me double check as I know there is another edge case for something else related to Workgroup sizes Vulkan doesn't allow that SPIR-V does

2021-08-19 16:06 UTC, sfricke-samsung commented on layers/shader_module.cpp
> +        if (opcode == spv::OpSpecConstantComposite) {
ok, @ncesario-lunarg the reason you **need** `OpSpecConstantComposite` is because of `VUID-WorkgroupSize-WorkgroupSize-04427` which requires a `int vec3` to declare the `WorkgroupSize` decoration

`OpSpecConstant` can is just a scalar, so you will never be able to declare it

Valid example btw:

```swift
               OpDecorate %x SpecId 0
               OpDecorate %y SpecId 1
               OpDecorate %z SpecId 2
               OpDecorate %workGroupSize BuiltIn WorkgroupSize
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
       %uint = OpTypeInt 32 0
      %uvec3 = OpTypeVector %uint 3
          %x = OpSpecConstant %uint 1
          %y = OpSpecConstant %uint 1
          %z = OpSpecConstant %uint 1
%workGroupSize = OpSpecConstantComposite %uvec3 %x %y %z ; turns scalars into uvec3
```

2021-08-19 16:09 UTC, sfricke-samsung commented on layers/shader_module.cpp
> +        if (opcode == spv::OpSpecConstantComposite) {
btw, 100% would add a comment in the code so no one has to look this up again :)

2021-08-23 19:13 UTC, merged