layers: Fix vkCreateImage memory reqs. check for multiplanar
KhronosGroup/Vulkan-ValidationLayers pull request #3156
Opened 2021-08-11 20:06 UTC by jeremyg-lunarg

Use vkGetImageMemoryRequirements2KHR instead of the non-KHR version
when querying the memory requirements for multiplanar images.

This fixes the following test cases on some devices:

VkLayerTest.BindInvalidMemory2Disjoint
VkLayerTest.BindInvalidMemoryNoCheck

2021-08-11 21:51 UTC, mikes-lunarg requested changes
Sadly, I think which entry point is available depends on the combination of core version and enabled extensions. On my intel machine, `VkApplicationInfo::apiVersion = 1.0` + `VK_KHR_get_memory_requirements2` only gives me the "2KHR" entry point, and `VkApplicationInfo::apiVersion = 1.1` + no extensions only gives me the "2" entry point.

2021-08-11 22:07 UTC, mikes-lunarg commented
I think the device extension list is more reliable than `apiVersion`, so I would check for `device_extensions.vk_khr_get_memory_requirements_2` before using `DispatchGetImageMemoryRequirements2KHR`, and fall back to `DispatchGetImageMemoryRequirements2` otherwise

2021-08-11 23:06 UTC, mikes-lunarg approved these changes
Great

2021-08-12 05:35 UTC, ncesario-lunarg approved these changes

2021-08-12 14:38 UTC, merged