Adding vuid 01983 01984, Validate ConditionalRenderingBeginInfo offset
KhronosGroup/Vulkan-ValidationLayers pull request #3191
Opened 2021-08-18 22:15 UTC by ziga-lunarg

Offset must be less than buffer size by 4 bytes and a multiple of 4

2021-08-19 03:59 UTC, sfricke-samsung commented on layers/core_validation.cpp
> +        if ((pConditionalRenderingBegin->offset & 3) != 0) {
I know I discussed a bit with @ncesario-lunarg about moving the common draw/dispatch stuff a bit, but the rest of the 

> offset must be a multiple of 4

are all in `parameter_validation_utils.cpp`

2021-08-19 04:40 UTC, ncesario-lunarg requested changes
I think after moving the 01984 check to stateless validation this should be good to go!

2021-08-19 04:40 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +        if ((pConditionalRenderingBegin->offset & 3) != 0) {
+1

In general anything that _can_ go into stateless validation should. Admittedly I've been less than vigilant on calling those cases out, though.

2021-09-01 21:22 UTC, ncesario-lunarg approved these changes

2021-09-23 12:50 UTC, merged