tests: Shader tests use Vulkan Version enum
KhronosGroup/Vulkan-ValidationLayers pull request #3195
Opened 2021-08-20 17:16 UTC by sfricke-samsung

Attempt to have all shader tests use the `SPV_ENV_VULKAN_*` enum conventions to keep everything consistent

2021-08-20 18:36 UTC, ncesario-lunarg requested changes
Looks good! I think just a couple changes are needed to get CI happy.

2021-08-20 18:36 UTC, ncesario-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +                                       SPV_ENV_VULKAN_1_1));
Looks like this needs to be `SPV_ENV_VULKAN_1_3`?

2021-08-20 18:36 UTC, ncesario-lunarg commented on tests/vktestframework.h
> +                   std::vector<unsigned int> &spv, bool debug = false, const spv_target_env spv_env = SPV_ENV_VULKAN_1_0);
I think the `SPV_ENV_VULKAN*` cases will need to be added to the `glslang::EShTargetLanguageVersion ToGlslangTargetEnv` function?

2021-08-20 20:24 UTC, sfricke-samsung commented on tests/vklayertests_pipeline_shader.cpp
> +                                       SPV_ENV_VULKAN_1_1));
Vulkan 1.3 or `SPV_ENV_UNIVERSAL_1_3` 😆 

Is this tests failing CI with `SPV_ENV_VULKAN_1_1`?

2021-08-20 22:00 UTC, ncesario-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +                                       SPV_ENV_VULKAN_1_1));
Yep, says 1.3 is required :)

2021-08-20 22:12 UTC, sfricke-samsung commented on tests/vklayertests_pipeline_shader.cpp
> +                                       SPV_ENV_VULKAN_1_1));
See this is where I am curious because Vulkan 1.1 should be enforcing SPIR-V 1.3

2021-08-20 22:17 UTC, ncesario-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +                                       SPV_ENV_VULKAN_1_1));
I think `SPV_ENV_VULKAN*` needs to be added the "conversion" functions (see other comment in review). Right now I'm pretty sure this will hit the "default" case as far as converting this to a "glslang enum." The problem I ran into (and why I only used the "universal enums," is that glslang has different types for "vulkan" and "spirv." Might be able to "templatize" the return of the conversion function to get around this, but I didn't attempt that route (there are probably better, more elegant routes I could not think of).

2021-08-20 22:18 UTC, sfricke-samsung commented on tests/vklayertests_pipeline_shader.cpp
> +                                       SPV_ENV_VULKAN_1_1));
ok, sounds good will look into this...

2021-08-23 15:50 UTC, ncesario-lunarg commented
@sfricke-samsung I cherry picked this change into #3199 as there were some changes that needed to be made to get the various `SPV_ENV_VULKAN*` enums working with glslang. If that looks good to you, I'll merge that and close this.

2021-08-23 16:07 UTC, ncesario-lunarg commented
This change has been incorporated into #3199.

2021-08-23 16:07 UTC, closed without merging