Adding vuid 04727, Validate image view format features support blend
KhronosGroup/Vulkan-ValidationLayers pull request #3228
Opened 2021-08-30 14:49 UTC by ziga-lunarg

Closes #2681

At draw active subpasses image views format features must contain VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT if pipelines blendEnabled is VK_TRUE

2021-08-30 19:11 UTC, ncesario-lunarg reviewed
I think this looks good, but looks like it doesn't address part of the issue:

> ValidateGraphicsPipelineBindPoint currently has VUID-VkGraphicsPipelineCreateInfo-blendEnable-04717 but should be moved back pipeline creation time as VU talks about the potential format features.

2021-08-30 19:11 UTC, ncesario-lunarg commented on tests/vklayertests_command.cpp
> +    m_errorMonitor->VerifyFound();
Additional draw necessary?

2021-08-30 19:32 UTC, ziga-lunarg commented
> I think this looks good, but looks like it doesn't address part of the issue:
> 
> > ValidateGraphicsPipelineBindPoint currently has VUID-VkGraphicsPipelineCreateInfo-blendEnable-04717 but should be moved back pipeline creation time as VU talks about the potential format features.

I have overlooked that, have moved it now. Also I swapped the order or parameters in the 04717 log message, I think it wasn't correct before, can you double check this for me?

2021-08-30 22:58 UTC, ncesario-lunarg reviewed
A couple more questions, but looks good.

2021-08-30 22:58 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> -                                 i, report_data->FormatHandle(image_state->image()).c_str(), string_VkFormat(format));
Yep, those arguments look backwards. Nice catch!

2021-08-30 22:58 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                            skip |= LogError(device, "VUID-VkGraphicsPipelineCreateInfo-blendEnable-04717",
The original issue specifically mentions moving this to CreateGraphicsPipelines; this function is only called at draw command time, correct?. While I'm not sure if it is necessary (@sfricke-samsung?), it would catch the error earlier which would be good.

It also seems like this check could be moved to stateless validation?

2021-08-31 09:41 UTC, sfricke-samsung commented on layers/core_validation.cpp
> +                            skip |= LogError(device, "VUID-VkGraphicsPipelineCreateInfo-blendEnable-04717",
ok so the entire [Potential Format Feature](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap43.html#potential-format-features) is something I had to create a while ago purely for validation (originally for the YCbCr stuff, but expanded to some other VUs)

At `vkCmdDraw*` time you actually know which framebuffer is going to be used, and with that you can know the  `VkImageCreateInfo::tiling` which is needed to know which format feature to check (this is `imageview_state->format_features` here)

The WG wanted to keep the VUID earlier at (in this case at Graphics Pipeline creation time) as that is where some drivers will go bad if the format does not support the feature in any fashion.

The idea of "potential" here is that `GetPotentialFormatFeatures` checks all the possible feature flags and unions them to see if any support that feature.

----

So `04717` should still be in `ValidateGraphicsPipelineBindPoint` and `vuid.blend_enable` should remain here

in your test you should use

```cpp
// gets pass pipeline creation but not the actual tiling used
formatProps.optimalTilingFeatures |= VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT;

// will be caught at draw time that feature for optimal image is not set
// InitRenderTarget() should be setting color attachment as VK_IMAGE_TILING_LINEAR
formatProps.linearTilingFeatures &= ~VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT;
```

2021-08-31 09:42 UTC, sfricke-samsung requested changes
see replied comment

2021-08-31 15:42 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                            skip |= LogError(device, "VUID-VkGraphicsPipelineCreateInfo-blendEnable-04717",
Thanks @sfricke-samsung!

2021-09-01 16:57 UTC, ncesario-lunarg reviewed
One question, but I think this looks good.

2021-09-01 16:57 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +bool CoreChecks::ValidateGraphicsPipelineBlendEnable(const PIPELINE_STATE *pPipeline) const {
Sorry if I missed this before, but why is this in `shader_validation`? Seems like it belongs in `core_validation`?

2021-09-01 17:00 UTC, ziga-lunarg commented on layers/shader_validation.cpp
> +bool CoreChecks::ValidateGraphicsPipelineBlendEnable(const PIPELINE_STATE *pPipeline) const {
This was added now, I will fix it.

2021-09-01 19:54 UTC, ncesario-lunarg approved these changes

2021-09-01 20:41 UTC, merged