Fix overlap descriptor set
KhronosGroup/Vulkan-ValidationLayers pull request #3267
Opened 2021-09-09 13:21 UTC by quehuo01

Descriptor set update wasn't handling an update larger than the size
of the original binding correctly (Writing multiple bindings with one update).
The specs says "If a binding has a descriptorCount of zero, it is skipped."

Pull request https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2908 has been closed due to my rebase.
Test has been tested with and without the fix. Test is failing without the fix.

2021-09-09 13:22 UTC, quehuo01 commented
CC @jeremyg-lunarg

2021-09-09 15:42 UTC, jeremyg-lunarg requested changes
Thanks for the fix! The validation change looks good but github CI is failing because:

1.  The test change  commit message needs to start with "tests:"
2.  It doesn't look like this test works with the MockICD. Probably it needs to be guarded with a check against maxInlineUniformBlockSize like in VkLayerTest.InlineUniformBlockEXT

2021-09-10 07:51 UTC, quehuo01 commented
@jeremyg-lunarg I addressed the requested changes.

2021-09-10 14:38 UTC, jeremyg-lunarg commented
It looks like this change is failing in our internal testing, but only on a Galaxy S10:
```
[ RUN      ] VkLayerTest.DescriptorUpdateOfMultipleBindingWithOneUpdateCall
jni/../../tests/vklayertests_descriptor_renderpass_framebuffer.cpp:10263: Failure
Expected equality of these values:
  res
    Which is: -1000069000
  VK_SUCCESS
    Which is: 0
```
Which is a  failing with VK_ERROR_OUT_OF_POOL_MEMORY. I'll try to see if I can find more information about the failure.

2021-09-10 22:40 UTC, jeremyg-lunarg commented
I haven't yet been able to figure out why vkAllocateDescriptorSets() is failing for one device.  Here are the full contents of VkPhysicalDeviceInlineUniformBlockPropertiesEXT on 2 of our android CI devices.

Galaxy S10 (fails):
```
	maxInlineUniformBlockSize=65536
	maxPerStageDescriptorInlineUniformBlocks=4
	maxPerStageDescriptorUpdateAfterBindInlineUniformBlocks=4
	maxDescriptorSetInlineUniformBlocks=4
	maxDescriptorSetUpdateAfterBindInlineUniformBlocks=4
```
Pixel 3a (passes):
```
	maxInlineUniformBlockSize=256
	maxPerStageDescriptorInlineUniformBlocks=32
	maxPerStageDescriptorUpdateAfterBindInlineUniformBlocks=32
	maxDescriptorSetInlineUniformBlocks=32
	maxDescriptorSetUpdateAfterBindInlineUniformBlocks=32

```

2021-09-10 22:46 UTC, jeremyg-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    m_errorMonitor->VerifyNotFound();
Just noticed that this test leaks handles for descLayout, descPool and descSet. They need to be freed here, or you can use vk_testing::DescriptorSetLayout and the other wrapper objects which will automatically free them.

2021-09-13 08:54 UTC, quehuo01 commented
The test is trying to allocate 8 inline uniform block in my understanding (2 float) that would explain why it is failing on Samsung S10
Going to change that, and skip the test if "maxPerStageDescriptorInlineUniformBlocks" is less than 2

2021-09-13 13:31 UTC, quehuo01 commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    m_errorMonitor->VerifyNotFound();
I addressed those, and I try to figure out what the issue could be with the S10 but I cannot see why it does fail, as we are within the limit as we've 2 descriptor block each of 4 bytes.

2021-09-13 18:40 UTC, jeremyg-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    m_errorMonitor->VerifyNotFound();
Yep, leak fixes look good.  To get the S10 to pass I just added a test skip if the descriptor set allocation fails.

2021-09-13 18:40 UTC, jeremyg-lunarg approved these changes

2021-09-13 18:40 UTC, merged