Add vuid 06372-06373, Validate spirv Workgroup initialization
KhronosGroup/Vulkan-ValidationLayers pull request #3297
Opened 2021-09-16 11:36 UTC by ziga-lunarg

Closes #3294

2021-09-16 15:22 UTC, sfricke-samsung commented on layers/core_validation.h
> +    bool ValidateRuntimeSpirv(SHADER_MODULE_STATE const* src, spirv_inst_iter& insn) const;
So awhile ago I made a similar function

```
// Validate runtime usage of various opcodes that depends on what Vulkan properties or features are exposed
bool CoreChecks::ValidatePropertiesAndFeatures(SHADER_MODULE_STATE const *module, spirv_inst_iter &insn) const {
```

which also has Runtime SPIR-V validation checks (`shaderSubgroupClock`/`shaderDeviceClock` which I am labeling soon)

So I guess the big question (cc @ncesario-lunarg ) is do we want a single function or start breaking all these checks into separate functions with more descriptive naming

I can see the advantage to both

2021-09-16 16:17 UTC, ncesario-lunarg commented on layers/core_validation.h
> +    bool ValidateRuntimeSpirv(SHADER_MODULE_STATE const* src, spirv_inst_iter& insn) const;
I would definitely vote for small,  concise functions whenever possible _in general_. That said, it seems like this (and I think probably the code in PR 3298) belong in `ValidatePropertiesAndFeatures` since--from what I can tell--that is what these VUIDs are doing (i.e., checking property and feature values).

"ValidateRuntimeSpirv" seems a bit too generic IMHO as that is kind of what all of the code in `shader_validation.cpp` does, no? I suppose this function name might be appropriate as a "single entry point for all shader runtime validation," but I don't think our shader validation is designed that way at the moment.

2021-09-16 16:29 UTC, sfricke-samsung commented on layers/core_validation.h
> +    bool ValidateRuntimeSpirv(SHADER_MODULE_STATE const* src, spirv_inst_iter& insn) const;
so to add to this a bit, all the `VUID-RuntimeSpirv*` are really things that `spirv-val` can't do because it relies on the [features enabled, device limits, device properties] of the device, so that is where I got the name from

I feel it is always easy to combine these all later (if we find it is better for some reason) and now thinking about it more agree it would probably be good to call these functions things like

- `ValidateShaderClock`
- `ValidateWorkgroupInitialization`
- `ValidateTexelGatherOffset`

2021-09-16 16:59 UTC, ncesario-lunarg commented on layers/core_validation.h
> +    bool ValidateRuntimeSpirv(SHADER_MODULE_STATE const* src, spirv_inst_iter& insn) const;
^ sounds good to me. If `ValidateRuntimeSpirv` makes sense to everyone in this context, I'm fine with that too, though a comment might be good that more or less covers @sfricke-samsung's comment in that case.

2021-09-16 17:20 UTC, ncesario-lunarg requested changes
LGTM, just the testing nit. Up to you on whether or not to move validation check into the existing `ValidatePropertiesAndFeatures` or leave as is. We can refactor later if need be.

2021-09-16 17:20 UTC, ncesario-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +    if (InstanceExtensionSupported(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME)) {
You should be able to use `AddRequiredExtensions(VK_KHR_ZERO_INITIALIZE_WORKGROUP_MEMORY_EXTENSION_NAME)` and then check with `CanEnableDeviceExtension(VK_KHR_ZERO_INITIALIZE_WORKGROUP_MEMORY_EXTENSION_NAME)` after `InitFramework`. I'd like to get rid of adding extensions directly if possible as it's led to missing dependent extensions in the past.

I converted `vklayertests_buffer_image_memory_sampler.cpp` to use this, so there should be example usages in that file (I'll incrementally convert the other test files as time permits).

2021-09-18 14:59 UTC, ziga-lunarg commented on layers/core_validation.h
> +    bool ValidateRuntimeSpirv(SHADER_MODULE_STATE const* src, spirv_inst_iter& insn) const;
I've renamed to ValidateWorkgroupInitialization

2021-09-18 14:59 UTC, ziga-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +    if (InstanceExtensionSupported(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME)) {
Looks a lot better and simpler, thanks!

2021-09-20 15:42 UTC, sfricke-samsung approved these changes

2021-09-20 17:04 UTC, ncesario-lunarg approved these changes

2022-01-26 21:51 UTC, sfricke-samsung commented on layers/shader_validation.cpp
> +                    "but shader contains an OpVariable with Workgroup Storage Class with an Initializer operand.");
nit: Make use of new log statement

```suggestion
                    "but shader contains an OpVariable with Workgroup Storage Class with an Initializer operand.\n%s", src->DescribeInstruction(insn).c_str());
```

2022-01-26 22:05 UTC, ziga-lunarg commented on layers/shader_validation.cpp
> +                    "but shader contains an OpVariable with Workgroup Storage Class with an Initializer operand.");
I've been away for too long! Thanks!

2022-01-27 23:12 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +                    "but shader contains an OpVariable with Workgroup Storage Class with an Initializer operand.");
It's pretty new @ziga-lunarg. I'd probably also forget :)

2022-01-28 12:32 UTC, merged