Adding vuid 01769, Validate conservative rasterization overestimation size
KhronosGroup/Vulkan-ValidationLayers pull request #3317
Opened 2021-09-20 16:26 UTC by ziga-lunarg

2021-09-21 15:11 UTC, jeremyg-lunarg requested changes
looks like this needs to be rebased to resolve conflicts

2021-09-21 15:11 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                    "VkPhysicalDeviceTransformFeedbackPropertiesEXT::maxTransformFeedbackStreams (%f).",
this looks like the wrong field in the log message, since you're comparing against maxExtraPrimitiveOverestimationSize

2021-09-22 09:18 UTC, ziga-lunarg commented on layers/core_validation.cpp
> +                    "VkPhysicalDeviceTransformFeedbackPropertiesEXT::maxTransformFeedbackStreams (%f).",
Good catch

2021-09-23 14:34 UTC, jeremyg-lunarg requested changes

2021-09-23 14:34 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                    "VkPhysicalDeviceTransformFeedbackPropertiesEXT::maxExtraPrimitiveOverestimationSize (%f).",
shouldn't this be VkPipelineRasterizationConservativeStateCreateInfoEXT::maxExtraPrimitiveOverestimationSize?

2021-09-23 23:11 UTC, ziga-lunarg commented on layers/core_validation.cpp
> +                    "VkPhysicalDeviceTransformFeedbackPropertiesEXT::maxExtraPrimitiveOverestimationSize (%f).",
Right, I don't know how I missed that

2021-09-24 13:57 UTC, jeremyg-lunarg approved these changes
LGTM

2021-09-24 16:06 UTC, merged