Adding vuid 03572, Validate acceleration structure bindings count
KhronosGroup/Vulkan-ValidationLayers pull request #3326
Opened 2021-09-22 23:07 UTC by ziga-lunarg

2021-09-23 14:24 UTC, jeremyg-lunarg requested changes
Probably a leak in the test case, otherwise looks good.

2021-09-23 14:24 UTC, jeremyg-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    VkDescriptorSetLayout ds_layout;
Looks like ds_layout will be leaked. vk_testing::DescriptorSetLayout

2021-09-23 23:03 UTC, ziga-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    VkDescriptorSetLayout ds_layout;
Will do, thanks

2021-09-24 13:58 UTC, jeremyg-lunarg approved these changes
LGTM

2021-09-24 14:55 UTC, merged