Fix issue 3426, Fix validating if swapchain image was acquired
KhronosGroup/Vulkan-ValidationLayers pull request #3427
Opened 2021-10-13 16:06 UTC by ziga-lunarg

Closes #3426

2021-10-13 16:31 UTC, ncesario-lunarg reviewed
One question, but I think this looks good.

FYI @jeremyg-lunarg for the addition to `CMD_BUFFER_STATE`.

2021-10-13 16:31 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +            skip |= ValidateImageAcquired(*image_state, func_name);
Should we check if `image_state` is not null here? e.g., could a user pass in an image that was previously destroyed to a barrier call without getting an error previously? I don't think they can, but not 100% sure (just from a quick look, looks like validation is skipped in `ValidateImageBarrier` if `image_state` is null).

2021-10-13 18:46 UTC, Tony-LunarG requested changes

2021-10-13 18:46 UTC, Tony-LunarG commented on layers/core_validation.cpp
> +    cb_state->barrierUpdates.emplace_back([this, imageMemoryBarrierCount, pImageMemoryBarriers, func_name]() {
Is pImageMemoryBarriers safe to emplace here? I think it's pointing to app data.

2021-10-13 20:53 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +    CMD_BUFFER_STATE *cb_state = GetCBState(command_buffer);
Should this function return if `imageMemoryBarrierCount == 0`?

2021-10-18 19:42 UTC, jeremyg-lunarg commented on layers/queue_state.h
> +    void execute_waiting_functions() {
shouldn't this be ExecuteWaitingFunctions()?

2021-10-18 20:47 UTC, ziga-lunarg commented
> I'm getting a crash running the surge in LvlFindInChain here:
> 
> ```
> void ValidationStateTracker::PostCallRecordQueuePresentKHR(VkQueue queue, const VkPresentInfoKHR *pPresentInfo, VkResult result) {
>     // Semaphore waits occur before error generation, if the call reached the ICD. (Confirm?)
>     const auto present = [this, pPresentInfo, result]() {
>         const auto *present_id_info = LvlFindInChain<VkPresentIdKHR>(pPresentInfo->pNext);
> ```

Do you have a call stack?

2021-10-18 21:33 UTC, ziga-lunarg commented on layers/queue_state.h
> +            if (func.use_count() == 1) {
`vkQueuePresentKHR()` can wait on multiple semaphores, only the last semaphore that gets signaled should execute this function.

2021-10-18 22:16 UTC, ncesario-lunarg commented on layers/queue_state.h
> +            if (func.use_count() == 1) {
I guess I'm having trouble seeing how this condition guarantees only the last one gets called. If `func` was added `N` times to  `waiting_functions`, wouldn't `use_count` be `N` for the duration of this loop? Is `func.reset()` meant to be called after `(*func)();`?

2021-10-18 22:44 UTC, ncesario-lunarg commented on layers/queue_state.h
> +            if (func.use_count() == 1) {
:+1: thanks, think I finally got it :)

2021-10-20 19:25 UTC, ncesario-lunarg commented on layers/image_state.h
> +    WAITING_SEMAPHORE,
Is this used anywhere?

2022-03-21 17:49 UTC, closed without merging