layers: Add VK_KHR_dynamic_rendering
KhronosGroup/Vulkan-ValidationLayers pull request #3517
Opened 2021-11-09 13:48 UTC by AaronHaganAMD

WIP - Add VU for VK_KHR_dynamic_rendering extension.

2021-11-09 15:30 UTC, jeremyg-lunarg reviewed
Good to see this PR! Some preliminary comments since it looks like you're still working on it. The 2 big things so far are:

1.  Please rebase against the current tip of master, which is already updated to Vulkan-Headers 1.2.197. This should make the size  of your patch go way down.
2.  Please use snake_case for struct members and local variables. Yes the code is very inconsistent but we're trying to move to using the Google style guide (see:  CONTRIBUTING.md)

2021-11-09 15:30 UTC, jeremyg-lunarg commented on layers/core_validation.h
> +                                                    const VkRenderingAttachmentInfoKHR* pAttachments) const;
This needs to be 'const override'

2021-11-09 15:30 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +    // cb_state->useDynamicRendering = true;
these commented out lines need to be removed or uncommented, not sure which.

2021-11-09 15:30 UTC, jeremyg-lunarg commented on scripts/known_good.json
> +      "commit": "v1.2.197"
This should go away if you rebase on top of def5cf6be051fd791e9c6bf4a41d4b6617fcbbf8

2021-11-09 15:30 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +            std::shared_ptr<RENDER_PASS_STATE> renderPassState(new RENDER_PASS_STATE(begin_rendering_info));
should be render_pass_state. yes we have lots of inconsistencies but trying to get better :)

2021-11-09 15:30 UTC, jeremyg-lunarg commented on layers/render_pass_state.h
> +    bool useDynamicRendering;
these struct members should be snake_case names.

2021-11-09 15:30 UTC, jeremyg-lunarg commented on layers/render_pass_state.h
> +    bool useDynamicRendering;
also, can the non-const members be made const?

2021-11-09 16:36 UTC, sfricke-samsung commented on layers/core_validation.cpp
> +    if (!(device_extensions.vk_amd_mixed_attachment_samples || device_extensions.vk_nv_framebuffer_mixed_samples)) {
for anything with `device_extensions.vk_*` please use the `IsExtEnabled()` wrapper

2021-11-09 16:40 UTC, sfricke-samsung commented on layers/core_validation.cpp
> +                                 "Color attachment ref %u has sample count %s, whereas first color attachment ref has "
please add `vkCmdBeginRenderingKHR(): ` to start each error message

2021-11-09 18:42 UTC, jeremyg-lunarg commented on layers/pipeline_state.h
> +        safe_VkPipelineRenderingCreateInfoKHR dynamic_rendering;
This member isn't used and I don't think it would work to add it here.  This structure is chained onto the graphics pipeline info, so it should be available through graphics.pNext

2021-11-09 23:16 UTC, jeremyg-lunarg requested changes
Whew, made it all the way through the changes. Other than the extra formatting changes that got added in the last push, I think this is getting close. Several comments inline about some of the VUID checks and other things.

2021-11-09 23:16 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                    "vkCmdBeginRenderingKHR(): image must not have been created with VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL");
imageLayout must not be

2021-11-09 23:16 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +            if (pRenderingInfo->pDepthAttachment->resolveMode != VK_RESOLVE_MODE_NONE) {
combine the 2 resolveMode != NONE if conditionals?

2021-11-09 23:16 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                    "vkCmdBeginRenderingKHR(): image must not have been created with VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL");
imageLayout must not be

2021-11-09 23:16 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +        if (pAttachments->resolveMode != VK_RESOLVE_MODE_NONE && image_view_state->samples != VK_SAMPLE_COUNT_1_BIT) {
combine all of the resolveMode != NONE conditionals?

2021-11-09 23:16 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                if (renderPass && !renderPass->use_dynamic_rendering) {
I think this needs to be:
```
       if (info->renderPass != VK_NULL_HANDLE) {
           const auto *render_pass = GetRenderPassState(info->renderPass);
           if (!render_pass) {
                  VUID-06000
            }
       } else {
```

2021-11-10 03:05 UTC, AaronHaganAMD commented on layers/best_practices_utils.cpp
> +    RENDER_PASS_STATE* rp_state = cmd_state->active_render_pass.get();
I can leave the pre-existing members alone for now..

2021-11-10 11:02 UTC, Tobski commented on layers/render_pass_state.h
> +    safe_VkRenderingInfoKHR dynamic_rendering_info;
It's updated in

```c++
RENDER_PASS_STATE::RENDER_PASS_STATE(VkRenderingInfoKHR const *pRenderingInfo);
```

which is called by 

```c++
void CMD_BUFFER_STATE::BeginRendering(...)
```

2021-11-10 15:24 UTC, jeremyg-lunarg commented
@AaronHaganAMD and @Tobski do you have an estimate when you'll be done adding functionality to this PR? The deadline to get it stabilized, cleaned up and merged for the next SDK is rapidly approaching.  It is currently crashing the unit tests on all targets in VkLayerTest.SecondaryCommandBufferNullRenderpass.  If you need details about the crashes or cannot reproduce them locally please let me know.

2021-11-10 16:48 UTC, Tobski commented on layers/core_validation.cpp
> +            if (pRenderingInfo->pDepthAttachment->resolveMode != VK_RESOLVE_MODE_NONE) {
Done.

2021-11-10 16:48 UTC, Tobski commented on layers/core_validation.cpp
> +        if (pAttachments->resolveMode != VK_RESOLVE_MODE_NONE && image_view_state->samples != VK_SAMPLE_COUNT_1_BIT) {
Done

2021-11-10 16:50 UTC, Tobski commented
> @AaronHaganAMD and @Tobski do you have an estimate when you'll be done adding functionality to this PR? The deadline to get it stabilized, cleaned up and merged for the next SDK is rapidly approaching. It is currently crashing the unit tests on all targets in VkLayerTest.SecondaryCommandBufferNullRenderpass. If you need details about the crashes or cannot reproduce them locally please let me know.

We're working more or less full time on this right now, we'll be done before the end of the week (I believe your deadline is Friday?)

2021-11-10 18:23 UTC, jeremyg-lunarg commented
> We're working more or less full time on this right now, we'll be done before the end of the week (I believe your deadline is Friday?)

Ok. I do need some time to review and to run additional tests beyond our automated CI on the final version, which will take several hours.

2021-11-10 19:04 UTC, KarenGhavam-lunarG commented
> We're working more or less full time on this right now, we'll be done before the end of the week (I believe your deadline is Friday?)

We are suddenly being asked for lots of code reviews on a compressed schedule due to the quantity of changes coming in late. To give us some time to do the reviews and for you to be able to react and fix per the reviews, you should not be thinking that Friday is your deadline. More like EOB today.

2021-11-10 20:58 UTC, AaronHaganAMD commented
VkLayerTest.SecondaryCommandBufferNullRenderpass should be passing now..

2021-11-10 21:17 UTC, jeremyg-lunarg commented
> VkLayerTest.SecondaryCommandBufferNullRenderpass should be passing now..

Great! Are you all done making functional changes or is there still more to come?

2021-11-10 21:27 UTC, AaronHaganAMD commented
> > VkLayerTest.SecondaryCommandBufferNullRenderpass should be passing now..
> 
> Great! Are you all done making functional changes or is there still more to come?

I think this PR is in good shape.. But there are still a lot of VUs that still need added. Should we get this PR merged and add more VU's in a new a PR ?

2021-11-10 21:33 UTC, jeremyg-lunarg commented
> 
> I think this PR is in good shape.. But there are still a lot of VUs that still need added. Should we get this PR merged and add more VU's in a new a PR ?

Definitely needs to be a separate PR for the additional VUs at this point. I'll start reviewing this one again.

2021-11-10 22:04 UTC, Tobski commented
Just to be clear, when I said "end of Friday" I was including review time - I didn't foresee us having substantial changes beyond EOB today. Tomorrow morning I'll take a look at @jeremyg-lunarg's review comments, and hopefully when you all come online tomorrow we'll be in good shape to submit - everything from then til Friday is wiggle room.

2021-11-10 22:49 UTC, jeremyg-lunarg reviewed
I'm still waiting on results from extra testing to make sure we're not regressing any of the application traces in our test suite. But I think this is pretty close. There's probably some refactoring that can be done with the existing code to make this all fit together better, but that's going to happen after the fact.

There will be a change you need to make as a result of  PR #3523,  in CoreChecks::PreCallValidateCreateGraphicsPipelines() I added a check for null renderpass handles, you'll want to remove the UNASSIGNED-VkGraphicsPipelineCreateInfo-dynamicRendering-not-supported case but keep the VUID-VkGraphicsPipelineCreateInfo-dynamicRendering-06052 case. There's another conflict in the ValidationStateTracker version of this method that I noted inline. This change was necessary so that we have somewhat OK behavior if someone triggers 06052 or if we have to ship the SDK without this change for some late breaking reason.

2021-11-10 22:49 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
> +                        image_index = colorAttachmentCount * 2;
since this offset math has to stay in sync with the code in CMD_BUFFER_STATE::BeginRendering(), would it be possible to have a method, function or something to return the correct index, which gets used in both places?

2021-11-10 22:49 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +        // Validate dynamic rendering
seems like this should be checking rp_state->use_dynamic_rendering since there will be a stub rp_state  here.  Are there VUIDs that you're going to add here in a separate PR? If so maybe make this a TODO

2021-11-10 22:49 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                            "vkCmdBeginRenderingKHR(): width of the pColorAttachments[%u].imageView: %u must be greater than"
this error is for a height check but the message says width.

2021-11-10 22:49 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                                     "vkCmdBeginRenderingKHR(): width of the pDepthAttachment->imageView: %u must be greater than"
also should be height.

2021-11-10 22:49 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                                     "vkCmdBeginRenderingKHR(): width of the pStencilAttachment->imageView: %u must be greater than"
height

2021-11-10 22:49 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                skip |= LogError(device, "VUID-VkRenderingInfoKHR-pDepthAttachment-06105",
06105 and 06104 seem to contradict each other, if resolveMode is NONE for depth or stencil, you'd fail 06104 but pass 06105. Is this a spec problem?  Seems like it would be less confusing to only check 06105 here.

2021-11-10 22:49 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                                 "vkCmdBeginRenderingKHR(): imageLayout must not have be "
typo: must not have be

2021-11-10 22:49 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                             "resolveImageView sample count must be must not have a VK_SAMPLE_COUNT_1_BIT for Resolve Mode %s",
typo: "must be must not have" from the VUID it looks like this should say "must be"

2021-11-10 22:49 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                const auto dynamic_rendering_info = pCB->activeRenderPass->dynamic_rendering_info;
Are there VUIDs you're going to add here in a separate PR? If so maybe make this a TODO

2021-11-10 22:49 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +        } else {
There's going to be a merge conflict from PR #3523 here.  To resolve, I think you should have something like:
```
     if (begin_rendering_info) {
    } else if (pCreateInfos[i].renderPass != VK_NULL_HANDLE) {
    } else {
       insert null shared_ptr.
    }

```

2021-11-10 22:49 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                                 "vkCmdBeginRenderingKHR(): width of the pColorAttachments[%u].imageView: %u must be greater than"
This should say height, not width.

2021-11-10 22:49 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                                 "vkCmdBeginRenderingKHR(): width of the pDepthAttachment->imageView: %u must be greater than"
height, not width.

2021-11-10 22:49 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                                 "vkCmdBeginRenderingKHR(): width of the pStencilAttachment->imageView: %u must be greater than"
height, not width.

2021-11-10 23:04 UTC, jeremyg-lunarg commented
Also related to VUID-VkGraphicsPipelineCreateInfo-dynamicRendering-06052, is there a VUID for the case where the renderPass handle is null, but there is not a VkPipelineRenderingCreateInfoKHR structure in the pNext chain?  I cannot find one yet, but this case could cause a crash in the layer if not handled correctly.

2021-11-11 08:55 UTC, AaronHaganAMD commented
> I'm still waiting on results from extra testing to make sure we're not regressing any of the application traces in our test suite. But I think this is pretty close. There's probably some refactoring that can be done with the existing code to make this all fit together better, but that's going to happen after the fact.
> 
> There will be a change you need to make as a result of PR #3523, in CoreChecks::PreCallValidateCreateGraphicsPipelines() I added a check for null renderpass handles, you'll want to remove the UNASSIGNED-VkGraphicsPipelineCreateInfo-dynamicRendering-not-supported case but keep the VUID-VkGraphicsPipelineCreateInfo-dynamicRendering-06052 case. There's another conflict in the ValidationStateTracker version of this method that I noted inline. This change was necessary so that we have somewhat OK behavior if someone triggers 06052 or if we have to ship the SDK without this change for some late breaking reason.

Removed VUID-VkGraphicsPipelineCreateInfo-dynamicRendering-06052  and handled the inline comment in regards to creating the pipeline.

2021-11-11 10:52 UTC, Tobski commented on layers/core_validation.cpp
> +                skip |= LogError(device, "VUID-VkRenderingInfoKHR-pDepthAttachment-06105",
I'm not sure why you think this is a contradiction - these are two separate limit values being tested (albeit with very similar names). We could perhaps change it so that the less restrictive condition is only checked if the more restrictive condition passes?

2021-11-11 10:56 UTC, Tobski commented on layers/buffer_validation.cpp
> +                        image_index = colorAttachmentCount * 2;
Yea that's probably not the worst idea. I think there's scope  for a lot of refactoring in this area which I think is something we probably want to discuss after this lands.

2021-11-11 12:03 UTC, Tobski commented
> Also related to VUID-VkGraphicsPipelineCreateInfo-dynamicRendering-06052, is there a VUID for the case where the renderPass handle is null, but there is not a VkPipelineRenderingCreateInfoKHR structure in the pNext chain? I cannot find one yet, but this case could cause a crash in the layer if not handled correctly.

There's no VU for it because default values are assumed for VkPipelineRenderingCreateInfoKHR if it's not present. I'll take a look at making this not crash...

2021-11-11 12:15 UTC, Tobski commented on layers/buffer_validation.cpp
> +                        image_index = colorAttachmentCount * 2;
Done, I've added functions to cmd_buffer_state for this.

2021-11-11 12:15 UTC, Tobski commented on layers/core_validation.cpp
> +                                 "vkCmdBeginRenderingKHR(): imageLayout must not have be "
Fixed.

2021-11-11 12:15 UTC, Tobski commented on layers/core_validation.cpp
> +                             "resolveImageView sample count must be must not have a VK_SAMPLE_COUNT_1_BIT for Resolve Mode %s",
Fixed.

2021-11-11 12:16 UTC, Tobski commented on layers/core_validation.cpp
> +                const auto dynamic_rendering_info = pCB->activeRenderPass->dynamic_rendering_info;
I've added a TODO - hopefully that's what you expected?

2021-11-11 12:16 UTC, Tobski commented
> There's no VU for it because default values are assumed for VkPipelineRenderingCreateInfoKHR if it's not present. I'll take a look at making this not crash...

I've added code to handle this and I'll add a test for it shortly.

2021-11-11 13:47 UTC, Tobski commented
@jeremyg-lunarg finally looks like we've got CI passing so the question now is what additional tests do you think we need to get in? I'll do the one I said above, what else do you think we need to get this in?

I'm inclined to hold off tests for the new VUs that were added until after we merge this, because that's a big effort, and running against CTS at least proved they don't generate false positives.

I'm similarly inclined to work on doing any further refactoring work after we merge this, probably as a first step before we add more VU checks.

2021-11-11 16:16 UTC, jeremyg-lunarg reviewed
It looks like we're down to a few things. I am mainly concerned that the new test cases (including in PR #3525) do not crash:

- VkLayerTest.CreateGraphicsPipelineNullRenderPass
- VkLayerTest.CreateGraphicsPipelineDynamicRenderingNoInfo
- VkPositiveLayerTest.CreateGraphicsPipelineDynamicRendering

I've noted in line where I think the crashes are coming from, but if the tests are wrong lets fix them instead.

There's also an offline discussion about the plan to finish the validation and tests for this extension that you should have received.

2021-11-11 16:16 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +        } else if (dynamic_rendering || pCreateInfos[i].renderPass != VK_NULL_HANDLE) {
This isn't correct and I think it is causing a crash in a test case I wrote yesterday evening.  Probably it needs to be if (!dynamic_rendering || ...) See https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3525  VkLayerTest.CreateGraphicsPipelineDynamicRenderingNoInfo

2021-11-11 16:39 UTC, Tobski commented on layers/core_validation.cpp
> +                skip |= LogError(device, "VUID-VkRenderingInfoKHR-pDepthAttachment-06105",
>So is it valid for either resolveMode to be NONE if the other is not? If yes, then 06104 is wrong, if no, then 06105 is redundant. 

Both? Either? Depends on the implementation. Again - separate limits!

6104 triggers if and only if (phys_dev_props_core12.independentResolveNone == VK_FALSE).

6105 triggers if and only if (phys_dev_props_core12.independentResolve == VK_FALSE). Note that this is a _different limit_. In addition, you can't support the former limit if this limit is not supported.

The truth table is thus much bigger... I can type the whole thing out if I absolutely must but I'm not super keen on doing so 😅

2021-11-11 16:52 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                skip |= LogError(device, "VUID-VkRenderingInfoKHR-pDepthAttachment-06105",
Ah, I missed the independentResolveNone vs independentResolve. Thanks!

2021-11-11 17:08 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +        } else if (dynamic_rendering || pCreateInfos[i].renderPass != VK_NULL_HANDLE) {
actually, this seems to work better for me:
```
        if (pCreateInfos[i].renderPass != VK_NULL_HANDLE) {
              cgpl_state->pipe_state.push_back(std::make_shared<PIPELINE_STATE>(this, &pCreateInfos[i],
                                                                               GetRenderPassShared(pCreateInfos[i].renderPass),
                                                                                GetPipelineLayoutShared(pCreateInfos[i].layout)));
         } else if (enabled_features.dynamic_rendering_features.dynamicRendering) {
              auto dynamic_rendering = LvlFindInChain<VkPipelineRenderingCreateInfoKHR>(pCreateInfos[i].pNext);
              cgpl_state->pipe_state.push_back(std::make_shared<PIPELINE_STATE>(this, &pCreateInfos[i],
                                                                                std::make_shared<RENDER_PASS_STATE>(dynamic_rendering),
                                                                                GetPipelineLayoutShared(pCreateInfos[i].layout)));
          } else {
              cgpl_state->pipe_state.push_back(std::shared_ptr<PIPELINE_STATE>());
          }
      }

```

2021-11-11 20:39 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +        } else if (dynamic_rendering || pCreateInfos[i].renderPass != VK_NULL_HANDLE) {
I just pushed this fix.

2021-11-11 21:19 UTC, jeremyg-lunarg approved these changes
LGTM.  We'll need to address additional VUIDs and missing test cases in separate PRs. I'll be opening issues to track.

2021-11-11 21:20 UTC, merged