tests: Additional dynamic rendering pipeline tests
KhronosGroup/Vulkan-ValidationLayers pull request #3525
Opened 2021-11-11 16:08 UTC by jeremyg-lunarg

2021-11-11 17:29 UTC, Tony-LunarG requested changes
The new tests don't pass yet

2021-11-11 17:29 UTC, Tony-LunarG commented on tests/positive/pipeline.cpp
> +    ASSERT_NO_FATAL_FAILURE(InitRenderTarget());
I don't think you need a render target if you aren't going to draw

2021-11-11 17:29 UTC, Tony-LunarG commented on tests/positive/pipeline.cpp
> +    ASSERT_NO_FATAL_FAILURE(InitRenderTarget());
Doing this twice will leak resources

2021-11-11 17:29 UTC, Tony-LunarG commented on tests/positive/pipeline.cpp
> +    m_errorMonitor->VerifyNotFound();
This does get an expected error - VK_KHR_dynamic_rendering is currently unsupported

2021-11-11 17:29 UTC, Tony-LunarG commented on tests/vklayertests_pipeline_shader.cpp
> +    ASSERT_NO_FATAL_FAILURE(InitRenderTarget());
Same render target issue here

2021-11-11 17:29 UTC, Tony-LunarG commented on tests/vklayertests_pipeline_shader.cpp
> +    m_errorMonitor->VerifyNotFound();
Is this meant to be a positive test or should you look for UNASSIGNED-VkGraphicsPipelineCreateInfo-dynamicRendering-not-supported

2021-11-11 17:32 UTC, jeremyg-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +    m_errorMonitor->VerifyNotFound();
This is meant to merge after #3517, which will remove that error.

2021-11-11 17:36 UTC, Tony-LunarG commented on tests/vklayertests_pipeline_shader.cpp
> +    m_errorMonitor->VerifyNotFound();
Got it

2021-11-11 17:40 UTC, jeremyg-lunarg commented on tests/positive/pipeline.cpp
> +    ASSERT_NO_FATAL_FAILURE(InitRenderTarget());
yep, thanks!

2021-11-11 20:38 UTC, Tony-LunarG commented on tests/vklayertests_pipeline_shader.cpp
> +    pipe.CreateVKPipeline(pl.handle(), VK_NULL_HANDLE, &create_info);
If this is really VerifyNotFound should this be a positive test?

2021-11-11 20:42 UTC, jeremyg-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +    pipe.CreateVKPipeline(pl.handle(), VK_NULL_HANDLE, &create_info);
Yes you're right. I wasn't sure what was supposed to happen when I wrote this but Tobias clarified and it should be a positive. I'll move it.

2021-11-11 21:41 UTC, Tony-LunarG approved these changes
LGTM

2021-11-11 22:28 UTC, merged

2021-11-15 18:04 UTC, ncesario-lunarg reviewed
Just a nit about enabling extensions, but LGTM!

2021-11-15 18:04 UTC, ncesario-lunarg commented on tests/positive/pipeline.cpp
> +    if (DeviceExtensionSupported(VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME)) {
It would be probably be good to use the `AddRequiredExtensions` and similar functions to ensure all dependent extensions get added.