layers: Add VK_KHR_dynamic_rendering
KhronosGroup/Vulkan-ValidationLayers pull request #3535
Opened 2021-11-15 20:26 UTC by AaronHaganAMD

Add additional VUs for the VK_KHR_dynamic_rendering extension.

VUID-VkDeviceQueueCreateInfo-flags-06449
VUID-VkRenderingInfoKHR-imageView-06124
VUID-VkRenderingInfoKHR-imageView-06125
VUID-VkRenderingFragmentShadingRateAttachmentInfoKHR-imageView-06147
VUID-VkRenderingFragmentShadingRateAttachmentInfoKHR-imageView-06149
VUID-VkRenderingFragmentShadingRateAttachmentInfoKHR-imageView-06150
VUID-VkRenderingFragmentShadingRateAttachmentInfoKHR-imageView-06151
VUID-VkRenderingFragmentShadingRateAttachmentInfoKHR-imageView-06152
VUID-VkRenderingFragmentShadingRateAttachmentInfoKHR-imageView-06153
VUID-VkRenderingFragmentShadingRateAttachmentInfoKHR-imageView-06154
VUID-VkRenderingFragmentShadingRateAttachmentInfoKHR-imageView-06155
VUID-VkRenderingFragmentShadingRateAttachmentInfoKHR-imageView-06156
VUID-VkRenderingInfoKHR-imageView-06116
VUID-VkRenderingAttachmentInfoKHR-imageView-06143
VUID-VkRenderingAttachmentInfoKHR-imageView-06140
VUID-VkRenderingAttachmentInfoKHR-imageView-06144
VUID-VkRenderingAttachmentInfoKHR-imageView-06141
VUID-VkRenderingAttachmentInfoKHR-imageView-06142
VUID-VkCommandBufferBeginInfo-flags-06001
VUID-VkCommandBufferBeginInfo-flags-06003
VUID-VkCommandBufferBeginInfo-flags-06003
VUID-VkCommandBufferInheritanceRenderingInfoKHR-pColorAttachmentFormats-06006
VUID-VkCommandBufferInheritanceRenderingInfoKHR-depthAttachmentFormat-06007
VUID-VkCommandBufferInheritanceRenderingInfoKHR-stencilAttachmentFormat-06199
VUID-VkCommandBufferInheritanceRenderingInfoKHR-depthAttachmentFormat-06200
VUID-VkCommandBufferInheritanceRenderingInfoKHR-multiview-06008
VUID-VkCommandBufferInheritanceRenderingInfoKHR-viewMask-06009

2021-11-15 21:43 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +        const VkQueueFlags queue_flags = GetPhysicalDeviceState()->queue_family_properties[requested_queue_family].queueFlags;
this should use pd_state->queue_family_properties.  The no-argument version of GetPhysicalDeviceState() only works inside of calls that involve a VkDevice (which is very confusing...)   But this is what caused your internal CI job to fail on most platforms.

2021-11-15 22:58 UTC, lunarpapillo commented
FYI, the CI failures suggest that the device needs to be rebooted (or that someone is logged in over RDP and the graphics stack is broken).  I'll restart tests after I do that.

2021-11-15 23:16 UTC, lunarpapillo commented
I take it back, sorry.  Some of our Windows boxes will show failures on `PSOPolygonModeInvalid` if the device is in trouble; but the problem is occurring on Linux and Android, which suggests the failure is not due to a CI system issue.

2021-11-16 06:01 UTC, ncesario-lunarg commented
@AaronHaganAMD you might need to replace the full VUID name with something like "VUID-06006" to make the commit message check happy.

2021-11-16 15:30 UTC, jeremyg-lunarg requested changes
Can you please give these PR and commit messages unique subject lines somehow?  I worry we're going to get confused when there's a whole bunch more of them for all the other remaining VUIDs.

Other than that, there's a few minor things to fix inline but this looks pretty close.

2021-11-16 15:30 UTC, jeremyg-lunarg commented on layers/sync_utils.h
> +uint32_t MostSignificantBit(uint32_t);
This should go in vk_layer_utils.h where there's already a bunch of similar functions, like u_ffs() and IsPowerOfTwo(). Unfortunately there doesn't seem to be a standard way to do this operation until c++20 which gives std::bit_floor().

2021-11-16 15:30 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +bool CoreChecks::UniqueImageViews(const VkRenderingInfoKHR* pRenderingInfo, VkImageView imageView) const {
can this just be a static function? It is only used in one place and doesn't use any information from the class.

2021-11-16 15:30 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                                "vkCmdBeginRenderingKHR(): If the multiview feature is not enabled, viewMask must be 0 (%u)",
Should this message and 06009 below start with vkBeginCommandBuffer()?

2021-11-16 20:11 UTC, jeremyg-lunarg approved these changes
LGTM

2021-11-16 21:35 UTC, merged