layers: Add VK_KHR_dynamic_rendering VUs - Change Set #2
KhronosGroup/Vulkan-ValidationLayers pull request #3549
Opened 2021-11-18 15:14 UTC by AaronHaganAMD

Add additional VUs for the VK_KHR_dynamic_rendering extension.
Small refactors and unit tests as well as addition of  VUIDs for
VkDraw* commands.

2021-11-18 15:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3549) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3549) before we can accept your contribution.<br/><hr/>**ahagan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3549) it.</sub>

2021-11-18 17:04 UTC, jeremyg-lunarg commented
Looks like this is failing on our NV test machines:
```
[ RUN      ] VkPositiveLayerTest.DynamicRenderingDraw
ERROR: -------------------------------------------------------------
ERROR: FAIL during test after 18.22 minutes (1092.95 seconds) with execute(C:\j\w\64-bit\Debug\Vulkan-ValidationLayers\dbuild\tests\Debug\vk_layer_validation_tests.exe --gtest_catch_exceptions=0 --gtest_filter=-VkLayerTest.NonSemanticInfoEnabled) failed after 18.22 minutes (1092.92 seconds) with returncode=3221225477 (0xc0000005=STATUS_ACCESS_VIOLATION)
INFO: Test run complete after 23.60 minutes (1415.82 seconds)
```

2021-11-18 17:57 UTC, jeremyg-lunarg requested changes
Can you please put the test code into a separate git commit? 

The validation code looks reasonable, I think.

I can try to reproduce the NV crash later today  and get more info on what is wrong there.


Thanks!

2021-11-18 17:57 UTC, jeremyg-lunarg commented on tests/positive/dynamic_rendering.cpp
> +    if (DeviceExtensionSupported(VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME)) {
This should use AddRequiredDeviceExtensions() I need to fix my test case to use it too

2021-11-18 19:39 UTC, ncesario-lunarg reviewed
One nit with the print formatting; otherwise I echo @jeremyg-lunarg's comments.

2021-11-18 19:39 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                    "%s: Currently bound pipeline %s viewMask (%u) must be equal to pBeginRendering->viewMask (%u)",
Can `%u` be replaced with `PRIu32` (or the appropriate type)? We have standardized on using the `PRI*` macros to give us some "type safety" with printf.

2021-11-19 15:40 UTC, jeremyg-lunarg reviewed
LGTM but we still need to update a driver in CI before the new test can merge

2021-11-22 16:18 UTC, jeremyg-lunarg commented
CI failure today is a different one. Looks like many of the log messages in CoreChecks::ValidatePipelineDrawtimeState() are now using strings but have % PRIu32 formats rather than %s:
```
layers/core_validation.cpp: In member function ‘bool CoreChecks::ValidatePipelineDrawtimeState(const LAST_BOUND_STATE&, const CMD_BUFFER_STATE*, CMD_TYPE, const PIPELINE_STATE*) const’:
layers/core_validation.cpp:722:33: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 7 has type ‘const char*’ [-Wformat=]
  722 |                                 "%s: Color attachment (%" PRIu32 ") sample count (%u) must match corresponding VkAttachmentSampleCountInfoAMD sample count (%" PRIu32 ")",
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  723 |                                 caller, i, string_VkSampleCountFlagBits(color_image_samples),
      |                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                        |
      |                                                                        const char*
layers/core_validation.cpp:722:33: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 8 has type ‘const char*’ [-Wformat=]
  722 |                                 "%s: Color attachment (%" PRIu32 ") sample count (%u) must match corresponding VkAttachmentSampleCountInfoAMD sample count (%" PRIu32 ")",
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  723 |                                 caller, i, string_VkSampleCountFlagBits(color_image_samples),
  724 |                                 string_VkSampleCountFlagBits(p_attachment_sample_count_info_amd->pColorAttachmentSamples[i]));
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                             |

```

2021-11-22 18:48 UTC, AaronHaganAMD commented
> CI failure today is a different one. Looks like many of the log messages in CoreChecks::ValidatePipelineDrawtimeState() are now using strings but have % PRIu32 formats rather than %s:
> 
> ```
> layers/core_validation.cpp: In member function ‘bool CoreChecks::ValidatePipelineDrawtimeState(const LAST_BOUND_STATE&, const CMD_BUFFER_STATE*, CMD_TYPE, const PIPELINE_STATE*) const’:
> layers/core_validation.cpp:722:33: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 7 has type ‘const char*’ [-Wformat=]
>   722 |                                 "%s: Color attachment (%" PRIu32 ") sample count (%u) must match corresponding VkAttachmentSampleCountInfoAMD sample count (%" PRIu32 ")",
>       |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   723 |                                 caller, i, string_VkSampleCountFlagBits(color_image_samples),
>       |                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |                                                                        |
>       |                                                                        const char*
> layers/core_validation.cpp:722:33: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 8 has type ‘const char*’ [-Wformat=]
>   722 |                                 "%s: Color attachment (%" PRIu32 ") sample count (%u) must match corresponding VkAttachmentSampleCountInfoAMD sample count (%" PRIu32 ")",
>       |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   723 |                                 caller, i, string_VkSampleCountFlagBits(color_image_samples),
>   724 |                                 string_VkSampleCountFlagBits(p_attachment_sample_count_info_amd->pColorAttachmentSamples[i]));
>       |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       |                                                             |
> ```

these should be fixed now.

2021-11-22 20:09 UTC, jeremyg-lunarg approved these changes
LGTM. Linux github failures are due to a new Vulkan-Loader change which is causing the same failure in other PRs.

2021-11-22 20:10 UTC, merged