Tests: Added tests for some dynamic rendering VUIDs
KhronosGroup/Vulkan-ValidationLayers pull request #3573
Opened 2021-11-29 16:00 UTC by stu-s

Added tests for the following:

VUID-vkCmdExecuteCommands-pCommandBuffers-06019
VUID-vkCmdExecuteCommands-pBeginInfo-06020
VUID-vkCmdExecuteCommands-pBeginInfo-06025
VUID-vkCmdExecuteCommands-flags-06026
VUID-vkCmdExecuteCommands-colorAttachmentCount-06027
VUID-vkCmdExecuteCommands-imageView-06028
VUID-vkCmdExecuteCommands-pDepthAttachment-06029
VUID-vkCmdExecuteCommands-pStencilAttachment-06030
VUID-vkCmdExecuteCommands-viewMask-06031
VUID-vkCmdBeginRenderingKHR-commandBuffer-06068
VUID-vkCmdBeginRenderingKHR-dynamicRendering-06446

I also added tests for VUID-vkCmdExecuteCommands-contents-06018 and VUID-vkCmdExecuteCommands-flags-06024, but they also generate the following:
UNASSIGNED-CoreValidation-DrawState-InvalidCommandBuffer(ERROR / SPEC): msgNum: 298202768 - 
    Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidCommandBuffer ] Object 0: 
    handle = 0x18e5fb48c90, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x11c63690 | 
    vkCmdExecuteCommands() cannot be called in a subpass using inline commands.

They're currently '#if 0"' as I wasn't sure what to do here.

2021-11-29 21:53 UTC, jeremyg-lunarg requested changes
Thanks! I think the tests are pretty close but  VkLayerTest.ValidateBeginRenderingDisabled is crashing on NV windows drivers for some reason. Let me know if you cannot reproduce that, I can try on my development machine.

2021-11-29 21:53 UTC, jeremyg-lunarg commented on tests/vklayertests_others.cpp
> +    pipeline_rendering_info.pColorAttachmentFormats = &color_formats;
should pipeline_rendering_info be used somewhere in this test?

2021-11-29 21:53 UTC, jeremyg-lunarg commented on tests/vklayertests_command.cpp
> +    if (DeviceExtensionSupported(VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME)) {
Please use AddRequiredDeviceExtensions() for this.

2021-11-29 21:53 UTC, jeremyg-lunarg commented on tests/vklayertests_command.cpp
> +    /*UNASSIGNED-CoreValidation-DrawState-InvalidCommandBuffer(ERROR / SPEC): msgNum: 298202768 -
It looks to me like the code in  CoreChecks::ValidateCmdSubpassState() that emits this error is checking the same thing as your code in CoreChecks::PreCallValidateCmdExecuteCommands() for 06018 and 06024.  I think the UNASSIGNED check can be removed.

2021-11-30 12:49 UTC, stu-s commented on tests/vklayertests_others.cpp
> +    pipeline_rendering_info.pColorAttachmentFormats = &color_formats;
Nope, it should have been deleted.

2021-11-30 12:50 UTC, stu-s commented on tests/vklayertests_command.cpp
> +    if (DeviceExtensionSupported(VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME)) {
Fixed

2021-11-30 12:50 UTC, stu-s commented on tests/vklayertests_command.cpp
> +    /*UNASSIGNED-CoreValidation-DrawState-InvalidCommandBuffer(ERROR / SPEC): msgNum: 298202768 -
Done. Thanks.

2021-11-30 12:52 UTC, stu-s commented
I've applied the fixes, uncommented the two tests, and added a commit to remove the old VU.

I haven't seen ValidateBeginRenderingDisabled() crash, but I'll have a poke around.

2021-11-30 15:09 UTC, jeremyg-lunarg approved these changes
LGTM, Thanks!

2021-11-30 15:09 UTC, merged