Validate spirv storage class
KhronosGroup/Vulkan-ValidationLayers pull request #3596
Opened 2021-12-09 18:04 UTC by ziga-lunarg

Added following VUIDs:

VUID-SampleId-SampleId-04355
VUID-FrontFacing-FrontFacing-04230
VUID-ClipDistance-ClipDistance-04189
VUID-CullDistance-CullDistance-04198
VUID-Layer-Layer-04275
VUID-ViewportIndex-ViewportIndex-04407
VUID-SampleMask-SampleMask-04358
VUID-PointCoord-PointCoord-04312
VUID-SamplePosition-SamplePosition-04361
VUID-VertexIndex-VertexIndex-04399
VUID-BaseInstance-BaseInstance-04182
VUID-BaseVertex-BaseVertex-04185
VUID-InstanceIndex-InstanceIndex-04264
VUID-NumSubgroups-NumSubgroups-04294
VUID-NumWorkgroups-NumWorkgroups-04297
VUID-BaryCoordNV-BaryCoordNV-04155
VUID-HelperInvocation-HelperInvocation-04240
VUID-SubgroupEqMask-SubgroupEqMask-04370
VUID-SubgroupGeMask-SubgroupGeMask-04372
VUID-SubgroupGtMask-SubgroupGtMask-04374
VUID-SubgroupLtMask-SubgroupLtMask-04378
VUID-SubgroupLeMask-SubgroupLeMask-04376
VUID-LocalInvocationId-LocalInvocationId-04282
VUID-LocalInvocationIndex-LocalInvocationIndex-04285
VUID-ShadingRateKHR-ShadingRateKHR-04491
VUID-WorkgroupId-WorkgroupId-04423
VUID-SubgroupSize-SubgroupSize-04382
VUID-SubgroupId-SubgroupId-04368
VUID-TessLevelInner-TessLevelInner-04396
VUID-TessLevelOuter-TessLevelOuter-04392
VUID-TessCoord-TessCoord-04388

2021-12-09 18:18 UTC, sfricke-samsung requested changes
So all of these should be in SPIR-V Tools already

https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/val/validation_state.cpp#L1385

Which if you run the "todo script" with the certain flag you will see
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2145

So curious (haven't tried) but shouldn't all of these tests fail from an invalid SPIR-V module?

For example `VUID-Layer-Layer-04275` was added with tests here https://github.com/KhronosGroup/SPIRV-Tools/pull/4013

2021-12-09 20:31 UTC, ncesario-lunarg commented
> So all of these should be in SPIR-V Tools already

@sfricke-samsung as in this will get reported as part of the spirv-val output?

2021-12-09 21:11 UTC, sfricke-samsung commented
@ncesario-lunarg yes, for example if I run `./test/val/test_val_abcde --gtest_filter=*LayerAndViewportIndexFragmentNotInput*` in SPIRV-Tools you will see

```
[VUID-Layer-Layer-04275] Vulkan spec doesn't allow BuiltIn Layer and ViewportIndex to be used for variables with Output storage class if execution model is Fragment. ID <2> (OpVariable) depends on ID <3> (OpTypeStruct) which is decorated with BuiltIn Layer. Id <2> is later referenced by ID <83> (OpAccessChain) in function <1> which is called with execution model Fragment.
  %83 = OpAccessChain %_ptr_Output_uint %2 %uint_0
```

Which is the same output one would see if running `spirv-val`

2021-12-09 21:30 UTC, ncesario-lunarg commented
👍if _all_ of these are covered by spirv-val (which should also get printed by [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/shader_validation.cpp#L2516), right?), then I don't think there is a reason to duplicate them inside of the VL.

What do you think @ziga-lunarg?

2021-12-09 21:58 UTC, sfricke-samsung commented on tests/vklayertests_pipeline_shader.cpp
> +%gl_NumSubgroups = OpVariable %_ptr_Input_uint Output
So if I take this an `spirv-as --target-env vulkan1.2 x.spvasm -o x.spv && spirv-val --target-env vulkan1.2 x.spv` I get 

```
error: line 19: From SPIR-V spec, section 3.32.8 on OpVariable:
Its Storage Class operand must be the same as the Storage Class operand of the result type.
  %gl_NumSubgroups = OpVariable %_ptr_Input_uint Output
```

But some reason this is not getting tripped when running through the test framework :confused:

2021-12-09 22:05 UTC, sfricke-samsung commented on tests/vklayertests_pipeline_shader.cpp
> +%gl_NumSubgroups = OpVariable %_ptr_Input_uint Output
ok, so I see what is happening

at 

```cpp
cs_pipeline.cs_ = layer_data::make_unique<VkShaderObj>(m_device, csSource, VK_SHADER_STAGE_COMPUTE_BIT, this);
```

it IS triggering `UNASSIGNED-CoreValidation-Shader-InconsistentSpirv` but it is being skipped

2021-12-09 22:23 UTC, ziga-lunarg commented
> 👍if _all_ of these are covered by spirv-val (which should also get printed by [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/shader_validation.cpp#L2516), right?), then I don't think there is a reason to duplicate them inside of the VL.
> 
> What do you think @ziga-lunarg?

I can close this if it's already validated

2021-12-09 22:23 UTC, ziga-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +%gl_NumSubgroups = OpVariable %_ptr_Input_uint Output
Is this not a different error than what I'm checking?

2021-12-09 22:33 UTC, sfricke-samsung commented on tests/vklayertests_pipeline_shader.cpp
> +%gl_NumSubgroups = OpVariable %_ptr_Input_uint Output
> VUID-NumSubgroups-NumSubgroups-04294
The variable decorated with NumSubgroups must be declared using the Input Storage Class

So yes, your test is doing that but it should be

```patch
- %_ptr_Input_uint = OpTypePointer Input %uint
+ %_ptr_Input_uint = OpTypePointer Output %uint
```

otherwise `spirv-val` is hitting the error about first

2021-12-09 22:38 UTC, ziga-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +%gl_NumSubgroups = OpVariable %_ptr_Input_uint Output
If you change that, you get the same error I'm checking for?

2021-12-09 23:00 UTC, sfricke-samsung commented on tests/vklayertests_pipeline_shader.cpp
> +%gl_NumSubgroups = OpVariable %_ptr_Input_uint Output
```patch
diff --git a/layers/shader_validation.cpp b/layers/shader_validation.cpp
index aaa73ecd2..9bd56d04d 100644
--- a/layers/shader_validation.cpp
+++ b/layers/shader_validation.cpp
@@ -2751,7 +2751,7 @@ bool CoreChecks::ValidatePipelineShaderStage(const PIPELINE_STATE *pipeline, con
     skip |= ValidateShaderStageWritableOrAtomicDescriptor(pStage->stage, stage_state.has_writable_descriptor,
                                                           stage_state.has_atomic_descriptor);
     skip |= ValidateShaderStageInputOutputLimits(module, pStage, pipeline, entrypoint);
-    skip |= ValidateDecorationWithStorageType(module, pStage->stage);
+    // skip |= ValidateDecorationWithStorageType(module, pStage->stage);
     skip |= ValidateShaderStorageImageFormats(module);
     skip |= ValidateShaderStageMaxResources(pStage->stage, pipeline);
     skip |= ValidateAtomicsTypes(module);
diff --git a/tests/vklayertests_pipeline_shader.cpp b/tests/vklayertests_pipeline_shader.cpp
index bf7f01f9c..b289022d1 100644
--- a/tests/vklayertests_pipeline_shader.cpp
+++ b/tests/vklayertests_pipeline_shader.cpp
@@ -16669,7 +16669,7 @@ TEST_F(VkLayerTest, ValidateDecorationsWithStorageClassCompute) {
        %uint = OpTypeInt 32 0
 %_ptr_Workgroup_uint = OpTypePointer Workgroup %uint
           %x = OpVariable %_ptr_Workgroup_uint Workgroup
-%_ptr_Input_uint = OpTypePointer Input %uint
+%_ptr_Input_uint = OpTypePointer Output %uint
 %gl_NumSubgroups = OpVariable %_ptr_Input_uint Output
 
                ; Function main
@@ -16683,13 +16683,11 @@ TEST_F(VkLayerTest, ValidateDecorationsWithStorageClassCompute) {
 
         CreateComputePipelineHelper cs_pipeline(*this);
         cs_pipeline.InitInfo();
-        cs_pipeline.cs_ = layer_data::make_unique<VkShaderObj>(m_device, csSource, VK_SHADER_STAGE_COMPUTE_BIT, this);
-        cs_pipeline.InitState();
         m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "VUID-NumSubgroups-NumSubgroups-04294");
-        cs_pipeline.CreateComputePipeline();
+        VkShaderObj::CreateFromASM(*m_device, *this, VK_SHADER_STAGE_COMPUTE_BIT, csSource, "main", nullptr, SPV_ENV_VULKAN_1_1);
         m_errorMonitor->VerifyFound();
     }
-
+return;
     {
         static const std::string csSource = R"(
                OpCapability Shader
```

This will still pass `./tests/vk_layer_validation_tests --gtest_filter=VkLayerTest.ValidateDecorationsWithStorageClassCompute`

The error message being caught is

```
Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x3977740, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: [VUID-NumSubgroups-NumSubgroups-04294] Vulkan spec allows BuiltIn NumSubgroups to be only used for variables with Input storage class. ID <3> (OpVariable) is referencing ID <3> (OpVariable) which is decorated with BuiltIn NumSubgroups. ID <3> (OpVariable) uses storage class Output.
  %gl_NumSubgroups = OpVariable %_ptr_Output_uint Output
```

which still has the string in it... So I think the tests here are still worth having IMO in case SPIRV-Tools regresses on us, just I think the standalone shader validation should be kept in SPIRV-Tools

2021-12-10 17:23 UTC, ncesario-lunarg commented
@ziga-lunarg it would probably be good to keep the tests to verify spirv-val is indeed logging these errors correctly.

2021-12-13 11:15 UTC, ziga-lunarg commented
> @ziga-lunarg it would probably be good to keep the tests to verify spirv-val is indeed logging these errors correctly.

Sure, but then I need to somehow get the spirv-val error message and match it with a VUID?

2021-12-13 15:31 UTC, sfricke-samsung commented
> Sure, but then I need to somehow get the spirv-val error message and match it with a VUID?

The VUID you have are the same, and it should be in the `spirv-val` error message so the VVL test framework will see it in the error string. The only difference is you need to check at `vkCreateShaderModule` time and not pipeline creation time I think for all of them

2021-12-13 17:27 UTC, ncesario-lunarg commented
> The VUID you have are the same, and it should be in the spirv-val error message so the VVL test framework will see it in the error string. The only difference is you need to check at vkCreateShaderModule time and not pipeline creation time I think for all of them

This is also my understanding. i.e., I don't think we're doing anything other than a string search with `ErrorMonitor`, so adding the testing for the VUID in the "normal way" should "just work." If not, then that would be good to know, too.

2022-10-15 08:05 UTC, spencer-lunarg commented
closing as these are validated in `spirv-val` already

2022-10-15 08:05 UTC, closed without merging