tests: Add VK_KHR_dynamic_rendering VUs
KhronosGroup/Vulkan-ValidationLayers pull request #3600
Opened 2021-12-13 03:59 UTC by AaronHaganAMD

VUID-VkCommandBufferInheritanceRenderingInfoKHR-colorAttachmentCount-06004
VUID-VkCommandBufferInheritanceRenderingInfoKHR-variableMultisampleRate-06005
VUID-vkCmdDraw*-pDepthAttachment-06189
VUID-vkCmdDraw*-pStencilAttachment-06190
VUID-vkCmdDraw*-renderPass-06198
VUID-VkGraphicsPipelineCreateInfo-renderPass-06055
Fixes #3595
VUID-VkGraphicsPipelineCreateInfo-renderPass-06057
VUID-VkGraphicsPipelineCreateInfo-renderPass-06058

2021-12-13 15:34 UTC, ziga-lunarg commented on layers/core_validation.cpp
> +                auto depth_view_state = Get<IMAGE_VIEW_STATE>(pCB->activeRenderPass->dynamic_rendering_begin_rendering_info.pDepthAttachment->imageView);
This could be `const auto&` so shared_ptr doesn't get copied

2021-12-13 15:36 UTC, ziga-lunarg commented on layers/core_validation.cpp
> +                    LogError(device, "VUID-VkGraphicsPipelineCreateInfo-renderPass-06055",
This is missing `skip |=` in front

2021-12-13 18:33 UTC, ncesario-lunarg reviewed
This code LGTM! Can we have tests added for each of these VUIDs?

The failure on Github Actions is failing during the mock ICD build before VVL is ever touched, so this might be an unrelated problem with the state of the Vulkan-Tools repo; haven't verified this yet.

The internal CI failure is due to a crash on our nvidia machine in the `VkPositiveLayerTest.CreateGraphicsPipelineDynamicRenderingNoInfo` test.

2021-12-13 18:33 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +        if ((p_attachment_sample_count_info_amd || p_attachment_sample_count_info_nv) == false) {
This seems a bit more confusing than just `(!p_attachment_sample_count_info_amd && !p_attachment_sample_count_info_nv)`, but that might just be me.

2021-12-13 18:33 UTC, ncesario-lunarg commented on layers/core_validation.h
> +    const char* dynamic_rendering_06189 = kVUIDUndefined;
Appending the VUID here makes a lot of sense! I wonder why this wasn't done before 🤔?

2021-12-13 18:33 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +    for (uint32_t location = 0; location < location_map.size(); ++location) {
This LGTM, but I'm curious if this fixed a specific error you were hitting?

2021-12-13 18:53 UTC, AaronHaganAMD commented on layers/shader_validation.cpp
> +    for (uint32_t location = 0; location < location_map.size(); ++location) {
This should prevent #3595 from crashing.

2021-12-13 20:56 UTC, AaronHaganAMD commented
> pipeline->rp_state->dynamic_rendering_pipeline_create_info.colorAttachmentCount

the failing test should be fixed now.

2021-12-13 21:11 UTC, AaronHaganAMD commented on layers/core_validation.h
> +    const char* dynamic_rendering_06189 = kVUIDUndefined;
yeah.. I can go back and re-name the other dynamic rendering VUIDs

2021-12-13 21:12 UTC, AaronHaganAMD commented
> This code LGTM! Can we have tests added for each of these VUIDs?
> 
> The failure on Github Actions is failing during the mock ICD build before VVL is ever touched, so this might be an unrelated problem with the state of the Vulkan-Tools repo; haven't verified this yet.
> 
> The internal CI failure is due to a crash on our nvidia machine in the `VkPositiveLayerTest.CreateGraphicsPipelineDynamicRenderingNoInfo` test.

Yes. will work on adding tests as well for the VUIDs

2021-12-13 21:43 UTC, jeremyg-lunarg commented
Shouldn't the commit message be tagged "corechecks: ..." or "layers: ..."? "tests:" indicates a change to the unit tests. Otherwise this LGTM

2021-12-14 00:48 UTC, AaronHaganAMD commented
> Shouldn't the commit message be tagged "corechecks: ..." or "layers: ..."? "tests:" indicates a change to the unit tests. Otherwise this LGTM

Yes.. I updated it to "layers"

2021-12-14 01:16 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +    for (uint32_t location = 0; location < location_map.size(); ++location) {
FYI @Tony-LunarG.

2021-12-15 13:16 UTC, ncesario-lunarg commented
_Hopefully_ https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3606 resolves the github checks 🤞. Once that's in, then I think just adding tests for these VUIDs should be all that's left!

2021-12-16 16:55 UTC, Tony-LunarG commented on layers/shader_validation.cpp
> +    for (uint32_t location = 0; location < location_map.size(); ++location) {
While this does fix 
dEQP-VK.dynamic_rendering.suballocation.load_store_op_none.color_load_op_none_store_op_none_resolve, 
it now causes 
VkPositiveLayerTest.CreateGraphicsPipelineDynamicRenderingNoInfo 
to crash at 
```
227 auto format = pipeline->rp_state->dynamic_rendering_pipeline_create_info.pColorAttachmentFormats[location];
```
location is zero and pColorAttachmentFormats is NULL

2021-12-17 02:47 UTC, AaronHaganAMD commented on layers/shader_validation.cpp
> +    for (uint32_t location = 0; location < location_map.size(); ++location) {
Crashes should be resolved with 85e4bcc293495cd22676b5edd989008dc28b8661

2021-12-17 04:13 UTC, ncesario-lunarg reviewed
Added a few comments before realizing this is a draft :)

Looks good though!

2021-12-17 04:13 UTC, ncesario-lunarg commented on tests/vklayertests_dynamic_rendering.cpp
> +    SetTargetApiVersion(VK_API_VERSION_1_2);
If 1.2 is needed, a `if (DeviceValidationVersion() < VK_API_VERSION_1_2) ...` check should be made after any `InitFramework` (or `Init` in this case, which calls `InitFramework`).

2021-12-17 04:13 UTC, ncesario-lunarg commented on tests/vklayertests_dynamic_rendering.cpp
> +    VkCommandBufferInheritanceRenderingInfoKHR cmd_buffer_inheritance_rendering_info = {};
Might be a bit more readable and more inline with the [style guide](https://google.github.io/styleguide/cppguide.html#Local_Variables) if these are declared when initialized. You can use the auto-generated `LvlInitStruct<>` functions to cut down on the repetition a bit.

2021-12-17 04:13 UTC, ncesario-lunarg commented on tests/vklayertests_dynamic_rendering.cpp
> +    vk::BeginCommandBuffer(secondary_cmd_buffer, &cmd_buffer_begin_info);
It would be great if we could have one `VerifyFound` per check, as that will make it easier to pinpoint failures in the future. e.g.,
```cpp
// state setup for 06003
m_errorMonitor->SetDesiredFailure(...06003);
vk::BeginCommandBuffer(...);
m_errorMonitor->VerifyFound();

// state setup for 06004
m_errorMonitor->SetDesiredFailure(...06004);
vk::BeginCommandBuffer(...);
...
m_errorMonitor->VerifyFound();
...
```

2021-12-20 16:18 UTC, AaronHaganAMD commented on tests/vklayertests_dynamic_rendering.cpp
> +    vk::BeginCommandBuffer(secondary_cmd_buffer, &cmd_buffer_begin_info);
I seem to be getting the other VU errors when separating the VUs like this. for example...

    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "VUID-VkGraphicsPipelineCreateInfo-renderPass-06055");
    pipe.CreateVKPipeline(pl.handle(), VK_NULL_HANDLE, &create_info);
    m_errorMonitor->VerifyFound();

    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "VUID-VkGraphicsPipelineCreateInfo-renderPass-06057");
    pipe.CreateVKPipeline(pl.handle(), VK_NULL_HANDLE, &create_info);
    m_errorMonitor->VerifyFound();

On the first VerifyFound it is reporting that "VUID-VkGraphicsPipelineCreateInfo-renderPass-06057" is hit and unhandled...

2021-12-20 19:13 UTC, ncesario-lunarg commented on tests/vklayertests_dynamic_rendering.cpp
> +    vk::BeginCommandBuffer(secondary_cmd_buffer, &cmd_buffer_begin_info);
Ah, ok, if they are really coupled (i.e., it's impossible to trigger one without also triggering others), then what you currently have is necessary.

2021-12-20 19:54 UTC, ncesario-lunarg requested changes
This is causing `VkLayerTest.ExecuteDiffertQueueFlagsSecondaryCB` to crash. I haven't dug into this too much, but adding the following to that test seems to fix it:
```diff
diff --git a/tests/vklayertests_command.cpp b/tests/vklayertests_command.cpp
index 08c84cb74..23612cd21 100644
--- a/tests/vklayertests_command.cpp
+++ b/tests/vklayertests_command.cpp
@@ -5183,8 +5183,13 @@ TEST_F(VkLayerTest, ExecuteDiffertQueueFlagsSecondaryCB) {
     command_buffer_allocate_info.level = VK_COMMAND_BUFFER_LEVEL_SECONDARY;
     vk::AllocateCommandBuffers(m_device->device(), &command_buffer_allocate_info, &command_buffer[1]);
 
-    VkCommandBufferBeginInfo begin_info = {};
-    begin_info.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
+    auto inheritance_info = LvlInitStruct<VkCommandBufferInheritanceInfo>();
+    inheritance_info.renderPass = m_renderPass;
+    inheritance_info.subpass = 0;
+    inheritance_info.framebuffer = m_framebuffer;
+
+    auto begin_info = LvlInitStruct<VkCommandBufferBeginInfo>();
+    begin_info.pInheritanceInfo = &inheritance_info;
 
     // secondary
     vk::BeginCommandBuffer(command_buffer[1], &begin_info);
```

FYI @sfricke-samsung (original author?) as I'm not sure how this test was working before since it hits VUID-00051 (no inheritance info for the secondary command buffer)? I really need to get #3177 in sooner than later...

2021-12-20 19:54 UTC, ncesario-lunarg commented on tests/vklayertests_dynamic_rendering.cpp
> +    multisample_state_create_info.rasterizationSamples = VK_SAMPLE_COUNT_2_BIT;
Looks like this is unused (causing a warning on linux compilers)?

2021-12-20 20:06 UTC, AaronHaganAMD commented on tests/vklayertests_dynamic_rendering.cpp
> +    multisample_state_create_info.rasterizationSamples = VK_SAMPLE_COUNT_2_BIT;
VkLayerTest.ExecuteDiffertQueueFlagsSecondaryCB and this warning should be fixed with 802f7da14a9f819787b5088143cb98a90e1dcd57

2021-12-21 15:44 UTC, sfricke-samsung commented
>  I'm not sure how this test was working before since it hits VUID-00051

So the issue I think is how the error message is wrapped

```cpp
    // secondary
    vk::BeginCommandBuffer(command_buffer[1], &begin_info);
    vk::EndCommandBuffer(command_buffer[1]);

    // Try using different pool's command buffer as secondary
    vk::BeginCommandBuffer(command_buffer[0], &begin_info);
    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "VUID-vkCmdExecuteCommands-pCommandBuffers-00094");
    vk::CmdExecuteCommands(command_buffer[0], 1, &command_buffer[1]);
    m_errorMonitor->VerifyFound();
    vk::EndCommandBuffer(command_buffer[0]);
  ```
  
  so because it was done prior to ` m_errorMonitor->SetDesiredFailureMsg` it doesn't get caught I think... but 100% agree it is currently wrong

2021-12-21 17:07 UTC, ncesario-lunarg requested changes
Some minor test nits, but looks like this is still missing the other test fixes?

2021-12-21 17:42 UTC, ncesario-lunarg commented on tests/vklayertests_dynamic_rendering.cpp
> +    cmd_buffer_inheritance_rendering_info.viewMask = 0xff;
This will need a similar solution to https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3616/files#r772606427, but I think there is also a change necessary for `MostSignificantBit`.

2021-12-22 17:10 UTC, AaronHaganAMD commented on tests/vklayertests_dynamic_rendering.cpp
> +    cmd_buffer_inheritance_rendering_info.viewMask = 0xff;
I updated similar to #3616

2021-12-22 18:27 UTC, ncesario-lunarg approved these changes

2021-12-22 18:27 UTC, merged