add VK_ARM_rasterization_order_attachment_access VUs and tests
KhronosGroup/Vulkan-ValidationLayers pull request #3601
Opened 2021-12-13 16:39 UTC by youkim02

2021-12-13 16:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3601) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3601) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3601) it.</sub>

2021-12-14 01:14 UTC, ncesario-lunarg reviewed
Some minor nits, but looks good. Thanks!

2021-12-14 01:14 UTC, ncesario-lunarg commented on layers/stateless_validation.h
> +        std::vector<uint32_t> subpasses_flags;
Looks like this should probably be `std::vector<VkSubpassDescriptionFlags>`?

2021-12-14 01:14 UTC, ncesario-lunarg commented on tests/positive/pipeline.cpp
> +                                      "VUID-VkPipelineColorBlendStateCreateInfo-rasterizationOrderColorAttachmentAccess-06465");
Ideally only positive tests live under the `tests/positive` directory. Can this test be split up such that the "positive" portion  lives here, and the rest lives under, say, `tests/vklayertests_pipeline_shader.cpp`?

2021-12-14 01:14 UTC, ncesario-lunarg commented on tests/positive/pipeline.cpp
> +        return render_pass;
It would be nice if this could instead return a `vk_testing::RenderPass` instance to help protect against future resource leaking.

2021-12-14 01:14 UTC, ncesario-lunarg commented on tests/positive/pipeline.cpp
> +    VkRenderPass render_pass;
Probably would be good to use `vk_testing::RenderPass` here to avoid resource leaking.

2021-12-14 01:19 UTC, ncesario-lunarg commented
We're getting the following failure on our internal nvidia CI machine:
```
[ RUN      ] VkLayerTest.PSOPolygonModeInvalid
ERROR: ----stderr---------------------------------------------------
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(1234) : Assertion failed: vector subscript out of range
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(1235) : Assertion failed: "Standard C++ Libraries Out of Range" && 0
```
It's a bit strange as this is only happening on that platform, and only for debug 64 bit.

2021-12-14 10:12 UTC, youkim02 commented on layers/parameter_validation_utils.cpp
> +                                "VK_PIPELINE_DEPTH_STENCIL_STATE_CREATE_RASTERIZATION_ORDER_ATTACHMENT_DEPTH_ACCESS_BIT_ARM");
Ack!

2021-12-14 10:41 UTC, youkim02 commented on layers/stateless_validation.h
> +        std::vector<uint32_t> subpasses_flags;
You are right. Thank you!

2021-12-14 17:11 UTC, youkim02 commented on tests/positive/pipeline.cpp
> +    VkRenderPass render_pass;
Ack

2021-12-14 17:11 UTC, youkim02 commented on tests/positive/pipeline.cpp
> +        return render_pass;
Ack

2021-12-14 18:01 UTC, youkim02 commented on tests/positive/pipeline.cpp
> +                                      "VUID-VkPipelineColorBlendStateCreateInfo-rasterizationOrderColorAttachmentAccess-06465");
ack

2021-12-15 11:55 UTC, ncesario-lunarg reviewed
One final nit in the tests, but LGTM!

2021-12-15 11:55 UTC, ncesario-lunarg commented on tests/positive/pipeline.cpp
> +    SetTargetApiVersion(VK_API_VERSION_1_2);
If this test requires 1.2, You'll probably want a `if (DeviceValidationVersion() >= VK_API_VERSION_1_2)` after the `InitFrameworkAndRetrieveFeatures` call (and similarly for other instances).

2021-12-15 17:46 UTC, younggwan-arm commented
It looks like mock CI problem fixed. How can I run the CI again?

2021-12-15 20:25 UTC, ncesario-lunarg commented
I have to trigger it manually for the first PR, but it should be automatic for you after this one merges.

2021-12-16 17:01 UTC, ncesario-lunarg requested changes

2021-12-16 17:01 UTC, ncesario-lunarg commented on layers/stateless_validation.h
> +        renderpass_state.subpasses_flags.reserve(pCreateInfo->subpassCount);
Sorry I missed this before. This needs to be `resize` instead of `reserve` (this is what's causing the crash in CI).

2021-12-16 19:12 UTC, younggwan-arm commented on layers/stateless_validation.h
> +        renderpass_state.subpasses_flags.reserve(pCreateInfo->subpassCount);
My mistake. I will take it.

2021-12-16 20:30 UTC, ncesario-lunarg approved these changes

2021-12-16 21:11 UTC, merged

2021-12-17 01:10 UTC, timvpGoogle commented
This CL is crashing in Chromium:
3345619: Roll vulkan-deps from 39f3a18bdfbe to 71f20fae7128 (2 revisions) | https://chromium-review.googlesource.com/c/chromium/src/+/3345619

Example crash:
https://chromium-swarm.appspot.com/task?id=57de0b72d03c4711&w=true
```
[ RUN      ] PipelineProgramUniformUpdatesTest.ToggleBetweenPPOAndProgramVKWithUniformUpdate/ES3_1_Vulkan
angle::PrintStackBacktrace() at crash_handler_posix.cpp:454
angle::Handler(int) at crash_handler_posix.cpp:616
killpg at ??:?
CoreChecks::ValidateExecutionModes(SHADER_MODULE_STATE const*, spirv_inst_iter, VkShaderStageFlagBits, PIPELINE_STATE const*) const at shader_validation.cpp:2049
CoreChecks::ValidatePipelineShaderStage(PIPELINE_STATE const*, PipelineStageState const&, bool) const at shader_validation.cpp:2600
CoreChecks::ValidateGraphicsPipelineShaderState(PIPELINE_STATE const*) const at shader_validation.cpp:?
CoreChecks::ValidatePipelineUnlocked(PIPELINE_STATE const*, unsigned int) const at core_validation.cpp:1682
CoreChecks::PreCallValidateCreateGraphicsPipelines(VkDevice_T*, VkPipelineCache_T*, unsigned int, VkGraphicsPipelineCreateInfo const*, VkAllocationCallbacks const*, VkPipeline_T**, void*) const at core_validation.cpp:5699
vulkan_layer_chassis::CreateGraphicsPipelines(VkDevice_T*, VkPipelineCache_T*, unsigned int, VkGraphicsPipelineCreateInfo const*, VkAllocationCallbacks const*, VkPipeline_T**) at chassis.cpp:572
initGraphics at vk_wrapper.h:1554
rx::GraphicsPipelineCache::insertPipeline(rx::ContextVk*, rx::vk::PipelineCache const&, rx::vk::RenderPass const&, rx::vk::PipelineLayout const&, angle::BitSetT<16ul, unsigned long, unsigned long> const&, angle::BitSetT<32ul, unsigned long, unsigned long> const&, angle::BitSetT<8ul, unsigned char, unsigned long> const&, angle::PackedEnumMap<gl::ShaderType, rx::vk::BindingPointer<rx::vk::ObjectAndSerial<rx::vk::ShaderModule> >, 6ul> const&, rx::vk::SpecializationConstants const&, rx::vk::GraphicsPipelineDesc const&, rx::vk::GraphicsPipelineDesc const**, rx::vk::PipelineHelper**) at vk_cache_utils.cpp:3688
getPipeline at vk_cache_utils.h:1612
IsError at Error.h:180
IsError at Error.h:180
rx::ContextVk::drawArrays(gl::Context const*, gl::PrimitiveMode, int, int) at ContextVk.cpp:2679
IsError at Error.h:180
(anonymous namespace)::PipelineProgramUniformUpdatesTest_ToggleBetweenPPOAndProgramVKWithUniformUpdate_Test::TestBody() at VulkanUniformUpdatesTest.cpp:635
os_stack_trace_getter at gtest.cc:6229
testing::TestInfo::Run() at gtest.cc:2888
testing::TestSuite::Run() at gtest.cc:3046
testing::internal::UnitTestImpl::RunAllTests() at gtest.cc:5914
testing::UnitTest::Run() at gtest.cc:5482
RUN_ALL_TESTS at gtest.h:2497
main at angle_generic_tests_main.cpp:17
__libc_start_main at libc-start.c:344
_start at ??:?
```

Can we revert this while it's investigated?