layers: Fix assumption on DRM modifiers
KhronosGroup/Vulkan-ValidationLayers pull request #3603
Opened 2021-12-14 14:57 UTC by djdeath

There is a confusion that DRM modifiers are bit fields but they're more like enums.

2021-12-14 14:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3603) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3603) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3603) it.</sub>

2021-12-14 14:58 UTC, djdeath commented
/cc @sfricke-samsung since you wrote the code

2021-12-14 15:41 UTC, sfricke-samsung approved these changes
I wrote `VK_EXT_image_drm_format_modifier` blind (didn't have anything to run it on) so feel free to make any changes needed (these all look fine to me)

2021-12-14 15:42 UTC, sfricke-samsung commented on layers/buffer_validation.cpp
> +    VkFormatFeatureFlags tiling_features = 0;
so I wish I would have wrote a comment WHY I used `VK_FORMAT_FEATURE_FLAG_BITS_MAX_ENUM` but I use it in a few other places for the same issue... curious if worth changing the other use cases of `VK_FORMAT_FEATURE_FLAG_BITS_MAX_ENUM` to `0` as well

2021-12-14 15:46 UTC, sfricke-samsung commented on layers/buffer_validation.cpp
> +    VkFormatFeatureFlags tiling_features = 0;
looking more at it, I think I was worried my logic for `VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT` would not work and throw a false error for `VUID-VkImageViewCreateInfo-None-02273`

2021-12-14 15:57 UTC, djdeath commented on layers/buffer_validation.cpp
> +    VkFormatFeatureFlags tiling_features = 0;
`0` sounds like the right value to have if the implementation reports no feature or doesn't list the drm modifier. I'll update the other location.

2021-12-14 16:36 UTC, ncesario-lunarg commented on layers/buffer_validation.cpp
> +    VkFormatFeatureFlags tiling_features = 0;
I like the idea of using a known constant such as `VK_FORMAT_FEATURE_FLAG_BITS_MAX_ENUM` as it's not clear (to me, at least) what `0` represents (e.g., is it a valid enum value?). If `0` makes sense to everyone though, I'm fine with it.

2021-12-14 16:41 UTC, ncesario-lunarg requested changes
Just my 2 cents on using 0 as an invalid value and a type change request, but otherwise LGTM!

2021-12-14 16:41 UTC, ncesario-lunarg commented on layers/buffer_validation.cpp
> +        std::set<uint64_t> drm_format_modifiers;
If possible, this should probably be a `layer_data::unordered_set`.

2021-12-14 17:06 UTC, sfricke-samsung commented on layers/buffer_validation.cpp
> +    VkFormatFeatureFlags tiling_features = 0;
So there is a 3 way if/else case and `tiling_features` should have been set by the end of it. I guess while I agree `VK_FORMAT_FEATURE_FLAG_BITS_MAX_ENUM` shows you it is invalid, we were never checking/asserting it anyway which is why I was ok with `0`

2021-12-15 17:56 UTC, djdeath commented on layers/buffer_validation.cpp
> +        std::set<uint64_t> drm_format_modifiers;
Done.

2021-12-15 18:22 UTC, djdeath commented
Contribution from Intel Corporation (still tried to sign the CLA but it's not working...)

2021-12-15 20:37 UTC, ncesario-lunarg commented on layers/buffer_validation.cpp
> +        std::unordered_set<uint64_t> drm_format_modifiers;
Did the `layer_data::unordered_set` version not work?

2021-12-15 20:52 UTC, djdeath commented on layers/buffer_validation.cpp
> +        std::unordered_set<uint64_t> drm_format_modifiers;
Ah sorry, I got them mixed :)

2021-12-16 17:03 UTC, ncesario-lunarg commented
I think all that's missing is CLA signature, and then this is GTG :)

2021-12-16 17:31 UTC, djdeath commented
> I think all that's missing is CLA signature, and then this is GTG :)

Like I mentioned above, this is a contribution from Intel Corporation. I have tried the CLA signature many times, it doesn't work.
Could it be that it's because I'm using my personal github account which is not linked to my email address?

I have trouble opening PRs with my other account because it's used for internal Intel things :(

2021-12-16 21:14 UTC, Khronoswebmaster commented
Hi @djdeath, it appears the commit was done from account @llandwerlin-intel, and that account will need to sign the CLA.

2021-12-16 22:27 UTC, llandwerlin-intel commented
> Hi @djdeath, it appears the commit was done from account @llandwerlin-intel, and that account will need to sign the CLA.

Makes sense now, done.

2021-12-16 22:30 UTC, ncesario-lunarg approved these changes

2021-12-16 22:31 UTC, merged