Updated render area VUIDs
KhronosGroup/Vulkan-ValidationLayers pull request #3608
Opened 2021-12-16 10:44 UTC by stu-s

Removed VUIDs (recently removed from spec):
VUID-VkRenderPassBeginInfo-pNext-02854
VUID-VkRenderPassBeginInfo-pNext-02855
VUID-VkRenderingInfoKHR-pNext-06081
VUID-VkRenderingInfoKHR-pNext-06082

which are duplicates of:
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06166
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06167

Added VUIDs:
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06168
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06169

Updated VUIDs in InvalidDeviceGroupRenderArea test from:
VUID-VkRenderPassBeginInfo-pNext-02854
VUID-VkRenderPassBeginInfo-pNext-02855
to:
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06166
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06167

Added InvalidDeviceGroupRenderAreaDynamicRendering test to cover:
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06168
VUID-VkDeviceGroupRenderPassBeginInfo-offset-06169

2021-12-17 03:20 UTC, ncesario-lunarg requested changes
A few minor nits, but overall LGTM!

2021-12-17 03:20 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                                 "] sum of offset.x (%d) and extent.width (%u) is greater than maxFramebufferWidth (%u).",
`%d` -> `PRId32`
`%u` -> `PRIu32`

And similarly for the `y`-case below.

2021-12-17 03:20 UTC, ncesario-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    if (!AddRequiredDeviceExtensions(VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME)) {
This should go before `InitFramework` to ensure any necessary instance extensions are enabled.

2021-12-17 03:20 UTC, ncesario-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    SetTargetApiVersion(VK_API_VERSION_1_1);
If 1.1 is required, there should be an `if (DeviceValidationVersion() < VK_API_VERSION_1_1) ...` check after `InitFramework`.

2021-12-17 03:20 UTC, ncesario-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    VkRenderingInfoKHR begin_rendering_info = {};
Can consolidate a bit with `auto begin_rendering_info = LvlInitStruct<VkRenderingInfoKHR>(&device_group_render_pass_begin_info);` if desirable.

2021-12-17 10:12 UTC, stu-s commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    if (!AddRequiredDeviceExtensions(VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME)) {
Ah.  That means that all of the dynamic rendering tests I added to vklayertests_command.cpp are wrong, since I copy/pasted from there.  I'll add another commit to fix those

2021-12-17 10:12 UTC, stu-s commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    SetTargetApiVersion(VK_API_VERSION_1_1);
Also copied from the dynamic rendering tests in vklayertests_command.cpp.  I'll fix those too.

2021-12-17 10:35 UTC, stu-s commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    if (!AddRequiredDeviceExtensions(VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME)) {
Actually, isn't it already in the correct place as device extensions go between InitFramework() and InitState()?

Or should I be using DeviceExtensionSupported() and then m_device_extension_names.push_back() before calling InitState(), rather than using AddRequiredDeviceExtensions()?

2021-12-19 05:51 UTC, ncesario-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    if (!AddRequiredDeviceExtensions(VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME)) {
If the device extension has no instance dependencies, this would be ok, though would be somewhat inconsistent with other tests. Making the call before `InitFramework` ensures any dependent instance extensions get added as well (in this case, `VK_KHR_get_physical_device_properties2`); if that doesn't happen, the test can crash on some drivers. This isn't ideal, but we're trying to get the testing framework a bit more streamlined and less prone to crashing on untested HW.

See the code snippet [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/creating_tests.md#extensions) for intended usage (`IsRequestedExtensionsEnabled` should be `AreRequestedExtensionsEnabled`) and https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3285 for context.

2021-12-19 05:53 UTC, ncesario-lunarg commented on tests/vklayertests_command.cpp
>      if (!AddRequiredDeviceExtensions(VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME)) {
Yeah, this call should be before `InitFramework`. Even if you don't use anything from the required instance extension (`VK_KHR_get_physical_device_properties2`), not enabling it can cause problems on some platforms.

2021-12-20 12:48 UTC, stu-s commented on tests/vklayertests_command.cpp
>      if (!AddRequiredDeviceExtensions(VK_KHR_DYNAMIC_RENDERING_EXTENSION_NAME)) {
Done

2021-12-20 17:24 UTC, ncesario-lunarg approved these changes
LGTM, thanks for the changes!

2021-12-20 18:01 UTC, ncesario-lunarg requested changes
Hopefully one final change to prevent CI from crashing 🤞

2021-12-20 18:01 UTC, ncesario-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    m_commandBuffer->EndRendering();
Looks like the `EndRendering` command needs to be removed here and below. Since `BeginRendering` fails in the `PreCallValidate*` step, nothing ever gets dispatched to the driver, and I'm guessing that's why we're seeing a crash in `CmdEndRenderingKHR` on our local CI (Windows + Nvidia, which is currently the only platform we have that supports dynamic rendering in our CI).

2021-12-21 10:36 UTC, stu-s commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    m_commandBuffer->EndRendering();
Thanks.  Fixed.

2021-12-21 17:45 UTC, merged