Add tests for VkPipelineRenderingCreateInfoKHR VUIDs
KhronosGroup/Vulkan-ValidationLayers pull request #3616
Opened 2021-12-20 16:22 UTC by stu-s

Adds tests for:

VUID-VkPipelineRenderingCreateInfoKHR-pColorAttachmentFormats-06064
VUID-VkPipelineRenderingCreateInfoKHR-depthAttachmentFormat-06065
VUID-VkPipelineRenderingCreateInfoKHR-stencilAttachmentFormat-06164
VUID-VkPipelineRenderingCreateInfoKHR-depthAttachmentFormat-06165
VUID-VkPipelineRenderingCreateInfoKHR-multiview-06066
VUID-VkPipelineRenderingCreateInfoKHR-viewMask-06067

2021-12-20 19:10 UTC, ncesario-lunarg requested changes
Couple minor nits, but one possible layers bug that needs to be fixed (yay for tests!). Otherwise LGTM!

2021-12-20 19:10 UTC, ncesario-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +    pipeline_rendering_info.viewMask = 1 << multiview_props.maxMultiviewViewCount;
I think this needs to be something like `1u << (multiview_props.maxMultiviewViewCoun - 1u)`, otherwise you'll be off by one. However, even with that, I'm pretty sure there's a bug at https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3535/files#diff-b1a98a527f3c9e68d5e44886e229c38df0184ce6aaf581a531c5e5596ad0f51aR7155

I think `MostSignificantBit` currently returns 1 less than it should. FYI @AaronHaganAMD just to be sure. If that is indeed correct, then I think the following fix needs to be made in the layers code:
```diff
diff --git a/layers/vk_layer_utils.h b/layers/vk_layer_utils.h
index 1ccc7e509..cdedd4aef 100644
--- a/layers/vk_layer_utils.h
+++ b/layers/vk_layer_utils.h
@@ -161,7 +161,7 @@ static inline uint32_t MostSignificantBit(uint32_t mask) {
     uint32_t highest_view_bit = 0;
     for (uint32_t k = 0; k < 32; ++k) {
         if (((mask >> k) & 1) != 0) {
-            highest_view_bit = k;
+            highest_view_bit = k + 1;
         }
     }
     return highest_view_bit;
```

This could be made as a separate commit for this PR.

2021-12-20 19:45 UTC, stu-s commented on tests/vklayertests_pipeline_shader.cpp
> +    TEST_DESCRIPTION("Test pipeline rendering formats and viewmask");
Yep.  Copy and paste from the test above.  Fixed.

2021-12-20 19:45 UTC, stu-s commented on tests/vklayertests_pipeline_shader.cpp
> +    pd_features2.pNext = &multiview_features;
Fixed.  Thanks.

2021-12-20 20:05 UTC, stu-s commented on tests/vklayertests_pipeline_shader.cpp
> +    pipeline_rendering_info.viewMask = 1 << multiview_props.maxMultiviewViewCount;
I did wonder about this, but managed to convince myself that the code was correct.  I'm happy to be told otherwise!

2021-12-21 00:12 UTC, ncesario-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +    pipeline_rendering_info.viewMask = 1 << multiview_props.maxMultiviewViewCount;
Is `MostSignificantBit` supposed to be "0-based"? If so, I think the code at https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3535/files#diff-b1a98a527f3c9e68d5e44886e229c38df0184ce6aaf581a531c5e5596ad0f51aR7155 needs to be adjusted accordingly.

2021-12-21 00:36 UTC, ncesario-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +    pipeline_rendering_info.viewMask = 1 << multiview_props.maxMultiviewViewCount;
On my local machine (and it looks like our CI HW as well) where `maxMultiviewViewCount == 32`, `1 << multiview_props.maxMultiviewViewCount` evaluates to `1`, so I think at least that does need to change.

2021-12-21 11:19 UTC, stu-s commented on tests/vklayertests_pipeline_shader.cpp
> +    pipeline_rendering_info.viewMask = 1 << multiview_props.maxMultiviewViewCount;
Ah, yes, the test should probably be skipped for a value of 32.

@AaronHaganAMD do you have any thoughts on the viewMask stuff?  My understanding is that for `maxMultiviewViewCount=6` this means that bits 0-5 are all valid to use in viewMask, so to trigger the VUID I set bit 6 (`1 << maxMultiviewViewCount)` which causes `MostSignificantBit(viewMask)>=maxMultiviewViewCount` to be true.

2021-12-22 15:24 UTC, ncesario-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +    pipeline_rendering_info.viewMask = 1 << multiview_props.maxMultiviewViewCount;
Thanks to @AaronHaganAMD for the offline discussion; this was my mistake. As @stu-s suggested, skipping the test for `maxMultiviewViewCount == 32` seems correct. The name `MostSignificantBit` seems misleading to me, but I can change that in a separate commit.

2021-12-22 15:25 UTC, ncesario-lunarg approved these changes

2021-12-22 15:25 UTC, merged