layers: Dynamic Rendering render_area fixes
KhronosGroup/Vulkan-ValidationLayers pull request #3620
Opened 2021-12-21 18:56 UTC by AaronHaganAMD

Uses VkRenderingInfoKHR->render_area if dynamic area is active.

Fixes #3614

2021-12-22 15:42 UTC, ncesario-lunarg approved these changes
LGTM, thanks!

Are there other areas where this might be a problem? e.g., https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/a44b81881710a6ba2fdfd29fb24f4aee3921eff9/layers/best_practices_utils.cpp#L2959 or https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/a44b81881710a6ba2fdfd29fb24f4aee3921eff9/layers/synchronization_validation.cpp#L1898?

2021-12-27 18:27 UTC, ncesario-lunarg requested changes
One necessary change for the positive test, but everything else LGTM!

2021-12-27 18:27 UTC, ncesario-lunarg commented on tests/positive/dynamic_rendering.cpp
> +    TEST_DESCRIPTION("Various tests for validating usage of vkCmdClearAttachments with Dynamic Rendering");
Sorry if I missed this before, but positive tests currently need to start with `m_errorMonitor->ExpectSuccess()` and end with `m_errorMonitor->VerifyNotFound()`. This will not be necessary with an upcoming change, but is required for now.

2022-01-03 16:45 UTC, AaronHaganAMD commented on tests/positive/dynamic_rendering.cpp
> +    TEST_DESCRIPTION("Various tests for validating usage of vkCmdClearAttachments with Dynamic Rendering");
Added the ExpectSuccess and VerifyNotFound

2022-01-03 17:06 UTC, ncesario-lunarg approved these changes

2022-01-03 18:33 UTC, ncesario-lunarg commented
Looks like these files now need to get their copyrights updated (happy new year!).

We are also seeing a crash on nvidia hardware in test `VkPositiveLayerTest.CmdClearAttachmentTestsDynamicRendering`. I can try to dig into the root cause later today.

2022-01-12 16:35 UTC, merged