layers: Add VK_KHR_dynamic_rendering VUs and Tests
KhronosGroup/Vulkan-ValidationLayers pull request #3625
Opened 2021-12-23 21:21 UTC by AaronHaganAMD

VU Statements:
VUID-VkGraphicsPipelineCreateInfo-renderPass-06053
VUID-VkGraphicsPipelineCreateInfo-renderPass-06054
VUID-VkRenderingAttachmentInfoKHR-imageView-06145
VUID-VkRenderingAttachmentInfoKHR-imageView-06146
VUID-VkRenderingInfoKHR-imageView-06107
VUID-VkRenderingInfoKHR-imageView-06108
VUID-VkRenderingInfoKHR-imageView-06109

Tests:
VUID-VkGraphicsPipelineCreateInfo-renderPass-06053
VUID-VkGraphicsPipelineCreateInfo-renderPass-06054
VUID-VkRenderingAttachmentInfoKHR-imageView-06129
VUID-VkRenderingAttachmentInfoKHR-imageView-06145
VUID-VkRenderingAttachmentInfoKHR-imageView-06146
VUID-VkRenderingInfoKHR-imageView-06107
VUID-VkRenderingInfoKHR-imageView-06108
VUID-VkRenderingInfoKHR-imageView-06116
VUID-VkRenderingInfoKHR-viewMask-06069
VUID-VkRenderingInfoKHR-multiview-06127

2022-01-03 18:52 UTC, ncesario-lunarg commented
I haven't had a chance to review this in-depth, but looks like:
- More copyright updates necessary for the new year 🎉 
- `VkLayerTest.DynamicRenderingAttachmentInfo` is crashing on nvidia HW

2022-01-11 19:58 UTC, ncesario-lunarg requested changes
Some minor nits, but overall LGTM!

2022-01-11 19:58 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                "Pipeline %" PRIu32
This should start with the name of the API that triggered the error, so I think something like `vkCreateGraphicsPipelines: ...` in this case.

2022-01-11 19:58 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                auto depth_view_state = Get<IMAGE_VIEW_STATE>(pRenderingInfo->pDepthAttachment->imageView);
Looks like `imageView` is optional for `VkRenderingAttachmentInfoKHR`? Should we check to make sure it's not `VK_NULL_HANDLE` (or similarly that `depth_view_state != nullptr`)?

2022-01-11 19:58 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                                 "%" PRIu32 ") equal to 1 when viewMask 0",
"viewMask `is`/`=` 0`?

2022-01-12 22:22 UTC, AaronHaganAMD commented on layers/core_validation.cpp
>      if (rendering_struct) {
if VkPipelineRenderingCreateInfoKHR is used, that would imply renderPass is VK_NULL_HANDLE.

2022-01-12 22:43 UTC, AaronHaganAMD commented on layers/core_validation.cpp
> +             (create_info.pDepthStencilState->sType != VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO))) {
` ((create_info.pDepthStencilState == nullptr) ||
             (create_info.pDepthStencilState->sType != VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO)))`

Was supposed to be the check for `and an invalid pDepthStencilState structure` of the VUID-VkGraphicsPipelineCreateInfo-renderPass-06053 validation statement.  Do you suggest just checking against null to see if its a valid pDepthStencilState structure ?

2022-01-14 16:33 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +             (create_info.pDepthStencilState->sType != VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO))) {
Correct, that _should_ be sufficient, as I'm pretty sure the `sType` check should have already occurred during parameter validation.

2022-01-17 19:13 UTC, ncesario-lunarg commented on tests/vklayertests_dynamic_rendering.cpp
> +    m_commandBuffer->end();
@AaronHaganAMD I think these calls (and similarly for the following test) need to be removed. It is crashing in the nvidia driver, likely due to the fact that vkCmdBeginRenderingKHR never gets dispatched to the driver due to the validation errors.

2022-01-18 19:56 UTC, ncesario-lunarg commented
Crashes fixed, now all tests are passing except 1:
```
[ RUN      ] VkLayerTest.InvalidPipelineRenderingParameters
Unexpected: Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-renderPass-06053 ] Object 0: handle = 0x2061e79b480, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x247dedb2 | vkCreateGraphicsPipelines(): Pipeline 0 has fragment state and a depth format (VK_FORMAT_R8G8B8A8_UNORM) or stencil format (VK_FORMAT_UNDEFINED) and an invalid pDepthStencilState structure The Vulkan spec states: If renderPass is VK_NULL_HANDLE, the pipeline is being created with fragment shader state, and either of VkPipelineRenderingCreateInfoKHR::depthAttachmentFormat or VkPipelineRenderingCreateInfoKHR::stencilAttachmentFormat are not VK_FORMAT_UNDEFINED, pDepthStencilState must be a valid pointer to a valid VkPipelineDepthStencilStateCreateInfo structure (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-renderPass-06053)
C:\lunarg\external-prs\Vulkan-ValidationLayers\tests\vkrenderframework.cpp(206): error: FailedReceived unexpected error(s).
Unexpected: Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-renderPass-06053 ] Object 0: handle = 0x2061e79b480, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x247dedb2 | vkCreateGraphicsPipelines(): Pipeline 0 has fragment state and a depth format (VK_FORMAT_UNDEFINED) or stencil format (VK_FORMAT_R8G8B8A8_UNORM) and an invalid pDepthStencilState structure The Vulkan spec states: If renderPass is VK_NULL_HANDLE, the pipeline is being created with fragment shader state, and either of VkPipelineRenderingCreateInfoKHR::depthAttachmentFormat or VkPipelineRenderingCreateInfoKHR::stencilAttachmentFormat are not VK_FORMAT_UNDEFINED, pDepthStencilState must be a valid pointer to a valid VkPipelineDepthStencilStateCreateInfo structure (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-renderPass-06053)
C:\lunarg\external-prs\Vulkan-ValidationLayers\tests\vkrenderframework.cpp(206): error: Failed
Received unexpected error(s).
Unexpected: Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-renderPass-06053 ] Object 0: handle = 0x2061e79b480, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x247dedb2 | vkCreateGraphicsPipelines(): Pipeline 0 has fragment state and a depth format (VK_FORMAT_D32_SFLOAT) or stencil format (VK_FORMAT_D32_SFLOAT_S8_UINT) and an invalid pDepthStencilState structure The Vulkan spec states: If renderPass is VK_NULL_HANDLE, the pipeline is being created with fragment shader state, and either of VkPipelineRenderingCreateInfoKHR::depthAttachmentFormat or VkPipelineRenderingCreateInfoKHR::stencilAttachmentFormat are not VK_FORMAT_UNDEFINED, pDepthStencilState must be a valid pointer to a valid VkPipelineDepthStencilStateCreateInfo structure (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-renderPass-06053)
C:\lunarg\external-prs\Vulkan-ValidationLayers\tests\vkrenderframework.cpp(206): error: Failed
```

Looks like this is a different dynamic rendering test added by @stu-s?

2022-01-19 02:14 UTC, AaronHaganAMD commented
> Crashes fixed, now all tests are passing except 1:
> 
> ```
> [ RUN      ] VkLayerTest.InvalidPipelineRenderingParameters
> Unexpected: Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-renderPass-06053 ] Object 0: handle = 0x2061e79b480, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x247dedb2 | vkCreateGraphicsPipelines(): Pipeline 0 has fragment state and a depth format (VK_FORMAT_R8G8B8A8_UNORM) or stencil format (VK_FORMAT_UNDEFINED) and an invalid pDepthStencilState structure The Vulkan spec states: If renderPass is VK_NULL_HANDLE, the pipeline is being created with fragment shader state, and either of VkPipelineRenderingCreateInfoKHR::depthAttachmentFormat or VkPipelineRenderingCreateInfoKHR::stencilAttachmentFormat are not VK_FORMAT_UNDEFINED, pDepthStencilState must be a valid pointer to a valid VkPipelineDepthStencilStateCreateInfo structure (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-renderPass-06053)
> C:\lunarg\external-prs\Vulkan-ValidationLayers\tests\vkrenderframework.cpp(206): error: FailedReceived unexpected error(s).
> Unexpected: Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-renderPass-06053 ] Object 0: handle = 0x2061e79b480, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x247dedb2 | vkCreateGraphicsPipelines(): Pipeline 0 has fragment state and a depth format (VK_FORMAT_UNDEFINED) or stencil format (VK_FORMAT_R8G8B8A8_UNORM) and an invalid pDepthStencilState structure The Vulkan spec states: If renderPass is VK_NULL_HANDLE, the pipeline is being created with fragment shader state, and either of VkPipelineRenderingCreateInfoKHR::depthAttachmentFormat or VkPipelineRenderingCreateInfoKHR::stencilAttachmentFormat are not VK_FORMAT_UNDEFINED, pDepthStencilState must be a valid pointer to a valid VkPipelineDepthStencilStateCreateInfo structure (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-renderPass-06053)
> C:\lunarg\external-prs\Vulkan-ValidationLayers\tests\vkrenderframework.cpp(206): error: Failed
> Received unexpected error(s).
> Unexpected: Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-renderPass-06053 ] Object 0: handle = 0x2061e79b480, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x247dedb2 | vkCreateGraphicsPipelines(): Pipeline 0 has fragment state and a depth format (VK_FORMAT_D32_SFLOAT) or stencil format (VK_FORMAT_D32_SFLOAT_S8_UINT) and an invalid pDepthStencilState structure The Vulkan spec states: If renderPass is VK_NULL_HANDLE, the pipeline is being created with fragment shader state, and either of VkPipelineRenderingCreateInfoKHR::depthAttachmentFormat or VkPipelineRenderingCreateInfoKHR::stencilAttachmentFormat are not VK_FORMAT_UNDEFINED, pDepthStencilState must be a valid pointer to a valid VkPipelineDepthStencilStateCreateInfo structure (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-renderPass-06053)
> C:\lunarg\external-prs\Vulkan-ValidationLayers\tests\vkrenderframework.cpp(206): error: Failed
> ```
> 
> Looks like this is a different dynamic rendering test added by @stu-s?

VkLayerTest.InvalidPipelineRenderingParameters should be passing now...

2022-01-31 10:38 UTC, stu-s commented
@AaronHaganAMD / @ncesario-lunarg is this ok to be merged now?

2022-02-02 04:15 UTC, AaronHaganAMD commented
> @AaronHaganAMD / @ncesario-lunarg is this ok to be merged now?

I believe everything has been addressed.

2022-02-04 16:00 UTC, ncesario-lunarg approved these changes

2022-02-04 16:00 UTC, merged