corechecks: Add setting to enable fine-grained locking
KhronosGroup/Vulkan-ValidationLayers pull request #3646
Opened 2022-01-03 22:06 UTC by jeremyg-lunarg

Add a setting to make calls to ValidationObject::ReadLock() and
WriteLock() be no-ops, because locking in other parts of the code
has made these global locks unnecessary.

Currently this only affects Core Validation, but eventually it should
also change the behavior of Best Practices and Synchronization
Validation.

The setting defaults to off for now and there is logging when fine grained
locking is enabled, since this is an experimental feature which
make cause stability problems or incorrect errors to be reported.
Once this stabilizes, the setting will default to on and the log message
will report when it is turned off, because that will be slow.

2022-01-03 22:08 UTC, KarenGhavam-lunarG commented
@christophe-lunarg Ping. We will want these settings exposed by vkconfig.

2022-01-03 22:28 UTC, mark-lunarg commented on layers/core_validation.cpp
> +void CoreChecks::PostCallRecordCreateInstance(const VkInstanceCreateInfo *pCreateInfo, const VkAllocationCallbacks *pAllocator,
Other options might be to call this `corechecks_fine_grained_locking`, then it could still be in `ProcessConfigAndEnvSettings()`.  Or, have this routine make a call back into a new helper function in that file?  It'd be nice keep all the settings stuff in one spot (though there are some in GPU-AV and debugprintf -- hopefully we can clean that up when this stuff gets redone).

2022-01-03 22:34 UTC, mark-lunarg commented on layers/core_validation.cpp
> +        if (fine_grained_locking) {
There's also a status message that gets output at CreateInstance-time (kVUID_Core_CreateInstance_Status) that'll have this setting in it already, and already spits out a perf warning for debug builds.  Again, not a big deal, just centralizing.

2022-01-03 22:36 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +void CoreChecks::PostCallRecordCreateInstance(const VkInstanceCreateInfo *pCreateInfo, const VkAllocationCallbacks *pAllocator,
I was eventually hoping to have this setting apply to everything that uses ValidationStateTracker. That's not going to happen for the first pass, but it should be fairly easy afterwards.  At that point the setting could move into  ProcessConfigAndEnvSettings().  Ideally, fine_grained_locking=true becomes the default for all of the validation flavors and you only turn it off to debug. And then you could just use the .enables and .disables settings to focus in on what you're debugging. So I think we could get by without a separate corechecks_, gpuav, etc. versions of the setting even though the code will be non-ideal for a bit.

2022-01-04 10:08 UTC, christophe-lunarg requested changes
The manifest file is not correct (default is a boolean), here is a fix with some clean up:
```
            "settings": [
                {
                    "key": "fine_grained_locking",
                    "env": "VK_LAYER_FINE_GRAINED_LOCKING",
                    "label": "Fine Grained Locking",
                    "description": "Enable fine grained locking for Core Validation, which should improve performance in multithreaded applications. This is an experimental feature which may cause stability problems or incorrect errors to be reported.",
                    "status": "BETA",
                    "type": "BOOL",
                    "default": false,
                    "platforms": [ "WINDOWS", "LINUX", "MACOS", "ANDROID" ]
                },
```

There is no "experimental" status for settings only "alpha", "beta", "stable" and "deprecated".

I would add this setting first in the list for where it will be exposed in Vulkan Configurator UI

2022-01-04 15:36 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +void CoreChecks::PostCallRecordCreateInstance(const VkInstanceCreateInfo *pCreateInfo, const VkAllocationCallbacks *pAllocator,
after sleeping, I think you're right to move all of this to ProcessConfigAndEnvSettings() now. Working on that.

2022-01-04 18:09 UTC, mark-lunarg approved these changes
This LGTM.  One of the things on my (previous life) cleanup list was to redo the settings stuff -- you can see the work it currently takes to add even a simple setting.  It _should_ be a new setting object that does everything automagically, someday.

2022-01-04 19:41 UTC, christophe-lunarg commented on layers/json/VkLayer_khronos_validation.json.in
> +                {
Looks great!

2022-01-04 19:41 UTC, christophe-lunarg approved these changes

2022-01-06 18:09 UTC, ncesario-lunarg approved these changes
LGTM!

2022-01-19 18:04 UTC, merged