Adding validations for 02746 and 02747 regarding fragment density map extension + tests
KhronosGroup/Vulkan-ValidationLayers pull request #3670
Opened 2022-01-12 01:35 UTC by Theundeadwarrior

Removed obsolete validation 02744 (which seems to come from an older version of the spec)

2022-01-12 01:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3670) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3670) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3670) it.</sub>

2022-01-12 18:44 UTC, ncesario-lunarg requested changes
Some minor requests/comments, but overall this looks really good; thanks for the PR!

2022-01-12 18:44 UTC, ncesario-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    }
You should be able to boil all of this down to `AddRequiredExtensions(VK_EXT_FRAGMENT_DENSITY_MAP_EXTENSION_NAME)` (see [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/creating_tests.md#extensions)). That will ensure all dependent instance extensions get added before `InitFramework` is called and that all dependent device extensions get added during `InitState`. After `InitFramework is called you can call `AreRequestedExtensionsEnabled()` to see if all _device_ extensions are supported.

2022-01-12 18:44 UTC, ncesario-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    PFN_vkGetPhysicalDeviceFeatures2KHR vkGetPhysicalDeviceFeatures2KHR =
These should use `reinterpret_cast` (can use `auto` to cut down on the typing a bit) to align with the [coding guidlines](https://google.github.io/styleguide/cppguide.html#Casting).

2022-01-12 18:44 UTC, ncesario-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    VkFramebuffer fb;
Might be better to use `vk_testing::Framebuffer(*m_device, fb_inf)` to ensure object cleanup, and likewise for similar objects (e.g., `RenderPass`).

2022-01-12 18:44 UTC, ncesario-lunarg commented on tests/vklayertests_imageless_framebuffer.cpp
> -TEST_F(VkLayerTest, RenderPassCreateFragmentDensityMapReferenceToInvalidAttachment) {
Rather than removing, this should probably be updated to only run for `1.0` devices without the multiview extension (see previous comment).

2022-01-12 19:09 UTC, Tony-LunarG commented on layers/core_validation.cpp
> -                                if (view_state->normalized_subresource_range.layerCount != 1) {
validusage.json says
```
"(VK_EXT_fragment_density_map)+!(VK_VERSION_1_1,VK_KHR_multiview)": [
        {
          "vuid": "VUID-VkFramebufferCreateInfo-pAttachments-02744",
          "text": " If <code>renderpass</code> is not <a href=\"#VK_NULL_HANDLE\">VK_NULL_HANDLE</a>, an element of <code>pAttachments</code> that is referenced by <code>fragmentDensityMapAttachment</code> <strong class=\"purple\">must</strong> have a <code>layerCount</code> equal to <code>1</code>"
        }
```
and isn't ',' an OR, so wouldn't it be not api >= 1.1 or not vk_khr_multiview? But I confuse myself all the time with these.
@mikes-lunarg would know for sure.

2022-01-12 19:25 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> -                                if (view_state->normalized_subresource_range.layerCount != 1) {
That's the question...I thought it was _and_. You're probably right; I guarantee I'm more confused than you ;)

2022-01-12 19:27 UTC, Tony-LunarG commented on layers/core_validation.cpp
> -                                if (view_state->normalized_subresource_range.layerCount != 1) {
I just edited my first reply to be !a _and_ !m

2022-01-12 19:28 UTC, Tony-LunarG commented on layers/core_validation.cpp
> -                                if (view_state->normalized_subresource_range.layerCount != 1) {
I think '+' is and

2022-01-12 19:32 UTC, mikes-lunarg commented on layers/core_validation.cpp
> -                                if (view_state->normalized_subresource_range.layerCount != 1) {
The `,` and `+` come directly from the vulkan spec [asciidoctor markup](https://docs.asciidoctor.org/asciidoc/latest/directives/ifdef-ifndef/#checking-multiple-attributes). `+` is AND, `,` is OR

2022-01-12 19:36 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> -                                if (view_state->normalized_subresource_range.layerCount != 1) {
Ah, that's what I was looking for @mikes-lunarg. Thanks!

2022-01-13 02:01 UTC, Theundeadwarrior commented
Thank you very much for the feedback (I'm pretty new to this codebase so it's really appreciated)! I'll try to make the changes and update the PR tomorrow :)

2022-01-17 23:00 UTC, Theundeadwarrior commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    VkFramebuffer fb;
I ended up not using the vk_testing handles:
- There's an assert that the call to create the object returns VK_SUCCESS but the call to CreateFramebuffer will return an error code (I think VK_ERROR_VALIDATION_FAILED_EXT)).
- The vk_testing::RenderPass uses vkCreateRenderPass and not vkCreateRenderPass2 and setting up the subpasses using the first version ended up being more complex imo than just handling the objects cleanup.

2022-01-17 23:03 UTC, Theundeadwarrior commented on tests/vklayertests_imageless_framebuffer.cpp
>      TEST_DESCRIPTION(
I've noticed that the tests in vklayertests_imageless_framebuffer.cpp aren't run on Android (the file is missing from the make file). Is that on purpose? 
I didn't want to enable all of them since it was out of the scope of this change but I was able to test this one locally to make sure it still returns the proper validation error.

2022-01-18 17:42 UTC, ncesario-lunarg commented on tests/vklayertests_imageless_framebuffer.cpp
>      TEST_DESCRIPTION(
That is a really good question! I don't see anything indicating it was left out on purpose (though I may have missed it), and there's a very real chance it was just forgotten. I've created a change to add it in and I am testing it locally.

2022-01-18 17:43 UTC, ncesario-lunarg commented on tests/vklayertests_imageless_framebuffer.cpp
>      TEST_DESCRIPTION(
Looks like the file also needs an updated copyright.

2022-01-18 17:46 UTC, ncesario-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    VkFramebuffer fb;
👍 ah, yep, missed that the VUID is triggered in the `Create*` call.

2022-01-19 19:43 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                                    !(api_version == VK_API_VERSION_1_1 || IsExtEnabled(device_extensions.vk_khr_multiview))) {
Sorry I missed this earlier, but shouldn't this be `api_version >= VK_API_VERSION_1_1` (as opposed to `==`) as @Tony-LunarG suggested?

2022-01-19 19:46 UTC, Theundeadwarrior commented on layers/core_validation.cpp
> +                                    !(api_version == VK_API_VERSION_1_1 || IsExtEnabled(device_extensions.vk_khr_multiview))) {
Yes you're right, good catch!

2022-01-20 22:55 UTC, ncesario-lunarg approved these changes

2022-01-21 13:49 UTC, merged