layers: Add VK_QCOM_fragment_density_map_offset VUs
KhronosGroup/Vulkan-ValidationLayers pull request #3716
Opened 2022-02-01 02:14 UTC by arpiagarwal

2022-02-01 02:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3716) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3716) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-ValidationLayers?pullRequest=3716) it.</sub>

2022-02-01 19:29 UTC, sfricke-samsung commented on layers/core_validation.cpp
> +    const VkRenderPassCreateInfo2 *rpci = rp_state->createInfo.ptr();
nit: move this inside the below if condition in case `rp_state` is null

2022-02-01 19:29 UTC, sfricke-samsung commented on layers/core_validation.cpp
> +            const VkSubpassFragmentDensityMapOffsetEndInfoQCOM *fdmOffsetInfo;
nit: `fdm_offset_info`

2022-02-01 19:33 UTC, sfricke-samsung commented on layers/core_validation.cpp
> +                                     "vkCmdEndRenderPass2KHR(): fragmentDensityOffsetCount is %" PRIu32
instead of using `vkCmdEndRenderPass2KHR` please use the `%s` and `function_name` (it could be `vkCmdEndRenderPass2` and that will set it to the right function name at runtime)

2022-02-01 19:34 UTC, sfricke-samsung commented on layers/core_validation.cpp
> +                            if (fdmOffsetInfo->pFragmentDensityOffsets[k].x % width != 0) {
there is a `SafeModulo` util function to use

2022-02-01 19:35 UTC, sfricke-samsung commented on layers/core_validation.cpp
> +                                    skip |= LogError(
for this (and the ones below) please use the `i` variable to list which index attachment the error is on as that is very useful to developers

2022-02-01 19:36 UTC, ncesario-lunarg reviewed
Thanks for the PR @arpiagarwal! Some minor nits here and there, but overall this looks good!

2022-02-01 19:36 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                                             "vkCmdEndRenderPass2KHR(): Input attachment #%u is not created with"
`u` -> `PRIu32` (and similarly below).

2022-02-01 19:36 UTC, ncesario-lunarg commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +    const bool push_fragment_density_offset_support = CanEnableDeviceExtension(VK_QCOM_FRAGMENT_DENSITY_MAP_OFFSET_EXTENSION_NAME);
I think you also need to add `AddRequiredExtension(VK_QCOM_FRAGMENT_DENSITY_MAP_OFFSET_EXTENSION_NAME);` before `InitFramework` as well.

2022-02-01 19:36 UTC, ncesario-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    fragment_density_map_create_info.sType = VK_STRUCTURE_TYPE_RENDER_PASS_FRAGMENT_DENSITY_MAP_CREATE_INFO_EXT;
`auto fragment_density_map_create_info = LvlInitStruct<VkRenderPassFragmentDensityMapCreateInfoEXT>();` (this will also ensure `pNext` is initialized to null). Likewise for similar initializations.

2022-02-01 19:36 UTC, ncesario-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    VkFramebuffer fb1;
Can `vk_testing::Framebuffer` be used? e.g., `vk_testing::Framebuffer fb1(*m_device, fbci);` This helps streamline cleanup.

2022-02-01 19:36 UTC, ncesario-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    VkRenderPass rp2[2];
This reminds me that we need to setup `vk_testing::RenderPass` to support RenderPass2 :/

2022-02-01 19:36 UTC, sfricke-samsung commented on layers/core_validation.cpp
> +    bool skip = ValidateCmdEndRenderPass(RENDER_PASS_VERSION_2, commandBuffer, CMD_ENDRENDERPASS2, VK_NULL_HANDLE);
why is `pSubpassEndInfo` not passed in here?

2022-02-01 22:47 UTC, arpiagarwal commented on layers/buffer_validation.cpp
> +    if (!IsExtEnabled(device_extensions.vk_qcom_fragment_density_map_offset)) {
Yes. Thanks for catching that. Also, I belive you meant `if (!enabled_features.fragment_density_map_offset_features.fragmentDensityMapOffset)`?

2022-02-01 22:52 UTC, arpiagarwal commented on layers/core_validation.cpp
> +    bool skip = ValidateCmdEndRenderPass(RENDER_PASS_VERSION_2, commandBuffer, CMD_ENDRENDERPASS2, VK_NULL_HANDLE);
I didn't pass it here because this extension is only valid for CmdEndRenderPass2KHR() but on second thought, I think it makes sense to pass it here as well.

2022-02-03 00:09 UTC, ncesario-lunarg commented on layers/buffer_validation.cpp
> +    if (!IsExtEnabled(device_extensions.vk_qcom_fragment_density_map_offset)) {
Right, that's what I meant :)

2022-02-03 00:11 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                                             "vkCmdEndRenderPass2KHR(): Input attachment #%u is not created with"
Correct, so `"... %" PRIu32 " ..."` instead of `"... #%u ..."`. It's tedious, but helps give us some type safety with printf until we update our logging mechanism.

2022-02-04 18:22 UTC, arpiagarwal commented on layers/core_validation.cpp
> +    const VkRenderPassCreateInfo2 *rpci = rp_state->createInfo.ptr();
Done.

2022-02-04 18:22 UTC, arpiagarwal commented on layers/core_validation.cpp
> +            const VkSubpassFragmentDensityMapOffsetEndInfoQCOM *fdmOffsetInfo;
Done.

2022-02-04 18:22 UTC, arpiagarwal commented on layers/core_validation.cpp
> +            fdm_attachment = LvlFindInChain<VkRenderPassFragmentDensityMapCreateInfoEXT>(rpci->pNext);
Done.

2022-02-04 18:22 UTC, arpiagarwal commented on layers/core_validation.cpp
> +                                     "vkCmdEndRenderPass2KHR(): fragmentDensityOffsetCount is %" PRIu32
Done.

2022-02-04 18:22 UTC, arpiagarwal commented on layers/core_validation.cpp
> +                            if (fdmOffsetInfo->pFragmentDensityOffsets[k].x % width != 0) {
Done.

2022-02-04 18:22 UTC, arpiagarwal commented on layers/core_validation.cpp
> +                                    skip |= LogError(
Done.

2022-02-04 18:23 UTC, arpiagarwal commented on layers/buffer_validation.cpp
> +    if (!IsExtEnabled(device_extensions.vk_qcom_fragment_density_map_offset)) {
Done.

2022-02-04 18:23 UTC, arpiagarwal commented on layers/core_validation.cpp
> +            const VkSubpassFragmentDensityMapOffsetEndInfoQCOM *fdmOffsetInfo;
Done.

2022-02-04 18:23 UTC, arpiagarwal commented on layers/core_validation.cpp
> +                                     "vkCmdEndRenderPass2KHR(): fragmentDensityOffsetCount is %" PRIu32
Done.

2022-02-04 18:27 UTC, arpiagarwal commented on layers/core_validation.cpp
> +        if ((pSubpassEndInfo != VK_NULL_HANDLE) && (pSubpassEndInfo->pNext != NULL)) {
Done. Also, it feels counterintuitive but its `if (pSubpassEndInfo && pSubpassEndInfo->pNext)`. I got confused as well :)

2022-02-04 18:27 UTC, arpiagarwal commented on layers/core_validation.cpp
> +            uint32_t height = phys_dev_ext_props.fragment_density_map_offset_props.fragmentDensityOffsetGranularity.height;
Done.

2022-02-04 18:28 UTC, arpiagarwal commented on layers/core_validation.cpp
> +                                             "vkCmdEndRenderPass2KHR(): Input attachment #%u is not created with"
Thanks and done.

2022-02-04 18:28 UTC, arpiagarwal commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +    const bool push_fragment_density_offset_support = CanEnableDeviceExtension(VK_QCOM_FRAGMENT_DENSITY_MAP_OFFSET_EXTENSION_NAME);
Done.

2022-02-04 18:28 UTC, arpiagarwal commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    fragment_density_map_create_info.sType = VK_STRUCTURE_TYPE_RENDER_PASS_FRAGMENT_DENSITY_MAP_CREATE_INFO_EXT;
Done.

2022-02-04 18:28 UTC, arpiagarwal commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    VkFramebuffer fb1;
Done.

2022-02-04 18:28 UTC, arpiagarwal commented on layers/core_validation.cpp
> +    bool skip = ValidateCmdEndRenderPass(RENDER_PASS_VERSION_2, commandBuffer, CMD_ENDRENDERPASS2, VK_NULL_HANDLE);
Done.

2022-02-04 18:31 UTC, arpiagarwal commented
Not sure why a new commit got created even though I amended the last commit. Let me know if you can still just pull the latest commit from the pull request or if I should create a new pull request? Any other suggestions? Thanks!

2022-02-08 03:21 UTC, ncesario-lunarg reviewed
Sorry for the last response @arpiagarwal. It looks like there is a merge commit which is not allowed on the `master` branch. If you can please do a rebase instead of a merge, this change LGTM now.

2022-02-15 23:38 UTC, arpiagarwal commented
Hi @ncesario-lunarg Let me know if you have any questions about this change. All checks have passed but I'd still like to be able to test the two VUIDs that depend on fragmentDensityOffsetGranularity.width and height being > 1. These are implementation-dependent properties and set to 1 in Khronos's build. I have, for now, added a check to only expect the violation for these VUIDs if width/height > 1.  If there is a way to ovverride these, I can do that remove the check. Thanks.

2022-02-16 23:25 UTC, Tony-LunarG commented
@arpiagarwal I think you could override those value using the device_profile_api, but doing it in the pNext of GetPhysicalDeviceProperties2 hasn't been done.

See https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/tests/layers/device_profile_api.cpp

That is probably more work than it's worth, and there's a history of not going to the trouble:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/tests/vklayertests_command.cpp#L1793

Don't let me discourage you if you want to do it, but the PR can be accepted without it.  Please let us know what you want to do.

2022-02-17 22:20 UTC, arpiagarwal commented
> @arpiagarwal I think you could override those value using the device_profile_api, but doing it in the pNext of GetPhysicalDeviceProperties2 hasn't been done.
> 
> See https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/tests/layers/device_profile_api.cpp
> 
> That is probably more work than it's worth, and there's a history of not going to the trouble: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/tests/vklayertests_command.cpp#L1793
> 
> Don't let me discourage you if you want to do it, but the PR can be accepted without it. Please let us know what you want to do.

Thanks for the guidance, Tony. I agree with you. It's not worth the effort at this point.

2022-02-17 22:20 UTC, arpiagarwal commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +TEST_F(VkLayerTest, InvalidRenderPassEndFragmentDensityMapOffsetQCOM) {
Will do.

2022-02-18 17:08 UTC, arpiagarwal commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +
I followed your instructions and saw a handful of errors thrown when creating renderpass and framebuffer. Fixed all errors and updated the commit with changes. Hope its all good now.

2022-02-18 21:21 UTC, arpiagarwal commented
Hi @Tony-LunarG . I am not sure why ci-build is failing. The test is passing on my end and I can't repro the assert even after fetching the tip :(

2022-02-18 22:58 UTC, Tony-LunarG commented
It looks like the CI run is getting past the check for the extension support and failing when trying to create an image.  Every real CI system we have here skips the test due to lack of extension support.  I can take a closer look on Monday.

2022-02-21 21:55 UTC, Tony-LunarG requested changes
Looks good with just a couple of test problems

2022-02-21 21:55 UTC, Tony-LunarG commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    VkImageObj fdm_image(m_device);
The problem here (and in CI) is that the mock ICD reports 1 for imageCreateMaxArrayLayers for all linear formats, and the test asks for 3 array layers. The test should really check the format for allowed array layers, and choosing OPTIMAL tiling will allow the mock icd to run the test.

2022-02-21 21:55 UTC, Tony-LunarG commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    vk::CreateImageView(m_device->device(), &ivci, NULL, &iv[1]);
All of these image views need to be destroyed.  Or use vk_testing::ImageView and they'll be destroyed for you.

2022-02-21 21:55 UTC, Tony-LunarG commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +        m_commandBuffer->reset();
The command pool needs to be created with VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT if you reset command buffers.

2022-02-23 15:43 UTC, arpiagarwal commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +        m_commandBuffer->reset();
Done.

2022-02-23 15:43 UTC, arpiagarwal commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    vk::CreateImageView(m_device->device(), &ivci, NULL, &iv[1]);
Done.

2022-02-23 15:43 UTC, arpiagarwal commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    VkImageObj fdm_image(m_device);
Fixed. Thanks for helping with this.

2022-02-23 19:49 UTC, Tony-LunarG approved these changes
LGTM

2022-02-23 21:28 UTC, Tony-LunarG commented
FYI - A new test requirement around LvlInitStruct developed since you submitted this PR.  I did a little touch up to the test before commiting.  Thanks for the PR

2022-02-23 21:28 UTC, closed without merging

2022-02-23 22:57 UTC, arpiagarwal commented
> FYI - A new test requirement around LvlInitStruct developed since you submitted this PR. I did a little touch up to the test before commiting. Thanks for the PR

Oh ok. Thanks for taking care of it Tony :)