syncval: Handle destruction of bindless descriptor resources
KhronosGroup/Vulkan-ValidationLayers pull request #3719
Opened 2022-02-01 23:18 UTC by jeremyg-lunarg

If a descriptor set is created with VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT, it is valid to destroy buffers or images (or views) used by one of its descriptors, as long as that descriptor is not 'dynamically used' by any shader invocations. Because these descriptor sets are often quite large, the state tracker does not remove state pointers from descriptors when a resource is destroyed. Avoid crashing in this case by checking for destroyed state objects.

Fixes #3717

2022-02-08 21:55 UTC, jzulauf-lunarg reviewed
Not fully consistent (*_state not always checked) ... consider suggested Invalid function.

2022-02-08 21:55 UTC, jzulauf-lunarg commented on layers/synchronization_validation.cpp
> +                        if (!buf_view_state || buf_view_state->Destroyed() || !buf_view_state->buffer_state) continue;
maybe using `Invalid(const BASE_NODE *p) { return !p || p->Destroyed() || (p->Handle().handle == VK_NULL_HANDLE); }` would be DRY'r and more consistent?   static BASE_NODE function?

2022-02-08 22:14 UTC, jeremyg-lunarg commented on layers/synchronization_validation.cpp
> +                        if (!buf_view_state || buf_view_state->Destroyed() || !buf_view_state->buffer_state) continue;
> Not fully consistent (*_state not always checked) ... consider suggested Invalid function.

Is the inconsistency the difference between *views* which have a buffer or image, and plain buffer or image, which do not?

2022-02-08 22:21 UTC, jzulauf-lunarg commented on layers/synchronization_validation.cpp
> +                        if (!buf_view_state || buf_view_state->Destroyed() || !buf_view_state->buffer_state) continue;
right... but if we're checking for buffer_state, maybe`if(Invalid(buf_view_state) || Invalid(buf_view_state->buffer_state)` or some overload or SFINAE for  `*_VIEW_STATE` object meeting a concept that has a BaseState() method?

2022-02-08 22:22 UTC, jeremyg-lunarg commented on layers/synchronization_validation.cpp
> +                        if (!buf_view_state || buf_view_state->Destroyed() || !buf_view_state->buffer_state) continue;
or Descriptor::Invalid()?

2022-02-08 22:24 UTC, jzulauf-lunarg commented on layers/synchronization_validation.cpp
> +                        if (!buf_view_state || buf_view_state->Destroyed() || !buf_view_state->buffer_state) continue;
Dealer's choice.

2022-02-11 17:34 UTC, jzulauf-lunarg requested changes
I think there's a copy paste error.

I've probably made this more complex by asking you to DRY, but it is way cleaner.

2022-02-11 17:34 UTC, jzulauf-lunarg commented on layers/descriptor_sets.cpp
> +        case VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE:
Is this a copy/pasta?  for these types, WriteUpdate is setting the image_view_state_

2022-02-11 18:32 UTC, jeremyg-lunarg commented on layers/descriptor_sets.cpp
> +        case VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE:
yeah. ugh

2022-02-11 21:52 UTC, jzulauf-lunarg approved these changes
Nice and DRY with the descriptor type and state type specific stuff nicely encapsulated.

2022-02-11 21:57 UTC, merged