Issue 1495 proposal
KhronosGroup/Vulkan-ValidationLayers pull request #3722
Opened 2022-02-03 22:41 UTC by aitor-lunarg

Here's the proposal to fix issue #1495. Eases the restrictions for image view creations when an image was created with extended usage bit.

Solves the following scenario (just an example of what we are trying to solve):
Image created with storage and sample bits for usage. Compressed format. Flags contain extended usage, mutable and block texel view compatible bits (nasty combination that it's legal).
Image view with compressed format for sampling.
Image view with uncompressed format for storing.

2022-02-03 23:30 UTC, sfricke-samsung requested changes

2022-02-03 23:30 UTC, sfricke-samsung commented on layers/buffer_validation.cpp
> +            const auto &c = format_usage_features[i];
nit: to be consistent with rest of repo, should not be using single letter variables and instead

2022-02-03 23:30 UTC, sfricke-samsung commented on layers/buffer_validation.cpp
> +    VkImageUsageFlags error_index = 0u;
I am not sure why this is done here at `VkImageView` time, the `VK_IMAGE_CREATE_EXTENDED_USAGE_BIT` is for `VkImage` creation time

A VU like `VUID-VkImageViewCreateInfo-usage-02274` uses `VkImageViewCreateInfo::format` and not related to `VK_IMAGE_CREATE_EXTENDED_USAGE_BIT` at all

2022-02-03 23:34 UTC, sfricke-samsung commented on tests/positive/image_buffer.cpp
> +        VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT | VK_IMAGE_CREATE_EXTENDED_USAGE_BIT | VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT;
`VK_IMAGE_CREATE_EXTENDED_USAGE_BIT` says

> specifies that the image **can** be created with usage flags that are not supported for the format the image is created with but are supported for at least one format a **VkImageView** created from the image **can** have.

This means I would expect a test where the `VkImage` and `VkImageView` have different formats and the there is a `VK_IMAGE_USAGE_*` flag the `VkImage::format` doesn't support but the `VkImageView::format` does

if **both** formats don't support the `VK_IMAGE_USAGE_*` flag then that is invalid behavior and the VVL are doing it's job

2022-02-04 14:34 UTC, aitor-lunarg commented on layers/buffer_validation.cpp
> +    VkImageUsageFlags error_index = 0u;
True, but we also need to have in mind that `usage` gets inherited from the image for the view. That VU states `If usage contains VK_IMAGE_USAGE_SAMPLED_BIT, then the [format features](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#resources-image-view-format-features) of the resultant image view must contain VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT` and should pop at image view creation because that's when we check `vkImageViewCreateInfo`.

The reason to use `VK_IMAGE_CREATE_EXTENDED_USAGE_BIT` there is to know how we want to check view's usage.

2022-02-04 14:43 UTC, aitor-lunarg commented on tests/positive/image_buffer.cpp
> +        VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT | VK_IMAGE_CREATE_EXTENDED_USAGE_BIT | VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT;
I'll update the test to show what I'm trying to solve, but basically is the following:

If I create a compressed image with sample usage, I should be able to create a compressed view for sampling right?

What if now the image is created with those flags, a compressed format and usage for sampling and storing. The compressed format does not support storing, but due to flags that image is legal. Now, what if I want to create a view of that image with same format for sampling? That should be completely legal, or at least that is what I understand. We can also have the posibility to create a view for storing that has a valid format for that usage. So we would have 2 views, one for sampling the compressed format, and other for storing the uncompressed format.

At the moment, the VVL does not allow the creation of the compressed view for sampling.

There's one thing I have not checked, is there any VUID that checks for view usage whenever we actually use it. Meaning that it should be illegal to use a compressed view with sampling usage for storing. This cannot be checked at creation time due to the image flags that were provided at image creation.

2022-02-04 16:47 UTC, sfricke-samsung commented on tests/positive/image_buffer.cpp
> +        VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT | VK_IMAGE_CREATE_EXTENDED_USAGE_BIT | VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT;
So the idea is if you use `VK_IMAGE_CREATE_EXTENDED_USAGE_BIT` with a compress format you can create a `VkImage` that might not have format support

But normally you would have to have the **same** format at `VkImage` and `VkImageView` which means at `VkImageView` time the format **still** doesn't have the format feature support

BUT since we use `VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT` that is what allows using a uncompressed format at `VkImageView` time

----

So for a test, I would expect `VK_FORMAT_BC3_UNORM_BLOCK` at `VkImage` time and using the code logic from #3724 it will be ignored because of `VK_IMAGE_CREATE_EXTENDED_USAGE_BIT`

At `VkImageView` time I would expect an uncompressed format that is "size-compatiable" (which I think would be like `VK_FORMAT_R32G32B32A32_SFLOAT` in this case... we don't have logic to check for "Size-Compatible Image Formats" defined in the spec)

in this case the uncompressed format should just have the format feature support... if it doesn't then it is invalid Vulkan

----

pro tip, you can always use the [Device Profile layer](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/creating_tests.md#device-profile-format-feature) for making a test the same on all devices

2022-02-07 12:58 UTC, aitor-lunarg commented
Closing PR because in the end I think there's nothing to be changed on how we test image view's usage and format features. I'll provide a more extensive explanation once everything is confirmed in the issue.

2022-02-07 12:58 UTC, closed without merging