Track deferred objects after successful creation
KhronosGroup/Vulkan-ValidationLayers pull request #3793
Opened 2022-02-28 23:29 UTC by aitor-lunarg

Fixes the last issue mentioned in #2767. Objects that were created through a deferred operation will be tracked after that operation has completed successfully.

2022-02-28 23:30 UTC, aitor-lunarg commented on layers/state_tracker.cpp
> +            auto copy = pipe_states;
I'm not happy with this, but I'm running into the following error if I don't create a copy when I try to add the states: It complains that the returned value by `std::move` is constant and therefore cannot be added through the `Add` function. Any suggestions or insight are more than welcome.

2022-03-01 00:00 UTC, ziga-lunarg commented on layers/state_tracker.cpp
> +            auto copy = pipe_states;
You are capturing by value, if you capture by reference I think it should work.

`        auto pipe_states = crtpl_state->pipe_state;
        auto register_fn = [this, &pipe_states](VkResult res) {
            if (res == VK_SUCCESS) {
                for (uint32_t index = 0; index < pipe_states.size(); index++) {
                    this->Add(std::move(pipe_states[index]));
                }
            }
        };
`

2022-03-01 00:05 UTC, ziga-lunarg commented on tests/vklayertests_others.cpp
> +    VkRayTracingShaderGroupCreateInfoKHR group_create_infos[2] = {};
Is there a reason for array size 2?

2022-03-03 18:52 UTC, aitor-lunarg commented on layers/state_tracker.cpp
> +            auto copy = pipe_states;
The issue with capturing by reference is the lifetime of the object (which by the time it's used, the object has already stopped existing). That is why I'm capturing by copy (or at least that's what I think I'm doing), but it doesn't make any sense that it does not let me modify the captured copy... So it may not be a copy? I will modify it to not use lambdas on that part of the code, which is not consistent with the other changes, but I'm having issues to accomplish what I want with lambdas. If there are any other ideas, let me know. I'm more than happy to test a few other things

2022-03-03 19:13 UTC, aitor-lunarg commented on tests/vklayertests_others.cpp
> +    VkRayTracingShaderGroupCreateInfoKHR group_create_infos[2] = {};
There's no reason for that. I just didn't have a throughout look to the test since I took it from another PR and modified to test what I wanted. Thank you for the chatch.

2022-03-04 04:39 UTC, ncesario-lunarg reviewed
Some minor nits/questions, but this LGTM pending others' input.

2022-03-04 04:39 UTC, ncesario-lunarg commented on layers/state_tracker.cpp
> +            CleanUp(ValidationStateTracker *vst, const std::vector<std::shared_ptr<PIPELINE_STATE>> &pps)
Should probably remove the `&`, since that sort of implies `pps` is being used as a reference, when it's really being copied.

2022-03-04 04:39 UTC, ncesario-lunarg commented on layers/state_tracker.cpp
> +            iter->second.emplace_back(register_fn);
Might be a bit clearer/direct to just use a lambda here and forego the one-off CleanUp class. Though, with the weird "constness" @jeremyg-lunarg ran into, maybe not. e.g. (including unfortunate `const_cast`s that shouldn't be necessary...but are),
```cpp
            iter->second.emplace_back([this, pipe_states = crtpl_state->pipe_state](VkResult res){
                auto state_data = const_cast<ValidationStateTracker*>(this);
                if (res == VK_SUCCESS) {
                    for (uint32_t index = 0; index < pipe_states.size(); index++) {
                        state_data->Add(std::move(std::const_pointer_cast<PIPELINE_STATE>(pipe_states[index])));
                    }
                }
                const_cast<std::vector<std::shared_ptr<PIPELINE_STATE>>*>(&pipe_states)->clear();
            });
```

2022-03-04 04:39 UTC, ncesario-lunarg commented on tests/vklayertests_others.cpp
> +    PFN_vkCreateRayTracingPipelinesKHR vkCreateRayTracingPipelinesKHR =
While perhaps unpopular, the `PFN_vk...`s are rather redundant here without `auto`.

2022-03-04 04:39 UTC, ncesario-lunarg commented on layers/object_tracker_utils.cpp
> +            std::memcpy(pipelines.data(), pPipelines, sizeof(VkPipeline) * pipelines.size());
In general I'd personally vote for something like `std::copy` over `memcpy` as the former adds a bit of type checking, but in this case, why not just
```cpp
std::vector<VkPipeline> pipelines(pPipelines, pPipelines + createInfoCount);
```
and skip the copy?

2022-03-04 04:39 UTC, ncesario-lunarg commented on layers/object_tracker_utils.cpp
> +                    for (uint32_t index = 0; index < pipelines.size(); index++) {
Range-based for loop?

2022-03-04 15:51 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +            CleanUp(ValidationStateTracker *vst, const std::vector<std::shared_ptr<PIPELINE_STATE>> &pps)
the & saves a useless copy onto the stack for the argument.

2022-03-04 15:59 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +            CleanUp(ValidationStateTracker *vst, const std::vector<std::shared_ptr<PIPELINE_STATE>> &pps)
and this is a vector of shared_ptr's not just one...
if a method doesn't need to copy the shared_ptr, the right way to indicate that is to pass a raw & or * to the underlying object.

2022-03-04 16:11 UTC, ncesario-lunarg commented on layers/state_tracker.cpp
> +            CleanUp(ValidationStateTracker *vst, const std::vector<std::shared_ptr<PIPELINE_STATE>> &pps)
Is there not also a copy on the next line with the constructor `pipe_states(pps)`? Though, I would think without  the `&` that copy would be elided. Either way there should only be one copy, I just thought this was a little confusing.

2022-03-04 17:43 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +            CleanUp(ValidationStateTracker *vst, const std::vector<std::shared_ptr<PIPELINE_STATE>> &pps)
yes, there's 1 mandatory copy in that code.  The only way to void it would be to use && and std::move() and it isn't clear to me if the source can be stolen here.  I don't think copy elision would happen here because the source isn't a temporary, but https://en.cppreference.com/w/cpp/language/copy_elision is very confusing and I might be missing something.

2022-03-04 17:48 UTC, ncesario-lunarg commented on layers/state_tracker.cpp
> +            CleanUp(ValidationStateTracker *vst, const std::vector<std::shared_ptr<PIPELINE_STATE>> &pps)
>  but https://en.cppreference.com/w/cpp/language/copy_elision is very confusing

I quite agree :)

If a lambda is used instead of the CleanUp class (see below comment), then this can all be avoided; albeit at the cost of the weird const issues inside the lambda (I keep meaning to look into that more...not sure why the compiler gets confused with that).

2022-03-10 23:58 UTC, ziga-lunarg commented on tests/vklayertests_others.cpp
> +    if (DeviceValidationVersion() < VK_API_VERSION_1_1) {
You set api version 1_2, but check for 1_1, I assume one is wrong

2022-03-11 00:08 UTC, ziga-lunarg commented on layers/state_tracker.cpp
> +                auto pipeline_states = std::move(pps);
This doesn't look right, pps is captured by value, which means it's const and should not be moved.

2022-03-11 21:28 UTC, aitor-lunarg commented on tests/vklayertests_others.cpp
> +    if (DeviceValidationVersion() < VK_API_VERSION_1_1) {
Fixed the one above since we only need 1.1 for raytracing

2022-03-13 08:28 UTC, martty commented on layers/state_tracker.cpp
> +            iter->second.emplace_back([this, pipeline_states](VkResult res) mutable {
I think you may intended to write `[this, pipeline_states = std::move(crtpl_state->pipe_state)]` which avoids copying, the current code does a move and then a copy.

2022-03-14 18:21 UTC, martty commented on layers/state_tracker.cpp
> +            iter->second.emplace_back([this, pipeline_states](VkResult res) mutable {
I see, in this case writing
`auto& pipeline_states = crtpl_state->pipe_state;`
would avoid the move and result in just a copy (of the value).

2022-03-14 20:24 UTC, locke-lunarg commented
https://github.com/locke-lunarg/Vulkan/tree/test-deferred
I wrote a test about that is forked from SaschaWillems's raytracingbasic sample.

There're two cases in this test.
1.  If I don't add `VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT` (remove `instanceCreateInfo.pNext = &v_feature;`) in my test, It crashes in the same place. See https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3825.

2. If I add `VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT`, it will get a new crash in
```
bool CoreChecks::PreCallValidateGetRayTracingShaderGroupHandlesKHR(VkDevice device, VkPipeline pipeline, uint32_t firstGroup,
                                                                   uint32_t groupCount, size_t dataSize, void *pData) const {
    bool skip = false;
    auto pipeline_state = Get<PIPELINE_STATE>(pipeline);
```
The `pipeline_state` is empty because it didn't get added into map.

2022-03-16 14:37 UTC, jeremyg-lunarg reviewed
Nice work! This is a tricky part of the spec and I still have a few questions inline.

2022-03-16 14:37 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +            iter->second.emplace_back([this, pipeline_states](VkResult res) mutable {
This part of the code could do with a comment explaining what C++ magic is happening here.   I *think* martty's version is slightly simpler, but in terms of performance it is unlikely to matter.  Whichever version ends up here in the end it would be helpful if there's a comment so that they understand what is happening.

2022-03-16 14:37 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +            iter->second.emplace_back([this, pipeline_states](VkResult res) mutable {
Also it might be worth a test for GPUAV and DebugPrintf to cover this code.  Both of those use crtpl_state->pipe_state, see GpuAssisted::PreCallRecordCreateRayTracingPipelinesKHR().  It isn't clear to me if they need to be updated.

2022-03-25 21:34 UTC, aitor-lunarg commented
I had to redo the approach, because I did not have in mind a small detail for the first implementation. We will now differentiate between pending and checked. So a deferred operation will be pending until is completed. Once the operation has completed, we will unlock the resources and delete any extra memory allocated for the operation. We will not add the objects that may or may not have been created to the tracking until the user has checked that the operation has completed successfully.

This change also brings back issue #3645 due to reverting the change that fixed "the issue". Found that the crash is present due to an issue in the CTS test, I will create the corresponding issue for this in the CTS repo so they can have it fixed (it's an easy fix so hopefully it does not take long).

Let me know what you think

2022-03-28 22:52 UTC, locke-lunarg requested changes

2022-03-28 22:52 UTC, locke-lunarg commented on layers/state_tracker.cpp
> +        deferredOperation = layer_data->Unwrap(deferredOperation);
Here should check `if (wrap_handles)`.
I think the other places where `deferredOperation = layer_data->Unwrap(deferredOperation)` should also check `if (wrap_handles)`.

2022-03-29 16:01 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +        deferredOperation = layer_data->Unwrap(deferredOperation);
It could also be worthwhile to just have Unwrap() check wrap_handles and return its argument if not enabled

2022-03-29 17:47 UTC, ncesario-lunarg commented on layers/state_tracker.cpp
> +        deferredOperation = layer_data->Unwrap(deferredOperation);
+1

This is what happens in the chassis code.

2022-03-29 20:25 UTC, aitor-lunarg commented on layers/state_tracker.cpp
> +        deferredOperation = layer_data->Unwrap(deferredOperation);
Thank you for the catch, I think I modified all the ones that were using this. Let me know if I missed anything else.

I do also think that having the check done inside the Unwrap() function would be worthwhile since it removes the possibility of the user forgetting it (I do see myself forgetting about it again in the future, although I will try to be more careful with this).

2022-03-29 21:37 UTC, locke-lunarg requested changes

2022-03-29 21:37 UTC, locke-lunarg commented on layers/generated/layer_chassis_dispatch.cpp
> +        if (iter_fn->first && iter_pipes->first)
Thanks, @aitor-lunarg . Here still has a issue. When `wrap_handles is false`, `operation` won't  be added into `deferred_operation_pipelines`, so `iter_pipes->first` is false. It causes pipeline state can't be added into map.

2022-03-31 17:28 UTC, aitor-lunarg commented on layers/generated/layer_chassis_dispatch.cpp
> +        if (iter_fn->first && iter_pipes->first)
It should be fixed now, thank you for pointing it out.

2022-04-04 20:09 UTC, locke-lunarg commented on layers/generated/layer_chassis_dispatch.cpp
> +        if (iter_fn->first && iter_pipes->first)
Thanks. Good fixed !

2022-04-04 20:10 UTC, locke-lunarg commented
Good fixed. Thanks, @aitor-lunarg

2022-04-04 20:16 UTC, locke-lunarg approved these changes

2022-04-06 17:14 UTC, merged