layers: Track and warn using unset push constants
KhronosGroup/Vulkan-ValidationLayers pull request #3923
Opened 2022-03-28 00:30 UTC by ziga-lunarg

Closes #3518

2022-03-28 13:37 UTC, sfricke-samsung requested changes

2022-03-28 13:37 UTC, sfricke-samsung commented on layers/best_practices_utils.cpp
> +    skip |= ValidatePushConstants(commandBuffer, "vkCmdDraw()");
why not just put this call inside `ValidateCmdDrawType`?

2022-03-28 13:37 UTC, sfricke-samsung commented on layers/best_practices_utils.cpp
> +                               "%s: pipeline uses push constants with %" PRIu32 " bytes, but byte %" PRIu32 " was never written.",
"never written" is a bit misleading

The issue is you might have

```glsl
layout (push_constant) uniform push_constants {
	uint a;
	vec4 b;
	float c[4];
};
```

and not "set" some of the values with `vkCmdPushConstants` so telling the user to use `vkCmdPushConstants` in this message would be helpful

2022-03-28 13:37 UTC, sfricke-samsung commented on layers/best_practices_utils.cpp
> +        if (!cb_state->push_constant_data_set[i]) {
if I have 

```glsl
layout (push_constant) uniform push_constants {
    uint x[64];
}
```

And forgot to set them all, I think this will trow 64 errors

Also if they have

```glsl
layout (push_constant) uniform push_constants {
    uint8_t a;
    uint8_t b;
 }
 ```
 
 and don't set `b` because you are using `size_t` it will not detect it looking at the code

2022-04-03 20:00 UTC, ziga-lunarg commented on layers/best_practices_utils.cpp
> +        if (!cb_state->push_constant_data_set[i]) {
It wont throw more than 1 error because I have a break in the loop. Also I tested the second shader and it does find the error.

2022-04-03 20:03 UTC, ziga-lunarg commented on layers/best_practices_utils.cpp
> +                               "%s: pipeline uses push constants with %" PRIu32 " bytes, but byte %" PRIu32 " was never written.",
I'm not quite understanding what you mean by this

2022-04-03 20:05 UTC, sfricke-samsung commented on layers/best_practices_utils.cpp
> +                               "%s: pipeline uses push constants with %" PRIu32 " bytes, but byte %" PRIu32 " was never written.",
sorry, my comment was trying to say

instead of "never written" use "never set with vkCmdPushConstants"

as I read "never written" as "the shader code never did a write to the memory" (which doesn't make sense since they are read only values"

2022-04-12 06:46 UTC, ncesario-lunarg reviewed
I think everything can move to BP-specific code, this should be GTG.

2022-04-12 06:46 UTC, ncesario-lunarg commented on layers/cmd_buffer_state.h
> +    std::vector<uint8_t> push_constant_data_set;
If this is BP-only data, it should go in the BP-derived state.

2022-04-12 06:46 UTC, ncesario-lunarg commented on layers/state_tracker.cpp
> +        std::memset(cb_state->push_constant_data_set.data() + offset, 1, static_cast<std::size_t>(size));
I think something like `std::fill` would be the "type aware method" for doing this.

2022-04-20 16:03 UTC, ncesario-lunarg approved these changes
Minor comment nit, but this LGTM if @sjfricke's concerns are addressed.

2022-04-20 16:03 UTC, ncesario-lunarg commented on layers/best_practices_utils.cpp
> +            // Spec states that after BeginRenderPass all resources should be rebound
`BeginRenderPass` -> `NextSubpass`?

2022-04-20 20:55 UTC, sjfricke commented on layers/best_practices_utils.cpp
> +        if (!cb_state->push_constant_data_set[i]) {
>  Also I tested the second shader and it does find the error.

So what if I have 

```glsl
layout (push_constant) uniform push_constants {
    uint8_t a; // set 
    uint8_t b; // not set
    uint8_t c; // set
 }
 ```
 
 and don't set `b` here, I am not sure how the code will find that
 
 the error message says `but byte %" PRIu32 " was never set` when you are printing 4 bytes instead

2022-05-04 01:05 UTC, ncesario-lunarg commented on layers/best_practices_utils.cpp
> +        if (!cb_state->push_constant_data_set[i]) {
@sjfricke I think in this case the error would print `but byte 5 was never set`, is that correct @ziga-lunarg?

I wonder if it would make more sense to have the shader module class return something like an iterator over all contained push constant variable data (name if available, type, size), and we could then iterate over the shaders in the bound pipeline at this point, reporting exactly which variables are not set. That would also allow us to iterate over the entire range of data without reporting a bunch of redundant information (as in the `uint x[64]` example Spencer gave above).

2022-05-11 23:43 UTC, ziga-lunarg commented on layers/best_practices_utils.cpp
> +        if (!cb_state->push_constant_data_set[i]) {
Added a test for that and it does get found. It will log that the second byte was not set.

2023-03-30 10:04 UTC, spencer-lunarg commented
rebased - still need to fix, but at least got it using new Github actions for now

2023-04-20 18:07 UTC, closed without merging