Check subresource overlap in blit operations
KhronosGroup/Vulkan-ValidationLayers pull request #3937
Opened 2022-03-31 20:07 UTC by aitor-lunarg

Adds check for subresource overlap in blit operations, same approach as the one used in `vkCmdCopyImage`. There's an issue that we may want to tackle at some point, but since there has not been any complain on how the check is done in `vkCmdCopyImage` we can keep as things are for now.

The issue I found is the following: We currently only check for overlap if the same `VkImage` is used, and we only check against the subresource dimensions. What happens if we have 2 images that bind to the same memory and we use as src (the first one for example) and dst (the second one) with same subresource dimensions such that the memory is overlapped.

Ideally we would need to compute all memory locations and check that none overlap. Let me know what you think and how we should try to tackle the mentioned issue or if we care at all about this.

2022-04-04 20:26 UTC, ziga-lunarg requested changes

2022-04-04 20:26 UTC, ziga-lunarg commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +    ASSERT_NO_FATAL_FAILURE(Init());
Could use TEST_DESCRIPTION()

2022-04-04 20:26 UTC, ziga-lunarg commented on layers/buffer_validation.cpp
> +                        skip |= LogError(cb_node->commandBuffer(), vuid, "%s: pRegion[%u] src overlaps with pRegions[%u] dst.",
`PRIu32 ` instead of `u`

2022-04-04 20:26 UTC, ziga-lunarg commented on layers/buffer_validation.cpp
> +            if (srcImage == dstImage) {
I don't think this is correct, what if 2 `VkImage`s use same device memory?

2022-04-04 20:34 UTC, jeremyg-lunarg commented on layers/buffer_validation.cpp
> +            if (srcImage == dstImage) {
Yes Aitor pointed that out in the PR description. Handling that will be pretty complicated. Some of the corner cases:

- same VkDeviceMemory but using offsets to avoid overlap
- sparse images
- disjoint images where some of the VkDeviceMemories overlap but not others
- probably more

Aren't there similar problems with buffers such as VUID-vkCmdCopyBuffer-pRegions-00117?

It seems to me like a big enough problem to be a separate PR / Issue

2022-04-04 20:38 UTC, ziga-lunarg commented on layers/buffer_validation.cpp
> +            if (srcImage == dstImage) {
Skipped the description, my bad. That does sound like quite a project.

2022-04-06 15:23 UTC, aitor-lunarg commented on layers/buffer_validation.cpp
> +            if (srcImage == dstImage) {
Yes, we do have a similar issue with the VUID you mentioned.

My main concern is that for non-linear images, there's no way to get how they are stored in memory due to being implementation specific, and vulkan cannot provide that information (or at least that's how I understand it). I've used these parts of the specification to reach the conclusion: 
https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkSubresourceLayout.html
https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#glossary-linear-resource

The good thing about the VUID we are trying to cover (VUID-vkCmdCopyBuffer-pRegions-00117 and similars) is how they are described `The union of all destination regions, specified by the elements of pRegions, must not overlap in memory with any texel that may be sampled during the blit operation`. The interesting part is the `may`. Which allow us to be conservative and say: well since we don't know how non-linear textures are stored in memory due to being implementation specific, we assume the whole texture as potentially sampled. Allowing us to use the description to our advantage. (We may also drop the VUID from error to warning if we take the mentioned approach?)

I do also think this should be a different PR, and may need some discussion since it does not seem an easy fix that will make everyone happy.

2022-04-06 15:27 UTC, ziga-lunarg commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +    ci.pQueueFamilyIndices = NULL;
Prefer `nullptr` over `NULL`

2022-04-06 15:28 UTC, ziga-lunarg approved these changes

2022-04-08 17:00 UTC, merged