VK_EXT_graphics_pipeline_library: shader refactor prep
KhronosGroup/Vulkan-ValidationLayers pull request #3958
Opened 2022-04-04 18:00 UTC by ncesario-lunarg

More or less a duplicate of #3800.

2022-04-04 20:26 UTC, jeremyg-lunarg reviewed
Looks like BUILD.gn needs to be updated.  Otherwise looks pretty good.

2022-04-04 20:26 UTC, jeremyg-lunarg commented on layers/shader_module.h
> +    SHADER_MODULE_STATE(VkShaderModuleCreateInfo const &create_info, spv_target_env env, uint32_t unique_shader_id)
Most of the existing code is `const StructName ...` should this one be swapped?

2022-04-04 20:26 UTC, jeremyg-lunarg commented on layers/shader_module.h
> +    SHADER_MODULE_STATE(VkShaderModuleCreateInfo const &create_info, VkShaderModule shaderModule, spv_target_env env,
same as above

2022-04-04 20:26 UTC, jeremyg-lunarg commented on layers/pipeline_state.h
> +    const std::shared_ptr<VertexInputState> vertex_input_state;  // VK_GRAPHICS_PIPELINE_LIBRARY_VERTEX_INPUT_INTERFACE_BIT_EXT
Since you have the GetSubState<> accessors, should these members be protected or private?

2022-04-04 20:26 UTC, jeremyg-lunarg commented on layers/pipeline_state.h
> +    static std::shared_ptr<VertexInputState> CreateVertexInputState(const ValidationStateTracker &state,
these static methods could be file level functions in the .cpp if you want

2022-04-05 16:33 UTC, ncesario-lunarg commented on layers/shader_module.h
> +    SHADER_MODULE_STATE(VkShaderModuleCreateInfo const &create_info, spv_target_env env, uint32_t unique_shader_id)
I'll swap to make it consistent. I actually prefer `const` on the left, so I'm not sure why I did that...or more likely it was a copy paste error on my part.

2022-04-05 16:36 UTC, ncesario-lunarg commented on layers/pipeline_state.h
> +    static std::shared_ptr<VertexInputState> CreateVertexInputState(const ValidationStateTracker &state,
I think at the time I thought this was clearer, but don't think I had a good reason for it. I can move these to only be in the cpp if that's better.

2022-04-05 16:37 UTC, ncesario-lunarg commented on layers/pipeline_state.h
> +    const std::shared_ptr<VertexInputState> vertex_input_state;  // VK_GRAPHICS_PIPELINE_LIBRARY_VERTEX_INPUT_INTERFACE_BIT_EXT
Yep, I think I just forgot to do this.

2022-04-05 16:39 UTC, ncesario-lunarg commented
> Looks like BUILD.gn needs to be updated.

I don't think this PR will build in CI on its own, as it needs a commit in a later PR.

2022-04-05 17:16 UTC, ncesario-lunarg commented on layers/pipeline_state.h
> +    const std::shared_ptr<VertexInputState> vertex_input_state;  // VK_GRAPHICS_PIPELINE_LIBRARY_VERTEX_INPUT_INTERFACE_BIT_EXT
This will actually be a bigger change than I thought. This was my original plan, but got side tracked with C++ templating issues with the getter and decided to shelve it in the interest of time. I just resolved the C++ templating issues, but I'd like to figure out the rest of the errors in CI before making this change (which should be trivial, it will just take some time).

2022-04-05 17:20 UTC, jeremyg-lunarg commented on layers/pipeline_state.h
> +    const std::shared_ptr<VertexInputState> vertex_input_state;  // VK_GRAPHICS_PIPELINE_LIBRARY_VERTEX_INPUT_INTERFACE_BIT_EXT
works for me

2022-04-06 16:43 UTC, jeremyg-lunarg requested changes
the new files need copyright headers. I haven't found any non nitpicky problems with the code but I'll keep looking.

2022-04-06 16:43 UTC, jeremyg-lunarg commented on layers/pipeline_sub_state.h
> +#pragma once
This file needs a copyright header

2022-04-06 16:43 UTC, jeremyg-lunarg commented on layers/pipeline_layout_state.cpp
> +#include "pipeline_layout_state.h"
copyright header

2022-04-06 16:43 UTC, jeremyg-lunarg commented on layers/pipeline_layout_state.h
> +#pragma once
copyright header

2022-04-06 18:47 UTC, jeremyg-lunarg commented on scripts/helper_file_generator.py
> +                    '    bool is_graphics_library = LvlFindInChain<VkGraphicsPipelineLibraryCreateInfoEXT>(in_struct->pNext);\n'
In a later PR you have this, I think to fix VS 2015:
`'    bool is_graphics_library = LvlFindInChain<VkGraphicsPipelineLibraryCreateInfoEXT>(in_struct->pNext) != nullptr;\n'`

2022-04-06 18:49 UTC, ncesario-lunarg commented on scripts/helper_file_generator.py
> +                    '    bool is_graphics_library = LvlFindInChain<VkGraphicsPipelineLibraryCreateInfoEXT>(in_struct->pNext);\n'
Yep, I'll see if I can move that commit here.

2022-04-06 22:20 UTC, jeremyg-lunarg approved these changes
LGTM

2022-04-08 02:53 UTC, closed without merging