Jerdna
KhronosGroup/Vulkan-ValidationLayers pull request #4010
Opened 2022-04-14 11:13 UTC by jerdna

2022-04-14 15:40 UTC, Tony-LunarG requested changes
Just a couple small nits

2022-04-14 15:40 UTC, Tony-LunarG commented on tests/vklayertests_others.cpp
> +    qpci.queryType = VK_QUERY_TYPE_PRIMITIVES_GENERATED_EXT;
Need to enable primitivesGeneratedQuery feature

2022-04-14 15:40 UTC, Tony-LunarG commented on tests/vklayertests_others.cpp
> +    m_commandBuffer->end();
Ending the command buffer with queries active will generate 00061.  Either end the 3 queries with valid CmdEndQuery calls or don't end the command buffer

2022-04-14 20:36 UTC, jerdna commented on layers/core_validation.cpp
> +                if (index >= phys_dev_ext_props.transform_feedback_props.maxTransformFeedbackStreams) {
Isn't vkCmdEndQueryIndexedEXT provided by VK_EXT_transform_feedback? I have been told that there is usually a VUID that checks for an enabled extension when a function gets called. That's the reason I dropped it. Otherwise, I should add a check for all VUIDs in this function?

2022-04-14 21:05 UTC, Tony-LunarG commented on layers/core_validation.cpp
> +                if (index >= phys_dev_ext_props.transform_feedback_props.maxTransformFeedbackStreams) {
Yes, parameter validation will log an error if  vkCmdEndQueryIndexedEXT is called without VK_EXT_transform_feedback.  But if the application doesn't abort on that error and continues anyway, it should not get 02346 without VK_EXT_transform_feedback enabled.  Please just replace the check that was there before.

2022-04-14 22:25 UTC, Tony-LunarG commented on layers/core_validation.cpp
> +                if (index >= phys_dev_ext_props.transform_feedback_props.maxTransformFeedbackStreams) {
And to follow up, since any error after the first cannot be trusted, you are right that it essentially doesn't matter what additional errors are issued, it's just that the validusage.json clearly says that 02346 shouldn't be issued if VK_EXT_transform_feedback isn't enabled.  Which way to go really doesn't matter so I'm inclined to stay with the status quo.

2022-04-15 07:28 UTC, jerdna commented on layers/core_validation.cpp
> +                if (index >= phys_dev_ext_props.transform_feedback_props.maxTransformFeedbackStreams) {
I agree with you that there should be a check. In my opinion, throwing all possible errors at a user is not the best thing one can do. But on the other hand, throwing these errors could be a symptom. For example. I couldn't find a VUID that checks for enabled extension when calling vkCmdEndQueryIndexedEXT. Meaning there would be no error.

The only thing that bothers me is the inconsistency. 02343 02346 02347 06694 06695 all have VK_EXT_transform_feedback as a requirement, but in case of forgotten extension one would still get 02343 02347. Why not all of them? Why some? Which ones?

2022-04-15 14:12 UTC, mark-lunarg commented on layers/core_validation.cpp
> +                if (index >= phys_dev_ext_props.transform_feedback_props.maxTransformFeedbackStreams) {
The 'Valid Usage for Extensions' section in the spec might help.

2022-04-15 20:39 UTC, Tony-LunarG commented on tests/vklayertests_others.cpp
> +
This needs a call to vk::GetPhysicalDeviceFeatures2(gpu(), &features2);  And I have a fix for the place I would guess you copied this from.

2022-04-18 16:12 UTC, ncesario-lunarg approved these changes
LGTM pending @Tony-LunarG's approval.

2022-04-18 16:39 UTC, Tony-LunarG approved these changes
LGTM  @jerdna  thanks for the contribution

2022-04-18 16:39 UTC, merged