layers: Fix checking enabled multiview feature
KhronosGroup/Vulkan-ValidationLayers pull request #4062
Opened 2022-04-27 21:01 UTC by ziga-lunarg

Closes #4061

2022-04-27 21:05 UTC, ncesario-lunarg approved these changes
Minor nit, but LGTM!

2022-04-27 21:05 UTC, ncesario-lunarg commented on tests/positive/render_pass.cpp
> +    m_errorMonitor->ExpectSuccess();
Might as well move this to the top of the test.

2022-04-27 21:11 UTC, Eearslya commented on tests/positive/render_pass.cpp
> +    TEST_DESCRIPTION("Create render pass with view mask, but multiview feature disabled.");
Looks like a possible copy/paste error with this description?

2022-04-27 21:12 UTC, ncesario-lunarg requested changes

2022-04-27 21:12 UTC, ncesario-lunarg commented on tests/positive/render_pass.cpp
> +    TEST_DESCRIPTION("Create render pass with view mask, but multiview feature disabled.");
^ yep, nice catch!

2022-04-27 21:23 UTC, ncesario-lunarg approved these changes

2022-04-28 08:48 UTC, sjfricke approved these changes
This fixes the original issue, but there are more `enabled_features.multiview_features` in the code that I think are also meant to be `core11`

2022-04-29 12:21 UTC, merged