Validate VkBindImagePlaneMemoryInfo is in pNext when binding planes
KhronosGroup/Vulkan-ValidationLayers pull request #4125
Opened 2022-05-17 18:53 UTC by aitor-lunarg

I couldn't find any VUID (I think there's none and one should be added) that states a `VkBindImagePlaneMemoryInfo` is needed in the `pNext` of `VkBindImageMemoryInfo` when binding planes of disjoint images.

Without adding it to `pNext, there's no way to specify to which plane we are binding the memory, and the spec states the following `In order to bind planes of a disjoint image, add a VkBindImagePlaneMemoryInfo structure to the pNext chain of VkBindImageMemoryInfo (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkBindImageMemoryInfo.html).`.

2022-05-17 18:56 UTC, aitor-lunarg commented
#4122 also has the same modification to the test, but I think having it in a different PR with a new VUID to explain should be a better approach than just modifying the test.

2022-05-17 20:00 UTC, Tony-LunarG approved these changes
LGTM but could use a test for UNASSIGNED-VkBindImageMemoryInfo-pNext-missing-VkBindImagePlaneMemoryInfo

2022-05-17 21:38 UTC, ncesario-lunarg requested changes
LGTM with a minor change + Tony's suggestion.

2022-05-17 21:38 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                skip |= LogError(bind_info.image, "UNASSIGNED-VkBindImageMemoryInfo-pNext-missing-VkBindImagePlaneMemoryInfo",
`UNASSIGNED-VkBindImageMemoryInfo-pNext-missing-VkBindImagePlaneMemoryInfo` should be set in `core_validation_error_enums.h` and then the constant used here. Then as Tony suggests, there should be a test for this.

2022-05-18 13:08 UTC, ziga-lunarg approved these changes
LGTM other than what Tony and Nate pointer out

2022-05-18 15:05 UTC, aitor-lunarg commented on layers/core_validation.cpp
> +                skip |= LogError(bind_info.image, "UNASSIGNED-VkBindImageMemoryInfo-pNext-missing-VkBindImagePlaneMemoryInfo",
Thank you for pointing it out! I was not aware of this procedure.

2022-05-18 16:30 UTC, Tony-LunarG approved these changes
LGTM

2022-05-18 20:47 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                skip |= LogError(bind_info.image, "UNASSIGNED-VkBindImageMemoryInfo-pNext-missing-VkBindImagePlaneMemoryInfo",
Yeah, this information should probably be mentioned (or at least reachable) via CONRIBUTING.md. I've added a TODO to add this.

2022-05-18 20:54 UTC, ncesario-lunarg approved these changes
LGTM!

2022-05-18 20:54 UTC, ncesario-lunarg commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +                                             "UNASSIGNED-VkBindImageMemoryInfo-pNext-missing-VkBindImagePlaneMemoryInfo");
We don't seem to be consistent on this throughout the tests, but I would think we'd want to use the constant here (and below). Up to you on what makes more sense.

2022-05-18 21:45 UTC, jeremyg-lunarg approved these changes

2022-05-19 14:46 UTC, merged