Add VK_EXT_image_compression_control VU and tests
KhronosGroup/Vulkan-ValidationLayers pull request #4127
Opened 2022-05-18 10:21 UTC by younggwan-arm

2022-05-18 13:04 UTC, ziga-lunarg requested changes

2022-05-18 15:21 UTC, younggwan-arm commented on layers/core_validation.cpp
> +                                 "vkGetImageSubresourceLayout2EXT: image tiling should is %s", string_VkImageTiling(imageTiling));
Change it to is.

2022-05-18 15:22 UTC, younggwan-arm commented on layers/core_validation.cpp
> +                                 "vkGetImageSubresourceLayout2EXT: image tiling should is %s", string_VkImageTiling(imageTiling));
Change it to is.

2022-05-18 15:26 UTC, younggwan-arm commented on layers/core_validation.cpp
> +                             "vkGetImageSubresourceLayout2EXT: image array layers %d but subresource array layer is %d",
ack

2022-05-18 15:28 UTC, younggwan-arm commented on layers/core_validation.cpp
> +                                 "vkGetImageSubresourceLayout2EXT: format of image is %s which which does not have stencil "
ack

2022-05-18 15:28 UTC, younggwan-arm commented on layers/core_validation.cpp
> +                                 "vkGetImageSubresourceLayout2EXT: format of image is %s which which does not have stencil "
ack

2022-05-18 15:31 UTC, younggwan-arm commented on tests/positive/image_buffer.cpp
> +    SetTargetApiVersion(VK_API_VERSION_1_2);
Add check api version.

2022-05-18 15:35 UTC, younggwan-arm commented on tests/positive/image_buffer.cpp
> +    auto vkGetPhysicalDeviceImageFormatProperties2KHR = (PFN_vkGetPhysicalDeviceImageFormatProperties2KHR)vk::GetInstanceProcAddr(
ack

2022-05-18 15:38 UTC, younggwan-arm commented on tests/vklayertests_wsi.cpp
> +    PFN_vkGetPhysicalDeviceSurfaceFormats2KHR vkGetPhysicalDeviceSurfaceFormats2KHR =
ack

2022-05-18 15:50 UTC, younggwan-arm commented on layers/parameter_validation_utils.cpp
> +                    "VkImageCompressionControlEXT::pFixedRateFlags is nullptr even VkImageCompressionControlEXT::flags is %s",
ack

2022-05-18 21:06 UTC, Tony-LunarG commented on layers/core_validation.cpp
> +                                 "vkGetImageSubresourceLayout2EXT: image tiling is %s", string_VkImageTiling(imageTiling));
The error message says what the layout is, but not why it's wrong.  A better message would be "Image tiling is required to be VK_IMAGE_TILING_LINEAR or VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT but image tiling is %s'.  Similarly in the error messages below

2022-05-19 06:55 UTC, younggwan-arm commented on layers/core_validation.cpp
> +                                 "vkGetImageSubresourceLayout2EXT: image tiling is %s", string_VkImageTiling(imageTiling));
ack

2022-05-19 06:57 UTC, younggwan-arm commented on tests/positive/image_buffer.cpp
> +    m_errorMonitor->VerifyNotFound();
ack

2022-05-19 07:02 UTC, younggwan-arm commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +    const bool multi_plane_extensions = CanEnableDeviceExtension(VK_KHR_SAMPLER_YCBCR_CONVERSION_EXTENSION_NAME);
ack

2022-05-19 07:04 UTC, younggwan-arm commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +            image.init(&image_create_info);
ack

2022-05-20 11:30 UTC, younggwan-arm commented
@ziga-lunarg , @Tony-LunarG can you review this again?

2022-05-20 12:03 UTC, ziga-lunarg approved these changes
LGTM once that small message error is fixed

2022-05-20 12:03 UTC, ziga-lunarg commented on layers/core_validation.cpp
> +                             "image array layers %" PRIu32 "but subresource array layer is %" PRIu32,
I think it should be `image array layers are` and a space between `"but`

2022-05-20 14:14 UTC, younggwan-arm commented on layers/core_validation.cpp
> +                             "image array layers %" PRIu32 "but subresource array layer is %" PRIu32,
ack

2022-05-20 15:07 UTC, Tony-LunarG commented on tests/positive/image_buffer.cpp
> +    m_errorMonitor->ExpectSuccess();
m_errorMonitor->VerifyNotFound()

2022-05-20 15:10 UTC, Tony-LunarG commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +        m_errorMonitor->ExpectSuccess();
The positive test fixtures start with ExpectSuccess to start a test block followed by code that is expected to get no errors, followed by VerifyNotFound to confirm that no errors occured.

2022-05-20 15:11 UTC, Tony-LunarG commented
Just a couple test nits

2022-05-22 11:08 UTC, younggwan-arm commented on tests/positive/image_buffer.cpp
> +    m_errorMonitor->ExpectSuccess();
ack

2022-05-24 09:03 UTC, younggwan-arm commented
@Tony-LunarG , can you review again? Let me know if I have missing things.

2022-05-24 15:00 UTC, Tony-LunarG reviewed
Just two small changes needed

2022-05-24 15:26 UTC, younggwan-arm commented on tests/positive/image_buffer.cpp
> +    m_errorMonitor->ExpectSuccess();
It was confusing... 
ExpectSucess for the first time and after that, VerifyNotFound.
ack

2022-05-24 19:58 UTC, Tony-LunarG commented on tests/vklayertests_wsi.cpp
> +    ASSERT_NO_FATAL_FAILURE(InitState(nullptr, &features2));
Including features2 here is causing our AMD driver to return OUT_OF_HOST_MEMORY at CreateDevice.  I would suggest InitState() since it still doesn't enable the feature when the extension is supported and still allows CreateDevice to succeed when it isn't.

2022-05-25 08:14 UTC, younggwan-arm commented on tests/vklayertests_wsi.cpp
> +    ASSERT_NO_FATAL_FAILURE(InitState(nullptr, &features2));
I would like to change code like follow to clarify intention.
`
    if (image_compression_control.imageCompressionControl == true)
    {
        // disable imageCompressionControl feature;
        image_compression_control.imageCompressionControl = false;
        ASSERT_NO_FATAL_FAILURE(InitState(nullptr, &features2));
    }
    else
    {
        ASSERT_NO_FATAL_FAILURE(InitState());
    }`

2022-05-25 17:56 UTC, Tony-LunarG commented on tests/vklayertests_wsi.cpp
> +    ASSERT_NO_FATAL_FAILURE(InitState(nullptr, &features2));
I like your version better, but:

C:\j\w\32-bit\Release\Vulkan-ValidationLayers\tests\vklayertests_wsi.cpp(2528): warning C4805: '==': unsafe mix of type 'VkBool32' and type 'bool' in operation

Maybe just "if (image_compression_control.imageCompressionControl)"? Or compare to VK_TRUE?

2022-05-26 05:27 UTC, younggwan-arm commented on tests/vklayertests_wsi.cpp
> +    ASSERT_NO_FATAL_FAILURE(InitState(nullptr, &features2));
ack

2022-05-26 15:24 UTC, Tony-LunarG approved these changes
LGTM - thanks

2022-05-26 15:40 UTC, merged