VkSparseImageMemoryBind check offset VUIDs
KhronosGroup/Vulkan-ValidationLayers pull request #4135
Opened 2022-05-19 18:25 UTC by aitor-lunarg

The added VUIDs only apply if the image is sparse and resident. Otherwise, there's no VUIDs that check for correct alignment, although there's mention to what it should be (I will probably add another unassigned VUID for this). I left a comment to point it out.

2022-05-20 00:01 UTC, ncesario-lunarg reviewed
This LGTM, just the one nit, and we might want to add a 01102 check here (if it's not already being done for images).

2022-05-20 11:52 UTC, aitor-lunarg commented on layers/core_validation.cpp
> +            skip |= LogError(image, "VUID-VkSparseMemoryBind-memoryOffset-01101",
There's no need to check for `01102`. `01101` is also not needed, but since it was already there, I just moved it to this new function I added. It should later be replaced by the one mentioned in the comment. What we need to check is `01105` that states:
```
memory and memoryOffset must match the memory requirements of the calling command’s image, as described in section https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#resources-association
```
Now, this VUID covers a a bunch of things like checking `memoryOffset` is correctly aligned, checking `memory` has the right type, and other things that I need to confirm. There's also `VUID-VkSparseMemoryBind-memory-01096` that states the same.

The "similar" check that `01102` adds, should be covered by `01108`, `01110` and `01112`, although these do not state that the extent should not go beyond image limits.

2022-05-20 12:27 UTC, aitor-lunarg commented
I noticed that the VUIDs I'm adding should only be reached if the image is sparse resident, so I removed a few things I was adding.

2022-05-20 18:04 UTC, ncesario-lunarg approved these changes
LGTM once Tony's comment has been addressed.

2022-05-20 21:10 UTC, aitor-lunarg commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +    create_info.arrayLayers = 2;
Thank you for pointing it out!

2022-05-20 21:38 UTC, ncesario-lunarg requested changes

2022-05-20 21:38 UTC, ncesario-lunarg commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +
Actually, one thing I forgot is that this should start with `m_errorMonitor->ExpectSuccess()`, and all code that should succeed should be wrapped in `ExpectSuccess()`/`VerifyNotFound()`. If there is a VU check for what Tony pointed out, this should have caught it.

2022-05-23 12:13 UTC, aitor-lunarg commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +
Thank you for pointing it out. I will keep it in mind for next tests too.

2022-05-23 15:29 UTC, Tony-LunarG approved these changes
LGTM

2022-05-23 21:26 UTC, ncesario-lunarg approved these changes

2022-05-24 14:46 UTC, merged