codegen: Update 'create' criteria
KhronosGroup/Vulkan-ValidationLayers pull request #4138
Opened 2022-05-19 22:17 UTC by ncesario-lunarg

Determine whether or not a command is expected to return a result in a
pointer based on parameter type rather than a hard-coded list of command
names.

Closes #4136.

2022-05-20 00:16 UTC, mikes-lunarg requested changes
Reading the spec a little closer, it looks like this is not the right approach.

`vkGetWinrtDisplayNV` is *not* a create call. It should return the same handle when called multiple times with the same arguments, and the returned handle should be one of the `VkDisplayKHR` handles enumerated by `vkGetPhysicalDeviceDisplayPropertiesKHR`. Check out `ValidationObject::WrapDisplay` and `Validation::MaybeWrapDisplay` to see some of the existing code deal with these handles.

2022-05-20 00:30 UTC, ncesario-lunarg commented
Then perhaps rather than an "allow list," we should have a "block list" of commands that return pointers that should not be wrapped?

2022-05-20 00:54 UTC, mikes-lunarg commented
Sure, we sort of already have that with `no_autogen_list` which is how it looks like we deal with the existing parts of the API which touch `VkDisplayKHR` handles (paired with a custom wrapping/unwrapping implementation). It would be really great if we could generalize the `VkDisplayKHR` wrapping codegen and get rid of the custom implementations since these handles have popped up in a few new extensions now.

2023-04-14 19:20 UTC, juan-lunarg commented
@ncesario-lunarg could you rebase this PR?

It's using the old CI flow which is impacting up the github actions cache.

2023-04-17 17:02 UTC, juan-lunarg commented
Closing due to age / staleness / impacting CI caching

If still valuable please open new PR

2023-04-17 17:02 UTC, closed without merging