Complete missing 02271 check
KhronosGroup/Vulkan-ValidationLayers pull request #4143
Opened 2022-05-20 21:01 UTC by aitor-lunarg

I was checking a few things for subresource layouts and VUID-02271 was halfway implemented. I'm not very familiar with DRM formats, so if there's anything to be changed let me know.

2022-05-22 04:03 UTC, sjfricke commented on layers/buffer_validation.cpp
> +        VkImageDrmFormatModifierPropertiesEXT drm_format_properties = {VK_STRUCTURE_TYPE_IMAGE_DRM_FORMAT_MODIFIER_PROPERTIES_EXT,
`LvlInitStruct<VkImageDrmFormatModifierPropertiesEXT>();`

(to be fair this needed a cleanup anyway https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4147)

2022-05-22 04:09 UTC, sjfricke commented on layers/buffer_validation.cpp
> +                is_valid = true;
So I think this VU should had been broken into a few smaller VUs, but for better error messaging it might be better to keep it as 

```
if ((sub_aspect != VK_IMAGE_ASPECT_MEMORY_PLANE_0_BIT_EXT) && .. )) {
    skip |= LogError(image, "VUID-vkGetImageSubresourceLayout-tiling-02271",
                    "vkGetImageSubresourceLayout(): VkImageSubresource.aspectMask must be "
                    "VK_IMAGE_ASPECT_MEMORY_PLANE_i_BIT_EXT.");
} else {
    // Check if `i` being used is less than drmFormatModifierPlaneCount
}
```

2022-05-22 04:10 UTC, sjfricke commented on layers/buffer_validation.cpp
> +                is_valid = true;
Also the idea is they might us `VK_IMAGE_ASPECT_MEMORY_PLANE_2_BIT_EXT` which is not valid because `drmFormatModifierPlaneCount` for the format is only `1` but this code currently would not validate if reading it correctly

2022-05-23 12:05 UTC, aitor-lunarg commented on layers/buffer_validation.cpp
> +                is_valid = true;
> Also the idea is they might us `VK_IMAGE_ASPECT_MEMORY_PLANE_2_BIT_EXT` which is not valid because `drmFormatModifierPlaneCount` for the format is only `1` but this code currently would not validate if reading it correctly

I'm not sure I understand correctly. You mean there could be a case in which `VK_IMAGE_ASPECT_MEMORY_PLANE_2_BIT_EXT` is used when `drmFormatModifierPlaneCount` is `1` (which is not valid) and the current code does not correctly report the case?

2022-05-23 12:23 UTC, sjfricke commented on layers/buffer_validation.cpp
> +                is_valid = true;
> You mean there could be a case

Yes

> the current code does not correctly report the case?

ok, I see, that `bool is_valid = false;` is `false` by default, so I guess in that case it would never get set to true... nvm, looks good

2022-05-23 18:39 UTC, ncesario-lunarg commented on layers/buffer_validation.cpp
> +            drm_properties.resize(fmt_drm_props.drmFormatModifierCount);
Can collapse this to `std::vector<VkDrmFormatModifierPropertiesEXT> drm_properties(fmt_drm_props.drmFormatModifierCount);` if you like.

2022-05-23 18:51 UTC, ncesario-lunarg requested changes
A couple nits with the test, but this LGTM!

2022-05-23 18:51 UTC, ncesario-lunarg commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +TEST_F(VkLayerTest, GetImageSubresourceLayoutInvalidDrmPlane) {
"Expected successful code" should be wrapped in `ExpectSuccess`/`VerifyNotFound`.

2022-05-23 18:51 UTC, ncesario-lunarg commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +    if (!AddRequiredDeviceExtensions(VK_EXT_IMAGE_DRM_FORMAT_MODIFIER_EXTENSION_NAME)) {
All `AddRequiredDeviceExtensions` should happen before `InitFramework` to ensure any dependent instance extensions get enabled. You can then use the awesome `RequestedExtensionsNotSupported` Spencer recently added to print which extensions are not supported.

2022-05-24 15:53 UTC, Tony-LunarG commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +    if (!AddRequiredDeviceExtensions(VK_EXT_IMAGE_DRM_FORMAT_MODIFIER_EXTENSION_NAME)) {
I don't think you can call AddRequiredDeviceExtensions without a physical device (needed for call to DeviceExtensionSupported) - I think it should be AddRequiredExtensions if you call it before InitFramework.

2022-05-24 16:19 UTC, Tony-LunarG commented on layers/buffer_validation.cpp
> +            DispatchGetPhysicalDeviceFormatProperties2(physical_device, image_entry->createInfo.format, &fmt_props_2);
Probably not worth worrying about, but could you get here with a 1.0 api level, without VK_KHR_get_physical_device_properties2 and be unable to make this call?

2022-05-24 17:56 UTC, aitor-lunarg commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +    if (!AddRequiredDeviceExtensions(VK_EXT_IMAGE_DRM_FORMAT_MODIFIER_EXTENSION_NAME)) {
> All `AddRequiredDeviceExtensions` should happen before `InitFramework` to ensure any dependent instance extensions get enabled. You can then use the awesome `RequestedExtensionsNotSupported` Spencer recently added to print which extensions are not supported.

You are right. I didn't do it that way first because I thought we needed to create the device to check for requested device extensions, which is not the case. We already know which ones are not supported after `InitFramework`. I'll keep this in mind so I don't have to manually check which instance extensions are needed for the device extensions I want to enable.

2022-05-24 17:57 UTC, aitor-lunarg commented on tests/vklayertests_buffer_image_memory_sampler.cpp
> +    if (!AddRequiredDeviceExtensions(VK_EXT_IMAGE_DRM_FORMAT_MODIFIER_EXTENSION_NAME)) {
> I don't think you can call AddRequiredDeviceExtensions without a physical device (needed for call to DeviceExtensionSupported) - I think it should be AddRequiredExtensions if you call it before InitFramework.

You are right

2022-05-25 00:41 UTC, jeremyg-lunarg approved these changes

2022-05-25 19:41 UTC, merged