Validate transform feedback shader stages
KhronosGroup/Vulkan-ValidationLayers pull request #4172
Opened 2022-06-02 15:45 UTC by ziga-lunarg

Closes #4158

2022-06-02 16:11 UTC, ncesario-lunarg reviewed
Some questions, but otherwise LGTM.

2022-06-02 16:11 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +        constexpr std::array<VkShaderStageFlagBits, 4> pre_raster_stages = {
Actually, I'm not sure this is needed at all. See comment below.

2022-06-02 16:11 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +        if (last_pre_raster_stage != last_pre_raster_stage_with_xfb) {
This might work, but this sounds a little different from the VUID. The VUID is specifically asking:
> The last [pre-rasterization shader stage](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/chap10.html#pipeline-graphics-subsets-pre-rasterization) of the bound graphics pipeline must have been declared with the Xfb execution mode

Seems like we just want to check whether the last pre-raster shader stage has xfb or not. Since we `states` is already "in pipeline order" (probably should add a comment regarding as such here either way), using a reverse iterator over `states` and just checking the first pre-raster state that is found seems like the correct thing to do, but I might be missing something here.

2022-06-02 22:41 UTC, ziga-lunarg commented on layers/core_validation.cpp
> +        if (last_pre_raster_stage != last_pre_raster_stage_with_xfb) {
I got confused by the VUIDs, I'm using the correct one here now I think and added the one from the issue.

2022-06-03 18:46 UTC, ncesario-lunarg requested changes

2022-06-03 18:46 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                for (const auto &state : pipeline->stage_state) {
Won't this still find the _first_ stage with Xfb, not the _last_? e.g.,
- VS <- no Xfb
- TE <- Xfb
- Geom <- no Xfb

Should trigger 04128, and I don't think it would given this code.

2022-06-03 18:46 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                        std::find(pre_raster_stages.begin(), pre_raster_stages.end(), stage) != pre_raster_stages.end()) {
The `pre_raster_stages` above still seems incorrect (still missing possible pre-raster stages). Again, not sure if mesh and task shaders can do xfb, but if not, a comment should be added stating this. It might be easier to just check `stage_flag & PreRasterState::ValidShaderStages()` to check whether or not it's a valid pre-raster stage.

2022-06-03 18:46 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                                                 "] State: both stage %s and %s use Xfb execution mode.",
This might be a little awkward if more than 2 stages use xfb; might be nicer to accumulate all stages that use xfb, then report all stages. Probably not a common case to worry about, though.

2023-03-30 16:22 UTC, spencer-lunarg commented
closing as this has got stale and a lot of refactoring in the shader module has occured

This is still being tracked in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4158 and can use this as reference later

2023-03-30 16:22 UTC, closed without merging