Fix crash in layers if pResolveAttachments is null when testing for VUID-06508
KhronosGroup/Vulkan-ValidationLayers pull request #4176
Opened 2022-06-02 22:44 UTC by Theundeadwarrior

pResolveAttachments from VkSubpassDescription can either be null or an array to of size colorAttachmentCount. When checking for VUID-06508, we weren't checking for if pResolveAttachments was null before iterating it.

2022-06-02 23:52 UTC, ncesario-lunarg requested changes
This change LGTM, just a question regarding the test.

2022-06-02 23:52 UTC, ncesario-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +                                             "VUID-VkSubpassFragmentDensityMapOffsetEndInfoQCOM-fragmentDensityOffsetCount-06510");
We usually try keep the number of "desired failures" to a minimum (with one being preferred if possible) per API call. These errors seem unrelated to the layer change made. Given the change that was made to the layers, it looks like a `positive` test (i.e., a test that does _not trigger_ any errors) should be added, whereas this test is intended to _trigger_ errors. Is there any way to do that for this particular case? Unfortunately I don't have an easy way to test this out at the moment as I don't have access to a device that exposes that extension.

2022-06-03 00:02 UTC, Theundeadwarrior commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +                                             "VUID-VkSubpassFragmentDensityMapOffsetEndInfoQCOM-fragmentDensityOffsetCount-06510");
Thanks for the quick feedback! I agree with you that the errors I'm testing are not related to the change. I'll modify the code to make so that I can call m_errorMonitor->VerifyNotFound correctly.

2022-06-30 20:48 UTC, Theundeadwarrior commented
@ncesario-lunarg I think the CI failed for reasons unrelated to this PR. 
```
[macos (Release)](https://github.com/KhronosGroup/Vulkan-ValidationLayers/runs/7014649267?check_suite_focus=true)
An error occurred while provisioning resources (Error Type: Disconnect).
```
I can't retrigger the jobs myself, is it possible for someone else to trigger them?
Thanks :)

2022-07-05 19:50 UTC, ncesario-lunarg requested changes
Sorry for the delayed response. This looks good! Two very minor nits:
1. Since this is a positive test, can you please move the test to `tests/positive/render_pass.cpp`?
2. For a positive test, making calls to `m_errorMonitor` should no longer be necessary (i.e., no need for the `m_errorMonitor->VerifyNotFound()` call)
3. Not necessary, but using `LvlinitStruct` is preferred over initializing `VkStructureType`s to avoid mis-initializing these type of structures. We have some enforcement through format checking with this, but there is some flexibility when initializing arrays if need be.

2022-07-05 19:50 UTC, ncesario-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +        m_errorMonitor->VerifyNotFound();
This is no longer necessary for a positive test.

2022-08-03 20:16 UTC, ncesario-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +        m_errorMonitor->VerifyNotFound();
This function has been made private as it is implicitly called as needed now, so just needs to be removed here.

2022-08-03 22:02 UTC, Theundeadwarrior commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +        m_errorMonitor->VerifyNotFound();
Yeah sorry about that, I auto merged the latest changes from the KhronosGroup repo into my fork and haven't had a chance to make that modification yet! I'll try to finalize it tonight :)

2022-08-04 02:08 UTC, Theundeadwarrior commented
The test actually fails at the moment, I'll make a fix it before you accept the merge!

2022-08-04 19:52 UTC, ncesario-lunarg commented
> The test actually fails at the moment, I'll make a fix it before you accept the merge!

This failure? https://github.com/KhronosGroup/Vulkan-ValidationLayers/runs/7664017490?check_suite_focus=true#step:5:4958

2022-08-04 20:01 UTC, Theundeadwarrior commented
> > The test actually fails at the moment, I'll make a fix it before you accept the merge!
> 
> This failure? https://github.com/KhronosGroup/Vulkan-ValidationLayers/runs/7664017490?check_suite_focus=true#step:5:4958

I was talking about the new test itself that was failing some validations. I'm guessing the failure of the build system is not related to this change?

2022-08-05 15:19 UTC, ncesario-lunarg commented
Our internal CI is passing (i.e., VVL tests running on actual hardware), but it looks like there is one final test failing on the mock ICD: https://github.com/KhronosGroup/Vulkan-ValidationLayers/runs/7664017490?check_suite_focus=true#step:5:4958

2022-11-18 07:41 UTC, spencer-lunarg commented
@Theundeadwarrior Hey, sorry for another delay response, but this change is useful and would like to get it merged in, could you rebase this and hopefully we can get it in finally!

2023-02-06 19:13 UTC, juan-lunarg commented
I've rebased this PR on main

2023-02-06 20:46 UTC, juan-lunarg commented
Testing passed with the caveat that `EndRenderPassSucceedsWhenDepthAndResolveAttachmentsAreNull` was skipped on all platforms because nothing we have supports this extension.

2023-02-07 13:43 UTC, spencer-lunarg commented
>  was skipped on all platforms because nothing we have supports this extension.

I can use the profiles I have to test this and make sure this test is running properly and approve it from there

2023-02-08 06:32 UTC, spencer-lunarg commented on tests/positive/render_pass.cpp
> +    ASSERT_NO_FATAL_FAILURE(InitState(nullptr, nullptr, VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT));
```patch
-    ASSERT_NO_FATAL_FAILURE(InitState(nullptr, nullptr, VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT));
+    auto multiview_features = LvlInitStruct<VkPhysicalDeviceMultiviewFeatures>();
+    auto fragment_density_features = LvlInitStruct<VkPhysicalDeviceFragmentDensityMapOffsetFeaturesQCOM>(&multiview_features);
+    GetPhysicalDeviceFeatures2(fragment_density_features);
+    if (fragment_density_features.fragmentDensityMapOffset == VK_FALSE) {
+        GTEST_SKIP() << "fragmentDensityMapOffset feature is not supported";
+    }
+    if (multiview_features.multiview == VK_FALSE) {
+        GTEST_SKIP() << "multiview feature not supported";
+    }
+
+    ASSERT_NO_FATAL_FAILURE(InitState(nullptr, &fragment_density_features, VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT));
```

need to enable the features

2023-02-08 06:33 UTC, spencer-lunarg commented
So pulled this down and built and tests.

Yes, this layer change fixes the crash

The test is still not a valid positive test as it has many other errors at `vkCmdEndRenderPass2` too

```
VUID-VkSubpassFragmentDensityMapOffsetEndInfoQCOM-fragmentDensityMapOffsets-06503 
VUID-VkFramebufferCreateInfo-renderPass-06502
VUID-VkSubpassFragmentDensityMapOffsetEndInfoQCOM-fragmentDensityMapAttachment-06504
VUID-VkSubpassFragmentDensityMapOffsetEndInfoQCOM-fragmentDensityOffsetCount-06511
```

Looking a bit into it, some are fixed with just adding the feature bits to `InitState`, but I think the logic for the `VK_QCOM_fragment_density_map_offset` is not correct and has bugs in it, so this test is is getting false positive errors because of it

2023-02-09 17:21 UTC, juan-lunarg commented
I removed the testing given the simplicity of the fix, and a lack of CI to test the test.

2023-02-10 03:37 UTC, spencer-lunarg approved these changes

2023-02-10 15:55 UTC, merged