layers: Use CMD_TYPE in synch validation
KhronosGroup/Vulkan-ValidationLayers pull request #4183
Opened 2022-06-05 00:27 UTC by sjfricke

Some of synch val was using `CMD_TYPE` but added it where it wasn't being used

Also unified the naming to `cmd_type` to be consistent with the rest of the code base

2022-06-06 15:32 UTC, jzulauf-lunarg requested changes
I've got a fairly large feature branch in the same code to land early this week, so I'd prefer not seeing this ATM.

I'll see if I can stack this on top trivially.

2022-06-06 21:07 UTC, sjfricke commented
@jzulauf-lunarg I am happy to rebase this when you are done, just let me know when you have your features in, this is in no rush to get in, just something I noticed

2022-06-06 21:08 UTC, jzulauf-lunarg commented
@sjfricke  -- thanks.. just pushed.  Let me know if you have any issues/questions.

2022-06-07 14:28 UTC, jzulauf-lunarg approved these changes
The change is an improvement.  Two optional nits.

2022-06-07 14:28 UTC, jzulauf-lunarg commented on layers/synchronization_validation.cpp
> +        skip |= recorded_cb_context->ValidateFirstUse(&proxy_cb_context, "vkCmdExecuteCommands", cb_index);
Why was this path left unchanged? from const char * to CMD_TYPE

2022-06-07 18:23 UTC, sjfricke commented on layers/synchronization_validation.cpp
> +            const char *func_name = CommandTypeString(cmd_type);
No reason, I would love to unify it to just one name (which one I have zero preference)

2022-06-07 18:24 UTC, sjfricke commented on layers/synchronization_validation.cpp
> +        skip |= recorded_cb_context->ValidateFirstUse(&proxy_cb_context, "vkCmdExecuteCommands", cb_index);
There is a call to ValidateFirstUse with "vkQueueSumbit" which doesn't have a CMD_TYPE

2022-06-07 19:49 UTC, jeremyg-lunarg approved these changes

2022-06-07 19:58 UTC, ncesario-lunarg approved these changes

2022-06-09 15:10 UTC, merged