layers: Update enum check for spec change
KhronosGroup/Vulkan-ValidationLayers pull request #4228
Opened 2022-06-14 20:48 UTC by ncesario-lunarg

Update for validates enum values based on enabled extensions.

This change moves away from the `All*Enums` vectors and instead uses a parameterized function `ValidParamValues<Enum>` to return a list of valid enums based on currently enabled extensions.

2022-08-25 05:32 UTC, oddhack commented
@ncesario-lunarg @mikes-lunarg does your schedule allow progressing this MR? It's the only blocker on the underlying spec change in internal vulkan MR 5206 and as that's globally affecting the "valid enumerant value" definition it would be great to be able to accept that MR.

2022-09-08 08:42 UTC, Rua commented
I notice that `VkStructureType` is not in the list?

2023-01-10 04:57 UTC, spencer-lunarg commented on scripts/parameter_validation_generator.py
> +        self.categoryFilePath = 'categories.cpp.in'
what is the `.cpp.in` suppose to signify from just `.cpp`?

2023-01-10 04:57 UTC, spencer-lunarg commented on tests/vklayertests_dynamic_rendering.cpp
> +    color_attachment.resolveImageLayout = VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL_KHR;
this shouldn't actually matter right?

2023-01-10 04:57 UTC, spencer-lunarg commented on scripts/parameter_validation_generator.py
> +                        enum_entry += f'const std::vector<{groupName}> Core{groupName}Enums = {{ {enum_entry_map["core"]} }};\n'
what was wrong with `constexpr std::array`?

2023-01-11 17:43 UTC, ncesario-lunarg commented on scripts/parameter_validation_generator.py
> +        self.categoryFilePath = 'categories.cpp.in'
Just that it is not a "complete .cpp" file and is meant to be included in another file (which I should make clear in the comments in that file...).

It's probably not the correct thing to do, though, considering some editors don't pick up syntax highlighting for it.

2023-01-11 17:49 UTC, ncesario-lunarg commented on tests/vklayertests_dynamic_rendering.cpp
> +    color_attachment.resolveImageLayout = VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL_KHR;
The test is not using Vulkan 1.3, so one _should_ be using the KHR enum here.

2023-01-11 18:01 UTC, ncesario-lunarg commented on scripts/parameter_validation_generator.py
> +                        enum_entry += f'const std::vector<{groupName}> Core{groupName}Enums = {{ {enum_entry_map["core"]} }};\n'
Uuuh, nothing? :)

2023-01-27 20:41 UTC, juan-lunarg requested changes

2023-01-27 20:41 UTC, juan-lunarg commented on .github/workflows/build_windows.yml
> +          python-version: '3.8'
Add a python version check the scripts in question that require 3.8 to avoid user confusion.

Also make sure to update any docs that reference the python version (like BUILD.md)

2023-01-27 20:41 UTC, juan-lunarg commented on layers/generated/chassis.cpp
> +#include "categories.cpp.in"
What's the rational for adding categories.cpp.in like this?

2023-01-27 20:41 UTC, juan-lunarg commented on layers/generated/categories.cpp.in
> +/* *** THIS FILE IS GENERATED - DO NOT EDIT! ***
By ending with the `.in` file extension intellisense won't work.

2023-01-27 20:41 UTC, juan-lunarg commented on layers/generated/categories.cpp.in
> + * Copyright (c) 2015-2023 Valve Corporation
```suggestion
 * Copyright (c) 2023 The Khronos Group Inc.
 * Copyright (c) 2023 LunarG, Inc.
 * Copyright (C) 2023 Google Inc.
 * Copyright (c) 2023 Valve Corporation
```

2023-01-27 20:41 UTC, juan-lunarg commented on layers/generated/categories.cpp.in
> +const layer_data::unordered_map<const ExtEnabled DeviceExtensions::*, std::vector<VkPipelineCacheHeaderVersion>> ExtendedVkPipelineCacheHeaderVersionEnums = {
Haven't got time to handle this yet but there are issues with globals affecting google, which I haven't full resolved yet (in particular globals for non-trivial classes):
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4884

2023-01-28 00:03 UTC, ncesario-lunarg commented on .github/workflows/build_windows.yml
> +          python-version: '3.8'
I can remove this if it is confusing, or just update the BUILD.md if not.

Currently no scripts _require_ it. In an early version of this PR I was using assignment expressions, but I ended up not using them. I decided to keep this version bump, though, since 3.8 comes "by default" on Ubuntu 20.04 (though we may still "officially" support 18.04), and I'd like the option to use this feature in the future. In the past when we've made a python version bump we have not made "in-code checks;" I'd like to avoid those if possible, as they can be painful to maintain (though I may be misunderstanding the request).

2023-01-28 00:13 UTC, ncesario-lunarg commented on layers/generated/chassis.cpp
> +#include "categories.cpp.in"
Good question! I think I can just make this a separate compilation unit now (it was originally part of paramter_validation.cpp, but I needed to refactor it out of there due to recent changes on master/main).

2023-01-28 00:13 UTC, ncesario-lunarg commented on layers/generated/categories.cpp.in
> +/* *** THIS FILE IS GENERATED - DO NOT EDIT! ***
Yes, you have to update your file association settings. I think I can just get rid of it and make it a separate compilation unit, though.

2023-01-28 00:18 UTC, ncesario-lunarg commented on layers/generated/categories.cpp.in
> +const layer_data::unordered_map<const ExtEnabled DeviceExtensions::*, std::vector<VkPipelineCacheHeaderVersion>> ExtendedVkPipelineCacheHeaderVersionEnums = {
It should be possible to move these definitions inside the corresponding function definitions right below. I'll give that a try.

2023-01-31 18:46 UTC, juan-lunarg commented on layers/generated/categories.cpp
> +/* *** THIS FILE IS GENERATED - DO NOT EDIT! ***
FFTI perhaps a better name for this file is `valid_param_values.cpp`?

2023-01-31 18:46 UTC, juan-lunarg commented on layers/generated/categories.cpp
> +    }
Use C++17 structured bindings

```suggestion
    for (const auto& [extension, enums] : ExtendedVkPipelineCacheHeaderVersionEnums) {
        if (IsExtEnabled(device_extensions.*extension)) {
            unique_exts.insert(enums.cbegin(), enums.cend());
        }
    }
```

2023-01-31 18:46 UTC, juan-lunarg commented on layers/generated/chassis.h
> +#include "parameter_specializations.h"
FFTI but what about

```suggestion
#include "valid_param_values.h"
```

2023-01-31 18:46 UTC, juan-lunarg commented on layers/stateless/stateless_validation.h
> +}  // namespace std
This can be moved to the top of `categories.cpp` without issue. And would reduce be better for locality.

2023-01-31 18:46 UTC, juan-lunarg commented on layers/stateless/stateless_validation.h
> +                                 const char *enumName, uint32_t count, const T *array, bool countRequired,
FFTI but a span could be used

2023-01-31 18:46 UTC, juan-lunarg commented on layers/stateless/stateless_validation.h
> +                                 const ParameterName &arrayName, const char *enumName, uint32_t count, const T *array,
FFTI but a span could be used

2023-01-31 19:53 UTC, ncesario-lunarg commented on layers/generated/categories.cpp
> +/* *** THIS FILE IS GENERATED - DO NOT EDIT! ***
Yep, I agree. I couldn't think of a decent name when doing it originally; I like that much better.

2023-01-31 20:15 UTC, ncesario-lunarg commented on layers/stateless/stateless_validation.h
> +}  // namespace std
I agree that's better for locality, but it's also unnecessary duplication. I `hash_vk_types.h` is where I should have put this.

2023-01-31 20:29 UTC, ncesario-lunarg commented on layers/stateless/stateless_validation.h
> +                                 const char *enumName, uint32_t count, const T *array, bool countRequired,
I agree. I felt this was a little outside the purview of this change, but I'll see if it's quick to make. If not, I'll reserve for a future PR.

2023-01-31 20:41 UTC, ncesario-lunarg commented on layers/stateless/stateless_validation.h
> +                                 const char *enumName, uint32_t count, const T *array, bool countRequired,
Not too bad, but a little more than what I wanted to include in this PR. I will make a follow up PR.

2023-01-31 20:56 UTC, juan-lunarg approved these changes

2023-02-01 16:55 UTC, merged