layers: Relax sync VUs in 1.3.218
KhronosGroup/Vulkan-ValidationLayers pull request #4246
Opened 2022-06-20 17:34 UTC by ncesario-lunarg

Rename 00867 to 06809 and 03087 to 06810. This also removes the ordering
restrictions on these VUs.

Closes #4236.

2022-06-20 18:28 UTC, jeremyg-lunarg requested changes

2022-06-20 18:28 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
>                      "Dependency %u specifies a self-dependency from logically-later stage (%s) to a logically-earlier stage (%s).",
I don't think this error message makes sense any more. The logically later and earlier parts of the VU got removed.

2022-06-20 19:19 UTC, Tony-LunarG approved these changes
LGTM with @jeremyg-lunarg's message touch up.  Maybe something about framebuffer stages and non-framebuffer stages.

2022-06-20 19:27 UTC, ncesario-lunarg commented on layers/core_validation.cpp
>                      "Dependency %u specifies a self-dependency from logically-later stage (%s) to a logically-earlier stage (%s).",
🤦‍♂️ yep, that ain't right.

2022-06-20 21:04 UTC, jeremyg-lunarg approved these changes
LGTM

2022-06-20 23:52 UTC, merged

2023-05-10 19:46 UTC, artem-lunarg commented on layers/core_validation.cpp
>                      "Dependency %u specifies a self-dependency from logically-later stage (%s) to a logically-earlier stage (%s).",
Meanwhile in the nearest future🛸 . The work is in progress on new syncval codegen based on xml input . 

Found some issues with `GetLogicallyLatestGraphicsPipelineStage`. Trying to get only earliest or latest stage can get unexpected results. The problem is that `GetLogicallyLatestGraphicsPipelineStage` tries to create global ordering of all pipeline stages (not only graphics as the name suggests). So, if the mask specifies `fragment+raytracing` stages then `earliest_dst_stage` stage will be evaluated to `fragment` stage, but the goal is at least to show `raytracing` stage in the report because it causes the issue. I'm going to use a solution that logs all non-framebuffer pipeline stages in the destination stage mask.