Check for ClearValue without LoadOpClear
KhronosGroup/Vulkan-ValidationLayers pull request #4247
Opened 2022-06-20 20:30 UTC by paul-lunarg

Add warning message when VkRenderPassBeginInfo.clearValueCount>0
but none of the attachments have VK_ATTACHMENT_LOAD_OP_CLEAR
Close https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3123

2022-06-20 22:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=4247) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=4247) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-ValidationLayers?pullRequest=4247) it.</sub>

2022-06-20 23:51 UTC, ncesario-lunarg requested changes
Great to see this PR up so fast @paul-lunarg! Just some minor nits with regards to the test, but otherwise this looks good!

2022-06-20 23:51 UTC, ncesario-lunarg commented on layers/best_practices_utils.cpp
> +                "This render pass does not have VkRenderPassCreateInfo.pAttachments->loadOp == VK_ATTACHMENT_LOAD_OP_CLEAR "
Would it be worth spelling out a bit more? e.g., "...does not have _any_ VkRenderPassCreateInfo.pAttachments with loadOp == VK_ATTACHMENT_LOAD_OP_CLEAR.".

2022-06-20 23:51 UTC, ncesario-lunarg commented on tests/vklayertests_best_practices.cpp
> +    m_errorMonitor->ExpectSuccess();
Might as well put this right at the top, right after `TEST_DESCRIPTION` to catch _any_ errors (as unlikely as they might be).

2022-06-20 23:51 UTC, ncesario-lunarg commented on tests/vklayertests_best_practices.cpp
> +    vk::CreateImageView(m_device->device(), &iv_info, nullptr, &image_view);
I think you can make use of `VkImageObj::targetView` here. e.g., `const auto image_view = image.targetView(VK_FORMAT_R8G8B8A8_UNORM);`

2022-06-20 23:51 UTC, ncesario-lunarg commented on tests/vklayertests_best_practices.cpp
> +    vk::CreateRenderPass(m_device->device(), &rp_info, nullptr, &rp);
Where possible, best to use the test wrappers, e.g., `vk_testing::RenderPass rp(*m_device, rp_info);` here. You'll just need to use the `handle()` function to access the object's "raw" Vulkan handle. This helps to ensure these objects get cleaned up properly (I don't think this is currently getting destroyed).

2022-06-20 23:51 UTC, ncesario-lunarg commented on tests/vklayertests_best_practices.cpp
> +    vk::CreateFramebuffer(m_device->device(), &fb_info, NULL, &fb);
Same comment as above; you can use `vk_testing::Framebuffer (*m_device, fb_info);` to ensure proper cleanup.

2022-06-20 23:51 UTC, ncesario-lunarg commented on tests/vklayertests_best_practices.cpp
> +    memset(cv.color.float32, 0, 4 * 4);
I'd vote for something with some type awareness such as `std::fill` over `::memset`.

2022-06-21 12:36 UTC, paul-lunarg commented on tests/vklayertests_best_practices.cpp
> +    m_errorMonitor->ExpectSuccess();
Sure, didn't know if I could, I'll add asserts on the Init calls too

2022-06-22 11:22 UTC, paul-lunarg commented on layers/best_practices_error_enums.h
> +// clang-format off
I added clang-format on but didn't change to pragma once, it should probably be in a different PR, and discussed with others

2022-06-22 17:46 UTC, ncesario-lunarg commented on layers/best_practices_utils.cpp
> +                "This render pass does not have VkRenderPassCreateInfo.pAttachments->loadOp == VK_ATTACHMENT_LOAD_OP_CLEAR "
`VkRenderPassCreateInfo.pAttachments->loadOp` is good with me if it's also clear to others; just a bit different from what I've seen before.

2022-06-22 17:49 UTC, ncesario-lunarg commented on tests/vklayertests_best_practices.cpp
> +    // Setup finished
I like this! Sometimes it's difficult to tell what's actually being tested; wonder if we should make this more common practice.

2022-06-22 17:49 UTC, ncesario-lunarg approved these changes
LGTM! Nice work!

2022-06-23 11:39 UTC, merged