Add Spec Constants Shared Memory
KhronosGroup/Vulkan-ValidationLayers pull request #4300
Opened 2022-07-12 15:44 UTC by sjfricke

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3282 (and https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3283)

Just as we did for Spec Constants and `WorkGroupSize` this does the same for `ComputeSharedMemory`. This will apply the spec constant values and then rebuild the `def_index` and use that to get the correct size

2022-07-14 19:28 UTC, ncesario-lunarg requested changes
This LGTM with just some minor nits and a question on whether or not we can avoid adding duplicate code.

2022-07-14 19:28 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +            auto get_def = [&def_index, &specialized_spirv](uint32_t id) -> spirv_inst_iter {
Can `get_def` and `get_type_bits_size` be moved to static functions inside SHADER_MODULE_STATE? Or (more ideally IMHO), how bad would it be perf-wise to just create a SHADER_MODULE_STATE here from `specialized_spirv` and call the necessary methods on that? I'd mainly just like to avoid the duplicate code if possible :)

2022-07-14 19:28 UTC, ncesario-lunarg commented on tests/positive/shaderval.cpp
> +    auto features2 = LvlInitStruct<VkPhysicalDeviceFeatures2>(&explicit_layout_features);
I added [GetPhysicalDevice(Features|Properties)2](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/df5ac8acc8f8d0b3b6e6432cdadf0ba0eae3d15c/tests/layer_validation_tests.h#L266) so you should be able to avoid having to worry about which version of that function to use:
```cpp
auto features2 = GetPhysicalDeviceFeatures2(explicit_layout_features);
```

2022-07-14 19:28 UTC, ncesario-lunarg commented on tests/positive/shaderval.cpp
> +        return;
This should use `GTEST_SKIP()`.

2022-07-15 00:22 UTC, sjfricke commented on layers/shader_validation.cpp
> +            auto get_def = [&def_index, &specialized_spirv](uint32_t id) -> spirv_inst_iter {
So I was debating this as well how to handle the duplication, I tried moving things around, had various compile errors since normally at this point in the code the SHADER_MODULE_STATE is const/read only, the issue is really needing to parse the entire module again, I am not sure what the perf difference would be to just create a new instance of the object.

Happy to leave and make a new PR to move around and test the perf there or to try moving it in. Will let you decide 😉

2022-07-19 21:47 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +            auto get_def = [&def_index, &specialized_spirv](uint32_t id) -> spirv_inst_iter {
I tried this out and ran https://github.com/ncesario-lunarg/Vulkan-ValidationLayers/commit/3b94c2b08f8ec589796474398d039a16107a3906 through our perf regression suite and didn't see any regressions, so I'd vote for just creating a `SHADER_MODULE_STATE` here and using the methods already implemented.

2022-07-20 05:31 UTC, ncesario-lunarg approved these changes
LGTM!

2022-07-20 15:27 UTC, ncesario-lunarg commented
Pretty sure the internal CI failure is spurious. Kicking it one more time to see if we can get it to pass.

2022-07-20 16:18 UTC, merged