tests: Add submit2 GPU-Val test
KhronosGroup/Vulkan-ValidationLayers pull request #4370
Opened 2022-08-02 12:48 UTC by sjfricke

So I originally thought there was a bug with `vkQueueSubmit2` for GPU-Validation, but after writing a test I realize there isn't.

This test still adds a missing test for `VUID-vkCmdDrawIndexedIndirectCount-countBuffer-02717` and cleans up the `GpuDrawIndirectCountDeviceLimit` a bit. Also, I can see using the `submit2` for future tests

2022-08-02 15:18 UTC, Tony-LunarG requested changes
Just a couple things needed.  A suggestion when developing GPU-AV tests is to enable core validation by setting features.disabledValidationFeatureCount = 0 in line 26 of vklayertests_gpu.cpp until your new test is clean from validation errors.

2022-08-02 15:18 UTC, Tony-LunarG commented on tests/vklayertests_gpu.cpp
> -    AddRequiredExtensions(VK_KHR_DRAW_INDIRECT_COUNT_EXTENSION_NAME);
If you use the api level to enable indirect count, you need to enable the feature or get VUID-vkCmdDrawIndexedIndirectCount-None-04445

2022-08-02 15:18 UTC, Tony-LunarG commented on tests/vklayertests_gpu.cpp
> +        GTEST_SKIP() << "At least Vulkan version 1.3 is required";
This needs to enable drawIndirectCount (04445)  and Synchronization2 (03866)

2022-08-02 15:18 UTC, Tony-LunarG commented on tests/vklayertests_gpu.cpp
> +    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "VUID-vkCmdDrawIndexedIndirectCount-countBuffer-02717");
It needs to have an index buffer bound

2022-08-02 15:25 UTC, ncesario-lunarg commented
> A suggestion when developing GPU-AV tests is to enable core validation by setting features.disabledValidationFeatureCount = 0 in line 26 of vklayertests_gpu.cpp until your new test is clean from validation errors.

Should/can this be the default?

2022-08-02 15:51 UTC, jeremyg-lunarg commented
> > A suggestion when developing GPU-AV tests is to enable core validation by setting features.disabledValidationFeatureCount = 0 in line 26 of vklayertests_gpu.cpp until your new test is clean from validation errors.
> 
> Should/can this be the default?

I think so. Once we get a batch of tests clean with that option it does seem like we should keep it on. The only downside is the risk of implicit dependency on having core validation, which hides failures when GPU-AV (or whatever) is run alone. But given recent history that seems like a lower risk  to me.

2022-08-02 15:52 UTC, Tony-LunarG commented
> 

If I remember correctly, and it's been long enough that I probably don't, we want to test GPU-AV without CoreChecks because
- That's the way we tell end users to run it
- There were cases where CoreChecks "fixed" something in GPU-AV and we want to catch those cases
- There's no reason to validate the same test that hasn't changed in years 10 times a day
But I can see the other side too

2022-08-03 04:47 UTC, sjfricke commented on tests/vklayertests_gpu.cpp
> -    AddRequiredExtensions(VK_KHR_DRAW_INDIRECT_COUNT_EXTENSION_NAME);
I agree... but not why is that producing an error for this test... I thought we fixed this, will look into this

2022-08-03 05:46 UTC, sjfricke commented
> Should/can this be the default?

I agree with Tony reasoning as I doubt too many new people will be attempting to write more GPU Validation tests randomly.

Maybe worth adding a flag to `vk_layer_validation_tests` to quickly be able to go between the 2 options... regardless, should for sure add this to [gpu_validation.md#gpu-assisted-validation-testing](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/gpu_validation.md#gpu-assisted-validation-testing) about the preferred way to toggle them off and on... but not all the tests even use `InitGpuAssistedFramework` to start with so there isn't even currently a single location all the tests could toggle them

2022-08-03 15:41 UTC, ncesario-lunarg commented
> If I remember correctly, and it's been long enough that I probably don't, we want to test GPU-AV without CoreChecks because
> 
> * That's the way we tell end users to run it
> * There were cases where CoreChecks "fixed" something in GPU-AV and we want to catch those cases
> * There's no reason to validate the same test that hasn't changed in years 10 times a day
>   But I can see the other side too

Hmm...I wonder if this means we should add "yet another permutation" to CI :/

2022-08-05 21:06 UTC, Tony-LunarG approved these changes
LGTM

2022-08-05 21:06 UTC, merged