Add indirect dispatch to GPU-AV
KhronosGroup/Vulkan-ValidationLayers pull request #4398
Opened 2022-08-10 05:28 UTC by sjfricke

Adds

- VUID-VkDispatchIndirectCommand-x-00417
- VUID-VkDispatchIndirectCommand-y-00418
- VUID-VkDispatchIndirectCommand-z-00419

In process 2 other changes to GPU-AV
- `GpuAssistedCmdDrawIndirectState` to `GpuAssistedCmdIndirectState` (named `cdi_state` to `indirect_state`)
- created a `GpuAssistedAccelerationStructureBuildValidationState::Destroy` to be consistent with how the GPU-VA validation state is destroyed

2022-08-10 16:21 UTC, lunarpapillo commented
I suspect the CI run failed because Windows decided it was a good time to update the machine.  Re-running.

2022-08-10 17:19 UTC, ncesario-lunarg reviewed
This LGTM, but will wait for @Tony-LunarG's input.

Great to know there's another GPUAV expert!

2022-08-10 17:19 UTC, ncesario-lunarg commented on layers/gpu_validation.cpp
> +        pre_dispatch_validation_state.initialized = true;
It's not immediately clear to me why this isn't predicated on `result == VK_SUCCESS` at the end of this function?

2022-08-10 18:02 UTC, sjfricke commented on layers/gpu_validation.cpp
> +        pre_dispatch_validation_state.initialized = true;
Then needs a better comment, but we only need to create the pipeline/shader once for the entire life of the VkDevice because it can just reuse the same VkPipeline each vkCmdDispatchIndirect... Another way to do it would be to create it once upfront at vkCreateDevice time always instead of waiting for the first dispatch indirect call

2022-08-11 13:56 UTC, Tony-LunarG requested changes
Looks good, but the new setting needs to be added to .\layers\json\VkLayer_khronos_validation.json.in and then @christophe-lunarg needs to add the setting to vkconfig

2022-08-11 14:15 UTC, sjfricke commented
added to `VkLayer_khronos_validation.json.in` ... is `layers/vk_layer_settings.txt` still being used then?

2022-08-11 15:02 UTC, christophe-lunarg commented
It looks great and should work with vkconfig and this is merged.

2022-08-11 15:02 UTC, christophe-lunarg approved these changes

2022-08-11 15:47 UTC, Tony-LunarG approved these changes
LGTM

2022-08-11 15:47 UTC, merged