Enable QueueSubmit2 and 2KHR in SyncVal
KhronosGroup/Vulkan-ValidationLayers pull request #4447
Opened 2022-08-19 21:09 UTC by jzulauf-lunarg

Refactored the Sync1 QueueSubmit code to support both paths.  Simplifying some of the template madness by simply converting the Sync 1 parameter to the Sync 2 set, and using plain common functions for the validate and record functions.

Some minor flattening of twoliner functions that were called once.

A simple Submit2 test case with test helper object refinements.

2022-08-19 22:12 UTC, jeremyg-lunarg requested changes

2022-08-19 22:12 UTC, jeremyg-lunarg commented on layers/synchronization_validation.cpp
> +    return ValidateQueueSubmit(queue, submitCount, submit_info.info2s.data(), fence, "VkQueueSubmit");
since submit_info.info2s is only used right here and only once, would it be better to have something like:
```
     std::vector<VkSubmitInfo> info2s = submit_info.GetSubmitInfoVec();
```

2022-08-19 22:12 UTC, jeremyg-lunarg commented on tests/vksyncvaltests.cpp
> +    if (VK_API_VERSION_1_3 != SetTargetApiVersion(VK_API_VERSION_1_3)) {
I think this check isn't correct which is causing the CI crashes. Instead you should have something like:
```
    SetTargetApiVersion(VK_API_VERSION_1_3);
    ASSERT_NO_FATAL_FAILURE(Init());
    if (DeviceValidationVersion() < VK_API_VERSION_1_3) {
        GTEST_SKIP() << "At least Vulkan version 1.3 is required";
    }

```

2022-08-22 17:48 UTC, jzulauf-lunarg commented on layers/synchronization_validation.cpp
> +    return ValidateQueueSubmit(queue, submitCount, submit_info.info2s.data(), fence, "VkQueueSubmit");
Noting that each info needs backing stores for its p<Foo>Infos with invariant pointers ... the object seemed the best way to organize them

2022-08-22 17:48 UTC, jzulauf-lunarg commented on layers/synchronization_validation.h
> +    bool DoQueueSubmtValidate(const SyncValidator &sync_state, QueueSubmitCmdState &cmd_state, const VkSubmitInfo2 &submit_info);
Fixed I literally could *not* spell Submit all day that day.  Sumbit was the most common form...

2022-08-22 18:09 UTC, jeremyg-lunarg commented on layers/synchronization_validation.cpp
> +    return ValidateQueueSubmit(queue, submitCount, submit_info.info2s.data(), fence, "VkQueueSubmit");
Where is that requirement coming from? Maybe a comment explaining it is needed.

2022-08-22 18:10 UTC, jeremyg-lunarg approved these changes
LGTM

2022-08-22 20:31 UTC, jzulauf-lunarg commented on layers/synchronization_validation.cpp
> +    return ValidateQueueSubmit(queue, submitCount, submit_info.info2s.data(), fence, "VkQueueSubmit");
It's the nature of the info2s -- similar to what we do for the safe_Vk<foo> structs.  I'll add a comment though.

2022-08-22 22:23 UTC, jzulauf-lunarg commented on layers/synchronization_validation.cpp
> +    return ValidateQueueSubmit(queue, submitCount, submit_info.info2s.data(), fence, "VkQueueSubmit");
Comment added @jeremyg-lunarg

2022-08-23 01:22 UTC, jeremyg-lunarg approved these changes

2022-08-23 16:40 UTC, merged