Add check for VUID-vkCmdDraw-None-02686
KhronosGroup/Vulkan-ValidationLayers pull request #4519
Opened 2022-09-05 19:14 UTC by paul-lunarg

Add check for not binding all input attachments that are used in a subpass.
Also adds a check for when an input attachment descriptor image view isn't used as input attachment in current subpass/framebuffer. Is this already a VUID ? I can't find it anywhere, and seems like it should be.

Closes #4494

2022-09-06 14:52 UTC, jeremyg-lunarg commented
FYI it looks like there was checking for 02686 but it was removed by https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2244

2022-09-06 15:18 UTC, jeremyg-lunarg approved these changes
LGTM

2022-09-06 15:18 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                result |= LogError(view, vuid.subpass_input,
Please remove this comment from core_validation.h (line 62)

```
    // subpass input doesn't validate anything because those checks were done in ValidateCreateGraphicsPipelines
    const char* subpass_input = kVUIDUndefined;

```

2022-09-08 16:45 UTC, ncesario-lunarg approved these changes
LGTM!

2022-09-09 16:16 UTC, ncesario-lunarg requested changes

2022-09-09 16:16 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                                            LogError(image_view, "UNASSIGNED-input-attachment-descriptor-not-in-subpass",
Be sure to add this in `layers/core_validation_error_enums.h` and use the constant here.

2022-09-12 14:49 UTC, merged