Issue 4579 - Unconsumed attributes warning&errors behavior
KhronosGroup/Vulkan-ValidationLayers pull request #4630
Opened 2022-10-06 13:17 UTC by arno-lunarg

Fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4579

Completely unconsumed attributes are allowed, and should result in a performance warning if the best practices layer is enabled.
Partially unconsumed attributes are allowed if `maintenance4` is enabled, but should still result in a performance warning. They are illegal when `maintenance4` is disabled, and result in an error.

❗The best practices code is a _copy pasta®️_ from CoreChecks, with the function `GetShaderStageId` and the static global array `shader_stage_attribs` being 1:1 copies. Any ideas for a clean refactor?
❗I found `CoreChecks::ValidateInterfaceBetweenStages` rather hard to decipher, I tried to make things clearer in  `BestPractices::ValidateInterfaceBetweenStages`, but the core idea of the function is the same. I only slightly touched the original function. If you like the `BestPractices` version better, I can try to clean the `CoreChecks` equivalent.

2022-10-06 23:01 UTC, juan-lunarg requested changes

2022-10-06 23:31 UTC, ncesario-lunarg requested changes
Overall this change LGTM, and I appreciate the comments :)

Just a lot of duplication that would be nice to consolidate. Some of it I think we can consolidate pretty easily, but other parts may be more effort than it's worth.

2022-10-06 23:31 UTC, ncesario-lunarg commented on layers/best_practices_utils.cpp
> +        }
Looks like `out_attrib` is read-only in this function? Might make sense to put this in a constructor and make `out_attrib` `const`, but definitely not necessary. Same comment for `in_attrib` below (might be able to consolidate that initialization code a bit as well then).

2022-10-06 23:31 UTC, ncesario-lunarg commented on layers/best_practices_utils.cpp
> +    }
Not a ton of code here, but another duplication of CoreChecks code. Again, might be more effort than it's worth to consolidate, but if we can, that would be good.

2022-10-07 09:39 UTC, arno-lunarg commented
I am going to improve on duplication, thank you for the comments @juan-lunarg and @ncesario-lunarg!

2022-10-11 21:32 UTC, jeremyg-lunarg commented on layers/best_practices_utils.cpp
> +}
This is already defined in shader_validation.cpp, it should be made available outside that file somehow.

2022-10-13 14:23 UTC, arno-lunarg commented
Ok so I refactored `CoreChecks::ValidateInterfaceBetweenStages` and `BestPractices::ValidateInterfaceBetweenStages`, As well as the for loop you mentioned [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4630#discussion_r989556763) @ncesario-lunarg.
It took way more time than anticipated, because of how I wanted to refactor the ValidateInterface functions. I wanted to separate the iterators increments part from the checks part, so that those two functions only need to worry about checking a (out, in) attribute pair. Turns out redoing iterators increments was kind of hard. Also, the check parts now heavily rely on the `ShaderAttribute` struct, it makes the code simpler and more explicit.

Some bugs appeared along the way, and some still are very much alive, because I did not know about the `component` attribute layout qualifier. This keyword is a nightmare, especially when combined with the special rules for types like `dvec3` and `dvec4`. ATM, I still do not handle correctly those types, since I do not know how to see if an attribute has such a type?

2022-10-13 15:22 UTC, arno-lunarg commented
Failing test is `VkLayerTest.PipelineInUseDestroyedSignaled` on tcwinnvi2 debug 64, seems unrelated to those changes

2022-10-15 04:54 UTC, spencer-lunarg commented on layers/shader_validation.cpp
> +                skip |= LogError(producer.vk_shader_module(), kVUID_Core_Shader_OutputNotConsumed, "%s", msg.c_str());
I think this is `VUID-RuntimeSpirv-OpTypeVector-06816`/`VUID-RuntimeSpirv-OpTypeVector-06817`

>    Any OpTypeVector output interface variables must: not have a higher
    Component Count than a matching OpTypeVector input
    interface variable
    
so would make this

```cpp
const char* vuid = IsExtEnabled(device_extensions.vk_khr_maintenance4) ? "VUID-RuntimeSpirv-OpTypeVector-06817" : "VUID-RuntimeSpirv-OpTypeVector-06816";
```

(and then apply to the test case below to check for this)

2022-10-17 13:37 UTC, closed without merging

2022-10-17 13:37 UTC, arno-lunarg commented
Closed for now, spotted few more problems related to 64 bits types, I have to make some changes.