layers: SPIR-V Instruction class
KhronosGroup/Vulkan-ValidationLayers pull request #4634
Opened 2022-10-07 07:39 UTC by sjfricke

This adds a new `Instruction` class in favor of the old `spirv_inst_iter` method. 

- **What this provides** 
   - Having a capsulated `Instruction`  class makes the code more readable that only a single instruction is being passed around and not a random iterator.
   - This makes the code more like `SPIRV-Tools`/`spirv-val`
   - Opens up for more refactoring to move Instruction logic (ex. `Instruction::GetStorageClass` or `Instruction::GetBitWidth`) to be added
   - Will allow us to finally solve issues such as https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4355#issuecomment-1266428301
 - **What is not done**
   - I didn't remove `spirv_inst_iter` completely because both GPU-AV and debug-printf make use of the iterator more and wanted to test it separately as it might include more invasive changes to the code. Plan to do that in a follow-up PR

2022-10-10 18:32 UTC, ncesario-lunarg reviewed
This is awesome, I've been wanting something like this for a long time!

Most of these comments are style-related nits and some questions about constness (as there was a pretty large effort to make as much data "const" as possible in the past), but overall I think this is great. Thanks @sjfricke!

2022-10-10 18:32 UTC, ncesario-lunarg commented on layers/shader_module.h
> +    std::vector<Instruction> instructions_;
If I understand correctly this will effectively duplicate all of `words_`. Might make sense to use `span` to store the words associated with each instruction, as you should end up with effectively the same code, save _some_ space, and avoid a few copies, but probably doesn't make too much of a difference one way or the other here.

2022-10-10 18:32 UTC, ncesario-lunarg commented on layers/shader_module.h
> +    StaticData static_data_;
Does this need to be non-const now? If so, the name "static data" probably doesn't fit. The original idea behind this class was to put all "const data" within it and initialize everything within its constructor. It looks like the function `SetStaticData` is only called within constructors, so it seems like this should still be possible?

2022-10-10 18:32 UTC, ncesario-lunarg commented on layers/shader_module.h
> -          static_data_(*this) {
This should probably remain the same if possible or be renamed (see previous comments).

2022-10-10 18:32 UTC, ncesario-lunarg commented on layers/shader_validation.cpp
> +static const Instruction *GetBaseTypeIter(const SHADER_MODULE_STATE &module_state, uint32_t type) {
Should this be renamed to `GetBaseTypeInstruction` now?

2022-10-10 18:32 UTC, ncesario-lunarg commented on layers/shader_module.h
> +    layer_data::unordered_map<uint32_t, const Instruction *> definitions_;
Looks like this is const data, and therefore could go into `static_data_`.

2022-10-10 18:32 UTC, ncesario-lunarg commented on layers/shader_instruction.h
> +        std::vector<uint32_t> words_;
See previous comment. Might make sense to make this a `span`, but also might not.

2022-10-10 18:32 UTC, ncesario-lunarg commented on layers/shader_instruction.h
> +    char const * GetAsString(uint32_t operand) const { return (char const *)&words_.at(operand); }
This seems a little scary if the wrong operand is passed in; are we guaranteed a null value at least at the end of the SPIR-V content?

2022-10-10 18:32 UTC, ncesario-lunarg commented on layers/shader_instruction.h
> +struct atomic_instruction_info {
`CamelCase`.

2022-10-10 22:25 UTC, sjfricke commented on layers/shader_instruction.h
> +    uint32_t word(size_t index) const { return words_[index]; }
So happy to make these function names match normal code convention, just not the diff will be MUCH bigger as I will have to touch everywhere that uses it

2022-10-10 22:28 UTC, sjfricke commented on layers/shader_module.h
> +        const Instruction *insn;  // OpEntryPoint instruction
These should not be null pointers, unless we are given a bogus SPIR-V module that `spirv-val` didn't catch, but realize the shader_module code can have bugs... let me play around with this and get a more robust solution

2022-10-10 22:31 UTC, sjfricke commented on layers/shader_module.h
> +    std::vector<Instruction> instructions_;
So the only 2 places we still actually even need `words_` is

- GPU-AV (because didn't touch it yet)
- When we run `spirv-val`/`spirv-opt` and need to give it the fully buffer

`span` is a c++ 20 feature I think, are we at c++ 20 yet?

2022-10-10 22:33 UTC, sjfricke commented on layers/shader_instruction.h
> +    char const * GetAsString(uint32_t operand) const { return (char const *)&words_.at(operand); }
So I guess all this was doing was moving the "scary" cast to a function... let me just add an bound check by making sure `operand` is not above `length` and that should make sure nothing aweful happens

2022-10-10 22:34 UTC, sjfricke commented on layers/shader_instruction.h
> +struct atomic_instruction_info {
This was moved here, but about to do a full "make the legacy names match what they should" pass now :muscle:

2022-10-11 05:06 UTC, sjfricke commented on layers/shader_instruction.h
> +    char const * GetAsString(uint32_t operand) const { return (char const *)&words_.at(operand); }
Added in a comment above the function, but [SPIR-V spec](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#Literal) says

> A string is interpreted as a nul-terminated stream of characters

2022-10-11 08:20 UTC, sjfricke commented on layers/shader_module.h
> +    std::vector<Instruction> instructions_;
There are 2 issues I am running into

1. Unless we do an initial loop prior, I don't know how big to make `span` at init time
2. In the future we will want `Instruction` to be copied and owned outside the life of the `SHADER_MODULE_STATE` and I think you run into the issue where sometimes the `SHADER_MODULE_STATE` owns the `words` and sometimes the `Instruction` do, not sure if a more clever way to work around that

I don't like having essentially a copy of the `words` neither, but not 100% at this moment which is the best approach

2022-10-11 08:59 UTC, sjfricke commented on layers/shader_module.cpp
> +            *const_cast<StaticData*>(&static_data_) = StaticData(*this);
CI is not happy because this seems to not work with `EntryPoint::insn` being a reference and blowing up trying to copy `std::unordered_multimap<std::string, EntryPoint> entry_points;`... can reproduce on Android, will need to pull out some extra std template foo to figure out what operator needs to be given an override

(tried `Instruction &operator=(const Instruction &other)` but seems to not be any luck)

2022-10-11 20:54 UTC, juan-lunarg commented on layers/shader_instruction.h
> +    ~Instruction() {}
```suggestion
    ~Instruction() = default;
```

2022-10-11 20:54 UTC, juan-lunarg commented on layers/shader_module.cpp
> +        it += 5;  // skip first 5 word of header
Is there a constant that could be used instead?

2022-10-12 00:15 UTC, sjfricke commented on layers/shader_module.cpp
> +        it += 5;  // skip first 5 word of header
There is no value in the SPIR-V headers, but this is just a constant in the spec, `SPIRV-Tools` does the same with a literal

2022-10-12 00:16 UTC, sjfricke commented on layers/shader_instruction.h
> +        return (char const*)&words_.at(operand);
before the assert, but now you are right, will turn to index

2022-10-12 05:01 UTC, ncesario-lunarg commented on layers/shader_instruction.h
> +    uint32_t word(size_t index) const { return words_[index]; }
Yeah, I kind of assumed some of the choices were to avoid widespread changes. I still have hopes of getting clang-tidy integration working at some point, and this would get changed as part of that effort, so up to you on whether or not to do it here :)

2022-10-12 05:09 UTC, ncesario-lunarg commented on layers/shader_module.h
> +    std::vector<Instruction> instructions_;
So my assumption was that (2) was _not_ the case (i.e., an `Instruction` would _not_ outlive the `SHADER_MODULE_STATE` it belongs to). If that assumption is false, then I think the current solution is the only way to go (i.e., copy the words into the instruction).

2022-10-12 05:23 UTC, ncesario-lunarg commented on layers/shader_module.cpp
> +        it += 5;  // skip first 5 word of header
It would be nice if this information was in one of the json files in SPIRV-Headers, but it looks like this is currently missing.

2022-10-12 05:28 UTC, ncesario-lunarg commented on layers/shader_instruction.h
> +        return (char const*)&words_.at(operand);
It might not be terrible if we ended up with an abort in release here rather than somewhere down the road if operand is invalid. Since we have exceptions disabled, I would be surprised if `at` makes much of a perf difference here (via branch prediction and other dark arts...), but my assumption may very well be invalid.

2022-10-12 05:33 UTC, sjfricke commented on layers/shader_module.cpp
> +        it += 5;  // skip first 5 word of header
Raised issue, for now should be good, but :100: agree would be better to have the const in the official headers
https://github.com/KhronosGroup/SPIRV-Headers/issues/297

2022-10-12 05:34 UTC, sjfricke commented on layers/shader_instruction.h
> +        return (char const*)&words_.at(operand);
well with the `assert` I can't imagine where indexing would ever go bad and I would almost change it to be consistent instead of making the next dev waste anytime going "why is this `at` and not `[]`"

2022-10-12 05:38 UTC, ncesario-lunarg commented on layers/shader_module.cpp
> +            *const_cast<StaticData*>(&static_data_) = StaticData(*this);
If going the reference route, I think you'll need to use something like `std::reference_wrapper<Instruction>` in order to get copy semantics. Again, I'm not sure this is the "right" way to go as I haven't personally used `std::reference_wrapper` a whole lot, but that seems like one way to indicate `insn` is non-null with code (though it would be nice if a plain old reference "just worked"...).

2022-10-12 05:44 UTC, sjfricke commented on layers/shader_module.h
> +    std::vector<Instruction> instructions_;
> Instruction would not outlive the SHADER_MODULE_STATE it belongs to)

So the only time have to worry is

```c++
vkCreateShaderModule(&module);
vkCreatePipeline(module, &pipeline);
vkDestroyShaderModule(module);

vkCmdBindPipeline(pipeline);
vkCmdDraw(); // Invalid draw time instruction
```

To my knowledge `SHADER_MODULE_STATE` would be gone at this moment (if not, well then yes, `2` is not an issue) and we still want to be able to save the Instruction

I am still looking into a way to `Instruction` both be able to easily hold a its own `vector<uint32_t>` or `span<uint32_t>`

2022-10-12 05:47 UTC, sjfricke commented on layers/shader_module.h
> +    std::vector<Instruction> instructions_;
One way would be using the `operator=` and it `Instruction` is constructed it is a `span` but if copied, we do a deep copy and grab the memory over

2022-10-12 06:46 UTC, ncesario-lunarg commented on layers/shader_module.h
> +    std::vector<Instruction> instructions_;
> So the only time have to worry is....

Yep, [this](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap9.html#vkDestroyShaderModule) bit in the spec makes it pretty clear:
> A shader module can be destroyed while pipelines created using its shaders are still in use.

So yeah, definitely need to copy. That said...I'm pretty sure this would crash in the validation layers currently 🤔

2022-10-12 07:10 UTC, ncesario-lunarg commented on layers/shader_module.h
> +    std::vector<Instruction> instructions_;
> I am still looking into a way to Instruction both be able to easily hold a its own vector<uint32_t> or span<uint32_t>

Looks like we need to copy, so not sure that is necessary. `layer_data::small_vector` might be good to use here, too, since I'm assuming most instructions will be about the same size and we could then avoid some heap allocations.

I suppose something like the following _could_ (??) work, but it would have to be with unions since we don't have access to `std::variant`:
```cpp
template<int N = 0>
struct Instruction {
        ...
        std::span<const uint32_t> Words() const {
                const auto& s = std::get<N>(store_);
                return std::span<const uint32_t>(s.begin(), s.end());
        }
        ...
        std::variant<std::vector<uint32_t>, std::span<uint32_t>> store_;
};

using InstructionDeepCopy = Instruction<0>;
using InstructionShallowCopy = Instruction<1>;
```

2022-10-12 15:28 UTC, juan-lunarg requested changes
minor nitpick

2022-10-12 15:28 UTC, juan-lunarg commented on layers/vk_layer_data.h
> +    }
Couldn't we leverage the existing `==` operator?

```suggestion
    bool operator!=(const small_vector &rhs) const { return !(*this == rhs); }
```

2022-10-12 15:50 UTC, juan-lunarg approved these changes
LGTM but @ncesario-lunarg is much more familiar with the code at hand

2022-10-12 18:16 UTC, ncesario-lunarg commented on layers/shader_instruction.h
> +    //   287 of 423 had 4 or less operands
Good to know!

2022-10-13 00:32 UTC, ncesario-lunarg commented
I think the following should get things compiling:
```diff
diff --git a/layers/shader_instruction.h b/layers/shader_instruction.h
index 92ee89a46..54be749ac 100644
--- a/layers/shader_instruction.h
+++ b/layers/shader_instruction.h
@@ -45,7 +45,7 @@ class Instruction {
     ~Instruction() = default;

     // The word used to define the Instruction
-    uint32_t Word(size_t index) const { return words_[index]; }
+    uint32_t Word(uint32_t index) const { return words_[index]; }

     uint32_t Length() const { return words_[0] >> 16; }

diff --git a/layers/shader_module.cpp b/layers/shader_module.cpp
index d085acbf8..072c47a16 100644
--- a/layers/shader_module.cpp
+++ b/layers/shader_module.cpp
@@ -429,7 +429,7 @@ SHADER_MODULE_STATE::StaticData::StaticData(const SHADER_MODULE_STATE& module_st

                 auto range = entry_points.equal_range(entrypoint_name);
                 for (auto it = range.first; it != range.second; ++it) {
-                    if (it->second.insn == insn) {
+                    if (insn == it->second.insn.get()) {
                         entry_point = &(it->second);
                         break;
                     }
@@ -595,7 +595,7 @@ layer_data::optional<Instruction> SHADER_MODULE_STATE::FindEntrypoint(char const
     auto range = static_data_.entry_points.equal_range(name);
     for (auto it = range.first; it != range.second; ++it) {
         if (it->second.stage == stageBits) {
-            assert(it->second.insn.Opcode() == spv::OpEntryPoint);
+            assert(it->second.insn.get().Opcode() == spv::OpEntryPoint);
             result.emplace(it->second.insn);
             break;
         }
diff --git a/layers/shader_module.h b/layers/shader_module.h
index f52f97002..f0d03c21b 100644
--- a/layers/shader_module.h
+++ b/layers/shader_module.h
@@ -205,7 +205,7 @@ struct shader_struct_member {

 struct SHADER_MODULE_STATE : public BASE_NODE {
     struct EntryPoint {
-        const Instruction &insn;  // OpEntryPoint instruction
+        std::reference_wrapper<const Instruction> insn;  // OpEntryPoint instruction
         VkShaderStageFlagBits stage;
         std::vector<function_set> function_set_list;
         shader_struct_member push_constant_used_in_shader;
```

2022-10-18 04:43 UTC, ncesario-lunarg approved these changes

2022-10-18 21:47 UTC, spencer-lunarg commented
CI Tests are unrelated and being discussed inside to prevent the false positive

2022-10-18 21:47 UTC, merged