docs: Improve BUILD.md
KhronosGroup/Vulkan-ValidationLayers pull request #4662
Opened 2022-10-13 20:43 UTC by juan-lunarg

- Address concerns from PR#4659
- Use bash syntax highlighting
- Update Visual Studio docs

2022-10-13 21:38 UTC, lunarpapillo requested changes
Mostly style.  Should fix the VS2022 version number, though.

Have you tried the command lines to make sure they work? ;-)

2022-10-13 21:38 UTC, lunarpapillo commented on BUILD.md
>  - [CMake 3.10.2](https://cmake.org/files/v3.10/cmake-3.10.2-win64-x64.zip) is recommended.
Unrelated to your changes, but this caught my eye now.  I believe we currently require a minimu of **CMake** 3.10.2, but I *think* our documented "recommended" **CMake** version is supposed to match the version we actually use in CI, right?  (That would currently be 3.19.3.)

If that's true, this text should be updated to include both the minimum and recommended **CMake** versions, e.g.:
```
- [CMake 3.10.2](https://cmake.org/files/v3.10/cmake-3.10.2-win64-x64.zip) is the minimum CMake version supported.  [CMake 3.19.3](https://cmake.org/files/v3.19/cmake-3.19.3-win64-x64.zip) is recommended.
```

2022-10-13 21:38 UTC, lunarpapillo commented on BUILD.md
> +specify it for Visual Studio 2022, for example, with:
The sentence here is awkward.  Replace with:
```
specify it with the `-G` switch.  For example, to specify Visual Studio 2022, use:
```

2022-10-13 21:38 UTC, lunarpapillo commented on BUILD.md
> +    32-bit: -G "Visual Studio 14 2022" -A Win32
I believe VS2022 would be: `-G "Visual Studio 17 2022"` in both examples.  ("14" is the revision number for VS2015.)

2022-10-13 21:38 UTC, lunarpapillo commented on BUILD.md
> +By default VS2017 and lower target "Win32"
Turn this into a list (or add punctuation, so they won't be sentence fragments), e.g.:
```
NOTE:
- By default, VS2019 and higher target `x64`
- By default, VS2017 and lower target `Win32`

2022-10-13 21:38 UTC, lunarpapillo commented on BUILD.md
> +```
Do we also need:
```
export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu-pkgconfig
```
?

2022-10-13 21:38 UTC, lunarpapillo commented on BUILD.md
> +export PATH=$ANDROID_SDK_HOME/build-tools/26.0.3:$PATH
The `build-tools/N.N.N` directory will change for more recent Android installations (for reference, `tcubuand` and `leasath` have `build-tools/29.0.2`).  CI happens to search the `build-tools` directory looking for the most recent version.

I'm sure you can find a clever way to say this. :-)

2022-10-13 21:38 UTC, lunarpapillo commented on BUILD.md
> +export PATH=$ANDROID_SDK_HOME/build-tools/26.0.3:$PATH
Probably similar to above.

2022-10-13 21:59 UTC, juan-lunarg commented on BUILD.md
> +```
Just tested the 32 bit build. Doesn't appear `PKG_CONFIG_PATH` is needed.

2022-10-13 22:02 UTC, juan-lunarg commented on BUILD.md
> +    32-bit: -G "Visual Studio 14 2022" -A Win32
Good catch you are correct.

2022-10-13 22:36 UTC, juan-lunarg commented
> Have you tried the command lines to make sure they work? ;-)

I did test the 32 bit linux. I got trigger happy with WIN32 due to having documented similar things in the past, and my overconfidence gets to me.

2022-10-14 19:34 UTC, lunarpapillo requested changes

2022-10-14 19:34 UTC, lunarpapillo commented on BUILD.md
> +Check the official CMake docs for further information on Visual Studio generators
I think I'd made an earlier comment on this line that was missed...

2022-10-14 19:34 UTC, lunarpapillo commented on BUILD.md
> +export PATH=$ANDROID_SDK_HOME/build-tools/X.Y.Z:$PATH
Add a comment explaining what `X.Y.Z` needs to be, e.g.:

> where `X.Y.Z` is the most recent version number inside the `build-tools` directory.

2022-10-14 19:37 UTC, lunarpapillo commented on BUILD.md
> +Check the official CMake docs for further information on Visual Studio generators
Hmmm, but I can't find any reference to it... I recommend turning this into a sentence (without a period, it's just a fragment) and including a link, e.g.:
```
Check the [official CMake documentation](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#visual-studio-generators) for further information on Visual Studio generators.
```

2022-10-14 19:46 UTC, lunarpapillo approved these changes
Thanks for your patience and persistence. :-)  This is much better than it was.

2022-10-14 21:14 UTC, merged