Issue 4579 - Unconsumed attributes warning&error behavior
KhronosGroup/Vulkan-ValidationLayers pull request #4672
Opened 2022-10-18 13:54 UTC by arno-lunarg

Fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4579

Completely unconsumed attributes are allowed, and should result in a performance warning if the best practices layer is enabled.
Partially consumed attributes are allowed if `maintenance4` is enabled, but should still result in a performance warning. They are illegal when `maintenance4` is disabled, and result in an error.

Follow up from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4630, had to make some fixes.
From this previous PR, I re-did `ShaderAttribute` struct and (out, in) attributes iteration again, it should be more simple (and more correct)

2022-10-18 17:13 UTC, juan-lunarg requested changes

2022-10-18 17:13 UTC, juan-lunarg commented on layers/shader_validation.h
> +extern const std::array<shader_stage_attributes, 5> shader_stage_attribs;
Suggestion feel free to ignore.

Might be cleaner to have this variable as a static member of `ShaderAttribute`. Since it will act as a namespace essentially.

EX:

```
// Feel free to tweak name to reduce redundancy
ShaderAttribute::shader_stage_attribs
```

2022-10-18 17:13 UTC, juan-lunarg commented on layers/shader_validation.h
> +struct ShaderAttribute {
feel free to ignore

I think it may be cleaner to have `ShaderAttribute` in it's own files. Especially since this header file already defines another class.

ShaderAttribute.h / ShaderAttribute.cpp

2022-10-18 17:15 UTC, juan-lunarg commented on layers/shader_validation.h
> +        if (is_valid) {
This is a question, since I don't fully understand the context. It may be the correct approach. It's just counter intuitive to the regular RAII approach used with classes in C++.

2022-10-18 19:05 UTC, arno-lunarg commented on layers/best_practices_utils.cpp
> +            ((enabled_features.core13.maintenance4 && out.IsOnlyPartiallyConsumed()) || out.IsFullyUnconsumed())) {
`out` is one the lambda's parameter!

2022-10-18 19:11 UTC, arno-lunarg commented on layers/shader_validation.h
> +        if (is_valid) {
Incrementing an iterator in `IterateInterfaceBetweenStages` looks like this:
```cpp
    const auto increment_out_iterator = [&]() {
        if (out_iterator == shader_outputs.end()) return;
        ++out_iterator;
        out = ShaderAttribute(producer, out_iterator, shader_outputs.end());
        if (out.DoesOverflowOnNextLocation()) {
            assert(out_iterator != shader_outputs.end());
            ++out_iterator;
        }
    };
```

But the iterator given to `ShaderAttribute` can be invalid, thus the check. The validity of `ShaderAttribute` is checked when comparing it to another one, here when comparing `out` and `in`. This logic happens inside the `ShaderAttribute` class, I found that it made the code in `IterateInterfaceBetweenStages` more readable.
I could try to always pass a valid iterator, but I think it would make `IterateInterfaceBetweenStages` messier?

2022-10-18 19:13 UTC, arno-lunarg commented on layers/shader_validation.h
> +extern const std::array<shader_stage_attributes, 5> shader_stage_attribs;
yep it would be better!

2022-10-18 19:16 UTC, arno-lunarg commented on layers/shader_validation.h
> +struct ShaderAttribute {
yes I think you are right... And the name too, `ShaderAttribute` still not sure about it, since this class was made to help check shader attributes, it sort of wraps parts of a shader attribute, plus things related to performing the check, so I should find another name.

2022-10-18 19:29 UTC, juan-lunarg commented on layers/best_practices_utils.cpp
> +            ((enabled_features.core13.maintenance4 && out.IsOnlyPartiallyConsumed()) || out.IsFullyUnconsumed())) {
Oh sorry I read this wrong...

2022-10-18 19:32 UTC, juan-lunarg commented on layers/shader_validation.h
> +        if (is_valid) {
Gotcha, that makes sense. I'll mark this as resolved.

2022-10-19 09:42 UTC, arno-lunarg commented on layers/shader_validation.h
> +extern const std::array<shader_stage_attributes, 5> shader_stage_attribs;
In the end I moved it in the only function it is used, `ValidateInterfaceBetweenAllPipelineStages`

2022-10-19 09:42 UTC, arno-lunarg commented on layers/shader_validation.h
> +struct ShaderAttribute {
I Added `shader_attribute_validation.h`, and renamed `ShaderAttribute` to `ShaderAttributeValidation`

2022-10-19 17:27 UTC, juan-lunarg requested changes

2022-10-19 17:27 UTC, juan-lunarg commented on layers/best_practices_validation.h
> +#include "shader_validation.h"
Since everything is passed by pointer or reference you can just forward declare instead of including.

2022-10-19 17:27 UTC, juan-lunarg commented on layers/shader_attribute_validation.h
> +        if (is_valid_) {
Return early to avoid indenting the majority of the logic.

```suggestion
        if (!is_valid_) { return; }
```

2022-10-19 17:27 UTC, juan-lunarg commented on layers/shader_attribute_validation.h
> +        if (range_intersection.non_empty()) {
Return early to avoid indenting the majority of the logic.

```suggestion
        if (range_intersection.empty()) { return; }
```

2022-10-19 17:27 UTC, juan-lunarg commented on layers/shader_attribute_validation.h
> +    static const std::array<shader_stage_attributes, 5> shader_stage_attribs = {
nitpick

```suggestion
    constexpr std::array<shader_stage_attributes, 5> shader_stage_attribs = {
```

2022-10-19 18:16 UTC, arno-lunarg commented on layers/shader_attribute_validation.h
> +    std::array<ComponentStatus, 16> components_ = {{ComponentStatus::Uninitialized}};
a `mat4` occupies 16 components, or 4 components on 4 consecutive locations. But writing that, I now realise that a `dmat4` would occupy 32 components, each scalar occupying 2 components... need to have a look at this. And will add a comment regarding where this array's size comes from

2022-10-19 18:22 UTC, arno-lunarg commented on layers/shader_attribute_validation.h
> +class ShaderAttributeValidation {
I think this small is too small for the decrease in compile time to be a problem, and with the present form it gives the compiler the choice of inlining or not. So I think it is ok to keep it as an header only. But maybe the other reviewers have another opinion!

2022-10-19 18:27 UTC, arno-lunarg commented on layers/shader_attribute_validation.h
> +    }
I added a comment on `DoesOverflowOnNextLocation` to explain the method:
```cpp
// True for vector types with more than 2 components and 64 bits scalar type (dvec3, dvec4, ...)
    bool DoesOverflowOnNextLocation() const { return components_count_ > 4; }
```
But on this specific block, I need to add another comment, stating why I need to increment iterators if this is true: in that case, tne next iterator holds the same info as the current one but with an incremented `location`. Since it is still the same out/in attribute, I skip it.

2022-10-19 18:29 UTC, arno-lunarg commented on layers/best_practices_validation.h
> +#include "shader_validation.h"
I think that according to the style guide, I should keep the include: https://google.github.io/styleguide/cppguide.html#Forward_Declarations

2022-10-19 18:29 UTC, arno-lunarg commented on layers/shader_attribute_validation.h
> +        if (is_valid_) {
yes it looks better this way!

2022-10-19 18:30 UTC, arno-lunarg commented on layers/shader_attribute_validation.h
> +    static const std::array<shader_stage_attributes, 5> shader_stage_attribs = {
I think I still need the `static` keyword here? Does `constexpr` implies `static`?

2022-10-19 18:43 UTC, juan-lunarg commented on layers/shader_attribute_validation.h
> +    static const std::array<shader_stage_attributes, 5> shader_stage_attribs = {
After checking godbolt and cppreference, constexpr doesn't imply static

https://godbolt.org/z/G7Wb35594

You still need the static keyword.

2022-10-19 19:13 UTC, juan-lunarg commented on layers/best_practices_validation.h
> +#include "shader_validation.h"
Ah. I was looking at a different style guide.

2022-10-19 19:14 UTC, juan-lunarg commented on layers/shader_attribute_validation.h
> +    static const std::array<shader_stage_attributes, 5> shader_stage_attribs = {
FFTI this request. I thought constexpr did imply static. I learned something new.

2022-10-19 19:18 UTC, arno-lunarg commented on layers/shader_attribute_validation.h
> +    std::array<ComponentStatus, 16> components_ = {{ComponentStatus::Uninitialized}};
Actually, it seems that I only need a size of 8. Each column of a matrix occupies its own location, so just need a max of 8 to be able to fit a `dvec4`

2022-10-19 20:54 UTC, juan-lunarg approved these changes
1 minor nitpick other than that LGTM

2022-10-19 20:54 UTC, juan-lunarg commented on layers/shader_attribute_validation.h
> +    std::array<ComponentStatus, 8> components_ = {{ComponentStatus::Uninitialized}};
Add comment explaining size 8

2022-10-20 10:01 UTC, arno-lunarg commented on layers/shader_attribute_validation.h
> +    std::array<ComponentStatus, 8> components_ = {{ComponentStatus::Uninitialized}};
oopsy forgot to add it

2022-10-20 10:43 UTC, spencer-lunarg commented on layers/shader_attribute_validation.h
> +class ShaderAttributeValidation {
It takes quit a bit to fully understand what this class/file is actually for. 

Also I think `attribute` is the wrong name for this. In Vulkan an `attribute` is only for the input of the vertex shader

2022-10-20 10:50 UTC, spencer-lunarg commented on layers/shader_module.h
> +    static uint32_t GetShaderStageId(VkShaderStageFlagBits stage) {
I don't think this belongs in `SHADER_MODULE_STATE`, I didn't see the issue of keeping it in the .cpp file as it was

2022-10-20 10:51 UTC, spencer-lunarg commented on layers/shader_module.cpp
> +    if ( opcode == spv::OpTypePointer )
nit: This ran with clang-format? not sure how this is passing

2022-10-20 10:59 UTC, spencer-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +        CreatePipelineHelper::OneshotTest(*this, set_info, kErrorBit, "VUID-RuntimeSpirv-OpTypeVector");
this needs to be `VUID-RuntimeSpirv-OpTypeVector-06816` (also you have `VUID-RuntimeSpirv-OpTypeVector-06817` but it is `VUID-RuntimeSpirv-maintenance4-06817`)

2022-10-20 11:02 UTC, spencer-lunarg commented on layers/shader_validation.cpp
> +                            std::string{producer_stage->name} + " writes to output location " + std::to_string(out_location) + '.' +
This is not what `VUID-RuntimeSpirv-maintenance4-06817` is checking

> If [maintenance4](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#features-maintenance4) is not enabled, any OpTypeVector output interface variables must not have a higher Component Count than a matching OpTypeVector input interface variable

This is VU is suppose to be used to check if the vertex shader writes `vec4` but fragment shader reads `vec3` at the same `Location` and nothing to do with being consumed

2022-10-20 11:16 UTC, spencer-lunarg commented on layers/shader_validation.cpp
> +    auto validate_attrib = [this](const SHADER_MODULE_STATE &producer, shader_stage_attributes const *producer_stage,
what is the advantage of doing this as a lambda here and not having this just be a separate function?

2022-10-20 11:41 UTC, arno-lunarg commented on layers/shader_attribute_validation.cpp
> +    const auto base_type_components_count = shader_module.GetNumComponentsInBaseType(def);
chat with spencer

2022-10-20 12:47 UTC, arno-lunarg commented on layers/shader_validation.cpp
> +    auto validate_attrib = [this](const SHADER_MODULE_STATE &producer, shader_stage_attributes const *producer_stage,
I need to pass this function to `IterateInterfaceBetweenStages`, and since it calls methods on a `CoreChecks` object, better to capture `this` using a lambda

2022-10-20 12:48 UTC, arno-lunarg commented on layers/shader_module.cpp
> +    if ( opcode == spv::OpTypePointer )
Yes I am surprise it ran without issue... Will do the change manually

2022-10-20 12:50 UTC, arno-lunarg commented on layers/shader_module.h
> +    static uint32_t GetShaderStageId(VkShaderStageFlagBits stage) {
This function is now used in `ValidateInterfaceBetweenAllPipelineStages` (`shader_attribute_validation.h`), it need to be moved somewhere. I am open to a better location though!

2022-10-20 12:56 UTC, arno-lunarg commented on layers/shader_attribute_validation.h
> +class ShaderAttributeValidation {
I do not like this name either, and I am open to suggestions. Reading [the glsl spec](https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.pdf), page 51:
> It is expected that graphics hardware will have a small number of fixed vector locations for passing
vertex inputs. Therefore, the OpenGL Shading Language defines each non-matrix input variable as
taking up one such vector location.

So I could maybe rename it to `VectorLocationValidation`? Add still add a comment

2022-10-20 13:04 UTC, arno-lunarg commented on layers/shader_attribute_validation.h
> +class ShaderAttributeValidation {
I think `InterfaceLocationValidation` better captures the intent, and the names of the 2 other functions in this .h

2022-10-20 18:05 UTC, arno-lunarg commented on layers/shader_validation.cpp
> +#if 0
Until maintenance4 description is clarified, this part is disabled

2022-10-20 18:31 UTC, arno-lunarg commented on layers/shader_validation.cpp
> +#if 0
@ncesario-lunarg and @spencer-lunarg for visibility

2023-03-30 10:05 UTC, spencer-lunarg commented
This will need a LOT of rebasing with new shader module refactoring. Going to close this as it has got stale, tracking issue still has reference for when we need to find this code

2023-03-30 10:06 UTC, closed without merging