build: Use C++14 standard
KhronosGroup/Vulkan-ValidationLayers pull request #4685
Opened 2022-10-19 22:46 UTC by ncesario-lunarg

@juan-lunarg showed that we are already using C++14 features, so making the minimum explicit.

2022-10-20 16:32 UTC, juan-lunarg commented
> CI Vulkan-ValidationLayers build # 9100 passed.

Probably a good idea to update build.gn and the android build as well

2022-10-22 04:10 UTC, ncesario-lunarg commented
> > CI Vulkan-ValidationLayers build # 9100 passed.
> 
> Probably a good idea to update build.gn and the android build as well

I don't see where to make this change, but that is probably just due to my ignorance with GN.

2022-10-24 15:11 UTC, juan-lunarg commented
> I don't see where to make this change, but that is probably just due to my ignorance with GN.

Yeah, I was a bit confused by that as well.

2022-11-11 22:11 UTC, juan-lunarg commented
The GN build has a minor issue:
```
-std=c++17 -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=c++14
```

Looks like -std=c++14 is overriding the -std=c++17 you set

2022-11-11 22:25 UTC, juan-lunarg commented on BUILD.gn
> +  }
I found an example for setting the C++ standard:
https://fuchsia.googlesource.com/fuchsia/+/refs/heads/main/build/config/BUILD.gn

Looks like there is a kinda standard approach. Couldn't find anything in the docs.

```
import("//build_overrides/vulkan_validation_layers.gni")

config("language") {
  if (!is_win) {
    cflags_cc += [ "-std=c++17" ]
  } else {
    cflags_cc += [ "/std:c++17" ]
  }
}
```

2022-11-11 22:27 UTC, juan-lunarg commented on BUILD.gn
> +  }
Note you want to use the `cflags_cc` variable otherwise you'll affect the compilation of `xxhash` which is a c library

2022-11-11 22:30 UTC, juan-lunarg commented on BUILD.gn
> +  }
Hmm, now I'm not so sure after looking at this chromium build.
https://github.com/timniederhausen/gn-build/blob/923683700a39a53ecf467974cbf29f3405358292/config/BUILD.gn#L807

2022-11-11 22:34 UTC, juan-lunarg commented on BUILD.gn
> +  }
Looks like the chromium builds don't have  a standardized approach like `CXX_STANDARD` in CMake. So each repo makes up their own approach.

2022-11-11 22:58 UTC, ncesario-lunarg commented on BUILD.gn
> +  }
:+1: thanks! I can cherry pick the changes you made in #4791 here.

The internal build failure looks spurious.

2022-11-11 23:11 UTC, juan-lunarg commented on BUILD.gn
> +  }
I wouldn't cherry pick yet since my change failed to build.

2022-11-11 23:56 UTC, juan-lunarg commented on BUILD.gn
> +  }
Latest version of my PR appears to pass.

2022-11-15 16:31 UTC, juan-lunarg requested changes

2022-11-15 16:31 UTC, juan-lunarg commented on BUILD.md
> +that the minimum officially supported C++17 compiler version is GCC 5.4.0,
The Ubuntu version and GCC version don't seem correct.

2022-11-15 17:59 UTC, juan-lunarg commented on BUILD.md
> +that the minimum officially supported C++17 compiler version is GCC 5.4.0,
Min Ubuntu version should be 18.04, not sure what the min GCC version should be.

2022-11-15 18:22 UTC, juan-lunarg approved these changes

2022-11-15 23:16 UTC, merged