docs: Documentation cleanup
KhronosGroup/Vulkan-ValidationLayers pull request #4700
Opened 2022-10-24 11:19 UTC by spencer-lunarg

In effort to make it easier for new developers to get up and running with the code

Highlights:
- Reduce `BUILD.md` to just what it takes to build
- Created `tests/README.md` to hold information about running the tests
- Added a `docs/generated_code.md` and `docs/shader_validation.md`

2022-10-25 05:16 UTC, ncesario-lunarg approved these changes
Some minor grammar nits here and there, but I'd be happy taking this as is. Clears things up nicely!

2022-10-25 05:16 UTC, ncesario-lunarg commented on docs/generated_code.md
> +If only dealing with a single file, comment out all the other file names `scripts/generate_source.py` to speed up testing iteration.
```suggestion
If only dealing with a single file, comment out all the other file names in `scripts/generate_source.py` to speed up testing iterations.
```

2022-10-25 05:16 UTC, ncesario-lunarg commented on docs/shader_validation.md
> +as well as the `VkPipeline` object interface with the shader. Note, this all done on the CPU and different than
```suggestion
Shader validation is run at `vkCreateShaderModule` and `vkCreate*Pipelines` time. It makes sure both the `SPIR-V` is valid
as well as the `VkPipeline` object interface with the shader. Note, this is all done on the CPU and different than
```

2022-10-25 05:16 UTC, ncesario-lunarg commented on docs/shader_validation.md
> +There are a few special places where `spirv-opt` is ran to reduce recreating work already done in `SPIRV-Tools`.
```suggestion
There are a few special places where `spirv-opt` is run to reduce recreating work already done in `SPIRV-Tools`.
```

2022-10-25 05:16 UTC, ncesario-lunarg commented on docs/stateless_validation.md
> +validation found in Stateless Validation it will return and not call Core Validation.
```suggestion
The Stateless Validation is run before [Core Validation Checks](core_checks.md). If there is a
validation error found in Stateless Validation, it will return and not call Core Validation nor call down the layer chain.
```

2022-10-25 05:16 UTC, ncesario-lunarg commented on tests/README.md
> +- ``VkPortabilitySubsetTest` - Test [VK_KHR_portability_subset validation](../docs/portability_validation.md)
Might make sense for this to be a bit more generic. There are more "categories" than these, and I think it would be helpful if there were even more (e.g., I think a category for each "tests" cpp file would be helpful).

2022-10-25 05:16 UTC, ncesario-lunarg commented on tests/README.md
> +export VK_LAYER_PATH=/path/to/Vulkan-ValidationLayers/build/layers/
I think this is effectively the same for Windows as well. Could maybe combine Windows and Linux (and Mac?) to be "set the environment variable `VK_LAYER_PATH` ..."

I think Android is the only one that requires "special instructions."

2022-10-25 05:30 UTC, spencer-lunarg commented on BUILD.md
> +OR set the Vulkan-ValidationLayers CMake option `USE_ROBIN_HOOD_HASHING` to `OFF`.
It was, but threw it under the `Build Options` section for the time being

2022-10-25 05:40 UTC, spencer-lunarg commented on tests/README.md
> +- ``VkPortabilitySubsetTest` - Test [VK_KHR_portability_subset validation](../docs/portability_validation.md)
I think I was thinking as `TEST_F` categories which I realize looking at `layer_validation_tests.h` there are actually more than these, will change this up though

2022-11-09 14:58 UTC, spencer-lunarg commented on BUILD.md
> +### Windows Install Target
Happy to remove later, for now it is at the bottom of the file

2022-11-09 15:00 UTC, spencer-lunarg commented on tests/README.md
> +- ``VkPortabilitySubsetTest` - Test [VK_KHR_portability_subset validation](../docs/portability_validation.md)
reworded

2022-11-10 18:22 UTC, juan-lunarg requested changes

2022-11-10 18:22 UTC, juan-lunarg commented on BUILD.md
> +    - You must clone the headers repository and build its `install` target
I don't clone and install the loader.

2022-11-10 18:22 UTC, juan-lunarg commented on docs/README.md
> +This directory contains more detailed information about how each part of the Validation Layers work.
This file would be much more useful with a table of content:
https://stackoverflow.com/questions/18244417/how-do-i-create-some-kind-of-table-of-content-in-github-wiki

2022-11-10 18:22 UTC, juan-lunarg commented on BUILD.md
> +If Python is found on your system, the Vulkan Registry and SPIRV-Headers **must** be present!
Redirect users to the `generated_code.md` file instead

2022-11-10 18:22 UTC, juan-lunarg commented on tests/README.md
> +
```suggestion
```

2022-11-17 12:29 UTC, merged