layers: Fix missing linear_color_attachment validation
KhronosGroup/Vulkan-ValidationLayers pull request #4725
Opened 2022-10-27 23:43 UTC by pdaniell-nv

There were a few places where VVL would throw false failures when the application tried to use linear color attachments with the VK_NV_linear_color_attachment extension and linearColorAttachment feature enabled. Implementations that can't support general color attachment usage of linear images can expose this extension if they can support it with the restriction that all color attachments to the framebuffer are either optimal or linear, and not a mix of the two. Because of this restriction, they can't advertise the regular VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT format feature for linear images, they instead advertise VK_FORMAT_FEATURE_2_LINEAR_COLOR_ATTACHMENT_BIT_NV.

2022-10-28 07:42 UTC, spencer-lunarg commented on layers/core_validation.cpp
> +                if (!enabled_features.linear_color_attachment_features.linearColorAttachment) {
So the reason we use `IsExtEnabled` is depending which extension is given determines the URL link to the spec

I would expect somewhere else to make sure `VK_FORMAT_FEATURE_2_LINEAR_COLOR_ATTACHMENT_BIT_NV` can't be used without `linearColorAttachment` and with that assumption this code could be simplified to

```cpp
if ((format_features & (VK_FORMAT_FEATURE_2_COLOR_ATTACHMENT_BIT | VK_FORMAT_FEATURE_2_LINEAR_COLOR_ATTACHMENT_BIT_NV)) == 0) {
    IsExtEnabled(device_extensions.vk_nv_linear_color_attachment)
    const char *vuid = IsExtEnabled(device_extensions.vk_nv_linear_color_attachment)
                    ? "VUID-VkGraphicsPipelineCreateInfo-renderPass-06582"
                    : "VUID-VkGraphicsPipelineCreateInfo-renderPass-06581";
    skip |= LogError(device, vuid,
                    "vkCreateGraphicsPipelines() pCreateInfos[%" PRIu32
                    "]: pColorAttachmentFormats[%" PRIu32 "] color format (%s) must be a format with potential format features that include "
                    "VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT or VK_FORMAT_FEATURE_2_LINEAR_COLOR_ATTACHMENT_BIT_NV",
                    pipe_index, color_index, string_VkFormat(color_format));
}
```

2022-10-28 07:44 UTC, spencer-lunarg commented on layers/core_validation.cpp
> +                                        "VUID-VkCommandBufferInheritanceRenderingInfoKHR-pColorAttachmentFormats-06492",
random side note: `Linear Color attachment` in the spec for this VUID doesn't actually point anywhere

2022-10-28 07:46 UTC, spencer-lunarg commented on layers/core_validation.cpp
> +                                if ((potential_format_features & (VK_FORMAT_FEATURE_2_COLOR_ATTACHMENT_BIT_KHR |
This VU seems to only be checking for `VK_FORMAT_FEATURE_2_LINEAR_COLOR_ATTACHMENT_BIT_NV` and seems this would not catch a case where `COLOR_ATTACHMENT_BIT` is only set instead

2022-10-28 07:47 UTC, spencer-lunarg commented on layers/core_validation.cpp
> +                    if (!enabled_features.linear_color_attachment_features.linearColorAttachment) {
I'm slightly confused, so if `linearColorAttachment` is enabled the format could not have `VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT` and still be valid?

2022-10-28 17:37 UTC, pdaniell-nv commented on layers/core_validation.cpp
> +                    if (!enabled_features.linear_color_attachment_features.linearColorAttachment) {
Right. VK_NV_linear_color_attachment was created because we can't advertise VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT in general for linear tiling image because the Vulkan spec allows framebuffers to be created with a mixture of linear and optimal color image attachments, but we only support all optimal or all linear attachments. So this extension created a new format feature bit to indicate that the linear image can be used as a color attachment, but in this more limited way.

2022-11-01 07:48 UTC, spencer-lunarg requested changes
@pdaniell-nv it all LGTM to merge but first

1. I would inverse the logic of the `if/else` to more match the wording of the VUID (prevent someone in the future from messing it up)
2. Can we get a test to help prevent a regression here, should be able to hopefully just take the logic of the current tests for the other VUs and just add a

```c++
AddRequiredExtensions(VK_NV_LINEAR_COLOR_ATTACHMENT_EXTENSION_NAME);
// ...
auto linear_color_features = LvlInitStruct<VkPhysicalDeviceLinearColorAttachmentFeaturesNV>();
VkPhysicalDeviceFeatures2 features2 = GetPhysicalDeviceFeatures2(linear_color_features);
if (linear_color_features.linearColorAttachment == VK_FALSE) {
    GTEST_SKIP() << "Test requires (unsupported) linearColorAttachment";
}

// Use the formats you can't expose COLOR_ATTACHMENT on
```

and it should hit the other VUs for you

2022-11-01 07:48 UTC, spencer-lunarg commented on layers/core_validation.cpp
> +                            if (!enabled_features.linear_color_attachment_features.linearColorAttachment) {
Looking that these VUs, I think the logic for all of these should be the following to help make the it less error prone for a future dev touching this code

```c++
if ((potential_format_features & VK_FORMAT_FEATURE_2_COLOR_ATTACHMENT_BIT_KHR) == 0) {
    if (!enabled_features.linear_color_attachment_features.linearColorAttachment) {
        LogError(06006);
    } else if ((potential_format_features & VK_FORMAT_FEATURE_2_LINEAR_COLOR_ATTACHMENT_BIT_NV) == 0) {
        LogError(06492);
    }
}
```

2022-11-01 21:39 UTC, pdaniell-nv commented
> @pdaniell-nv it all LGTM to merge but first
> 
> 1. I would inverse the logic of the `if/else` to more match the wording of the VUID (prevent someone in the future from messing it up)
> 2. Can we get a test to help prevent a regression here, should be able to hopefully just take the logic of the current tests for the other VUs and just add a
> 
> ```c++
> AddRequiredExtensions(VK_NV_LINEAR_COLOR_ATTACHMENT_EXTENSION_NAME);
> // ...
> auto linear_color_features = LvlInitStruct<VkPhysicalDeviceLinearColorAttachmentFeaturesNV>();
> VkPhysicalDeviceFeatures2 features2 = GetPhysicalDeviceFeatures2(linear_color_features);
> if (linear_color_features.linearColorAttachment == VK_FALSE) {
>     GTEST_SKIP() << "Test requires (unsupported) linearColorAttachment";
> }
> 
> // Use the formats you can't expose COLOR_ATTACHMENT on
> ```
> 
> and it should hit the other VUs for you

Thanks for the review. I've addressed your two requests.

2022-11-01 22:12 UTC, spencer-lunarg approved these changes

2022-11-02 02:59 UTC, merged