layers: Remove unused ValidateViConsistency
KhronosGroup/Vulkan-ValidationLayers pull request #4774
Opened 2022-11-09 07:57 UTC by spencer-lunarg

I realized that `ValidateViConsistency` is not being checked because there is already 

> VUID-VkPipelineVertexInputStateCreateInfo-pVertexBindingDescriptions-00616
>
> All elements of pVertexBindingDescriptions must describe distinct binding numbers

That is validating this

Also while at it, took the `vkCmdSetVertexInputEXT` logic and made it consistent and improved the error message

2022-11-09 17:39 UTC, juan-lunarg submitted a review, later dismissed

2022-11-09 17:39 UTC, juan-lunarg commented on layers/parameter_validation_utils.cpp
> +            auto const &binding_it = vertex_bindings.find(binding);
`find` doesn't return a const reference

2022-11-09 17:39 UTC, juan-lunarg commented on layers/parameter_validation_utils.cpp
> +            auto const &location_it = vertex_locations.find(location);
`find` doesn't return a const reference

2022-11-09 20:03 UTC, ncesario-lunarg reviewed
LGTM once Juan's comments are resolved.

2022-11-09 20:03 UTC, ncesario-lunarg commented on layers/parameter_validation_utils.cpp
> +            auto const &binding_it = vertex_bindings.find(binding);
I believe it is legal to assign an rvalue to a const ref and this _can_ (??) avoid copy construction, so I think this is fine, but it's quite possible I'm not remembering this detail correctly.

2022-11-09 20:49 UTC, juan-lunarg commented on layers/parameter_validation_utils.cpp
> +            auto const &binding_it = vertex_bindings.find(binding);
@ncesario-lunarg is correct. I forgot the nuance for `const` references. [Source FWIW](https://stackoverflow.com/questions/22845167/const-reference-and-lvalue)

2022-11-09 20:51 UTC, juan-lunarg submitted a review, later dismissed

2022-11-09 21:46 UTC, juan-lunarg requested changes
```
[ctest] The following tests FAILED:
[ctest] 	594 - VkLayerTest.ValidateVertexInputDynamicStateEnabled (SEGFAULT)
[ctest] 	595 - VkLayerTest.ValidateVertexInputDynamicStateDivisor (SEGFAULT)
```

2022-11-09 21:53 UTC, juan-lunarg requested changes

2022-11-09 21:53 UTC, juan-lunarg commented on layers/parameter_validation_utils.cpp
> +        for (uint32_t i = 0; i < vertexBindingDescriptionCount; ++i) {
```suggestion
        layer_data::unordered_set<uint32_t> vertex_locations(vertexAttributeDescriptionCount);
        for (uint32_t i = 0; i < vertexAttributeDescriptionCount; ++i) {
```

2022-11-10 17:01 UTC, juan-lunarg approved these changes
LGTM

2022-11-10 18:47 UTC, merged