Add VK_EXT_descriptor_buffer
KhronosGroup/Vulkan-ValidationLayers pull request #4828
Opened 2022-11-18 13:17 UTC by archimedus

Add support into validation layers for VK_EXT_descriptor_buffer and appropriate tests.
Mostlikely [defs: Update VK_EXT_descriptor_buffer in known_good.json](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/5b3b80df983a6c353cf0c282f3e972579b3aea6a) should be removed

2022-11-18 13:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=4828) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=4828) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: stu-s<br/>:x: Boris Zanin<br/><hr/>**Boris Zanin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-ValidationLayers?pullRequest=4828) it.</sub>

2022-11-18 15:57 UTC, jeremyg-lunarg requested changes
Getting there!  Here are the major problems:
# the script/known_good.json changes should be left out since they're a no-op. (git rebase -i; git push -f your-fork)
# ValidationStateTracker should not have PreCallValidate methods. I think I pointed this out earlier on gitlab but maybe I forgot
# CoreChecks should not have Pre/PostCallRecord methods (in this case at least, there are exceptions)
# The FIXME comments need to be removed or they will confuse scripts/vk_validation_stats.py. I will pull down this version of the PR and make an Issue for all the VUIDs mentioned in a fixme.
# It looks like you found and fixed a pre-existing problem in cmd_buffer_state.cpp. I will make a separate PR for this fix so that we can bookkeep any existing issues that it fixes.

2022-11-18 15:57 UTC, jeremyg-lunarg commented on layers/object_tracker_utils.cpp
> +			} break;
The indentation here is very strange. Is this the output of `git clang-format`? Does it get better if you do:
```
         }
         break;
     }
```

2022-11-18 15:57 UTC, jeremyg-lunarg commented on layers/state_tracker.h
> +    bool VerifyBoundMemoryIsValid(const DEVICE_MEMORY_STATE* mem_state, const T1 object, const VulkanTypedHandle& typed_handle,
I don't think these Verify* methods should be in state_tracker.h, why did they need to move out of core_validation.h? Maybe we can find a better place for them if necessary.

2022-11-18 15:57 UTC, jeremyg-lunarg commented on layers/descriptor_validation.cpp
> +bool ValidationStateTracker::PreCallValidateCmdBindDescriptorBufferEmbeddedSamplersEXT(VkCommandBuffer commandBuffer,
This should be a CoreChecks method.

2022-11-18 15:57 UTC, jeremyg-lunarg commented on layers/descriptor_validation.cpp
> +bool ValidationStateTracker::PreCallValidateCmdSetDescriptorBufferOffsetsEXT(VkCommandBuffer commandBuffer,
This should be a CoreChecks method.

2022-11-18 15:57 UTC, jeremyg-lunarg commented on layers/descriptor_validation.cpp
> +void ValidationStateTracker::PreCallRecordCmdBindDescriptorBuffersEXT(VkCommandBuffer commandBuffer, uint32_t bufferCount,
This should be in state_tracker.cpp

2022-11-18 15:57 UTC, jeremyg-lunarg commented on layers/descriptor_validation.cpp
> +void ValidationStateTracker::PreCallRecordCmdSetDescriptorBufferOffsetsEXT(VkCommandBuffer commandBuffer,
state_tracker.cpp

2022-11-18 15:57 UTC, jeremyg-lunarg commented on layers/descriptor_validation.cpp
> +bool ValidationStateTracker::ValidateDescriptorAddressInfoEXT(VkDevice device,
CoreChecks

2022-11-18 15:57 UTC, jeremyg-lunarg commented on layers/descriptor_validation.cpp
> +bool ValidationStateTracker::PreCallValidateGetDescriptorEXT(VkDevice device, const VkDescriptorGetInfoEXT *pDescriptorInfo,
CoreChecks

2022-11-18 15:57 UTC, jeremyg-lunarg commented on layers/state_tracker.h
> +    bool VerifyBoundMemoryIsValid(const DEVICE_MEMORY_STATE* mem_state, const T1 object, const VulkanTypedHandle& typed_handle,
Reviewing further, I think this was necessary because of the PreCallValidate methods added to ValidationStateTracker below. Those should move to CoreChecks and then these templates can stay where they were I think.

2022-11-18 15:57 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +bool ValidationStateTracker::ValidateMemoryIsBoundToBuffer(const BUFFER_STATE *buffer_state, const char *api_name,
This should be in descriptor_validation.cpp and be a CoreChecks method. Applies to all other methods with Validate in their name.

2022-11-18 15:57 UTC, jeremyg-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +        // frag_shader_lib.InitState();
Why are these InitState() calls commented out? Please remove if they're not needed.

2022-11-21 04:57 UTC, spencer-lunarg commented on layers/buffer_validation.cpp
> +    if ((pCreateInfo->usage & VK_BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT) &&
I would make group the `VK_BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT` together

```cpp
 if (pCreateInfo->usage & VK_BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT) {
    // 08101 check
    
    // 08102 check
        
    // 08103 check
 }
```

2022-11-21 05:03 UTC, spencer-lunarg commented on layers/core_validation.h
> +    const char* descriptor_buffer_08114 = kVUIDUndefined;
these VUID sometimes change number, so nice to have the variable name be not tied to the VUID number

Some suggestions

`descriptor_buffer_08114` - > `descriptor_buffer_bit_set`
`descriptor_buffer_08115` - > `descriptor_buffer_bit_not_set`
`descriptor_buffer_08116` - > `descriptor_buffer_set_offset_dynamic`
`descriptor_buffer_08117` - > `descriptor_buffer_set_offset_missing`

2022-11-21 05:05 UTC, spencer-lunarg commented on layers/state_tracker.h
> +    bool VerifyBoundMemoryIsValid(const DEVICE_MEMORY_STATE* mem_state, const T1 object, const VulkanTypedHandle& typed_handle,
Haven't got far enough in the review, but we should not have anything called `Verify` that belongs to the State Tracker, so we do keep it here, the names need to change

2022-11-21 05:06 UTC, spencer-lunarg commented on scripts/generate_source.py
> -                   # Temporarily disable VK_EXT_descriptor_buffer codegen until more complete support lands
Creating comment to not forget to remove this before merging

2022-11-21 05:12 UTC, spencer-lunarg commented on scripts/helper_file_generator.py
> +            # It looks like framework is not ready for two properties structs per extension (like VK_EXT_descriptor_buffer have). Workarounding.
o this is not nice at all, creating a separate issue, can you put a  `# TODO Issue 4841 - ` in front of this for me

2022-11-21 05:15 UTC, spencer-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +TEST_F(VkLayerTest, DescriptorBufferLibrary) {
I would move this test to `vklayertests_graphics_library.cpp`

2022-11-21 05:17 UTC, spencer-lunarg commented on layers/descriptor_sets.h
> +    std::unique_ptr<VkDeviceSize> layoutSizeInBytes;
nit: `layout_size_in_bytes` to match other variable naming convention

2022-11-21 11:56 UTC, archimedus commented on layers/cmd_buffer_state.cpp
> -            auto &set_info = last_bound.per_set[set_index];
Please point me the new PR or please clarify which problem it might cause?
For me it looks like more like finding typo: the condition that avoiding crash is in following if-operator.

2022-11-21 12:01 UTC, archimedus commented on layers/object_tracker_utils.cpp
> +			} break;
before break for some reason `tab` is used. With tab width 4 it looks ok, with tab width 8 it looks strange.
I will replace tab with space.

2022-11-21 13:17 UTC, spencer-lunarg commented on layers/cmd_buffer_state.cpp
> -            auto &set_info = last_bound.per_set[set_index];
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4831

2022-11-21 15:17 UTC, archimedus commented on layers/state_tracker.h
> +    bool VerifyBoundMemoryIsValid(const DEVICE_MEMORY_STATE* mem_state, const T1 object, const VulkanTypedHandle& typed_handle,
I rearranged methods and this time I hope correctly.

2022-11-21 15:20 UTC, archimedus commented on layers/core_validation.cpp
> +        if (!cb_node->descriptor_buffer_bindings.empty()) {
Nothing good: it will flood with values either 8114 or 8116.

8116 requires access to values in buffer. This cookie will be useful when GPU AV assistance will be ready.

I better remove 8114: it seems it replaces 2699 and I suppose I just should `sed s/02699/08114/`

2022-11-21 15:21 UTC, archimedus commented on tests/vklayertests_pipeline_shader.cpp
> +TEST_F(VkLayerTest, DescriptorBufferLibrary) {
moved

2022-11-21 15:22 UTC, archimedus commented on scripts/helper_file_generator.py
> +            # It looks like framework is not ready for two properties structs per extension (like VK_EXT_descriptor_buffer have). Workarounding.
Do I need to do anything here?

2022-11-21 15:22 UTC, archimedus commented on scripts/generate_source.py
> -                   # Temporarily disable VK_EXT_descriptor_buffer codegen until more complete support lands
Hm. `-` in the beginning means I removed it. Do I miss anything else here?

2022-11-21 15:23 UTC, archimedus commented on layers/core_validation.h
> +    const char* descriptor_buffer_08114 = kVUIDUndefined;
done

2022-11-21 15:23 UTC, archimedus commented on tests/vklayertests_pipeline_shader.cpp
> +        // frag_shader_lib.InitState();
removed

2022-11-21 15:25 UTC, archimedus commented on layers/descriptor_sets.cpp
> +    else
done

2022-11-21 15:33 UTC, archimedus commented on scripts/known_good.json
> +            "url": "https://gitlab.khronos.org/vulkan/Vulkan-Headers.git",
done

2022-11-23 02:11 UTC, spencer-lunarg commented on scripts/generate_source.py
> -                   # Temporarily disable VK_EXT_descriptor_buffer codegen until more complete support lands
sorry, I am dumb, when I looked at this I thought it was green and adding it... this is perfect, thanks :sweat_smile:

2022-11-23 02:11 UTC, spencer-lunarg commented on scripts/helper_file_generator.py
> +            # It looks like framework is not ready for two properties structs per extension (like VK_EXT_descriptor_buffer have). Workarounding.
```suggestion
            # TODO Issue 4841 -  It looks like framework is not ready for two properties structs per extension (like VK_EXT_descriptor_buffer have). Workarounding.
```

2022-11-23 12:09 UTC, archimedus commented on scripts/helper_file_generator.py
> +            # It looks like framework is not ready for two properties structs per extension (like VK_EXT_descriptor_buffer have). Workarounding.
done

2022-11-23 12:12 UTC, archimedus commented on layers/core_validation.cpp
> +        if (!cb_node->descriptor_buffer_bindings.empty()) {
I see difference between 2699 and 8114. I implemented proper usage of 2699 and 8114.

2022-11-23 12:14 UTC, archimedus commented on layers/core_validation.cpp
> +    // FIXME - VUID-vkCmdDraw-None-08114
I am not sure what to do here.

2022-11-23 13:34 UTC, spencer-lunarg commented on layers/descriptor_validation.cpp
> +                const VkAccelerationStructureNV as = reinterpret_cast<VkAccelerationStructureNV>(pDescriptorInfo->data.accelerationStructure);
CI is failing because this branch needs to be rebased (a bad test was fixed) also here

> 'reinterpret_cast': cannot convert from 'const VkDeviceAddress' to 'VkAccelerationStructureNV'

error is thrown on Windows Visual Studio builds

2022-11-23 13:39 UTC, spencer-lunarg commented on layers/parameter_validation_utils.cpp
> +            (!descriptor_buffer_features ||
You shouldn't need the extra `descriptor_buffer_features` here as the `descriptor_buffer_features &&` checks for non-null already

2022-11-23 13:41 UTC, spencer-lunarg commented on layers/pipeline_state.cpp
> +      descriptor_buffer_mode(!!(create_info.graphics.flags & VK_PIPELINE_CREATE_DESCRIPTOR_BUFFER_BIT_EXT)),
to be consistent with the other code can you change to

`descriptor_buffer_mode((create_info.graphics.flags & VK_PIPELINE_CREATE_DESCRIPTOR_BUFFER_BIT_EXT) != 0)`

2022-11-23 13:44 UTC, spencer-lunarg commented on layers/buffer_validation.cpp
> +            "VkPhysicalDeviceDescriptorBufferPropertiesEXT::samplerDescriptorBufferAddressSpaceSize or "
for these VUs please print out the sizes in the error message

2022-11-23 14:27 UTC, archimedus commented on layers/descriptor_validation.cpp
> +                const VkAccelerationStructureNV as = reinterpret_cast<VkAccelerationStructureNV>(pDescriptorInfo->data.accelerationStructure);
It does not fail me in VS2022. Which one does build system use?

Will replace to c-cast:
```
                const VkAccelerationStructureNV as = (VkAccelerationStructureNV)pDescriptorInfo->data.accelerationStructure;
```

2022-11-23 14:32 UTC, archimedus commented on layers/parameter_validation_utils.cpp
> +            (!descriptor_buffer_features ||
This is not obvious, thus I would stay with current null-check.

2022-11-23 14:37 UTC, archimedus commented on layers/pipeline_state.cpp
> +      descriptor_buffer_mode(!!(create_info.graphics.flags & VK_PIPELINE_CREATE_DESCRIPTOR_BUFFER_BIT_EXT)),
Will fix

2022-11-23 14:37 UTC, spencer-lunarg commented on layers/descriptor_validation.cpp
> +                                 "not equal to VK_DESCRIPTOR_TYPE_SAMPLER but the "
please use `string_VkDescriptorType` to print out the actual value in the error

2022-11-23 14:40 UTC, spencer-lunarg commented on layers/descriptor_validation.cpp
> +        setCount = std::min(setCount, static_cast<uint32_t>(pipeline_layout->set_layouts.size()));
I would be happy to change this to

```c++
// If the set count is to large, return instead of having to bound check for OOB errors
return skip;
```

2022-11-23 14:40 UTC, spencer-lunarg commented on layers/descriptor_validation.cpp
> +                             "] is not aligned to VkPhysicalDeviceDescriptorBufferPropertiesEXT::descriptorBufferOffsetAlignment",
print the value of both `descriptorBufferOffsetAlignment` and `pOffsets[i]` in error message

2022-11-23 14:41 UTC, spencer-lunarg commented on layers/descriptor_validation.cpp
> +    for (uint32_t i = 0; i < setCount; i++) {
should be able to combine both the `for (uint32_t i = 0; i < setCount; i++) {` together

2022-11-23 14:43 UTC, spencer-lunarg commented on layers/descriptor_validation.cpp
> +                             "] is greater than VkPhysicalDeviceDescriptorBufferPropertiesEXT::maxDescriptorBufferBindings",
please print both values to error message

2022-11-23 14:44 UTC, spencer-lunarg commented on layers/descriptor_validation.cpp
> +                         "vkCmdBindDescriptorBufferEmbeddedSamplersEXT(): set is greater than "
print values to error

2022-11-23 14:45 UTC, spencer-lunarg commented on layers/descriptor_validation.cpp
> +    for (uint32_t i=0 ; i< bufferCount; i++) {
merge other ` for (uint32_t i=0 ; i< bufferCount; i++) {` together

2022-11-23 14:45 UTC, spencer-lunarg commented on layers/descriptor_validation.cpp
> +bool CoreChecks::PreCallValidateCmdBindDescriptorBuffersEXT(
print values in errors where possible for all checks

2022-11-24 08:22 UTC, archimedus commented on layers/descriptor_validation.cpp
> +                                 "not equal to VK_DESCRIPTOR_TYPE_SAMPLER but the "
Will do.

2022-11-24 08:23 UTC, archimedus commented on layers/descriptor_validation.cpp
> +        setCount = std::min(setCount, static_cast<uint32_t>(pipeline_layout->set_layouts.size()));
Why? Current behavior seems reasonable: we validate what we can validate.

2022-11-24 09:02 UTC, spencer-lunarg commented on layers/descriptor_validation.cpp
> +        setCount = std::min(setCount, static_cast<uint32_t>(pipeline_layout->set_layouts.size()));
I guess the idea is `setCount` is a value passed in from the app, if debugging something below in the future might become misleading, but looking more into the scope of what is being checked, it should be fine

2022-11-24 10:17 UTC, archimedus commented
@spencer-lunarg 

I hope I fixed all issues pointed in latest push.

2022-11-28 16:55 UTC, jeremyg-lunarg approved these changes
+2 LGTM. All my concerns are addressed. @spencer-lunarg how about you?

2022-11-29 08:45 UTC, spencer-lunarg requested changes
Few nits I have left, but otherwise LGTM once resolved and rebased

2022-11-29 08:45 UTC, spencer-lunarg commented on layers/core_validation.cpp
> +            // TODO-08116 Descriptors in bound descriptor buffers, specified via vkCmdSetDescriptorBufferOffsetsEXT, must be valid
Please tie new TODO to issues (new system we are trying to enforce)

```suggestion
            // TODO Issue 4832 - VUID 08116 Descriptors in bound descriptor buffers, specified via vkCmdSetDescriptorBufferOffsetsEXT, must be valid
```

2022-11-29 08:45 UTC, spencer-lunarg commented on layers/buffer_validation.cpp
> +        const char *spec_message =
This is not needed, all Validation Messages print out the spec message by default, this is duplicating it

2022-11-29 08:45 UTC, spencer-lunarg commented on layers/core_validation.cpp
>      if (VK_PIPELINE_BIND_POINT_GRAPHICS == bind_point) {
The above don't have a `vkCmdDispatch` VUID, shouldn't all the above checks be moved into here?

2022-11-29 08:45 UTC, spencer-lunarg commented on layers/core_validation.cpp
> +                                   "If the descriptors used by the VkPipeline bound to the pipeline bind point were specified via "
Please prefix these error messages with the Vulkan command

```cpp
    "%s: If the descriptors used by the VkPipeline bound to the pipeline bind point were specified via "
    "vkCmdBindDescriptorSets, the bound VkPipeline must have been created without "
    "VK_PIPELINE_CREATE_DESCRIPTOR_BUFFER_BIT_EXT", function);
```

2022-11-29 08:45 UTC, spencer-lunarg commented on layers/descriptor_validation.cpp
> +                         "must: be enabled.");
nit:  not asciidoctor

```suggestion
                         "must be enabled.");
```

few other spots below too

2022-11-29 08:45 UTC, spencer-lunarg commented on layers/descriptor_validation.cpp
> +                                 "If usage includes VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT, address must be an address "
For the other ones below as well

```suggestion
                                 "vkCmdBindDescriptorBuffersEXT():  If usage includes VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT, address must be an address "
```

2022-11-29 08:45 UTC, spencer-lunarg commented on layers/descriptor_validation.cpp
> +                                     "If type is VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV and accelerationStructure is not 0, "
```suggestion
                                     "vkGetDescriptorEXT(): If type is VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV and accelerationStructure is not 0, "
```

2022-11-29 08:45 UTC, spencer-lunarg commented on layers/descriptor_validation.cpp
> +                             "dataSize must equal the size of a descriptor of type VkDescriptorGetInfoEXT::type "
For both of these errors append with `vkGetDescriptorEXT():` and print the sizes out for the user

2022-11-29 13:12 UTC, archimedus commented on layers/core_validation.cpp
> +                                   "If the descriptors used by the VkPipeline bound to the pipeline bind point were specified via "
Will do.

2022-11-29 14:21 UTC, spencer-lunarg commented on layers/core_validation.cpp
>      if (VK_PIPELINE_BIND_POINT_GRAPHICS == bind_point) {
ok, I see, this part is not the issue then

2022-11-29 14:24 UTC, spencer-lunarg commented on layers/drawdispatch.cpp
> +        descriptor_buffer_set_offset_missing = "VUID-vkCmdDraw-None-08117";
you are missing adding these 4 VUIDs for

- `VUID-vkCmdDispatch-None-0811*`
- `VUID-vkCmdDispatchIndirect-None-0811*`
- `VUID-vkCmdDispatchBase-None-0811*`
- `VUID-vkCmdTraceRaysNV-None-0811*`
- `VUID-vkCmdTraceRaysKHR-None-0811*`
- `VUID-vkCmdTraceRaysIndirectKHR-None-0811*` 
- `VUID-vkCmdTraceRaysIndirect2KHR-None-0811*`

2022-11-29 15:41 UTC, archimedus commented on layers/buffer_validation.cpp
> +        const char *spec_message =
Removed

2022-11-29 15:43 UTC, archimedus commented on layers/drawdispatch.cpp
> +        descriptor_buffer_set_offset_missing = "VUID-vkCmdDraw-None-08117";
Added in latest commit.

2022-11-29 18:51 UTC, jeremyg-lunarg commented
In order to keep this PR moving forward I've done a maintainer push to clear the merge conflicts. There are still test failures with the latest MockICD. I think these just started showing up because MockICD now supports the descriptor buffer extension.

To reproduce them you need to:

-  Pull and build the latest verison of [KhronosGroup/Vulkan-Tools](https://github.com/KhronosGroup/Vulkan-Tools)
- Set/export VK_ICD_FILENAMES=<full path to the VkICD_mock_icd.json file under Vulkan-Tools/build>
-  Run  `vk_layer_validation_tests --gtest_filter=*DescriptorBuffer*`

MockICD is weird because it says it supports all extensions but returns 0 for most/all features and properties. I'll add review comments on the failures I understand, but a lot of them are interactions with existing descriptor set / layout VUIDs that are not obvious to me

2022-11-29 19:06 UTC, jeremyg-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +        m_errorMonitor->VerifyFound();
```
Did not receive expected error 'VUID-VkDescriptorSetLayoutBinding-descriptorType-08004'
/home/jgebben/src/Vulkan-ValidationLayers/tests/vkerrormonitor.cpp:106: Failure
Failed
Validation Error: [ VUID-VkPipelineLayoutCreateInfo-descriptorType-03022 ] Object 0: handle = 0x561db4dcea60, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xd8bf598e | vkCreatePipelineLayout(): max per-stage sampler bindings count (2) exceeds device maxPerStageDescriptorUpdateAfterBindSamplers limit (0). The Vulkan spec states: The total number of descriptors with a descriptorType of VK_DESCRIPTOR_TYPE_SAMPLER and VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER accessible to any given shader stage across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceDescriptorIndexingProperties::maxPerStageDescriptorUpdateAfterBindSamplers (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPipelineLayoutCreateInfo-descriptorType-03022)
/home/jgebben/src/Vulkan-ValidationLayers/tests/vkerrormonitor.cpp:106: Failure
Failed
Validation Error: [ VUID-VkPipelineLayoutCreateInfo-pSetLayouts-03036 ] Object 0: handle = 0x561db4dcea60, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xd87c4910 | vkCreatePipelineLayout(): sum of sampler bindings among all stages (2) exceeds device maxDescriptorSetUpdateAfterBindSamplers limit (0). The Vulkan spec states: The total number of descriptors of the type VK_DESCRIPTOR_TYPE_SAMPLER and VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER accessible across all shader stages and across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceDescriptorIndexingProperties::maxDescriptorSetUpdateAfterBindSamplers (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPipelineLayoutCreateInfo-pSetLayouts-03036)
```

2022-11-29 19:06 UTC, jeremyg-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +        ASSERT_VK_SUCCESS(err);
```
Validation Error: [ VUID-VkPipelineLayoutCreateInfo-descriptorType-03022 ] Object 0: handle = 0x561db444bb10, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xd8bf598e | vkCreatePipelineLayout(): max per-stage sampler bindings count (1) exceeds device maxPerStageDescriptorUpdateAfterBindSamplers limit (0). The Vulkan spec states: The total number of descriptors with a descriptorType of VK_DESCRIPTOR_TYPE_SAMPLER and VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER accessible to any given shader stage across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceDescriptorIndexingProperties::maxPerStageDescriptorUpdateAfterBindSamplers (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPipelineLayoutCreateInfo-descriptorType-03022)
/home/jgebben/src/Vulkan-ValidationLayers/tests/vkerrormonitor.cpp:106: Failure
Failed
Validation Error: [ VUID-VkPipelineLayoutCreateInfo-pSetLayouts-03036 ] Object 0: handle = 0x561db444bb10, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xd87c4910 | vkCreatePipelineLayout(): sum of sampler bindings among all stages (1) exceeds device maxDescriptorSetUpdateAfterBindSamplers limit (0). The Vulkan spec states: The total number of descriptors of the type VK_DESCRIPTOR_TYPE_SAMPLER and VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER accessible across all shader stages and across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceDescriptorIndexingProperties::maxDescriptorSetUpdateAfterBindSamplers (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPipelineLayoutCreateInfo-pSetLayouts-03036)
/home/jgebben/src/Vulkan-ValidationLayers/tests/vklayertests_descriptor_renderpass_framebuffer.cpp:13089: Failure

```

2022-11-29 19:06 UTC, jeremyg-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +        ASSERT_VK_SUCCESS(err);
```
Validation Error: [ VUID-VkBufferCreateInfo-usage-08097 ] Object 0: handle = 0x561db46dc2b0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xba8ed18f | vkCreateBuffer(): Requested buffer size (4096) plus current total (0) is greater than specified in properties field samplerDescriptorBufferAddressSpaceSize (0). The Vulkan spec states: If usage includes VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT, creating this VkBuffer must not cause the total required space for all currently valid buffers using this flag on the device to exceed VkPhysicalDeviceDescriptorBufferPropertiesEXT::samplerDescriptorBufferAddressSpaceSize or VkPhysicalDeviceDescriptorBufferPropertiesEXT::descriptorBufferAddressSpaceSize (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkBufferCreateInfo-usage-08097)
/home/jgebben/src/Vulkan-ValidationLayers/tests/vkerrormonitor.cpp:106: Failure
Failed
Validation Error: [ VUID-VkBufferCreateInfo-usage-08097 ] Object 0: handle = 0x561db46dc2b0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xba8ed18f | vkCreateBuffer(): Requested buffer size (4096) plus current total (0) is greater than specified in properties field descriptorBufferAddressSpaceSize (0) The Vulkan spec states: If usage includes VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT, creating this VkBuffer must not cause the total required space for all currently valid buffers using this flag on the device to exceed VkPhysicalDeviceDescriptorBufferPropertiesEXT::samplerDescriptorBufferAddressSpaceSize or VkPhysicalDeviceDescriptorBufferPropertiesEXT::descriptorBufferAddressSpaceSize (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkBufferCreateInfo-usage-08097)
/home/jgebben/src/Vulkan-ValidationLayers/tests/vkerrormonitor.cpp:106: Failure
Failed
Validation Error: [ VUID-VkBufferCreateInfo-usage-08098 ] Object 0: handle = 0x561db46dc2b0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xe21d42c4 | vkCreateBuffer(): Requested buffer size (4096) plus current total (0) is greater than specified in properties field resourceDescriptorBufferAddressSpaceSize (0). The Vulkan spec states: If usage includes VK_BUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT, creating this VkBuffer must not cause the total required space for all currently valid buffers using this flag on the device to exceed VkPhysicalDeviceDescriptorBufferPropertiesEXT::resourceDescriptorBufferAddressSpaceSize or VkPhysicalDeviceDescriptorBufferPropertiesEXT::descriptorBufferAddressSpaceSize (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkBufferCreateInfo-usage-08098)
/home/jgebben/src/Vulkan-ValidationLayers/tests/vkerrormonitor.cpp:106: Failure
Failed
Validation Error: [ VUID-VkBufferCreateInfo-usage-08098 ] Object 0: handle = 0x561db46dc2b0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xe21d42c4 | vkCreateBuffer(): Requested buffer size (4096) plus current total (0) is greater than specified in properties field descriptorBufferAddressSpaceSize (0). The Vulkan spec states: If usage includes VK_BUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT, creating this VkBuffer must not cause the total required space for all currently valid buffers using this flag on the device to exceed VkPhysicalDeviceDescriptorBufferPropertiesEXT::resourceDescriptorBufferAddressSpaceSize or VkPhysicalDeviceDescriptorBufferPropertiesEXT::descriptorBufferAddressSpaceSize (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkBufferCreateInfo-usage-08098)

/home/jgebben/src/Vulkan-ValidationLayers/tests/vklayertests_descriptor_renderpass_framebuffer.cpp:13674: Failure

```

2022-11-29 19:06 UTC, jeremyg-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +        ASSERT_VK_SUCCESS(err);
```
Validation Error: [ VUID-VkPipelineLayoutCreateInfo-descriptorType-03022 ] Object 0: handle = 0x561db4d25fe0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xd8bf598e | vkCreatePipelineLayout(): max per-stage sampler bindings count (1) exceeds device maxPerStageDescriptorUpdateAfterBindSamplers limit (0). The Vulkan spec states: The total number of descriptors with a descriptorType of VK_DESCRIPTOR_TYPE_SAMPLER and VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER accessible to any given shader stage across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceDescriptorIndexingProperties::maxPerStageDescriptorUpdateAfterBindSamplers (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPipelineLayoutCreateInfo-descriptorType-03022)
/home/jgebben/src/Vulkan-ValidationLayers/tests/vkerrormonitor.cpp:106: Failure
Failed
Validation Error: [ VUID-VkPipelineLayoutCreateInfo-descriptorType-03023 ] Object 0: handle = 0x561db4d25fe0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf26ac9dd | vkCreatePipelineLayout(): max per-stage uniform buffer bindings count (1) exceeds device maxPerStageDescriptorUpdateAfterBindUniformBuffers limit (0). The Vulkan spec states: The total number of descriptors with a descriptorType of VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER and VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC accessible to any given shader stage across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceDescriptorIndexingProperties::maxPerStageDescriptorUpdateAfterBindUniformBuffers (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPipelineLayoutCreateInfo-descriptorType-03023)
/home/jgebben/src/Vulkan-ValidationLayers/tests/vkerrormonitor.cpp:106: Failure
Failed
Validation Error: [ VUID-VkPipelineLayoutCreateInfo-pSetLayouts-03036 ] Object 0: handle = 0x561db4d25fe0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xd87c4910 | vkCreatePipelineLayout(): sum of sampler bindings among all stages (1) exceeds device maxDescriptorSetUpdateAfterBindSamplers limit (0). The Vulkan spec states: The total number of descriptors of the type VK_DESCRIPTOR_TYPE_SAMPLER and VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER accessible across all shader stages and across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceDescriptorIndexingProperties::maxDescriptorSetUpdateAfterBindSamplers (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPipelineLayoutCreateInfo-pSetLayouts-03036)
/home/jgebben/src/Vulkan-ValidationLayers/tests/vkerrormonitor.cpp:106: Failure
Failed
Validation Error: [ VUID-VkPipelineLayoutCreateInfo-pSetLayouts-03037 ] Object 0: handle = 0x561db4d25fe0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x498f6d17 | vkCreatePipelineLayout(): sum of uniform buffer bindings among all stages (1) exceeds device maxDescriptorSetUpdateAfterBindUniformBuffers limit (0). The Vulkan spec states: The total number of descriptors of the type VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER accessible across all shader stages and across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceDescriptorIndexingProperties::maxDescriptorSetUpdateAfterBindUniformBuffers (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPipelineLayoutCreateInfo-pSetLayouts-03037)
/home/jgebben/src/Vulkan-ValidationLayers/tests/vklayertests_descriptor_renderpass_framebuffer.cpp:14077: Failure

```

2022-11-29 19:06 UTC, jeremyg-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +        m_errorMonitor->VerifyFound();
```
/home/jgebben/src/Vulkan-ValidationLayers/tests/vkerrormonitor.cpp:106: Failure
Failed
Validation Error: [ VUID-vkGetDescriptorEXT-dataSize-arraylength ] Object 0: handle = 0x561db4dabdf0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf6da95b8 | vkGetDescriptorEXT: parameter dataSize must be greater than 0. The Vulkan spec states: dataSize must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkGetDescriptorEXT-dataSize-arraylength)
/home/jgebben/src/Vulkan-ValidationLayers/tests/vkerrormonitor.cpp:162: Failure
Failed
Did not receive expected error 'VUID-VkDescriptorGetInfoEXT-type-08020'
/home/jgebben/src/Vulkan-ValidationLayers/tests/vkerrormonitor.cpp:162: Failure
Failed
Did not receive expected error 'VUID-VkDescriptorGetInfoEXT-type-08019'
/home/jgebben/src/Vulkan-ValidationLayers/tests/vkerrormonitor.cpp:106: Failure

```

2022-11-30 08:29 UTC, spencer-lunarg commented
@jeremyg-lunarg and @archimedus I assume all of these "failing" tests will be fixed once I get Profile Layers into the CI

I would be more than happy to add to all the failing tests, when I add the Profile Layers I plan grep the `TODO Issue 4867` and remove all of these

```c++
    // TODO Issue 4867 - MockICD doesn't return proper values
    if (IsPlatform(kMockICD)) {
        GTEST_SKIP() << "Test not supported by MockICD";
    }
```

2022-11-30 14:43 UTC, archimedus commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +        m_errorMonitor->VerifyFound();
> dataSize must be greater than 0
No such issue under Windows. MockICD issue.
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4828#issuecomment-1331801093

2022-11-30 14:43 UTC, archimedus commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +        ASSERT_VK_SUCCESS(err);
> max per-stage sampler bindings count (1) exceeds device maxPerStageDescriptorUpdateAfterBindSamplers limit (0)
No such issue under Windows. MockICD issue.
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4828#issuecomment-1331801093

2022-11-30 14:45 UTC, archimedus commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +        m_errorMonitor->VerifyFound();
> max per-stage sampler bindings count (2) exceeds device maxPerStageDescriptorUpdateAfterBindSamplers limit (0). 

No such issue under Windows. MockICD issue.
Resolved https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4828#issuecomment-1331801093

2022-11-30 14:46 UTC, archimedus commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +        ASSERT_VK_SUCCESS(err);
> vkCreatePipelineLayout(): max per-stage sampler bindings count (1) exceeds device maxPerStageDescriptorUpdateAfterBindSamplers limit (0)

No such issue under Windows. MockICD issue.
Resolved https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4828#issuecomment-1331801093

2022-11-30 14:47 UTC, archimedus commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +        ASSERT_VK_SUCCESS(err);
> Requested buffer size (4096) plus current total (0) is greater than specified in properties field samplerDescriptorBufferAddressSpaceSize (0).

No such issue under Windows. MockICD issue.
Resolved https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4828#issuecomment-1331801093

2022-11-30 15:13 UTC, spencer-lunarg approved these changes

2022-11-30 15:42 UTC, jeremyg-lunarg commented
It looks like there are still tests failing. I'm going to add a commit to revert the failing sections and then @spencer-lunarg can handle them as part of issue #4867

2022-11-30 17:44 UTC, jeremyg-lunarg commented
Test failure was on a single Android device in a test that shouldn't be related to this change, re-running.

2022-11-30 18:37 UTC, merged