layers: Fix image nullptr crash
KhronosGroup/Vulkan-ValidationLayers pull request #4839
Opened 2022-11-19 20:08 UTC by ziga-lunarg

This crash happened when `vkQueuePresentKHR ` returned `VK_SUBOPTIMAL_KHR`, not sure if I can write a test for this

2022-11-20 07:17 UTC, spencer-lunarg commented on layers/buffer_validation.cpp
> +        if (!subres_map) {
I am not sure where `pCB->image_layout_map` is actually being populated, but not sure why the `ImageSubresourceLayoutMap` would be null

2022-11-20 07:19 UTC, spencer-lunarg commented on layers/buffer_validation.cpp
> +        if (!subres_map) {
So this check is not being done in the `ExecuteCommands` calls for secondary buffer?

2022-11-21 21:52 UTC, juan-lunarg commented on tests/vklayertests_wsi.cpp
> +    VkPipelineColorBlendAttachmentState att_state = {}, att_state2 = {};
att_state2 isn't being used

```suggestion
    VkPipelineColorBlendAttachmentState att_state = {};
```

2022-11-22 22:06 UTC, juan-lunarg commented on tests/vklayertests_wsi.cpp
> +TEST_F(VkLayerTest, UseDestroyedSwapchain) {
I don't see any usage of `m_errorMonitor`. If that's the case then it belongs in the `tests/positive` directory

2022-11-22 22:16 UTC, ziga-lunarg commented on tests/vklayertests_wsi.cpp
> +TEST_F(VkLayerTest, UseDestroyedSwapchain) {
This is WIP, this test should fail, but it doesn't.

2022-11-28 16:09 UTC, jeremyg-lunarg commented on layers/core_validation.cpp
> +                            const auto &image_state = Get<IMAGE_STATE>(ivci.image);
This shouldn't be an auto &. We need to copy to ensure a reference is held on the IMAGE_STATE, otherwise it could be destroyed in a different thread. (This would be invalid vulkan but we need to guard against it)

2022-11-28 16:10 UTC, jeremyg-lunarg commented
> This crash happened when `vkQueuePresentKHR ` returned `VK_SUBOPTIMAL_KHR`, not sure if I can write a test for this

It almost seems like we need a "Mock Swapchain" to test things like this. Not sure how hard that would be.

2022-11-28 16:10 UTC, jeremyg-lunarg requested changes
-1, the shared_ptr & needs to be fixed.

2023-03-30 16:39 UTC, closed without merging