Use pythonic  "foo not in blah" instead of "not foo in blah"
KhronosGroup/Vulkan-ValidationLayers pull request #4864
Opened 2022-11-25 23:01 UTC by dneto0

This fixes a "pythonic" style checker warning in my downstream flows.

2022-11-26 07:17 UTC, spencer-lunarg commented
@dneto0 LGTM, same thing as other PR

1. append `scripts:` to commit message
2. how was this found?

2022-11-28 18:29 UTC, juan-lunarg requested changes
commit message fails CI

```
python3 ./scripts/check_code_format.py
```

2022-11-29 19:25 UTC, juan-lunarg approved these changes

2022-11-29 21:10 UTC, merged

2022-11-29 21:11 UTC, juan-lunarg commented
@dneto0 hope you don't mind but I amended your commit messages to get these python PRs in sooner.