Improve CONTRIBUTING.md  doc
KhronosGroup/Vulkan-ValidationLayers pull request #4865
Opened 2022-11-26 13:10 UTC by spencer-lunarg

- Clean up file to be as simple as possible to make easier to read for new users
- Add "TODO" and "Commenting out Code" section
- Describe review system

2022-11-26 14:14 UTC, ziga-lunarg approved these changes

2022-11-27 17:26 UTC, arno-lunarg commented on CONTRIBUTING.md
> +* Validation source code should be in a separate commit from the tests, unless there are interdependencies. The repo should compile and pass all tests after each commit.
Compile and pass all tests after each commit? It seems drastic

2022-11-27 17:32 UTC, arno-lunarg reviewed
LGTM! One comment about compilation/tests succeeding

2022-11-28 04:33 UTC, spencer-lunarg commented on CONTRIBUTING.md
> +* Validation source code should be in a separate commit from the tests, unless there are interdependencies. The repo should compile and pass all tests after each commit.
I would expect any commit to at least compile

I guess the goal of this is to say that any "partial" commit should still in theory work

2022-11-28 10:35 UTC, aitor-lunarg reviewed
I left a few comments on parts where I think there should be some discussion before proceeding with the merge since we would be committing to those. Other than that, looks good to me!

2022-11-28 10:35 UTC, aitor-lunarg commented on CONTRIBUTING.md
> +It is the maintainers goal for all issues to be assigned or triaged within one business day of their submission. If you choose
While I do think it would be ideal to have issues either assigned or triaged in a single day of their submission, I think it may put expectations too high for the public and adding extra pressure on having new issues processed when the team may be focused on something else

2022-11-28 10:35 UTC, aitor-lunarg commented on CONTRIBUTING.md
> +to work on an issue that is assigned, simply coordinate with the current assignee.
I do agree with this, but we also need to assign issues to the pool if we are not working on them (I'm looking at myself, but there's probably more people in the same boat). I think this should be stated somewhere, also, before unassigning to have the issue back in the pool, the assigned should leave some comments with findings or something about the current progress.

2022-11-28 10:35 UTC, aitor-lunarg commented on CONTRIBUTING.md
> +* Validation source code should be in a separate commit from the tests, unless there are interdependencies. The repo should compile and pass all tests after each commit.
I do also think that it should compile at least. Testing every single test when adding a new VUID seems excessive since there's CI to check for that, plus the user may not have all the configurations tests. On the other hand, we don't want to drown CI with changes that fail...

2022-11-28 11:06 UTC, spencer-lunarg commented on CONTRIBUTING.md
> +It is the maintainers goal for all issues to be assigned or triaged within one business day of their submission. If you choose
So for my "triaged" means

- First decide if actually a real issue (often people raise spec bugs and we need to tell them to move it to the correct repo)
- Next decide what to label it as (bug, incomplete VUID, nice-to-have, we are breaking ANGLE's build, etc)
- Decide how important it is (somethings are in nature going to take priority over othere)
- Label it with a GitHub tag and then assign to someone

The goal is not to have no action at all on an issue, want to at least show "we are aware of the issue" which is NOT the same as "we are going to fix it NOW"

You raised a good concern.... I will update what `triage` means in this context in the doc

2022-11-28 16:02 UTC, jeremyg-lunarg approved these changes
+1

2022-11-28 16:02 UTC, jeremyg-lunarg commented on CONTRIBUTING.md
> +All PR's must have been marked as `Approve` by 1 maintainer and have no outstanding request changes.
So we should be adding +1/+2 in comments when reviewing? Who is allowed to +2?  I like this idea, I wish github had more of gerrit's good features.

2022-11-28 16:13 UTC, mark-lunarg commented on CONTRIBUTING.md
> +* Validation source code should be in a separate commit from the tests, unless there are interdependencies. The repo should compile and pass all tests after each commit.
This requirement was chosen for a few reasons but one of the big ones is for `git bisect`.  Each commit should run and pass all tests, otherwise the needless test failures will make bisecting ineffective or impossible.  And, the discipline entailed is good for organizing changes anyway (but it does take more thought and effort -- interactive rebase is your friend).

2022-11-28 16:15 UTC, jeremyg-lunarg commented on CONTRIBUTING.md
> +All PR's must have been marked as `Approve` by 1 maintainer and have no outstanding request changes.
Yeah we need to set expectations on who can approve, and maybe point to a github group that defines the 'who'.  Making +2 = 'Approve button clicked by maintainer' works for me. -1/-2 seems harder. If something has an identifiable bug in it, I really want to put 'Changes requested' on it.  -2 seems like it happens fairly rarely and usually results in off line discussion with relevant parties.

2022-11-28 16:19 UTC, jzulauf-lunarg commented on CONTRIBUTING.md
> +* Validation source code should be in a separate commit from the tests, unless there are interdependencies. The repo should compile and pass all tests after each commit.
@mark-lunarg is exactly correct.  Changes must be bisectable.  There are times this couple test/validation changes (especially for a correction to validation logic) awkwardly, but bisectability is very important for regression debugging etc.

2022-11-28 18:33 UTC, juan-lunarg requested changes
I don't see where in our docs we tell contributors to run `check_code_format.py` before making a PR. We have instructions for running clang-format directly, but not the python script which also checks the commit

2023-03-07 01:15 UTC, Matraqueeheh approved these changes

2023-03-30 10:42 UTC, spencer-lunarg commented
Closing - going to redo in smaller PRs

2023-03-30 10:42 UTC, closed without merging