Move RTX tests to new files, some cleaning along the way
KhronosGroup/Vulkan-ValidationLayers pull request #4871
Opened 2022-11-28 18:30 UTC by arno-lunarg

Issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4857

- Move ray tracing tests to their own files, depending on their nature
- Prefix them all by `RayTracing`
- Prefix NVIDIA specific tests by `NVRayTracing`, and group them
- Unify usage of `Get{Device, Instance}ProcAddr`
- Use `InitFrameworkForRayTracingTest` when relevant
- Use `VkLayerTest::GetPhysicalDeviceProperties2` instead of manual pointer acquisition & dispatch

2022-11-28 18:59 UTC, juan-lunarg commented on tests/layer_validation_tests.h
> +    }
Instead of having `assert_proc` be a runtime variable, what about a template parameter?

```suggestion
    template <typename Proc, bool assert_proc = true>
    const Proc GetInstanceProcAddr(const char *proc_name) {
        auto proc = reinterpret_cast<Proc>(vk::GetInstanceProcAddr(instance(), proc_name));
        if constexpr (assert_proc) {
            assert(proc);
        }
        return proc;
    }
```

2022-11-28 18:59 UTC, juan-lunarg commented on tests/vklayertests_ray_tracing.cpp
> +    assert(vkBuildAccelerationStructuresKHR);
Use new helper function

2022-11-28 18:59 UTC, juan-lunarg commented on tests/layer_validation_tests.h
> +        auto proc = reinterpret_cast<Proc>(vk::GetDeviceProcAddr(device(), proc_name));
Ensure the template parameter is a function.

```suggestion
        static_assert(std::is_function_v<Proc>);
        auto proc = reinterpret_cast<Proc>(vk::GetDeviceProcAddr(device(), proc_name));
```

2022-11-28 18:59 UTC, juan-lunarg commented on tests/vklayertests_ray_tracing.cpp
> +    ASSERT_TRUE(vkGetPhysicalDeviceProperties2KHR != nullptr);
Should the new helper function use ASSERT_TRUE instead?

2022-11-28 20:45 UTC, arno-lunarg commented on tests/layer_validation_tests.h
> +    }
Yep this is better!

2022-11-28 20:46 UTC, arno-lunarg commented on tests/layer_validation_tests.h
> +        auto proc = reinterpret_cast<Proc>(vk::GetDeviceProcAddr(device(), proc_name));
Oh I did not know about that, will do

2022-11-28 20:48 UTC, arno-lunarg commented on tests/vklayertests_ray_tracing.cpp
> +    ASSERT_TRUE(vkGetPhysicalDeviceProperties2KHR != nullptr);
Yes it seems better

2022-11-28 20:53 UTC, arno-lunarg commented on tests/vklayertests_ray_tracing.cpp
> +    ASSERT_TRUE(vkGetPhysicalDeviceProperties2KHR != nullptr);
Oh but I cannot call ASSERT_TRUE in a function called in a test, it is a weird macro, it returns a value...

2022-11-28 21:16 UTC, juan-lunarg requested changes
Squash and rebase this PR into 1/2 commits. 12 commits is too much.

2022-11-28 21:16 UTC, juan-lunarg commented on tests/vklayertests_ray_tracing.cpp
> +    ASSERT_TRUE(vkGetPhysicalDeviceProperties2KHR != nullptr);
If that's the case then regular assert is fine for the helper function.

2022-11-28 21:16 UTC, juan-lunarg commented on tests/layer_validation_tests.h
> +    const Proc GetInstanceProcAddr(const char *proc_name, bool assert_proc = true) {
Use `[[nodiscard]]` for these new helper functions

```suggestion
     [[nodiscard]]  const Proc GetInstanceProcAddr(const char *proc_name, bool assert_proc = true) {
```

2022-11-28 21:19 UTC, mark-lunarg commented
Number of commits is fine, the smaller the better as long as they're grouped by functionality and are atomic in that they'll run and pass CI.

2022-11-28 21:28 UTC, juan-lunarg commented
> Number of commits is fine, the smaller the better as long as they're grouped by functionality and are atomic in that they'll run and pass CI.

I agree. I just looked at the recent commits and saw not each one is atomic and passes CI. Figured it'd be easier to just squash into 1 or 2.

2022-11-29 05:17 UTC, spencer-lunarg commented on tests/vklayertests_ray_tracing.cpp
> +    ASSERT_TRUE(vkGetPhysicalDeviceProperties2KHR != nullptr);
For now this is fine IMO, we do this all over, it is on my radar to fix across everywhere with a better system

2022-11-29 05:23 UTC, spencer-lunarg commented on tests/vklayertests_ray_tracing.cpp
> +    ASSERT_TRUE(vkGetPhysicalDeviceProperties2KHR != nullptr);
nvm, already added the logic I see, expands the scope of this PR a bit, but I think it is not too big of a change so ok with it

2022-11-29 05:26 UTC, spencer-lunarg commented
> Number of commits is fine, the smaller the better as long as they're grouped by functionality and are atomic in that they'll run and pass CI.

I agree, but also guess I feel this is on the verge of being too small IMO where you have to do extra bisect for overly small changes, also no reason IMO to add 2 commit for the function implementation and also the usage, when I look at a git blame of when a function is added, I want to see where it was initially used right away too

For now I am ok with it, but for example I would have grouped this PR as

- `test: Add new test files for ray tracing` (creating the file and just doing a `move` on the tests and the "grouping")
- `tests: Use InitFrameworkForRayTracingTest`
- `tests: Add VkLayerTest::Get***ProcAddr` (**both** creating and using it)
- `tests: Make RTX Tests consistent` (adding the spaces, etx)

2022-11-29 05:28 UTC, spencer-lunarg approved these changes
Nice cleanup of these tests into their own spot (will also make future RTX PR much nicer!). Still want @juan-lunarg code/git comments resolved first, but otherwise the LGTM!

2022-11-29 10:56 UTC, arno-lunarg commented
I consolidated the commits, there are 6 now. 
Trying to fixup the "group NV tests" into the first "add new RT tests files" commit gives me horrible merge issues because of the following "Use  InitFrameworkForRayTracingTest" commit. I could merge this commit into the first one, but I'd rather not, they solve different problems. 
There is still a commit for the off by one error, because again it is unrelated to the other ones.

Still, each commit should compile, and pass the tests now.

2022-11-29 14:28 UTC, merged