Fix vkExportMetalObjectsExt
KhronosGroup/Vulkan-ValidationLayers pull request #4878
Opened 2022-11-29 20:52 UTC by juan-lunarg

closes #4873

2022-11-29 20:54 UTC, juan-lunarg commented on layers/generated/layer_chassis_dispatch.cpp
> -    layer_data->device_dispatch_table.ExportMetalObjectsEXT(device, (VkExportMetalObjectsInfoEXT*)local_pMetalObjectsInfo);
Currently marked as a draft PR, since I'm not sure my new DispatchExportMetalObjectsEXT is safe.

2022-11-29 20:55 UTC, juan-lunarg commented on tests/positive/other.cpp
> +TEST_F(VkPositiveLayerTest, ExportMetalObjectsNotNull) {
I've verified the regression with this test. And verified this fixes the issue on a MacBook Pro that was lent to me.

2022-11-29 21:51 UTC, mark-lunarg requested changes
Sorry I was so confusing with my advice yesterday -- let me know what additional information I can supply.

2022-11-29 21:51 UTC, mark-lunarg commented on layers/generated/layer_chassis_dispatch.cpp
> +        layer_data->device_dispatch_table.ExportMetalObjectsEXT(device, pMetalObjectsInfo);
I think this function needs to contain the generated code that the original contained -- if any structure in the pNext chain of `vkExportMetalObjectsEXT()` has a handle in it, the display driver won't know what it is and might crash.  I think the old code needs to be copied back in, and then after the dispatch call is made, you'd need to copy the appropriate `MTLXxx_id` from the temporary structure _back_ into the original pMetalObjectsInfo structure.  This thing is so crazy overloaded (16 possible pNext structure types!) that hopefully there's a clever way to do this, but it might just be a huge loop/switch statement.

2022-11-29 21:51 UTC, mark-lunarg commented on tests/positive/other.cpp
> +    auto deviceInfo = LvlInitStruct<VkExportMetalDeviceInfoEXT>();
I think you might've picked the one `pNext` struct for this guy that doesn't have a VkObject handle in it.  For instance, the `VkExportMetalCommandQueueInfoEXT` structure has a `VkQueue` that would need to be unwrapped before calling down to the driver.  Thanks Apple!

2022-11-29 22:04 UTC, Tony-LunarG commented on layers/generated/layer_chassis_dispatch.cpp
> +        layer_data->device_dispatch_table.ExportMetalObjectsEXT(device, pMetalObjectsInfo);
I think you are going to run into handle wrapping issues this way.  For instance, if pMetalObjectsInfo.pNext points to a VkExportMetalTextureInfoEXT, the image or imageview or bufferview parameter will have been wrapped when it was created and needs to be unwrapped before sending it to the driver.

2022-11-29 22:07 UTC, Tony-LunarG commented on layers/generated/layer_chassis_dispatch.cpp
> +        layer_data->device_dispatch_table.ExportMetalObjectsEXT(device, pMetalObjectsInfo);
Or what Mark said...

2022-11-30 17:52 UTC, juan-lunarg commented on tests/positive/other.cpp
> +TEST_F(VkPositiveLayerTest, ExportMetalObjects) {
This test will currently fail to pass. But that's fine for now.

2022-11-30 17:53 UTC, juan-lunarg commented on layers/generated/layer_chassis_dispatch.cpp
> +        layer_data->device_dispatch_table.ExportMetalObjectsEXT(device, pMetalObjectsInfo);
I'll handle this in another PR. I'm trying to figure out a good way to handle this robustly.

2022-11-30 17:54 UTC, juan-lunarg commented on tests/positive/other.cpp
> +    auto deviceInfo = LvlInitStruct<VkExportMetalDeviceInfoEXT>();
In my next PR I'll add more to the ExportMetalObjects test

2022-11-30 18:11 UTC, mark-lunarg requested changes
As an outside observer it looks like this is two unrelated issues?  Let's split this into separate PRs, one for the MacOS build fix (prolly GTG as-is) and another for the ExportMetalObjects stuff, which we can leave WIP until that's covered.

2022-12-01 01:12 UTC, closed without merging