layers: Track input assembly state at pre_raster_state
KhronosGroup/Vulkan-ValidationLayers pull request #4889
Opened 2022-12-01 06:18 UTC by zzoon

Currently the validation layer can't judge if 00736 is being kept correctly because pre_raster_state doesn't have the input assembly state.

2022-12-01 08:48 UTC, spencer-lunarg commented
For record keeping - This is an internal issue https://gitlab.khronos.org/vulkan/vulkan/-/issues/3300

2022-12-01 08:55 UTC, spencer-lunarg approved these changes
This looks good to me, but before merging is there a CTS tests or something related that this fixes?

2022-12-02 00:17 UTC, zzoon commented
> This looks good to me, but before merging is there a CTS tests or something related that this fixes?
Yeah. https://gitlab.khronos.org/Tracker/vk-gl-cts/-/issues/4146 

> For record keeping - This is an internal issue https://gitlab.khronos.org/vulkan/vulkan/-/issues/3300
Thanks. I didn't notice when I make this PR.
We probably need to wait for the conclusion of the issue?

2022-12-08 18:19 UTC, ncesario-lunarg requested changes
This does not seem correct. My understanding is that each sub-state is disjoint from every other sub-state. If 00736 requires pre-raster _and_ vertex-input state, then we should be checking that each of those states are present. It may be the case that check isn't being made for a linked pipeline, and that would need to be fixed differently. We also need a test for 00736 when using graphics pipeline libraries (I don't think one currently exists).

If you supply `pInputAssemblyState` when creating a pre-raster library, I think it should be ignored (or maybe an error?). Is that correct @Tobski?

2022-12-08 18:37 UTC, ncesario-lunarg commented
I think a simple fix for this is to update the 00736 condition to:
```cpp
if (has_control && has_eval && pipeline.vertex_input_state && pipeline.pre_raster_state && (!ia_state || ia_state->topology != VK_PRIMITIVE_TOPOLOGY_PATCH_LIST)) {
```
I'll create a test to try this out.

2022-12-08 23:17 UTC, ncesario-lunarg commented
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4936 should address the problem and adds a test that reproduced the original issue.

2022-12-09 05:02 UTC, ncesario-lunarg commented
@zzoon Would you be able to try out #4936 and see if that resolves your issue?

2023-01-03 08:43 UTC, zzoon commented
> @zzoon Would you be able to try out #4936 and see if that resolves your issue?

Sorry about late reply, I got back from holidays.

Yeah I think your approach makes sense. 

Closing this issue.

2023-01-03 08:43 UTC, closed without merging