layers: Fix descriptor buffer VUIDs 08115 and 08117
KhronosGroup/Vulkan-ValidationLayers pull request #4918
Opened 2022-12-05 22:05 UTC by jeremyg-lunarg

These 2 VUIDs are about which pipelines are compatible with vkCmdBindDescriptorSets() or vkCmdSetDescriptorBufferOffsetsEXT(). The old code was looking at state set by vkCmdBindDescriptorBuffersEXT(). It should be valid to have descriptors bound but not used to allow switching back and forth between pipelines that use descriptor sets and descriptor buffers.

Fixes #4913

2022-12-05 22:06 UTC, jeremyg-lunarg commented
This is a draft because I still need to make a unit test for these 2 VUIDs, even if this PR isn't correct.

2022-12-06 14:42 UTC, archimedus commented
> @archimedus I think you added the descriptor_buffer state stuff - are you able to look at this?

I am on it.

2022-12-07 13:52 UTC, archimedus commented
@jeremyg-lunarg 

The code you propose is definitely better and fixes the issue. I would write following tests for these VUIDs:

// Test for 08115
pdb = createpipeline(flags | VK_PIPELINE_CREATE_DESCRIPTOR_BUFFER_BIT_EXT)
begincmdbuffer
vkCmdBindDescriptorSets(pdb)
vkCmdDraw()
endcmdbuffer

// Test for 08117
pds = createpipeline(flags & ~VK_PIPELINE_CREATE_DESCRIPTOR_BUFFER_BIT_EXT)
begincmdbuffer
vkCmdSetDescriptorBufferOffsetsEXT(pds)
vkCmdBindDescriptorBuffersEXT(pds)
vkCmdDraw()
endcmdbuffer

If you didn't start writing the tests I can do that.

2022-12-07 14:16 UTC, jeremyg-lunarg commented
> If you didn't start writing the tests I can do that.

I haven't been able to start yet and that would be greatly appreciated.  Thanks!

2022-12-07 18:31 UTC, juan-lunarg requested changes

2022-12-07 18:31 UTC, juan-lunarg commented on layers/state_tracker.cpp
> +    }
Use [insert](https://en.cppreference.com/w/cpp/container/vector/insert) instead for succinctness.

2022-12-07 18:31 UTC, juan-lunarg commented on layers/state_tracker.cpp
> +    cb_state->descriptor_buffer_binding_info.reserve(bufferCount);
Since clear doesn't change the capacity of the vector, the reserve call isn't needed.

```suggestion
```

2022-12-07 18:46 UTC, jeremyg-lunarg commented on layers/cmd_buffer_state.cpp
> +void CMD_BUFFER_STATE::PushDescriptorSetState(VkPipelineBindPoint pipelineBindPoint, PIPELINE_LAYOUT_STATE &pipeline_layout,
wow I can't believe this compiles as-is.

2022-12-07 18:51 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +    }
Wouldn't this be less succinct since I need to supply an iterator to insert()?

2022-12-07 18:58 UTC, jeremyg-lunarg commented on layers/cmd_buffer_state.cpp
> +void CMD_BUFFER_STATE::PushDescriptorSetState(VkPipelineBindPoint pipelineBindPoint, PIPELINE_LAYOUT_STATE &pipeline_layout,
looks like it wasn't const in the header but it can and should be.

2022-12-07 18:58 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +    }
switched to use resize() + indexing, which is much more concise

2022-12-08 15:49 UTC, archimedus commented
> I haven't been able to start yet and that would be greatly appreciated. Thanks!

I prepared tests in https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/b57df5b92392c9cf9f20fb331549f5fd72228662 , though it seems it needs to be retargeted (will do tomorrow)  . Feel free to retarget or just copy-paste tests from vklayertests_descriptor_renderpass_framebuffer.cpp.

2022-12-08 16:01 UTC, jeremyg-lunarg commented
> > I haven't been able to start yet and that would be greatly appreciated. Thanks!
> 
> I prepared tests in [b57df5b](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/b57df5b92392c9cf9f20fb331549f5fd72228662) , though it seems it needs to be retargeted (will do tomorrow) . Feel free to retarget or just copy-paste tests from vklayertests_descriptor_renderpass_framebuffer.cpp.

Thanks, I'll pull them over to this PR today

2022-12-08 16:44 UTC, juan-lunarg requested changes

2022-12-08 16:44 UTC, juan-lunarg commented on layers/cmd_buffer_state.cpp
> +    }
Why is `last_set_index` needed?

```suggestion
    // Resize binding arrays
    if (last_binding_index >= last_bound.per_set.size()) {
        last_bound.per_set.resize(required_size);
    }
```

2022-12-08 16:44 UTC, juan-lunarg commented on layers/core_validation.cpp
> +        const auto &ds = last_bound.per_set[i];
range-based for loop

```suggestion
    for (const auto &ds : last_bound.per_set) {
```

2022-12-08 16:44 UTC, juan-lunarg commented on layers/core_validation.cpp
> +        if (pipeline.active_slots.size() > 0 && !IsBoundSetCompat(pipeline.max_active_slot, last_bound, *pipeline_layout)) {
```suggestion
        if (!pipeline.active_slots.empty() && !IsBoundSetCompat(pipeline.max_active_slot, last_bound, *pipeline_layout)) {
```

2022-12-08 16:44 UTC, juan-lunarg commented on layers/pipeline_state.h
> +                  (*(last_bound.per_set[set].compat_id_for_set) == *(pipeline_layout.set_compat_ids[set]));
The bool isn't needed, return the expression directly.

2022-12-08 16:44 UTC, juan-lunarg commented on layers/state_tracker.cpp
> +        cb_state->PushDescriptorSetState(template_ci.pipelineBindPoint, *layout_data, set,
Looks like layout_data could be nullptr based on line 4268

2022-12-08 17:07 UTC, jeremyg-lunarg commented on layers/pipeline_state.h
> +                  (*(last_bound.per_set[set].compat_id_for_set) == *(pipeline_layout.set_compat_ids[set]));
Based on the comment in IsPipelineLayoutSetCompat() about wanting the bool to debug this expression, I'm going to leave this one that way too (and copy the comment)

2022-12-08 17:23 UTC, juan-lunarg commented on layers/pipeline_state.h
> +                  (*(last_bound.per_set[set].compat_id_for_set) == *(pipeline_layout.set_compat_ids[set]));
It may be worth breaking up this function into multiple bools for readability/debugability.

2022-12-08 17:27 UTC, jeremyg-lunarg commented on layers/pipeline_state.h
> +                  (*(last_bound.per_set[set].compat_id_for_set) == *(pipeline_layout.set_compat_ids[set]));
Yeah I might as well since I'm touching it.

2022-12-08 18:43 UTC, juan-lunarg requested changes

2022-12-08 18:43 UTC, juan-lunarg commented on layers/pipeline_state.h
> +    if (a && b) {
Avoid nested if statement.

```suggestion
    if (a == nullptr || b == nullptr) { return false; }
```

2022-12-08 18:43 UTC, juan-lunarg commented on layers/state_tracker.cpp
> +    if (template_state && layout_data) {
Avoid code indentation for readability.

```suggestion
    if (template_state == nullptr || layout_data == nullptr) { return; }
```

2022-12-08 18:43 UTC, juan-lunarg commented on layers/state_tracker.cpp
> +    }
```suggestion
    std::copy(pBindingInfos, pBindingInfos + bufferCount, cb_state->descriptor_buffer_binding_info.data());
```

2022-12-08 18:43 UTC, juan-lunarg commented on layers/cmd_buffer_state.cpp
> +        push_descriptor_cleanup(set_info.bound_descriptor_set);  // TODO
TODO?

2022-12-08 18:43 UTC, juan-lunarg commented on layers/cmd_buffer_state.cpp
> +    // We need this three times in this function, but nowhere else
```suggestion
    // We need this two times in this function, but nowhere else
```

2022-12-08 18:43 UTC, juan-lunarg commented on layers/state_tracker.cpp
> +    cb_state->UpdateLastBoundDescriptorSets(pipelineBindPoint, *pipeline_layout, firstSet, setCount, pDescriptorSets, no_push_desc,
Potential nullptr dereference

```suggestion
    if (pipeline_layout == nullptr) { return; }
    
    cb_state->UpdateLastBoundDescriptorSets(pipelineBindPoint, *pipeline_layout, firstSet, setCount, pDescriptorSets, no_push_desc,
```

2022-12-08 18:43 UTC, juan-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    buffCI.usage = VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT | VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT;
`VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT` is used but `VK_KHR_BUFFER_DEVICE_ADDRESS_EXTENSION_NAME` was listed as an optional extension.

2022-12-08 19:04 UTC, juan-lunarg commented on layers/cmd_buffer_state.cpp
> +    // We need this three times in this function, but nowhere else
Considering this lambda is used in 2 different functions now, it may be worth making into it's own static function.

2022-12-08 19:23 UTC, juan-lunarg requested changes

2022-12-08 19:23 UTC, juan-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +TEST_F(VkLayerTest, DescriptorBufferIncosistentBuffer) {
```suggestion
TEST_F(VkLayerTest, DescriptorBufferInconsistentBuffer) {
```

2022-12-08 19:23 UTC, juan-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +TEST_F(VkLayerTest, DescriptorBufferIncosistentSet) {
```suggestion
TEST_F(VkLayerTest, DescriptorBufferInconsistentSet) {
```

2022-12-08 19:23 UTC, juan-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    };
Use std::array

2022-12-08 19:23 UTC, juan-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +        vk::GetDeviceProcAddr(m_device->device(), "vkCmdSetDescriptorBufferOffsetsEXT"));
ASSERT_TRUE that the function pointers aren't nullptr

2022-12-08 19:23 UTC, juan-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    auto features2 = LvlInitStruct<VkPhysicalDeviceFeatures2KHR>(&buffer_device_address_features);
Is this extension needed? I don't see it used at all, unlike the prior test.

2022-12-08 19:23 UTC, juan-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    };
use std::array

2022-12-08 19:33 UTC, ncesario-lunarg commented on layers/pipeline_state.h
> +    if (a && b) {
In general I think we avoid the `== nullptr` as we use a lot of smart pointers, and this way we can take advantage of `operator bool` if the type changes.

2022-12-08 20:21 UTC, jeremyg-lunarg commented on layers/pipeline_state.h
> +    if (a && b) {
I was under the impression that we were trying to *not* use `== nullptr` for checks like this.

2022-12-08 20:33 UTC, juan-lunarg commented on layers/pipeline_state.h
> +    if (a && b) {
I updated the suggestion to reflect that.

2022-12-08 20:54 UTC, jeremyg-lunarg commented on layers/cmd_buffer_state.cpp
> +    // We need this three times in this function, but nowhere else
Yeah. done.

2022-12-08 21:03 UTC, jeremyg-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    auto features2 = LvlInitStruct<VkPhysicalDeviceFeatures2KHR>(&buffer_device_address_features);
VK_EXT_descriptor_buffer requires VK_EXT_buffer_device_address, which is why these tests can get away with being inconsistent.

2022-12-08 22:52 UTC, juan-lunarg requested changes

2022-12-08 22:52 UTC, juan-lunarg commented on layers/cmd_buffer_state.cpp
> +
```suggestion
```

2022-12-08 22:52 UTC, juan-lunarg commented on layers/pipeline_state.h
> +    if ((set >= a->set_compat_ids.size()) && (set >= b->set_compat_ids.size())) {
Minor logic issue.

```suggestion
    if ((set >= a->set_compat_ids.size()) || (set >= b->set_compat_ids.size())) {
```

2022-12-08 23:01 UTC, jeremyg-lunarg commented on layers/pipeline_state.h
> +    if ((set >= a->set_compat_ids.size()) && (set >= b->set_compat_ids.size())) {
that's more than minor!

2022-12-08 23:23 UTC, juan-lunarg approved these changes
LGTM

2022-12-08 23:40 UTC, jeremyg-lunarg commented
> LGTM

Thanks for the thorough reviewing. I'm making a separate PR to clean up the other tests.

2022-12-08 23:52 UTC, juan-lunarg commented
> Thanks for the thorough reviewing. I'm making a separate PR to clean up the other tests.

No worries. I tried to run the tests as a double check but my local system doesn't support the extension you are testing.

2022-12-09 00:28 UTC, merged