layers: Fix 00736 trigger
KhronosGroup/Vulkan-ValidationLayers pull request #4936
Opened 2022-12-08 23:17 UTC by ncesario-lunarg

00736 should only be triggered when vertex input state (not just
pre-raster state) is present.

2022-12-09 03:16 UTC, spencer-lunarg approved these changes

2022-12-09 17:39 UTC, juan-lunarg requested changes
minor nitpicks

2022-12-09 17:39 UTC, juan-lunarg commented on tests/vklayertests_graphics_library.cpp
> +    VkPipeline libs[4] = {
Use std::array

2022-12-09 17:39 UTC, juan-lunarg commented on tests/vklayertests_graphics_library.cpp
> +    VkPipelineTessellationStateCreateInfo tsci{VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO, nullptr, 0, 3};
Use LvlInitStruct

2022-12-09 17:39 UTC, juan-lunarg commented on tests/vklayertests_graphics_library.cpp
> +        pre_raster_lib.InitPreRasterLibInfoFromContainer(shaders);
Why are we creating a std::vector here? If it's because thats what `InitPreRasterLibInfoFromContainer` requires, then that should be changed to use a layer_data::span to avoid allocations.

2022-12-12 20:18 UTC, ncesario-lunarg commented on tests/vklayertests_graphics_library.cpp
> +    VkPipelineTessellationStateCreateInfo tsci{VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO, nullptr, 0, 3};
Copy paste error on my part.

2022-12-12 20:40 UTC, ncesario-lunarg commented on tests/vklayertests_graphics_library.cpp
> +        pre_raster_lib.InitPreRasterLibInfoFromContainer(shaders);
Nope, this can be a `std::array` :)

2022-12-12 20:47 UTC, juan-lunarg requested changes
Use CTAD (Class template argument deduction)  with std::array

2022-12-12 20:47 UTC, juan-lunarg commented on tests/vklayertests_graphics_library.cpp
> +        std::array<decltype(vs_stage.stage_ci), 2> shaders = {vs_stage.stage_ci, tcs_stage.stage_ci};
```suggestion
        const std::array shaders = {vs_stage.stage_ci, tcs_stage.stage_ci};
```

2022-12-12 20:47 UTC, juan-lunarg commented on tests/vklayertests_graphics_library.cpp
> +        std::array<decltype(vs_stage.stage_ci), 2> shaders = {vs_stage.stage_ci, tes_stage.stage_ci};
```suggestion
        const std::array shaders = {vs_stage.stage_ci, tes_stage.stage_ci};
```

2022-12-12 20:47 UTC, juan-lunarg commented on tests/vklayertests_graphics_library.cpp
> +    std::vector<decltype(vs_stage.stage_ci)> tess_shaders = {vs_stage.stage_ci, tcs_stage.stage_ci, tes_stage.stage_ci};
```suggestion
    const std::array tess_shaders = {vs_stage.stage_ci, tcs_stage.stage_ci, tes_stage.stage_ci};
```

2022-12-13 20:24 UTC, ncesario-lunarg commented on tests/vklayertests_graphics_library.cpp
> +        std::array<decltype(vs_stage.stage_ci), 2> shaders = {vs_stage.stage_ci, tcs_stage.stage_ci};
Didn't realize this was in C++17; nice!

2022-12-13 22:28 UTC, juan-lunarg approved these changes
:+1:

2022-12-14 04:53 UTC, merged