layers: Fix 06887 to check stencil write mask
KhronosGroup/Vulkan-ValidationLayers pull request #4937
Opened 2022-12-09 07:54 UTC by spencer-lunarg

closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4921

The spec was updated in 1.3.237 to have the VU check the `writeMask` (static or dynamic)

2022-12-09 09:28 UTC, arno-lunarg commented on layers/core_validation.cpp
> +                    ((ds_state->front.failOp == VK_STENCIL_OP_KEEP) && (ds_state->front.passOp != VK_STENCIL_OP_KEEP) &&
I think `ds_state->front.passOp != VK_STENCIL_OP_KEEP` should be `ds_state->front.passOp == VK_STENCIL_OP_KEEP`

2022-12-09 09:58 UTC, arno-lunarg requested changes
LGTM, aside one thing that probably needs to be fixed

2022-12-10 04:03 UTC, spencer-lunarg commented on layers/core_validation.cpp
> +                    ((ds_state->front.failOp == VK_STENCIL_OP_KEEP) && (ds_state->front.passOp != VK_STENCIL_OP_KEEP) &&
yes, thanks for catching this!!!, such an awful typo on my part

2022-12-11 19:14 UTC, arno-lunarg approved these changes

2022-12-12 03:21 UTC, merged