Split DS Image layout VU and add missing attachment layout VU
KhronosGroup/Vulkan-ValidationLayers pull request #4950
Opened 2022-12-12 14:47 UTC by spencer-lunarg

- Moves the code to the source files instead of headers
- Adds all the missing `VUID-VkAttachmentDescription2-*` that map to a `VUID-VkAttachmentDescription-*`
- label `VUID-VkAttachmentDescription2-format-06247` and `VUID-VkAttachmentDescription2-format-06248`
- Add
  - `VUID-VkAttachmentDescription-format-06242`
  - `VUID-VkAttachmentDescription-format-06243`
  - `VUID-VkAttachmentDescription2-format-06249`
  - `VUID-VkAttachmentDescription2-format-06250`
  - `VUID-VkAttachmentDescription-synchronization2-06908`
  - `VUID-VkAttachmentDescription-synchronization2-06909`
  - `VUID-VkAttachmentDescription2-synchronization2-06908`
  - `VUID-VkAttachmentDescription2-synchronization2-06909`

2022-12-12 19:29 UTC, jeremyg-lunarg approved these changes
LGTM / +2

2022-12-12 19:29 UTC, jeremyg-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    AddRequiredExtensions(VK_KHR_CREATE_RENDERPASS_2_EXTENSION_NAME);
this tests requires renderpass2 and vulkan 1.3. Couldn't it just require 1.3?

2022-12-12 20:20 UTC, juan-lunarg requested changes
minor nitpicks

2022-12-12 20:20 UTC, juan-lunarg commented on layers/parameter_validation_utils.cpp
> +            if (attachment_description_stencil_layout->stencilInitialLayout == VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL ||
Create helper variables. Consistent with above code and helps readability.

```suggestion
            const VkImageLayout stencilInitialLayout = attachment_description_stencil_layout->stencilInitialLayout;
            const VkImageLayout stencilFinalLayout = attachment_description_stencil_layout->stencilFinalLayout;
            if (stencilInitialLayout == VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL ||
```

2022-12-12 20:20 UTC, juan-lunarg commented on layers/parameter_validation_utils.cpp
> +    bool use_rp2 = (rp_version == RENDER_PASS_VERSION_2);
```suggestion
    const bool use_rp2 = (rp_version == RENDER_PASS_VERSION_2);
```

2022-12-12 20:20 UTC, juan-lunarg commented on layers/parameter_validation_utils.cpp
> +    const char *vuid;
```suggestion
    const char *vuid = nullptr;
```

2022-12-13 06:33 UTC, spencer-lunarg commented on layers/parameter_validation_utils.cpp
> +            if (attachment_description_stencil_layout->stencilInitialLayout == VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL ||
This part was not touched in the copy over, but agree should be approved while here!

2022-12-13 06:40 UTC, spencer-lunarg commented on tests/vklayertests_descriptor_renderpass_framebuffer.cpp
> +    AddRequiredExtensions(VK_KHR_CREATE_RENDERPASS_2_EXTENSION_NAME);
yes, but `TestRenderPassCreate` had a bug, fixed and removed this `AddRequiredExtensions`

2022-12-13 17:08 UTC, juan-lunarg approved these changes

2022-12-13 22:58 UTC, merged