corechecks: Fix VUID 08049
KhronosGroup/Vulkan-ValidationLayers pull request #4953
Opened 2022-12-12 21:11 UTC by jeremyg-lunarg

This check had a copy / paste error, which was found by a 'set but not used' warning from clang-15.

2022-12-12 21:12 UTC, jeremyg-lunarg commented
FYI @archimedus, I can't add you as a reviewer for some reason.

2022-12-12 21:31 UTC, juan-lunarg requested changes

2022-12-12 21:31 UTC, juan-lunarg commented on layers/descriptor_validation.cpp
> +                         "vkCmdBindDescriptorBuffersEXT(): Number of sampler buffers is %" PRIu32
The message needs be updated as well, it's currently warns about sample buffers.

2022-12-12 21:59 UTC, juan-lunarg approved these changes

2022-12-13 06:32 UTC, spencer-lunarg approved these changes

2022-12-13 10:10 UTC, stu-s approved these changes

2022-12-13 14:55 UTC, merged