layers: Validate framebuffer when using gl_Layer
KhronosGroup/Vulkan-ValidationLayers pull request #4978
Opened 2022-12-19 19:02 UTC by juan-lunarg

closes #3019

2022-12-19 19:05 UTC, juan-lunarg commented
Here is the official doc for [gl_Layer](https://registry.khronos.org/OpenGL-Refpages/gl4/html/gl_Layer.xhtml) for reference.

As stated in the doc: "In the geometry language, gl_Layer is used to select a specific layer (or face and layer of cube map) in a multi-layer framebuffer attachment."

Which implies it shouldn't be legal to use gl_Layer when using a single-layer framebuffer attachment. Which aligns with what was originally reported in https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3019

2022-12-19 19:09 UTC, juan-lunarg commented on layers/pipeline_state.h
> +    bool WritesToGLLayer() const {
Wasn't sure how to handle the function name. Would `WriteTo_gl_layer()` be preferred?

2022-12-21 00:42 UTC, spencer-lunarg commented on layers/pipeline_state.h
> +    bool WritesToGLLayer() const {
I don't see a need for this to be a function, I can't imagine it ever being reused

2022-12-21 00:53 UTC, spencer-lunarg commented on layers/drawdispatch.cpp
> +    // Only the geometry shader can write to gl_Layer
This isn't true

> VUID-Layer-Layer-04272
> 
> The Layer decoration must be used only within the MeshEXT, MeshNV, Vertex, TessellationEvaluation, Geometry, or Fragment Execution Model

I think a proper VUID is needed here, curious if this is actually limited to Geometry

2022-12-21 17:18 UTC, juan-lunarg commented on layers/drawdispatch.cpp
> +    // Only the geometry shader can write to gl_Layer
Well for fragment shaders it's a read operation not a write operation (If I'm reading the docs correctly). As for the Mesh/Vertex/Tesselation I had no idea based off the documentation I found (https://registry.khronos.org/OpenGL-Refpages/gl4/html/gl_Layer.xhtml).

2022-12-22 17:09 UTC, ncesario-lunarg commented on layers/drawdispatch.cpp
> +    // Only the geometry shader can write to gl_Layer
I think SPIR-v allows layer to be written in any "pre-raster stage," and only GLSL restricts writing to the geometry stage, but I'm not 100% sure.

2022-12-22 17:19 UTC, ncesario-lunarg commented on layers/drawdispatch.cpp
> +    // Only the geometry shader can write to gl_Layer
https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_builtin

Looks like vertex, tessellation, or geometry stages can write the layer; I don't see any mention of mesh shaders, but the documentation does say "See the client API specification for more detail."

2022-12-22 17:38 UTC, ncesario-lunarg requested changes
Looks good! I think the feedback from Spencer is necessary, but I'm also curious if my understanding of the problem is correct (see GPUAV related comment). If it is, we should make it clear where the VUID is triggered and in the issue that this is only an approximation (maybe that was made clear and I just missed it).

2022-12-22 17:38 UTC, ncesario-lunarg commented on layers/drawdispatch.cpp
> +    if (!pipeline_state->HasShaderStage(VK_SHADER_STAGE_GEOMETRY_BIT)) {
Based on Spencer's comment this needs to be updated to include vertex, tess, and mesh stages.

2022-12-22 17:38 UTC, ncesario-lunarg commented on layers/drawdispatch.cpp
> +    const safe_VkAttachmentReference2 *p_color_attachments = active_subpass_desc->pColorAttachments;
I don't think the `p_` "hungarian-like notation" is consistent with code elsewhere. These prefixes are usually only used when referencing variable names coming directly from the vulkan API.

2022-12-22 17:38 UTC, ncesario-lunarg commented on layers/pipeline_state.h
> +    bool WritesToGLLayer() const {
`WritesToGLLayer` is clearer than `std::any_of(stage_state.begin(), stage_state.end(), [](const PipelineStageState &stage) { return stage.writes_to_gl_layer; })` IMHO, but I don't have a particularly strong feeling either way.

2022-12-22 17:38 UTC, ncesario-lunarg commented on layers/drawdispatch.cpp
> +        const bool is_multi_layer = active_frame_buffer->IsMultiLayerAttachment(attachment);
So if I understand correctly, this isn't _really_ catching the error. i.e., a shader stage could be write the value `x` to `gl_Layer`, but the attachment only has `y` layers with `x > y`? If so, we need GPUAV to do this properly.

2022-12-22 17:38 UTC, ncesario-lunarg commented on tests/vklayertests_pipeline_shader.cpp
> +    if (!IsPlatform(kMockICD)) {
If the error is triggered properly, the draw should never get submitted to the driver. Seems like this is unnecessarily limiting.

2022-12-22 18:13 UTC, juan-lunarg commented
"actually I am going to raise an issue with the WG on this one... I have found we have wasted a lot of time in the past trying to add UNASSIGNED VUID support to only have a VU change and be different then what it should be

also VK_EXT_shader_viewport_index_layer and VK_NV_geometry_shader_passthrough is going to add wrinkles to this"
- @spencer-lunarg 

I agree. I didn't consider the other shader stages when I made this PR, I also am unsure how robust my solution is altogether.

Given the small length of this PR. It wouldn't be hard to redo in the future except incorporating the feedback here.

2022-12-22 18:13 UTC, closed without merging