vkQueueWaitIdle in death test
KhronosGroup/Vulkan-ValidationLayers pull request #4999
Opened 2022-12-26 16:27 UTC by arno-lunarg

- Fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4983

The targeted `vkQueueWaitIdle` may cause a crash, so perform wait in its own process using a death test to avoid crashing the test suite.

2022-12-26 17:56 UTC, arno-lunarg commented
The failure on nvidia is still happening but does not cause a test suite crash:
```
[==========] Running 1564 tests from 15 test suites.
[----------] Global test environment set-up.
[----------] 1 test from VkGpuAssistedLayerDeathTest
[ RUN      ] VkGpuAssistedLayerDeathTest.GpuBufferDeviceAddressOOB
Driver Name = NVIDIA
Driver Info = 515.65.01
/home/lunarg/.jenkins/vz4/Release64/Vulkan-ValidationLayers/tests/vklayertests_gpu.cpp:1185: Failure
Death test: QueueWaitIdleWithTimeout(std::chrono::seconds(8), m_errorMonitor, m_device->m_queue)
    Result: died but not with expected exit code:
            Terminated by signal 11 (core dumped)
Actual msg:
[  DEATH   ] vk::QueueWaitIdle timeout. Waited 8 seconds.
[  FAILED  ] VkGpuAssistedLayerDeathTest.GpuBufferDeviceAddressOOB (10490 ms)
[----------] 1 test from VkGpuAssistedLayerDeathTest (10490 ms total)
```

2022-12-26 18:36 UTC, lunarpapillo reviewed
Thank you for doing this.

I looked at the code as an interested party, though I should not be considered an official reviewer.

2022-12-26 18:36 UTC, lunarpapillo commented on tests/vklayertests_gpu.cpp
> +                    std::exit(0);
Everywhere else I can find, we exit with either `EXIT_FAILURE` or `EXIT_SUCCESS`.  Here we use integers 0 through -5.  Help me understand why?

2022-12-26 18:36 UTC, lunarpapillo commented on tests/vklayertests_gpu.cpp
> +                if (const bool found = errorMonitor->VerifyFound(); found) {
Nit: I don't think the `; found` is necessary.  (Is it?)

2022-12-26 18:36 UTC, lunarpapillo commented on tests/vkerrormonitor.cpp
>          // The lock must be released before the ExpectSuccess call at the end
Not your code.... but is this comment correct?

2022-12-26 18:51 UTC, lunarpapillo commented
> The failure on nvidia is still happening but does not cause a test suite crash:

That's a **Linux-NVIDIA** failure, which might be a concern since this test used to run correctly: http://erusea:8080/job/Vulkan-ValidationLayers/9910/BITS=64,BUILD_MODE=Debug,USE_ROBIN_HOOD_HASHING=ON,label=Linux-NVIVIA-new/artifact/vulkantest-results/execution-logs/009-vk_layer_validation_tests-stdout.txt
```
Driver Name = NVIDIA
Driver Info = 515.65.01
...
[ RUN      ] VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB
[       OK ] VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB (193 ms)
```
I noticed that the test section changed from `VkGpuAssistedLayerTest` to `VkGpuAssistedLayerDeathTest` - does this mean that you intentionally modified the test to die (in order to check this code)?  If so, I'm fine...

2022-12-26 18:55 UTC, lunarpapillo commented
> The targeted vkQueueWaitIdle may cause a crash, so perform wait in its own process using a death test to avoid crashing the test suite.

Ah, then, that's a problem.

For what it's worth, I don't mind if a failure crashes the test suite.  In the original issue, the problem was that the test hanged the test suite, stopping CI throughput until an hour had passed and potentially leaving behind a running process that would cause subsequent runs to fail.

2022-12-26 19:13 UTC, arno-lunarg commented on tests/vklayertests_gpu.cpp
> +                if (const bool found = errorMonitor->VerifyFound(); found) {
oh yes indeed!

2022-12-26 19:17 UTC, arno-lunarg commented on tests/vklayertests_gpu.cpp
> +                    std::exit(0);
I wanted to use a different error code for every handled error. I really do not use `exit` often, so maybe I just should not do that, and rely on the message printed to `stderr`.

2022-12-26 19:17 UTC, arno-lunarg commented on tests/vkerrormonitor.cpp
>          // The lock must be released before the ExpectSuccess call at the end
ExpectSuccess is locking the mutex, so I think this comment is valid

2022-12-26 19:26 UTC, arno-lunarg commented
> I noticed that the test section changed from VkGpuAssistedLayerTest to VkGpuAssistedLayerDeathTest - does this mean that you intentionally modified the test to die (in order to check this code)? If so, I'm fine...

Yes, the google test doc advises to use a test class ending with `DeathTest` so that death test are detected and ran first. But the test should succeed if there is no timeout or a driver crash. The test will now just die properly if there is a crash.

2022-12-26 19:28 UTC, arno-lunarg commented
> That's a Linux-NVIDIA failure, which might be a concern since this test used to run correctly
Maybe the crash happens _because_ of my changes then, unforeseen consequences of the fork call on linux maybe?

2022-12-26 19:31 UTC, arno-lunarg commented
> For what it's worth, I don't mind if a failure crashes the test suite. In the original issue, the problem was that the test hanged the test suite, stopping CI throughput until an hour had passed and potentially leaving behind a running process that would cause subsequent runs to fail.

Oh ok! Doing this should be easy, basically I just have to call `QueueWaitIdleWithTimeout` without putting it in a death test macro.

2022-12-26 19:51 UTC, arno-lunarg commented
I switched to a simple timeout on the wait idle without new process/death test logic to see if it fixes the test crashing. If it does, then probably let's go for this way of doing things, since it is what @lunarpapillo asked for.

2022-12-27 16:01 UTC, jeremyg-lunarg requested changes
I'm worried what happens when the QueueWaitIdle() doesn't finish on time and this code handles the timeout but there's still that wait hanging out in the background. What does that do to the rest of the test run? Why not just wait on a fence, which can time out?

2022-12-27 19:55 UTC, arno-lunarg commented on tests/vklayertests_gpu.cpp
> +    QueueWaitIdleWithTimeout(std::chrono::seconds(10), m_device->m_queue);
ah I did not think about that, it should be more simple (and also simply the correct Vulkan way)

2022-12-28 09:42 UTC, arno-lunarg commented on tests/vklayertests_gpu.cpp
> +    QueueWaitIdleWithTimeout(std::chrono::seconds(10), m_device->m_queue);
Thinking about this overnight, since the error is a device lost, and since the fence is created using the device, isn't there a risk for the fence to be in a bad state and _unwaitable_?

2022-12-28 20:24 UTC, closed without merging

2022-12-28 20:25 UTC, arno-lunarg commented
Closing this PR, it does not fix the problem