[WIP] Add support for VK_EXT_surface_maintenance1 and VK_EXT_swapchain_maintenance1
KhronosGroup/Vulkan-ValidationLayers pull request #5000
Opened 2022-12-26 16:55 UTC by mark-lunarg

I'm sure this is full of scary stuff.  Just wanted to get it through a CI pass before any attention was paid to it.

2022-12-27 16:55 UTC, jeremyg-lunarg commented on layers/parameter_validation_utils.cpp
> +    if (instance_extensions.vk_ext_surface_maintenance1) {
Shouldn't this use IsExtEnabled()?

2022-12-27 16:55 UTC, jeremyg-lunarg commented on layers/parameter_validation_utils.cpp
> +        if (instance_extensions.vk_google_surfaceless_query) {
Also IsExtEnabled()?

2022-12-27 16:55 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +            for (uint32_t i = 0; i < swapchain_present_modes_ci->presentModeCount; i++) {
You should call swapchain->present_modes.reserve(swapchain_present_modes_ci->presentModeCount); before the loop. Or use std::copy() instead of the loop.

2022-12-27 16:55 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +    if (result == VK_ERROR_DEVICE_LOST) {
Should this be result != VK_SUCCESS for consistency with other code?

2022-12-27 16:55 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +        if ((!device_extensions.vk_ext_surface_maintenance1) || (!surface_present_mode)) {
IsExtEnabled()

2022-12-27 16:55 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +    /*
We don't really have a way to handle pReleaseInfo correctly here at the present. To do it right, I think we need to store the fences and semaphores associated with each swapchain image in either SWAPCHAIN_NODE or IMAGE_STATE and then use this call as another way to call Retire() on the fences and semaphores when it succeeds.

2022-12-28 14:09 UTC, mark-lunarg commented on layers/state_tracker.cpp
> +            for (uint32_t i = 0; i < swapchain_present_modes_ci->presentModeCount; i++) {
*sweats*. Is it right that I can either do a reserve + copy here, or do a copy with  `back_inserter()`?

2022-12-28 14:19 UTC, mark-lunarg commented on layers/state_tracker.cpp
> +    /*
I had forgotten all about this function, sigh.  I will give it a go but look out.

2022-12-28 15:04 UTC, jeremyg-lunarg commented on layers/state_tracker.cpp
> +            for (uint32_t i = 0; i < swapchain_present_modes_ci->presentModeCount; i++) {
yep either of those should work

2022-12-29 16:03 UTC, mark-lunarg commented on layers/image_state.h
> +    mutable layer_data::unordered_map<VkPhysicalDevice,
I think there is a catch -- differing `min/maxImageCounts` can be returned if the extension structs are chained.  So for any given `[pdev][presentMode]`, even if the extension is enabled those values will be different depending on how it gets called.  We could unify the maps and add some state indicating which values should be returned, but at the cost of some additional complexity. In practice how many apps are going to simultaneously create multiple swapchains with and without using the extension, but I guess they could?  I'm happy to go either way!

2023-01-02 19:17 UTC, mark-lunarg commented
@spencer-lunarg, @juan-lunarg, @ncesario-lunarg, Jeremy thinks this is far enough along to take off the WIP.  I'd appreciate any attention you can afford.  We did decide to handle the swapchain state_tracker/synchronization updates in a separate PR though the validation is ostensibly covered. Dang, copyright dates!  Somebody should redo that script.

2023-01-02 20:42 UTC, jeremyg-lunarg commented
If you rebase this on to tip of master, you should get the new copyright script and clear the errors without changing them all...

2023-01-02 23:02 UTC, mark-lunarg commented on layers/state_tracker.cpp
> +    /*
This will be handled in a follow-on PR.

2023-01-03 22:55 UTC, ncesario-lunarg reviewed
Some nits and comments, but LGTM!

2023-01-03 22:55 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                    return true;
Probably not necessary due to precedent in this file, but this is kind of abnormal and might be nice to have a comment indicating why no other validation in this function should run. Same comment for similar instances below.

2023-01-03 22:55 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                if (LogError(device, "VUID-VkSwapchainCreateInfoKHR-imageExtent-01274",
I'm probably just being ignorant here, but why is the usual `skip |= LogError(...` not used here and below?

2023-01-03 22:55 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +        if (skip) return true;
Shouldn't this return skip? If it shouldn't (??), don't we need an `else`, or something to indicate what is returned? As it stands now, if `!skip`, seems like the return value is undefined.

2023-01-03 22:55 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                        auto fence_state = Get<FENCE_STATE>(swapchain_present_fence_info->pFences[i]);
This can probably be `const`. I only noticed since you were much more thorough than I and used `const` in your function parameter definition, which I always forget to do :)

2023-01-03 22:55 UTC, ncesario-lunarg commented on layers/parameter_validation_utils.cpp
> +    //if (instance_extensions.vk_ext_surface_maintenance1) {
?

2023-01-03 22:55 UTC, ncesario-lunarg commented on tests/vklayertests_wsi.cpp
> +        GTEST_SKIP() << "At least Vulkan version 1.1 is required";
`VK_API_VERSION_1_0` -> `VK_API_VERSION_1_1` above?

2023-01-03 23:23 UTC, mark-lunarg commented on layers/core_validation.cpp
> +        if (skip) return true;
I will verify, but IIRC any accumulated errors cause bad behavior below, so if there are errors we return otherwise we keep validating.

2023-01-03 23:23 UTC, mark-lunarg commented on layers/core_validation.cpp
> +                    return true;
Sure, I'll audit the error handling.

2023-01-03 23:24 UTC, mark-lunarg commented on layers/core_validation.cpp
> +                if (LogError(device, "VUID-VkSwapchainCreateInfoKHR-imageExtent-01274",
I noticed that the default for the WSI-related checks was mostly one-and-done -- any single validation error results in the validation routine exiting immediately.  My theory was that if just about any of this stuff fails your app is hosed anyway.  I did play some games because the new extension validation checks were so interrelated -- switching to all skips or all returns would mean a slew of `SetUnexpectedError()` calls in the tests, so now they're kinda grouped by related failure groups.

2023-01-03 23:38 UTC, juan-lunarg requested changes

2023-01-03 23:38 UTC, juan-lunarg commented on layers/core_validation.cpp
> +                if (!found_match) {
C++17 if statement. Reads better and keeps tight scope. See above example.

2023-01-03 23:38 UTC, juan-lunarg commented on layers/core_validation.cpp
> +                if (!found_match) {
C++17 if statement. Reads better and keeps tight scope. See above example.

2023-01-03 23:38 UTC, juan-lunarg commented on layers/core_validation.cpp
> +                                 "contains a non-supported presentMode in pPresentModes[%d]: (%s).",
Use PRIu32 format specifier

2023-01-03 23:38 UTC, juan-lunarg commented on layers/core_validation.cpp
> +                                 func_name, i, string_VkPresentModeKHR(swapchain_present_mode))) {
Use PRIu32 format specifier

2023-01-03 23:38 UTC, juan-lunarg commented on layers/core_validation.cpp
> +                }
Avoid if statement with `|=`

```suggestion
                const bool has_present_mode = (swapchain_present_modes_ci->pPresentModes[i] == present_mode);
                found_swapchain_modes_ci_present_mode |= has_present_mode;
```

2023-01-03 23:38 UTC, juan-lunarg commented on layers/core_validation.cpp
> +        auto pres_scale_ci = LvlFindInChain<VkSwapchainPresentScalingCreateInfoEXT>(pCreateInfo->pNext);
Given the amount of code a helper function for validating `VkSwapchainPresentScalingCreateInfoEXT` would be nice (and reduce indentation).

2023-01-03 23:40 UTC, juan-lunarg commented on layers/core_validation.cpp
> +                                "imageIndex (%i) has not been acquired",
removing suggestion since it could become out of date with a spec update (didn't think about that).

2023-01-04 11:01 UTC, spencer-lunarg commented on layers/core_validation.cpp
> +                    if (device_extensions.vk_ext_swapchain_maintenance1 &&
for all the `device_extensions.vk_*` in this PR, please use the`IsExtEnabled` wrapper for it

2023-01-04 11:04 UTC, spencer-lunarg commented on layers/core_validation.cpp
> +            if (skip) return true;
There are a few early returns in this function, was this on purpose, is there a reason we shouldn't keep checking (if so not 100% obvious and maybe worth a comment)

2023-01-04 14:49 UTC, mark-lunarg commented
Thanks to all the great review input -- there was a regression running with swiftshader (CI doesn't really touch any of this) and I'm almost done combining the `present_modes_` maps in state_tracker.  I'll be OOO 4 of the next 5 or 6 days but plan to address all of the feedback ASAP.

2023-01-04 17:59 UTC, juan-lunarg requested changes

2023-01-04 17:59 UTC, juan-lunarg commented on layers/core_validation.cpp
> +                if (!found_match) {
```suggestion
                if (std::find(present_modes.begin(), present_modes.end(), swapchain_present_mode) == present_modes.end()) {
```

2023-01-04 17:59 UTC, juan-lunarg commented on layers/core_validation.cpp
> +                if (!found_match) {
```suggestion
                if (std::find(compatible_present_modes.begin(), compatible_present_modes.end(), swapchain_present_mode) == compatible_present_modes.end()) {
```

2023-01-04 17:59 UTC, juan-lunarg commented on layers/core_validation.cpp
> +                    surface_state->GetCompatibleModes(physical_device, present_mode);
```suggestion
                const std::vector<VkPresentModeKHR> compatible_present_modes =
                    surface_state->GetCompatibleModes(physical_device, present_mode);
```

2023-01-04 18:08 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +                                         static_cast<int>(swapchain_state->images.size()));
`%z` == `size_t`? If that's true, I don't think there is a `PRIz` to use.

2023-01-04 18:15 UTC, juan-lunarg commented on layers/core_validation.cpp
> +                                         static_cast<int>(swapchain_state->images.size()));
Agreed

2023-01-06 20:01 UTC, mark-lunarg commented on layers/image_state.h
> +    mutable layer_data::unordered_map<VkPhysicalDevice,
Done.

2023-01-06 20:22 UTC, mark-lunarg commented on layers/core_validation.cpp
> +                                error_prefix, swapchain_info->imageIndex);
Done

2023-01-06 20:25 UTC, mark-lunarg commented on layers/core_validation.cpp
> +                if (!found_match) {
Done

2023-01-06 20:27 UTC, mark-lunarg commented on layers/core_validation.cpp
> +                                 "contains a non-supported presentMode in pPresentModes[%d]: (%s).",
Done

2023-01-06 20:29 UTC, mark-lunarg commented on layers/core_validation.cpp
> +                    surface_state->GetCompatibleModes(physical_device, present_mode);
Done

2023-01-06 20:30 UTC, mark-lunarg commented on layers/core_validation.cpp
> +                if (!found_match) {
Done

2023-01-06 20:35 UTC, mark-lunarg commented on layers/core_validation.cpp
> +                }
Done.  Uncomfortable, but done.

2023-01-06 22:19 UTC, mark-lunarg commented on layers/core_validation.cpp
> +                        auto fence_state = Get<FENCE_STATE>(swapchain_present_fence_info->pFences[i]);
Done

2023-01-06 22:20 UTC, mark-lunarg commented on layers/parameter_validation_utils.cpp
> +    //if (instance_extensions.vk_ext_surface_maintenance1) {
Done

2023-01-06 22:22 UTC, mark-lunarg commented on tests/vklayertests_wsi.cpp
> +        GTEST_SKIP() << "At least Vulkan version 1.1 is required";
Done

2023-01-06 22:27 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +        if (skip) return true;
Sounds like we should `assert(skip)` at this point then, and return `skip`? If `!skip` here, that sill seems like it's going to be undefined behavior, but maybe I'm missing something.

2023-01-06 22:29 UTC, ncesario-lunarg commented
> ... Jeremy thinks this is far enough along to take off the WIP. I'd appreciate any attention you can afford. We did decide to handle the swapchain state_tracker/synchronization updates in a separate PR though the validation is ostensibly covered.

Sounds good to me! Though I think there are still some outstanding comments that need to be resolved one way or the other.

> Dang, copyright dates! Somebody should redo that script.

I believe @jeremyg-lunarg already did?

2023-01-06 23:17 UTC, ncesario-lunarg commented on layers/core_validation.cpp
> +        if (skip) return true;
Just ignore me. For some silly reason the diff I was looking at made it look as though the `}` on the next line was the end of the function.

2023-01-06 23:53 UTC, mark-lunarg commented on layers/core_validation.cpp
> +        auto pres_scale_ci = LvlFindInChain<VkSwapchainPresentScalingCreateInfoEXT>(pCreateInfo->pNext);
Done.

2023-01-07 02:45 UTC, mark-lunarg commented on layers/core_validation.cpp
> +            } else if (IsExtEnabled(instance_extensions.vk_google_surfaceless_query)) {
I believe so, this was not changed other than to wrap it in a `!IsExtEnabled(swapchain_ext)` conditional.

2023-01-08 05:14 UTC, mark-lunarg commented on layers/core_validation.cpp
> +                    return true;
Got rid of all the early returns.

2023-01-08 05:15 UTC, mark-lunarg commented on layers/core_validation.cpp
> +                if (LogError(device, "VUID-VkSwapchainCreateInfoKHR-imageExtent-01274",
Switched to normal skip error returns.

2023-01-08 05:16 UTC, mark-lunarg commented on layers/core_validation.cpp
> +            if (skip) return true;
Removed early returns.

2023-01-08 05:21 UTC, mark-lunarg commented
@jeremyg-lunarg, you might take a look at the changes for combining the `present_mode` maps using `std::optional` (in a separate commit)-- CI choked on the 'old' MacOS build saying it didn't support `value()`.  My workarounds for this are in the final commit but I'm not confident there isn't a better way to fix things.

2023-01-09 19:07 UTC, juan-lunarg commented on layers/image_state.cpp
> +                                       std::vector<VkPresentModeKHR> &&compatible_modes) {
This should also use a span. Avoids creating temp std::vector at call site.

```suggestion
void SURFACE_STATE::SetCompatibleModes(VkPhysicalDevice phys_dev, const VkPresentModeKHR present_mode,
                                       layer_data::span<const VkPresentModeKHR> compatible_modes) {
```

2023-01-09 19:08 UTC, juan-lunarg commented on layers/image_state.cpp
> +        present_mode_state->compatible_present_modes_ = compatible_modes;
NOTE: compatible_modes won't be moved it will be copied. And if it was moved it the following for loop would be invalid.

2023-01-09 19:09 UTC, juan-lunarg commented on layers/image_state.cpp
> +    if (present_modes_data_.find(phys_dev) != present_modes_data_.end()) {
Add 1 line comment. Since I would assume by default this function is just a helper for `DispatchGetPhysicalDeviceSurfacePresentModesKHR`

2023-01-11 17:36 UTC, mark-lunarg commented on layers/image_state.cpp
> +    auto &present_mode_state = *(present_modes_data_[phys_dev][present_mode]);
Used temp var to make clang-tidy happy.

2023-01-11 17:37 UTC, mark-lunarg commented on layers/image_state.cpp
> +            auto &scaling_caps = *((iter->second)[present_mode]);
Fixed.

2023-01-11 17:37 UTC, mark-lunarg commented on layers/image_state.cpp
> +
Fixed.

2023-01-11 18:17 UTC, mark-lunarg commented on layers/image_state.cpp
>  void SURFACE_STATE::SetPresentModes(VkPhysicalDevice phys_dev, std::vector<VkPresentModeKHR> &&modes) {
Done

2023-01-11 18:18 UTC, mark-lunarg commented on layers/image_state.cpp
> +            present_modes_data_[phys_dev][new_present_mode] = std::nullopt;
I believe so, yes.  It just sets the present modes for the legacy API and does nothing else.

2023-01-11 18:22 UTC, mark-lunarg commented on layers/image_state.cpp
> +    if (present_modes_data_.find(phys_dev) != present_modes_data_.end()) {
Done

2023-01-11 18:25 UTC, mark-lunarg commented on layers/image_state.cpp
> +                                       std::vector<VkPresentModeKHR> &&compatible_modes) {
Done.

2023-01-11 18:29 UTC, mark-lunarg commented on layers/image_state.cpp
> +    VkPhysicalDeviceSurfaceInfo2KHR surface_info = LvlInitStruct<VkPhysicalDeviceSurfaceInfo2KHR>();
Fixed all of these guys, thanks!

2023-01-12 05:35 UTC, spencer-lunarg commented on layers/parameter_validation_utils.cpp
> +        if (surface_present_mode_compatibility && !(LvlFindInChain<VkSurfacePresentModeEXT>(pSurfaceInfo->pNext))) {
nit: Can group both skips together for both

- `if !(LvlFindInChain<VkSurfacePresentModeEXT>(pSurfaceInfo->pNext))`
- `if (pSurfaceInfo->surface == VK_NULL_HANDLE)`

2023-01-12 17:23 UTC, mark-lunarg commented on layers/parameter_validation_utils.cpp
> +        if (surface_present_mode_compatibility && !(LvlFindInChain<VkSurfacePresentModeEXT>(pSurfaceInfo->pNext))) {
Done.

2023-01-12 17:50 UTC, mark-lunarg commented
@juan-lunarg, what else can I update for y'all?

2023-01-12 18:42 UTC, juan-lunarg requested changes
Mostly just PRIu32 issues

2023-01-12 18:42 UTC, juan-lunarg commented on layers/parameter_validation_utils.cpp
> +        if (surface_present_mode_compatibility && !(LvlFindInChain<VkSurfacePresentModeEXT>(pSurfaceInfo->pNext))) {
Minor code duplication regarding `!(LvlFindInChain<VkSurfacePresentModeEXT>(pSurfaceInfo->pNext)))`  lines 9304 and 9312

2023-01-12 18:42 UTC, juan-lunarg commented on layers/parameter_validation_utils.cpp
> +            if (surface_present_mode_compatibility && (pSurfaceInfo->surface == VK_NULL_HANDLE)) {
Minor code duplication regarding ```(pSurfaceInfo->surface == VK_NULL_HANDLE))``` lines 9321 and 9329

2023-01-12 18:42 UTC, juan-lunarg commented on layers/parameter_validation_utils.cpp
> +            const auto *surface_present_mode_compatibility =
Minor indentation issue? Surprised clang-format didn't complain.
```suggestion
        const auto *surface_present_mode_compatibility =
```

2023-01-12 18:42 UTC, juan-lunarg commented on layers/state_tracker.cpp
> +            uint32_t present_mode_count = swapchain_present_modes_ci->presentModeCount;
```suggestion
            const uint32_t present_mode_count = swapchain_present_modes_ci->presentModeCount;
```

2023-01-12 18:42 UTC, juan-lunarg commented on layers/wsi_validation.cpp
> +                surface_state->GetCompatibleModes(physical_device, present_mode);
This vector shouldn't be constructed in the for loop. And surface_state needs to be checked nullptr.

2023-01-12 18:42 UTC, juan-lunarg commented on layers/wsi_validation.cpp
> +                         "(%d) then presentGravityY (%d) must also be zero.",
Use PRIu32 (VkPresentGravityFlagsEXT is really just a VkFlag which is a uint32_t)

2023-01-12 18:42 UTC, juan-lunarg commented on layers/wsi_validation.cpp
> +                         func_name, pres_scale_ci->presentGravityX, pres_scale_ci->presentGravityY)) {
Use PRIu32 (VkPresentGravityFlagsEXT is really just a VkFlag which is a uint32_t)

2023-01-12 18:42 UTC, juan-lunarg commented on layers/wsi_validation.cpp
> +                         "%s: VkSwapchainPresentScalingCreateInfoEXT is present in the pNext chain and scalingBehavior (%d) "
Use PRIu32 (VkPresentGravityFlagsEXT is really just a VkFlag which is a uint32_t)

2023-01-12 18:42 UTC, juan-lunarg commented on layers/wsi_validation.cpp
> +                         "%s: VkSwapchainPresentScalingCreateInfoEXT is present in the pNext chain and presentGravityX (%d) "
Use PRIu32 (VkPresentGravityFlagsEXT is really just a VkFlag which is a uint32_t)

2023-01-12 18:42 UTC, juan-lunarg commented on layers/wsi_validation.cpp
> +                         "%s: VkSwapchainPresentScalingCreateInfoEXT is present in the pNext chain and presentGravityY (%d) "
Use PRIu32 (VkPresentGravityFlagsEXT is really just a VkFlag which is a uint32_t)

2023-01-12 18:42 UTC, juan-lunarg commented on layers/wsi_validation.cpp
> +                                 "VkSurfacePresentScalingCapabilitiesEXT::supportedPresentScaling for pPresentModes[%d]: (%s).",
Use PRIu32

2023-01-12 18:42 UTC, juan-lunarg commented on layers/wsi_validation.cpp
> +                                 func_name, string_VkPresentGravityFlagsEXT(pres_scale_ci->presentGravityX).c_str(), i,
Use PRIu32

2023-01-12 18:42 UTC, juan-lunarg commented on layers/wsi_validation.cpp
> +                            "VkSurfacePresentScalingCapabilitiesEXT::supportedPresentGravityY for pPresentModes[%d]: (%s).",
Use PRIu32

2023-01-12 18:42 UTC, juan-lunarg commented on layers/wsi_validation.cpp
> +            surface_state->GetPresentModeScalingCapabilities(physical_device, present_mode);
surface_state could potentially be nullptr

2023-01-12 18:42 UTC, juan-lunarg commented on layers/wsi_validation.cpp
> +                    surface_state->GetPresentModeScalingCapabilities(physical_device, present_modes_ci->pPresentModes[i]);
surface_state could potentially be nullptr

2023-01-12 18:42 UTC, juan-lunarg commented on layers/wsi_validation.cpp
> +                        "is %i. For VkSwapchainPresentFenceInfoEXT in pNext chain of VkPresentInfoKHR, "
Use PRIU32

2023-01-12 18:42 UTC, juan-lunarg commented on layers/wsi_validation.cpp
> +                        "is %i. For VkSwapchainPresentModeInfoEXT in pNext chain of VkPresentInfoKHR, "
Use PRIU32

2023-01-12 18:42 UTC, juan-lunarg commented on layers/wsi_validation.cpp
> +                    if (swapchain_state->present_modes.size()) {
```suggestion
                    if (!swapchain_state->present_modes.empty()) {
```

2023-01-12 18:42 UTC, juan-lunarg commented on layers/wsi_validation.cpp
> +                                 "vkReleaseSwapchainImagesEXT: swapchain image index is too large (%u). There are only %u images "
Use PRIu32

2023-01-12 18:54 UTC, juan-lunarg requested changes
Testing looks good overall. I'd like to see a follow up PR though that adds positive testing though. As that can help catch bugs in the VVL implementation as well.

2023-01-12 18:54 UTC, juan-lunarg commented on tests/vklayertests_wsi.cpp
> +    const std::vector<VkPresentModeKHR> defined_present_modes{
This doesn't need to be a std::vector, use std::array with CTAD

```suggestion
    const std::array defined_present_modes{
```

2023-01-12 18:54 UTC, juan-lunarg commented on tests/vklayertests_wsi.cpp
> +        std::vector<VkPresentScalingFlagBitsEXT> scaling_flag_bits = {VK_PRESENT_SCALING_ONE_TO_ONE_BIT_EXT,
```suggestion
        const std::array scaling_flag_bits = {VK_PRESENT_SCALING_ONE_TO_ONE_BIT_EXT,
```

2023-01-12 18:54 UTC, juan-lunarg commented on tests/vklayertests_wsi.cpp
> +    std::vector<VkPresentGravityFlagBitsEXT> gravity_flag_bits = {VK_PRESENT_GRAVITY_MIN_BIT_EXT, VK_PRESENT_GRAVITY_MAX_BIT_EXT,
```suggestion
    const std::array gravity_flag_bits = {VK_PRESENT_GRAVITY_MIN_BIT_EXT, VK_PRESENT_GRAVITY_MAX_BIT_EXT,
```

2023-01-12 18:54 UTC, juan-lunarg commented on tests/vklayertests_wsi.cpp
> +    std::vector<VkPresentGravityFlagBitsEXT> defined_gravity_flag_bits = {
```suggestion
    const std::array defined_gravity_flag_bits = {
```

2023-01-12 18:54 UTC, juan-lunarg commented on tests/vklayertests_wsi.cpp
> +    const std::vector<VkPresentModeKHR> defined_present_modes{
```suggestion
    const std::array defined_present_modes{
```

2023-01-12 19:39 UTC, mark-lunarg commented on layers/parameter_validation_utils.cpp
> +            const auto *surface_present_mode_compatibility =
Yeah, I thought that was weird too.  I fixed it while working Spencer's comments, seems OK now.

2023-01-12 19:40 UTC, mark-lunarg commented on layers/parameter_validation_utils.cpp
> +        if (surface_present_mode_compatibility && !(LvlFindInChain<VkSurfacePresentModeEXT>(pSurfaceInfo->pNext))) {
Spencer also pointed these out, fixed.

2023-01-12 20:00 UTC, mark-lunarg commented on layers/wsi_validation.cpp
> +                surface_state->GetCompatibleModes(physical_device, present_mode);
Done.

2023-01-12 20:31 UTC, mark-lunarg commented on tests/vklayertests_wsi.cpp
> +    const std::vector<VkPresentModeKHR> defined_present_modes{
That's a cool trick! Fixed all three of these.

2023-01-12 21:09 UTC, juan-lunarg commented on tests/vklayertests_wsi.cpp
> +    const std::vector<VkPresentModeKHR> defined_present_modes{
Agreed class template argument deduction really helps usability of `std::array` in particular.

2023-01-12 21:18 UTC, juan-lunarg reviewed
Just 1 last question

2023-01-12 21:18 UTC, juan-lunarg commented on layers/wsi_validation.cpp
> +            surface_state->GetCompatibleModes(physical_device, present_mode);
Why do we check for surface_state on line 93 but assert on line 107?

2023-01-12 21:28 UTC, mark-lunarg commented on layers/wsi_validation.cpp
> +            surface_state->GetCompatibleModes(physical_device, present_mode);
In my understanding, if surfaceless_query is enabled then surface_state _can_ be null here.  Below, guarded by the `if (swapchain_present_modes_ci) {` it has to be non-null there.

2023-01-12 21:30 UTC, juan-lunarg commented on layers/wsi_validation.cpp
> +            surface_state->GetCompatibleModes(physical_device, present_mode);
Got it that makes sense. A comment explaining the assert would be helpful.

2023-01-12 21:55 UTC, mark-lunarg commented on layers/wsi_validation.cpp
> +            surface_state->GetCompatibleModes(physical_device, present_mode);
👍

2023-01-12 22:21 UTC, juan-lunarg approved these changes
LGTM

2023-01-12 22:23 UTC, mark-lunarg commented
@juan-lunarg, @jeremyg-lunarg, thanks for all your help. When more hardware coverage arrives I'm sure there'll be some deficiencies and I'll be glad to hop back in if it'd be helpful.

2023-01-12 23:22 UTC, merged