layers: Clean up vk_layer_logging.h
KhronosGroup/Vulkan-ValidationLayers pull request #5016
Opened 2022-12-29 18:11 UTC by jeremyg-lunarg

Add vk_layer_logging.cpp, so that most of the logging functions can be de-inlined. This appears to reduce compiled code size for the validation layer by 33% (on linux).

Change LogMsgLocked() to LogMsg() and restructure it to avoid duplicated code in class ValidationObject.

Remove use of vasprintf() and use stack buffers and snprintf() instead. vasprintf() calls malloc internally and VVL must call free. When overriding malloc, this gets complicated because libc and VVL can end up using different malloc and free implementations.

2022-12-29 18:24 UTC, jeremyg-lunarg commented
This is needed to allow https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4876 to work on linux. But it is worth doing on its own.

The size of the VVL .so on linux / GCC 12 goes from 412Mb to 276Mb for Debug and 208Mb to 184Mb for Release

2022-12-29 18:49 UTC, mark-lunarg approved these changes
This is great!

2022-12-29 22:24 UTC, juan-lunarg commented on layers/vk_layer_logging.cpp
> +}
This one line function is only used once. Better to just remove IMO. Especially since it only used once, and doesn't even use the first parameter it's passed.

2022-12-29 22:24 UTC, juan-lunarg commented on layers/vk_layer_logging.cpp
> +    char buf[1024];
Is 1024 enough? Should we assert if it's not enough?

2022-12-29 22:32 UTC, jeremyg-lunarg commented on layers/vk_layer_logging.cpp
> +    char buf[1024];
I *think* it is enough, but probably we should assert. There's another buffer in one of the callback functions which is 2048, but that's for this part of the message and the VUID text.

2022-12-29 22:40 UTC, jeremyg-lunarg commented on layers/vk_layer_logging.cpp
> +}
it's actually worse than that, because the call site is immediately before `delete debug_data;` which will clear the callback list.

2022-12-29 23:35 UTC, jeremyg-lunarg commented on layers/vk_layer_logging.cpp
> +    char buf[1024];
I forgot to add the assert, but I think I figured out a way to do it without the possibility of overrun failure.

2022-12-29 23:49 UTC, spencer-lunarg approved these changes

2022-12-30 21:13 UTC, juan-lunarg requested changes
Looks like just 1 test is failing.

```
 [  FAILED  ] 1 test, listed below:
[  FAILED  ] VkLayerTest.SpecLinks

 1 FAILED TEST
  YOU HAVE 1 DISABLED TEST
```

2023-01-02 16:50 UTC, jeremyg-lunarg commented on layers/vk_layer_logging.cpp
> +        str_plus_spec_text.resize(result);
Ugh, it still isn't right. I need the +1 in the overflow case because:
```
The functions snprintf() and vsnprintf() write at most size bytes (including the terminating null byte ('\0')) to str.
```

2023-01-02 16:52 UTC, jeremyg-lunarg commented on layers/vk_layer_logging.cpp
> +        str_plus_spec_text.resize(result);
BUT:
```
RETURN VALUE
       Upon successful return, these functions return the number of characters printed (excluding the null byte used to end output to strings).
```

2023-01-03 16:34 UTC, ncesario-lunarg approved these changes
LGTM once the gremlins are worked out :)

The overflow case is more motivation to refactor the base logging mechanisms, but if that's working again, we'll probably kick that down the road again...

2023-01-03 16:34 UTC, ncesario-lunarg commented on tests/vklayertests_others.cpp
> +    // VUID-VkPhysicalDeviceProperties2-pNext-pNext produces a massive ~3600 character log message, which hits a
😬

2023-01-03 16:53 UTC, jeremyg-lunarg commented
> The overflow case is more motivation to refactor the base logging mechanisms, but if that's working again, we'll probably kick that down the road again...

I agree we should refactor more.

2023-01-03 16:54 UTC, juan-lunarg commented on tests/vklayertests_others.cpp
> +    // VUID-VkPhysicalDeviceProperties2-pNext-pNext produces a massive ~3600 character log message, which hits a
I think this PR is fine once the logging code is fixed to address this.

2023-01-03 18:08 UTC, jeremyg-lunarg commented on tests/vklayertests_others.cpp
> +    // VUID-VkPhysicalDeviceProperties2-pNext-pNext produces a massive ~3600 character log message, which hits a
Yes it is working now. With earlier versions of the code I was either dropping a character in this log message or putting a '\0' in the middle of the message which would cause the SpecLinks test to fail. By changing the DesiredFailure here, both of those problems are covered by a test case.

2023-01-03 18:53 UTC, juan-lunarg approved these changes

2023-01-03 18:56 UTC, merged