cmake: Build a shared library instead of module
KhronosGroup/Vulkan-ValidationLayers pull request #5018
Opened 2022-12-30 01:37 UTC by sarnex

If we use MODULE, cmake doesn't set SONAME which we should have. MODULE is not meant only for runtime explicit dynamic linking with dlopen

Signed-off-by: Nick Sarnie <sarnex@gentoo.org>

2022-12-30 01:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5018) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5018) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5018) it.</sub>

2022-12-30 17:14 UTC, juan-lunarg requested changes
-1

2022-12-30 17:14 UTC, juan-lunarg commented on layers/CMakeLists.txt
> +add_library(VkLayer_khronos_validation SHARED)
2 main things.

1.) This will cause problems for [Windows](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4804). By specifying the library as a `MODULE` CMake won't install the pointless `.lib`, which is important for LunarG SDK script generation

2.) "MODULE is meant only for runtime explicit dynamic linking with dlopen". Yes that is correct. That is the way layers are opened by the Vulkan Loader. Users aren't meant to link against the loader.

2022-12-30 17:27 UTC, juan-lunarg commented
> If we use MODULE, cmake doesn't set SONAME which we should set

What is the consequence? Because testing didn't catch anything.

2022-12-30 20:51 UTC, sarnex commented
Sorry, I didn't look deep enough into the vulkan loader usage to find the dlopen

2022-12-30 20:51 UTC, closed without merging

2022-12-30 20:51 UTC, sarnex commented on layers/CMakeLists.txt
> +add_library(VkLayer_khronos_validation SHARED)
> > If we use MODULE, cmake doesn't set SONAME which we should set
> 
> What is the consequence? Testing didn't catch anything.

I found this from some automated QA testing in Gentoo

2022-12-30 21:11 UTC, juan-lunarg commented
> Sorry, I didn't look deep enough into the vulkan loader usage to find the dlopen

No worries. Out of curiosity what does the automated QA testing look for?

2022-12-31 00:54 UTC, sarnex commented
> > Sorry, I didn't look deep enough into the vulkan loader usage to find the dlopen
> 
> No worries. Out of curiosity what does Gentoo's automated QA testing look for?

We look for SONAME in all shared libraries, the implementation of that check is here

https://gitweb.gentoo.org/proj/portage.git/tree/bin/install-qa-check.d/80libraries

2022-12-31 01:26 UTC, juan-lunarg commented
> We look for SONAME in all shared libraries, the implementation of that check is here
> 
> https://gitweb.gentoo.org/proj/portage.git/tree/bin/install-qa-check.d/80libraries

Very cool to see this proactive approach to fixing libraries upstream :+1: