Using InterfaceVariable in EntryPoint
KhronosGroup/Vulkan-ValidationLayers pull request #5036
Opened 2023-01-04 13:17 UTC by spencer-lunarg

Currently the shader validation code gets the same information from many different ways resulting in a tangled mess.

This attempts to move more information over to `InterfaceVariable` and then have it at a per-EntryPoint level (which will be needed to support multiple entry points correctly)

This is just a first step PR, the biggest issue is an "Interface Variable" being used for a descriptor is not being treated the same as the Input/Output shader stage interface variables, but yet are sharing some of the same logic. The Input/Output interface is a slight more tricky due to the fact it can have `OpMemberDecorate`

In the process of trying to refactor this, had some generic cleanup as well

2023-01-04 17:56 UTC, ncesario-lunarg approved these changes
LGTM once internal CI passes!

2023-01-04 18:54 UTC, juan-lunarg requested changes

2023-01-04 18:54 UTC, juan-lunarg commented on layers/best_practices_utils.cpp
> +    auto interface_variables = module_state->GetInterfaceVariable(entrypoint);
Current code doesn't check if `module_state->GetInterfaceVariable(` returns a nullptr.

Also IMO the type returned by `GetInterfaceVariable` should be specified.

```suggestion
    const std::vector<InterfaceVariable>* interface_variables = module_state->GetInterfaceVariable(entrypoint);
    if (interface_variables) {
        ... // check for kVUID_BestPractices_CreateComputePipelines_ComputeSpatialLocality
    }
```

2023-01-04 18:54 UTC, juan-lunarg commented on layers/pipeline_state.cpp
>      bool primitiverate_written = false;
nit

```suggestion
    bool primitive_rate_written = false;
```

2023-01-04 18:54 UTC, juan-lunarg commented on layers/pipeline_state.cpp
> +    if (entrypoint) {
```suggestion
    if (!entrypoint) {
        return;
    }
```

2023-01-04 18:54 UTC, juan-lunarg commented on layers/pipeline_state.cpp
> +        for (const InterfaceVariable &variable : *stage.descriptor_variables) {
```suggestion
        for (const InterfaceVariable &descriptor : *stage.descriptor_variables) {
```

2023-01-04 18:54 UTC, juan-lunarg commented on layers/pipeline_state.cpp
> +            if (variable.samplers_used_by_image.size()) {
```suggestion
            if (!variable.samplers_used_by_image.empty()) {
```

2023-01-04 18:54 UTC, juan-lunarg commented on layers/shader_module.cpp
> +            bool is_storage_buffer = interface_var.storage_class == spv::StorageClassStorageBuffer;
```suggestion
            const bool is_storage_buffer = interface_var.storage_class == spv::StorageClassStorageBuffer;
```

2023-01-04 19:22 UTC, ncesario-lunarg commented on layers/best_practices_utils.cpp
> +    auto interface_variables = module_state->GetInterfaceVariable(entrypoint);
We should probably have this discussion in the next team sync. After using `auto` _liberally_ for the past 6+ years, I haven't found a benefit to being verbose with types in cases like this, but that is my subjective opinion. If we want to reduce or remove the use of `auto`, that's fine, but we'll need to come to a consensus, and then going forward we can make that official. For now, this lines up with current usage of `auto` elsewhere in the codebase, so I don't see a need for that to change here.

2023-01-04 19:39 UTC, juan-lunarg commented on layers/best_practices_utils.cpp
> +    auto interface_variables = module_state->GetInterfaceVariable(entrypoint);
I made a case for not using auto here because to me it might have made it more clear to check for `nullptr`. My only indication that this was a pointer was it being dereferenced in the for loop. In general I don't mind `auto` (assuming my intellisense works).

2023-01-04 20:10 UTC, juan-lunarg commented on layers/best_practices_utils.cpp
> +    auto interface_variables = module_state->GetInterfaceVariable(entrypoint);
Updated suggestion.

```suggestion
    auto interface_variables = module_state->GetInterfaceVariable(entrypoint);
    if (interface_variables) {
        ... // check for kVUID_BestPractices_CreateComputePipelines_ComputeSpatialLocality
    }
```

2023-01-04 20:56 UTC, ncesario-lunarg commented on layers/best_practices_utils.cpp
> +    auto interface_variables = module_state->GetInterfaceVariable(entrypoint);
That's a good point. We've been putting off the "auto discussion" for a long time, and I'd like to get it nailed down on what the team would like to see going forward.

In this particular instance I personally don't see the benefit to even adding `*` as the type could change to `std::shared_ptr`, `std::optional`, or something else with `operator bool` and it does not change how the code below is interpreted by a human. Again, though, this is my lazy and subjective point of view, and I assume I'm in the minority here :)

2023-01-05 01:48 UTC, spencer-lunarg commented on layers/pipeline_state.cpp
> +    if (entrypoint) {
Thought about this, but in future someone might want to add logic to the constructor non related to `entrypoint` and this clearly groups all the member variables effected by `entrypoint`

2023-01-05 01:52 UTC, spencer-lunarg commented on layers/pipeline_state.cpp
> +        for (const InterfaceVariable &variable : *stage.descriptor_variables) {
`descriptor` is a misleading variable name here. I made an effort to use `variable` consistently everywhere because `InterfaceVariable` is describing the `OpVariable`

2023-01-05 01:53 UTC, spencer-lunarg commented on layers/best_practices_utils.cpp
> +    auto interface_variables = module_state->GetInterfaceVariable(entrypoint);
applied change, was going to add my two cents about `auto` but rather defer that to a proper discussion time/place

2023-01-05 19:16 UTC, juan-lunarg commented on layers/pipeline_state.cpp
> +    if (entrypoint) {
Makes sense :+1:

2023-01-05 20:33 UTC, juan-lunarg approved these changes
:+1:

2023-01-06 00:04 UTC, merged