build: Set external dir based on build type
KhronosGroup/Vulkan-ValidationLayers pull request #5100
Opened 2023-01-13 06:43 UTC by ncesario-lunarg

Set the --dir value passed to update_deps.py via cmake variable (-DUPDATE_DEPS_DIR), or automatically based on build type.

2023-01-13 18:49 UTC, juan-lunarg requested changes

2023-01-13 18:49 UTC, juan-lunarg commented on CMakeLists.txt
> +    set(_update_deps_dir ${CMAKE_CURRENT_LIST_DIR}/external-${_build_type})
This will cause problems for GitHub actions caching.

If we want to improve the update_deps.py script it'd be good to mimic how vcpkg handles this scenario. I believe they build debug/release binaries in 1 go. That way it works for Ninja / Visual Studio builds elegantly.

2023-01-13 19:21 UTC, ncesario-lunarg commented on CMakeLists.txt
> +    set(_update_deps_dir ${CMAKE_CURRENT_LIST_DIR}/external-${_build_type})
Ah, yep, good catch!

2023-01-13 19:27 UTC, juan-lunarg requested changes
GitHub actions will need to be updated as well

2023-01-13 19:27 UTC, juan-lunarg commented on CMakeLists.txt
> +    set(_update_deps_dir ${CMAKE_CURRENT_LIST_DIR}/external-${_build_type})
Keep all installed dependencies in 1 folder.

```suggestion
    set(_update_deps_dir ${CMAKE_CURRENT_LIST_DIR}/external/${_build_type})
```

2023-01-13 19:27 UTC, juan-lunarg commented on CMakeLists.txt
> +    endif()
I don't think this code does anything.

```suggestion
```

2023-01-13 19:28 UTC, juan-lunarg commented on CMakeLists.txt
> +    set(_update_deps_dir ${CMAKE_CURRENT_LIST_DIR}/external-${_build_type})
Also removes the need to update the `.gitignore`

2023-01-13 19:34 UTC, juan-lunarg commented
This will also require updating multiple CI scripts due to changing the `helper.cmake` invocation.

```
 loading initial cache file ../external/helper.cmake
CMake Error: Error processing file: /home/runner/work/Vulkan-ValidationLayers/Vulkan-ValidationLayers/external/helper.cmake
-- The CXX compiler identification is GNU 9.4.0
```

2023-01-13 20:35 UTC, ncesario-lunarg commented on CMakeLists.txt
> +    set(_update_deps_dir ${CMAKE_CURRENT_LIST_DIR}/external-${_build_type})
Yep, much better, thanks!

2023-01-13 20:36 UTC, ncesario-lunarg commented on CMakeLists.txt
> +    endif()
This is to allow for setting the "external directory" directly, rather than having it derived from the build type.

2023-01-18 01:01 UTC, juan-lunarg approved these changes
LGTM once the merge conflict is resolved

2023-01-18 18:53 UTC, merged