layers: Move files into dedicated folders
KhronosGroup/Vulkan-ValidationLayers pull request #5126
Opened 2023-01-18 08:16 UTC by spencer-lunarg

Takes all files and move them into a more structured folder scheme. In the process some notable modifications were made:
- synchronization_* renamed to sync_* to match other files
- drawdispatch.cpp -> drawdispatch_validation.cpp
- clang-format was ran on some files not ran in a while

2023-01-18 16:47 UTC, juan-lunarg commented on CMakeLists.txt
> +        COMMAND ${PYTHON_EXECUTABLE} ${CMAKE_CURRENT_LIST_DIR}/scripts/update_deps.py
Revert change.

2023-01-18 16:47 UTC, juan-lunarg commented on layers/CMakeLists.txt
> +target_include_directories(VkLayer_khronos_validation PUBLIC
I disagree with adding these include directories, projects should strive to minimize their include directories as much as possible.

It also forces users to specify the directory, which I'd argue is a good thing. Since it highlights the project structure.

EX:

```
#include "best_practices/best_practices_validation.h"
```

2023-01-19 07:26 UTC, spencer-lunarg commented on CMakeLists.txt
> +        COMMAND ${PYTHON_EXECUTABLE} ${CMAKE_CURRENT_LIST_DIR}/scripts/update_deps.py
fixed on rebase

2023-01-20 16:09 UTC, juan-lunarg requested changes

2023-01-20 16:09 UTC, juan-lunarg commented on layers/CMakeLists.txt
> -    generated
We need to keep the generated include directory. Otherwise `VkLayer_utils` won't install properly.

2023-01-21 04:30 UTC, spencer-lunarg commented on layers/CMakeLists.txt
> -    generated
ok, will revert... with a comment 😆

2023-01-23 18:20 UTC, juan-lunarg approved these changes

2023-01-24 05:53 UTC, merged