scripts: Check that LunarG / Valve Copyright is updated
KhronosGroup/Vulkan-ValidationLayers pull request #5144
Opened 2023-01-21 00:01 UTC by juan-lunarg

See https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5142#discussion_r1083124269

2023-01-21 00:51 UTC, ncesario-lunarg approved these changes

2023-01-21 01:04 UTC, merged

2023-01-21 01:09 UTC, lunarpapillo requested changes
Bad script to start with... but your changes look good (at least no worse than the script around them).

I'd like to work with you to clean it up a bit.

I presume there's no Python standard for this project, and that `pylint` has never been run on this script...

2023-01-21 01:09 UTC, lunarpapillo commented on scripts/check_code_format.py
> +            copyright_match = re.search('Copyright .*(\d{4}) ' + company, open(file, encoding="utf-8", errors='ignore').read(1024))
Not your code, but this is pretty grisly.  It fails if the copyright isn't in the first 1K of the file, leaks an open file for every file it examines, breaks if two copyright lines for the same company appear in the file, regenerates `re` patterns repeatedly and needlessly, and relies on an obscure pattern match behavior (that `.` doesn't include a newline unless `re.M` is used).

Also, what should happen if no copyright is found in a given file?  I'd think that should be an error, but it isn't covered here.

I'll talk to you in person about a recommendation to clean this up (more code than I want to write in a web form).

2023-01-21 01:50 UTC, mark-lunarg commented on scripts/check_code_format.py
> +            copyright_match = re.search('Copyright .*(\d{4}) ' + company, open(file, encoding="utf-8", errors='ignore').read(1024))
"Grisly" eh? [Writes in a little notebook with a very short pencil].

2023-01-25 15:03 UTC, ncesario-lunarg commented on scripts/check_code_format.py
> +                    msg = 'Change written in {} but copyright ends in {}.'.format(commit_year, copyright_year)
We are using 3.7 as a minimum right, and I'll be bumping to 3.8 soon.

2023-01-25 16:28 UTC, lunarpapillo commented on scripts/check_code_format.py
> +                    msg = 'Change written in {} but copyright ends in {}.'.format(commit_year, copyright_year)
Please do a Python version check at the top of the script.  @Tony-LunarG already ran into confusion when he used an earlier Python.

With 3.7 using f-strings should be preferred over format strings.