Fix 06937 validation
KhronosGroup/Vulkan-ValidationLayers pull request #5335
Opened 2023-02-24 17:00 UTC by arno-lunarg

- Fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/4322

Updated tests:
`VkPositiveLayerTest.ClearRectWith2DArray`: Update frame buffer layers count so that clear call is valid
`VkLayerTest.SecondaryCommandBufferClearColorAttachmentsRenderArea`: Use `vk_testing::CommandBuffer`
`VkLayerTest.InvalidClearColorAttachmentsWithMultiview`: This test now (correctly) triggers 06937 , so set it set as a desired error
`VkLayerTest.DynamicRenderingCmdClearAttachmentTests` and `VkLayerTest.CmdClearAttachmentTests`: Update tests to account for validation change, and add test cases for secondary command buffers. Adding test cases for secondary command buffers lead to the modification in `cmd_buffer_validation.cpp` to properly validate them when using dynamic rendering.

2023-02-24 23:22 UTC, ncesario-lunarg reviewed
One questions, but this LGTM!

2023-02-24 23:22 UTC, ncesario-lunarg commented on layers/core_checks/image_validation.cpp
> +        if ((rect_base_layer >= render_pass_layer_count) || (rect_base_layer + rect_layer_count > render_pass_layer_count)) {
If `rect_base_layer` and `rect_layer_count` are always `>= 0`, then is the `rect_base_layer >= render_pass_layer_count` check needed, or is `rect_base_layer + rect_layer_count > render_pass_layer_count` sufficient?

2023-02-24 23:56 UTC, juan-lunarg requested changes
Failing Android CI

2023-02-24 23:56 UTC, juan-lunarg commented on layers/core_checks/cmd_buffer_validation.cpp
> +                        // Make sure render pass is compatible with parent command buffer pass if has continue
if has continue?

2023-02-27 16:35 UTC, arno-lunarg commented on layers/core_checks/cmd_buffer_validation.cpp
> +                        // Make sure render pass is compatible with parent command buffer pass if has continue
yes the comment is confusing, I updated it to 
> Make sure render pass is compatible with parent command buffer pass if secondary command buffer has "continue" flag

2023-02-27 17:15 UTC, ncesario-lunarg approved these changes

2023-02-27 17:17 UTC, arno-lunarg commented
Still have what looks like a crash in `VkPositiveLayerTest.ClearRectWith2DArray` on S10 and Pixel 6...

2023-02-28 02:36 UTC, spencer-lunarg commented
> Still have what looks like a crash in VkPositiveLayerTest.ClearRectWith2DArray

I looked into this, it is crashing on `vkCmdBeginRenderPass` and I made sure all things related to the framebuffer/renderPass are not violating any VUs

I am convinced this is a driver bug and that the correct course of action is to blacklist the test on Mali Android devices (the S10 and Pixel 6) and then for me to get an issue with CTS to add a test

2023-03-01 17:45 UTC, merged