Add VK_EXT_image_sliced_view_of_3d validation
KhronosGroup/Vulkan-ValidationLayers pull request #5350
Opened 2023-02-27 20:27 UTC by juan-lunarg

- layers: Add validation for VkImageViewSlicedCreateInfoEXT
- layers: Add testing for VkImageViewSlicedCreateInfoEXT

closes #5314

2023-02-27 20:29 UTC, juan-lunarg commented on tests/vklayertests_image.cpp
> +    m_errorMonitor->VerifyFound();
I believe I interpreted this VUID correctly. Would a appreciate a double check though:
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkImageViewSlicedCreateInfoEXT.html

2023-02-27 21:27 UTC, Tony-LunarG commented on tests/vklayertests_image.cpp
> +    m_errorMonitor->VerifyFound();
That's the way I read it

2023-02-27 22:08 UTC, juan-lunarg commented
> CI Vulkan-ValidationLayers build # 10887 failed.

Failed on VideoDecodeH264

```
[ RUN      ] VkPositiveVideoLayerTest.VideoDecodeH264
ERROR: -------------------------------------------------------------
ERROR: FAIL during test after 6.09 minutes (365.42 seconds) with execute(C:\j\vz2\Release32\Vulkan-ValidationLayers\build32\tests\Release\vk_layer_validation_tests.exe --gtest_catch_exceptions=0 --gtest_filter=-VkPositiveGraphicsLibraryLayerTest.NotAttachmentDynamicBlendEnable:VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB:VkVideoLayerTest.*) failed after 6.09 minutes (365.41 seconds) with returncode=3221225477 (0xc0000005=STATUS_ACCESS_VIOLATION)
INFO: Test run complete after 12.67 minutes (760.27 seconds)
```

@lunarpapillo looks like the video tests still aren't stable.

2023-02-27 22:17 UTC, lunarpapillo commented
> Failed on VideoDecodeH264?

From higher up:
```
INFO: executing #8: C:\j\vz2\Release32\Vulkan-ValidationLayers\build32\tests\Release\vk_layer_validation_tests.exe --gtest_catch_exceptions=0 --gtest_filter=-VkPositiveGraphicsLibraryLayerTest.NotAttachmentDynamicBlendEnable:VkGpuAssistedLayerTest.GpuBufferDeviceAddressOOB:VkVideoLayerTest.*
```
We're not yet disabling `VkPositiveVideoLayerTest.*`, only `VkVideoLayerTest.*`.  PR coming.

2023-02-27 23:14 UTC, Tony-LunarG requested changes
LGTM with one nit and one question
The commit message on the test commit starts with layers: instead of tests:
And I'm not comfortable enough with sync validation to know, but does IsDepthSliced need to be aware of a new way to make sliced images?

2023-02-27 23:14 UTC, Tony-LunarG commented on tests/positive/image_buffer.cpp
> +        return GetMipMapSize(ci.extent.depth, ivci.subresourceRange.baseMipLevel, ci.flags);
Is this testing GetMipMapSize?

2023-02-27 23:14 UTC, spencer-lunarg commented on layers/core_checks/image_validation.cpp
> +                             "vkCreateImageView(): imageSlicedViewOf3D not supported.");
nit: 

`supported` means the device support the feature
`enabled` means the user forgot to enable it

```suggestion
                             "vkCreateImageView(): imageSlicedViewOf3D not enabled.");
```

2023-02-27 23:19 UTC, spencer-lunarg approved these changes
LGTM with nits

2023-02-27 23:44 UTC, juan-lunarg commented on tests/positive/image_buffer.cpp
> +        return GetMipMapSize(ci.extent.depth, ivci.subresourceRange.baseMipLevel, ci.flags);
The intent is to make it clear to the reader of the test what the effective depth is/should-be at each point in the tests.

Let me know if that's too confusing. I thought it was useful since the VUID's in question reference the effective depth quite a bit.

2023-02-27 23:48 UTC, juan-lunarg commented on tests/positive/image_buffer.cpp
> +        return GetMipMapSize(ci.extent.depth, ivci.subresourceRange.baseMipLevel, ci.flags);
Also I guess it actually does test `GetMipMapSize` didn't consider that bonus :+1:

2023-02-27 23:56 UTC, juan-lunarg commented
> And I'm not comfortable enough with sync validation to know, but does IsDepthSliced need to be aware of a new way to make sliced images?

I'm not sure. + @jeremyg-lunarg for input.

2023-02-28 00:17 UTC, ncesario-lunarg approved these changes
LGTM!

2023-02-28 00:26 UTC, Tony-LunarG approved these changes

2023-02-28 11:18 UTC, HansKristian-Work commented on layers/core_checks/image_validation.cpp
> +        if (mip_level != 1) {
mip_level can be REMAINING_LEVELS if the image has 1 mip level.

2023-02-28 11:18 UTC, HansKristian-Work commented on layers/core_checks/image_validation.cpp
> +        if (mip_level != 1) {
>  The image view must reference exactly 1 mip level

Doesn't mean mipLevel must: be 1.

2023-02-28 18:38 UTC, juan-lunarg commented on layers/vk_layer_utils.h
> +constexpr uint32_t GetMipMapSize(uint32_t value, uint32_t levels, VkImageCreateFlags flags) {
I see what you are saying but it feels awkward to have in `IMAGE_STATE` since it requires information from the image view.

2023-02-28 19:24 UTC, juan-lunarg commented on layers/core_checks/image_validation.cpp
> +        if (mip_level != 1) {
Thanks for the catch :+1: . I added `GetLevelCount` to correctly calculate the number of effective mip levels.

2023-02-28 19:26 UTC, juan-lunarg commented on layers/vk_layer_utils.h
> +constexpr uint32_t GetMipMapSize(uint32_t value, uint32_t levels, VkImageCreateFlags flags) {
I rewrote this function to be `GetEffectiveExtent` which has stricter type checking to show the intent of when it should be used.

2023-02-28 19:27 UTC, juan-lunarg commented on layers/core_checks/image_validation.cpp
> +        const uint32_t effective_view_depth = GetEffectiveExtent(image_state->createInfo, pCreateInfo->subresourceRange).depth;
Note: This is slightly un-optimal. But it reads so much better and has stronger type safety.

2023-02-28 19:53 UTC, juan-lunarg commented on layers/core_checks/image_validation.cpp
> +        if (mip_level != 1) {
I also added extra testing to cover this cas

2023-02-28 20:32 UTC, HansKristian-Work approved these changes
The fix to mip levels LGTM.

2023-02-28 20:37 UTC, juan-lunarg commented
Note I need to update the validation to also validate the viewType. Not just the imageType.
https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5749

2023-02-28 20:43 UTC, juan-lunarg commented on layers/core_checks/image_validation.cpp
> +        }
Updated validation based on https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5749

Thanks for the quick turnaround @zmike :+1:

2023-02-28 22:55 UTC, merged