vkCmdClearAttachments sync validation
KhronosGroup/Vulkan-ValidationLayers pull request #5455
Opened 2023-03-16 23:37 UTC by artem-lunarg

2023-03-20 17:25 UTC, juan-lunarg requested changes

2023-03-20 17:25 UTC, juan-lunarg commented on layers/sync/sync_validation.cpp
> +    return attachment_index;
FFTI

```suggestion
    const bool invalid_index = (attachment_index == VK_ATTACHMENT_UNUSED || attachment_index >= rpci.attachmentCount);
    return invalid_index ? {} : attachment_index;
```

2023-03-20 17:25 UTC, juan-lunarg commented on layers/sync/sync_validation.cpp
> +    const uint32_t first = std::max(subresource_range.baseArrayLayer, subresource_range.baseArrayLayer);
?

This looks like a mistake. Which might mean more testing is needed.

2023-03-20 17:25 UTC, juan-lunarg commented on layers/sync/sync_validation.cpp
> +    const uint32_t last_range = subresource_range.baseArrayLayer + subresource_range.layerCount;
What if `layerCount == VK_REMAINING_ARRAY_LAYERS`?

See `ResolveRemainingLayers` helper function.

2023-03-20 19:02 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +    const uint32_t first = std::max(subresource_range.baseArrayLayer, subresource_range.baseArrayLayer);
Nice catch, thanks!

2023-03-20 19:08 UTC, juan-lunarg commented on tests/negative/sync_val.cpp
> +    // Positive test: regions touch but do not overlap. Copy to the first region, clear the second region.
Minor nitpick. Positive testing should go in the positive testing folder.

2023-03-20 19:08 UTC, juan-lunarg commented on tests/framework/render.h
> +    const VkImageView &targetView(VkImageViewCreateInfo ci) {
What's the advantage of const reference here? VkImageView is just a handle (IE a pointer).

2023-03-20 19:14 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +    const uint32_t last_range = subresource_range.baseArrayLayer + subresource_range.layerCount;
It can't be in this context. Normalized subresource range is passed as the first parameter (`view_state.normalized_subresource_range`). And according VkClearRect documentation it does not use special numbers. But I will add assert to check anyway, since bugs like these are likely.

2023-03-20 19:22 UTC, artem-lunarg commented on tests/framework/render.h
> +    const VkImageView &targetView(VkImageViewCreateInfo ci) {
So, it's similar to what we have for some other types. It helps with a situation when Vulkan API accepts pointer to handle. Then it's possible to write
```
vk_struct.pView = &targetView();
```

Otherwise we need local variable.
Initially I used this in this PR but then needed array, so it's unused now.
One example is `Handle` type:
```
template <typename T>
class Handle {
  public:
    const T &handle() const noexcept { return handle_; }
```

2023-03-20 19:38 UTC, juan-lunarg commented on tests/framework/render.h
> +    const VkImageView &targetView(VkImageViewCreateInfo ci) {
Gotcha that makes sense :+1:

2023-03-20 22:53 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +    const uint32_t first = std::max(subresource_range.baseArrayLayer, subresource_range.baseArrayLayer);
Added positive test that caught that issue.

2023-03-20 22:59 UTC, artem-lunarg commented on tests/negative/sync_val.cpp
> +    // Positive test: regions touch but do not overlap. Copy to the first region, clear the second region.
New positive test now in the new positive folder. The old positive test is part of  a single scenario, so I keep it, but removed the comment that it's a positive test. FWIW, we sometimes do that in the negative tests - show that some parameters do not cause errors before/after going with the negative test scenario.

2023-03-21 02:15 UTC, spencer-lunarg commented on layers/sync/sync_validation.cpp
> +    if (first >= last) return {};
so is the `{}` here the same as returning `std::optional<VkImageSubresourceRange>()`?

Or is this returning an empty struct?

2023-03-21 02:16 UTC, spencer-lunarg approved these changes

2023-03-21 08:52 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +    if (first >= last) return {};
Good question. I checked and this constructs empty `std::optional`. It's also possible to return `std::nullopt` to make it more clear.

2023-03-21 16:01 UTC, juan-lunarg commented on layers/sync/sync_validation.cpp
> +    if (first >= last) return {};
I personally find returning `{};` readable here. Since the function is small enough you can see the return type.

2023-03-21 16:11 UTC, ncesario-lunarg approved these changes
LGTM, but it would be good if one of the sync wizards could also sign off.

2023-03-21 21:46 UTC, jzulauf-lunarg requested changes
A couple of nits, a couple correctness issues.

2023-03-21 21:46 UTC, jzulauf-lunarg commented on layers/sync/sync_validation.cpp
> +        ((clear_aspect_mask & view_aspect_mask) & (VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_STENCIL_BIT)) != 0;
why is the `clear_aspect_mask` in this?

2023-03-21 21:46 UTC, jzulauf-lunarg commented on layers/sync/sync_validation.cpp
> +    return result;
Not a fan of this.  `result` is auto, so the type in non-obvious.  The construction of the returned optional is implicit... so it smells a bit magic.

Would think something like the below more clear/maintainable...  or is that too old school?

```
std::optional<VkImageSubresourceRange> result;
if (first >= last) {
    result.emplace(normalized_ ...
    result->baseArray ... // touch up result
    ...
}
return result;
```

2023-03-21 21:46 UTC, jzulauf-lunarg commented on layers/sync/sync_validation.cpp
> +namespace ClearAttachmentHelper {
Not that we've been consistent about namespace uses, but I've been placing localized functionality like this a class and struct member of the the class needing the functionality, in this case `RenderPassAccessContext`.

Eventually, too support dynamic rendering they'll likely be some base RenderingAccessContext call for RP and dynamic rendering subclasses this could be moved into (or specialized between).

Also saves needing to namespace qualifiying in the RenderpassAccessContext methods below.

Style thoughts @ncesario-lunarg @juan-lunarg @jeremyg-lunarg ?

2023-03-21 21:46 UTC, jzulauf-lunarg commented on layers/sync/sync_validation.cpp
> +        HazardResult hazard = CurrentContext().DetectHazard(image_state, SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE,
Probably needs a comment describing why LATE_FRAGMENT... is being used (because it's after EARLY and thus the "most recent access" per the design approach)

2023-03-21 21:46 UTC, jzulauf-lunarg commented on layers/sync/sync_validation.cpp
> +bool RenderPassAccessContext::ValidateClearAttachment(const CommandExecutionContext &exec_context,
Probably want to report which rectangle from pRect's is hazarding, by passing in the rect index.

2023-03-21 21:46 UTC, jzulauf-lunarg commented on layers/sync/sync_validation.cpp
> +    if (clear_attachment.aspectMask & VK_IMAGE_ASPECT_COLOR_BIT) {
Hazard detection and reporting could be DRY'r.  See ValidateLoadOperation for ideas.

2023-03-21 21:46 UTC, jzulauf-lunarg commented on layers/sync/sync_validation.cpp
> +        subresource_range->aspectMask = VK_IMAGE_ASPECT_STENCIL_BIT;
we shouldn't be changing the subresource_range, because we need to check if the aspect is *both* in the view and the ClearAttachment correct?  What if the clear_attachment.aspectMask has both D/S and the view only has one... is that a noop, or just ignore the aspect not in the view?

2023-03-21 21:46 UTC, jzulauf-lunarg commented on layers/sync/sync_validation.cpp
> +        subresource_range->aspectMask &= (VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_STENCIL_BIT);
The subresource range should only include the aspects in both the view and clear masks.

2023-03-21 21:51 UTC, juan-lunarg commented on layers/sync/sync_validation.cpp
> +namespace ClearAttachmentHelper {
Personally since the functions are local to this cpp file I think a nameless namespace is most appropriate. Nameless namespaces are intended to replace the `static` keyword for functions (Which is pretty overloaded).

When I see a namespace I assume these functions are exposed in the public interface (IE the header file).

But these are just my opinions.

2023-03-21 22:20 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +namespace ClearAttachmentHelper {
>  Nameless namespaces are intended to replace the static keyword for functions (Which is pretty overloaded)
There is one drawback in nameless namespaces, in my opinion. One example, we have a function in a cpp file:
```
void f() {}
```
And just by looking into it it's unclear if it's function with linkage or not because nameless namespace can be far away and static keyword is local to the function.

2023-03-21 22:22 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +bool RenderPassAccessContext::ValidateClearAttachment(const CommandExecutionContext &exec_context,
💯

2023-03-21 22:34 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +        ((clear_aspect_mask & view_aspect_mask) & (VK_IMAGE_ASPECT_DEPTH_BIT | VK_IMAGE_ASPECT_STENCIL_BIT)) != 0;
One example. `clear_aspect_mask` specifies `VK_IMAGE_ASPECT_DEPTH_BIT` and `view_aspect_mask` speficies `VK_IMAGE_ASPECT_STENCIL_BIT` then there is not depth aspect in the view to clear, according to spec nothing should happen. For color aspect we can have only single aspect and that's the reason why it have simple `can_clear_color` condition.

2023-03-21 22:40 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +namespace ClearAttachmentHelper {
Initially it was struct and later I replaced it with a namespace. The idea was that these functions are related only to `clear attachment` code and not very useful in other parts. So `struct` might be an option if you think it's better.

2023-03-21 22:45 UTC, juan-lunarg commented on layers/sync/sync_validation.cpp
> +namespace ClearAttachmentHelper {
I personally think the code is readable and straightforward.

2023-03-21 22:52 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +    return result;
This version looks good. One thing I personally prefer more, if we have opportunity to return specific value, for example `false` and then I like to return just that constant instead of relying on `result` variable's initial value. By returning result you still need to apply some min amount of mental effort to check that `result` was not changed after initialization. But it looks different people have different tastes here and I don't think this is something fundamental. Will go with suggested change.

2023-03-22 14:15 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +        subresource_range->aspectMask = VK_IMAGE_ASPECT_STENCIL_BIT;
Good catch, thanks!

In your example, I assumed it's noop. According to spec:
> If any attachment’s aspectMask to be cleared is not backed by an image view, the clear has no effect on that aspect.

2023-03-22 15:09 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +        subresource_range->aspectMask = VK_IMAGE_ASPECT_STENCIL_BIT;
Replaced `CanClear` helper with `GetAspectsToClear` that returns the exact set of aspects that should be cleared, thus it removes the need for more complex checks later that _view_ and _clear_ masks have to match.

View subresource's aspect still should be updated, added comments to clarify this.

2023-03-23 01:16 UTC, jzulauf-lunarg requested changes
Aspect mask issues, I believe.  Check on my assertion that only a single bit can be set, but in any case clear mask COLOR -> view aspect mask (either COLOR or the plane (planes)) in terms of the memory affected.

2023-03-23 01:16 UTC, jzulauf-lunarg commented on layers/sync/sync_validation.cpp
> +    if (info->aspects_to_clear & VK_IMAGE_ASPECT_COLOR_BIT) {
If we change aspect_to_clear above, we'll need to change this test too.

2023-03-23 01:16 UTC, jzulauf-lunarg commented on layers/sync/sync_validation.cpp
> +    if (info->aspects_to_clear & VK_IMAGE_ASPECT_COLOR_BIT) {
and again here.

2023-03-23 01:16 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +    if (clear_attachment.aspectMask & VK_IMAGE_ASPECT_COLOR_BIT) {
Merged some similar depth and stencil code and also added helper method to extract identical initialization in Validate and Record.

2023-03-23 01:56 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +    if (clear_color && (view_aspect_mask & color_aspects) != 0) {
Thanks, that's valuable clarification. I discussed this some time ago with Spencer and there were open questions about this part, but this explanation makes sense and fits the spec.

2023-03-27 22:08 UTC, artem-lunarg commented
@jzulauf-lunarg the requested changes are implemented. Please fill free to check them when you have opportunity.

2023-03-28 03:44 UTC, jzulauf-lunarg approved these changes
LGTM

2023-03-28 12:46 UTC, merged