Add validation for vkMap/UnmapMemory2KHR
KhronosGroup/Vulkan-ValidationLayers pull request #5475
Opened 2023-03-21 17:30 UTC by gfxstrand

2023-03-21 17:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5475) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5475) before we can accept your contribution.<br/><hr/>**Faith Ekstrand** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5475) it.</sub>

2023-03-21 18:10 UTC, juan-lunarg submitted a review, later dismissed
Positive/negative testing is required to ensure the new validation is valid.

2023-03-21 18:32 UTC, gfxstrand commented on .mailmap
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5476

2023-03-21 19:19 UTC, juan-lunarg commented
> Positive/negative testing is required to ensure the new validation is valid.

See PR #5350 for an example of adding validation + positive/negative testing.

Note: Negative testing is now in the tests/negative folder.

2023-03-21 22:50 UTC, ncesario-lunarg reviewed
This mostly LGTM with some minor nits. The only potential problem is updating the header version, which we will probably want to wait for @mikes-lunarg.

2023-03-21 22:50 UTC, ncesario-lunarg commented on scripts/known_good.json
> +            "commit": "v1.3.244"
Usually @mikes-lunarg handles updating the header version. There are some other things that need to happen related to header updates (`build-android/known_good.json` needs to be updated, git tags, other repos that rely on Vulkan-ValidationLayers I think also need to get updated). If this change relies on the 1.3.244 header, it might be better to wait for that to go in separately, and/or coordinate with Mike.

2023-03-22 14:12 UTC, gfxstrand commented
Is the CI running the unit tests?  I couldn't figure out how to run them locally.

2023-03-22 14:12 UTC, gfxstrand commented on scripts/known_good.json
> +            "commit": "v1.3.244"
That's fine.  This can wait until Mike does an update. That's why I did it as a separate patch. :grinning:

2023-03-22 14:22 UTC, gfxstrand commented on layers/core_checks/device_memory_validation.cpp
> +                            report_data->FormatHandle(pMemoryMapInfo->memory).c_str());
What I did here is exactly identical to the `vkMapMemory()` validation.  Would you like me to fix up both?

2023-03-22 17:25 UTC, juan-lunarg commented
> Is the CI running the unit tests? I couldn't figure out how to run them locally.

Our GitHub actions CI tests against the mock driver we use. And that can be run locally with  `scripts/github_ci_win_linux.py`. It's been very useful for catching address sanitization issues and working on cutting edge extensions (Also not having to worry about driver bugs).

But you are passing those tests.

We have a secondary CI process with jenkins using multiple real GPUs (AMD, Nvidia, Pixel, M1, etc) which needs to be triggered by LunarG employees. The results also can only be seen by LunarG employees. We are working on making this process better for open source contributors. Apologies for the inconvenience.

2023-03-22 17:28 UTC, juan-lunarg commented
Note the newly added testing isn't being run by the Mock driver:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/4483965347/jobs/7883927844?pr=5475

`Vulkan-Profiles` will also need a header update in order for the new testing to be run.

```
[ RUN      ] VkLayerTest.InvalidMemoryMapping2
../tests/negative/memory.cpp:196: Skipped
VK_KHR_map_memory2 not supported
[  SKIPPED ] VkLayerTest.InvalidMemoryMapping2 (2 ms)
```

2023-03-22 17:33 UTC, juan-lunarg commented on tests/positive/memory.cpp
> + * Copyright (c) 2015-2023 Google, Inc.
```suggestion
 * Copyright (c) 2023 The Khronos Group Inc.
 * Copyright (c) 2023 Valve Corporation
 * Copyright (c) 2023 LunarG, Inc.
 * Copyright (c) 2023 Collabora, Inc.
```

2023-03-22 17:33 UTC, juan-lunarg commented on scripts/known_good.json
> +            "commit": "v1.3.244"
As noted we will also need an update for Vulkan Profiles in order for the mock testing to be run.

2023-03-22 17:33 UTC, juan-lunarg commented on layers/core_checks/device_memory_validation.cpp
> +                            report_data->FormatHandle(pMemoryMapInfo->memory).c_str());
Fixing up both is best. We are working to improve the clarity of our error messages.

2023-03-22 18:44 UTC, juan-lunarg commented
> CI Vulkan-ValidationLayers build # 11289 failed.

Failed due to same Android build failure that GitHub CI is showing.

2023-03-22 20:06 UTC, gfxstrand commented on scripts/known_good.json
> +            "commit": "v1.3.244"
Works for me. I'm happy to let this sit for a couple days if needed. Sorry I'm so ahead of the curve. :stuck_out_tongue_closed_eyes:

2023-03-22 21:38 UTC, juan-lunarg commented
> Looks like that's due to a missing header update somewhere in a "jni" folder. Is that something I can fix? Or do we just need to wait for all the updates?

I'd just wait for @mikes-lunarg's change and then rebase

I'd also wait until Vulkan-Profiles updates it's version of Vulkan-Headers (@christophe-lunarg )

2023-03-23 03:51 UTC, mikes-lunarg commented
#5485 is merged, rebasing should fix the android build failures.

2023-03-23 17:27 UTC, juan-lunarg commented
Once this is merged re-run the tests to ensure the new tests are passing with the Mock driver:
https://github.com/KhronosGroup/Vulkan-Profiles/pull/382

A force push will re-trigger the testing. Or you can use github cli.

2023-03-23 19:05 UTC, juan-lunarg commented
Profiles has been updated. Please force push to verify new testing has passed on the mock driver.

2023-03-23 21:04 UTC, juan-lunarg requested changes
Tests are not being run.

2023-03-23 21:04 UTC, juan-lunarg commented on tests/negative/memory.cpp
> +    ASSERT_NO_FATAL_FAILURE(InitState());
```suggestion
    AddRequiredExtensions(VK_KHR_MAP_MEMORY_2_EXTENSION_NAME);

    ASSERT_NO_FATAL_FAILURE(Init());

    if (!AreRequiredExtensionsEnabled()) {
        GTEST_SKIP() << RequiredExtensionsNotSupported() << " not supported";
    }
```

2023-03-23 21:07 UTC, juan-lunarg commented on tests/negative/memory.cpp
> +    ASSERT_NO_FATAL_FAILURE(InitState());
See https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/tests/README.md

2023-03-23 21:10 UTC, juan-lunarg commented on tests/negative/memory.cpp
> +    ASSERT_NO_FATAL_FAILURE(InitState());
Note this feedback applies to both new tests. Also this test has a validation error and will not pass as is:

```
Validation Error: [ VUID-vkDestroyDevice-device-00378 ] Object 0: handle = 0x5555581179f0, type = VK_OBJECT_TYPE_DEVICE; Object 1: handle = 0xfa21a40000000003, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0x71500fba | OBJ ERROR : For VkDevice 0x5555581179f0[], VkDeviceMemory 0xfa21a40000000003[] has not been destroyed. The Vulkan spec states: All child objects created on device must have been destroyed prior to destroying device (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
```

2023-03-24 16:48 UTC, juan-lunarg reviewed
I think overall it looks good :+1: 

Just some nitpicks/comments/suggestions.

2023-03-24 16:48 UTC, juan-lunarg commented on tests/positive/memory.cpp
> +    bool pass = m_device->phy().set_memory_type(~0u, &memory_info, VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT);
Use the STL or the provided constants in the vvl namespace.

```suggestion
    const bool pass = m_device->phy().set_memory_type(vvl::kU32Max, &memory_info, VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT);
```

2023-03-24 16:48 UTC, juan-lunarg commented on tests/negative/memory.cpp
> +    static const VkDeviceSize allocation_size = atom_size * 64;
Why does this variable need to be static?

2023-03-24 16:48 UTC, juan-lunarg commented on layers/core_checks/device_memory_validation.cpp
> +                         "VUID-VkMemoryUnmapInfoKHR-memory-07964", "Unmapping Memory without memory being mapped: %s.",
FFTI but given the simplicity of the vuid/fix for a vulkan dev, I think a concise message is best.

```suggestion
                         "VUID-VkMemoryUnmapInfoKHR-memory-07964", "Invalid memory unmapping: %s.",
```

2023-03-24 16:48 UTC, juan-lunarg commented on layers/core_checks/device_memory_validation.cpp
> +                            "Memory (%s) must not have been allocated with multiple instances",
Currently this error message just repeat the VUID description which isn't very helpful to users.

2023-03-24 16:48 UTC, juan-lunarg commented on layers/core_checks/device_memory_validation.cpp
> +            phys_dev_mem_props.memoryTypes[mem_info->alloc_info.memoryTypeIndex].propertyFlags;
Place `mem_info->alloc_info.memoryTypeIndex` to avoid minor code duplication.

2023-03-24 16:48 UTC, juan-lunarg commented on layers/core_checks/device_memory_validation.cpp
> +                            "Mapping Memory without VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT set. "
```suggestion
                            "Mapping memory without VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT set. "
```

2023-03-24 16:48 UTC, juan-lunarg commented on layers/core_checks/device_memory_validation.cpp
> +            phys_dev_mem_props.memoryTypes[mem_info->alloc_info.memoryTypeIndex].propertyFlags;
Place `mem_info->alloc_info.memoryTypeIndex` to avoid minor code duplication.

2023-03-24 16:48 UTC, juan-lunarg commented on layers/core_checks/device_memory_validation.cpp
> +                        "VkMapMemory: Attempting to map memory range of size zero");
To avoid potential confusion perhaps best to not prefix the function?

```suggestion
                        "Attempting to map memory range of size zero");
```

2023-03-24 16:48 UTC, juan-lunarg commented on layers/core_checks/device_memory_validation.cpp
>      if (offset >= mem_info->alloc_info.allocationSize) {
Place `mem_info->alloc_info.allocationSize` into a variable to avoid code duplication.

2023-03-24 16:50 UTC, juan-lunarg commented on tests/negative/memory.cpp
> +TEST_F(VkLayerTest, InvalidMemoryMapping2) {
My rational is to make it easier to run the positive/negative test at the same time. By having the same name you can do this:

```
//"--gtest_filter=*SlicedCreateInfo*" // As an example.
```

Also invalid is implied by the negative folder.

2023-03-24 16:51 UTC, juan-lunarg commented on layers/core_checks/device_memory_validation.cpp
> +                            "Memory (%s) must not have been allocated with multiple instances",
The VUID description is appended in the log message when given a valid VUID.

2023-03-24 17:12 UTC, gfxstrand commented on layers/core_checks/device_memory_validation.cpp
> +                            "Memory (%s) must not have been allocated with multiple instances",
Replaced it with "Memory allocated with multiple instances" in both the `vkMapMemory()` and `vkMapMemory2KHR()` validators and we'll let the automatic VUID printing do the rest.

2023-03-24 17:58 UTC, gfxstrand commented on tests/negative/memory.cpp
> +    static const VkDeviceSize allocation_size = atom_size * 64;
I just copied and pasted from the other tests.  I don't have good justification for any of the set-up code here.

2023-03-24 18:04 UTC, gfxstrand commented on tests/positive/memory.cpp
> +    memory_info.allocationSize = 64 << 10;
64K is a size that I know, based on over-all hardware knowledge, is a whole number of pages for everyone.  It's also the maximum sparse block size for whatever that's worth.

What's the right size?  IDK.  Technically, I think Vulkan will let us allocate 5B if we want.  You'll get way more than that and mappings will end up being at 4K or 16K boundaries or something like that but you're allowed to pretend your memory object is 5B.  The negative tests I copied created a buffer and used that to get memory requirements and then allocated memory.  I could do that here too if you want but it seems unnecessary.

I'm happy to do whatever. IDK what the standard thing for your unit tests is.  If you want me to allocate a buffer instead of choosing a size arbitrarily, I can do that.  If you'd rather not have the buffer allocation clutter, I can do that too.  We should probably make them match between the positive/negative ones, I suppose.

2023-03-24 18:19 UTC, juan-lunarg commented on tests/positive/memory.cpp
> +    memory_info.allocationSize = 64 << 10;
:+1:  explanation

2023-03-24 19:24 UTC, gfxstrand commented on tests/positive/memory.cpp
> +    memory_info.allocationSize = 64 << 10;
Ok, I've switched both tests to the direct allocate method that I used in the positive tests here. I've made `allocation_size` a separate variable with a comment as to why I chose 64KB.

2023-03-24 19:50 UTC, ncesario-lunarg approved these changes
LGTM!

2023-03-24 21:17 UTC, merged

2023-03-24 21:19 UTC, juan-lunarg commented
Thank you for the contribution + testing :+1: