layers: Mask fragment shader state with rasterizerDiscard
KhronosGroup/Vulkan-ValidationLayers pull request #5478
Opened 2023-03-21 21:37 UTC by HansKristian-Work

It is possible to encounter VUID 06590 as a false positive if rasterizer discard is used. Fragment output state was masked out (incorrectly, since it did not consider dynamic state), and fragment shader state was not masked at all.

Ran into this in vkd3d-proton test suite.

2023-03-21 21:54 UTC, juan-lunarg requested changes
Add a positive test to prevent a regression.

Positive tests are now under `tests/positive`

2023-03-22 21:59 UTC, juan-lunarg commented
> [  FAILED  ] VkPositiveLayerTest.CreateGraphicsPipelineWithIgnoredPointers
> [  FAILED  ] VkPositiveLayerTest.TestRasterizationDiscardEnableTrue
> [  FAILED  ] VkPositiveLayerTest.AttachmentsDisableRasterization

Looks like the following tests will need to be updated in order for this change to be merged in. Let us know if you need assistance with the testing.

2023-03-23 05:05 UTC, ncesario-lunarg reviewed
LGTM, but it sounds like we need a positive test to for this.

2023-03-28 22:37 UTC, juan-lunarg requested changes

2023-03-28 22:37 UTC, juan-lunarg commented on layers/state_tracker/pipeline_state.cpp
> +    if (!EnablesRasterizationStates(safe_create_info)) {
The following tests are failing because of this line.

```
The following tests FAILED:
        1554 - VkGraphicsLibraryLayerTest.MissingDSStateWithFragOutputState (Failed)
        1555 - VkGraphicsLibraryLayerTest.MissingColorBlendState (Failed)
```

The safe_create_info sets `pRasterizationState` to `null`. See line 368.

Using the `raw` `create_info` makes these tests pass.

2023-03-28 22:48 UTC, juan-lunarg commented on layers/stateless/parameter_validation_utils.cpp
> +                        if (swizzle_viewport_count < viewport_count) {
I noticed the test related to `VUID-VkPipelineViewportSwizzleStateCreateInfoNV-viewportCount-01215` was failing and after taking a look I noticed 2 things.

The VUID needed to be updated.

`VUID-VkPipelineViewportSwizzleStateCreateInfoNV-viewportCount-01215`
> viewportCount must be greater than or equal to the viewportCount set in VkPipelineViewportStateCreateInfo

And the corresponding test was confusing to debug. So I fixed both.

2023-03-28 23:10 UTC, juan-lunarg commented
With the latest commit only 3 tests are failing. 2 of which have been root caused.

2023-03-29 14:23 UTC, HansKristian-Work commented
> With the latest commit only 3 tests are failing. 2 of which have been root caused.

I cannot reproduce those failures locally. Not sure what to do.

2023-03-29 19:08 UTC, juan-lunarg commented
> I cannot reproduce those failures locally. Not sure what to do.

Are you using the mock driver?

2023-03-29 19:47 UTC, juan-lunarg commented on layers/stateless/parameter_validation_utils.cpp
> +                        if (swizzle_viewport_count < viewport_count) {
I've cherry picked this fix into https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5531 instead.

2023-03-29 19:54 UTC, juan-lunarg commented
> I cannot reproduce those failures locally. Not sure what to do.

How are you running the tests locally? Which driver?

Are you using the mock driver setup?

https://github.com/KhronosGroup/Vulkan-ValidationLayers/tree/main/tests#running-tests-on-mockicd-and-profiles-layer

2023-03-29 20:00 UTC, juan-lunarg commented
Running the follow on linux should assist you in reproducing the failures on github actions:

```bash
python3 scripts/github_ci_win_linux.py --build --config debug

export VK_KHRONOS_PROFILES_PROFILE_FILE='/home/juan/projects/vvl/tests/device_profiles/max_profile.json'

python3 scripts/github_ci_win_linux.py --test
```

2023-03-30 10:36 UTC, HansKristian-Work commented on layers/stateless/parameter_validation_utils.cpp
> +                        if (swizzle_viewport_count < viewport_count) {
I guess I should wait for that to be merged then rebase?

2023-03-30 16:09 UTC, juan-lunarg commented
Note: Rebasing on main will now address the `ViewportSwizzleNV` failure as of a87ccbef876c4fa3e478d1d4f19a8c6bc346eab8

2023-03-31 00:13 UTC, juan-lunarg commented on layers/state_tracker/pipeline_state.cpp
> +    if (!EnablesRasterizationStates(safe_create_info)) {
+ @ncesario-lunarg for advice here

2023-03-31 03:11 UTC, spencer-lunarg commented
@HansKristian-Work I pulled this down and rebased, seems there are some issues with the GPL tests, if you apply the following, rebase, should fix CI and be good to go

```patch
diff --git a/tests/framework/layer_validation_tests.cpp b/tests/framework/layer_validation_tests.cpp
index d27dcadf8..f42e89f68 100644
--- a/tests/framework/layer_validation_tests.cpp
+++ b/tests/framework/layer_validation_tests.cpp
@@ -1896,6 +1896,7 @@ void CreatePipelineHelper::InitFragmentOutputLibInfo(void *p_next) {
     gp_ci_.flags = VK_PIPELINE_CREATE_LIBRARY_BIT_KHR | VK_PIPELINE_CREATE_RETAIN_LINK_TIME_OPTIMIZATION_INFO_BIT_EXT;
     gp_ci_.pColorBlendState = &cb_ci_;
     gp_ci_.pMultisampleState = &pipe_ms_state_ci_;
+    gp_ci_.pRasterizationState = &rs_state_ci_;
     gp_ci_.renderPass = layer_test_.renderPass();
     gp_ci_.subpass = 0;
 
diff --git a/tests/negative/dynamic_rendering.cpp b/tests/negative/dynamic_rendering.cpp
index aedee8b96..8170ad506 100644
--- a/tests/negative/dynamic_rendering.cpp
+++ b/tests/negative/dynamic_rendering.cpp
@@ -3540,6 +3540,8 @@ TEST_F(VkLayerTest, DynamicRenderingInvalidLibraryRenderPass) {
     pipe.InitFragmentLibInfo(1, &fs_stage_ci, &library_create_info);
     pipe.gp_ci_.renderPass = VK_NULL_HANDLE;
     pipe.InitState();
+    // If not Frag Output with frag shader, need depth/stencil struct
+    pipe.ds_ci_ = LvlInitStruct<VkPipelineDepthStencilStateCreateInfo>();
     m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "VUID-VkGraphicsPipelineCreateInfo-renderpass-06625");
     pipe.CreateGraphicsPipeline();
     m_errorMonitor->VerifyFound();
```

2023-03-31 18:15 UTC, juan-lunarg commented
Mock driver tests are now all passing :100: 

Here are the remaining issues.

`VkDebugPrintfTest.GpuDebugPrintfGPL` is failing on Windows (MockDriver skips this test):
> [ RUN      ] VkDebugPrintfTest.GpuDebugPrintfGPL
ERROR: ----stderr---------------------------------------------------
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector(110) : Assertion failed: cannot seek value-initialized vector iterator
ERROR: -------------------------------------------------------------

The following tests are failing on MacOS:

```
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] VkPortabilitySubsetTest.CreateGraphicsPipelinesTriangleFans
[  FAILED  ] VkPortabilitySubsetTest.CreateGraphicsPipelinesVertexInputStride
[  FAILED  ] VkPortabilitySubsetTest.CreateGraphicsPipelinesVertexAttributes
[  FAILED  ] VkPortabilitySubsetTest.CreateGraphicsPipelinesDepthStencilState
```

2023-04-01 00:59 UTC, spencer-lunarg commented
> The following tests are failing on MacOS:

This **might** be related this what I just found recently https://gitlab.khronos.org/vulkan/vulkan/-/issues/3436

2023-04-05 18:12 UTC, juan-lunarg commented
Once my PR gets merged in you can test the portability failures on linux/windows by setting `VK_KHRONOS_PROFILES_EMULATE_PORTABILITY` to `true`
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5578

2023-04-10 07:38 UTC, spencer-lunarg commented
Looking at the failing tests, its the same issue I had in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5385

> https://gitlab.khronos.org/vulkan/vulkan/-/issues/3436

They didn't get to it last Friday, so I think the fix for now is to make it so if you are using `VK_KHR_portability_subset` and a graphics pipeline library, we just return out of the validation check as this intersection is not possible with the given VU for portability

I just added this in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5385 - so lets try to get that merged quick (since its a simple PR), rebase this and this should be ready to go then

2023-04-11 08:56 UTC, spencer-lunarg commented
So looking more into this, 

1. I was able to get all tests running except 2 (`VkGraphicsLibraryLayerTest.InvalidLayouts, VkGraphicsLibraryLayerTest.IncompatibleLayouts`) because when we link all the stages together it is failing in `CreateFragmentOutputState` from `EnablesRasterizationStates`,

[5478.patch.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/11198632/5478.patch.txt)

2. There seems to be some duplicate work going on here, in `vk_safe_struct.cpp` we have

```cpp
bool is_dynamic_has_rasterization = false;
if (in_struct->pDynamicState && in_struct->pDynamicState->pDynamicStates) {
    for (uint32_t i = 0; i < in_struct->pDynamicState->dynamicStateCount && !is_dynamic_has_rasterization; ++i)
        if (in_struct->pDynamicState->pDynamicStates[i] == VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE_EXT)
            is_dynamic_has_rasterization = true;
}
const bool has_rasterization = in_struct->pRasterizationState ? (is_dynamic_has_rasterization || !in_struct->pRasterizationState->rasterizerDiscardEnable) : false;

//...
if (in_struct->pColorBlendState && ((has_rasterization && uses_color_attachment) || is_graphics_library))
    pColorBlendState = new safe_VkPipelineColorBlendStateCreateInfo(in_struct->pColorBlendState);
else
    pColorBlendState = nullptr; // original pColorBlendState pointer ignored
 ```

2023-04-11 12:20 UTC, HansKristian-Work commented
Is there anything actionable for me to do here? I'm unable to do meaningful development on macOS.

2023-04-11 19:22 UTC, ncesario-lunarg commented on layers/state_tracker/pipeline_state.cpp
> +        if (ss && EnablesRasterizationStates(ss->parent.create_info.graphics)) {
I'm not 100% sure, but I think this might need to be:
```cpp
if (ss && EnablesRasterizationStates(ss->parent.create_info.graphics) && EnablesRasterizationStates(safe_create_info)) {
```
If that's true, then I would re-order the checks a bit, as that condition needs to be checked in both `if` branches.

2023-04-11 19:24 UTC, ncesario-lunarg commented
@HansKristian-Work I added my changes in a separate commit (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5478/commits/ee82e8418fd4aa3ad65f27db43e6167df79c4dbf). Can you please take a look at those changes as well as the comment I added?

2023-04-14 23:13 UTC, juan-lunarg commented
portability tests should pass now with the latest commit. I tested with the mock driver however, so we will see.

2023-04-14 23:27 UTC, juan-lunarg approved these changes
LGTM on passing CI

2023-04-14 23:27 UTC, juan-lunarg commented on layers/gpu_validation/debug_printf.cpp
> +        assert(pgm.size() != 0);
```suggestion
        assert(!pgm.empty());
```

2023-04-15 00:41 UTC, merged