build: Fix LunarG/VulkanTools build
KhronosGroup/Vulkan-ValidationLayers pull request #5488
Opened 2023-03-22 22:08 UTC by juan-lunarg

Currently Lunarg/VulkanTools depends on VkLayer_utils, and recent changes broke the expected interface.

2023-03-22 22:17 UTC, mark-lunarg commented on layers/vk_layer_logging.cpp
> -VKAPI_ATTR bool LogMsg(const debug_report_data *debug_data, VkFlags msg_flags, const LogObjectList &objects, const std::string &vuid_text, const char *format, va_list argptr) {
Hard to tell but some of these seem to be whitespace/formatting changes -- is this a generated file?  If not, it'd be better for such changes to be in a separate commit/PR maybe?

2023-03-22 22:22 UTC, juan-lunarg commented on layers/vk_layer_logging.cpp
> -VKAPI_ATTR bool LogMsg(const debug_report_data *debug_data, VkFlags msg_flags, const LogObjectList &objects, const std::string &vuid_text, const char *format, va_list argptr) {
It's not a generated file the formatting was done on accident.

2023-03-22 22:25 UTC, juan-lunarg commented on layers/vk_layer_logging.cpp
> -VKAPI_ATTR bool LogMsg(const debug_report_data *debug_data, VkFlags msg_flags, const LogObjectList &objects, const std::string &vuid_text, const char *format, va_list argptr) {
Fixed accidental formatting

2023-03-22 22:26 UTC, lunarpapillo requested changes
I'm trying to understand the overview here..  With extensive movement of files in `BUILD.gn`, `CMakeLists.txt`, and `Android.mk`, how was the VVL build not completely broken before this commit?

2023-03-22 22:26 UTC, lunarpapillo commented on layers/vk_layer_logging.cpp
> +                                         uint64_t callback) {
The changes in this file seem to be whitespace changes only.  Why are they here?

2023-03-22 22:26 UTC, lunarpapillo commented on layers/xxhash.cpp
> +/* Copyright (c) 2023 The Khronos Group Inc.
This file looks like a functional duplicate of the `layers/external/xhash.cpp` file that was marked deleted above - but the copyright notice is different.  The last time I checked, we weren't allowed to modify copyright notices in that way.

2023-03-22 22:41 UTC, juan-lunarg commented on layers/xxhash.cpp
> +/* Copyright (c) 2023 The Khronos Group Inc.
This file wasn't created by xxhash devs. This is a file we created. It should have been using our copyright in the first place.

2023-03-22 22:42 UTC, juan-lunarg commented on layers/vk_layer_logging.cpp
> +                                         uint64_t callback) {
This has already been fixed

2023-03-22 22:42 UTC, charles-lunarg commented on BUILD.gn
>    "layers/external/vma/vk_mem_alloc.h",
Why does vma/vk_mem_alloc.h live in external while vma.cpp doesn't?

2023-03-22 22:43 UTC, juan-lunarg commented
> I'm trying to understand the overview here.. With extensive movement of files in `BUILD.gn`, `CMakeLists.txt`, and `Android.mk`, how was the VVL build not completely broken before this commit?

Because this doesn't affect the vvl build. It affects the Lunarg/VulkanTools build due to `VkLayer_utils` being installed. Which isn't tested anywhere

2023-03-22 22:43 UTC, juan-lunarg commented on BUILD.gn
>    "layers/external/vma/vk_mem_alloc.h",
vma.cpp doesn't need to live there it's a file we own/created similar to xxhash.cpp

2023-03-22 22:45 UTC, charles-lunarg commented on BUILD.gn
>    "layers/external/vma/vk_mem_alloc.h",
Gotcha, its a vendored file and lives in `layers/external`.

2023-03-23 01:42 UTC, spencer-lunarg approved these changes

2023-03-23 01:44 UTC, spencer-lunarg commented
For the short term I understand why this is needed, but we really should move away from being constrained in this repo to do things for other repos

2023-03-23 05:27 UTC, ncesario-lunarg requested changes
I do not understand this change. If VulkanTools is referencing _source_ files in VVL (which shouldn't be the case, but I understand that's the current state of things), then why can VulkanTools not update? Either that, or we need to bite the bullet and fix the longstanding dependency issues we have here. This is undoing organizational changes I would rather not see undone.

2023-03-23 17:23 UTC, juan-lunarg commented
> This is undoing organizational changes I would rather not see undone.

There are multiple ways to fix this build breakage. I'll try another tempt that doesn't undo the organizational changes. I just did what I found easiest.

2023-03-23 17:23 UTC, closed without merging