layers: Label new CmdPushDescriptorSetWithTemplate VUID
KhronosGroup/Vulkan-ValidationLayers pull request #5498
Opened 2023-03-24 12:49 UTC by spencer-lunarg

Adds VUID for new VUs added in 245 headers to replace to old UNASSIGNED VUIDs

- VUID-vkCmdPushDescriptorSetWithTemplateKHR-layout-07993
- VUID-vkCmdPushDescriptorSetWithTemplateKHR-descriptorUpdateTemplate-07994
- VUID-vkCmdPushDescriptorSetWithTemplateKHR-set-07995

2023-03-24 17:08 UTC, juan-lunarg requested changes
Double check the error messages for redundancy to help readability.

2023-03-24 17:08 UTC, juan-lunarg commented on layers/core_checks/descriptor_validation.cpp
> +            skip |= LogError(cb_state->commandBuffer(), "VUID-vkCmdPushDescriptorSetWithTemplateKHR-descriptorUpdateTemplate-07994",
Currently this error message just repeats the VUID description which isn't very helpful to users. The VUID description is appended in the log message when given a valid VUID.

2023-03-25 02:28 UTC, spencer-lunarg commented on layers/core_checks/descriptor_validation.cpp
> +            skip |= LogError(cb_state->commandBuffer(), "VUID-vkCmdPushDescriptorSetWithTemplateKHR-descriptorUpdateTemplate-07994",
For this PR lets just have this be the "245 header fix"

I will make another PR now to improve this and other nearby error messages

2023-03-25 04:08 UTC, spencer-lunarg commented on layers/core_checks/descriptor_validation.cpp
> +            skip |= LogError(cb_state->commandBuffer(), "VUID-vkCmdPushDescriptorSetWithTemplateKHR-descriptorUpdateTemplate-07994",
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5502

2023-03-27 16:11 UTC, juan-lunarg approved these changes

2023-03-28 08:27 UTC, merged