Compatible validation for VK_EXT_shader_object
KhronosGroup/Vulkan-ValidationLayers pull request #5570
Opened 2023-04-05 05:14 UTC by daniel-story

This PR introduces a number of changes needed to allow validation of applications that use VK_EXT_shader_object without the layer crashing or generating false positives:

ValidateExtendedDynamicState() and its callers are modified to check for either the specific EDS1/2/3/etc. feature originally associated with each function, or the shaderObject feature (which also makes it legal to call them, even when the corresponding dynamic state feature is disabled). This allows these commands to be called with only the shaderObject feature enabled, as expected by the spec.

ValidateCmdBufDrawState() is temporarily modified to early out if the shaderObject feature is enabled but there isn't a pipeline bound. This avoids a false positive error when shader objects have been bound instead of pipelines.

The autogeneration code for the vk_extension_helper.h and vk_dispatch_table_helper.h files is modified to support a new ExtEnabled enum value: kEnabledByInteraction. This is a workaround for a limitation in the autogeneration architecture where types (including functions) that are introduced into the API by more than one extension can only be attributed to only one of the extensions at a time. Without this fix, vkGetInstanceProcAddr()/vkGetDeviceProcAddr() incorrectly return nullptr whenever applications query for EDS1/2/3/etc. entrypoints with only VK_EXT_shader_object enabled, which is intended to work. Also, many false positives would be generated when calling those entrypoints.

A missing null check in CMD_BUFFER_STATE::UpdatePipelineState() is added in order to avoid a crash when no pipeline is bound.

Finally, the logic in thread_safety_generator.py is modified to prevent inappropriate calls to StartReadObject() and CreateObject() in the autogenerated code for vkCreateShadersEXT().

With all these changes, shader object applications can run and make use of the functionality of the extension without the layer crashing or reporting false positives.

Full validation will come in the future.

2023-04-05 05:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5570) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5570) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5570) it.</sub>

2023-04-05 05:38 UTC, spencer-lunarg commented on layers/core_checks/cmd_buffer_dynamic_validation.cpp
> -                                     enabled_features.extended_dynamic_state2_features.extendedDynamicState2PatchControlPoints,
traditionally in the past for things like

```
ifdef::VK_EXT_shader_object[]
ifdef::VK_EXT_extended_dynamic_state2[]
  * [[VUID-vkCmdSetPatchControlPointsEXT-None-08574]]
    Either the <<features-extendedDynamicState2PatchControlPoints,
    pname:extendedDynamicState2PatchControlPoints>> feature or the
    <<features-shaderObject, pname:shaderObject>> feature or both must: be
    enabled
endif::VK_EXT_extended_dynamic_state2[]
ifndef::VK_EXT_extended_dynamic_state2[]
  * [[VUID-vkCmdSetPatchControlPointsEXT-None-08575]]
    The <<features-shaderObject, pname:shaderObject>> feature must: be
    enabled
endif::VK_EXT_extended_dynamic_state2[]
endif::VK_EXT_shader_object[]
ifndef::VK_EXT_shader_object[]
  * [[VUID-vkCmdSetPatchControlPointsEXT-None-04873]]
    The <<features-extendedDynamicState2PatchControlPoints,
    pname:extendedDynamicState2PatchControlPoints>> feature must: be enabled
endif::VK_EXT_shader_object[]
```

We would do some ternary operation to select the VUID depending on which extension the user picked. (One reason is so the script that scans which VUID are done catches them)

For sake of this PR's goal, not worried about it, but should be addressed after in the "full validation" PR

2023-04-05 05:40 UTC, spencer-lunarg commented on scripts/helper_file_generator.py
> +                    '        // Workaround for functions being introducted by multiple extensions, until the layer is fixed to handle this correctly',
@ncesario-lunarg we have a working issue for this so this doesn't just get lost?

2023-04-05 05:42 UTC, spencer-lunarg commented on layers/state_tracker/state_tracker.cpp
> +    if (pStages) {
if `pStages` is false, I would imagine it would get trigged first by `VUID-vkCmdBindShadersEXT-pStages-parameter`/`VUID-vkCmdBindShadersEXT-stageCount-arraylength` and would never make it to `ValidationStateTracker`

2023-04-05 05:43 UTC, spencer-lunarg approved these changes

2023-04-05 06:12 UTC, spencer-lunarg commented
> Author daniel-story not on autobuild list. Waiting for curator authorization before starting CI build.

@daniel-story I added you to the list and kicked off the CI for you

2023-04-05 19:28 UTC, ncesario-lunarg commented on layers/core_checks/cmd_buffer_dynamic_validation.cpp
> -                                     enabled_features.extended_dynamic_state2_features.extendedDynamicState2PatchControlPoints,
➕

2023-04-05 19:31 UTC, juan-lunarg commented on scripts/helper_file_generator.py
> +                    '        // Workaround for functions being introducted by multiple extensions, until the layer is fixed to handle this correctly',
Is the issue with our layer or the extension layer that was just added? (https://github.com/KhronosGroup/Vulkan-ExtensionLayer)

2023-04-05 20:03 UTC, ncesario-lunarg reviewed
A couple questions/comments, but this LGTM.

2023-04-05 20:03 UTC, ncesario-lunarg commented on scripts/helper_file_generator.py
> +                    '                            this->*(info.state) = kEnabledByInteraction;',
Did you happen to try out using `kEnabledByCreateInfo` to avoid adding another `ExtEnabled` state?

2023-04-05 23:52 UTC, ncesario-lunarg requested changes

2023-04-05 23:52 UTC, ncesario-lunarg commented on layers/generated/vk_extension_helper.h
> +        }
Looking at this a bit more, I actually do not understand why this is needed at all. The purpose of the code in this function is to ensure that dependent extensions have been enabled, and my initial understanding was that these extensions were _dependencies_ of VK_EXT_shader_object. However, that does not appear to be the case (this extension appears to only depend on `VK_KHR_get_physical_device_properties2` and `VK_KHR_dynamic_rendering`). Even if these extensions were dependencies, this would actually still be incorrect.

@daniel-story can you please elaborate on what this is meant to solve?

2023-04-06 00:02 UTC, spencer-lunarg commented on scripts/helper_file_generator.py
> +                    '        // Workaround for functions being introducted by multiple extensions, until the layer is fixed to handle this correctly',
@daniel-story can you add a link to 5579 in the comment?

2023-04-07 00:31 UTC, ncesario-lunarg commented on layers/generated/vk_extension_helper.h
> +        }
Thank you for the clarification (on gitlab) @daniel-story. Per my comments over on gitlab, can you please try using https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5590? If that works, that should be a general solution for this particular problem (i.e., GetDeviceProcAddr), and then `kEnabledByInteraction` should not be necessary.

2023-04-07 17:22 UTC, juan-lunarg commented on layers/generated/vk_extension_helper.h
> +        // Workaround for functions being introducted by multiple extensions, until the layer is fixed to handle this correctly
`introduceted`?

2023-04-07 17:22 UTC, juan-lunarg commented on layers/generated/vk_extension_helper.h
> +            constexpr std::array<const char*, 4> shader_object_interactions = {
Use CTAD

```suggestion
            constexpr std::array shader_object_interactions = {
```

2023-04-07 17:22 UTC, juan-lunarg commented on layers/state_tracker/cmd_buffer_state.cpp
> +    if (pipe && VK_NULL_HANDLE != last_bound.pipeline_layout) {
Return early if pipe is false.

Also avoids a check on line 1153

2023-04-07 22:06 UTC, ncesario-lunarg commented on layers/generated/vk_extension_helper.h
> +        }
Daniel pointed out another issue: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5600. "Extension interactions" apparently have always been very broken and we've just gotten lucky about not running into any issues in the past.

In light of this, I'm good with merging this as is to get things unblocked for the upcoming SDK.

2023-04-07 22:06 UTC, ncesario-lunarg commented on scripts/helper_file_generator.py
> +                    '        // Workaround for functions being introducted by multiple extensions, until the layer is fixed to handle this correctly',
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5600 is also related.

2023-04-07 22:06 UTC, ncesario-lunarg approved these changes

2023-04-11 02:40 UTC, merged