layers: Add `VK_KHR_separate_depth_stencil_layouts` related VUIDs
KhronosGroup/Vulkan-ValidationLayers pull request #5664
Opened 2023-04-17 14:29 UTC by arno-lunarg

- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5624

Add:
VUID-VkRenderPassCreateInfo2-attachment-06244
VUID-VkRenderPassCreateInfo2-attachment-06245
VUID-VkRenderPassCreateInfo2-attachment-06246
VUID-vkCmdBeginRenderPass-stencilInitialLayout-02843
VUID-vkCmdBeginRenderPass2-stencilInitialLayout-02845
VUID-vkCmdBeginRenderPass-initialLayout-02842
VUID-vkCmdBeginRenderPass2-initialLayout-02844

Two new tests: `RenderPassBeginLayoutsStencilBufferImageUsageMismatches` and `RenderPassBeginInvalidStencilFormat`
Split up `RenderPassCreateAttachmentReferenceInvalidLayout` into two tests because the `if (separate_depth_stencil_layouts_features.separateDepthStencilLayouts) { ... }` logic was not working as intended anymore, and one branch was dead. There is now one test for each of the previous branches.

2023-04-17 16:42 UTC, juan-lunarg requested changes

2023-04-17 16:42 UTC, juan-lunarg commented on tests/negative/subpass.cpp
Create `tests/positive/subpass.cpp` then add the corresponding positive tests.

2023-04-17 16:42 UTC, juan-lunarg commented on tests/negative/renderpass.cpp
Add corresponding positive testing to `tests/positive/render_pass.cpp`

2023-04-17 16:42 UTC, juan-lunarg commented on tests/negative/multiview.cpp
Create `tests/positive/multiview.cpp` then add the corresponding positive test(s).

2023-04-17 16:42 UTC, juan-lunarg commented on tests/framework/layer_validation_tests.cpp
> +        assert(vkCmdBeginRenderPass2KHR);
I don't think we need to do this anymore now that Artem's change is merged in?

2023-04-18 04:57 UTC, spencer-lunarg commented on tests/negative/subpass.cpp
for a test like `RenderPassCreate2SubpassInvalidInputAttachmentParameters` would it not just be easier and more maintainable to add a 

```c++
// Valid
reference.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
PositiveTestRenderPass2KHRCreate(*m_errorMonitor, *m_device, rpci2);
```

otherwise I feel we are writing an very basic positive test with little coverage

---

I agree having positive tests is good, but it is hard to determine what a good positive test would be because there infinite positive ways to write Vulkan and a set number of VUs how not to write it

The positive test that are the best are for the more complex VUs

2023-04-18 05:04 UTC, spencer-lunarg commented on layers/core_checks/image_layout_cc_validation.cpp
> +    if (IsValueIn(layout, {VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL, VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL,
## future cleanup PR idea after this

We have the `IsImageLayoutReadOnly`/`IsImageLayoutStencilReadOnly`/`IsImageLayoutDepthReadOnly` helper functions already

Here (and other places using depth and/or stencil layouts) could make use of a `IsSeperateDepthStencilLayout` - it would make this logic more easy to understand right away

2023-04-18 05:09 UTC, spencer-lunarg commented on layers/core_checks/render_pass_cc_validation.cpp
> +                    if (IsExtEnabled(device_extensions.vk_khr_separate_depth_stencil_layouts)) {
this `if` is not needed, we will throw an error earlier if you use `VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL` without the extension enabled

2023-04-18 05:12 UTC, spencer-lunarg approved these changes
Nits, otherwise happy with this

2023-04-18 08:23 UTC, arno-lunarg commented on tests/negative/multiview.cpp
I am going to add a call to `PositiveTestRenderPass2KHRCreate` in this test

2023-04-18 08:25 UTC, arno-lunarg commented on tests/negative/subpass.cpp
I share Spencer's view, here to me it makes more sense to add a `PositiveTestRenderPass2KHRCreate` call with valid parameters, and then invalidate them and do the negative testing.

2023-04-18 08:49 UTC, arno-lunarg commented on tests/negative/renderpass.cpp
Given this PR's scope the only positive test I would consider is adding one where a `VkAttachmentDescriptionStencilLayoutKHR` is used, but there is already `VkPositiveLayerTest::BeginRenderPassDedicatedStencilLayout`

2023-04-18 09:53 UTC, arno-lunarg commented on layers/core_checks/image_layout_cc_validation.cpp
> +    if (IsValueIn(layout, {VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL, VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL,
I defined `IsImageLayoutStencilOnly` and `IsImageLayoutDepthOnly`, and replace the `IsValueIn` code by calls to those. I will do the cleanups in a following PR.

2023-04-18 10:25 UTC, spencer-lunarg commented on layers/core_checks/image_layout_cc_validation.cpp
> +    if (IsValueIn(layout, {VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL, VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL,
awesome, it already looks much better to read with those functions in this PR

2023-04-19 09:31 UTC, merged