layers: Fix to the logic defining a `VkStridedDeviceAddressRegionKHR` as unused
KhronosGroup/Vulkan-ValidationLayers pull request #5675
Opened 2023-04-18 15:07 UTC by arno-lunarg

- Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5635

2023-04-18 15:32 UTC, artem-lunarg approved these changes
LGTM! Thanks for clarifying this.

2023-04-18 17:31 UTC, juan-lunarg requested changes
LGTM overall

2023-04-18 17:31 UTC, juan-lunarg commented on tests/positive/ray_tracing.cpp
Revert change to this file. Or add change in 2nd commit.

2023-04-18 17:31 UTC, juan-lunarg commented on tests/negative/ray_tracing.cpp
> +                          1);
Move positive testing to `tests/positive/ray_tracing.cpp`.

2023-04-19 18:48 UTC, juan-lunarg approved these changes

2023-04-21 06:49 UTC, merged