Fix false positive VUID-vkResetCommandBuffer-commandBuffer-00045 error after exporting submitted fence handle
KhronosGroup/Vulkan-ValidationLayers pull request #5695
Opened 2023-04-19 16:10 UTC by i-nazarov-samsung

This request fixes the issue: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5694

2023-04-19 18:50 UTC, juan-lunarg requested changes
Currently CI is failing on `VkPositiveLayerTest.ExternalFenceSubmitCmdBuffer`

```
[  FAILED  ] 1 test, listed below:
[  FAILED  ] VkPositiveLayerTest.ExternalFenceSubmitCmdBuffer

 1 FAILED TEST
  YOU HAVE 10 DISABLED TESTS
```

2023-04-19 19:05 UTC, jeremyg-lunarg commented
> Currently CI is failing on `VkPositiveLayerTest.ExternalFenceSubmitCmdBuffer`

Could this be related to the use of MockICD in our github actions for testing on Linux?  I doubt it exports a valid fence file descriptor.

The code changes seem reasonable to me.

2023-04-19 19:13 UTC, juan-lunarg requested changes
Test runs fine on my AMD APU. Doesn't work on our Mock driver. Looking at the other tests this is a known limitation.

2023-04-19 19:32 UTC, i-nazarov-samsung commented on tests/positive/sync.cpp
> +    }
Thanks!

On my end test runs OK on Android: S906B (Samsung S22 AMD), G996B (S21+ Mali), G991U (S21 Adreno), and Pixel 4a.

2023-04-19 19:46 UTC, i-nazarov-samsung commented on tests/positive/sync.cpp
> +    }
Done.

2023-04-19 19:46 UTC, i-nazarov-samsung commented on tests/positive/sync.cpp
> +    vkGetPhysicalDeviceExternalFencePropertiesKHR(gpu(), &efi, &efp);
Done.

2023-04-19 19:49 UTC, juan-lunarg approved these changes

2023-04-19 20:19 UTC, ShabbyX commented
I can confirm the test runs fine on Pixel 6

2023-04-20 04:45 UTC, spencer-lunarg approved these changes

2023-04-20 10:15 UTC, artem-lunarg commented on layers/state_tracker/queue_state.cpp
> +        if (scope_ == kSyncScopeInternal) {
Do we need this condition?
According to spec:
> Additionally, exporting a fence payload to a handle with copy transference has the same side effects on the source fence’s payload as executing a fence reset operation.

2023-04-20 13:36 UTC, i-nazarov-samsung commented on layers/state_tracker/queue_state.cpp
> +        if (scope_ == kSyncScopeInternal) {
> According to spec it sounds like the reset happens unconditionally:

I guess the question was for the `if (scope_ == kSyncScopeInternal)` condition and unconditional `state_ = FENCE_UNSIGNALED` assignment. I'm not 100% sure either. I took logic from `FENCE_STATE::Reset()`.

I do not see strong reasons why we need this condition in both methods. I guess the original intent was that if scope is not `kSyncScopeInternal`, other parts of the code ignore what is in the `state_`, therefore - no need to change it.

However, `completed_` is still reset regardless of `scope_ `. IMO, it is better to also reset `state_` unconditionally for consistency.

2023-04-20 13:43 UTC, i-nazarov-samsung commented on layers/state_tracker/queue_state.cpp
> +        if (scope_ == kSyncScopeInternal) {
Removed `if (scope_ == kSyncScopeInternal)` from both methods.

2023-04-20 13:59 UTC, artem-lunarg commented on layers/state_tracker/queue_state.cpp
> +        if (scope_ == kSyncScopeInternal) {
Thanks for the explanation. Yeah, if no good reason then a check before assignment is not an (micro)optimization either, condition if not predicted is much heavier. But IMO the main reason that it can cost developer time in an attempt to understand the whys. If it breaks something then we will revert this part back with a good comment.

2023-04-20 16:19 UTC, artem-lunarg approved these changes

2023-04-20 16:27 UTC, artem-lunarg approved these changes
LGTM, still need to wait for CI to confirm that suggestion to reset unconditionally does not cause issues.

2023-04-24 19:56 UTC, merged

2023-04-24 19:59 UTC, juan-lunarg commented
Thanks for the fix/test @i-nazarov-samsung :+1: