layers: Fix UB for VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT
KhronosGroup/Vulkan-ValidationLayers pull request #5706
Opened 2023-04-20 09:57 UTC by haasn

Several codepaths in the layers called into
vkGetPhysicalDeviceImageFormatProperties2KHR without including a valid VkPhysicalDeviceImageDrmFormatModifierInfoEXT, despite this being a requirement for images with DRM format modifier tiling.

For the vkBindImageMemory check, there is a hypothetical possibility of the driver returning VK_ERROR_OUT_OF_HOST_MEMORY when querying the image's DRM format. In this case, for lack of anything better to do, we preserve the current behavior.

It might make more sense to query the DRM format modifier immediately after image creation and cache it inside the image state, but I didn't want to make that (more invasive) change myself.

Fixes: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5649
Supersedes: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5688

2023-04-20 10:00 UTC, spencer-lunarg commented on layers/core_checks/cc_image.cpp
> +        VkExternalMemoryHandleTypeFlags compatible_types = 0;
this is the same idea as https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5688 , but I seem to like this better @emersion can you confirm this solves your problem

I am happy to get this in and I can write a test (for regression) after to help unblock people

2023-04-20 10:06 UTC, emersion commented on layers/core_checks/cc_image.cpp
> +            auto modifier_list = LvlFindInChain<VkImageDrmFormatModifierListCreateInfoEXT>(pCreateInfo->pNext);
Since `external_memory_create_info != nullptr`, it's illegal to pass a modifier list. IOW, when importing a DMA-BUF, a single modifier must be specified.

2023-04-20 10:07 UTC, emersion commented on layers/core_checks/cc_image.cpp
> +                drm_format_modifier.drmFormatModifier = explicit_modifier->drmFormatModifier;
Should maybe set `sharingMode` here?

2023-04-20 10:08 UTC, emersion commented on layers/core_checks/cc_image.cpp
> +        VkExternalMemoryHandleTypeFlags compatible_types = 0;
> I seem to like this better

Can you elaborate?

2023-04-20 10:10 UTC, haasn commented
Oh, I totally didn't realize me and @emersion worked on the same fix for the same bug (tracked in separate issues) at the same time. My bad.

2023-04-20 10:11 UTC, emersion commented on layers/core_checks/cc_image.cpp
> +        VkExternalMemoryHandleTypeFlags compatible_types = 0;
This patch fixes both export and import, while https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5688 fixes only import.

2023-04-20 10:12 UTC, emersion commented
Yeah, sorry, I completely missed https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5649 as well!

2023-04-20 10:22 UTC, haasn commented
For the missing positive check, what I do in libplacebo is use the vulkan API to create a DRM tiled image and export it as a DMABUF, then re-import that back into the vulkan device as a second VkImage. This does not require any non-Vulkan calls to accomplish.

My test case can be found [here](https://code.videolan.org/videolan/libplacebo/-/blob/master/src/tests/gpu_tests.h#L1548) but it's entirely written around my own high-level wrappers.

The relevant bits are the `pl_tex_create` calls, which ultimately resolve to [vk_tex_create](https://code.videolan.org/videolan/libplacebo/-/blob/master/src/vulkan/gpu_tex.c#L230), [slab_alloc](https://code.videolan.org/videolan/libplacebo/-/blob/master/src/vulkan/malloc.c#L365) and [vk_malloc_import](https://code.videolan.org/videolan/libplacebo/-/blob/master/src/vulkan/malloc.c#L746)

It is quite a lot of code but copy/pasting it should at least be somewhat straightforward.

2023-04-20 10:26 UTC, haasn commented on layers/core_checks/cc_image.cpp
> +            auto modifier_list = LvlFindInChain<VkImageDrmFormatModifierListCreateInfoEXT>(pCreateInfo->pNext);
Correct me if I'm wrong, but `VkExternalMemoryImageCreateInfo` is also passed when *exporting* a VkImage to a DMA-BUF, in which case a modifier list is perfectly legal. In fact, this is what my code does. (But maybe my code is wrong)

2023-04-20 10:29 UTC, haasn commented on layers/core_checks/cc_image.cpp
> +                drm_format_modifier.drmFormatModifier = explicit_modifier->drmFormatModifier;
I can add this, though note that the existing code for the DRM format validation also does not set `sharingMode` for this call. Should we also fix that code path?

2023-04-20 10:31 UTC, emersion commented on layers/core_checks/cc_image.cpp
> +            auto modifier_list = LvlFindInChain<VkImageDrmFormatModifierListCreateInfoEXT>(pCreateInfo->pNext);
Hm right… You are correct!

2023-04-20 10:37 UTC, haasn commented
Updated to set `sharingMode` correctly, including for the existing calls to this function.

2023-04-20 10:46 UTC, haasn commented
Updated to also set `sharingMode` in the `vkBindImageMemory` check, for completeness' sake, and tagged @emersion as co-author.

2023-04-20 10:48 UTC, spencer-lunarg submitted a review, later dismissed

2023-04-20 16:58 UTC, juan-lunarg reviewed
LGTM overall. Main concern is a test should be added to prevent a regression.

2023-04-21 09:38 UTC, haasn commented
> CI Vulkan-ValidationLayers build # 11742 failed.

Can I get details on this failure somehow?

2023-04-21 11:55 UTC, arno-lunarg commented
It looks like a CI problem. I restarted a test run, we will see how it goes

2023-04-21 17:30 UTC, juan-lunarg commented
> Can I get details on this failure somehow?

Currently LunarG has internal jenkins testing to test on real GPU hardware. Sadly OS contributors don't have an easy way to access these logs. We are working on improving the process for OS contributors.

2023-04-21 18:19 UTC, ncesario-lunarg submitted a review, later dismissed

2023-04-21 20:16 UTC, juan-lunarg commented
> CI Vulkan-ValidationLayers build # 11754 failed.

Failure doesn't look sporadic.

It's failing on `VkPositiveLayerTest.SecondaryCommandBufferBarrier` for `Linux-Mesa-6800` and `VkPositiveLayerTest.OwnershipTranfersImage` Windows-AMD.

@haasn if you have an AMD GPU could you try running those tests locally? If not I'll look into it.

2023-04-21 20:16 UTC, juan-lunarg requested changes
Passes MockICD but fails on real hardware.

2023-04-24 23:44 UTC, juan-lunarg commented
> It's failing on VkPositiveLayerTest.SecondaryCommandBufferBarrier for Linux-Mesa-6800

I rebased the PR via the github UI.

I wasn't able to repro the test failure on my local system. Running jenkins CI again.

2023-04-25 17:21 UTC, juan-lunarg commented
> CI Vulkan-ValidationLayers build # 11789 failed.

It's failing the following tests on AMD/Android GPUs with access violations.

- `VkPositiveLayerTest.OwnershipTranfersImage` (AMD)
- `VkPositiveLayerTest.SecondaryCommandBufferBarrier` (AMD)
- `VkLayerTest.PSOPolygonModeInvalid` (Android)

Passes fine on Nvidia / MacOS... not sure why yet.

2023-05-11 17:45 UTC, juan-lunarg commented
Rebased on main to address merge conflict. Trying to figure out testing failure to see if we can get this in for the upcoming SDK release.

2023-05-11 19:06 UTC, juan-lunarg commented
Also FWIW @haasn `LunarG CI Checkrun` now shows the results of internal CI to external contributors. So if you are planning on future contributions it will be a smoother experience.

2023-05-11 22:26 UTC, juan-lunarg commented on layers/core_checks/cc_image.cpp
> +        if IsExtEnabled(device_extensions.vk_khr_get_physical_device_properties2) { // I believe this is the cause of the crashes
FYI @jeremyg-lunarg

2023-05-11 22:30 UTC, ncesario-lunarg commented on layers/core_checks/cc_image.cpp
> +        if IsExtEnabled(device_extensions.vk_khr_get_physical_device_properties2) { // I believe this is the cause of the crashes
Considering how ubiquitous the query APIs behind `VK_KHR_get_physical_device_properties2` are, I wonder if it makes sense to create a dispatch wrapper similar to what we use in the tests?

2023-05-11 22:33 UTC, jeremyg-lunarg commented on layers/core_checks/cc_image.cpp
> +        if IsExtEnabled(device_extensions.vk_khr_get_physical_device_properties2) { // I believe this is the cause of the crashes
I would love to have magic dispatch wrappers for pretty much every function that exists with multiple names (EXT, KHR, plain)

2023-05-11 23:21 UTC, juan-lunarg requested changes

2023-05-11 23:21 UTC, juan-lunarg commented on layers/core_checks/cc_image.cpp
> +        result = DispatchGetPhysicalDeviceImageFormatProperties2(physical_device, &image_format_info, &image_format_properties);
This is the cause of the CI failures. `GetPhysicalDeviceImageFormatProperties2` isn't supported on all  devices.

Credit to @jeremyg-lunarg for pointing that out.

2023-05-11 23:37 UTC, juan-lunarg approved these changes
I amended the original commit to check for `vk_khr_get_physical_device_properties2` support.

With that and the new test to prevent a regression I think this PR is good to go.

2023-05-12 01:19 UTC, juan-lunarg commented
Reverted my test since it has a minor issue on Android. I'll add the test in another PR so we can get this PR in time for the SDK release.

https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5841

2023-05-12 15:51 UTC, merged