Fix External Format Android tests
KhronosGroup/Vulkan-ValidationLayers pull request #5712
Opened 2023-04-21 06:10 UTC by spencer-lunarg

1. Fixes External Format tests to query before creating the image otherwise it was failing with `VUID-VkImageCreateInfo-pNext-00990`

2. Add 2 Null-AHB test to make sure we fail early

2023-04-21 13:17 UTC, arno-lunarg approved these changes

2023-04-21 17:19 UTC, ncesario-lunarg approved these changes

2023-04-21 17:26 UTC, juan-lunarg requested changes
Crashing on the GalaxyS10:

```
INFO: GalaxyS22-R5CT7020CJR: PASS
INFO: Pixel_6-1B211FDF60004H: PASS
ERROR: GalaxyS10-R28M31RTPWK: FAIL
INFO: Pixel3-89RX0E68Y: PASS
INFO: ShieldTV-1322020015983: PASS
```

```
ERROR: GalaxyS10-R28M31RTPWK: CRASH in package com.example.VulkanLayerValidationTests
ERROR: GalaxyS10-R28M31RTPWK: signal 11 (SIGSEGV) code 1 (SEGV_MAPERR) fault_addr 0x8
ERROR: GalaxyS10-R28M31RTPWK: cause null pointer dereference
ERROR: GalaxyS10-R28M31RTPWK: backtrace follows
```

2023-04-22 02:09 UTC, spencer-lunarg commented
> Crashing on the GalaxyS10:

I fixed this, but seems CI needed a manual reset, passed now

2023-04-22 02:09 UTC, merged