layers: Use FormatUtils for imageViewFormatReinterpretation
KhronosGroup/Vulkan-ValidationLayers pull request #5722
Opened 2023-04-24 06:27 UTC by spencer-lunarg

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2361

Before (when issue was opened 2+ years ago) we didn't have a generated Format Util that could check against each component bit size

Even if it is compressed formats, it will still match correctly

2023-04-24 12:16 UTC, arno-lunarg commented on layers/generated/vk_format_utils.cpp
> +    } else if (item_a->second.component_count != item_a->second.component_count) {
```suggestion
    } else if (item_a->second.component_count != item_b->second.component_count) {
```

2023-04-24 12:17 UTC, arno-lunarg commented on scripts/format_utils_generator.py
> +    } else if (item_a->second.component_count != item_a->second.component_count) {
```suggestion
    } else if (item_a->second.component_count != item_b->second.component_count) {
```

2023-04-24 12:20 UTC, arno-lunarg approved these changes
LGTM! One needed change

2023-04-24 14:24 UTC, spencer-lunarg commented on scripts/format_utils_generator.py
> +    } else if (item_a->second.component_count != item_a->second.component_count) {
:sob: thanks for catching this

2023-04-24 16:28 UTC, arno-lunarg commented on scripts/format_utils_generator.py
> +    } else if (item_a->second.component_count != item_a->second.component_count) {
I have done it so much time in the past, and will do it countless times in the future, so be wary of my PRs ( ͡• ͜ʖ ͡• )

2023-04-24 16:58 UTC, juan-lunarg requested changes
:+1:

2023-04-24 16:58 UTC, juan-lunarg commented on layers/generated/vk_format_utils.cpp
> +    auto item_b = kVkFormatTable.find(format_b);
```suggestion
    const auto item_a = kVkFormatTable.find(format_a);
    const auto item_b = kVkFormatTable.find(format_b);
```

2023-04-24 16:58 UTC, juan-lunarg commented on layers/generated/vk_format_utils.cpp
> +    return true;
When adding testing for this function test formats that would hit each of these return statements.

2023-04-24 16:58 UTC, juan-lunarg commented on layers/generated/vk_format_utils.cpp
> +bool FormatsSameComponentBits(VkFormat format_a, VkFormat format_b) {
Add testing for `FormatsSameComponentBits` in `tests/positive/layer_utils.cpp`

2023-04-25 06:13 UTC, spencer-lunarg commented on layers/generated/vk_format_utils.cpp
> +bool FormatsSameComponentBits(VkFormat format_a, VkFormat format_b) {
added tests, good call, there were more nasty edge cases that were failing

2023-04-25 16:57 UTC, juan-lunarg approved these changes

2023-04-25 17:10 UTC, juan-lunarg commented on tests/negative/portability_subset.cpp
> +    m_errorMonitor->SetUnexpectedError("VUID-VkImageViewCreateInfo-None-02273");
Can we detect the ImageView format isn't supported and skip instead?

2023-04-25 17:32 UTC, ncesario-lunarg approved these changes
I completely forgot about this issue :)

2023-04-25 17:32 UTC, ncesario-lunarg commented on tests/negative/portability_subset.cpp
> +    m_errorMonitor->SetUnexpectedError("VUID-VkImageViewCreateInfo-None-02273");
:heavy_plus_sign:

2023-04-26 04:39 UTC, spencer-lunarg commented on tests/negative/portability_subset.cpp
> +    m_errorMonitor->SetUnexpectedError("VUID-VkImageViewCreateInfo-None-02273");
If we do, this will never be tested, I am not sure what format is supported on MacOS that was designed to hit `VUID-VkImageViewCreateInfo-imageViewFormatReinterpretation-04466` this way

Added a comment to look into ti

2023-04-26 05:57 UTC, merged