layers: Add support for VK_EXT_shader_tile_image
KhronosGroup/Vulkan-ValidationLayers pull request #5736
Opened 2023-04-25 17:25 UTC by mohfai-arm

Closes #5630

2023-04-25 17:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5736) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5736) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5736) it.</sub>

2023-04-25 17:46 UTC, juan-lunarg requested changes

2023-04-25 17:46 UTC, juan-lunarg commented on tests/negative/dynamic_rendering.cpp
Add positive testing for `VK_EXT_shader_tile_image` to prevent false positives.

2023-04-25 17:46 UTC, juan-lunarg commented on layers/state_tracker/shader_module.cpp
> +            }break;
```suggestion
                 shader_tile_image_inst.push_back(&insn);
                 break;
            }
```

2023-04-25 19:00 UTC, ncesario-lunarg submitted a review, later dismissed
Some minor nits and suggestions, but overall this looks good, thanks @mohfai-arm!

It would probably be good to get @spencer-lunarg's input here as this touches a lot of the shader validation code which has been refactored quite a bit recently.

2023-04-26 04:43 UTC, spencer-lunarg commented on layers/core_checks/cc_shader.cpp
> +    if (IsExtEnabled(device_extensions.vk_ext_shader_tile_image) && (stage == VK_SHADER_STAGE_FRAGMENT_BIT)) {
there is a `if (stage == VK_SHADER_STAGE_FRAGMENT_BIT) {` below, can just move the `IsExtEnabled` check in there

(try to group all the "Fragment only" functions together

2023-04-26 04:49 UTC, spencer-lunarg commented on tests/negative/dynamic_rendering.cpp
> +    assert(vkCmdEndRendering != nullptr);
yes, no more need to call `GetDeviceProcAddr`, enabling the extension will get the functions for you

```suggestion
```

2023-04-26 16:31 UTC, ncesario-lunarg commented on tests/negative/dynamic_rendering.cpp
> +    assert(vkCmdEndRendering != nullptr);
I also keep forgetting we have this feature now!

2023-04-27 09:29 UTC, janharaldfredriksen-arm commented on layers/core_checks/cc_cmd_buffer_dynamic.cpp
> +                case spv::OpDepthAttachmentReadEXT: {
@juan-lunarg - for the dependencies, do you have a preference for how we proceed?

We could push a separate PR to known_good.json to bring in the required SPIR-V Headers and Tools, but I don't know if you want to do that as a one-time update ahead of the next SDK release?

Or we could leave this PR in draft until whenever the known goods are updated, which is probably fine in practice (since it will take time for this feature to show up in devices), but would leave the feature released without validation for a couple of months.

2023-04-27 15:02 UTC, mohfai-arm commented on tests/negative/dynamic_rendering.cpp
> +    assert(vkCmdEndRendering != nullptr);
Updated in the latest changes.

2023-04-27 15:04 UTC, mohfai-arm commented on layers/state_tracker/shader_module.cpp
> +            case spv::OpColorAttachmentReadEXT:{
Thanks for the suggestion, I updated the code with boolean and removed 'for' loop

2023-04-27 15:06 UTC, mohfai-arm commented on layers/core_checks/cc_cmd_buffer_dynamic.cpp
> +                            "%s(): depthWriteEnable parameter in the last call to vkCmdSetDepthWriteEnable must be VK_FALSE",
Updated the error text as suggested.

2023-04-27 15:08 UTC, mohfai-arm commented on layers/core_checks/cc_synchronization.cpp
> +        if ((mem_barrier.srcStageMask & ~framebuffer_space_stage_flags) != 0) {
Moved the framebuffer stage flags in the sync_utils as it has been used in one more file previously.

2023-04-27 15:08 UTC, mohfai-arm commented on layers/core_checks/cc_synchronization.cpp
> +                         loc.dot(Field::srcStageMask).Message().c_str(), mem_barrier.srcStageMask, framebuffer_space_stage_flags);
Done, updated the code to print string

2023-04-27 15:13 UTC, mohfai-arm commented on layers/core_checks/cc_cmd_buffer_dynamic.cpp
> +        for (const Instruction *insn : module_state->static_data_.shader_tile_image_inst) {
Removed for loop, using bools in latest changes.

2023-04-27 15:13 UTC, mohfai-arm commented on layers/core_checks/cc_synchronization.cpp
> +                                                          const VkDependencyInfoKHR *dep_info) const {
Done

2023-04-27 16:24 UTC, juan-lunarg commented on layers/core_checks/cc_cmd_buffer_dynamic.cpp
> +                case spv::OpDepthAttachmentReadEXT: {
> We could push a separate PR to known_good.json to bring in the required SPIR-V Headers and Tools, but I don't know if you want to do that as a one-time update ahead of the next SDK release?

@mikes-lunarg usually updates those dependencies for SDK releases.

I'd prefer updating the known_good.json be updated in a separate PR. It shouldn't be part of this PR.

2023-04-27 16:25 UTC, juan-lunarg commented on tests/negative/dynamic_rendering.cpp
Ideally there are multiple positive tests. Not just a single one.

2023-04-27 16:34 UTC, juan-lunarg commented on tests/negative/dynamic_rendering.cpp
> +    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "VUID-vkCmdPipelineBarrier-shaderTileImageColorReadAccess-08718");
This VUID being triggered seems odd to me. This test isn't using shader tile functionality but now is triggering a VUID?

2023-04-27 16:41 UTC, juan-lunarg commented on layers/core_checks/cc_cmd_buffer_dynamic.cpp
> +                case spv::OpDepthAttachmentReadEXT: {
Assuming tests pass with the updated known_good.json you should be good to submit a PR with the updated dependencies.

2023-04-28 21:25 UTC, juan-lunarg commented on layers/core_checks/cc_cmd_buffer_dynamic.cpp
> +                case spv::OpDepthAttachmentReadEXT: {
Does this PR have new enough version of the SPIRV-* repos for your PR?
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5750

2023-05-02 07:49 UTC, janharaldfredriksen-arm commented on layers/core_checks/cc_cmd_buffer_dynamic.cpp
> +                case spv::OpDepthAttachmentReadEXT: {
Yeah, I was watching that PR go by. That should fix this bit.

2023-05-02 14:54 UTC, mohfai-arm commented on tests/negative/dynamic_rendering.cpp
> +    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "VUID-vkCmdPipelineBarrier-shaderTileImageColorReadAccess-08718");
Fixed in the latest update.

2023-05-02 15:01 UTC, juan-lunarg commented
1.) Make sure to run `scripts/check_code_format.py` before making a PR. It will check clang-format and the commit messages.
2.) Sign the Khronos Group CLA

2023-05-03 17:14 UTC, juan-lunarg requested changes

2023-05-03 17:14 UTC, juan-lunarg commented on layers/core_checks/cc_shader.cpp
> +    if (IsExtEnabled(device_extensions.vk_ext_shader_tile_image) && (stage == VK_SHADER_STAGE_FRAGMENT_BIT)) {
Add these as asserts as inside `ValidateShaderTileImage` as well. Helps prevent issues in case the function gets used in other place in the future. Also helps with readability inside the function.

EX. It's useful to know the logic inside `ValidateShaderTileImage` only applies to the fragment stage without having to look up other places in the codebase.

2023-05-03 17:14 UTC, juan-lunarg commented on layers/core_checks/cc_synchronization.cpp
> +}
Move this logic to `layers/utils/vk_layer_utils.h`

Also this function can be made constexpr.

2023-05-03 17:14 UTC, juan-lunarg commented on layers/sync/sync_utils.h
Move new helper function logic to `layers/utils/vk_layer_utils.h` instead.

Also the function can be made constexpr

2023-05-03 17:14 UTC, juan-lunarg commented on tests/negative/dynamic_rendering.cpp
> +        (PFN_vkCmdSetStencilWriteMask)vk::GetDeviceProcAddr(m_device->device(), "vkCmdSetStencilWriteMask");
See https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5780

There is no need to call vk::GetDeviceProcAddr if you enabled the extension correctly.

2023-05-04 14:59 UTC, mohfai-arm commented on layers/core_checks/cc_cmd_buffer_dynamic.cpp
> +    if ((dyn_depth_write_enable || dyn_stencil_write_mask) &&
Done

2023-05-04 15:00 UTC, mohfai-arm commented on layers/core_checks/cc_shader.cpp
> +    }
Reporting existing capabilities in fragment shader in latest update.

2023-05-04 15:02 UTC, mohfai-arm commented on layers/core_checks/cc_shader.cpp
> +    if (IsExtEnabled(device_extensions.vk_ext_shader_tile_image) && (stage == VK_SHADER_STAGE_FRAGMENT_BIT)) {
Moved 'if' statement inside function, I think that works better as you suggested if we have to use function somewhere else.

2023-05-04 15:03 UTC, mohfai-arm commented on layers/core_checks/cc_synchronization.cpp
> +}
Done

2023-05-04 15:03 UTC, mohfai-arm commented on layers/sync/sync_utils.h
Done and moved to `layers/utils/vk_layer_utils.h`

2023-05-04 15:04 UTC, mohfai-arm commented on tests/negative/dynamic_rendering.cpp
> +        (PFN_vkCmdSetStencilWriteMask)vk::GetDeviceProcAddr(m_device->device(), "vkCmdSetStencilWriteMask");
Done

2023-05-04 16:54 UTC, juan-lunarg commented on layers/core_checks/cc_cmd_buffer_dynamic.cpp
> +    if ((dyn_depth_write_enable || dyn_stencil_write_mask) &&
FWIW my rational for the suggestion is it reduces variable scope / and provides documentation. And by variable scope I don't just mean potential optimization I also mean that when debugging large functions it helps to have less variables on the stack.

2023-05-04 17:21 UTC, juan-lunarg requested changes

2023-05-04 17:21 UTC, juan-lunarg commented on layers/core_checks/cc_synchronization.cpp
> +        // Check shader tile image extension enabled
This comment doesn't explain the if else statement rational here. Please provide a concise comment explaining the rational here.

2023-05-04 17:21 UTC, juan-lunarg commented on layers/core_checks/cc_synchronization.cpp
> +    bool features_enabled = tile_image_features.shaderTileImageColorReadAccess ||
```suggestion
    const bool features_enabled = tile_image_features.shaderTileImageColorReadAccess ||
```

2023-05-04 17:21 UTC, juan-lunarg commented on layers/core_checks/cc_synchronization.cpp
> +        // Check stage mask
```suggestion

```

2023-05-04 17:21 UTC, juan-lunarg commented on layers/core_checks/cc_synchronization.cpp
> +        // Check access mask
```suggestion
```

2023-05-04 17:57 UTC, mohfai-arm commented on layers/core_checks/cc_synchronization.cpp
> +        // Check access mask
Done

2023-05-04 17:57 UTC, mohfai-arm commented on layers/core_checks/cc_synchronization.cpp
> +        // Check stage mask
Done

2023-05-04 17:58 UTC, mohfai-arm commented on layers/core_checks/cc_synchronization.cpp
> +        // Check shader tile image extension enabled
Updated the comment

2023-05-04 17:58 UTC, mohfai-arm commented on layers/core_checks/cc_shader.cpp
> +    if (using_tile_image_capability && (pipeline.GetCreateInfo<VkGraphicsPipelineCreateInfo>().renderPass != VK_NULL_HANDLE)) {
Done

2023-05-04 18:00 UTC, juan-lunarg commented on layers/core_checks/cc_shader.cpp
> +static const std::string GetShaderTileImageCapabilitiesString(const SHADER_MODULE_STATE &module_state) {
Oh I see sorry about that this comment is wrong.

2023-05-04 18:00 UTC, mohfai-arm commented on layers/core_checks/cc_shader.cpp
> +static const std::string GetShaderTileImageCapabilitiesString(const SHADER_MODULE_STATE &module_state) {
I will check again but not sure string_SpvCapability is visible in cc_shader.cpp from `/layers/generated/spirv_validation_helper.cpp`
I didn't find any occurrences in the code where it's been used other than in the generated file.

2023-05-04 18:27 UTC, juan-lunarg commented
Layer code looks good to me now. Time to see if the testing checks out on CI.

We will want to check if these tests are actually being run though. I don't believe we have an Android device that supports this extension yet. In which case we will want to test it via our mock driver + profiles combo.

Here is an example of adding a new extension to the `max_profiles.json` which allows us to run testing on the CPU and validate very new extensions:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5350/files

Let me know if you need help with this.

2023-05-04 19:57 UTC, mohfai-arm commented
> Layer code looks good to me now. Time to see if the testing checks out on CI.
> 
> We will want to check if these tests are actually being run though. I don't believe we have an Android device that supports this extension yet. In which case we will want to test it via our mock driver + profiles combo.
> 
> Here is an example of adding a new extension to the `max_profiles.json` which allows us to run testing on the CPU and validate very new extensions: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5350/files
> 
> Let me know if you need help with this.

Updated 'max_profiles.json' file.

2023-05-05 16:33 UTC, juan-lunarg approved these changes
LGTM I'll merge this in before end of day unless someone else has something to say

2023-05-05 16:33 UTC, juan-lunarg commented on tests/device_profiles/max_profile.json
I checked the Github actions CI it passes with the new changes to max_profile.json :100:

2023-05-05 16:50 UTC, mohfai-arm commented
@juan-lunarg I realized we are missing VkCmdPipelineBarrier validation which is different code path than VkCmdPipelineBarrier2.
I will update the code with changes for review later today to make sure validation works for both.

2023-05-05 16:53 UTC, juan-lunarg commented
> @juan-lunarg I realized we are missing VkCmdPipelineBarrier validation which is different code path than VkCmdPipelineBarrier2.
> I will update the code with changes for review later today to make sure validation works for both.

It would be better to just make another PR after this gets merged in. This is already a sizeable PR with tests passing.

2023-05-05 16:59 UTC, mohfai-arm commented
> It would be better to just make another PR after this gets merged in. This is already a sizeable PR with tests passing.

Thanks for quick reply, yes that's fine. I will make a separate PR.

2023-05-05 17:33 UTC, merged