tests: part 2 support for VK_EXT_shader_tile_image
KhronosGroup/Vulkan-ValidationLayers pull request #5737
Opened 2023-04-25 17:31 UTC by mohfai-arm

closes #5630

2023-04-25 17:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5737) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5737) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5737) it.</sub>

2023-04-25 17:43 UTC, janharaldfredriksen-arm commented
Note: This will depend on the changes in #5736 and likely fails as a standalone patch, but we wanted to get everything up for review.

2023-04-25 19:03 UTC, ncesario-lunarg commented on tests/negative/dynamic_rendering.cpp
> +            }
@mohfai-arm if this is blocked by glslang changes, you can also just paste the SPIR-V assembly here and set the `source_type` parameter to `SPV_SOURCE_ASM` when creating the the `VkShaderObj` object.

2023-04-25 19:04 UTC, ncesario-lunarg requested changes
LGTM, but a positive test utilizing `VK_EXT_shader_tile_image` should also be added.

2023-05-02 14:53 UTC, mohfai-arm commented
closing this PR because tests are moved into #5736 with spirv

2023-05-02 14:53 UTC, closed without merging