build: Add arch to deps dir
KhronosGroup/Vulkan-ValidationLayers pull request #5756
Opened 2023-04-28 05:19 UTC by ncesario-lunarg

Add the architecture type to the external dependency path when using UPDATE_DEPS=ON.

2023-04-28 17:40 UTC, juan-lunarg requested changes
This will break `vvl.yml` caching.

2023-04-28 17:40 UTC, juan-lunarg commented on scripts/CMakeLists.txt
> +        set(UPDATE_DEPS_DIR_SUFFIX "${UPDATE_DEPS_DIR_SUFFIX}/x86")
x64/x86 is misleading. You can build on arm for Windows.
```suggestion
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(UPDATE_DEPS_DIR_SUFFIX "${UPDATE_DEPS_DIR_SUFFIX}/64")
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
        set(UPDATE_DEPS_DIR_SUFFIX "${UPDATE_DEPS_DIR_SUFFIX}/32")
```

2023-05-17 18:59 UTC, juan-lunarg commented
Closing old PR due to lack of activity

2023-05-17 18:59 UTC, closed without merging

2023-05-18 18:16 UTC, ncesario-lunarg commented on scripts/CMakeLists.txt
> +        set(UPDATE_DEPS_DIR_SUFFIX "${UPDATE_DEPS_DIR_SUFFIX}/x86")
> This will break `vvl.yml` caching.

@juan-lunarg Any ideas how to get this working with vvl.yml caching? Seems like we need to declare a map or something to that effect to map the various cmake generators to 32/64, but I'm not sure if that's possible in github yml. I'd like to get this merged before Android cmake is working, but it would also be nice to have for Windows 32/64 bit builds.

2023-05-18 18:40 UTC, ncesario-lunarg commented
"Reopen PR" didn't seem to work as intended. This is now moved #5875.