layers: Add condition to validate clear attachments
KhronosGroup/Vulkan-ValidationLayers pull request #5795
Opened 2023-05-04 14:08 UTC by matkow01-arm

Issue with `VkCmdClearAttachments` was spotted after changing VL version to 1.3.243 and higher.
This is very similar to issue #657.

While using `VkCmdClearAttachments` in secondary command buffer with null in framebuffer pointer at inheritance structure I see that application is crashing in `CoreChecks::PreCallValidateCmdClearAttachments`. VL are trying to operate on image view's that comes from framebuffer pointer which is NULL.

I propose to add additional conditions to if statement for covering that case (skip checking framebuffer related objects when framebuffer pointer is NULL).

2023-05-04 14:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5795) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5795) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-ValidationLayers?pullRequest=5795) it.</sub>

2023-05-04 14:54 UTC, spencer-lunarg commented
This looks good to me, but we will definitely want a test to prevent this from regressing in the future

2023-05-04 17:25 UTC, juan-lunarg requested changes
Add testing to prevent regression.

2023-05-08 19:48 UTC, juan-lunarg commented
I pulled down this PR locally and verified the test passes with our Mock Vulkan driver.

As soon as https://github.com/KhronosGroup/Vulkan-Loader/pull/1194 is merged, I'll re-trigger the CI and it should pass then I'll merged it in.

2023-05-08 21:32 UTC, juan-lunarg requested changes

2023-05-08 21:32 UTC, juan-lunarg commented on tests/positive/command.cpp
> +    hinfo.framebuffer = nullptr;
32 bit compilation error

> 6>C:\j\vz2\Release32\Vulkan-ValidationLayers\tests\positive\command.cpp(155,32): error C2440: '=': cannot convert from 'nullptr' to 'VkFramebuffer' [C:\j\vz2\Release32\Vulkan-ValidationLayers\build32\tests\vk_layer_validation_tests.vcxproj]

```suggestion
```

2023-05-09 08:44 UTC, arno-lunarg commented on tests/positive/command.cpp
> +    hinfo.framebuffer = nullptr;
We get this error in our internal CI. On top of my head, it is because on 32 bits platforms, a Vulkan handle is defined as a `uint64_t`. 
Since structs are zero initialised when using `LvlInitStruct`, you can simply do:
```cpp
auto hinfo = LvlInitStruct<VkCommandBufferInheritanceInfo>();
hinfo.renderPass = renderPass();
auto info = LvlInitStruct<VkCommandBufferBeginInfo>();
info.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT | VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT;
info.pInheritanceInfo = &hinfo;

// ...
```

2023-05-09 18:46 UTC, juan-lunarg commented
> Author matkow01-arm not on autobuild list. Waiting for curator authorization before starting CI build.

I've added you to the autobuild list so Jenkins will trigger automatically in the future

2023-05-09 21:17 UTC, juan-lunarg commented on tests/positive/command.cpp
> +
Testing is passing on all Android devices except the ShieldTV.

```suggestion
    if (IsPlatform(kShieldTV) || IsPlatform(kShieldTVb)) {
        GTEST_SKIP() << "This test should not run on Shield TV";
    }
```

2023-05-09 21:17 UTC, juan-lunarg commented on tests/positive/command.cpp
> +    color_attachment.colorAttachment = 0;
```suggestion
    VkClearAttachment color_attachment = {};
    color_attachment.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
```

2023-05-09 21:17 UTC, juan-lunarg commented on tests/positive/command.cpp
> +    VkClearAttachment ds_attachment;
```suggestion
    VkClearAttachment ds_attachment = {};
```

2023-05-09 21:22 UTC, juan-lunarg commented on tests/positive/command.cpp
> +TEST_F(PositiveCommand, ClearAttachmentsCalledWithoutFbInSecondaryCB) {
Testing is failing on a `ShieldTV` but is passing on all other Android devices

<details>

```
ERROR: ShieldTV-1322020015983: CRASH in package com.example.VulkanLayerValidationTests
ERROR: ShieldTV-1322020015983: signal 11 (SIGSEGV) code 1 (SEGV_MAPERR) fault_addr 0x70
ERROR: ShieldTV-1322020015983: cause null pointer dereference
ERROR: ShieldTV-1322020015983: backtrace follows
    #00 pc 0000000001016408  /vendor/lib64/libglcore.so (__VkFramebuffer::GetColorView(__VkRenderPass const*, unsigned int, unsigned int) const+40)
    #01 pc 000000000104136c  /vendor/lib64/libglcore.so (__VkCommandBuffer::ClearColorAttachment(unsigned int, VkClearColorValue const*, unsigned int, VkClearRect const*)+268)
    #02 pc 0000000001040f10  /vendor/lib64/libglcore.so (__VkCommandBuffer::CmdClearAttachments(unsigned int, VkClearAttachment const*, unsigned int, VkClearRect const*)+240)
    #03 pc 0000000001a72ae8  /data/app/com.example.VulkanLayerValidationTests-do95A9BgqHBc5JRYsNlNWA==/lib/arm64/libVkLayer_khronos_validation.so
    #04 pc 0000000001b23d88  /data/app/com.example.VulkanLayerValidationTests-do95A9BgqHBc5JRYsNlNWA==/lib/arm64/libVkLayer_khronos_validation.so
    #05 pc 0000000001559a28  /data/app/com.example.VulkanLayerValidationTests-do95A9BgqHBc5JRYsNlNWA==/lib/arm64/libVulkanLayerValidationTests.so
    #06 pc 0000000001901f0c  /data/app/com.example.VulkanLayerValidationTests-do95A9BgqHBc5JRYsNlNWA==/lib/arm64/libVulkanLayerValidationTests.so (_ZN7testing8internal38HandleSehExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc+112)
    #07 pc 00000000018d51ec  /data/app/com.example.VulkanLayerValidationTests-do95A9BgqHBc5JRYsNlNWA==/lib/arm64/libVulkanLayerValidationTests.so (_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc+92)
    #08 pc 00000000018d5144  /data/app/com.example.VulkanLayerValidationTests-do95A9BgqHBc5JRYsNlNWA==/lib/arm64/libVulkanLayerValidationTests.so (testing::Test::Run()+176)
    #09 pc 00000000018d5c24  /data/app/com.example.VulkanLayerValidationTests-do95A9BgqHBc5JRYsNlNWA==/lib/arm64/libVulkanLayerValidationTests.so (testing::TestInfo::Run()+204)
    #10 pc 00000000018d69d4  /data/app/com.example.VulkanLayerValidationTests-do95A9BgqHBc5JRYsNlNWA==/lib/arm64/libVulkanLayerValidationTests.so (testing::TestSuite::Run()+256)
    #11 pc 00000000018e084c  /data/app/com.example.VulkanLayerValidationTests-do95A9BgqHBc5JRYsNlNWA==/lib/arm64/libVulkanLayerValidationTests.so (testing::internal::UnitTestImpl::RunAllTests()+1004)
    #12 pc 00000000019061dc  /data/app/com.example.VulkanLayerValidationTests-do95A9BgqHBc5JRYsNlNWA==/lib/arm64/libVulkanLayerValidationTests.so (_ZN7testing8internal38HandleSehExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc+112)
    #13 pc 00000000018e03ec  /data/app/com.example.VulkanLayerValidationTests-do95A9BgqHBc5JRYsNlNWA==/lib/arm64/libVulkanLayerValidationTests.so (_ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc+92)
    #14 pc 00000000018e0228  /data/app/com.example.VulkanLayerValidationTests-do95A9BgqHBc5JRYsNlNWA==/lib/arm64/libVulkanLayerValidationTests.so (testing::UnitTest::Run()+204)
    #15 pc 000000000113c4a4  /data/app/com.example.VulkanLayerValidationTests-do95A9BgqHBc5JRYsNlNWA==/lib/arm64/libVulkanLayerValidationTests.so
    #16 pc 000000000113c1f0  /data/app/com.example.VulkanLayerValidationTests-do95A9BgqHBc5JRYsNlNWA==/lib/arm64/libVulkanLayerValidationTests.so
    #17 pc 00000000018926c0  /data/app/com.example.VulkanLayerValidationTests-do95A9BgqHBc5JRYsNlNWA==/lib/arm64/libVulkanLayerValidationTests.so
    #18 pc 000000000008196c  /system/lib64/libc.so (__pthread_start(void*)+36)
    #19 pc 00000000000234b8  /system/lib64/libc.so (__start_thread+68)
```

</details>

2023-05-09 21:40 UTC, juan-lunarg commented on tests/positive/command.cpp
> +TEST_F(PositiveCommand, ClearAttachmentsCalledWithoutFbInSecondaryCB) {
@matkow01-arm unless you see something wrong with the test (I don't). It may be prudent to just skip this test on ShieldTV, we have quite a few tests that do this already.

2023-05-10 07:06 UTC, matkow01-arm commented on tests/positive/command.cpp
> +TEST_F(PositiveCommand, ClearAttachmentsCalledWithoutFbInSecondaryCB) {
To be honest I can't find suspicious part of test that can cause crashing here for ShieldTV.

2023-05-10 13:46 UTC, juan-lunarg commented on tests/positive/command.cpp
> +TEST_F(PositiveCommand, ClearAttachmentsCalledWithoutFbInSecondaryCB) {
Gotcha. I'll amend your test to skip on ShieldTV then.

2023-05-10 13:51 UTC, juan-lunarg commented on tests/positive/command.cpp
> +    }
@matkow01-arm I've added the skip for ShieldTV. As soon as testing passes I'll merge this PR in.

2023-05-10 13:52 UTC, matkow01-arm commented on tests/positive/command.cpp
> +    }
@juan-lunarg Thanks for helping me with that kind of activities.

2023-05-10 14:24 UTC, juan-lunarg commented on tests/positive/command.cpp
> +    }
No worries, I'm happy to help. Also worth noting open source contributors can now see the results of our internal Jenkins via `LunarG CI Checkrun`. So in the future you'll be able to see the results of your test on real hardware instead of us having to relay it to you.

For your PR:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5795/checks?check_run_id=13376049195

Note this feature is still relatively new, but it looks like it's working quite well. We are doing our best to improve the experience for contributors outside LunarG.

2023-05-10 15:19 UTC, merged

2023-05-10 15:20 UTC, juan-lunarg commented
Thanks for the contribution @matkow01-arm :+1: