layers: Ignore pNext structs in GPLs
KhronosGroup/Vulkan-ValidationLayers pull request #5829
Opened 2023-05-09 21:43 UTC by ncesario-lunarg

VkPipelineRenderingCreateInfo is part of fragment output state, and thus
should be ignored when a pipeline is being created without fragment
output state.

2023-05-17 22:07 UTC, ncesario-lunarg commented on layers/generated/layer_chassis_dispatch.cpp
> +            auto state_info = dynamic_cast<ValidationStateTracker*>(layer_data);
Note that we already rely on RTTI (see `BUILD_DISPATCH_VECTOR` in chassis_dispatch_helper.h).

2023-05-17 22:08 UTC, ncesario-lunarg commented on layers/state_tracker/cmd_buffer_state.cpp
> -        uint32_t bit_shift = 0;
I'm hitting this warning locally on main; I'm not sure why it's not getting hit in CI.

2023-05-18 06:32 UTC, spencer-lunarg commented on layers/state_tracker/pipeline_state.h
> +                   const ValidationStateTracker *state_data)
nit: The other helpers in `PIPELINE_STATE` use `const ValidationStateTracker& state_data`

2023-05-18 06:36 UTC, spencer-lunarg commented on layers/state_tracker/render_pass_state.h
> +    const bool rasterization_enabled{true};
This will override `rasterization_enabled(rasterization_enabled)` in the constructor

2023-05-18 06:40 UTC, spencer-lunarg commented on layers/state_tracker/pipeline_state.h
> +        if (safe_struct->sType == VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO) {
Is the idea `PNextCopyState` could have more than just `PnextRenderingInfoCustomCopy` and see we will chekc the `sType` in each helper Custom Copy function?

2023-05-18 06:40 UTC, spencer-lunarg approved these changes
LGTM - Few questions

2023-05-18 17:40 UTC, ncesario-lunarg commented on layers/state_tracker/pipeline_state.h
> +                   const ValidationStateTracker *state_data)
:+1: yeah, I'll take this opportunity to update this.

2023-05-18 17:50 UTC, ncesario-lunarg commented on layers/state_tracker/render_pass_state.h
> +    const bool rasterization_enabled{true};
I'm not sure I understand. This is to convey that the default value of this variable is true, and it will be set to true in constructors that do not set it. That's the intent at least, is that not happening?

2023-05-18 17:56 UTC, juan-lunarg commented
Will this PR close https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5233 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5650 ?

2023-05-18 17:59 UTC, juan-lunarg commented on layers/state_tracker/cmd_buffer_state.cpp
> -        uint32_t bit_shift = 0;
Likely you are using a newer compiler than what CI is using.

2023-05-18 18:01 UTC, ncesario-lunarg commented on layers/state_tracker/pipeline_state.h
> +        if (safe_struct->sType == VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO) {
Yes, the idea is that we may have other cases like this, and I didn't want to bake specific structs into `PNextCopyState`. e.g., I'm not sure if we need to ignore other structs that are only mentioned https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap10.html#pipelines-graphics-subsets-pre-rasterization in one particular sub-state. That said, I am very much open to changing this method for passing data down the pNext chain; I spun my wheels on this implementation way too much, and I'm not super happy with the end result, but I think it's better than some of the previous versions I had of it.

2023-05-18 18:39 UTC, juan-lunarg requested changes
This approach adds extra complexity the majority of safe_* structs don't need just for GPL.

2023-05-18 18:39 UTC, juan-lunarg commented on scripts/generators/helper_file_generator.py
> +#include <stdlib.h>
Use cstdlib instead of stdlib.h

```suggestion
#include <cstdlib>
```

2023-05-18 18:39 UTC, juan-lunarg commented on layers/state_tracker/render_pass_state.h
> +    const bool rasterization_enabled{true};
I believe @ncesario-lunarg is correct. I don't think setting the default value overrides the constructor.

2023-05-18 18:39 UTC, juan-lunarg commented on scripts/generators/helper_file_generator.py
> +    switch (header->sType) {
We are adding extra overhead to all safe copies/initialization just for GPLs?

This doesn't seem like the best approach.

If GPLs safe structs are so specialized maybe they need their own explicit code generation. This current approach adds extra complexity / overhead to structs that don't need it.

I'm also not sure why we want the safe struct to have a different pnext chain from the original struct. To make the validation simpler?

2023-05-18 20:32 UTC, ncesario-lunarg commented on scripts/generators/helper_file_generator.py
> +    switch (header->sType) {
> We are adding extra overhead to all safe copies/initialization just for GPLs?

Yes, though there are other potential places this could be used. e.g., this could replace all of the "manual construction" we currently specify in the code generation script, which extends beyond GPLs and is potentially useful in the future.

> This doesn't seem like the best approach.

I'm very happy to try other approaches, but I didn't see a "clean" way of doing this with our current infrastructure. `SafePNextCopy` is a recursive call, and we need state passed down the chain; having "ad-hoc" `SafePNextCopy`s for individula structs is also an added complication. If performance is an issue, then that's something we can explore, but I'd rather not if possible.

> If GPLs safe structs are so specialized maybe they need their own explicit code generation. This current approach adds extra complexity / overhead to structs that don't need it.

I would rather not wait for a solution such as this if performance is not affected. This fixes a crash and is required based on the spec (see second commit message), but--as stated earlier--this method _could_ be used to remove manual construction that is currently specified in the scripts (which would also be future work if done at all). Also, I assume separate code generation would imply different copy methods for individual structs, which, also as stated before, seems like unnecessary complexity.

> I'm also not sure why we want the safe struct to have a different pnext chain from the original struct. To make the validation simpler?

No, the spec requires that we must ignore certain fields of certain pNext structs based on graphics pipeline state. See, e.g., the comment about `viewMask` in https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap10.html#pipelines-graphics-subsets-pre-rasterization. I'm happy to explore other suggestions anyone has to approach this differently; there is probably a much nicer way to get to a solution here that I didn't see.

2023-05-18 21:07 UTC, juan-lunarg commented on scripts/generators/helper_file_generator.py
> +    switch (header->sType) {
Gotcha I think I see the tradeoffs and understand the current approach.

2023-05-18 21:11 UTC, juan-lunarg requested changes
Add a test in `other.cpp` directly testing the new functionality added to safe structs.

See for an example of the safe structs being tested. `VkPositiveLayerTest.SafeVoidPointerCopies`

It may be prudent to have a test file for generated code.

The test should also highlight why the new functionality is needed.

2023-05-19 02:57 UTC, spencer-lunarg commented on layers/state_tracker/render_pass_state.h
> +    const bool rasterization_enabled{true};
ok, my C++ judo is always mixed, maybe it was

`const bool rasterization_enabled = true;`

or

`bool rasterization_enabled{true};`

but I recently had a bug because I thought I was setting it in the constructor and then it was re-initializing it here in the header

2023-05-19 19:00 UTC, juan-lunarg commented on layers/state_tracker/render_pass_state.h
> +    const bool rasterization_enabled{true};
> If a non-static data member has a default member initializer  and also appears in a member initializer list, then the member  initializer is used and the default member initializer is ignored (since C++11):

```c++
struct S
{
    int n = 42;   // default member initializer
    S() : n(7) {} // will set n to 7, not 42
};
```

https://en.cppreference.com/w/cpp/language/constructor

2023-05-19 19:06 UTC, juan-lunarg approved these changes

2023-05-19 19:06 UTC, juan-lunarg commented on tests/positive/other.cpp
> +    TEST_DESCRIPTION("Check passing custom data down the pNext chain for safe struct construction");
Complete nitpick. Please add a brief explanation of why this functionality was added to safe structs.

2023-05-19 19:52 UTC, juan-lunarg requested changes
`VkPositiveLayerTest.CustomSafePNextCopy` fails ASAN

2023-05-19 21:04 UTC, ncesario-lunarg commented
> `VkPositiveLayerTest.CustomSafePNextCopy` fails ASAN

Yeah, scoping mistake on my part. Should be fixed now.

2023-05-19 21:14 UTC, juan-lunarg approved these changes

2023-05-20 03:19 UTC, ncesario-lunarg commented
I want to get this through the perf suite before merging, but having some difficulties there with our CI machines. I will hopefully merge this once that's figured out.

2023-05-22 16:38 UTC, artem-lunarg commented on layers/state_tracker/cmd_buffer_state.cpp
>          while (stage_flags) {
nit: since this code is touched,  it should be possible to remove `stage_flags` and the `while` loop which sets the flags to zero.

2023-05-22 16:54 UTC, ncesario-lunarg commented on layers/state_tracker/cmd_buffer_state.cpp
>          while (stage_flags) {
:+1: good point. I just removed this since my compiler complained about it.

2023-05-22 17:04 UTC, merged