layers: Relabel maintenance4 VUID
KhronosGroup/Vulkan-ValidationLayers pull request #5856
Opened 2023-05-15 09:35 UTC by spencer-lunarg

add `VUID-RuntimeSpirv-OpTypeVector-06816` VUID

Add a negative test also (`PositiveShaderInterface.RelaxedTypeMatch` is already testing this in for a Positive test)

2023-05-15 16:54 UTC, juan-lunarg requested changes

2023-05-15 16:54 UTC, juan-lunarg commented on layers/core_checks/cc_shader.cpp
> +                                     "between input and output vectors.",
This last half of the error message doesn't make sense if `IsExtEnabled(device_extensions.vk_khr_maintenance4)` is true.

2023-05-15 16:57 UTC, arno-lunarg approved these changes

2023-05-16 02:55 UTC, spencer-lunarg commented on layers/core_checks/cc_shader.cpp
> +                                     "between input and output vectors.",
It is still a valid message, honestly these "If VUID" things are kinda nasty

You will ONLY get the first VUID if you enabled the extension, but not the feature bit.

I think adding information that a `maintenance` extension is around that makes a VU valid is helpful for a developer

2023-05-16 05:54 UTC, ncesario-lunarg approved these changes

2023-05-16 15:59 UTC, juan-lunarg approved these changes

2023-05-16 16:00 UTC, merged