tests: Add SPIRV-Hopper
KhronosGroup/Vulkan-ValidationLayers pull request #5913
Opened 2023-05-26 11:43 UTC by spencer-lunarg

Adds a new `SPIRV-Hopper` test harness

I have ran this on a lot of shaders generated from various places, and it now passes them all

As more shaders are added, this can be updated, but this is in good enough shape to start using for CI once merged

2023-05-26 16:15 UTC, artem-lunarg commented on tests/spirv_hopper/pass_through_shaders.cpp
> +        return false;
`shader` probably leaks here

2023-05-26 17:03 UTC, artem-lunarg commented on tests/spirv_hopper/spirv_hopper.cpp
> +        VkSubpassDependency dependency = {};
This dependency looks fine but I wonder if there was something that forced to add it? It looks the render pass specifies layout transition from UNDEFINED to GENERAL and in that case we have implicit EXTERNAL dependency.

2023-05-26 17:05 UTC, juan-lunarg commented on tests/spirv_hopper/main.cpp
> +namespace fs = std::filesystem;
```suggestion
```

2023-05-26 17:05 UTC, juan-lunarg commented on tests/spirv_hopper/external/spirv_reflect.cpp
> +#include "spirv_reflect.c"
Change the file extension of spirv_reflect.cpp. That's what we did with xxhash.c -> xxhash.cpp

2023-05-26 17:05 UTC, juan-lunarg commented on tests/spirv_hopper/external/CMakeLists.txt
Please add a README.md in this directory where these files came from since there isn't a known_good.json

2023-05-26 17:14 UTC, artem-lunarg commented on tests/spirv_hopper/main.cpp
> +                std::cout << "[" << files_ran_count++ << "|" << files_list_count << "] Running " << file << std::endl;
nit: Just to raise awareness. The difference between '\n' and std::endl is that the latter additionally flushes the stream. When a lot of output is performed on slow output devices (like Windows console or write to file) this can have measurable performance impact. Hard to say for this specific case.

2023-05-26 18:02 UTC, juan-lunarg commented on tests/spirv_hopper/main.cpp
> +                std::cout << "[" << files_ran_count++ << "|" << files_list_count << "] Running " << file << std::endl;
Agree it's best practice to only use std::endl when you actually need it.

2023-05-27 00:44 UTC, spencer-lunarg commented on tests/spirv_hopper/pass_through_shaders.cpp
> +    /* .MaxLights = */ 32,
went the `static TBuiltInResource InitResources()` approuch

2023-05-27 00:45 UTC, spencer-lunarg commented on tests/spirv_hopper/pass_through_shaders.cpp
> +        return false;
1. We should never be getting here, this would mean there is an error in `spirv-hopper`

2. I don't know if it leaks, I think it is all scoped on this stack in this function anyway

2023-05-27 00:48 UTC, spencer-lunarg commented on tests/device_profiles/spirv_hopper_profile.json
No (I can explain more in the README.md)

1. But there are limits we don't actually want set to Max UINT32_T in `max_profile.json` (because we need to test above the limit)
2. Some features we turn to `false` in  `max_profile.json` in order to make the tests fail because it doesn't have it
3. If we decide to move this out of VVL, its a small and portable profile

2023-05-27 00:49 UTC, spencer-lunarg commented on tests/spirv_hopper/external/spirv_reflect.cpp
> +#include "spirv_reflect.c"
ya, I guess that is an advantage of checking it in

2023-05-27 00:49 UTC, spencer-lunarg commented on tests/spirv_hopper/main.cpp
> +                std::cout << "[" << files_ran_count++ << "|" << files_list_count << "] Running " << file << std::endl;
#TheMoreYouKnow - Will update

2023-05-27 01:19 UTC, spencer-lunarg commented on tests/spirv_hopper/spirv_hopper.cpp
> +        VkSubpassDependency dependency = {};
ok, good catch, this is not needed at all to still be valid, removed

2023-05-29 08:26 UTC, arno-lunarg commented on tests/spirv_hopper/main.cpp
> +                file_list.push_back(dir_entry.path().c_str());
```suggestion
                file_list.push_back(dir_entry.path().string());
```

2023-05-29 08:43 UTC, arno-lunarg commented on tests/spirv_hopper/CMakeLists.txt
> +    dl
`dl` Not found on Windows

2023-05-29 12:34 UTC, arno-lunarg commented
Regarding the `dl` lib: since it seems needed for the ubuntu 20 + gcc 9 build, maybe continue to link it on linux?

2023-05-29 18:08 UTC, juan-lunarg commented on tests/spirv_hopper/CMakeLists.txt
> +target_compile_definitions(spirv-hopper PRIVATE SPIRV_REFLECT_USE_SYSTEM_SPIRV_H=1)
Remove this line entirely.

```suggestion
```

2023-05-29 18:08 UTC, juan-lunarg commented on tests/spirv_hopper/README.md
> +This tool is designed to be simple, its main job is to help catch issues in Shader Validation by allowing us to run against MANY shaders quickly. Paired with a database of SPIR-V binaries from a vari
```suggestion
This tool is designed to be simple, its main job is to help catch issues in Shader Validation by allowing us to run against MANY shaders quickly. Paired with a database of SPIR-V binaries from various SPIR-V generated tools (not just `glslang`), we can catch bugs/crashes at a per-commit testing level
```

2023-05-29 18:08 UTC, juan-lunarg commented on tests/spirv_hopper/external/CMakeLists.txt
> +target_compile_definitions(spirv-reflect PUBLIC SPIRV_REFLECT_USE_SYSTEM_SPIRV_H=1)
```suggestion
target_compile_definitions(spirv-reflect PUBLIC SPIRV_REFLECT_USE_SYSTEM_SPIRV_H)
```

2023-05-29 18:10 UTC, juan-lunarg commented
https://kubasejdak.com/modern-cmake-is-like-inheritance

Please review the above documentation for understanding PRIVATE vs PUBLIC.

2023-05-30 17:41 UTC, juan-lunarg requested changes

2023-05-30 17:41 UTC, juan-lunarg commented on tests/spirv_hopper/CMakeLists.txt
> +    ${CMAKE_DL_LIBS}
I'd prefer `VkLayer_utils` link against ${CMAKE_DL_LIBS} since `lvt_function_pointers.cpp` belongs to `VkLayer_utils` and is what actually requires the ${CMAKE_DL_LIBS} functionality.

That way we also only link ${CMAKE_DL_LIBS} once in the CMake code as well.

2023-05-30 17:41 UTC, juan-lunarg commented on tests/spirv_hopper/CMakeLists.txt
> +    pass_through_shaders.cpp
Sort the source files listed here.

2023-05-30 17:41 UTC, juan-lunarg commented on tests/device_profiles/spirv_hopper_profile.json
> +        "MAX_PROFILE": {
Why does this say `MAX_PROFILE`?

2023-05-30 17:41 UTC, juan-lunarg commented on tests/device_profiles/spirv_hopper_profile.json
Can we inherit from `max_profile.json`? IE override what we need to, but defer to `max_profile.json` when we don't specify? My intent being to reduce the size of this json and avoid duplicate efforts.

2023-05-30 17:41 UTC, juan-lunarg commented on tests/spirv_hopper/main.cpp
> +
```suggestion
```

2023-05-30 17:41 UTC, juan-lunarg commented on tests/spirv_hopper/main.cpp
> +        return -1;
```suggestion
        return EXIT_FAILURE;
```

2023-05-30 17:41 UTC, juan-lunarg commented on tests/spirv_hopper/main.cpp
> +        return -1;
```suggestion
        return EXIT_FAILURE;
```

2023-05-30 17:41 UTC, juan-lunarg commented on tests/spirv_hopper/main.cpp
> +    return result;
```suggestion
    if (!failed_files.empty()) {
        std::cout << "\nRESULT: Failure!\n";
        std::cout << "\nThe following tests failed:\n";
        for (const auto& file : failed_files) {
            std::cout << "\t" << file << "\n";
        }
        return EXIT_FAILURE;
    }
    
    std::cout << "\nRESULT: Success!\n";
```

2023-05-30 17:41 UTC, juan-lunarg commented on tests/spirv_hopper/main.cpp
> +            if (spirv_data == nullptr) {
Use std::vector to avoid manually calling malloc/free

2023-05-30 17:41 UTC, juan-lunarg commented on tests/spirv_hopper/pass_through_shaders.cpp
> +static constexpr bool IsFloatFormat(SpvReflectFormat format) {
Do we not already have this functionality in vvl or vll testing?

2023-05-31 03:22 UTC, spencer-lunarg commented on tests/spirv_hopper/pass_through_shaders.cpp
> +static constexpr bool IsFloatFormat(SpvReflectFormat format) {
This is `SPV_REFLECT_FORMAT` not `VkFormat`, its a subset the library decided

Honestly, my goal was to replace this with a fix in SPIRV-Reflect to have this, as this function depends on SPIRV-Reflect,  unlike the other VVL util

2023-05-31 05:28 UTC, spencer-lunarg commented on tests/device_profiles/spirv_hopper_profile.json
> Can we inherit from max_profile.json

We don't want to inherit anything from `max_profile`, the point of this profile is to have different values

> but defer to max_profile.json when we don't specify? 

If we leave it blank, we defer it to false (or whatever default Profile layers give)

> My intent being to reduce the size of this json and avoid duplicate efforts.

This json file in theory could just be generated from the `vk.xml` using the `<spirvextensions>` and `<spirvcapabilities>` tags (Which would be more ideal and what I originally wanted)

As for size, this is by far the smallest profile we have now (after I just went in now and trimmed more stuff out)

```
475K max_profile.json
216K pixel_6_mali.json
179K nvidia_tegra_x1.json
171K pixel_6_adreno.json
 41K spirv_hopper_profile.json
```

2023-05-31 07:25 UTC, arno-lunarg approved these changes

2023-05-31 16:32 UTC, juan-lunarg approved these changes

2023-05-31 16:32 UTC, juan-lunarg commented on tests/spirv_hopper/main.cpp
> +    return 0;
4) The body of the main function does not need to contain the [return statement](https://en.cppreference.com/w/cpp/language/return): if control reaches the end of main without encountering a return statement, the effect is that of executing return 0;.

```suggestion
```

2023-05-31 16:32 UTC, juan-lunarg commented on tests/spirv_hopper/pass_through_shaders.cpp
> +    glslang::TShader* shader = new glslang::TShader(glsl_stage);
Use a smart pointer. From a cursory glance I don't see where this memory is freed.

2023-05-31 17:45 UTC, ncesario-lunarg approved these changes
Minor nits, but LGTM!

2023-05-31 17:45 UTC, ncesario-lunarg commented on tests/spirv_hopper/README.md
> +Looked into threading the work, but seems to be more investigation how to properly thread the glslang instance at runtime.
"...threading the work..." is a bit vague. Maybe just indicate that `SPIRV-Hopper` is single-threaded, but multi-threading is left for future work?

2023-05-31 17:45 UTC, ncesario-lunarg commented on tests/spirv_hopper/external/README.md
> +- It is designed to be a files people include in their build
```suggestion
- These files are designed for people to include in their build
```

2023-06-01 00:33 UTC, spencer-lunarg commented on tests/spirv_hopper/pass_through_shaders.cpp
> +    glslang::TShader* shader = new glslang::TShader(glsl_stage);
there is a `delete shader;` this code was copied from `VkTestFramework::GLSLtoSPV(`, but agree smart pointer would be better (For both)

2023-06-01 05:39 UTC, merged

2023-06-01 17:42 UTC, dneto0 commented on tests/spirv_hopper/external/README.md
> +These files are taken from https://github.com/KhronosGroup/SPIRV-Reflect
Can we not do this please?

Bugfixes and potentially security fixes get stranded.

2023-06-01 23:12 UTC, spencer-lunarg commented on tests/spirv_hopper/external/README.md
> +These files are taken from https://github.com/KhronosGroup/SPIRV-Reflect
Would it be better for the short term to hide this `SPIRV-Hopper` behind an extra Opt-In flag

2023-06-01 23:16 UTC, juan-lunarg commented on tests/spirv_hopper/external/README.md
> +These files are taken from https://github.com/KhronosGroup/SPIRV-Reflect
The best solution is to upstream good CMake support IMO. I'd rather not add an extra Opt-In flag.

2023-06-02 14:15 UTC, jeremyg-lunarg commented on tests/spirv_hopper/external/README.md
> +These files are taken from https://github.com/KhronosGroup/SPIRV-Reflect
> The best solution is to upstream good CMake support IMO. I'd rather not add an extra Opt-In flag.

Should we do the same for VMA?

2023-06-02 15:10 UTC, jeremyg-lunarg commented on tests/spirv_hopper/external/README.md
> +These files are taken from https://github.com/KhronosGroup/SPIRV-Reflect
Also, this needs to be a new issue, not a discussion on a closed PR