layers: VK_IMAGE_COMPRESSION_DEFAULT_EXT flag fix
KhronosGroup/Vulkan-ValidationLayers pull request #5972
Opened 2023-06-09 15:48 UTC by sewbro01-ARM

VL falsely marks flag VK_IMAGE_COMPRESSION_DEFAULT_EXT as invalid. The value of this enum is 0 and ValidateFlags function used to check if flags are properly set has 'flag_type' parameter set to kRequiredSingleBit which doesnt allows 0 as flag value.

Changing flag_type to kOptionalSingleBit resolves issue.

2023-06-09 16:45 UTC, spencer-lunarg requested changes
This looks good, but we really should have a positive test that uses `VK_IMAGE_COMPRESSION_DEFAULT_EXT` to prevent regressions as this is an easy thing to mess up if we would ever refactor `ValidateFlags` in the future (which is on my todo list)

2023-06-13 10:51 UTC, spencer-lunarg commented
> had some trouble with setting environment correctly for the required compression extension to work properly with VL tests.

Not sure what you had troubles with, but is it anything we failed to document somewhere? I hate when people have to waste time getting dev environment setup instead of just doing the actual work

2023-06-13 11:00 UTC, sewbro01-ARM commented
I used MockICD and Profiles layer, maybe I made some silly mistake but I couldn't make those tests to be not skipped at first, then I used our internal method for running tests with our device from ARM that unfortunately I can't share with you.

2023-06-13 16:41 UTC, merged

2023-06-13 16:44 UTC, juan-lunarg commented
> I used MockICD and Profiles layer, maybe I made some silly mistake but I couldn't make those tests to be not skipped at first, then I used our internal method for running tests with our device from ARM that unfortunately I can't share with you.

Was there something wrong/unclear with the documentation on how to setup the Mock + Profiles testing?

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/tests/README.md#running-tests-on-mockicd-and-profiles-layer

2023-06-13 22:09 UTC, juan-lunarg commented
I ended up resetting my linux dev computer. And tried to run mock + profiles testing and it didn't work at all.

I updated my vulkan loader and it works now. So our testing currently relies on an up to date loader.