layers: Fix 02679 validation
KhronosGroup/Vulkan-ValidationLayers pull request #5998
Opened 2023-06-13 10:24 UTC by arno-lunarg

And add a regression test

2023-06-13 10:50 UTC, spencer-lunarg approved these changes

2023-06-13 16:51 UTC, juan-lunarg requested changes
The issue (https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5938) in question points to a false positive. Shouldn't a positive test be added?

2023-06-13 22:08 UTC, arno-lunarg commented
@juan-lunarg  The last few lines of the new test is the positive part, but I can just add a proper positive test if you want

2023-06-13 23:25 UTC, juan-lunarg commented on tests/negative/wsi.cpp
> +    vk::DestroySwapchainKHR(device(), swapchain, nullptr);
> @juan-lunarg The last few lines of the new test is the positive part, but I can just add a proper positive test if you want

A separate positive test would be my preference. Or adding a comment. My main nitpick is it's not immediately obvious that positive behavior is being tested.

It's obvious from the context of this PR. But it's not as obvious for a future test maintainer.

2023-06-14 19:25 UTC, arno-lunarg commented on tests/negative/wsi.cpp
> +    vk::DestroySwapchainKHR(device(), swapchain, nullptr);
True, I am going to add a proper positive test

2023-06-14 19:47 UTC, juan-lunarg approved these changes

2023-06-14 22:59 UTC, merged