layers: VVL coverage for new linear attachment VUs
KhronosGroup/Vulkan-ValidationLayers pull request #6003
Opened 2023-06-13 19:55 UTC by pdaniell-nv

These new VUs make it possible to use VK_NV_linear_color_attachment without always getting a VVL error.

2023-06-13 21:45 UTC, spencer-lunarg approved these changes
Assuming you tested this locally, so happy to get this in, but would highly recommend writing an unit test to make sure this doesn't get broken in the future if this function was refactored

2023-06-13 21:57 UTC, juan-lunarg requested changes
> These new VUs make it possible to use VK_NV_linear_color_attachment without always getting a VVL error

Add positive unit test.

2023-06-13 21:57 UTC, juan-lunarg commented on layers/core_checks/cc_image.cpp
> +            skip |= LogError(image_state.image(), "VUID-VkImageViewCreateInfo-usage-08931",
Add unit test

2023-06-13 21:57 UTC, juan-lunarg commented on layers/core_checks/cc_image.cpp
> +            skip |= LogError(image_state.image(), "VUID-VkImageViewCreateInfo-usage-08932",
Add unit test

2023-06-23 17:53 UTC, juan-lunarg approved these changes

2023-06-23 21:30 UTC, merged