ci: Add SPIRV-Hopper to CI
KhronosGroup/Vulkan-ValidationLayers pull request #6038
Opened 2023-06-20 06:58 UTC by spencer-lunarg

Run SPIRV-Hopper on shaders for CI

2023-06-20 06:59 UTC, spencer-lunarg commented on scripts/common_ci.py
> +    lvt_cmd = os.path.join(TEST_INSTALL_DIR, 'bin', 'spirv-hopper')
I don't know how to make sure this is in the install bin path

2023-06-20 06:59 UTC, spencer-lunarg commented on scripts/common_ci.py
> +    spirv_db = os.path.join(TEST_INSTALL_DIR, 'shader_db')
TODO - How do we get these spirv binaries here to test

2023-06-20 07:00 UTC, spencer-lunarg commented on scripts/common_ci.py
> +    lvt_cmd = os.path.join(TEST_INSTALL_DIR, 'bin', 'spirv-hopper')
I don't know how to make sure this is in the install bin path

2023-06-20 15:08 UTC, juan-lunarg commented on scripts/common_ci.py
> +    lvt_cmd = os.path.join(TEST_INSTALL_DIR, 'bin', 'spirv-hopper')
You need to install the spirv-hopper target

2023-06-20 15:09 UTC, juan-lunarg commented on scripts/common_ci.py
> +    lvt_cmd = os.path.join(TEST_INSTALL_DIR, 'bin', 'spirv-hopper')
We do this for the tests like this: `install(TARGETS vk_layer_validation_tests)`

2023-06-20 20:39 UTC, juan-lunarg commented on scripts/common_ci.py
> +    lvt_cmd = os.path.join(TEST_INSTALL_DIR, 'bin', 'spirv-hopper')
It's just 1 line of CMake to add. By default executables install to the bin directory.

2023-06-21 05:23 UTC, spencer-lunarg commented
> Cloning into 'SPIRV-Database'...
error: unable to create file vulkan/dawn/CompressedTextureFormatTest_BufferOffsetAndExtentFitRowPitch_Subzero_e_use_temporary_buffer_in_texture_to_texture_copy_TextureFormat_TextureFormat_ASTC10x10UnormSrgb_0.spv: Filename too long

... for now, just going to remove from Windows CI

2023-06-21 07:08 UTC, spencer-lunarg commented
Currently taking 17 minutes to run in debug and 7 minutes to run in release

Would it be better to somehow build a release version of the tests (the normal `exe` and `spirv-hopper`) when testing the debug build of the layers?

My concern is taking 17 minutes when 95% of PR will not touch the Shader Validation logic

2023-06-21 16:12 UTC, juan-lunarg approved these changes

2023-06-21 16:12 UTC, juan-lunarg commented on .github/workflows/vvl.yml
> +          VK_KHRONOS_PROFILES_PROFILE_FILE: ${{ github.workspace }}/tests/device_profiles/spirv_hopper_profile.json
`SPIRV-Hopper` is quite expensive looking at the result of github actions:

![image](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/114601453/5307a8af-e622-4838-b3dc-9916a7a7bfc5)

And with the sanitized builds it's REALLY expensive:

![image](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/114601453/9af29766-7c4b-480b-8e6b-7d0f785b7a9a)

Regardless optimizing the CI is better done in another PR.

2023-06-21 16:16 UTC, juan-lunarg requested changes
On second thought we should just optimize the CI time in this PR.

2023-06-21 16:27 UTC, juan-lunarg commented on .github/workflows/vvl.yml
> +          VK_KHRONOS_PROFILES_PROFILE_FILE: ${{ github.workspace }}/tests/device_profiles/spirv_hopper_profile.json
Note the hour+ build I posted an image of is under thread sanitizer which really impacts runtime performance by 5-15 times.

2023-06-22 04:17 UTC, spencer-lunarg commented on scripts/common_ci.py
> +    spirv_db = RepoRelative("%s/SPIRV-Database/vulkan" % EXTERNAL_DIR_NAME)
Kinda... I have plans to add more SPIR-V to the database

I do plan to have maybe a `vvl_issue` folder so if people do have bad shaders, I can throw it there instead of making a one off test in the unit test folder

2023-06-22 15:44 UTC, juan-lunarg approved these changes

2023-06-29 01:15 UTC, spencer-lunarg commented
decided to turn this into a nightly job, where to do it can be figured out later, closing for now (as don't have time to look into, and I can run locally for now)

2023-06-29 01:15 UTC, closed without merging