tests: Move tests to Unit folder and rename
KhronosGroup/Vulkan-ValidationLayers pull request #6044
Opened 2023-06-21 05:22 UTC by spencer-lunarg

- Creates a `tests/unit` folder
- Moved all `positive/` tests there with the name of the file having the `_positive` suffix

2023-06-21 16:55 UTC, juan-lunarg requested changes

2023-06-21 16:55 UTC, juan-lunarg commented on tests/CMakeLists.txt
> +    unit/android_hardware_buffer_positive.cpp
Fix the file ordering. This should be alphabetically ordered like how it was before.

2023-06-22 16:29 UTC, juan-lunarg approved these changes

2023-06-22 16:29 UTC, juan-lunarg commented on tests/CMakeLists.txt
> +    unit/atomics_positive.cpp
It's beautiful 🥇

2023-06-22 17:17 UTC, arno-lunarg approved these changes
Nice!!

2023-06-23 06:18 UTC, merged