Vk khr cooperative matrix vvl
KhronosGroup/Vulkan-ValidationLayers pull request #6093
Opened 2023-06-30 13:50 UTC by archimedus

TODO:
* Wait for proper Vulkan-Headers with VUID ids assigned
* Check test is ready and properly run

2023-07-03 13:14 UTC, spencer-lunarg commented on layers/core_checks/cc_shader.cpp
> +VkComponentTypeKHR GetComponentTypeKHR(const Instruction *insn) {
nit: Can we move this into the `Instruction` class

2023-07-03 13:15 UTC, spencer-lunarg commented on layers/core_checks/cc_shader.cpp
> +VkComponentTypeKHR GetComponentTypeKHR(const Instruction *insn) {
Lets make this either a static function, lambda, or just inline this, I can't imagine this will be used elsewhere

2023-07-03 13:17 UTC, spencer-lunarg commented on layers/core_checks/cc_shader.cpp
> +VkComponentTypeKHR GetComponentTypeKHR(const Instruction *insn) {
ok, nvm, I see you are just matching the `ValidateCooperativeMatrix` way we are doing it for the NV version... I guess for now this is fine

2023-07-03 13:21 UTC, spencer-lunarg commented on tests/unit/subgroups.cpp
> +    m_errorMonitor->SetUnexpectedError("VUID-RuntimeSpirv-MSize-08975");
This test is for `VK_NV_cooperative_matrix`, why are we now hitting ` VUID-RuntimeSpirv-MSize-08975` which is for KHR only

2023-07-03 13:23 UTC, spencer-lunarg requested changes
The layer code looks fine, we have a PR to get the 1.3.256 headers in, so will need to rebase on that (hopefully that will just be merged in the next 24 hours)

But this PR is missing actual testing

1. We need a test for every VU that was added
- [ ] VUID-RuntimeSpirv-cooperativeMatrixSupportedStages-08985
- [ ] VUID-RuntimeSpirv-OpTypeCooperativeMatrixKHR-08974
- [ ] VUID-RuntimeSpirv-OpCooperativeMatrixMulAddKHR-08976
- [ ] VUID-RuntimeSpirv-OpCooperativeMatrixMulAddKHR-08978
- [ ] VUID-RuntimeSpirv-OpCooperativeMatrixMulAddKHR-08980
- [ ] VUID-RuntimeSpirv-OpCooperativeMatrixMulAddKHR-08982
- [ ] VUID-VkPipelineShaderStageCreateInfo-module-08987
- [ ] VUID-RuntimeSpirv-scope-08984
- [ ] VUID-RuntimeSpirv-saturatingAccumulation-08983
- [ ] VUID-RuntimeSpirv-MSize-08975
- [ ] VUID-RuntimeSpirv-KSize-08977
- [ ] VUID-RuntimeSpirv-MSize-08979
- [ ] VUID-RuntimeSpirv-MSize-08981

2. We need at least 1 positive test (in `tests/unit/subgroups_positive.cpp`) that uses `VK_KHR_cooperative_matrix` but doesn't hit any Validation errors

2023-07-03 14:36 UTC, archimedus commented
> 1.  We need a test for every VU that was added

Well, I was basing on NV version, this one did not have any of such.

Will start implementing.


> 2. We need at least 1 positive test (in tests/unit/subgroups_positive.cpp) that uses VK_KHR_cooperative_matrix but doesn't hit any Validation errors

I am sorry I do not see `subgroups_positive.cpp` file in the project, do you mean I should add it?

2023-07-03 15:23 UTC, kpet commented
cc'ing @jeffbolznv since he took an action to start looking into this in the last Vulkan ML teleconference.

2023-07-03 17:17 UTC, jeffbolznv commented
> cc'ing @jeffbolznv since he took an action to start looking into this in the last Vulkan ML teleconference.

I hadn't done any work yet, and I don't object to somebody else doing it.

2023-07-07 11:54 UTC, archimedus commented
It looks like the only left 

* VUID-RuntimeSpirv-saturatingAccumulation-08983

2023-07-10 11:04 UTC, archimedus commented
> It looks like the only left
>
> *    VUID-RuntimeSpirv-saturatingAccumulation-08983

I don't know how to implement it in a sensible way.

It looks like it can force a lot of iterations: it looks we should find a pair of properties where saturatingAccumulation is true in one record and false in another. Number of properties returned by implementation can be as large as 11*11*11*2=2662 (i.e. 11 types for matrix A, B and C and saturatingAccumulation set to true/false), and number of comparisons in this case 2662<sup>2</sup>/2 = 3.5M.

2023-07-10 11:15 UTC, spencer-lunarg commented
> I don't know how to implement it in a sensible way.

Actually reading that VU, I am confused by it as well, 

> For OpCooperativeMatrixMulAddKHR, the SaturatingAccumulation cooperative matrix operand must be present if and only if VkCooperativeMatrixPropertiesKHR::saturatingAccumulation is VK_TRUE.

@jeffbolznv was this just suppose to mean if "any" `VkCooperativeMatrixPropertiesKHR` has `saturatingAccumulation` , or is there some implicit way we map a certain index of `VkCooperativeMatrixPropertiesKHR`  to each instruction?

2023-07-10 11:18 UTC, spencer-lunarg commented on tests/unit/shader_cooperative_matrix.cpp
> +    m_errorMonitor->SetUnexpectedError("VUID-RuntimeSpirv-OpTypeCooperativeMatrixKHR-06316");
just fyi, this is not an actual VU

I try to avoid using`SetUnexpectedError` unless adding a comment why

2023-07-10 11:22 UTC, spencer-lunarg commented on tests/unit/shader_cooperative_matrix.cpp
> +        for (const auto &y : subtests) {
while this seems "clever" to do, we have repeated by experiences with these types of test logic around the VUID error messages

I would perfer just unrolling the loop, while its more verbose, its MUCH easier to maintain in the long run for us

... a better question, why are we having to ignore 8 VUs each time? why are we not able to query the properties and write a test that doesn't fail in `VUID-RuntimeSpirv-MSize-08975`

2023-07-10 11:23 UTC, spencer-lunarg commented on tests/unit/shader_cooperative_matrix_positive.cpp
> +    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "VUID-VkPipelineShaderStageCreateInfo-pSpecializationInfo-06849");
positive tests are not allowed to have any errors, they are designed to make sure when people use the API correctly, it won't produce false positive validation errors

2023-07-10 11:24 UTC, spencer-lunarg commented on tests/unit/shader_cooperative_matrix.cpp
> +    m_errorMonitor->SetAllowedFailureMsg("VUID-RuntimeSpirv-MSize-08975");
why are we having to ignore 8 VUs each time? why are we not able to query the properties and write a test that doesn't fail in `VUID-RuntimeSpirv-MSize-08975`

2023-07-10 11:43 UTC, jeffbolznv commented
> > For OpCooperativeMatrixMulAddKHR, the SaturatingAccumulation cooperative matrix operand must be present if and only if VkCooperativeMatrixPropertiesKHR::saturatingAccumulation is VK_TRUE.
> 
> @jeffbolznv was this just suppose to mean if "any" `VkCooperativeMatrixPropertiesKHR` has `saturatingAccumulation` , or is there some implicit way we map a certain index of `VkCooperativeMatrixPropertiesKHR` to each instruction?

I didn't write it, but I interpret it to mean that if an instruction uses SaturatingAccumulation then there must be a property matching the instruction's types and dimensions that has saturatingAccumulation==TRUE.

I don't understand the previous comment. Realistically there aren't going to be thousands of cooperative matrix properties, and the complexity of this check could just be a hash map lookup.

2023-07-10 13:05 UTC, archimedus commented
> I don't understand the previous comment. Realistically there aren't going to be thousands of cooperative matrix properties

Upper limit properties reported: 11<sup>3</sup>*2. I agree that it will look weird to have A=i32, B=i32 and C=i8, though possible and I have no information what implementations will export.

> and the complexity of this check could just be a hash map lookup.

Could not agree with this. For example: assume we have only one property: A,B,C=i32, saturatingAccumulation=TRUE.
The test can easily be implemented: OpCooperativeMatrixMulAddKHR without SaturatingAccumulation. 

Now imagine two such properties reported:

A,B,C=i32, saturatingAccumulation=TRUE
A,B,C=i32, saturatingAccumulation=FALSE

Test CANNOT be implemented, because due to operation is allowed with SaturatingAccumulation (allowed by 1st properties) and without SaturatingAccumulation (allowed by 2nd properties). I.e. test CANNOT cause this VUID.

Thus test should take first record (with saturatingAccumulation=TRUE) and enumerate all left looking for 2nd record (with saturatingAccumulation=FALSE). Thus complexity is (11<sup>3</sup>*2)<sup>2</sup>/2.

2023-07-10 13:19 UTC, archimedus commented on tests/unit/shader_cooperative_matrix_positive.cpp
> +    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "VUID-VkPipelineShaderStageCreateInfo-pSpecializationInfo-06849");
This is NV code, I just moved it as you suggested from one file to another. 
I don't know why it was added, but it is optional within my environment, I will remove these two SetUnexpectedError. 

@jeffbolznv 
If you are not agree, please give me to know.

2023-07-10 13:53 UTC, spencer-lunarg commented
> test CANNOT cause this VUID

So for these types of things in the past we have used Device Profile API... honestly for the sake of getting this in... also we don't expect tests to be ran on EVERY device, just usually one

I am happy to get a test for `VUID-RuntimeSpirv-saturatingAccumulation-08983` after this PR, I rather not have this be blocking for this PR

2023-07-10 14:25 UTC, spencer-lunarg commented on tests/unit/shader_cooperative_matrix.cpp
> +    m_errorMonitor->SetAllowedFailureMsg("VUID-RuntimeSpirv-MSize-08975");
ok, fair, again for now I rather just get something in, can always be smoothed out in a follow up PR, but yes, as long as there is "a test" for "each VUID" that is the real important part

2023-07-10 14:28 UTC, archimedus commented
Thank you @spencer-lunarg for reviews.

> So for these types of things in the past we have used Device Profile API... honestly for the sake of getting this in...

I suppose I have seen something similar in CTS besides xgl and win32, there is null device. I was thinking is there something similar in VVL. Now I know there is :)

> I am happy to get a test for VUID-RuntimeSpirv-saturatingAccumulation-08983 after this PR, I rather not have this be blocking for this PR

It looks reasonable for me.

2023-07-12 01:28 UTC, spencer-lunarg approved these changes

2023-07-12 04:20 UTC, merged

2023-07-20 17:52 UTC, juan-lunarg commented on scripts/known_good.json
> +            "url": "https://github.com/archimedus/glslang.git",
This should have not been accepted until this was merged into `KhronosGroup/glslang`.

We will need to revert these changes.

2023-07-21 00:09 UTC, spencer-lunarg commented on scripts/known_good.json
> +            "url": "https://github.com/archimedus/glslang.git",
sorry @juan-lunarg , I missed this