android: Require CMake 3.21+ and ndk r24+
KhronosGroup/Vulkan-ValidationLayers pull request #6146
Opened 2023-07-14 19:13 UTC by juan-lunarg

Avoids legacy issues with older versions of these tools.

2023-07-14 21:16 UTC, lunarpapillo requested changes
These changes to `CMakeLists.txt` look great - clear, good commenting, good error messages.

Shouldn't there also be corresponding changes to the **Building On Android** section of `BUILD.md`?

2023-07-14 21:17 UTC, lunarpapillo commented on scripts/android.py
> -        cmake_cmd += ' -D CMAKE_ANDROID_RTTI=YES'
Just for my illumination... do you have any insights into why these two lines were there in the first place?

(Don't research it if you don't "just know" the answer - it's not that important.)

2023-07-14 21:18 UTC, juan-lunarg commented
> Shouldn't there also be corresponding changes to the **Building On Android** section of `BUILD.md`?

There will be. Currently BUILD.md still uses instructions for the ndk-build because that is what CI is using.

2023-07-14 21:20 UTC, juan-lunarg commented on scripts/android.py
> -        cmake_cmd += ' -D CMAKE_ANDROID_RTTI=YES'
CMAKE_ANDROID_RTTI was never needed as far as I can tell. I added it since it was in the CMake book for the sake of verbosity.

`CMAKE_ANDROID_EXCEPTIONS`  is buggy in the r23 NDK release. But now that we explicitly require a newer NDK we don't have to explicitly set it anymore.

2023-07-15 03:19 UTC, spencer-lunarg approved these changes

2023-07-17 16:02 UTC, merged