build: Redo API parameterization
KhronosGroup/Vulkan-ValidationLayers pull request #6150
Opened 2023-07-17 15:25 UTC by aqnuep

This re-does the API-specific parameterization needed to support downstream API variants like Vulkan SC after the generator script rewrites.

2023-07-17 15:37 UTC, spencer-lunarg commented on scripts/generate_source.py
> +        # IMPORTANT!
instead of just putting "important" and "don't remove" it would be more helpful to the future user to know why

Can we just label these as "for SC"

2023-07-17 15:47 UTC, aqnuep commented on scripts/generate_source.py
> +        # IMPORTANT!
I'd say this could have a wider impact, as it's a way to support Vulkan API variants in general, and some of these may apply to Vulkan too, going forward (in particular the solutions for the bypassed Vulkan registry dependency tools).

The reason I'm trying to very explicitly mark these from here on to not have to redo this effort a 3rd time.

2023-07-17 16:44 UTC, juan-lunarg commented on scripts/generate_source.py
> +        # IMPORTANT!
> a way to support Vulkan API variants in general

Is there going to be another Vulkan API variant?

2023-07-17 17:22 UTC, aqnuep commented on tests/framework/layer_validation_tests.cpp
> +// IMPORTANT! DO NOT REMOVE!
There's a common set of language I used in the comments for the different instances of the `APISpecific` utility class across the generator scripts.

If you could propose a change to those comments that you'd be happy with and that would still convey the key message that they and their use must be kept as is, unless otherwise agreed with downstream users, and shouldn't be merged back to the general parts of the generator script as part of refactoring, as it happened recently, then I'm happy to update the PR with it.

My goal, and why I used such strong words in these places, is to avoid accidental changes to these, as my previous attempt, even though I moved these pieces into their own variables and functions (which I naively thought should be sufficient), was thrown away as part of refactoring.

2023-07-17 18:41 UTC, aqnuep commented on scripts/generate_source.py
> +        # IMPORTANT!
That's not really what I said, but rather that there's nothing inherently Vulkan SC specific to the changes I'm upstreaming, but rather it's a set of injection points where a Vulkan variant like Vulkan SC can add its own specializations.

2023-07-18 00:11 UTC, spencer-lunarg commented on tests/framework/layer_validation_tests.cpp
> +// IMPORTANT! DO NOT REMOVE!
IMO, so test would be MUCH better at preventing regressions then a comment, as that actually tests the logic is not broken

I guess I would argue ALL code in the VVL is "Important" or else we really should get rid of it (same with `# DO NOT REMOVE THIS CHECK!`... makes it sound like everything else we could just remove)

A simple

```
// Keep for non-Vulkan API (ex. Vulkan SC)
```

is going to be way more useful to the future developer who is not currently reviewing this PR

2023-07-18 09:11 UTC, aqnuep commented on tests/framework/layer_validation_tests.cpp
> +// IMPORTANT! DO NOT REMOVE!
I've updated the comments.

Please merge this change if you're happy with it.

If we can agree offline to adding some sort of tests to prevent regressions, then I'll follow up with a PR for that ASAP.

2023-07-18 10:21 UTC, aqnuep commented
It looks like there's some general instability in one of the CI builds, as the same failure seems to appear after my comment-only updates in this PR, as in some of the latest main builds and in other PRs. Could you please rerun that manually, if possible?

2023-07-18 14:42 UTC, aqnuep commented
I've made some further minor changes, just to get everything out of the way, and also rebased now that I see that main was red only because of CI instabilities.

I'll also come back next week with a PR with a github actions proposal for testing the stability of the hooks.

2023-07-19 02:24 UTC, spencer-lunarg requested changes

2023-07-19 02:24 UTC, spencer-lunarg commented on scripts/generators/extension_helper_generator.py
> +    def getVersionFieldNameDict(targetApiName: str) -> dict[str, str]:
I REALLY REALLY wanted to move away from these "random small containers of data everywhere" as it had made maintainability a nightmare before by 1000 small cuts

I didn't like the fact we had this manually here to begin with... I realize this is either a chance for us to

1. Make things more complex again
2. Fix this properly at the source

I opt 10000% to do `2` and created a PR that should remove the need for these methods in this file (since `self.vk.versions` should be empty for SC)

https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6161

2023-07-19 02:24 UTC, spencer-lunarg commented on scripts/generators/extension_helper_generator.py
> +class APIVersion {
I think this class should not be generated, its should be pulled out into its own non-generated header things can include

2023-07-19 02:24 UTC, spencer-lunarg commented on scripts/generators/layer_chassis_generator.py
> +            case 'vulkan':
instead of having to do case statement on what is basically a C function written in a python string, would it be easier to have `void ValidationObject::InitObjectDispatchVectors() {` just call into a function that then could be `ifdef` out for SC?

2023-07-19 02:24 UTC, spencer-lunarg commented on scripts/generators/object_tracker_generator.py
> +                    'instance': 'VUID-vkDestroyInstance-instance-00629',
SC has different VUID?!?

2023-07-19 02:31 UTC, spencer-lunarg commented on scripts/generators/extension_helper_generator.py
> +class APIVersion {
or it would be easy to just generate it as it's own file, no reason I see it needs to live in this file, happy to do that if wanted

2023-07-19 07:44 UTC, aqnuep commented on scripts/generate_source.py
> +        if api != 'vulkan' and generators[target]['genCombined']:
Not really, if e.g. `api` is `vulkansc` and `genCombined` is `False`, then `apiList` must only contain `vulkansc`.

It's the other way, so maybe we can rewrite it like this:

```python
apiList = api

if api != 'vulkan' and generators[target]['genCombined']:
    SetMergedApiNames('vulkan')
    apiList.append('vulkan)
```

2023-07-19 07:50 UTC, aqnuep commented on scripts/generators/base_generator.py
> +        self.targetApiName = globalApiName
> to be honest, still not 100% why there is a apiname, mergeApiNames and defaultExtensions field in the reg.py generator options

They control completely different things:

  * `apiname` is the target API name to use
  * `mergeApiNames` allows merging other APIs into the target API, as used by Vulkan SC ecosystem components to merge also basic Vulkan API definitions with the SC ones to produce combined headers that enable ecosystem components like the VVL build, which obviously rely on all Vulkan definitions to be there
  * `defaultExtensions` allows specifying a filter for which extensions to include in the current spec/header/etc. build

All, except `mergeApiNames` have been always there in the registry tooling and they have their purpose. I think you'd need to talk with Jon if you don't know what some of the generator parameters mean (although they have documentation in their source).

I also don't see why that would be better. First of all, the code you listed here is about the `GeneratorOptions` class, but we need the target API in the `Generator` class.

What is exactly the problem with having a member variable for the target API? Why is that a problem in the first place?

2023-07-19 07:52 UTC, aqnuep commented on scripts/generators/base_generator.py
> -                nameString = f'"{name}"'
Yes, the purpose is to support API variant versions like `VKSC_VERSION_*`.

There is no `VKSC_VERSION_1_1` **yet**. But there's also a big difference between `VKSC_VERSION_1_0` and `VK_VERSION_1_0` in that Vulkan SC 1.0 includes almost all functionality of Vulkan 1.2, so it's not as trivial as you'd think.

Please don't worry about what's needed for SC specifically, that's something I'm taking care of.

2023-07-19 07:58 UTC, aqnuep commented on scripts/generators/extension_helper_generator.py
> +class APIVersion {
This has been there in the generator script, and wasn't factored out. So why now?

Also, over time this class will likely be partially auto-generated. I mean anywhere where a version number is used should really be auto-generated.

Sure, currently the generator scripts mostly hard-coded these, but that has been a bad practice anyway.

2023-07-19 08:01 UTC, aqnuep commented on scripts/generators/extension_helper_generator.py
> +    def getVersionFieldNameDict(targetApiName: str) -> dict[str, str]:
No `self.vk.versions` would not be empty for SC. You're making assumptions about SC here, but you really shouldn't.

Vulkan SC 1.0 requires Vulkan 1.0, Vulkan 1.1, and Vulkan 1.2 with some changes.

Now whether these variable names should be manually listed here (or hard-coded at source-level as they were before), is another question, but see my reply above.

2023-07-19 08:03 UTC, aqnuep commented on scripts/generators/layer_chassis_generator.py
> +            case 'vulkan':
We're not adding `#ifdef`'d code for SC upstream, because that was something LunarG explicitly didn't want.

We're not adding `#ifdef`'d code for SC downstream into files that come from upstream, because it's a guaranteed merge conflict and subject to refactoring breaking it.

What is really the problem for different API variants to generate different implementations of this function?

This was always generated upstream, I just made it so that downstream can customize it.

2023-07-19 08:03 UTC, aqnuep commented on scripts/generators/object_tracker_generator.py
> +                    'instance': 'VUID-vkDestroyInstance-instance-00629',
Yes.

2023-07-19 08:04 UTC, aqnuep commented on tests/framework/layer_validation_tests.cpp
> +#ifndef VVL_TESTS_USE_CUSTOM_TEST_FRAMEWORK
Why? This is literally less than 10 lines of effective code with no impact on VVL.

The reason for their existence is also explained in detail in the comments.

2023-07-19 08:26 UTC, spencer-lunarg commented on scripts/generate_source.py
> +        if api != 'vulkan' and generators[target]['genCombined']:
ok, happy with this, cleaner to read

2023-07-19 08:32 UTC, spencer-lunarg commented on scripts/generators/base_generator.py
> +        self.targetApiName = globalApiName
I want to move `base_generator.py` to be something the whole ecosystem uses, I left the `customApiName` only there for you, if you aren't going to use it, the code slowly just gets populated with random variables trying to solve the same problem

2023-07-19 08:36 UTC, spencer-lunarg commented on scripts/generators/extension_helper_generator.py
> +class APIVersion {
before we had the bad habits of merging multiple things into a single generator because the overhead of making a new one was so high (having to do all the `gen*()` calls and such)

I guess this was the logic moves from having 2 strings hardcoded, to just adjusting the `#include` statement

2023-07-19 08:45 UTC, aqnuep commented on scripts/generators/base_generator.py
> +        self.targetApiName = globalApiName
Why `customApiName` is needed in the first place? It's not custom API name, it's **the** API name, which may vary depending on the target API variant.

2023-07-19 15:32 UTC, aqnuep commented
CC @dgkoch.

@spencer-lunarg, in order to try to move this forward, can you please explain what is exactly so objectionable with having the `targetApiName` a member of the generator classes and with having dedicated `APISpecific` classes alongside the common generator code, which I separated out exactly to make it clear what may need to be API-specific vs what is common, as I think that is the number one contention about this PR.

Regarding the API version specific customizations, as we discussed offline, the main reason why those need customization, because the dependencies between versions (`<feature>` tags) is not linear, as it is assumed in some of the suggestions, because Vulkan SC, for example, has `VKSC_VERSION_1_0` depend on `VK_VERSION_1_2`.

2023-07-19 15:51 UTC, ncesario-lunarg commented on tests/framework/layer_validation_tests.cpp
> +#ifndef VVL_TESTS_USE_CUSTOM_TEST_FRAMEWORK
So the usage here is that a "vulkan offshoot" like SC defines `VVL_TESTS_USE_CUSTOM_TEST_FRAMEWORK`, and then adds their own framework file(s) in cmake? If so, I would vote for a cmake change along the lines of the following. I'm guessing @juan-lunarg has better ideas, though.
```diff
diff --git a/tests/CMakeLists.txt b/tests/CMakeLists.txt
index 92166d549..959d97614 100644
--- a/tests/CMakeLists.txt
+++ b/tests/CMakeLists.txt
@@ -21,8 +21,6 @@ else()
 endif()
 target_sources(vk_layer_validation_tests PRIVATE
     framework/android_hardware_buffer.h
-    framework/layer_validation_tests.h
-    framework/layer_validation_tests.cpp
     framework/test_common.h
     framework/shader_templates.h
     framework/error_monitor.cpp
@@ -144,6 +142,17 @@ target_sources(vk_layer_validation_tests PRIVATE
     unit/ycbcr_positive.cpp
     containers/small_vector.cpp
 )
+if ("${API_TYPE}" STREQUAL "vulkan")
+    target_sources(vk_layer_validation_tests PRIVATE
+        framework/layer_validation_tests.h
+        framework/layer_validation_tests.cpp
+    )
+elseif("${API_STYLE}" STREQUAL "vulkansc")
+    target_sources(vk_layer_validation_tests PRIVATE
+        framework/layer_validation_tests_sc.h
+        framework/layer_validation_tests_sc.cpp
+    )
+endif()
 get_target_property(TEST_SOURCES vk_layer_validation_tests SOURCES)
 source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}" FILES ${TEST_SOURCES})
```

2023-07-19 15:51 UTC, ncesario-lunarg commented on tests/framework/layer_validation_tests.cpp
> +#ifndef VVL_TESTS_USE_CUSTOM_TEST_FRAMEWORK
I _think_ you can call `target_sources` multiple times for a single target, but not 100% sure.

2023-07-19 15:56 UTC, ncesario-lunarg commented on scripts/generators/base_generator.py
> +            case 'vulkan':
How do downstream vulkan variants utilize this? Do they modify this file, adding cases here?

2023-07-19 16:11 UTC, ncesario-lunarg commented on scripts/generators/enum_flag_bits_generator.py
> +class APISpecific:
@aqnuep do you have downstream SC VVL changes that utilize these changes? I'm curious how downstream variants are meant to consume this. If it's modifying _this_ class in _this_ file, that seems problematic. There are a number of possible approaches, like passing in a different _instance_ of this class when the generator is created in `generate_source.py` based on the api type, that I would personally prefer, but I'm probably missing a larger part of the picture here.

@spencer-lunarg
> Also I would like the make the assumption we will only have 1 non-Vulkan API downstream, so it will either be vulkan or not

I would like to make that assumption, too, but I also would have liked to assume there was just Vulkan...but here we are :) Since we have to add the plumbing for SC, might as well make it flexible enough to handle other variants "just in case."

2023-07-19 16:12 UTC, aqnuep commented on scripts/generate_source.py
> +        if api != 'vulkan' and generators[target]['genCombined']:
I've redid this, but it had to look as follows:

```python
        apiList = [api]
        if api != 'vulkan' and generators[target]['genCombined']:
            SetMergedApiNames('vulkan')
            apiList.append('vulkan')
        else:
            SetMergedApiNames(None)
```

The `SetMergedApiNames(None)` call was necessary because I followed the design you established with these global variables, and unless you actually call the function the global won't be defined.

2023-07-19 16:19 UTC, aqnuep commented on tests/framework/layer_validation_tests.cpp
> +#ifndef VVL_TESTS_USE_CUSTOM_TEST_FRAMEWORK
The problem is that `layer_validation_tests.h` and `layer_validation_tests.cpp` contains 100 different, unrelated things (got worse since the recent refactoring with the dozens of new subclasses of `VkLayerTest`).

So replacing the entire header and source would require forking those files and keeping them in sync, which is a maintenance nightmare.

The only thing we need is to be able to change the base class of `VkLayerTest`, which is exactly the change tries to achieve. Nothing more, nothing less.

Of course, if things would be better structured, or if the test framework would support dependency injection or dependency inversion, then things could be done differently too, but that would require very intrusive and time consuming refactoring of the entire test framework of VVL.

In contrast, I tried to propose the minimal sufficient changes in order for us to make things work downstream, which is after all the goal we agreed to.

2023-07-19 16:22 UTC, ncesario-lunarg commented on scripts/generators/extension_helper_generator.py
> +class APIVersion {
Also for context: https://gitlab.khronos.org/vulkan/Vulkan-ValidationLayers/-/merge_requests/91#note_411319

2023-07-19 16:36 UTC, aqnuep commented on tests/framework/layer_validation_tests.cpp
> +#ifndef VVL_TESTS_USE_CUSTOM_TEST_FRAMEWORK
But, to be fair, if these `#ifdef`s are not accepted, I'll just write a script downstream to generate a patched versions of these files.

Regarding the cmake changes, we're not using the upstream cmake file for the tests at all, as we run our own version due to having very different needs on that front.

2023-07-19 16:43 UTC, ncesario-lunarg commented on tests/framework/layer_validation_tests.h
> +#include <condition_variable>
Used?

2023-07-19 16:46 UTC, aqnuep commented on scripts/generators/enum_flag_bits_generator.py
> +class APISpecific:
But then we'd have to run our own copy of `generate_source.py`, and it's the same issue like with `layer_validation_tests.*`.

Also, if you look at the other generator files, it's not always the case that SC needs to **add** something in addition, but rather **replace** something. In fact this is the only exception where it's just about adding something.

This is exactly the reason why the recent refactoring "broke" downstream, as it moved around, inlined, or otherwise removed the places that downstream could inject its own version to.

There simply have to be hooks for which there exists a default Vulkan implementation and downstream users can provide their own custom implementation.

2023-07-19 16:46 UTC, ncesario-lunarg commented on tests/framework/layer_validation_tests.cpp
> +#ifndef VVL_TESTS_USE_CUSTOM_TEST_FRAMEWORK
Fair enough. The portion of code guarded in the ifdef is quite small, and looking at it a bit more I would agree this is probably the best approach without more intrusive changes as you pointed out.

2023-07-19 16:49 UTC, aqnuep commented on tests/framework/layer_validation_tests.h
> +#include <condition_variable>
Yes, condition variables are used in your upstream code, and actually upstream currently fails to build with some compilers due to the missing include.

2023-07-19 17:35 UTC, juan-lunarg commented on tests/framework/layer_validation_tests.cpp
> +#ifndef VVL_TESTS_USE_CUSTOM_TEST_FRAMEWORK
> But, to be fair, if these #ifdefs are not accepted, I'll just write a script downstream to generate a patched versions of these files.

I'd prefer that solution.

2023-07-19 17:36 UTC, juan-lunarg commented on tests/framework/layer_validation_tests.h
> +#include <condition_variable>
What compilers? Could we add it to our github actions testing?

2023-07-19 17:44 UTC, juan-lunarg commented on CMakeLists.txt
> +# variant (e.g. Vulkan SC)
nitpick: make this a 1 line comment

2023-07-19 17:44 UTC, juan-lunarg commented on layers/CMakeLists.txt
> +# This variable enables downstream users to customize the CMake targets
nitpick: make this a 1 line comment

2023-07-19 17:44 UTC, juan-lunarg commented on scripts/CMakeLists.txt
> +    list(APPEND update_dep_command "${API_TYPE}")
👍🏾

2023-07-19 18:20 UTC, aqnuep commented on tests/framework/layer_validation_tests.cpp
> +#ifndef VVL_TESTS_USE_CUSTOM_TEST_FRAMEWORK
> I'd prefer that solution.

Fair enough, and I'm okay with that (probably wouldn't need a script either, as I could just modify the file in-place downstream, conflicts or breakage would still happen at the same rate).

It does make downstream's life more difficult by being more susceptible to conflicting changes, and I'm sure @dgkoch won't be happy about it, but these small pieces are the least of my concern.

2023-07-19 18:22 UTC, aqnuep commented on tests/framework/layer_validation_tests.h
> +#include <condition_variable>
I wish I would recall (it's been a few months now since I've added this), but I got an error of `std::conditional_variable` not being defined on one of them, as this file uses conditional variables and never included its header. It just so happens that most STL implementations implicitly include a lot of things in many headers, so it doesn't fail everywhere.

2023-07-19 18:43 UTC, dgkoch commented on scripts/generators/object_tracker_generator.py
> +                    'instance': 'VUID-vkDestroyInstance-instance-00629',
(in some cases - we re-use as much as possible).

2023-07-19 18:54 UTC, dgkoch commented on scripts/generators/enum_flag_bits_generator.py
> +class APISpecific:
Could it be acceptable if we put some of the `vulkansc` labels and minimal script logic into the upstream repository? 
Then it might be clearer why things are structured the way they are, that might otherwise look silly when there's only one case statement.

2023-07-19 21:45 UTC, KarenGhavam-lunarG commented on scripts/generators/enum_flag_bits_generator.py
> +class APISpecific:
> Could it be acceptable if we put some of the vulkansc labels and minimal script logic into the upstream repository?
Then it might be clearer why things are structured the way they are, that might otherwise look silly when there's only one case statement.

Aren't we doing a fork to avoid having SC specific content in VVL?

2023-07-20 01:01 UTC, dgkoch commented on scripts/generators/enum_flag_bits_generator.py
> +class APISpecific:
If the compliant is that these changes look pointless on their own, and someone might want to "clean them up" - the best way to give them a point is to make it more obvious what the hooks are for, and having a few Vulkan SC switches or branches shouldn't be an onerous ask. We AREN'T asking to land the whole VKSC VVL code here, just identifiers of places that are important for downstream consumers.

2023-07-20 01:22 UTC, spencer-lunarg commented
> @spencer-lunarg, in order to try to move this forward

sorry, spending a night thinking about this, these `APISpecific` right now are fine, what I don't understand is the future process to make any change to our scripts now

Ex. #6161 and #6162  are both valid changes we could want to make (with having to insight in SC's downstream). If we merge this PR, and then i want to make those changes, what is the process to do that? I want to be able to make changes in the future to these scripts, but if it involves needing to break an area where a `APISpecific` function is, how do we go about this?

2023-07-20 01:23 UTC, spencer-lunarg commented on scripts/generators/base_generator.py
> +        self.targetApiName = globalApiName
> Why customApiName is needed in the first place? 

I thought you might use it. It can be removed later if no one ends up using it

2023-07-20 01:28 UTC, spencer-lunarg commented on scripts/generators/extension_helper_generator.py
> +    def getVersionFieldNameDict(targetApiName: str) -> dict[str, str]:
> You're making assumptions about SC here, but you really shouldn't.

sorry, I was unaware the whole concept of a "version" I had is now broken because of SC.

I finally understand what you mean about the `<features>` not being linear, but the fact SC 1.0 is not "core" like Vulkan 1.0 is now just-yet-another-quirk that will need to be accounted for

... it was it is, will just note it now and move on

2023-07-20 01:29 UTC, spencer-lunarg commented on scripts/generators/object_tracker_generator.py
> +                    'instance': 'VUID-vkDestroyInstance-instance-00629',
ok, noted

2023-07-20 01:34 UTC, spencer-lunarg commented on tests/framework/layer_validation_tests.cpp
> +#ifndef VVL_TESTS_USE_CUSTOM_TEST_FRAMEWORK
the reason I wanted a different PR was the tests framework has its own issues compared to the scripts (not a fan how `layer_validation_tests` has become such a garbage bin of stuff, but not the time to clean it up)

2023-07-20 02:04 UTC, spencer-lunarg approved these changes
@aqnuep @dgkoch I was unaware by the time constraints you had for SC, I think there is a LOT to be figured out for how we move forward making changes, but these **can** be addressed after

I am going to merge this to allow Rakos life to be easier, but I still intend to figure out post PR to come up with a more long term sustainable way to do this

2023-07-20 02:06 UTC, merged

2023-07-20 02:07 UTC, spencer-lunarg commented on CMakeLists.txt
> +# variant (e.g. Vulkan SC)
can be cleaned up after

2023-07-20 07:42 UTC, aqnuep commented
> > @spencer-lunarg, in order to try to move this forward
> 
> sorry, spending a night thinking about this, these `APISpecific` right now are fine, what I don't understand is the future process to make any change to our scripts now
> 
> Ex. #6161 and #6162 are both valid changes we could want to make (with having no insight in SC's downstream). If we merge this PR, and then i want to make those changes, what is the process to do that?
> 
> I'm happy to now know that these area will cause issues for you, but I want to be able to make changes in the future to these scripts, but if it involves needing to break an area where a `APISpecific` function is, how do we go about this?

@spencer-lunarg, if you need to refactor code, like moving the APIVersion class to its own header and generator, that should be fine, as long as you still keep the portions of the code that are marked as API specific under a similar `APISpecific` function.

Sure, it would cause a conflict when we downstream in the next round, but one that's trivially resolvable by finding where that interface moved.

The main problem with the refactoring that happened recently is that it remerged code or strings that were intentionally separated into separate python methods or variables, and that's what we really should be avoiding.

Also, I can imagine another corner case, when the code or data generated by one of the `APISpecific` functions would need to be split out or otherwise refactored. That could be fine too, if the interface would be kept around and call the new sub-pieces.

If none of these options would work I think it's still fine to refactor if given a heads-up about the change.

The important part really would be to not have to reverse engineer where and how things were changed when it comes to these API-specific interfaces and the reason I tried to separate them out this time around so that there's a clean distinction between the common and API-specific pieces.