tests: Portability fixes
KhronosGroup/Vulkan-ValidationLayers pull request #6151
Opened 2023-07-17 16:46 UTC by richard-lunarg

Just a couple of tests fixed to account for macOS platform and the portability extension.

2023-07-17 16:50 UTC, juan-lunarg commented on tests/unit/command_positive.cpp
> +        }
Fix brackets. I know this code technically works but I had to do a double take because the formatting is awkward.

```suggestion
        if(portability_features.imageView2DOn3DImage == VK_FALSE) {
            GTEST_SKIP() << "Required feature 'imageView2DOn3DImage' not supported by portability extension.";
        }
    }
```

2023-07-17 17:02 UTC, richard-lunarg commented on tests/unit/command_positive.cpp
> +        }
Done.

2023-07-17 20:14 UTC, juan-lunarg requested changes
Please squash and rebase your 3 commits into 1 commit

2023-07-18 01:34 UTC, spencer-lunarg commented on tests/unit/other_positive.cpp
> -    dev_info.enabledExtensionCount = 0;
just leave `dev_info.enabledExtensionCount = device_extensions.size();` here and if no portability, it will be `0`

2023-11-15 16:13 UTC, closed without merging