scripts: restore the -o option on generate_source
KhronosGroup/Vulkan-ValidationLayers pull request #6165
Opened 2023-07-19 14:29 UTC by Keenuts

The old script had a way to specify a custom output directory for generated files. The recent refactoring removed this option, preventing us to build this.

2023-07-19 14:30 UTC, spencer-lunarg approved these changes

2023-07-19 17:54 UTC, juan-lunarg requested changes

2023-07-19 17:54 UTC, juan-lunarg commented on scripts/generate_source.py
> +      gen_dir = args.output_directory;
> The old script had a way to specify a custom output directory for generated files. The recent refactoring removed this option, preventing us to build this.

Who/what did we break exactly? I'd like that to be commented at least.

2023-07-20 12:38 UTC, Keenuts commented on scripts/generate_source.py
> +      gen_dir = args.output_directory;
Reworded the commit message to explain that.
This is useful when your build-system does the following:
 - source code is read-only
 - generated files are written to a writable intermediate folder
 - then, code is compiled, using those intermediates.
 
Also, before this refactoring, we were able to generate each file individually using the fine-grained python script. This means the build-system is responsible from parallelization. Now, we can only call this, and not parallelize this file generation step easily.

Another note: this script calls another python script using subprocess.check_call. This assumes the machine can run python scripts as-is. What if we require python scripts to be bundled first to run in an hermetic env?
(Also, same issue with the output directory)

2023-07-20 15:22 UTC, spencer-lunarg commented on scripts/generate_source.py
> +      gen_dir = args.output_directory;
>  we were able to generate each file individually using the fine-grained python script

you can in theory run `generate_source.py --target file_name` to do one file at a time

... but honestly, I would want to make parallelize generation the default, not something that is added afterwards

> this script calls another python script using subprocess.check_call

so before, ALL files were being called with `check_call`, now only the `vk_validation_stats.py` file is being called with it (it generates the `vk_validation_error_messages.h` and something that **can** be cleaned up in the future as well) ... so not sure why this is a problem now

2023-07-20 15:52 UTC, Keenuts commented on scripts/generate_source.py
> +      gen_dir = args.output_directory;
Thanks for the answer!

> you can in theory run `generate_source.py --target file_name` to do one file at a time
Oh, missed this one, thanks, that will be handy!


> so before, ALL files were being called with `check_call`
It was? I must have missed that in the old `run_generator.py` file (we called this one directly)

But those are 2 other problems, we stil remain with the issue that we cannot write in the repo directory, hence need a way to say "go output the files there", which was the output option.

2023-07-20 16:08 UTC, juan-lunarg approved these changes

2023-07-20 16:57 UTC, Keenuts commented
thanks for the review! force-pushed to rebase

2023-07-20 18:31 UTC, merged