cmake: Add utility libraries repository dependence
KhronosGroup/Vulkan-ValidationLayers pull request #6243
Opened 2023-08-02 13:05 UTC by christophe-lunarg

Splitting https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6088, the PR being too big and hard to resolve cause of test failure

2023-08-03 15:43 UTC, jeremyg-lunarg approved these changes
LGTM

2023-08-03 15:44 UTC, artem-lunarg commented on layers/CMakeLists.txt
>  # Order matters here. VkLayer_utils should be the last link library to ensure mimalloc overrides are picked up correctly.
> **Order matters here. VkLayer_utils should be the last link library to ensure mimalloc overrides are picked up correctly.**

2023-08-03 15:48 UTC, artem-lunarg commented on scripts/known_good.json
> +            "deps": [
I don't know much how know_good works. Why do we have `deps` here but don't specify dependencies in other sections?

2023-08-03 15:56 UTC, jeremyg-lunarg commented on layers/CMakeLists.txt
> +target_link_libraries(vvl PRIVATE VVL-SPIRV-LIBS VkLayer_utils Vulkan::LayerSettings)
doh! very good point!

2023-08-03 15:57 UTC, jeremyg-lunarg requested changes
@artem-lunarg 's comment about ordering needs to be addressed.

2023-08-03 16:08 UTC, christophe-lunarg commented on layers/CMakeLists.txt
> +target_link_libraries(vvl PRIVATE VVL-SPIRV-LIBS VkLayer_utils Vulkan::LayerSettings)
Fixed

2023-08-03 16:14 UTC, artem-lunarg commented on scripts/known_good.json
> +            "deps": [
Okay, sounds good.

I'll ping @juan-lunarg here. It would be nice to get comment later. I see that in the profiles repository we use `deps` in a few places but did not use in vvl before.

2023-08-03 16:15 UTC, artem-lunarg approved these changes

2023-08-03 16:18 UTC, jeremyg-lunarg approved these changes

2023-08-04 05:50 UTC, spencer-lunarg approved these changes

2023-08-04 05:51 UTC, merged

2023-08-14 17:22 UTC, juan-lunarg commented on scripts/known_good.json
> +            "deps": [
By specifying VULKAN_HEADERS_INSTALL_DIR the utility libraries will use the headers from VVL instead of it's own. That's the intent at least.

IE this situation arises due to shared dependencies which isn't an issue with other repos we consume.