Using VK_EXT_layer_settings  from the layer settings lib
KhronosGroup/Vulkan-ValidationLayers pull request #6245
Opened 2023-08-02 15:35 UTC by christophe-lunarg

Use layer settings library, replacing VK_EXT_layer_settings from the validation layer by the version from the layer settings library, shared across layers.

2023-08-21 16:13 UTC, juan-lunarg commented
I'd very much like this issue to be addressed first:
https://github.com/KhronosGroup/Vulkan-Utility-Libraries/issues/13

It should fix the dependency issue we have been having.

2023-08-22 16:28 UTC, charles-lunarg commented on layers/layer_options.cpp
> +    const std::string& string_enables = Merge(enables);
This looks very suspicious - Merge returns a value, but then we store it as a reference, does this dangle the string?

2023-08-22 16:59 UTC, juan-lunarg commented on layers/layer_options.cpp
> +    const std::string& string_enables = Merge(enables);
Agreed the code looks problematic.

2023-08-22 17:12 UTC, artem-lunarg commented on layers/layer_options.cpp
> +    const std::string& string_enables = Merge(enables);
That's fine according to c++ rules, lifetime of rvalues is extended if they are assigned to `const ref`. The problem here that this code looks like optimization but in fact can be slower (or maybe the same speed). According to `Merge` implementation compiler might do RVO or if it can then IIRC it **must** to use move constructor. RVO is likely so result can be put into result variable without copying. And if `const ref` it can be additional copy to store somewhere temp object so you can assign const ref to.

2023-08-22 17:33 UTC, juan-lunarg commented on layers/layer_options.cpp
> +    const std::string& string_enables = Merge(enables);
Gotcha. Although the code is legal I'd rather `string_enables` just be a `const std::string`. I'd rather initialization code be as simple as possible.

2023-08-22 18:52 UTC, juan-lunarg requested changes
https://github.com/KhronosGroup/Vulkan-Utility-Libraries/issues/13

I'd like this issue to be fixed before we merge this change. Avoiding the circular dependency. FYI @charles-lunarg

2023-08-22 18:52 UTC, juan-lunarg commented on scripts/known_good.json
> +            "name": "Vulkan-Utility-Libraries",
Note we will want to document this new dependency somewhere for system package managers when this PR gets merged in.

Otherwise they will get build errors and make issues. Not sure where the best place for that would be.

2023-08-22 18:52 UTC, juan-lunarg commented on tests/framework/test_framework.h
> +std::string format(const char *message, ...);
Given this helper function is only used in `others.cpp` please move the function to `others.cpp` It doesn't need to be in test_framework.h

2023-08-22 18:52 UTC, juan-lunarg commented on tests/framework/layer_validation_tests.h
> +#define OBJECT_LAYER_NAME "VK_LAYER_KHRONOS_validation"
Can't the test code just include `layer_options.h`?

2023-08-22 18:52 UTC, juan-lunarg commented on layers/layer_options.h
> +#define OBJECT_LAYER_NAME "VK_LAYER_KHRONOS_validation"
Avoid macros.

```suggestion
inline const char * GetObjectLayerName() { return "VK_LAYER_KHRONOS_validation"; }
```

2023-08-22 18:52 UTC, juan-lunarg commented on tests/framework/layer_validation_tests.cpp
> +    std::vector<VkLayerSettingEXT> settings{
I don't see a need for std::vector. There is only 1 `VkLayerSettingEXT`.

2023-08-22 18:52 UTC, juan-lunarg commented on tests/unit/best_practices.cpp
> +            OBJECT_LAYER_NAME, "enables",
I don't see a need for std::vector. There is only 1 VkLayerSettingEXT.

2023-08-22 18:52 UTC, juan-lunarg commented on tests/unit/others.cpp
Please write 2 positives tests that enables all the validation layer functionality using the new programmatic interface. Just creating a device with a command buffer is good enough. Nothing too complex.

- Best practice + synchronization + gpuav
- Best practice + synchronization + debug printf

This is something developers will try to do with the new programmatic interface.

And given that `debug Printf` functionality and `GPU-Assisted validation` cannot be run at the same time. We should have a negative test that produces a clear error message to the user as well. (I don't believe we have a test for this AFAIK).

2023-08-23 14:27 UTC, christophe-lunarg commented on layers/layer_options.cpp
> +    const std::string& string_enables = Merge(enables);
https://herbsutter.com/2008/01/01/gotw-88-a-candidate-for-the-most-important-const/

2023-08-23 16:05 UTC, christophe-lunarg commented on tests/unit/best_practices.cpp
> +            OBJECT_LAYER_NAME, "enables",
Done

2023-08-23 17:46 UTC, juan-lunarg commented on scripts/known_good.json
> +            "name": "Vulkan-Utility-Libraries",
I'll just make an issue once this gets in.

2023-08-23 21:57 UTC, juan-lunarg commented
@charles-lunarg has a WIP PR to fix the circular dependency issue.

https://github.com/KhronosGroup/Vulkan-Profiles/pull/487

2023-08-24 15:45 UTC, christophe-lunarg commented on layers/layer_options.h
> +#define OBJECT_LAYER_NAME "VK_LAYER_KHRONOS_validation"
I do find this pointless but I changed this.

2023-08-25 19:27 UTC, juan-lunarg commented
Circular dependency has been fixed. Please see updates to Vulkan-Profiles and the utility libraries.

2023-08-28 16:16 UTC, juan-lunarg commented on tests/unit/others.cpp
Feel free to ignore the `GetLayerName` suggestion. I didn't consider that aspect.

2023-08-28 16:19 UTC, juan-lunarg approved these changes

2023-08-29 10:13 UTC, christophe-lunarg commented on tests/unit/others.cpp
Ok!

2023-08-29 14:21 UTC, merged