layers: Pass pNext from vkCreatImage to dispatch
KhronosGroup/Vulkan-ValidationLayers pull request #6258
Opened 2023-08-04 03:39 UTC by spencer-lunarg

This "solves" https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6256 ... but I really hate how this code looks

We probably need a more elegant solution for the future as other calls might need this

The goal is to take a copy of the `pNext` structs from the incoming call that might be needed when making `DisaptchvkGetPhysicalDevice*` queries

2023-08-04 07:32 UTC, arno-lunarg commented on layers/core_checks/cc_image.cpp
> +            pNext_end->pNext = reinterpret_cast<VkBaseInStructure *>(&image_format_list);
When landing on this line, `pNext_end` can be null, so `pNext_end->pNext` is not valid

2023-08-04 07:35 UTC, arno-lunarg requested changes
I think the way the pNext chain is managed has some issues

2023-08-07 00:26 UTC, spencer-lunarg commented on layers/core_checks/cc_image.cpp
> +            pNext_end->pNext = reinterpret_cast<VkBaseInStructure *>(&image_format_list);
I decided to solve the short term problem and pass in `VkImageFormatListCreateInfo` to unblock Mesa, a follow up can be added to provide proper support to all `Dispatch` calls (not just here)

2023-08-07 07:26 UTC, arno-lunarg approved these changes

2023-08-07 07:46 UTC, merged