layers: Workaround sync valdation of descriptor arrays
KhronosGroup/Vulkan-ValidationLayers pull request #6605
Opened 2023-10-03 12:56 UTC by artem-lunarg

2023-10-03 17:46 UTC, jzulauf-lunarg requested changes
Too broad, effectively eliminates all syncval for descriptor based accesses -- and only stops validation, not record...  see the other instance of `for (const auto &variable : stage_state.entrypoint->resource_interface_variables)` ...

Any eventual fix will have to match in both `CommandBufferAccessContext::ValidateDispatchDrawDescriptorSet` and `CommandBufferAccessContext::RecordDispatchDrawDescriptorSet`

2023-10-03 17:46 UTC, jzulauf-lunarg commented on layers/sync/sync_validation.cpp
> +            // Currently, validation of memory accesses based on declared descriptors can produce false-positives.
This disables *all* descriptor access validation... needs to be more narrowly defined for the specific false positive cases affecting users.

2023-10-03 17:56 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +            // Currently, validation of memory accesses based on declared descriptors can produce false-positives.
Isn't this a specific case? Any descriptor array can produce false-positives, and that's a typical case for modern graphical apps that increasingly use more descriptor indexing. My impression that keeping this makes syncval unusable for most big engines, and the proper solution should be gpu-av framework when it's ready.

2023-10-03 18:03 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +            // Currently, validation of memory accesses based on declared descriptors can produce false-positives.
> and only stops validation, not record

I was trying to skip in record function, and then validation automatically does not have this access. Is `RecordDispatchDrawDescriptorSet` a wrong place to change?

2023-10-03 18:17 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +            // Currently, validation of memory accesses based on declared descriptors can produce false-positives.
ah, I see. I saw both places but decided it's enough to skip update. I agree, validation should also do the same.

2023-10-07 10:09 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +            // Currently, validation of memory accesses based on declared descriptors can produce false-positives.
Fixed to have check both in Record and Validate.

> Too broad, effectively eliminates all syncval for descriptor based accesses 

It does not eliminate *all* validation. We still validate a single descriptor. We can not validate array because the code assumes that every access propagates to all elements but the shader is not required to access all array elements. 

That to some degree if true even for a single descriptor but that's part is kept for now: the code's assumption about arrays is more often than not is false in practice, but with a single descriptor it's often true the shader accesses declared single descriptor, so at least it's different category of probabilities.

2023-10-07 11:48 UTC, martin-ejdestig commented on layers/sync/sync_validation.cpp
> +            // Currently, validation of memory accesses based on declared descriptors can produce false-positives.
If disabling checking on all arrays is not wanted, could it perhaps be limited to bindings with `VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT`and `VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT` ?

(Not sure it is a good idea. I have only implemented bindless for textures in my engine at the moment, and do not really know what other engines do. But I assume most bindless "designs" have those flags set. I also really have no idea how the validation layer works here. Just a thought.)

2023-10-10 15:11 UTC, artem-lunarg commented
@jzulauf-lunarg Updated implementation to narrow scope to runtime  descriptor arrays (`OpCapability RuntimeDescriptorArray`).

2023-10-17 14:25 UTC, jzulauf-lunarg approved these changes
LGTM

2023-10-17 15:12 UTC, artem-lunarg commented on layers/sync/sync_validation.cpp
> +        const bool has_runtime_descriptor_array_capability =
Updated code to cache runtime array capability.

2023-10-17 15:15 UTC, jzulauf-lunarg approved these changes
LGTM

2023-10-17 15:15 UTC, jzulauf-lunarg commented on layers/state_tracker/shader_module.cpp
> +                    has_capability_runtime_descriptor_array = true;
👍

2023-10-17 17:23 UTC, jeremyg-lunarg approved these changes

2023-10-17 17:24 UTC, merged