tests: Add support to Mock AHB
KhronosGroup/Vulkan-ValidationLayers pull request #6658
Opened 2023-10-08 02:02 UTC by spencer-lunarg

Problem: No way to test `VK_ANDROID_external_format_resolve` (or `VK_ANDROID_external_memory_android_hardware_buffer`) with out an Android device that supports it (even then it is not fun). This means no coverage is done in Github CI and development is hard

Solution: Add a "Mock AHB" so we can simulate the Android Hardware Buffer to allow the tests to run on local desktop devices

This change

- Adds a bunch headers to allow things to compile
- CI job to test `--gtest_filter=*AndroidHardwareBuffer*` tests
- CMake support for this with a `-DVVL_MOCK_ANDROID=ON` flag to toggle it on

2023-10-08 02:03 UTC, spencer-lunarg commented on layers/CMakeLists.txt
> +    target_include_directories(VkLayer_utils SYSTEM PUBLIC ../tests/android/mock)
@juan-lunarg is there a better way to do this then `../`?

2023-10-08 02:04 UTC, spencer-lunarg commented on tests/device_profiles/max_profile.json
> +                "VK_FORMAT_UNDEFINED": {
when using external formats, you pass in `VK_FORMAT_UNDEFINED`

2023-10-08 02:04 UTC, spencer-lunarg commented on tests/framework/layer_validation_tests.cpp
> +#if defined(VK_USE_PLATFORM_ANDROID_KHR) && !defined(VVL_MOCK_ANDROID)
we don't need to build the APK `main` for tests as we are using the "standard desktop" gtest still

2023-10-09 17:05 UTC, juan-lunarg requested changes
Mainly just feedback on how to cleanup the CMake

2023-10-09 17:05 UTC, juan-lunarg commented on tests/android/CMakeLists.txt
Example how you could move all the `VVL_MOCK_ANDROID` CMake logic in here. Which would be much better IMO.

```
# More details in tests/android/mock
option(VVL_MOCK_ANDROID "Enable building for Android on desktop for testing with MockICD setup")

if (VVL_MOCK_ANDROID)
    target_sources(VkLayer_utils PRIVATE mock/android/hardware_buffer.cpp)
    target_compile_definitions(VkLayer_utils PUBLIC VK_USE_PLATFORM_ANDROID_KHR VVL_MOCK_ANDROID __ANDROID__)
    target_include_directories(VkLayer_utils SYSTEM PUBLIC ../tests/android/mock)
endif()
```

2023-10-09 17:06 UTC, juan-lunarg commented on tests/android/CMakeLists.txt
NOTE: The use of PUBLIC with `VkLayer_utils`. Since everything links against `VkLayer_utils` everything will be propagated properly.

2023-10-09 17:20 UTC, juan-lunarg commented on tests/unit/android_hardware_buffer.cpp
> +        m_errorMonitor->SetUnexpectedError("VUID-vkAllocateMemory-pAllocateInfo-01714");  // incase at last index
gotcha

2023-10-09 17:23 UTC, spencer-lunarg commented on tests/android/CMakeLists.txt
yep, this works much cleaner having the `VVL_MOCK_ANDROID` all together and not scatter all around

2023-10-09 17:24 UTC, juan-lunarg commented on layers/CMakeLists.txt
> +endif()
This code can be moved to `tests/android/CMakeLists.txt` instead.

Which IMO is better since this code is only relevant for testing.

2023-10-09 17:46 UTC, spencer-lunarg commented on layers/CMakeLists.txt
> +endif()
moved to `tests/CMakelist.txt` (added comment why we don't plan to build the APK so it shouldn't be in the `tests/android/CMakeLists.txt`

2023-10-09 17:49 UTC, juan-lunarg commented on tests/android/CMakeLists.txt
> +    # nodelete : Marks that vvl shouldn't be unloaded at runtime.
Revert change here.

2023-10-09 17:49 UTC, juan-lunarg commented on tests/CMakeLists.txt
> +
Revert change here.

2023-10-09 18:47 UTC, juan-lunarg approved these changes

2023-10-09 23:48 UTC, arno-lunarg approved these changes

2023-10-10 01:17 UTC, merged