test: Replace usage of ASSERT_VK_SUCCESS
KhronosGroup/Vulkan-ValidationLayers pull request #6676
Opened 2023-10-11 21:47 UTC by charles-lunarg

Replaced with `ASSERT_EQ(VK_SUCCESS, ...);` and added the necessary logic to allow gtest to pretty-print VkResult values.

This allows every place where VkResult is compared to inside of a gtest macro to get pretty-printing, instead of just ASSERT_VK_SUCCESS.

2023-10-11 22:45 UTC, jeremyg-lunarg approved these changes
LGTM

2023-10-11 23:25 UTC, spencer-lunarg requested changes
So I have talked a lot about this with @artem-lunarg 

I honestly think most of these `ASSERT` are useless and should just be removed

We use to have these mainly because we didn't default to each test needing to not have any errors, so there were cases where we had a invalid `VkCreateImage` that trigger another validation, but was not seen

if it doesn't return VK_SUCCESS but has **not** Validation error that notifies you means

1. Your driver has a bug
2. We are missing some validation case (which I feel almost never happens now with testing since our coverage is higher).... also MockICD always returns success 
3. The call has another "successful" return which is when I would justify this

so instead of having a random subset of `vkCreateImage` check, I argue it should just be removed unless one ACTUALLY cares about the error code, which 99% of these don't

2023-10-12 01:39 UTC, spencer-lunarg commented on tests/unit/debug_printf.cpp
> -    ASSERT_VK_SUCCESS(vi.CreateGraphicsPipeline(false));
this could just be asserted inside `CreateGraphicsPipeline`

2023-10-12 01:42 UTC, spencer-lunarg commented on tests/unit/dynamic_rendering.cpp
> -                ASSERT_VK_SUCCESS(err);
cases like this are really just places we should replace with our framework helpers

for example, could declare the object with`vkt::Framebuffer` and then go `init` here and make sure the `VK_SUCCESS` is working inside the binding

2023-10-12 01:45 UTC, spencer-lunarg approved these changes
my issues are orthogonal, this removes `ASSERT_VK_SUCCESS` which is a valid step forward

2023-10-12 01:47 UTC, merged