Chromium build cleanup
KhronosGroup/Vulkan-ValidationLayers pull request #6803
Opened 2023-10-23 21:04 UTC by juan-lunarg

2023-10-23 22:09 UTC, mikes-lunarg commented
Can you run `gn format BUILD.gn` on this? (Maybe that should be a CI step too)

2023-10-23 23:00 UTC, juan-lunarg commented
> Can you run gn format BUILD.gn on this? (Maybe that should be a CI step too)

Will this cause the ANGLE build to fail if it's not properly formatted?

2023-10-23 23:05 UTC, mikes-lunarg commented
> > Can you run gn format BUILD.gn on this? (Maybe that should be a CI step too)
> 
> Will this cause the ANGLE build to fail if it's not properly formatted?

No, I don't think the formatting of a third-party gn will fail them. I just think it is nice to keep the file in its canonical format.

2023-10-23 23:07 UTC, mikes-lunarg requested changes

2023-10-23 23:07 UTC, mikes-lunarg commented on BUILD.gn
> -        "nativewindow",
This breaks the ANGLE android build
```
[409/409] SOLINK ./libVkLayer_khronos_validation.so
FAILED: libVkLayer_khronos_validation.so libVkLayer_khronos_validation.so.TOC lib.unstripped/libVkLayer_khronos_validation.so 
"python3" "../../build/toolchain/gcc_solink_wrapper.py" --readelf="../../third_party/llvm-build/Release+Asserts/bin/llvm-readelf" --nm="../../third_party/llvm-build/Release+Asserts/bin/llvm-nm" --strip=../../third_party/llvm-build/Release+Asserts/bin/llvm-strip  --sofile="./lib.unstripped/libVkLayer_khronos_validation.so" --tocfile="./libVkLayer_khronos_validation.so.TOC" --output="./libVkLayer_khronos_validation.so" -- ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,-soname="libVkLayer_khronos_validation.so" -Wl,-Bsymbolic,--exclude-libs,ALL -fuse-ld=lld -Wl,--fatal-warnings -Wl,--build-id -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--color-diagnostics -fexperimental-relative-c++-abi-vtables -Wl,--no-rosegment -Wl,--undefined-version -Wl,--no-call-graph-profile-sort -Wl,--exclude-libs=libvpx_assembly_arm.a -Wl,-z,max-page-size=4096 --target=aarch64-linux-android29 -Wl,-mllvm,-enable-machine-outliner=never -no-canonical-prefixes -Wl,--gc-sections -Wl,-z,defs -Wl,--as-needed --unwindlib=none -nostdlib++ --sysroot=../../third_party/android_toolchain/ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot -Werror -o "./lib.unstripped/libVkLayer_khronos_validation.so" @"./libVkLayer_khronos_validation.so.rsp"  
ld.lld: error: undefined symbol: AHardwareBuffer_describe
>>> referenced by cc_android.cpp:119 (../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/core_checks/cc_android.cpp:119)
>>>               obj/third_party/vulkan-deps/vulkan-validation-layers/src/VkLayer_khronos_validation/cc_android.o:(CoreChecks::PreCallValidateGetAndroidHardwareBufferPropertiesANDROID(VkDevice_T*, AHardwareBuffer const*, VkAndroidHardwareBufferPropertiesANDROID*, ErrorObject const&) const)
>>> referenced by cc_android.cpp:182 (../../third_party/vulkan-deps/vulkan-validation-layers/src/layers/core_checks/cc_android.cpp:182)
>>>               obj/third_party/vulkan-deps/vulkan-validation-layers/src/VkLayer_khronos_validation/cc_android.o:(CoreChecks::ValidateAllocateMemoryANDROID(VkMemoryAllocateInfo const*, Location const&) const)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

2023-10-23 23:17 UTC, mikes-lunarg commented on BUILD.gn
> -        "nativewindow",
`"android"` will also work here in place of `"nativewindow"`, I'm not sure which is best. @spencer-lunarg any thoughts?

2023-10-23 23:19 UTC, juan-lunarg commented on BUILD.gn
> -        "nativewindow",
I see what happened. The CMake build requires API level being at least 26 so it doesn't link this library.

```
/**
 * Return a description of the AHardwareBuffer in the passed
 * AHardwareBuffer_Desc struct.
 *
 * Available since API level 26.
 */
void AHardwareBuffer_describe(const AHardwareBuffer* _Nonnull buffer,
                              AHardwareBuffer_Desc* _Nonnull outDesc) __INTRODUCED_IN(26);
```

I'll fix this.

2023-10-23 23:30 UTC, juan-lunarg commented
> No, I don't think the formatting of a third-party gn will fail them. I just think it is nice to keep the file in its canonical format.

```
________ running 'python3 tools/clang/scripts/update.py' in '/Users/juanramos/projects/vvl'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Mac_arm64/clang-llvmorg-16-init-17653-g39da55e8-2.tar.xz .......... Done.
gn.py: Could not find gn executable at: /Users/juanramos/projects/vvl/./buildtools/mac/gn
Command "gn format BUILD.gn" failed with return code 2
```

Couldn't get it to work on mac.

2023-10-23 23:49 UTC, mikes-lunarg commented
> ```
> ________ running 'python3 tools/clang/scripts/update.py' in '/Users/juanramos/projects/vvl'
> Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Mac_arm64/clang-llvmorg-16-init-17653-g39da55e8-2.tar.xz .......... Done.
> gn.py: Could not find gn executable at: /Users/juanramos/projects/vvl/./buildtools/mac/gn
> Command "gn format BUILD.gn" failed with return code 2
> ```
> 
> Couldn't get it to work on mac.

I see. I think it is because the DEPS file we have checked in for CI only has the linux build tools defined. I can push a format commit to your branch or we can just fix it later.

2023-10-23 23:50 UTC, juan-lunarg commented
> I see. I think it is because the DEPS file we have checked in for CI only has the linux build tools defined. I can push a format commit to your branch or we can just fix it later.

Feel free to push a format commit

2023-10-23 23:55 UTC, mikes-lunarg approved these changes

2023-10-24 00:30 UTC, spencer-lunarg approved these changes

2023-10-24 01:34 UTC, merged