git: Use less minutes for GitHub Actions
KhronosGroup/Vulkan-ValidationLayers pull request #6811
Opened 2023-10-24 13:54 UTC by spencer-lunarg

An attempt to use less minutes for our normal github actions

https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

Currently we are waiting hours for our GitHub CI to run

2023-10-24 13:55 UTC, spencer-lunarg commented on .github/workflows/vvl.yml
> +  linuxBuild:
From what I found, the gcc and ubuntu 20 type CI is great for catching build errors, not so much for testing

2023-10-24 13:55 UTC, spencer-lunarg commented on .github/workflows/vvl.yml
> -        arch: [ amd64, amd64_x86 ]
have yet to see not all or none of the Window clients fail

2023-10-24 13:56 UTC, spencer-lunarg commented on .github/workflows/vvl.yml
> +        os: [ macos-12 ]
at a 10x cost for minutes, this might be better served for internal CI (maybe the other way around if internal CI is Macos 11)

2023-10-24 17:23 UTC, juan-lunarg requested changes

2023-10-24 17:23 UTC, juan-lunarg commented on .github/workflows/vvl.yml
> -        arch: [ amd64, amd64_x86 ]
When I added amd64_x86 it caught a few 32 bit issues. I'm fine with not testing release builds here.

2023-10-24 17:23 UTC, juan-lunarg commented on .github/workflows/vvl.yml
> +        os: [ macos-12 ]
I'd rather leave this alone for now. I agree this could be better served for internal CI potentially. But since it isn't being done I'd rather not change this right now.

2023-10-24 17:23 UTC, juan-lunarg commented on .github/workflows/vvl.yml
> +  linuxBuild:
agreed

2023-10-24 17:23 UTC, juan-lunarg commented on .github/workflows/vvl.yml
> +          LDFLAGS: ${{ matrix.flags.ld }}
None of these apply anymore.

2023-10-24 17:23 UTC, juan-lunarg commented on .github/workflows/vvl.yml
> +          key: ${{ matrix.os }}-${{ matrix.config }}-${{ matrix.compiler.cc }}-${{ matrix.compiler.cxx }}-${{ matrix.cpp_std }}-${{ matrix.flags.c }}-${{ matrix.flags.ld }}-${{matrix.robin_hood}}
This key uses matrix values that don't exist

2023-10-24 17:47 UTC, mikes-lunarg commented
I just noticed there is a usage page for each run. Are you referencing this to trim down the matrix?
https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/6627852969/usage

2023-10-25 00:09 UTC, spencer-lunarg commented
@mikes-lunarg the term "matrix" I ment is like we do Windows for `[32-bit, 64-bit]` and `[debug, release]` so instead of doing all 4 matrix permutation, just to do what we need to save minutes used

2023-10-25 00:11 UTC, spencer-lunarg commented on .github/workflows/vvl.yml
> +        os: [ macos-12 ]
I guess do we know of any MacOS 11 users, just as we stop supporting older Windows/Linux/C++ version, I feel MacOS should be same (especially for a platform that prides itself having a high adoption rate for updates)

2023-10-25 01:17 UTC, spencer-lunarg commented
closing for https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6818

couldn't update the branch easily because it is in this repo and not my fork

2023-10-25 01:17 UTC, closed without merging

2023-10-25 01:31 UTC, juan-lunarg commented on .github/workflows/vvl.yml
> +        os: [ macos-12 ]
In our SDK documentation we say we support the latest 2 MacOS releases

Same rational as supporting Ubuntu 20.04