layers: Add 03668
KhronosGroup/Vulkan-ValidationLayers pull request #6820
Opened 2023-10-25 08:30 UTC by arno-lunarg

Also refacto the ray tracing memory aliasing validation code

2023-10-25 08:50 UTC, spencer-lunarg requested changes

2023-10-25 08:50 UTC, spencer-lunarg commented on tests/unit/ray_tracing.cpp
> +TEST_F(NegativeRayTracing, AccelerationStructuresOverlappingMemory) {
I guess why partially disable it? 

can we not just break the test up so the working parts are in a "ready to go" test and the "not ready stuff" is behind a single test `DISABLED` instead of playing the `if 0` game

2023-10-25 08:50 UTC, spencer-lunarg commented on layers/core_checks/cc_ray_tracing.cpp
> +        skip |= ValidateAccelerationStructuresMemoryAlisasing(commandBuffer, infoCount, pInfos, info_i, error_obj);
why are we not passing in `info_loc` instead of `error_obj`, we lose the index knowledge

2023-10-25 10:17 UTC, spencer-lunarg commented on layers/core_checks/cc_ray_tracing.cpp
> +            validate_no_as_buffer_memory_overlap(*src_as_state, src_as_log_info.str().c_str(), *src_as_buffer, src_as_range,
Why not have the lambda only do the 

```
 if (const auto [memory, overlap_range] = buffer_a.GetResourceMemoryOverlap(range_a, &buffer_b, range_b);
                memory != VK_NULL_HANDLE) {
```

logic, the reason is I like not having to do string concatenation every time when this has no error

2023-10-25 10:22 UTC, spencer-lunarg commented on layers/core_checks/cc_ray_tracing.cpp
> +                    string_VkAccelerationStructureTypeKHR(dst_as_state->create_infoKHR.type));
you have `if (!dst_as_state` so this will be a null pointer reference

2023-10-25 10:24 UTC, spencer-lunarg commented on layers/core_checks/cc_ray_tracing.cpp
> +                                 string_VkBuildAccelerationStructureFlagsKHR(src_as_state->build_info_khr.flags).c_str());
if we hit `!src_as_state->built`  won't these flags value be undefined

2023-10-25 10:26 UTC, spencer-lunarg commented on layers/core_checks/cc_ray_tracing.cpp
> +    const auto src_as_state = Get<ACCELERATION_STRUCTURE_STATE_KHR>(pInfos[info_i].srcAccelerationStructure);
```suggestion
    const auto src_as_state = Get<ACCELERATION_STRUCTURE_STATE_KHR>(info.srcAccelerationStructure);
```

2023-10-27 04:52 UTC, arno-lunarg commented on layers/core_checks/cc_ray_tracing.cpp
> +                                 string_VkBuildAccelerationStructureFlagsKHR(src_as_state->build_info_khr.flags).c_str());
nice catch ty

2023-10-27 04:52 UTC, arno-lunarg commented on layers/core_checks/cc_ray_tracing.cpp
> +                    string_VkAccelerationStructureTypeKHR(dst_as_state->create_infoKHR.type));
nice catch ty

2023-10-27 07:33 UTC, spencer-lunarg approved these changes

2023-10-27 09:07 UTC, merged