Fix texel size in image/buffer copies
KhronosGroup/Vulkan-ValidationLayers pull request #6907
Opened 2023-11-03 01:45 UTC by Tony-LunarG

Addresses part of #6898

2023-11-03 01:48 UTC, spencer-lunarg commented on layers/core_checks/cc_copy_blit_resolve.cpp
> +        auto texel_size = vkuFormatTexelSizeWithAspect(image_state.createInfo.format,
The "Texel vs Element" size is something I still want to improve the documentation for as it is always confusing and hard to get right with some formats

2023-11-03 01:48 UTC, spencer-lunarg approved these changes

2023-11-03 08:14 UTC, arno-lunarg requested changes

2023-11-03 08:14 UTC, arno-lunarg commented on layers/core_checks/cc_copy_blit_resolve.cpp
> +            copy_size = static_cast<VkDeviceSize>(((region.bufferRowLength * region.bufferImageHeight) * texel_size));
```suggestion
            copy_size = static_cast<VkDeviceSize>(region.bufferRowLength) * region.bufferImageHeight * texel_size;
```
Assuming this will implicitly cast `region.bufferImageHeight` and `texel_size` to `VkDeviceSize` before doing the multiplication

2023-11-03 08:14 UTC, arno-lunarg commented on layers/core_checks/cc_copy_blit_resolve.cpp
> +                static_cast<VkDeviceSize>(region.imageOffset.x * region.imageOffset.y * region.imageOffset.z * texel_size);
```suggestion
                static_cast<VkDeviceSize>(region.imageOffset.x) * region.imageOffset.y * region.imageOffset.z * texel_size;
```
(Same assumption here)

2023-11-03 08:14 UTC, arno-lunarg commented on layers/core_checks/cc_copy_blit_resolve.cpp
> +            image_offset = (region.imageSubresource.baseArrayLayer * srl.arrayPitch) +
Will all the multiplications/additions happen using value casted to `VkDeviceSize` here?

2023-11-03 08:14 UTC, arno-lunarg commented on layers/core_checks/cc_copy_blit_resolve.cpp
> +                ((region.imageExtent.width * region.imageExtent.height * region.imageExtent.depth) * texel_size));
```suggestion
            copy_size = static_cast<VkDeviceSize>(region.imageExtent.width) * region.imageExtent.height * region.imageExtent.depth * texel_size;
```
(Same assumption here)

2023-11-03 15:29 UTC, Tony-LunarG commented on layers/core_checks/cc_copy_blit_resolve.cpp
> +            copy_size = static_cast<VkDeviceSize>(((region.bufferRowLength * region.bufferImageHeight) * texel_size));
The cast is to handle texel_size being a double.  I believe all of the arithmetic will be done in floating point and at the end, cast to VkDeviceSize (uint64_t), which is what I think I want.  Taking the suggestion would result in a conversion, possible loss of data error

2023-11-03 15:49 UTC, Tony-LunarG commented on layers/core_checks/cc_copy_blit_resolve.cpp
> +            image_offset = (region.imageSubresource.baseArrayLayer * srl.arrayPitch) +
I believe the cast of (region.imageOffset.x * texel_size) to VkDeviceSize will cause all operations to be at VkDeviceSize size.

2023-11-03 15:54 UTC, Tony-LunarG commented on layers/core_checks/cc_copy_blit_resolve.cpp
> +                static_cast<VkDeviceSize>(region.imageOffset.x * region.imageOffset.y * region.imageOffset.z * texel_size);
It should be floating point operations cast to uint64_t

2023-11-03 15:54 UTC, Tony-LunarG commented on layers/core_checks/cc_copy_blit_resolve.cpp
> +                ((region.imageExtent.width * region.imageExtent.height * region.imageExtent.depth) * texel_size));
It should be floating point operations cast to uint64_t

2023-11-06 18:29 UTC, arno-lunarg approved these changes

2023-11-06 18:52 UTC, merged