gpuav: Custom shader instrumentation
KhronosGroup/Vulkan-ValidationLayers pull request #7045
Opened 2023-11-29 16:02 UTC by spencer-lunarg

Attempt to add basic support for ` VUID-RuntimeSpirv-OpTraceRayKHR-06356` and `VUID-RuntimeSpirv-OpReportIntersectionKHR-06998` and doing it all with our new internal SPIR-V instrumentation logic

2023-11-29 17:02 UTC, spencer-lunarg commented on layers/gpu_validation/spirv/CMakeLists.txt
> +# Khronos validation additional dependencies
@arno-lunarg what was your idea for not having to duplicate this CMake `target_link_libraries` logic?

2023-11-29 17:50 UTC, arno-lunarg commented on layers/gpu_validation/spirv/CMakeLists.txt
> +# Khronos validation additional dependencies
A function that takes in a CMake target and add common compile options, libraries, etc...

2023-11-29 19:50 UTC, jeremyg-lunarg reviewed
this looks like a good start. I'm curious to see how much it would have to grow to accommodate the bindless and BDA passes. They need some additional features like injecting capabilities, extensions and addressing modes into the host module. One advantage of using the SPIRV-Tools Link() code is that it will tell you when this is messed up.

2023-11-29 19:50 UTC, jeremyg-lunarg commented on layers/gpu_validation/spirv/type_manager.h
> +    std::list<Type> types_;
I don't get why you need the lists, vs putting the storage in the maps. You might have to use std::unordered_map instead of robin_hood, to ensure stable pointers.

2023-11-29 19:50 UTC, jeremyg-lunarg commented on layers/gpu_validation/spirv/instruction.h
> +};
It would be great to have a ToString() method for debugging. Eventually.

2023-11-29 19:50 UTC, jeremyg-lunarg commented on layers/gpu_validation/spirv/instruction.cpp
> +// ever be used. With this, instead of trying to over-engineer something generated to find all reference IDs in each instructions,
How do we really know this, given that the linked functions come from glsl?

2023-11-29 19:50 UTC, jeremyg-lunarg commented on layers/gpu_validation/spirv/module.h
> +    ModuleHeader header_;
are you planning on leaving non-const data members as public? Are you using this direct access currently?

2023-11-30 00:42 UTC, spencer-lunarg commented on layers/gpu_validation/spirv/type_manager.h
> +    std::list<Type> types_;
this originally was a vector, but the pointers weren't stable... but yes, a map could store it I realize too

2023-11-30 00:44 UTC, spencer-lunarg commented on layers/gpu_validation/spirv/instruction.cpp
> +// ever be used. With this, instead of trying to over-engineer something generated to find all reference IDs in each instructions,
so the only real advantage of generating is when a new extensions adds `OpNewThing` it is handled automatically in the wild when this is used

since this is from our generated logic, we would catch the fact `OpNewThing` is not used at testing time, we don't have to worry about what the app provides us

2023-11-30 00:53 UTC, spencer-lunarg commented on layers/gpu_validation/spirv/module.h
> +    ModuleHeader header_;
this was a hard design decision I went back and forth a lot on, so there are 2 phases

1. when we parse the original SPIR-V
2. When we do a pass/linking and want to edit

From here, I found it such code gymnastic to have the Module class be the only thing that edit this, I felt that `Module` should just be the "raw data" that the other classes decide who is in charge of writing to it, like for example, `TypeManager` is in charge of all the types/constant/variables, the `BasicBlock` is in charge or writing the instructions in it, but the `Module` is the only object the user (gpu_validation.cpp) interacts with

2023-11-30 07:24 UTC, spencer-lunarg commented on layers/gpu_validation/spirv/module.h
> +    ModuleHeader header_;
thinking more about this, I might have gone to far in the fear to over abstract things...going to separate the part of `Module` that holds the spirv data and the part to orchestrates everything

2023-12-04 17:28 UTC, juan-lunarg requested changes

2023-12-04 17:34 UTC, juan-lunarg commented on layers/gpu_validation/spirv/CMakeLists.txt
> +    ${CMAKE_SOURCE_DIR}/layers/${API_TYPE}/generated/spirv_grammar_helper.cpp
This will break add_subdirectory / FetchContent users.

2023-12-04 17:35 UTC, juan-lunarg commented on layers/gpu_validation/spirv/CMakeLists.txt
> +    ${CMAKE_SOURCE_DIR}/layers/${API_TYPE}/generated/spirv_grammar_helper.cpp
Use VVL_SOURCE_DIR instead.

https://cmake.org/cmake/help/latest/variable/PROJECT-NAME_SOURCE_DIR.html

2023-12-18 03:53 UTC, spencer-lunarg commented
closing, this will be attempted for real after the next SDK freeze, for now, leaving the old system in place

2023-12-18 03:53 UTC, closed without merging