syncval: Set queue submit time sync val to default on
KhronosGroup/Vulkan-ValidationLayers pull request #7129
Opened 2023-12-11 23:54 UTC by jzulauf-lunarg

Set queue submit time sync validation to be on by default.

Add disable setting for those that want to turn it off for performance.

Fixes #7127

2023-12-12 00:15 UTC, spencer-lunarg approved these changes

2023-12-12 08:52 UTC, christophe-lunarg commented on layers/layer_options.cpp
> -            break;
It's not clear to me why stuff move around but that's ok with me. Just commenting to be sure that's not an accident,

2023-12-12 08:52 UTC, christophe-lunarg commented on layers/layer_options.cpp
> -            break;
Oh, it went from an enable to a disable ok!

2023-12-12 08:52 UTC, christophe-lunarg commented on tests/unit/sync_val_positive.cpp
> +    // QueueSubmit Validation *always* on (default behavior)
It sounds like to me we need to a test to check the "disable" code path is working? If it's always on, it's never tested,

2023-12-12 12:55 UTC, artem-lunarg approved these changes

2023-12-12 20:19 UTC, jzulauf-lunarg commented on tests/unit/sync_val_positive.cpp
> +    // QueueSubmit Validation *always* on (default behavior)
Cleaned this up...

2023-12-12 20:19 UTC, jzulauf-lunarg commented on tests/unit/sync_val_positive.cpp
> +    // QueueSubmit Validation *always* on (default behavior)
done

2023-12-12 21:10 UTC, christophe-lunarg commented on layers/layer_options.cpp
> +        SetValidationSetting(layer_setting_set, settings_data->disables, sync_validation_queue_submit,
This is the part of the new settings and it looks correct.

2023-12-12 21:11 UTC, christophe-lunarg requested changes
Sorry, I just realized : You only modified the legacy settings, that could be configured with VK_EXT_validation_features and the flags, but there is a new approach:
```
                            "settings": [
                                {
                                    "key": "sync_queue_submit",
                                    "label": "QueueSubmit Synchronization Validation",
                                    "description": "Enable synchronization validation between submitted command buffers when Synchronization Validation is enabled. This option will increase the synchronization performance cost.",
                                    "type": "BOOL",
                                    "default": false,
                                    "status": "ALPHA",
                                    "dependence": {
                                        "mode": "ALL",
                                        "settings": [
                                            {
                                                "key": "validate_sync",
                                                "value": true
                                            }
                                        ]
                                    }
                                }
                            ]
                            ```
        Replace this by :
                 ```
                            "settings": [
                                {
                                    "key": "sync_queue_submit",
                                    "label": "QueueSubmit Synchronization Validation",
                                    "description": "Enable synchronization validation between submitted command buffers when Synchronization Validation is enabled. This option will increase the synchronization performance cost.",
                                    "type": "BOOL",
                                    "default": true,
                                    "status": "STABLE",
                                    "dependence": {
                                        "mode": "ALL",
                                        "settings": [
                                            {
                                                "key": "validate_sync",
                                                "value": true
                                            }
                                        ]
                                    }
                                }
                            ]
                            ```           
                            
                            Sorry for the late feedback :/

2023-12-13 07:51 UTC, christophe-lunarg approved these changes

2023-12-13 11:54 UTC, merged