Add Dynamic Rendering Identity Swizzle
KhronosGroup/Vulkan-ValidationLayers pull request #7175
Opened 2023-12-20 10:36 UTC by spencer-lunarg

1.3.274 [added](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/6309/diffs) the following VUs

- VUID-VkRenderingInfo-colorAttachmentCount-09479
- VUID-VkRenderingInfo-colorAttachmentCount-09480
- VUID-VkRenderingInfo-pDepthAttachment-09481
- VUID-VkRenderingInfo-pDepthAttachment-09482
- VUID-VkRenderingInfo-pStencilAttachment-09483
- VUID-VkRenderingInfo-pStencilAttachment-09484
- VUID-VkRenderingInfo-imageView-09485
- VUID-VkRenderingInfo-imageView-09486

there are 2 commits here to first do some house cleaning around the begin rendering functions

2023-12-22 13:56 UTC, arno-lunarg requested changes

2023-12-22 13:56 UTC, arno-lunarg commented on layers/core_checks/cc_render_pass.cpp
> +    auto device_group_begin_info = vku::FindStructInPNextChain<VkDeviceGroupRenderPassBeginInfo>(pRenderPassBegin->pNext);
```suggestion
    auto device_group_rp_begin_info = vku::FindStructInPNextChain<VkDeviceGroupRenderPassBeginInfo>(pRenderPassBegin->pNext);
```

2023-12-22 13:56 UTC, arno-lunarg commented on layers/core_checks/cc_render_pass.cpp
> +                    skip |= LogError("VUID-VkRenderingInfo-pDepthAttachment-09477", objlist, color_loc.dot(Field::resolveImageView),
⚠️ probably should not be vuid `pDepthAttachment-09477` here, or the check is wrong

2023-12-23 10:15 UTC, spencer-lunarg commented on layers/core_checks/cc_render_pass.cpp
> +                    skip |= LogError("VUID-VkRenderingInfo-pDepthAttachment-09477", objlist, color_loc.dot(Field::resolveImageView),
ahh, yes, I have this is a followup commit I seemed to have forgot to push

2023-12-28 16:47 UTC, arno-lunarg approved these changes

2023-12-28 23:44 UTC, merged