sync: Fix async tag propagation
KhronosGroup/Vulkan-ValidationLayers pull request #7532
Opened 2024-02-19 17:36 UTC by artem-lunarg

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7386, https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7455

2024-02-20 00:35 UTC, spencer-lunarg commented on tests/unit/sync_val_positive.cpp
> +    VkImageObj image(m_device);
```suggestion
    vkt::Image image(*m_device, 64, 64, 1, VK_FORMAT_R8_UNORM, VK_IMAGE_USAGE_TRANSFER_DST_BIT);
```

2024-02-20 00:36 UTC, spencer-lunarg approved these changes
LGTM - @jzulauf-lunarg would be nice to confirm as well

2024-02-20 07:44 UTC, artem-lunarg commented on tests/unit/sync_val_positive.cpp
> +    VkImageObj image(m_device);
Fixed

2024-02-20 19:29 UTC, jzulauf-lunarg requested changes
queue_sync_tag_ is the global of each *other* queue with the one owning this QBC. Can't be scalar.  Algorithmic review with author done, for new approach.

Test gaps identified.

2024-02-23 14:00 UTC, artem-lunarg commented
Added regression test to show that previous approach with scalar asyn tag tracking is incorrect.

2024-02-23 21:39 UTC, artem-lunarg commented
@jzulauf-lunarg the author reworked the solution and also additional test was added to cause regression on initial broken implementation.

2024-02-27 19:06 UTC, jzulauf-lunarg approved these changes
LGTM -- thanks for the additional tests.

2024-02-27 23:04 UTC, merged