sync: Use CLEAR transfer stage for vkCmdFillBuffer
KhronosGroup/Vulkan-ValidationLayers pull request #7543
Opened 2024-02-20 20:09 UTC by artem-lunarg

`vkCmdFillBuffer` is a transfer clear command, and not a transfer copy command. I make this assumption because this command is described in the "Clear commands" section of the specification and not in the "Copy commands" section.

> VK_PIPELINE_STAGE_2_COPY_BIT specifies the execution of all [copy commands](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#copies)

> VK_PIPELINE_STAGE_2_CLEAR_BIT specifies the execution of [clear commands](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#clears)

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7406

2024-02-20 20:55 UTC, jzulauf-lunarg requested changes
vkCmdUpdateBuffer is also in the clear commands section, but uses `SYNC_COPY_TRANSFER_WRITE`.  Probably should also be updated.

2024-02-20 21:20 UTC, jzulauf-lunarg commented on tests/unit/sync_val_positive.cpp
> +TEST_F(PositiveSyncVal, FillBuffer) {
Should have a negative for this as well.

2024-02-20 21:31 UTC, artem-lunarg commented on tests/unit/sync_val_positive.cpp
> +TEST_F(PositiveSyncVal, FillBuffer) {
Added negative tests both for CmdUpdateBuffer and CmdFillBuffer. CmdFillBuffer already had a negative use case in `BufferCopyHazards` but it's nice to have a dedicated small test too.

2024-02-20 23:05 UTC, jzulauf-lunarg commented on tests/unit/sync_val.cpp
> +    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "SYNC-HAZARD-READ-AFTER-WRITE");
What I was thinking about was something that had a barrier for the wrong stage either source or dest...

2024-02-20 23:55 UTC, artem-lunarg commented on tests/unit/sync_val.cpp
> +    m_errorMonitor->SetDesiredFailureMsg(kErrorBit, "SYNC-HAZARD-READ-AFTER-WRITE");
Added wrong barriers on both sides of the conflict.

2024-02-21 07:51 UTC, spencer-lunarg approved these changes
LGTM - Zulaf comments seem to be have addressed

2024-02-21 07:58 UTC, merged

2024-02-21 15:27 UTC, jzulauf-lunarg reviewed
LGTM