Add validation for VK_EXT_map_memory_placed
KhronosGroup/Vulkan-ValidationLayers pull request #7588
Opened 2024-02-26 23:09 UTC by gfxstrand

The one VU I haven't validated is the one about `pPlacedAddress` not being inside the map of another Vulkan memory object. I don't know if that kind of tracking exists inside the validation layers or how to go about adding it if it doesn't. Everything else should be validated and tested.

2024-02-27 00:33 UTC, spencer-lunarg requested changes
LGTM - Just a few nit fixes

2024-02-27 00:33 UTC, spencer-lunarg commented on layers/core_checks/cc_device_memory.cpp
> +            skip |= LogError("VUID-vkMapMemory-flags-09568", memory, error_obj.location,
```suggestion
            skip |= LogError("VUID-vkMapMemory-flags-09568", memory, error_obj.location.dot(Field::flags),
```

2024-02-27 00:33 UTC, spencer-lunarg commented on layers/core_checks/cc_device_memory.cpp
> +                    skip |= LogError("VUID-VkMemoryMapInfoKHR-flags-09573", pMemoryMapInfo->memory, info_loc.dot(Field::offset),
`info_loc.dot(Field::offset)` will print out before the error message

> vkMapMemory2KHR() pMemoryMapInfo->offset 

so the error message will strange, 

suggest

"offset (0x%" PRIx64 ") is not an integer multiple of minPlacedMemoryMapAlignment (0x%" PRIx64 ") while VK_MEMORY_MAP_PLACED_BIT_EXT is set",

2024-02-27 00:33 UTC, spencer-lunarg commented on layers/core_checks/cc_device_memory.cpp
> +                    skip |= LogError("VUID-VkMemoryMapInfoKHR-flags-09573", pMemoryMapInfo->memory, info_loc.dot(Field::offset),
same for the rest of the error messages

2024-02-27 00:33 UTC, spencer-lunarg commented on tests/unit/memory.cpp
> +TEST_F(NegativeMemory, MapMemoryPlaced) {
for extensions, we want a single positive test (`memory_positive.cpp`) of using the extension in a basic way to help reduce false positive regressions

2024-02-27 00:33 UTC, spencer-lunarg commented on tests/unit/memory.cpp
> +    RETURN_IF_SKIP(InitFramework());
you can just go

```patch
- RETURN_IF_SKIP(InitFramework());
- 
- VkPhysicalDeviceMapMemoryPlacedFeaturesEXT map_placed_features = vku::InitStructHelper();
- GetPhysicalDeviceFeatures2(map_placed_features);
- if (map_placed_features.memoryMapPlaced != VK_TRUE) {
-     GTEST_SKIP() << "memoryMapPlaced feature not supported";
- }
- 
- RETURN_IF_SKIP(InitState(nullptr, &map_placed_features));
+ AddRequiredFeature(vkt::Feature::memoryMapPlaced);
+ RETURN_IF_SKIP(Init());
```

2024-02-27 00:33 UTC, spencer-lunarg commented on layers/core_checks/cc_device_memory.cpp
> +            } else if (reinterpret_cast<std::uintptr_t>(placed_info->pPlacedAddress) %
seems android/ios build aren't happy with this cast

2024-02-27 00:39 UTC, spencer-lunarg commented on layers/core_checks/cc_device_memory.cpp
> +                                     "VK_MEMORY_MAP_PLACED_BIT_EXT is set and size (0x%" PRIx64 ") is not VK_WHOLE_SIZE and "
another nit/question, people have complained that things like `size` and `offset` were in hex instead of decimal, as one of the main users of this extension, happy to follow your guide on this, but wanted to express this incase this was an oversight

2024-02-27 04:06 UTC, gfxstrand commented on layers/core_checks/cc_device_memory.cpp
> +                                     "VK_MEMORY_MAP_PLACED_BIT_EXT is set and size (0x%" PRIx64 ") is not VK_WHOLE_SIZE and "
I think it's a bit of a matter of user preference. For me, when I'm looking at something that's effectively an address, especially when the validation error is that the address isn't properly aligned, having it in decimal is next to useless while hex makes the error easy to see.

2024-02-27 04:10 UTC, gfxstrand commented on layers/core_checks/cc_device_memory.cpp
> +            } else if (reinterpret_cast<std::uintptr_t>(placed_info->pPlacedAddress) %
Fixed. It's not compatible with `PRIx64` on 32-bit builds. I've replaced it with `%p`.

2024-02-27 04:33 UTC, spencer-lunarg commented on layers/core_checks/cc_device_memory.cpp
> +                                     "VK_MEMORY_MAP_PLACED_BIT_EXT is set and size (0x%" PRIx64 ") is not VK_WHOLE_SIZE and "
sounds good

2024-02-27 16:28 UTC, gfxstrand commented on layers/core_checks/cc_device_memory.cpp
> +                    skip |= LogError("VUID-VkMemoryMapInfoKHR-flags-09573", pMemoryMapInfo->memory, info_loc.dot(Field::offset),
Fixed.

2024-02-27 16:28 UTC, gfxstrand commented on tests/unit/memory.cpp
> +TEST_F(NegativeMemory, MapMemoryPlaced) {
Done.

2024-02-28 00:52 UTC, spencer-lunarg approved these changes

2024-02-28 00:52 UTC, merged