layers: Add new vkCmdBeginTransformFeedbackEXT VU
KhronosGroup/Vulkan-ValidationLayers pull request #7753
Opened 2024-03-25 02:58 UTC by spencer-lunarg

`VUID-vkCmdBeginTransformFeedbackEXT-firstCounterBuffer-09630` was added in `1.3.281`

This might be what was causing some Transform Feedback tests to fail and be blacklisted in CI as the internal Gitlab issue showed that some driver crash and I never could figure out we were doing wrong in the tests

2024-03-25 05:25 UTC, arno-lunarg approved these changes
LGTM! Maybe one issue with error message

2024-03-25 05:25 UTC, arno-lunarg commented on layers/core_checks/cc_cmd_buffer.cpp
> +                         firstCounterBuffer, counterBufferCount, firstCounterBuffer + counterBufferCount);
```suggestion
                         firstCounterBuffer, counterBufferCount, firstCounterBuffer + counterBufferCount - 1);
```
(I think?)

2024-03-25 05:28 UTC, arno-lunarg requested changes

2024-03-25 05:28 UTC, arno-lunarg commented on layers/core_checks/cc_cmd_buffer.cpp
> +                         firstCounterBuffer, counterBufferCount, firstCounterBuffer + counterBufferCount);
VUID-vkCmdBeginTransformFeedbackEXT-firstCounterBuffer-09630
The sum of firstCounterBuffer and counterBufferCount **must be less than or equal to the number of transform feedback buffers currently bound** by [vkCmdBindTransformFeedbackBuffersEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkCmdBindTransformFeedbackBuffersEXT.html)

So I think that `test`ing to see if `firstCounterBuffer + counterBufferCount - 1` is set is not the correct way to check?

2024-03-25 05:31 UTC, spencer-lunarg commented on layers/core_checks/cc_cmd_buffer.cpp
> +                         firstCounterBuffer, counterBufferCount, firstCounterBuffer + counterBufferCount);
there are VU to make sure you have can't bind `[2, 3]` and you need to bind buffer `[0, 1]`

So if I have bound `[0, 1]` that means I need to make sure that `firstCounterBuffer + counterBufferCount` is not greater than `2` so I guess what would be your counter proposal?

2024-03-27 06:09 UTC, spencer-lunarg commented on layers/core_checks/cc_cmd_buffer.cpp
> +                         firstCounterBuffer, counterBufferCount, firstCounterBuffer + counterBufferCount);
@arno-lunarg I got clarifications and this was simpler than I realize

2024-03-28 02:28 UTC, arno-lunarg approved these changes

2024-03-28 03:24 UTC, merged