Fix update_deps.py script to handle Windows Arm64.
KhronosGroup/Vulkan-ValidationLayers pull request #7850
Opened 2024-04-15 21:36 UTC by alexrp

Mirroring https://github.com/KhronosGroup/Vulkan-Loader/pull/1469.

2024-04-15 21:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=7850) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-ValidationLayers?pullRequest=7850) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-ValidationLayers?pullRequest=7850) it.</sub>

2024-04-15 21:41 UTC, charles-lunarg requested changes
Change commit title to `build: Fix update_deps.py script to handle Windows Arm64` (CI check asks for this)

2024-04-15 21:53 UTC, charles-lunarg approved these changes
Thanks for fixing the commit message (not 100% sure its fixed, CI on this repo was taking a while to start). But I'll approve so that the 'request changes' goes away. Of course, a maintainer of this repo will have to approve & only they can merge it, but hopefully my response here lets them know whats up.

2024-04-16 04:53 UTC, spencer-lunarg approved these changes

2024-04-16 04:53 UTC, spencer-lunarg commented
> but hopefully my response here lets them know whats up.

:+1:

2024-04-16 04:53 UTC, merged