gpu: Fix internal dispatches errors
KhronosGroup/Vulkan-ValidationLayers pull request #7866
Opened 2024-04-19 10:35 UTC by arno-lunarg

Using self validation, i.e adding another build of the validation layer in the layer stack to validate the dispatches we make internally in GPU-AV, discovered multiple errors that showed up in the tests.
Tests should be green now.

I need to cleanup `gpu_validation.md` further, it is out of date. Just added table of contents, and how to setup self validation

Did one commit per bug fix

2024-04-19 13:03 UTC, spencer-lunarg requested changes

2024-04-19 14:35 UTC, jeremyg-lunarg commented on layers/gpu_validation/gpu_state_tracker.cpp
> +                new_bda_features.pNext = const_cast<void *>(modified_create_info->pNext);
This stuff could be rewritten using vku::AddExtension() and vku::AddToPnext(). There's examples of what I mean in Vulkan-ExtensionLayer and an internal repo...

2024-04-22 01:48 UTC, arno-lunarg commented on layers/layer_options.cpp
> +#else
This will trigger warnings, because you have code after an inevitable return

2024-04-22 01:59 UTC, arno-lunarg commented on layers/gpu_validation/gpu_state_tracker.cpp
> +    // GPU-AV relies
??

2024-04-22 06:15 UTC, arno-lunarg commented on layers/gpu_validation/gpu_state_tracker.cpp
> +                new_bda_features.pNext = const_cast<void *>(modified_create_info->pNext);
Ok, did the modif in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7866/commits/de6673c2bf36f282aabfc5674ddcd9f319eb494b

2024-04-23 13:01 UTC, spencer-lunarg commented on tests/CMakeLists.txt
> -    set_target_properties(vk_layer_validation_tests PROPERTIES VS_DEBUGGER_ENVIRONMENT "VK_LAYER_PATH=$<TARGET_FILE_DIR:vvl>")
@arno-lunarg did https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7869 solve this or did you still need this... I am not on Windows so trust you on this

2024-04-23 13:23 UTC, arno-lunarg commented on tests/CMakeLists.txt
> -    set_target_properties(vk_layer_validation_tests PROPERTIES VS_DEBUGGER_ENVIRONMENT "VK_LAYER_PATH=$<TARGET_FILE_DIR:vvl>")
We still need this change, but coupled with Charles' one if VK_LAYER_PATH is not supplied it will correctly default to the one we are working on, so everything is fine!

2024-04-29 03:43 UTC, merged