gpu: Fix shader caching
KhronosGroup/Vulkan-ValidationLayers pull request #8021
Opened 2024-05-16 09:55 UTC by arno-lunarg

Closes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8020

Take into account GPU AV settings

2024-05-16 10:30 UTC, artem-lunarg commented on layers/gpu_validation/gpu_setup.cpp
> +                char _pad[Align<size_t>(sizeof(GpuAVSettings) + sizeof(INST_SHADER_GIT_HASH), 4) - sizeof(GpuAVSettings) -
`_pad` - starting with underscore is probably reserved for the complier in c++.

If  `Align<size_t>(sizeof(GpuAVSettings) + sizeof(INST_SHADER_GIT_HASH), 4) - sizeof(GpuAVSettings) - sizeof(INST_SHADER_GIT_HASH)`  is zero then it is illegal to declare array of size zero. Probably it is not zero now, but might become if other fields change.

2024-05-16 10:34 UTC, arno-lunarg commented on layers/gpu_validation/gpu_setup.cpp
> +                char _pad[Align<size_t>(sizeof(GpuAVSettings) + sizeof(INST_SHADER_GIT_HASH), 4) - sizeof(GpuAVSettings) -
yeah this pad thing is garbage but does the job and seems to compile fine in CI... basically I just want to pad if needed. Probably some template shenanigans would allow me to do that, but I do not know what : /

2024-05-16 10:35 UTC, artem-lunarg commented on layers/gpu_validation/gpu_setup.cpp
> +                char _pad[Align<size_t>(sizeof(GpuAVSettings) + sizeof(INST_SHADER_GIT_HASH), 4) - sizeof(GpuAVSettings) -
Maybe the above can be achieved by using `struct alignas(4) ShaderCacheHash`?? This should ensure that struct size is also multiple of 4 in order to have correct alignment when structs are put in array.

2024-05-16 10:58 UTC, arno-lunarg commented on layers/gpu_validation/gpu_setup.cpp
> +                char _pad[Align<size_t>(sizeof(GpuAVSettings) + sizeof(INST_SHADER_GIT_HASH), 4) - sizeof(GpuAVSettings) -
What is want is access to the padding byte, to make sure they are always 0, because of the memory write and compare we do in this portion of code. 
If I do not explicitly add padding, not sure the trailing bytes are guaranteed to be 0?

2024-05-16 10:59 UTC, arno-lunarg commented on layers/gpu_validation/gpu_setup.cpp
> +                char _pad[Align<size_t>(sizeof(GpuAVSettings) + sizeof(INST_SHADER_GIT_HASH), 4) - sizeof(GpuAVSettings) -
struct mem layout looks like this in VS:
![image](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/111733687/57d5f28c-5456-4f24-826b-02995cf81d3d)

2024-05-16 11:00 UTC, arno-lunarg commented on layers/gpu_validation/gpu_setup.cpp
> +                char _pad[Align<size_t>(sizeof(GpuAVSettings) + sizeof(INST_SHADER_GIT_HASH), 4) - sizeof(GpuAVSettings) -
and `sizeof(ShaderCacheHash)`, without explicit padding, still gives me 64

2024-05-16 11:01 UTC, arno-lunarg commented on layers/gpu_validation/gpu_setup.cpp
> +                char _pad[Align<size_t>(sizeof(GpuAVSettings) + sizeof(INST_SHADER_GIT_HASH), 4) - sizeof(GpuAVSettings) -
But you make me realize that instead of adjusting by adding explicit padding, I could adjust the memory write and compare sizes, it will be less messy

2024-05-16 11:07 UTC, arno-lunarg commented
I am missing the shader cache hash write, in the process of adding that....

2024-05-16 11:20 UTC, arno-lunarg commented
Should be good now, I made sure that we hit the cache when we need, and only then

2024-05-16 11:42 UTC, artem-lunarg commented on layers/gpu_validation/gpu_setup.cpp
> +            constexpr size_t unpadded_shader_cash_hash_byte_size = sizeof(GpuAVSettings) + sizeof(INST_SHADER_GIT_HASH);
This assumes there is no padding between GpuAvSettings and GIT_HASH fields, not true in general.. I dont know if expression Obj obj{} initializes padding to zero, if yes, might help.

This stuff is always complicated, now I think maybe not that bad. I also like solution where you compute pad size manually and use constant and then after structure have static_assert(sizeof(struct) == sizeof(field1) + sizeof(field2) + padding_array_size_constant) so it will always complain at compile time and struct definition will be simple, but will need adjustment to padding_array_size_constant if structure definition changes.

2024-05-16 13:14 UTC, arno-lunarg commented on layers/gpu_validation/gpu_setup.cpp
> +            constexpr size_t unpadded_shader_cash_hash_byte_size = sizeof(GpuAVSettings) + sizeof(INST_SHADER_GIT_HASH);
I went for `#pragma pack(push, 1)` approach, makes things simpler indeed!

2024-05-16 13:48 UTC, artem-lunarg approved these changes

2024-05-16 13:59 UTC, spencer-lunarg reviewed
code is fine, but before we merge this, please let me test this tomorrow on Linux to make sure it works as intended

2024-05-17 03:06 UTC, spencer-lunarg commented on layers/gpu_validation/gpu_setup.cpp
> +            if (!strncmp(inst_shader_hash, reinterpret_cast<char *>(&shader_cache_hash), sizeof(shader_cache_hash))) {
before we had a `uint64_t` we were reading, but not we have a struct with bool that I assume are `0x0` should we be using `memcmp` as I am not sure why this is a string compare to be honest

2024-05-17 03:17 UTC, spencer-lunarg commented on layers/gpu_validation/gpu_setup.cpp
> +            if (!strncmp(inst_shader_hash, reinterpret_cast<char *>(&shader_cache_hash), sizeof(shader_cache_hash))) {
yes, confirmed this was happening to me and so this is not working as intended

![image](https://github.com/KhronosGroup/Vulkan-ValidationLayers/assets/115671160/f90c7b72-e865-40b7-a9cd-0e8dfe74d859)

2024-05-17 03:35 UTC, spencer-lunarg requested changes
need to use `memcmp`

2024-05-17 06:43 UTC, arno-lunarg commented on layers/gpu_validation/gpu_setup.cpp
> +            if (!strncmp(inst_shader_hash, reinterpret_cast<char *>(&shader_cache_hash), sizeof(shader_cache_hash))) {
Oh yes good catch!

2024-05-17 06:54 UTC, arno-lunarg commented on layers/gpu_validation/gpu_setup.cpp
> +            if (!strncmp(inst_shader_hash, reinterpret_cast<char *>(&shader_cache_hash), sizeof(shader_cache_hash))) {
(before I was an actual string so `strncmp` usage was warranted)

2024-05-17 07:06 UTC, spencer-lunarg approved these changes

2024-05-17 09:15 UTC, merged