gpu: Fix push constants restore
KhronosGroup/Vulkan-ValidationLayers pull request #8149
Opened 2024-06-13 16:45 UTC by arno-lunarg

- Push constants state restoration was not working correctly
- Reworked the state tracking, also in best practices
- Added 2 tests, `RestorePushConstants` is not working on my PC, vertex shader runs correctly but no fragment are emitted when doing an indirect draw. Things work as expected when doing a normal draw. It is not related to GPU-AV, as disabling it does not solve the problem. My indirect buffer looks ok, so I will what CI tells me.

2024-06-13 17:05 UTC, spencer-lunarg commented on tests/unit/gpu_av_positive.cpp
> +}
I would add another test for push constant that mixes push constants for Compute and Graphics as that is a fun case we have no GPU-AV tests for

Have both push constant write data to Storage Buffer (different for compute and graphics) and make sure we didn't clobber the values by accident 

```c++
VkPipelineLayout layout_graphics; // VK_SHADER_STAGE_FRAGMENT_BIT
VkPipelineLayout layout_compute;  // VK_SHADER_STAGE_COMPUTE_BIT

// vkBeginCommandBuffer()
vkCmdBindPipeline(pipeline_graphics); // layout_graphics
vkCmdBindPipeline(pipeline_compute);  // layout_compute

vkCmdPushConstants(layout_graphics); // VK_SHADER_STAGE_FRAGMENT_BIT
vkCmdDraw();

vkCmdPushConstants(layout_compute); // VK_SHADER_STAGE_COMPUTE_BIT
vkCmdDispatch(); // valid
```

2024-06-13 17:05 UTC, spencer-lunarg commented on layers/state_tracker/state_tracker.cpp
> +    cb_state->push_constant_data_chunks.emplace_back(push_constant_data);
If I go

```c++
vkCmdPushConstants(offset: 0, size: 16, value = [0, 0, 0, 0]);
vkCmdDraw(); // values = [0, 0, 0, 0]

vkCmdPushConstants(offset: 4, size: 8, value = [1 ,1]);
vkCmdDraw(); // values = [0, 1, 1, 0]
```

you shuold be overriding the values, this seem like it will make 2 copies where the first is actually outdated

2024-06-13 17:13 UTC, arno-lunarg commented on layers/state_tracker/state_tracker.cpp
> +    cb_state->push_constant_data_chunks.emplace_back(push_constant_data);
it will indeed not override, but there is no need to take care of this case: when restoring, I will do the exact same 2 dispatches you describe since I lookup elements in `push_constant_data_chunks` from 0 to N

2024-06-13 17:13 UTC, arno-lunarg commented on tests/unit/gpu_av_positive.cpp
> +}
yes good test case!

2024-06-13 17:22 UTC, spencer-lunarg commented on layers/state_tracker/state_tracker.cpp
> +    cb_state->push_constant_data_chunks.emplace_back(push_constant_data);
1. This needs a `// comment`
2. I think this will work, the only downside is we will have to track every `vkCmdPushConstants` call made so **if** they call this 100 times in the same range, we are now tracking all that memory and have to transverse it.... I have zero knowledge how many times an app will update the `vkCmdPushConstants` for a given range, so for now happy with this approuch (but leave a comment explaining all of this for the sad soul who has to touch this code next after us 2 lol)

2024-06-14 08:13 UTC, arno-lunarg commented on layers/state_tracker/state_tracker.cpp
> +    cb_state->push_constant_data_chunks.emplace_back(push_constant_data);
A comment is welcome indeed.
Not to worried about not optimizing this, not doing the same call multiple times is probably more up to the application to avoid doing. And even with a 1000 elements, it is still a small number and traversing the vector should not be a problem.

2024-06-14 09:00 UTC, arno-lunarg commented on tests/unit/gpu_av_positive.cpp
> +}
Added it as `RestoreUserPushConstants2`

2024-06-14 14:40 UTC, spencer-lunarg commented on layers/best_practices/bp_state.h
> +    void UnbindResources() {}
why keep this?

2024-06-14 14:41 UTC, spencer-lunarg commented on layers/state_tracker/pipeline_layout_state.h
> +    const PushConstantRangesId push_constant_ranges_layout;
ping on answer for this

2024-06-14 16:50 UTC, arno-lunarg commented on layers/best_practices/bp_state.h
> +    void UnbindResources() {}
When I looked at the spot where `UnbindResources` is called, I felt that the logic was logic to call it or not was not easy to grasp, so I left this empty function to ease the process of adding such a function back if it is needed

2024-06-14 17:28 UTC, spencer-lunarg commented on layers/best_practices/bp_state.h
> +    void UnbindResources() {}
maybe a comment... this will be strange if I came across this in the future

even a `// todo - remove` type comment

2024-06-16 16:16 UTC, arno-lunarg commented on layers/best_practices/bp_state.h
> +    void UnbindResources() {}
done

2024-06-17 02:33 UTC, spencer-lunarg requested changes
I added the 3 positive test to ToT and ran and they pass

So I guess if we are marking this as a "clean up" then this would be ok, but we are claiming this "fixes" the push constant restore, yet we added no test to prove what this fixed (and prevent regression)

(otherwise this looks great and ready to approve and merge)

2024-06-17 08:51 UTC, arno-lunarg commented
> I added the 3 positive test to ToT and ran and they pass
> 
> So I guess if we are marking this as a "clean up" then this would be ok, but we are claiming this "fixes" the push constant restore, yet we added no test to prove what this fixed (and prevent regression)
> 
> (otherwise this looks great and ready to approve and merge)

The po

2024-06-17 16:44 UTC, merged