gpu: Fix maxBoundDescriptorSets logic
KhronosGroup/Vulkan-ValidationLayers pull request #8189
Opened 2024-06-24 20:58 UTC by spencer-lunarg

Was trying to solve https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7178 but first needed to improve the logic around `maxBoundDescriptorSets`

This unifies things between GPU-AV and DebugPrintF as well as adds proper testing to make sure things are working as expected

2024-06-24 20:59 UTC, spencer-lunarg commented on layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
> +    if (enabled[gpu_validation_reserve_binding_slot]) {
This was not currently working for Debug PrintF, but it should, and this is how we will soon be able to run both GPU-AV and DebugPrintF together!

2024-06-24 21:01 UTC, spencer-lunarg commented on layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
> +        // TODO - Should check descriptor set layout per-createInfoCount
this is what https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7178 is failing on, this PR was getting big, so going to try and fix this (and add many tests of course), but for now keeping as is and improving the error message (to not talk about pipelines)

2024-06-24 21:01 UTC, spencer-lunarg commented on layers/gpu/instrumentation/gpu_shader_instrumentor.h
> -    uint32_t adjusted_max_desc_sets_ = 0;
this was always `desc_set_bind_index_ + 1` and it got confusing having 2 variables to describe the basic same idea... `desc_set_bind_index_ + 1` is just as good and doesn't get confusing why we are using which

2024-06-24 21:02 UTC, spencer-lunarg commented on layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
> +        InternalWarning(device, record_obj.location, strm.str().c_str());
we were accidentally aborting here, this is a warning and all the new tests show that after we hit this, we will still be able to report an error the next time the user uses valid amount of sets

2024-06-25 07:45 UTC, arno-lunarg commented on layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
> +            << "Validation is not modifying the Pipeline Layout and instrumented SPIR-V are replaced with non-instrumented SPIR-V.";
The message should be update then, to clearly state that all pipelines created with the faulty layout will not be instrumented, but only those. Something like:
```suggestion
            << "pCreateInfo::setLayoutCount (" << chassis_state.modified_create_info.setLayoutCount
            << ") will conflicts with validation's descriptor set at slot " << desc_set_bind_index_ << ". "
            << "This pipeline layout will not allow GPU shader instrumentation to be setup for pipelines created with it, so no error error will be repored for them by GPU-AV."
```

2024-06-25 09:54 UTC, arno-lunarg approved these changes

2024-06-25 09:54 UTC, arno-lunarg commented on layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
> +                    "SPIR-V.";
```suggestion
                 << "GPU-AV will not report validation error for this Shader Object at runtime.";
```

2024-06-25 09:54 UTC, arno-lunarg commented on tests/unit/debug_printf.cpp
> +    TEST_DESCRIPTION("Reserve a descriptor slot and proceed to use them all anyway so debug printf can't");
```suggestion
    TEST_DESCRIPTION("Do not reserve a descriptor slot and proceed to use them all anyway so debug printf can't");
```

2024-06-25 10:01 UTC, arno-lunarg requested changes
[ RUN      ] NegativeDebugPrintf.UseAllDescriptorSlotsPipelineReserved
C:\Users\Arno\lunarg\Vulkan-ValidationLayers\tests\framework\error_monitor.cpp(210): error: Failed
**Self Validation Error**: [ VUID-VkValidationFeaturesEXT-pEnabledValidationFeatures-02967 ] | MessageID = 0x50c7f50b | vkCreateInstance(): pCreateInfo->pNext<VkValidationFeaturesEXT>.pEnabledValidationFeatures includes both VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT and VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT. The Vulkan spec states: If the pEnabledValidationFeatures array contains VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT, then it must also contain VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkValidationFeaturesEXT-pEnabledValidationFeatures-02967)

Our error message for `02967` is busted, I am fixing it now, but the validation logic seems correct, so it does not look like a false positive

2024-06-25 13:23 UTC, spencer-lunarg commented on layers/gpu/instrumentation/gpu_shader_instrumentor.cpp
> +            << "Validation is not modifying the Pipeline Layout and instrumented SPIR-V are replaced with non-instrumented SPIR-V.";
yep updated

2024-06-27 15:04 UTC, arno-lunarg approved these changes

2024-06-27 18:40 UTC, merged